### ISSUE TITLE
Modded paintings do not cycle

### ISSUE THREAD

**Issue by Arthree** [ricksouth/serilum-mc-mods#1002]
## **Information**
Minecraft version: 1.18.2
Modloader: Fabric
Fabric loader version: 0.13.3 / Fabric API 0.48.0
Environment: Singleplayer

Mod name: Cycle Paintings
Mod version: 2.1

## **Description**
When attempting to cycle paintings, only default minecraft paintings will cycle. Modded paintings (such as Macaw's or Dark Paintings) can be placed in the classic way (breaking the painting and replacing until you get one) but they do not cycle.

showRegisteredPaintingsDebug reports that only the minecraft paintings are registered.

## **Crash report**
It didn't crash, but here's the latest log.
[latest.log](https://github.com/ricksouth/serilum-mc-mods/files/8356237/latest.log)

**Comment by Farsinuce** [comment]
I am having the same issue. Also using [Macaw's](https://www.curseforge.com/minecraft/mc-mods/macaws-paintings).
Only vanilla MC paintings cycle.

Here's my console paste, when I try to cycle:
[https://controlc.com/2152ebaa](https://controlc.com/2152ebaa)

MC version 1.19
Fabric Loader 0.14.7 / Fabric API 0.56.0
Mod version 2.3

**Comment by Farsinuce** [comment]
**Update:**
Now also tested with [Dark Paintings](https://www.curseforge.com/minecraft/mc-mods/dark-paintings).
The issue seems to lie with [Cycle Paintings](https://www.curseforge.com/minecraft/mc-mods/cycle-paintings-fabric), @ricksouth

**Comment by Ryuushen** [comment]
Same Issue here still hasn't fixed

Macaw's Painting is incompatible and won't be cycle

**Comment by ricksouth** [comment]
This has been fixed in version 2.7 of Cycle Paintings. Thanks for giving the mod a try and opening the issue/placing comments! Apologies it took so long for me to get to.

https://www.curseforge.com/minecraft/mc-mods/cycle-paintings-fabric/files
