### ISSUE TITLE
mod is completely broken

### ISSUE THREAD

**Issue by Warbringer12** [ricksouth/serilum-mc-mods#1003]
## **Information**
Minecraft version: 1.16.5
Modloader: Forge 
Forge version: 36.2.33
Environment: Singleplayer 

Mod name: Mod
Mod version: 5.4

## **Description**
mob list doesn't work
commands don't show whether they worked or not

## **Crash report**
none

**Comment by James103** [comment]
1. Which mod are you exactly referring to in this issue?
2. Can you please post the full mod list?

**Comment by Warbringer12** [comment]
1. im referring to just mob heads
