### ISSUE TITLE
Adult mooshroom spawned when breeding cows

### ISSUE THREAD

**Issue by nivnarna** [ricksouth/serilum-mc-mods#1006]
I bred two regular cows and it resulted in an adult mooshroom (1.18.2)

**Comment by James103** [comment]
Which mod(s) are you referring to? Can you please post the full mod list?

**Comment by nivnarna** [comment]
Sorry I wasn't sure how to add a mod label

I have both mooshroon tweaks and mooshroom spawns but my guess is that it's
spawns

**Comment by ricksouth** [comment]
This has been fixed in the latest release of Mooshroom Spawn and Collective. Thanks for opening the bug report and giving the mod a try!

https://www.curseforge.com/minecraft/mc-mods/collective/files
https://www.curseforge.com/minecraft/mc-mods/mooshroom-spawn/files
