### ISSUE TITLE
Keep My Soil Tilled spreads modded farmland

### ISSUE THREAD

**Issue by Arthree** [ricksouth/serilum-mc-mods#1007]
## **Information**
Minecraft version: 1.18.2
Modloader: Fabric
Fabric loader version: 0.13.3
Environment: Singleplayer

Mod name: Keep My Soil Tilled (Fabric)
Mod version: keepmysoiltilled-fabric_1.18.x-1.0.jar

## **Description**
When a pumpkin or melon (stem) is planted on modded farmland (e.g., Fertilized Soil from Farming for Blockheads), KMST will create the same type of farmland under the melon/pumpkin block when harvested.

The Farming for Blockheads soil is particularly problematic because there is currently a bug (in FFB) that prevents melons/pumpkins from growing on the fertilized soil. I.e., after harvesting the melon/pumpkin once, it will never be able to grow in the same spot again until the fertilized soil is replaced with some other kind of valid melon/pumpkin soil block.

Additionally, modded farmland (which may be expensive, rare, or hard to create) can be duplicated/spread infinitely (albeit very slowly) by growing melons/pumpkins on a single block and spreading it with this mod.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! I've made it so that the farmland that is being created will always be the vanilla farmland in version 1.6 of Keep My Soil Tilled. This should fix the problem.

https://www.curseforge.com/minecraft/mc-mods/keep-my-soil-tilled-fabric/files
