### ISSUE TITLE
Fence Gates Maker no sound when activated by pressure plate

### ISSUE THREAD

**Issue by JKachele** [ricksouth/serilum-mc-mods#1010]
## **Information**
Minecraft version: 1.18.2
Modloader: Fabric
Fabric loader version: 1.13.3
Environment: Singleplayer

Mod name: Double Doors
Mod version: 3.3

## **Description**
Whenever fence gates are opened with a pressure plate the gates make no sound. Opening them by hand works fine. This occurs with all fence gates and and all pressure plates.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 4.3 of Double Doors.

https://www.curseforge.com/minecraft/mc-mods/double-doors/files
