### ISSUE TITLE
Elytra Take off with firework crash

### ISSUE THREAD

**Issue by Keaft** [ricksouth/serilum-mc-mods#1013]
## **Information**
Minecraft version: 1.12.2
Modloader: Forge
Forge version: 14.23.5.2859
Environment: Singleplayer & Multiplayer

Easy Elytra Take Off
![image](https://user-images.githubusercontent.com/68153/160606664-726c18d3-89e9-417f-b24c-ba596d08a097.png)

## **Description**
I've been running a modpack on my server and have this crash from time to time. I've boiled down ~250 mods to those 2 in the picture. 

Equip a normal vanilla Elytra on your back and grab some fireworks. In either survival or creative (though creative provides the easiest testing) spam take off until it crashes. It's extraordinarily random at times. Sometimes it'll crash immediately and sometimes it requires a restart. If it doesn't crash after 50+ take offs, try restarting Minecraft. It breaks on both my personal computer in single player and server machine in multiplayer so hopefully this should be replicatable.

From the crash report it appears that the vanilla entity tracker is being fed a null value, but seems to be only occasionally.

## **Crash report**
[crash-2022-03-29_05.59.19-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/8371163/crash-2022-03-29_05.59.19-server.txt)

**Comment by James103** [comment]
Does this occur when Minecraft, Forge, Collective, and Easy Elytra Takeoff is installed for a newer version (such as 1.16)?

**Comment by Keaft** [comment]
My issue is with 1.12.2 and I have not opened a test environment for later versions.

**Comment by ricksouth** [comment]
Unfortunately I no longer support the 1.12.2 version, the code base is just too different. Apologies for any inconvenience. Thanks for giving the mod a try though!
