### ISSUE TITLE
GUI Clock doesn't show correct ingame time

### ISSUE THREAD

**Issue by LeivurGargiulo** [ricksouth/serilum-mc-mods#1014]
## **Information**
Minecraft version: 1.12.2
Modloader: Forge
Forge version: 14.23.5.2860
Environment: Singleplayer

Mod name: GUI Clock
Mod version: 3.0

## **Description**
The mod GUI Clock does not show ingame time correctly.

Screenshot:
https://paste.pics/5aaa2a6e6e74d6cc9d8c5d32a0043471

**Comment by James103** [comment]
Can you please post the full mod list?

---
Moved screenshot to Github storage as images stored on paste.pics may expire.
https://user-images.githubusercontent.com/37945304/160725396-cf4bfc7c-d5bf-41c5-bdac-bc8dd9084694.png

FYI: Paste an image while typing a comment on GitHub to upload and embed it.

**Comment by LeivurGargiulo** [comment]
Thank you for the tip! I am new to GitHub.

Mod List:
FoamFixCore 7.7.4
RandomPatches 1.12.2-1.22.1.10
AppleSkin 1.0.14
Quark r1.6-177
AutoRegLib 1.3-32
Bad Wither No Cookie! Reloaded 1.12.2-3.4.18
Blur 1.0.4-14
Client Tweaks 3.1.11
Clumps 3.1.2
Ding 1.12.2-1.0.2
Fast Leaf Decay v14
FoamFix 0.10.14-1.12.2
Gravestone mod 1.10.3
Invwentory Tweaks 1.63+release.109.220f
JourneyMap 1.12.2-5.7.1
Just Another Rotten Flesh to Leather Mod 1.1
Mouse Tweaks 2.10.1
Neat 1.4-17
NetherPortalFix 5.3.17
Placebo 1.12.2-1.6.0
SlimeMod (SSP) 1.12-2.1
SwingThroughGrass 1.12.2-1.2.3
Toast Control 1.12.2-1.8.1
Village Info (SSP) 1.12-2.1
WAIM 1.0.0
Collective 1.12.2-3.0
GUI Clock 1.12.2-3.0
GUI Compass 1.12.2-1.5

.

**Comment by ricksouth** [comment]
Unfortunately I no longer support 1.12.2. If the problem persists in 1.16+ please let me know. Apologies for the inconvenience.
