### ISSUE TITLE
Welcome Message sends message when changing dimensions

### ISSUE THREAD

**Issue by spoorn** [ricksouth/serilum-mc-mods#1018]
## **Information**
Minecraft version: 1.18.2
Modloader: Fabric
Fabric loader version: 0.13.3
Environment: Multiplayer

Mod name: Welcome Message (Fabric)
Mod version: 1.0

## **Description**
The welcome message is sent to players whenever they change dimensions

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 1.7 of Welcome Message.

https://www.curseforge.com/minecraft/mc-mods/welcome-message-fabric/files
