### ISSUE TITLE
Crash with Just Mob Heads

### ISSUE THREAD

**Issue by BaccarWozat** [ricksouth/serilum-mc-mods#1021]
## **Information**
Minecraft version: 22w14a (1.19 snapshot)
Modloader: Fabric
Fabric loader version: 0.13.3
Environment: Singleplayer

Mod name: Just Mob Heads (1.19.x)
Mod version: 5.4
Also: Collective 4.26

## **Description**
Was sailing along, approached a village on the shore, when suddenly the game crashed. Something about a ticking entity? 
Edit: It seems it was just as a raid was starting, maybe that has something to do with it.

## **Crash report**
[https://paste.ee/p/vbl4Z](https://paste.ee/p/vbl4Z)

**Comment by BaccarWozat** [comment]
Crash report if paste.ee link expired:
[log.txt](https://github.com/ricksouth/serilum-mc-mods/files/8548467/log.txt)

**Comment by ricksouth** [comment]
This should be fixed in the latest 1.19 release. Apologies for the late reply!
