### ISSUE TITLE
Crash with Tree Harvester

### ISSUE THREAD

**Issue by BaccarWozat** [ricksouth/serilum-mc-mods#1022]
## **Information**
Minecraft version: 22w14a (1.19 snapshot)
Modloader: Fabric
Fabric loader version: 0.13.3
Environment: Singleplayer

Mod name: Tree Harvester (1.19.x)
Mod version: 5.1
Also: Collective 4.26

## **Description**
Crash when attempted to use a stone axe on a birch tree. "Exception in server tick loop"

## **Crash report**
[https://paste.ee/p/1PBsk](https://paste.ee/p/1PBsk)

**Comment by BaccarWozat** [comment]
Crash report if paste.ee link expired:
[log.txt](https://github.com/ricksouth/serilum-mc-mods/files/8548465/log.txt)

**Comment by ricksouth** [comment]
This should be fixed in the latest 1.19 release. Apologies for the late reply!
