### ISSUE TITLE
Dragon egg

### ISSUE THREAD

**Issue by mirra78** [ricksouth/serilum-mc-mods#1027]
the dragon does not drop an egg after killing it for the second time and other times i kill it :(
please help. i'm using the 1.18.1 minecraft version. also tried the 1.18.2 version of the mod and i have the same problem.

**Comment by James103** [comment]
Which mod(s) are you referring to?

**Comment by mirra78** [comment]
End Portal Recipe (Forge)

**Comment by mirra78** [comment]
any help please?

**Comment by ricksouth** [comment]
Thanks for giving the mod a try and opening the issue! I have added an extra check in version 4.0 of End Portal Recipe to find players around if the last damage to the dragon wasn't by a player. This should fix the problem you were having. Apologies it took so long to get to.

https://www.curseforge.com/minecraft/mc-mods/end-portal-recipe
