### ISSUE TITLE
Crash on world load with Realistic Bees

### ISSUE THREAD

**Issue by brisingraerowing** [ricksouth/serilum-mc-mods#1029]
## **Information**
Minecraft version: 1.16.5
Modloader: Forge
Forge version: 36.2.31
Environment: Singleplayer

Mod name: Realistic Bees
Mod version: 2.5

## **Description**
Crash on world load.

## **Crash report**
https://bytebin.lucko.me/A8mxfipIGn

**Comment by James103** [comment]
Converted paste to text file as pastes stored on the website may expire.
[crash.txt](https://github.com/ricksouth/serilum-mc-mods/files/8483797/crash.txt)

**Comment by ricksouth** [comment]
This has been fixed in the latest version Realistic Bees. Thanks for opening the issue and giving the mod a try!

https://www.curseforge.com/minecraft/mc-mods/realistic-bees/files
