### ISSUE TITLE
Can't connect to official server

### ISSUE THREAD

**Issue by GoldenFurredFox** [ricksouth/serilum-mc-mods#1030]
## **Information**
Minecraft version: 1.18.2
Modloader: Forge
Forge version: 40.0.18
Environment: Multiplayer

Mod name: The Vanilla Experience
Mod version: 5.10

## **Question**
Why do I get the below error when trying to connect to the official server's IP from DesiredServers?
![image](https://user-images.githubusercontent.com/28793227/163263362-ef365127-c9f8-460e-a3ef-9d463f51920b.png)

**Comment by ricksouth** [comment]
At the moment the official server is offline, I haven't been able to manage it lately. I'll take a look at it soon, thanks for the interest!
