### ISSUE TITLE
Odd Language clash crash between Hammerlib and HOYI

### ISSUE THREAD

**Issue by border999** [ricksouth/serilum-mc-mods#1032]
Minecraft version: 1.18.2
Modloader: Forge
Forge version: 40.0.52 
Singleplayer

Mod name: Hand Over Your Items
Mod version: 1.4
Hammerlib version: 18.2.15
## **Description**
Hey! This happened..

## **Crash report**
(https://gist.github.com/border999/45e43775024bafdbd069ad293773462e)

**Comment by border999** [comment]
https://github.com/dragon-forge/HammerLib/issues/8

**Comment by border999** [comment]
made this issue on both sides seeing as it's when the two mods are together, even if they are the only mods, an odd crash occurs.

**Comment by ricksouth** [comment]
I couldn't find any information referencing Hand Over Your Items, so I don't think I can fix this on my end. I have however just uploaded version 2.0 which might fix the problem indirectly. I do see Hammerlib referenced in the crash log. Thanks for giving the mod a try!

https://curseforge.com/minecraft/mc-mods/hand-over-your-items
