### ISSUE TITLE
High / double flowers do not work

### ISSUE THREAD

**Issue by ArturilloD** [ricksouth/serilum-mc-mods#1033]
## **Information**
Minecraft version: 1.16.5
Modloader: Forge
Forge version: 36.2.20
Environment: Singleplayer

Mod name: Random Bone Meal Flowers
Mod version: 1.4

## **Description**
Good evening, I installed the mod and tried to change some things in the Blacklist configuration file. There I added high flowers that were missing vanilla and the high flowers and the mushrooms of the Botania, for some reason none of them is generated. I hope you can help me with this, thank you very much

## **Crash report**
If available.

**Comment by ricksouth** [comment]
Having thought about it a bit more, this is actually intended behaviour. It replaces flowers similar to the ones that spawn. Big flowers or mushrooms aren't something that I think fit in that category. Thanks for giving the mod a try though!
