### ISSUE TITLE
Passive Shields crash 1.18.1

### ISSUE THREAD

**Issue by MidasMischief** [ricksouth/serilum-mc-mods#1034]
## **Information**
Minecraft version: 1.18.1
Modloader: Fabric
Fabric loader version: 0.13.3
Environment: Singleplayer

Mod name: Passive Shields
Mod version: 2.0

## **Description**
Mod appears to not work in 1.18.1, asks for the latest version of collective despite having it installed.

## **Crash report**
A potential solution has been determined:
Replace mod 'Collective (Fabric)' (collective-fabric) 4.9 with version 4.18 or later.

Unmet dependency listing:
Mod 'Passive Shield (Fabric)' (passiveshield-fabric) 2.0 requires version 4.18 or later of mod 'Collective (Fabric)'<br>(collective-fabric), but only the wrong version is present: 4.9!

**Comment by ricksouth** [comment]
Thanks for the interest. Please update to Minecraft 1.18.2 to use the latest version of this mod.
