### ISSUE TITLE
Ticking Entity Crashing Server

### ISSUE THREAD

**Issue by DarkkRevenant** [ricksouth/serilum-mc-mods#1038]
## **Information**
Minecraft version: 1.18.2
Modloader: Forge
Forge version: 40.0.52
Environment: Multiplayer

Mod name: Villager Names
Mod version: 1.18.2-3.5

## **Description**
Cause an issue in a server which lead to a ticking entity. Upon entering the chunk where this entity is located, the server will crash.

## **Crash report**
https://pastebin.com/wpKzpr1t

**Comment by ricksouth** [comment]
Unfortunately due to me getting to this late, the paste has expired. Quite a lot of code has been changed in the latest version. If you're still experiencing issues, please let me know. Thanks for giving the mod a try!

https://www.curseforge.com/minecraft/mc-mods/villager-names/files
