### ISSUE TITLE
Crash with Your Items Are Safe, with BigInv

### ISSUE THREAD

**Issue by BaccarWozat** [ricksouth/serilum-mc-mods#1042]
## **Information**
Minecraft version: 22w16b
Modloader: Fabric
Fabric loader version: 0.14.1
Environment: Singleplayer

Mod name: Your Items Are Safe
Mod version: 1.1
Other mod involved: BigInv 0.1.1
https://github.com/SollyW/BigInv/releases (sorry, not on Curseforge or Modrinth)

## **Description**
Crashed upon killed with a full 108-slot inventory (which BigInv adds); obviously YIAS isn't going to know what to do with the extra 72 slots of stuff. Perhaps a message that says "[YIAS] was unable to save all of your items"? It would take 5 chests to store everything (including armor, offhand item and player head).

Workaround, of course, is to not use one of these mods.

## **Crash report**
https://paste.ee/p/iEpga

**Comment by James103** [comment]
Converted paste to text file (containing log and crash report) as logs uploaded to paste.ee have an expiration date.
[log.txt](https://github.com/ricksouth/serilum-mc-mods/files/8546103/log.txt)

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! I've added a fix in version 2.0 of Your Items Are Safe which prevents the mod from crashing. Anything above the space in the 2 chests will drop to the floor instead. There is too much hardcoded in the game for such a mod to work reliably. This way they'll at least play nice together.

https://www.curseforge.com/minecraft/mc-mods/your-items-are-safe-fabric
