### ISSUE TITLE
Prevents totem of undying to work

### ISSUE THREAD

**Issue by YumatanGames** [ricksouth/serilum-mc-mods#1043]
So, it seems this mod prevents the Totem of Undying from working by being activated first. What my tests suggest is that if you have all the items needed to create a chest and armor stand, the mod then takes the totem from you hand just before it can actually activate, and then you die. 

Maybe you could make the mod ignore the totem of undying when saving your items, or maybe to create a delay, just long enough to allow the totem enough time to work... I don't know...

**Comment by James103** [comment]
Which mod are you referring to? I assume it's "Your Items are Safe".

**Comment by YumatanGames** [comment]
Yes, that's correct. I just clicked on report issue within CurseForge and assumed I was directed to that specific mod. Sorry for that.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 2.0 of Your Items Are Safe. Apologies it took so long for me to get to.

https://www.curseforge.com/minecraft/mc-mods/your-items-are-safe
