### ISSUE TITLE
Love the Tiny Bees but....

### ISSUE THREAD

**Issue by ZeroOaths** [ricksouth/serilum-mc-mods#1045]
## **Information**

Minecraft version: 1.18.1
Modloader: Forge
Forge version: 39.1.0
Environment: Singleplayer / Multiplayer

Mod name: Realistic Bees
Mod version: 2.5

## **Question**
could the 1.18.1 version of this mod get an update to 2.5 for the increased hive limit of bees? I'd rather update to 1.18.2 but the mods I use for my modpack and server aren't all up to date yet so instead I'm brought to asking about a update.

Oh, and I guess one other thing, can I change the custom model/texture used by the mod to instead use one from a resource pack and still edit the bee size? I've tried changing the size of models myself but that didn't help at all.

**Comment by ricksouth** [comment]
Unfortunately I always use the latest Minecraft version to release mods for, to reduce the time spent on subversions. I appreciate the interest though!
