### ISSUE TITLE
[Beautified Chat [Server] (Forge)] Error in description on mod page and mod itself (low priority)

### ISSUE THREAD

**Issue by Maypul** [ricksouth/serilum-mc-mods#1047]
## **Information**
Minecraft version: 1.18.2
Modloader: Forge 
Forge version: N/A
Environment: Singleplayer / Multiplayer

Mod name: Mod
Mod version: x.x

## **Description**
chatMessageFormat (default = "%timestamp% | %username%: %chatmessage%"): Variables: %timestamp% = timestamp set in timestampFormat. %username% = the username of the player who sent the message. %username% = the username of who sent the message.

As shown above, description of feature doubles %username% twice where, I think, the correct description should should be for '%chatmessage%'

## **Crash report**
N/A

**Comment by ricksouth** [comment]
Appreciate you letting me know, fixed! :)
