### ISSUE TITLE
Allow this mod and village spawn point to work together

### ISSUE THREAD

**Issue by Jetpack-Cat** [ricksouth/serilum-mc-mods#1048]
forge 1.16.5
i'm trying to spawn 220 blocks above a village, replacing x and y with ~ just crash the game. Village spawn point doesn't allow you to offset x y and z values

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 2.5 of Set World Spawn Point.

https://www.curseforge.com/minecraft/mc-mods/set-world-spawn-point/files
