### ISSUE TITLE
Allow x y and z offset. 

### ISSUE THREAD

**Issue by Jetpack-Cat** [ricksouth/serilum-mc-mods#1049]
forge 1.16.5

i'm trying to spawn players 220 blocks above a village, your mods set world spawn and village spawn point don't work together, could you add an adjustable offset to village spawn point?

**Comment by James103** [comment]
Duplicate of #1048

This issue tracker is for all of @ricksouth's mods. To keep things organized, there is one issue tracker for all the dozens of mods he has made. In this case, this and #1048 would both apply to the mods "Village Spawn Point" and "Set World Spawn".
