### ISSUE TITLE
22w17a Crash with Collective!

### ISSUE THREAD

**Issue by BaccarWozat** [ricksouth/serilum-mc-mods#1052]
## **Information**
Minecraft version: (1.19 snapshot) 22w17a
Modloader: Fabric
Fabric loader version: 0.14.3
Environment: Singleplayer

Mod name: Collective
Mod version: 4.26
Also: Fabric API 0.51.3

## **Description**
Crash before title screen. No other mods involved (Fabric API excepted). Works without it.

## **Crash report**
[crash-2022-04-27_19.01.53-client.txt](https://github.com/ricksouth/serilum-mc-mods/files/8578540/crash-2022-04-27_19.01.53-client.txt)

## **Analysis**
I suspect it has something to do with the new chat encryption that is required even in singleplayer.

**Comment by BaccarWozat** [comment]
Well there's 1.19 and a new Collective so I guess it isn't a problem anymore. Thanks for all you do to keep this thing going!

**Comment by ricksouth** [comment]
Appreciate the support! Been working on a DIY project for the past few weeks but of course had to make time to update to the new release. Glad you like the mods :)
