### ISSUE TITLE
CollectivePlayerEvents.ON_PLAYER_DIG_SPEED_CALC doesn't seem to be working.

### ISSUE THREAD

**Issue by dragonmaus** [ricksouth/serilum-mc-mods#1053]
## **Information**
Minecraft version: 1.18.2
Modloader: Fabric
Fabric loader version: 0.13.3
Environment: Multiplayer

Mod name: Collective (affects Tree Harvester and Hoe Tweaks, and possibly others)
Mod version: 4.26

## **Description**
I was testing out Tree Harvester and Hoe Tweaks, and noticed that neither mod was having any impact on mining speed (logs for Tree Harvester, melons/pumpkins for Hoe Tweaks). It looks like both mods use the `CollectivePlayerEvents.ON_PLAYER_DIG_SPEED_CALC` callback to implement this functionality, so I'm submitting the issue against Collective.

I haven't seen anything useful in the logs; hopefully it isn't too difficult to track down what's wrong.

**Comment by ricksouth** [comment]
This has been fixed in the latest version of Collective. Thanks for opening the issue!

https://www.curseforge.com/minecraft/mc-mods/collective/files
