### ISSUE TITLE
IncreaseHarvestingTimePerLog doesn't seem to work

### ISSUE THREAD

**Issue by Some-Doofus** [ricksouth/serilum-mc-mods#1055]
## **Information**
Minecraft version: 1.18.2
Modloader: Fabric
Fabric loader version: 0.13.3
Environment: Singleplayer

Mod name: Tree Harvester
Mod version: 5.1

After trying multiple different values for IncreaseHarvestingTimePerLogMultiplier in the config file, including very large and very small values, it seems the config actually has no effect. IncreaseHarvestingTimePerLog is set to True so it should be working but no matter the size of the tree or value set in the config every tree breaks as fast as one log. This issue makes me not want to use the mod as tree harvesting becomes much too fast and easy. If there isn't already a default value set, the default value for time taken to fell a tree should be the same as if you were to break every block, but I assume this is meant to be true already but it is just bugged.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 6.48 of Collective. Tree Harvester doesn't need an update. Apologies it took so long to get to.

https://www.curseforge.com/minecraft/mc-mods/collective/files
