### ISSUE TITLE
Bigger Sponge Absorption Radius mod doesn't work with your other mods

### ISSUE THREAD

**Issue by MoreLemonPledge** [ricksouth/serilum-mc-mods#1058]
## **Information**
Minecraft version: 1.18.2
Modloader: Forge
Forge version: 40.1.0
Environment: Singleplayer

Mod name: Bigger Sponge Absorption Radius
Mod version: 2.0
Collective: 4.25

Currently I have 13 total mods and use 6 of yours (including collective) Bigger sponge, Double Doors, Infinite Trading, More Zombie Villagers and finally Tree Harvester. Bigger sponge was working fine on version 1.18.1. Now being on version 1.18.2 it has stopped working. I have found out through trial and error that if I remove your other 5 mods and keep just bigger sponge and collective that it works just as intended, but when I put back any of the 5 mods, bigger sponge stops working. I hope I have explained in plenty detail for you but if you need any more information I will happily provide it to you to the best of my knowledge, Thank you!

## **Crash report**
None.

**Comment by ricksouth** [comment]
This has been fixed in the latest release of Bigger Sponge Absorption Radius. Thanks for opening the issue and giving some of my mods a try!

https://www.curseforge.com/minecraft/mc-mods/bigger-sponge-absorption-radius/files
