### ISSUE TITLE
Getting the "mods from incorrect sources" after downloading them from Serilum's curseforge. (1.18.2)

### ISSUE THREAD

**Issue by SpookLass** [ricksouth/serilum-mc-mods#1059]
## **Information**
Minecraft version: 1.18.2
Modloader:  Fabric
Fabric loader version: 0.13.3
Environment: Singleplayer

Mod name: Collective + Giant Spawn
Mod version: 4.26 (Collective) and 2.7 (Giant Spawn)

## **Description**
The "mods from incorrect sources" message came up when loading the world, despite the mods being downloaded from the correct sources. 
https://www.curseforge.com/minecraft/mc-mods/collective-fabric
https://www.curseforge.com/minecraft/mc-mods/giant-spawn-fabric
It only happened once though, so many it's just a strange one-time thing? Either way, it's rather odd.
It likely doesn't need fixing, as it's minor, but I figured I may as well document it.

**Comment by ricksouth** [comment]
A little late, but do you have a screenshot of the instance's mod folder? With the jar names?

**Comment by SpookLad** [comment]
Here. Sorry I'm also a little late, I don't check Gmail often. I'm assuming that the check to make sure they're from the right sources depends on their names? I usually change the names of all of the mods in my modpack to keep it nice and consistent, although at that time I was leaving the version number out of the name for some reason.
![Screenshot (90)](https://user-images.githubusercontent.com/83087893/180674828-e7f89388-0074-4d54-9266-f200edd17c27.png)

**Comment by ricksouth** [comment]
This indeed has to do with renaming the files. The message will only be shown once if you do rename them, and the check won't be done again. Sorry for the inconvenience, it's a rough way to prevent certain mod rehosting websites. Thanks for downloading from CurseForge :)
