### ISSUE TITLE
Backport to 1.12.2

### ISSUE THREAD

**Issue by Delfite** [ricksouth/serilum-mc-mods#1066]
## **Information**
Mod name: Full Brightness Toggle (Forge)

## **Feature description**
I know 1.12.2 isn't a "maintained version" anymore despite there being quite a few mods still being updated for it, but being able to enable and disable pseudo-night vision on command is really nice to have no matter the version, especially since there aren't any mods that add such a simple thing for a standalone mod which is mildly upsetting to me.

I wouldn't imagine this being difficult to do since setting the game's gamma value really high up probably does the same thing for *almost* every version.

**Comment by ricksouth** [comment]
This mod should be compatible with 1.12.2: https://www.curseforge.com/minecraft/mc-mods/fullbright
I'm not actively developing for the version anymore unfortunately. But thanks for the interest!
