### ISSUE TITLE
Mod prevents totem of undying from working

### ISSUE THREAD

**Issue by frihi** [ricksouth/serilum-mc-mods#1068]
## **Information**
Minecraft version: 1.18.2
Modloader: Fabric
Fabric loader version: 0.14.5
Environment: Singleplayer / Multiplayer

Mod name: Your items are safe
Mod version: 1.18.x-1.1

## **Description**
When a player dies while holding a totem of undying, the totem gets placed on the armor stand/chest and the player dies anyways.

**Comment by James103** [comment]
See also #1043

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 2.0 of Your Items Are Safe. Apologies it took so long for me to get to.

https://www.curseforge.com/minecraft/mc-mods/your-items-are-safe-fabric
