### ISSUE TITLE
Trading Locks

### ISSUE THREAD

**Issue by davisjoel23** [ricksouth/serilum-mc-mods#1069]
## **Information**
Minecraft version: 1.18.2
Modloader: Fabric 0.14.4
Fabric loader version 0.14.4
Environment: Singleplayer

Mod name: Infinite Trading
Mod version: 1.18

## **Description**
The mod isn't working. The traders still lock up. It was working for a short while until I logged out and logged back in. I am playing on the mod pack Valhesia Enhanced Vanilla.

## **Crash report**
If available.

**Comment by ricksouth** [comment]
This has been fixed in version 3.0 of Infinite Trading. It has completely been rewritten. How the offers are reset has changed and it now accounts for demand correctly. Thanks for giving the mod a try and opening the issue!

https://www.curseforge.com/minecraft/mc-mods/infinite-trading-fabric/
