### ISSUE TITLE
I have a Idea for older versions

### ISSUE THREAD

**Issue by MangoYT567** [ricksouth/serilum-mc-mods#1073]
## **Information**
Mod name: Areas

## **Feature description**
If you can make the Areas Mod into versions 1.12 because I am looking forward to use the mod in a map but it is only supported later then version 1.12 if you can make the mod for a older version that would be great, hopefully it is possible.

**Comment by ricksouth** [comment]
Unfortunately I don't actively develop for 1.12 anymore. Thanks for the interest though!
