### ISSUE TITLE
Double Doors (Forge): Redstone logic

### ISSUE THREAD

**Issue by Nick1st** [ricksouth/serilum-mc-mods#1080]
## **Information**
Mod name: Double Doors (Forge)

## **Feature description**
Please fix redstone logic, it's very inconsistent. (Build a double door , place a block to the side of the upper half, put a button on top of that block, click the button)

Expected behavior: Opening both doors
What happens: Only the door directly attached opens

This also happens in other cases where redstone is involved

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 4.3 of Double Doors.

https://www.curseforge.com/minecraft/mc-mods/double-doors/files
