### ISSUE TITLE
Webs

### ISSUE THREAD

**Issue by vlad8599** [ricksouth/serilum-mc-mods#1081]
## **Information**
Minecraft version: 1.18.2
Modloader: Fabric
Fabric loader version: 0.14.6
Environment: Singleplayer / Multiplayer

Mod name: Spiders produce webs
Mod version: 1.5

## **Description**
I have delay 600 tics in config and normal(32 blocks) maximum distance, but... spiders just dont want produce web. Why?

## **Crash report**
No crash.

**Comment by ricksouth** [comment]
I can't reproduce this locally. The mod has to be installed on the server, for spiders to produce webs. 600 ticks means every 30 seconds. Please let me know if the issue persists. Thanks for giving the mod a try!
