### ISSUE TITLE
Nether portal spread incorrectly spreads nether for mods that inherit NetherPortalBlock

### ISSUE THREAD

**Issue by SimonMeskens** [ricksouth/serilum-mc-mods#1085]
## **Information**
Minecraft version: 1.18.2
Modloader: Forge
Forge version: 40.1.25
Environment: Singleplayer / Multiplayer

Mod name: Nether Portal Spread
Mod version: 2.5.7

Per title, mods like Blue Skies that have custom portals that inherit from NetherPortalBlock will trigger nether portal spread. If I may be so bold, it's probably better to use a tag instead of `instanceof`.

**Comment by Jadan1213** [comment]
I'm seeing this issue as well in 1.20.1, is it possible to disable the spread for non nether portals??

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 8.0 of Nether Portal Spread. Apologies it took so long for me to get to.

https://curseforge.com/minecraft/mc-mods/nether-portal-spread/files
