### ISSUE TITLE
Random Bone Meal Flowers Blacklist not working

### ISSUE THREAD

**Issue by JaxckLl** [ricksouth/serilum-mc-mods#1088]
## **Information**
Minecraft version: xx.xx.xx
Modloader: Forge / Fabric
Forge version: xx.xx.xx  OR  Fabric loader version: x.xx.x
Environment: Singleplayer / Multiplayer

Mod name: Random Bone Meal Flowers
Mod version: x.x

## **Description**
RBM Flowers is still causing any & all flowers to generate, regardless of blacklist. With Botania, I’m getting more functional flora than vanilla MC petals…

Secondary issue,
When bone mealing, grass & flowers are generated normally. After a moment, all the flowers are replaced ignoring the blacklist.

Can/will update further with additional Forge version & mod version info

## **Crash report**
No crash, just odd behaviour.

**Comment by jtenner** [comment]
I can confirm this is an issue. Please fix.

**Comment by ricksouth** [comment]
This should be fixed in version 3.0 of Random Bone Meal Flowers. Please let me know if you're still experiencing issues. Thanks for giving the mod a try and opening the issue!

https://www.curseforge.com/minecraft/mc-mods/random-bone-meal-flowers/files

**Comment by Lucipo** [comment]
issue is not fixed, here is the blacklist file that blocks all botania flowers for the latest version. Just paste into your blacklist file wherever needed. Make sure to include the correct comma placement.

!botania:labellia,
!botania:tigerseye,
!botania:vinculotus,
!botania:spectranthemum,
!botania:tangleberrie,
!botania:solegnolia,
!botania:rannuncarpus,
!botania:pollidisiac,
!botania:orechid_ignem,
!botania:orechid,
!botania:medumone,
!botania:marimorphosis,
!botania:loonium,
!botania:jiyuulia,
!botania:jaded_amaranthus,
!botania:hyacidus,
!botania:hopperhock,
!botania:heisei_dream,
!botania:fallen_kanade,
!botania:exoflame,
!botania:dreadthorne,
!botania:daffomill,
!botania:clayconia,
!botania:bubbell,
!botania:bubbell_chibi,
!botania:bellethorn,
!botania:agricarnation,
!botania:bergamute,
!botania:thermalily,
!botania:spectrolus,
!botania:shulk_me_not,
!botania:rosa_arcana,
!botania:rafflowsia,
!botania:narslimmus,
!botania:munchdew,
!botania:kekimurus,
!botania:hydroangeas,
!botania:gourmaryllis,
!botania:entropinnyum,
!botania:endoflame,
!botania:dandelifeon,
!botania:light_blue_shiny_flower,
!botania:pink_shiny_flower,
!botania:blue_mystical_flower,
!botania:purple_mystical_flower,
!botania:gray_shiny_flower,
!botania:light_gray_shiny_flower,
!botania:cyan_shiny_flower,
!botania:yellow_double_flower,
!botania:light_blue_double_flower,
!botania:magenta_double_flower,
!botania:purple_double_flower,
!botania:blue_double_flower,
!botania:blue_mushroom,
!botania:purple_shiny_flower,
!botania:green_mushroom,
!botania:green_double_flower,
!botania:brown_double_flower,
!botania:pink_double_flower,
!botania:gray_double_flower,
!botania:light_gray_double_flower,
!botania:cyan_double_flower,
!botania:lime_double_flower,
!botania:black_double_flower,
!botania:orange_double_flower,
!botania:light_gray_mushroom,
!botania:cyan_mushroom,
!botania:purple_mushroom,
!botania:red_double_flower,
!botania:brown_mushroom,
!botania:black_mushroom,
!botania:red_mushroom,
!botania:gray_mushroom,
!botania:white_double_flower,
!botania:lime_mushroom,
!botania:pink_mushroom,
!botania:yellow_mushroom,
!botania:light_blue_mushroom,
!botania:magenta_mushroom,
!botania:orange_mushroom,
!botania:white_mushroom,
!botania:black_shiny_flower,
!botania:green_shiny_flower,
!botania:brown_shiny_flower,
!botania:blue_shiny_flower,
!botania:white_mystical_flower,
!botania:orange_mystical_flower,
!botania:magenta_shiny_flower,
!botania:light_blue_mystical_flower,
!botania:yellow_mystical_flower,
!botania:pink_mystical_flower,
!botania:lime_mystical_flower,
!botania:gray_mystical_flower,
!botania:light_gray_mystical_flower,
!botania:orange_shiny_flower,
!botania:white_shiny_flower,
!botania:black_mystical_flower,
!botania:red_mystical_flower,
!botania:green_mystical_flower,
!botania:brown_mystical_flower,
!botania:cyan_mystical_flower,
!botania:magenta_mystical_flower,
!botania:cyan_mystical_flower,
!botania:marimorphosis_chibi,
!botania:jiyuulia_chibi,
!botania:yellow_shiny_flower,
!botania:lime_shiny_flower,
!botania:bellethorn_chibi,
!botania:clayconia_chibi,
!botania:agricarnation_chibi,
!botania:daybloom_motif,
!botania:pure_daisy,
!botania:manastar,
!botania:rannuncarpus_chibi,
!botania:hydroangeas_motif,
!botania:dreadthorn,
!botania:red_shiny_flower,
!botania:tangleberrie_chibi,
!botania:solegnolia_chibi,
!botania:nightshade_motif,
!botania:hopperhock_chibi

**Comment by ricksouth** [comment]
This has (finally) been fixed in version 4.1 of Random Bone Meal Flowers. Tested with Botania in 1.19.2. Thank you!

https://www.curseforge.com/minecraft/mc-mods/random-bone-meal-flowers/files
