### ISSUE TITLE
Hidden Recipe Book: Recipe book visible in furnace GUIs.

### ISSUE THREAD

**Issue by MattB70** [ricksouth/serilum-mc-mods#1089]
## **Information**
Mod name: Hidden Recipe Book

## **Feature description**
Recipe book visible in furnace GUIs.

Simple as that lol.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed/added in version 3.0 of Hidden Recipe Book. :)

https://www.curseforge.com/minecraft/mc-mods/hidden-recipe-book/files
