### ISSUE TITLE
1.16+ mob heads not appearing in config or in game

### ISSUE THREAD

**Issue by coreytg** [ricksouth/serilum-mc-mods#1090]
Minecraft version: 1.18.1
Modloader: Fabric
Fabric loader version: 0.13.3
Environment: Multiplayer

Mod name: Just Mob Heads (Fabric)
Mod version: justmobheads-fabric_1.18.x-5.2.jar

As the title says, no mob heads from 1.16+ are appearing in the game or in the config when I looked for them. This includes the axolotls, goat, piglins, Hoglin, glow squid, and strider. The mod page says they should be in but they don't appear in the files.

**Comment by ricksouth** [comment]
Thanks for letting me know and giving the mod a try! The latest version of Just Mob Heads has this issue fixed.

https://www.curseforge.com/minecraft/mc-mods/just-mob-heads-fabric/files
