### ISSUE TITLE
Can I download the source for just one mod?

### ISSUE THREAD

**Issue by LuciusofLegend** [ricksouth/serilum-mc-mods#1091]
## **Question**
Is there a way to download the source code of just one mod without downloading the entire .zip?

**Comment by ricksouth** [comment]
This StackOverflow page has a few suggestions on how to do it: https://stackoverflow.com/questions/7106012/download-a-single-folder-or-directory-from-a-github-repo

Thanks for the interest!

**Comment by LuciusofLegend** [comment]
Thanks, I installed the refined github browser extension.
