### ISSUE TITLE
Incompatibility with Apugli's Edible Item functionality

### ISSUE THREAD

**Issue by ChrysanthCow** [ricksouth/serilum-mc-mods#1094]
## **Information**
Minecraft version: 1.18.x
Modloader: Fabric
Fabric loader version: 0.14.6
Environment: Singleplayer

Mod name: Collective
Mod version: 4.26

## **Description**
> okay, I believe it's the collective api made by Serilum. Removing the collective-fabric-1.18.x-4.26.jar from my mods seems to properly give the edible item power its functions back, and replacing it should replicate the issue if you want to give it a check!

Happens with Apugli 1.6.2, making an item edible doesn't consume it and give you hunger when Collective is installed.

I'm reporting a bug I received on my end, and I'm sure I know the issue.
You've made the priority on your ItemStackMixin happen **before** other mods rather than after, (I think lower numbers happen first).

**Comment by ChrysanthCow** [comment]
Confirmed that it still happens on 1.19.2 with Apugli 1.9.0.
Message from my Discord.

![image](https://user-images.githubusercontent.com/81167232/185783668-add198bc-8d1d-42b9-8d1f-23e9eb004128.png)

**Comment by ricksouth** [comment]
Thanks for opening the issue! This has been fixed in version 4.63 of Collective. Apologies the fix took so long.

https://www.curseforge.com/minecraft/mc-mods/collective-fabric/files
