### ISSUE TITLE
Incompatability with Buried Barrels

### ISSUE THREAD

**Issue by WarmIceCream** [ricksouth/serilum-mc-mods#1095]
## **Information**
Mod names: Random Village Names, [Buried Barrels](https://www.curseforge.com/minecraft/mc-mods/buried-barrels)

## **Feature description**
Buried Barrels has barrel structures for each loot offering vanilla structure, including villages. The village barrels seem to also generate a village area sign despite being nowhere near a village (see screenshots) - this obviously gives away the location of the supposedly hidden barrel and defeats the purpose of the mod, though the other barrel types seem to be unaffected.

![2022-06-05_11 41 55](https://user-images.githubusercontent.com/63678263/172046803-dfdfa4f6-16ee-4a92-b0d3-5d8cf09a4ee8.png)
![2022-06-05_11 42 05](https://user-images.githubusercontent.com/63678263/172046805-c2b44e23-522b-4b59-b456-1d03e6606be2.png)
.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 2.0 of Random Village Names.

https://www.curseforge.com/minecraft/mc-mods/random-village-names/files
