### ISSUE TITLE
Spawning high in the sky

### ISSUE THREAD

**Issue by Sarsath** [ricksouth/serilum-mc-mods#1096]
## **Information**
Minecraft version: 1.18.2
Modloader: Both Forge and Fabric
Forge version: 40.1.47
Fabric loader version: 0.14.6
Environment: Singleplayer

Mod name: Village Spawn Point
Mod version:
- Forge: villagespawnpoint-fabric_1.18.x-1.8.jar
- Fabric: villagespawnpoint_1.18.2-1.9.jar

## **Description**
Whenever I create a new world with Village Spawn Point on alongside Set World Spawn Point, I spawn high up in the heavens and if I am in Survival Mode, I fall to my death.

## **Crash report**
Has nothing to do with crashing.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 2.5 of Set World Spawn Point.

https://www.curseforge.com/minecraft/mc-mods/set-world-spawn-point/files
https://www.curseforge.com/minecraft/mc-mods/set-world-spawn-point-fabric/files
