### ISSUE TITLE
Infinite Rockets with Easy Elytra Takeoff

### ISSUE THREAD

**Issue by SulpherStaer** [ricksouth/serilum-mc-mods#1100]
## **Information**
Minecraft version: 1.19
Modloader:  Fabric
Fabric loader version: 55.2
Environment: Multiplayer

Mod name: Easy Elytra Takeoff (Fabric)
Mod version: easyelytratakeoff-fabric_1.19.x-2.3.jar

## **Description**
![image](https://user-images.githubusercontent.com/5037244/172924174-9ad88ba7-2306-41a4-aeab-c47f6a4b7661.png)

One of the players on my server has figured out how to get infinite flight.

**Comment by ricksouth** [comment]
Is it still possible without the mod installed? Do you have a video of it happening?

**Comment by ricksouth** [comment]
This has been fixed in version 3.0 of Easy Elytra Takeoff. Thanks for giving the mod a try!

https://www.curseforge.com/minecraft/mc-mods/easy-elytra-takeoff
