### ISSUE TITLE
[1.19] wrong enchant applied

### ISSUE THREAD

**Issue by Bass2style** [ricksouth/serilum-mc-mods#1101]
## **Information**
Minecraft version: 1.19
Modloader: Forge
Forge version: 41.0.5
Environment: Singleplayer

Mod name: Enchanting Commands
Mod version: 1.8 ?

## **Description**
when enchanting with the mod, wrong enchant is applied, not tested if generatin an other map keeps the same enchants but :
Knockback gives fireaspect
looting gives bane of arthropods
sharpness gives Swift Sneak

in the chat it says "the enchantment 'xx' has been added to the item with a level of 'xx' (xx are placeholders for the example), showing the expected name, but the enchant itself is wrong

not tested all the other enchants, but something weird is happening. xd

## **Crash report**
nothing seems present in the latest.log

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in the latest release which I've just uploaded, alongside some other features.

https://www.curseforge.com/minecraft/mc-mods/enchanting-commands/files
