### ISSUE TITLE
Beautified Chat not working

### ISSUE THREAD

**Issue by EightBitBBQ** [ricksouth/serilum-mc-mods#1103]
## **Information**
Minecraft version: 1.19
Modloader: Forge
Forge version: 41.0.1
Environment: Multiplayer

Mod name: Beautified chat

Mod version: 1.1

## No chat appearing ingame
You can type but no chat appears.
Console gives error: username sent message with invalid signature
![bc issue](https://user-images.githubusercontent.com/107324400/173203753-3c963a0a-7c1c-4317-8652-c3df814bf9dc.jpeg)

**Comment by James103** [comment]
Are you running the client edition of Beautified Chat or the server edition?

The server edition of the mod will need to be adjusted so it uses the new chat preview and styling feature added in 1.19.

**Comment by EightBitBBQ** [comment]
Its on server side. Serilum already removed in updated version of TVE. But asked me to create issue here
(Installed the modpack so also client side i guess?)

**Comment by EightBitBBQ** [comment]
After the update. (So removing the Mod.)

Chat works again!

**Comment by ricksouth** [comment]
This has been fixed in version 1.5 of Beautified Chat Server. Thanks for letting me know and giving the mod a try!

https://www.curseforge.com/minecraft/mc-mods/beautified-chat-server/files
