### ISSUE TITLE
Enchanting Mod Problem

### ISSUE THREAD

**Issue by Eri-Vadi** [ricksouth/serilum-mc-mods#1109]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.19
Modloader: Forge / Fabric
Forge version: 41.0.17 OR  Fabric loader version: x.xx.x
Environment: Singleplayer

Mod name: Enchanting Forge
Mod version: 1.19 version CurseForge

## **Question**
Hy when I use /ec enchant  sharpness 100 
enchant command execute but the result is: " Swift Sneak enchantment.level.100" and don't change sword characteristics same with efficincy for tools.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in the latest release which I've just uploaded, alongside some other features.

https://www.curseforge.com/minecraft/mc-mods/enchanting-commands/files
