### ISSUE TITLE
Consider allowing non-Curseforge modpacks to use your mods with links back to your Curseforge pages?

### ISSUE THREAD

**Issue by wolfsprite** [ricksouth/serilum-mc-mods#1111]
I've been fine-tuning a modpack that uses a lot of mods that aren't on Curseforge, as well as mods that are on it. I've really enjoyed a lot of your mods in the past, and while looking to add some of yours to the modpack, I noticed your mod pages state that they can only be used in a modpack that's hosted on Curseforge. Since I'm using mods and resourcepacks not available on Curseforge, and intend to distribute the modpack as a simple install (freely, no ads), this means I can't use any of your mods in it, which is a bummer.

I hope you reconsider this policy, as I would really like to use your mods in the modpack, which is solely for improving Minecraft experience and not to be monetized in any way. 

In the meantime I've been looking for replacement mods that implement the same features that your mods do, since you currently do not give permission to distribute them outside of the Curseforge ecosystem. I've found a few, but I don't like having to do this, because I do like your mods a lot and would like to share them with others.

Anyway, thank you for creating the mods in the first place. I've especially enjoyed the configurable compass/clock GUIs, and Compact Help Command.

**Comment by ricksouth** [comment]
Hey @baphomutt, I appreciate you asking me. At the moment I don't want to give explicit permission to everyone for this. This is due to the problem with some websites rehosting stolen content from CurseForge authors.

You can definitely do what you're asking for though. I'll give you permission to include the mods. Thanks for giving them a try and glad they've been of some use to you: :)

**Comment by wolfsprite** [comment]
Thank you for your response; I'm extremely excited that I can include your mods in the modpack! :D 

It's primarily private right now (just for me and some friends while testing), but I do want to make it public at some point, and will be including a list of all the mods in it with links back to each individual mod page. :)

Thanks for providing Minecrafters with awesome mods. ^^

**Comment by copygirl** [comment]
Hi there! I figure responding to this issue might be better than creating my own, as I'm not sure what the best way to contact you is. I'm working on a modpack as well that has been private so far (thanks to packwiz I haven't even needed to redistribute much), but I'm planning to release it on Modrinth as well.

It's a pack that I've put together mainly for friends, but enough work went into it, and as I'm also showing off the pack as a streamer, I've been looking into getting permission from modders to release it to the world, just so others may have fun with it as well.

An explicit permission for me to do this would be nice, but I also would like you to reconsider your current decision.

> This is due to the problem with some websites rehosting stolen content from CurseForge authors.

Shady websites likely won't care about whether you give permission or not, and there's no reason you can't give permission to modpack authors while disallowing rehosting for any other purposes.

Alternatively (or on top of that) something that would be cool as well is if you released your mods on Modrinth. I know this may be a big feat as you've put out so many, but Modrinth is a very well-made user-friendly website (that might also have an actually usable, good search function, unlike some *\*cough\** other platforms *\*cough\**).

And thank you. I really appreciate your work and dedication you've put towards modding. :green_heart:
