### ISSUE TITLE
Welcome Message (Fabric) 1.19: Resends messages on dimension change

### ISSUE THREAD

**Issue by PillowRL** [ricksouth/serilum-mc-mods#1114]
Welcome messages are re-sent whenever a player changes dimensions.
For example: When I go through a nether portal, welcome messages are sent every time. This occurs both from overworld to nether and nether to overworld. 

Hopefully this is just a bug that is easily resolved.

The attached text file shows the chat log from:
1. Connecting to the server
2. Entering the nether from the overworld
3. Entering the overworld from the nether

[chatlog.txt](https://github.com/ricksouth/serilum-mc-mods/files/8927254/chatlog.txt)

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 1.7 of Welcome Message. Apologies it took so long for me to get to.

https://www.curseforge.com/minecraft/mc-mods/welcome-message-fabric/files
