### ISSUE TITLE
Recast (Fabric) Doesn't Work

### ISSUE THREAD

**Issue by MathewMantas** [ricksouth/serilum-mc-mods#1115]
## **Information**
Minecraft version: 1.19
Modloader: Fabric
Fabric loader version: 0.14.7
Environment: Multiplayer

Mod name: Recast (Fabric)
Mod version: 1.19

## **Description**
I log onto the server I went to fish and it doesn't fish and reel back automatically at all. I let it do it, but nothing happened. I have Fabric API as well as Collective (Fabric) and different mods that have nothing to do with fishing, mainly Iris and other graphical and performance enhancing mods.

I have provided a Gif of what I am experiencing.

[https://i.imgur.com/GBU4irc.gif](url)

## **Crash report**
No crash happens.

**Comment by James103** [comment]
Is the mod installed on the client, on the server, or both?

**Comment by MathewMantas** [comment]
> Is the mod installed on the client, on the server, or both?

On the client, does it also have to be installed on the server?

**Comment by MathewMantas** [comment]
> > Is the mod installed on the client, on the server, or both?
> 
> On the client, does it also have to be installed on the server?

I also tried it in Singleplayer and same issue.

**Comment by ricksouth** [comment]
I think you misunderstood what the mod does. It throws the hook back in automatically, after you manually reel it in. I double checked and it is working correctly. It does not automatically reel it in for you. Thanks for giving the mod a try!

**Comment by jessiewestlake** [comment]
I had the same *problem*, as I also didn't understand exactly what the mod did. Although, I *did* notice the added functionality of the fishing line being **Recast** 😄

Everything makes sense now.
