### ISSUE TITLE
Make Tree Harvester work with Mangrove Trees Roots

### ISSUE THREAD

**Issue by YumatanGames** [ricksouth/serilum-mc-mods#1118]
## **Information**
Mod name: Tree Harvester

## **Feature description**
This mod could treat the roots of the Mangrove Trees like leaves and make them decay fast, or like the wood itself. It would make it soooo much easier to harvest those trees!

**Comment by Mikzoru** [comment]
Seconding this, but to add, I would also appreciate it if this compatibility was added to the 1.18 version of the mod, for those using Blackgear's Wild Backport. Also, the mangrove propagules are often left behind floating in midair when chopping down the entire tree at once.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! Compatibility has been added in version 7.2 of Tree Harvester.

https://curseforge.com/minecraft/mc-mods/tree-harvester/files
