### ISSUE TITLE
Game Crashed when there was no item in hand

### ISSUE THREAD

**Issue by RandomGuy91** [ricksouth/serilum-mc-mods#1124]
## **Information**
Minecraft version: 1.16.5
Modloader: Forge
Forge version: 36.2.34
Environment: Singleplayer

Mod name: EnchantingCommands
Mod version: 1.0 ig?

## **Description**
I used the command '/ec (a modded enchantment) 100' with nothing in my hand, and the game crashed. Was this some other issue or is there not an error message for when that happens? If not, that's where I'd recommend you start btw. Thanks!

## **Crash report**
https://pastebin.com/Bguqy7Ks

**Comment by RandomGuy91** [comment]
Could you pls take a look into this or give me an update? I'm making a modpack and I would love to keep this in it, but if there is a critical bug, (because i realised it crashes no matter what I do, ill post a video too) then I might have to remove it and I really love your mod. Thx!

**Comment by ricksouth** [comment]
This has been fixed in version 2.5 of the mod. Thanks for opening the issue and giving the mod a try!

https://www.curseforge.com/minecraft/mc-mods/enchanting-commands/files

**Comment by RandomGuy91** [comment]
Thx! It works now!  Keep up the great work!
