### ISSUE TITLE
Server terminal spam when killing mobs [JustMobHeads]

### ISSUE THREAD

**Issue by ProTarg3t** [ricksouth/serilum-mc-mods#1129]
## **Information**
Minecraft version: 1.19.0
Modloader:  Fabric
Fabric loader version: 0.14.8
Environment:  Multiplayer

Mod name: just mod heads
Mod version: 5.4

## **Description**
Hey! every time a mob is killed with the just mob head mod active, a message is send to the server terminal

[20:03:25] [Server thread/INFO]: [STDOUT]: skeleton

I tried installing the BadSTD mod to get rid of it.

Now its:
[20:04:30] [Server thread/INFO]: [com.natamus.justmobheads.events.HeadDropEvent] skeleton

## **Crash report**
If available.
![terminal bug](https://user-images.githubusercontent.com/108022974/175107001-29ad4b4b-f665-4f92-afc5-5ddd3d1eca3f.PNG)

**Comment by James103** [comment]
Caused by this line: https://github.com/ricksouth/serilum-mc-mods/blob/65d9204352ddb1ce790c557de5ae2e411acf7234/sources-fabric/Just%20Mob%20Heads%20(Fabric)/src/main/java/com/natamus/justmobheads/events/HeadDropEvent.java#L77

**Comment by ricksouth** [comment]
Thanks for letting me know and giving the mod a try! I've just released version 5.9 of JMH, which fixes the issue.

https://www.curseforge.com/minecraft/mc-mods/just-mob-heads-fabric/files
