### ISSUE TITLE
May you allow your mods on used on the modrinth platform?

### ISSUE THREAD

**Issue by epicyeeto** [ricksouth/serilum-mc-mods#1138]
hello all, I have a question.

is it ok for your mods to be hosted on the modrinth platform you can also require credit if you really want and if you say no understand
modrinth is getting more popular and it's open-source and there going to introduce payouts so if you want to wait for that I understand

**Comment by ricksouth** [comment]
I have opened a Modrinth account and will look into this possibility in the near future. At the moment, they'll remain on CurseForge alone though. Thanks for the interest.
