### ISSUE TITLE
1.12.2 Trading item locking

### ISSUE THREAD

**Issue by KEJWII** [ricksouth/serilum-mc-mods#1140]
## **Information**
Minecraft version: 1.12.2
Modloader: Forge
Forge version: 14.23.5.2858
Environment: Singleplayer

Mod name: Infinite Trading (Forge)
Mod version: 1.12.2-1.4

## **Description**

So it doesn't bother me basically, but I decided to announce it.

Source of the problem: after trading with any villagers (vanilla and MCA mod) e.g. 2,000,000,000 times the same item, it happens that the offer is blocked and nothing can be done about it except finding another villager with a similar trade

**Comment by ricksouth** [comment]
Unfortunately I am unable to keep supporting 1.12.2. I appreciate the bug report though, thanks for the interest.
