### ISSUE TITLE
[Hoe Tweaks] Compatibility with Advanced Netherite

### ISSUE THREAD

**Issue by chimericdream** [ricksouth/serilum-mc-mods#1148]
## **Information**
Mod name: Hoe Tweaks

## **Feature description**
It would be awesome if the tools from Advanced Netherite were compatible with this as well. Looking at how the compatibility for Simply Steel was implemented, I think all you'd need to do is make the following change:

In [`util/Util.java`, line 56](https://github.com/ricksouth/serilum-mc-mods/blob/master/sources/Hoe%20Tweaks/src/main/java/com/natamus/hoetweaks/util/Util.java#L56) (and the [same line](https://github.com/ricksouth/serilum-mc-mods/blob/master/sources-fabric/Hoe%20Tweaks%20(Fabric)/src/main/java/com/natamus/hoetweaks/util/Util.java#L56) in the Fabric version):
```java
// Before
else if (tier.equals(Tiers.NETHERITE)) {

// After
else if (tier.equals(Tiers.NETHERITE) || tierstring.contains("netherite")) {
```

Here are the tier names in the [Advanced Netherite mod](https://github.com/Autovw/AdvancedNetherite/blob/1.19.X/src/main/java/com/autovw/advancednetherite/core/util/ModToolTiers.java#L82) for reference:
```java
public static void onCommonSetup() {
    TierSortingRegistry.registerTier(NETHERITE_IRON, new ResourceLocation(Reference.MOD_ID, "netherite_iron"), List.of(Tiers.NETHERITE), List.of());
    TierSortingRegistry.registerTier(NETHERITE_GOLD, new ResourceLocation(Reference.MOD_ID, "netherite_gold"), List.of(NETHERITE_IRON), List.of());
    TierSortingRegistry.registerTier(NETHERITE_EMERALD, new ResourceLocation(Reference.MOD_ID, "netherite_emerald"), List.of(NETHERITE_GOLD), List.of());
    TierSortingRegistry.registerTier(NETHERITE_DIAMOND, new ResourceLocation(Reference.MOD_ID, "netherite_diamond"), List.of(NETHERITE_EMERALD), List.of());
}
```

Thanks!

**Comment by ricksouth** [comment]
Thanks for the patience and the suggestion! Hoe Tweaks version 1.9 adds support for Advanced Netherite. :)

https://www.curseforge.com/minecraft/mc-mods/hoe-tweaks
