### ISSUE TITLE
world border max 5k*5k   fix pls

### ISSUE THREAD

**Issue by Mafy-17** [ricksouth/serilum-mc-mods#1149]
## **Information**
Minecraft version: 1.19
Modloader: Fabric
Fabric loader version: 0.14.8
Environment: Multiplayer

Mod name: Worldborder(fabric)
Mod version: 1.19x2,7

## **Description**
Hey so when I set world border to any value over 5k each direction(10000) it is automaticly set to 5k each direction it cant go more so I want my world border to be 32000  but it is only 5k each direction and since I need it to be 16k each direction  that isn't good for me xD
please fix it .  Thanks

**Comment by James103** [comment]
Try closing all running instances of Minecraft on your computer and only then changing the config file.

**Comment by ricksouth** [comment]
This has been fixed in the latest version of World Border. Thanks for opening the issue and giving the mod a try!

https://www.curseforge.com/minecraft/mc-mods/world-border/files
