### ISSUE TITLE
Can you add support for Explorer's and Nature's Compass on your GUICompass mod?

### ISSUE THREAD

**Issue by RandomGuy91** [ricksouth/serilum-mc-mods#1151]
## **Information**
Mod name: GUICompass

## **Feature description**
The title says it.

**Comment by ricksouth** [comment]
Thanks for the suggestion! Version 2.9 of GUI Compass adds compatibility for modded compasses.

https://www.curseforge.com/minecraft/mc-mods/gui-compass/files

**Comment by RandomGuy91** [comment]
Thanks! Love you work!
