### ISSUE TITLE
Crash with Dimension Threading (I think)

### ISSUE THREAD

**Issue by ghost** [ricksouth/serilum-mc-mods#1152]
Hello, my server crashed after I clicked on the bed to sleep.

I was reporting this issue also to the author from Dimensional Threading:
https://github.com/WearBlackAllDay/DimensionalThreading/issues/66

[crash-2022-07-07_16.52.29-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/9065924/crash-2022-07-07_16.52.29-server.txt)

Greetings!

**Comment by ghost** [comment]
I was updating my modpack and everything works now - not related with Dimensional Threading.

**Comment by ghost** [comment]
Oki, nope. Everything worked but after 2-3 minutes the server crashed again. I was opening a chest. Bug still occurs with Dimensional Threading.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 3.0 of Stack Refill.

https://www.curseforge.com/minecraft/mc-mods/stack-refill

**Comment by ghost** [comment]
Thanks for the update 🥰
