### ISSUE TITLE
Bigger Sponge Absorption Radius mod doesn't work with other Serilum mods

### ISSUE THREAD

**Issue by RedBeast1959** [ricksouth/serilum-mc-mods#1154]
## **Information**
Minecraft version: 1.19
Modloader: Forge
Forge version: 41.0.64
Environment: Singleplayer

Mod name: Bigger Sponge Absortion Radius mod
Mod version: biggerspongeabsorptionradius_1.19.0-2.0.jar

## **Description**
![2022-07-08_18 36 55](https://user-images.githubusercontent.com/100399264/177965906-8b8db781-2be6-447c-875d-ee3017809db7.png)
![2022-07-08_18 37 05](https://user-images.githubusercontent.com/100399264/177965916-3292b2db-cfdf-4811-ad2d-553718f36148.png)
Currently, Bigger Sponge Absortion Radius mod doesn't work with other Serilum mods.
Any other mods, like Starter kit & Anvil Restoration & Conduit Prevent Drowned & Skeleton/Zombie Horse Spawn & Cycling Painting... Literally with ANY other Serilum mods, this sponge mod is just broken.

![2022-07-08_18 41 07](https://user-images.githubusercontent.com/100399264/177966750-273dd49c-bc9f-4ac8-bdf9-02ffb5a5e146.png)

If only Bigger Sponge Absorption Radius installed, mod just works fine.

**Comment by ricksouth** [comment]
Thanks for opening the issue. This might actually go deeper than just this mod. I'm using the same mixin reference file names for each mod, to make it easier in my development environment. They might overwrite each other, causing this behaviour.

It's been a busy past few months with other life stuff, but I'll have time very soon to take a more detailed look! I've got an idea on how to fix it.

**Comment by ricksouth** [comment]
This has been fixed in the latest released version. Thank you for the patience and letting me know, it fixed a few issues with other mods as well. Appreciate it!

https://www.curseforge.com/minecraft/mc-mods/bigger-sponge-absorption-radius/files
