### ISSUE TITLE
Starter Kit doesn't work with potion items

### ISSUE THREAD

**Issue by RedBeast1959** [ricksouth/serilum-mc-mods#1155]
## **Information**
Minecraft version: 1.19
Modloader: Forge
Forge version: 41.0.64
Environment: Singleplayer

Mod name: Starter Kit
Mod version: starterkit_1.19.0-3.2.jar

## **Description**
![1](https://user-images.githubusercontent.com/100399264/177972655-1e6ad6e5-b5c8-4b11-addf-b04cbc098f65.PNG)
![2022-07-08_18 57 02](https://user-images.githubusercontent.com/100399264/177972616-2b8cacc8-81f0-4389-89ef-a3f40eeeb38e.png)

Starter Kit doesn't support portion item.  If potion items are in the config file, any item won't appear in new game inventory.
If there are no potion items in config, mod just works fine.

**Comment by James103** [comment]
1. Can you please post the text file itself, not just a screenshot?
2. Can you please post the log files from reproducing this?

**Comment by ricksouth** [comment]
Does it work when you use the command to set an inventory?

**Comment by RedBeast1959** [comment]
[starterkit-old.txt](https://github.com/ricksouth/serilum-mc-mods/files/9072139/starterkit-old.txt)
![2022-07-08_21 45 16](https://user-images.githubusercontent.com/100399264/177995363-25be63a7-fb61-4a12-9145-aa3322e192d7.png)
<Before Set Command>

[starterkit.txt](https://github.com/ricksouth/serilum-mc-mods/files/9072144/starterkit.txt)
![2022-07-08_21 49 44](https://user-images.githubusercontent.com/100399264/177995477-f0136607-27ba-4ac6-988b-d09e84d28a1d.png)
<After Set Command>

Command works! Looks like adding potion ID directly to config file doesn't work unlike other items.
