### ISSUE TITLE
Default spawn chances in config is zero?

### ISSUE THREAD

**Issue by MScott7** [ricksouth/serilum-mc-mods#1157]
Hi, love your mods. Just wondering if the default chances of giants spawning or bred rabbits being killer is 0 on purpose. The mod page says that the default chances should be 0.05, but in the freshly-generated config files the chances are just 0. Is it being set to an integer by accident? 
I believe this means that these mods will do nothing unless people happen to open the config files and notice that the stated default values aren't actually the default. 

Mod versions in question: Giant Spawn 2.7 and Breedable Killer Rabbit 1.5
(This may affect more than just these two mods, they're just the two I've noticed)
Minecraft version: 1.18.2
Modloader: Fabric
Fabric loader version: 0.14.8

**Comment by MScott7** [comment]
Can confirm that this also happens with Mooshroom Tweaks 1.6, Skeleton Horse Spawn 1.9, and Zombie Horse Spawn 3.0.

**Comment by ricksouth** [comment]
This has been fixed in the latest release of these mods, with the Forge/Fabric merge. Thanks for opening the issue!
