### ISSUE TITLE
Snowmen/snowgolems not dropping heads

### ISSUE THREAD

**Issue by Breadabix** [ricksouth/serilum-mc-mods#1159]
## **Information**
Minecraft version: 1.16.5
Modloader: Forge
Forge version: 36.2.30
Environment: SP and MP

Mod name: Justmobheads
Mod version: 1.16.5-5.4

## **Description**
Snowmen/snowgolems arent dropping their head, no matter the % chance of them doing so. Ive tried with and without looting, sweeping edge and anything else I can think of and still havent got a single head.

## **Crash report**
N/A

**Comment by ricksouth** [comment]
![2022-08-15_14 32 26](https://user-images.githubusercontent.com/38502394/184636212-e1482f4e-c5df-4038-a723-43a7e1814f2d.png)

**Comment by ricksouth** [comment]
Thanks for letting me know and using the mod! I've added the snow golem head (a small pumpkin basically) in version 5.9 of JMH alongside some other fixes.

https://www.curseforge.com/minecraft/mc-mods/just-mob-heads/files
