### ISSUE TITLE
GUI Clock encountered an error during the complete event phase

### ISSUE THREAD

**Issue by Gamemassa** [ricksouth/serilum-mc-mods#1161]
## **Information**
Minecraft version: 1.19
Modloader: Forge
Forge version: 41.0.87
Environment: N/A (Crashed while loading game)

Mod name: GUI Clock
Mod version: 3.1

## **Description**
Tried to load latest versions of GUI Clock and Forge and encountered an error during the complete event phase.
![image](https://user-images.githubusercontent.com/18667108/178146222-06886af6-3a8e-48c5-bb36-369f2ddba508.png)

## **Crash report**
[crash-2022-07-10_09.05.55-fml.txt](https://github.com/ricksouth/serilum-mc-mods/files/9079118/crash-2022-07-10_09.05.55-fml.txt)

**Comment by ricksouth** [comment]
This was due to changes in Forge. If you use the latest version of GUI Clock, it'll work. Thanks for the interest!
