### ISSUE TITLE
Really Annoying Problem In Collective

### ISSUE THREAD

**Issue by Ferrlius** [ricksouth/serilum-mc-mods#1163]
## **Information**
Minecraft version: 1.19
Modloader: Fabric
Fabric loader version: 0.14.8
Environment: Multiplayer

Mod name: Collective
Mod version: 4.27

## **Description**
Piglins are always trying to pickup random items and they have a player-sized inventory. It's not ok, I don't want it in my game. I think you always had this problem in your mod, I just couldn't find what mod coused it

**Comment by ricksouth** [comment]
The mod does not change any behaviour in Piglins. I believe this problem is from elsewhere. If I'm wrong, please let me know with some more pictures.
