### ISSUE TITLE
Crying Portals & Areas incompatibility

### ISSUE THREAD

**Issue by BrachoAlex** [ricksouth/serilum-mc-mods#1168]
## **Information**
Minecraft version: 1.19
Modloader: Forge
Forge version: 41.0.63
Environment: Singleplayer

Mod name: Crying Portals & Areas
Mod version: Crying Portals :1.19.0-1.2  Areas: 1.19.0-2.9

## **Description**
Crying portals mod wont work with Areas mod. For some reason, the activation of the nether portal using crying obsidian don't work while using Areas mod. 

## **Crash report**
None.

**Comment by ricksouth** [comment]
This has been fixed in the latest update of Crying Portals. Thanks for letting me know and using the mod!

https://www.curseforge.com/minecraft/mc-mods/crying-portals/files
