### ISSUE TITLE
Mod Loading Error 1.19

### ISSUE THREAD

**Issue by elkianty** [ricksouth/serilum-mc-mods#1169]
## **Information**
Minecraft version: 1.19
Modloader: Forge
Forge version: 41.0.98 
Environment: Singleplayer 

Mod name: Just Mob Heads
Mod version: 5.5

## **Description**
Hey! After loading into Minecraft, I got an error message saying that Just Mob Heads and Collective failed to load correctly. Pretty sure it is an issue on my side, but I have no idea how to fix it. 
Edit: Only happens in newer Forge versions. Works as intended with Forge 41.0.88.

## **Crash Report**
[crash-2022-07-13_03.44.07-fml.txt](https://github.com/ricksouth/serilum-mc-mods/files/9098169/crash-2022-07-13_03.44.07-fml.txt)

## **Screenshot**
![Screenshot (79)](https://user-images.githubusercontent.com/109189774/178629438-96d0d8fc-6bee-4594-a7c4-5db04db9b25c.png)

**Comment by James103** [comment]
Can you please upload the corresponding crash report if you still have it?
If not, try reproducing this problem then upload the latest `-fml` crash report.

**Comment by elkianty** [comment]
> 
[crash-2022-07-13_03.44.07-fml.txt](https://github.com/ricksouth/serilum-mc-mods/files/9098151/crash-2022-07-13_03.44.07-fml.txt)

**Comment by elkianty** [comment]
> Can you please upload the corresponding crash report if you still have it? 

Updated.

**Comment by ricksouth** [comment]
This was due to changes in Forge. If you use the latest version of Just Mob Heads, it'll work. Thanks for the interest!
