### ISSUE TITLE
CurseForge does not report all versions

### ISSUE THREAD

**Issue by RandomGgames** [ricksouth/serilum-mc-mods#1170]
## **Information**
Minecraft version: 1.19
Modloader: Fabric

Mod name: Just Mob Heads
Mod version: 5.4

## **Description**
In CurseForge, the file for it reports that it is only compatible with 1.19-Snapshot. In the file title it says 1.19.x, but I'm assuming it works with 1.19+, but 1.19 isn't listed in the compatible mods version. Please change the compatible versions to contain 1.19 as well as 1.19-Snapshot.

**Comment by ricksouth** [comment]
I have changed the format of Fabric versions to remove any confusion for the future. As of now, there should be a version available that works for your needs. I appreciate the interest!
