### ISSUE TITLE
Mods not loading/running in Fabric 1.19

### ISSUE THREAD

**Issue by PitchBlackNights** [ricksouth/serilum-mc-mods#1172]
## **Information**
Minecraft version: 1.19
Modloader: Fabric
Fabric loader version: 0.14.8
Environment: Singleplayer & Multiplayer

Mod name: GUI Clock, GUI Compass
Mod version: 2.3, 3.2 (in order)

## **Description**
Minecraft loads just fine, but the mods don't load. They don't show up in the log as enabled, and they don't generate configs.

## **Crash report**
No crash, but there is a log
[https://pastebin.com/LxQBY9GU](https://pastebin.com/LxQBY9GU)

**Comment by ricksouth** [comment]
I couldn't replicate this locally, but please give the latest version a try. I've changed a lot of the code. Remember that the mod has to be installed on the client.

https://www.curseforge.com/minecraft/mc-mods/gui-clock-fabric-version/
