### ISSUE TITLE
"The current actively developed Minecraft versions" line in README.md does not list 1.19

### ISSUE THREAD

**Issue by James103** [ricksouth/serilum-mc-mods#1173]
## **Information**
File in repository: https://github.com/ricksouth/serilum-mc-mods/blob/master/README.md
Commit: 65d9204352ddb1ce790c557de5ae2e411acf7234

## **Actual result**
The following line is incorrect.
"The current actively developed Minecraft versions are 1.16.5, 1.17.1, 1.18.2 for Forge and 1.16.x, 1.17.x, 1.18.2 for Fabric."

## **Expected result**
Corrected version:
"The current actively developed Minecraft versions are 1.16.5, 1.17.1, 1.18.2, and 1.19 for Forge and 1.16.x, 1.17.x, 1.18.2, and 1.19 for Fabric."

**Comment by ricksouth** [comment]
Thanks again @James103, fixed!
