### ISSUE TITLE
[Grass Seeds] Seeds fail to be planted while still consuming them erratically, as if tilled soil is "protected"

### ISSUE THREAD

**Issue by OutbackCatgirl** [ricksouth/serilum-mc-mods#1174]
## **Information**
Minecraft version: 1.19
Modloader: Fabric
Fabric loader version: 0.14.8
Environment: Singleplayer

Mod name: Uncertain; see list
Mod version: Latest non-snapshot at time of submission 

## **Description**
16/07 EDIT: Managed to eliminate the list below! it's caused directly by the Grass Seeds mod (v1.7 for 1.19.x)

I am trying to figure out what, exactly, is causing this. There are no errors or debug messages or log oddities to help me troubleshoot with. I have a selection of your mods, mostly QOL, installed, but none of them have anything to do with crops or farming explicitly. 
I think I have narrowed it down to either a fabric issue or an issue with one of your mods. Naturally, this behaviour is not present in vanilla minecraft nor vanilla with optifine.

Honestly i'm stumped on this and not entirely sure what to do or how to get more useful logs or data.

Mods active (besides automatic dependencies added by CurseForge such as the fabric loader itself):
Anvil Restoration (Fabric) (by Serilum)
Automatic Doors (Fabric) (by Serilum)
Collective (Fabric) (by Serilum)
Conduits Prevent Drowned (Fabric) (by Serilum)
Crying Ghasts (Fabric) (by Serilum)
Despawning Eggs Hatch (Fabric) (by Serilum)
Dismount Entity (Fabric) (by Serilum)
Double Doors (Fabric) (by Serilum)
Extended Bone Meal (Fabric) (by Serilum)
Fixed Anvil Repair Cost (Fabric) (by Serilum)
Furnace Recycle (Fabric) (by Serilum)
Grass Seeds (Fabric) (by Serilum)
GUI Clock (Fabric Version) (by Serilum)
GUI Compass (Fabric Version) (by Serilum)
GUI Followers (Fabric) (by Serilum)
Healing Campfire (Fabric) (by Serilum)
Infinite Trading (Fabric) (by Serilum)
Kelp Fertilizer (Fabric) (by Serilum)
Mineral Chance (Fabric) (by Serilum)
Random Bone Meal Flowers (Fabric) (by Serilum)
Scaffolding Drops Nearby (Fabric) (by Serilum)
Sleep Sooner (Fabric) (by Serilum)
Softer Hay Bales (Fabric) (by Serilum)
Spiders Produce Webs (Fabric) (by Serilum)
Stack Refill (Fabric) (by Serilum)
Village Bell Recipe (Fabric) (by Serilum)
Weaker Spiderwebs (Fabric) (by Serilum)
Wool Tweaks (Fabric) (by Serilum)
Zombie Proof Doors (Fabric) (by Serilum)

All are on the most updated version automatically downloaded by CurseForge when creating a mod profile for 1.19 Fabric at time of writing.

Let me know if there's any steps I can take to troubleshoot this.

**Comment by OutbackCatgirl** [comment]
FIGURED IT OUT! It's caused by the Grass Seeds mod!

**Comment by OutbackCatgirl** [comment]
Okay, now i know it's grass seeds causing this, I had a look and, sure enough, this is a duplicate of https://github.com/ricksouth/serilum-mc-mods/issues/837
If you want to close this in order to move discussion to that earlier thread, go ahead, i'm gonna keep an eye on it.

**Comment by ricksouth** [comment]
This has been fixed in version 2.2 of Grass Seeds. Thanks for using the mod and opening the issue!

https://www.curseforge.com/minecraft/mc-mods/grass-seeds-fabric/files
