### ISSUE TITLE
Crash when creating World

### ISSUE THREAD

**Issue by LilacV** [ricksouth/serilum-mc-mods#1175]
## **Information**
Minecraft version: 1.19
Modloader: Fabric
Fabric loader version: fabric-loader-0.14.8-1.19
Environment: Singleplayer

Mod name: Collective
Mod version: 4.27

## **Description**
I had created a fabric profile with a bunch of mods i wanted to play with and after tweaking them i went on to create a world, but the game crashed and after reading the crash report i came to the conclusion it had something with Collective to do. Thanks for the awesome mods always, looking forward to your help. 😄 

## **Crash report**
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 7/15/22, 5:36 PM
Description: Exception ticking world

java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because the return value of "java.util.HashMap.get(Object)" is null
	at com.natamus.collective_fabric.events.CollectiveEvents.onWorldTick(CollectiveEvents.java:38)
	at com.natamus.collective_fabric.CollectiveFabric.lambda$onInitialize$1(CollectiveFabric.java:27)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$4(ServerTickEvents.java:84)
	at net.minecraft.server.world.ServerWorld.handler$cae000$startWorldTick(ServerWorld:6223)
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld:279)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:875)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:819)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer:98)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:258)
	at java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.natamus.collective_fabric.events.CollectiveEvents.onWorldTick(CollectiveEvents.java:38)
	at com.natamus.collective_fabric.CollectiveFabric.lambda$onInitialize$1(CollectiveFabric.java:27)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$4(ServerTickEvents.java:84)
	at net.minecraft.class_3218.handler$cae000$startWorldTick(class_3218.java:6223)
	at net.minecraft.class_3218.method_18765(class_3218.java:279)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 0
	Level dimension: ae2:spatial_storage
	Derived: true
	Level spawn location: World: (32,63,-16), Section: (at 0,15,0 in 2,3,-1; chunk contains blocks 32,0,-16 to 47,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 1 game time, 1 day time
	Level name: Fabric's Finest
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 106230 (now: false), thunder time: 61480 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 621364224 bytes (592 MiB) / 2768240640 bytes (2640 MiB) up to 8388608000 bytes (8000 MiB)
	CPUs: 6
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: unknown
	Frequency (GHz): 2.81
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 6
	Graphics card #0 name: NVIDIA GeForce RTX 2060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f08
	Graphics card #0 versionInfo: DriverVersion=31.0.15.1659
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 20657.16
	Virtual memory used (MB): 13193.46
	Swap memory total (MB): 4352.00
	Swap memory used (MB): 132.44
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8000m -Xms256m
	Fabric Mods: 
		ae2: Applied Energistics 2 12.0.1-alpha
			noindium: No Indium? 1.0.2+1.18.2
				omega-config: OmegaConfig 1.2.3-1.18.1
		ae2wtlib: AE2WTLib 12.0.2-alpha
		allarrowsinfinityfix: All Arrows Infinity Fix 1.3
		alloy_forgery: Alloy Forgery 2.0.15+1.19
		alternate-current: Alternate Current 1.4.0
		amethystequipment: Amethyst Equipment 1.0.5
		anvilrestoration-fabric: Anvil Restoration (Fabric) 1.3
		appleskin: AppleSkin 2.4.0+mc1.19
		architectury: Architectury 5.9.31
		armorpointspp: Armorpoints++ 3.0.5
			fiber: fiber 0.23.0-2
		artifacts: Artifacts 7.1.1+fabric
			com_github_llamalad7_mixinextras: MixinExtras 0.0.11
			expandability: ExpandAbility 6.0.0
			step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		attributefix: AttributeFix 15.0.2
		awesomedungeon: Awesome Dungeon 2.0.11
		awesomedungeonend: Awesome Dungeon Edition end 1.0.3
		awesomedungeonnether: Awesome Dungeon Edition Nether 1.0.3
		awesomedungeonocean: Awesome Dungeon Edition Ocean 2.0.8
		backslot: BackSlot 1.2.8
			amecsapi: Amecs API 1.3.6+mc22w17a
		backslotaddon: BackSlot Addon 1.0.9
		balm-fabric: Balm 4.3.0+0
		basicaiots: Basic AIOTs 1.4+1.19
		bclib: BCLib 2.0.15
		bedbenefits: BedBenefits 7.0.2
		beenfo: Beenfo 1.19-fabric0.53.3-1.3.3
			crowdin-translate: CrowdinTranslate 1.4+1.19
			gbfabrictools: GBfabrictools 1.3.4+1.19
		betteradvancements: Better Advancements 0.2.1.134
		betterbeds: Better Beds 1.2.0
		betterend: Better End 2.0.9
		betternether: Better Nether 7.0.6
		betterthirdperson: Better Third Person 1.8.1
		boneequipment: Bone Equipment 1.0.4
		bookshelf: Bookshelf 14.1.7
		boostedbrightness: Boosted Brightness 2.1.2
		borderlessmining: Borderless Mining 1.1.5+1.19
		bsvsb: Better Sodium Video Settings Button 3.0.0
		cardinal-components: Cardinal Components API 5.0.1
			cardinal-components-base: Cardinal Components API (base) 5.0.1
			cardinal-components-block: Cardinal Components API (blocks) 5.0.1
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.1
			cardinal-components-entity: Cardinal Components API (entities) 5.0.1
			cardinal-components-item: Cardinal Components API (items) 5.0.1
			cardinal-components-level: Cardinal Components API (world saves) 5.0.1
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.0.1
			cardinal-components-world: Cardinal Components API (worlds) 5.0.1
		chassis: Chassis 1.2.0
		clear-skies: Clear Skies 2.0.94
		clienttweaks: Client Tweaks 8.0.0
		cloth-config: Cloth Config v6 7.0.73
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 9.0.0+3
		collective-fabric: Collective (Fabric) 4.27
		compressor: Compressor 0.3.0
		concreteconversion: Concrete Conversion 6.1.0.0
		continuity: Continuity 2.0.0+1.19
		controlling: Controlling For Fabric 10.0+3
		cookingforblockheads: Cooking for Blockheads 13.1.2
		craftingtweaks: Crafting Tweaks 15.0.1
		cryingportals-fabric: Crying Portals (Fabric) 1.3
		cull-less-leaves: Cull Less Leaves 1.0.4
			conditional-mixin: conditional mixin 0.3.0
		disable_custom_worlds_advice: Disable Custom Worlds Advice 3.0
		doubledoors-fabric: Double Doors (Fabric) 3.4
		dynamicfps: Dynamic FPS 2.2.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		easiervillagertrading: EasierVillagerTrading 1.19-fabric0.53.3-1.5.4
		elytratrinket: Elytra Trinket 3.0.0-1.18.1
		emeraldequipment: Emerald Equipment 1.0.4
		enchdesc: EnchantmentDescriptions 11.0.4
		enhancedblockentities: Enhanced Block Entities 0.7.1+1.19
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2
			spruceui: SpruceUI 4.0.0+1.19
		entitycollisionfpsfix: Entity Collision FPS Fix 2.0.0.0
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		exlinecopperequipment: Copper Equipment 2.1.1
		exlinedoors: Exline's Doors 2.3.5
		exlinefurniture: Exline's Furniture 2.2.1
		extragenerators: Extra Generators 1.2.1-BETA+1.19
			team_reborn_energy: Energy 2.2.0
		extremesoundmuffler: Extreme sound muffler 3.27_fabric-1.19
		fabric: Fabric API 0.57.0+1.19
			fabric-api-base: Fabric API Base 0.4.9+e62f51a3a9
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.7+9ff28f40a9
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.14+b2a4a624a9
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.18+9ff28f40a9
			fabric-command-api-v1: Fabric Command API (v1) 1.2.6+f71b366fa9
			fabric-command-api-v2: Fabric Command API (v2) 2.1.2+0d55f585a9
			fabric-commands-v0: Fabric Commands (v0) 0.2.23+df3654b3a9
			fabric-containers-v0: Fabric Containers (v0) 0.1.27+df3654b3a9
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.0+07df213ea9
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d24a9
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4aa9
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.1+a680b9b4a9
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.28+a6d2f785a9
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f40a9
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f40a9
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.25+df3654b3a9
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+18990361a9
			fabric-item-api-v1: Fabric Item API (v1) 1.5.4+767db26ea9
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.25+9ff28f40a9
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.18+9ff28f40a9
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.16+df3654b3a9
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+33fbc738a9
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.0+03a4e568a9
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.3+9e7660c6a9
			fabric-message-api-v1: Fabric Message API (v1) 1.0.1+513f4a59a9
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.10+33fbc738a9
			fabric-models-v0: Fabric Models (v0) 0.3.15+9ff28f40a9
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.27+7fe97409a9
			fabric-networking-v0: Fabric Networking (v0) 0.3.14+df3654b3a9
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.7+9ff28f40a9
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553aa9
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.17+23c4cfefa9
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.8+9ff28f40a9
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.9+1f92344ea9
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.18+df3654b3a9
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f40a9
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f40a9
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.20+df3654b3a9
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.14+9ff28f40a9
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a3a9
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.5+a6d2f785a9
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.24+f05effafa9
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.6+9ff28f40a9
			fabric-textures-v0: Fabric Textures (v0) 1.0.18+9ff28f40a9
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.9+e62f51a3a9
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c6a9
		fabric-language-kotlin: Fabric Language Kotlin 1.8.1+kotlin.1.7.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.3
		fabric-language-scala: Fabric Language Scala 1.1.0+scala.2.13.6
		fabricloader: Fabric Loader 0.14.8
		ferritecore: FerriteCore 4.2.1
		fixedanvilrepaircost-fabric: Fixed Anvil Repair Cost (Fabric) 1.8
		forgeconfigapiport: Forge Config API Port 4.0.0
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		ftblibrary: FTB Library 1900.3.7-build.131
		ftbultimine: FTB Ultimine 1900.3.4-build.58
		furnacerecycle-fabric: Furnace Recycle (Fabric) 1.3
		geckolib3: Geckolib 3.1.5
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		grindenchantments: Grind Enchantments 1.6.4+1.19
		healingcampfire-fabric: Healing Campfire (Fabric) 3.5
		heartytrinkets: Hearty Trinkets 1.19-1.0.0
		held-item-info: Held Item Info 1.3.0
		iknowwhatimdoing: I Know What I'm Doing 4.1.0
		indium: Indium 1.0.6+mc1.19
		inventoryhud: Inventory HUD + 3.4.2
		inventorysorter: Inventory Sorter 1.8.8-1.19
			kyrptconfig: Kyrpt Config 1.4.6-1.19
				blue_endless_jankson: jankson 1.2.1
		inventorytabs: Inventory Tabs 0.7.0-1.19.x
		inventorytotem-fabric: Inventory Totem (Fabric) 1.7
		itemmodelfix: Item Model Fix 1.0.3+1.19
		jade: Jade 7.6.0
		jamlib: JamLib 0.1.0
		java: OpenJDK 64-Bit Server VM 17
		krypton: Krypton 0.2.0
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		lazydfu: LazyDFU 0.1.3
		libraryferret: Library Ferret 2.0.0
		lightoverlay: Light Overlay 7.0.0
		lithium: Lithium 0.8.1
		logical_zoom: Logical Zoom 0.0.15
		magehand: Magehand 1.1.2
		maxhealthfix: MaxHealthFix 6.0.1
		mcwlights: Macaw's Lights and Lamps 1.0.3
		memoryleakfix: memory Leak Fix 1.19-0.4.1
		minecraft: Minecraft 1.19
		minieffects: Mini Effects 5.0.0
		mob_catcher: Mob Catcher 1.2.4
		moderndynamics: Modern Dynamics 0.3.0-beta
		modmenu: Mod Menu 4.0.4
		morevillagers: More Villagers 4.0.2
		mousetweaks: Mouse Tweaks 2.22
		mythicmetals: Mythic Metals 0.15.1
			magna: Magna 1.8.0-1.19
		mythicmetals_decorations: Mythic Metals Decorations 0.3.0
			ellemes_container_lib: Ellemes' Container Library 2.0.0-beta.4
		mythicmounts: Mythic Mounts 1.19-7.0
		naturescompass: Nature's Compass 1.19-2.0.4-fabric
		neat: Neat 1.8-31-FABRIC
		no-telemetry: No Telemetry 1.4.0
		no_fog: No Fog 1.3.0+1.16.5-1.19
		nochatreports: No Chat Reports 1.19-v1.2.3
		nohostilesaroundcampfire-fabric: No Hostiles Around Campfire (Fabric) 4.0
		notenoughcrashes: Not Enough Crashes 4.1.6+1.19
		noweathereffects: No Weather Effects 1.4.0
		obsidianequipment: Obsidian Equipment 1.0.4
		owo: oωo 0.7.3+1.19
		patchouli: Patchouli 1.19-74-FABRIC
		quarryplus: QuarryPlus 19.1.610
		quickshulker: Quick Shulker 1.3.6-1.19
			shulkerutils: shulkerutils 1.0.4-1.18
		rebind_all_the_keys: RebindAllTheKeys 1.2.0-beta.1+1.19
		reeses-sodium-options: Reese's Sodium Options 1.4.3+mc1.19-build.43
		rightclickharvest: Right Click Harvest 2.2.1
		ring_of_attraction: Ring Of Attraction 1.3.9
		ring_of_enderchest: Ring of Enderchest 1.3.9
		ring_of_growth: Ring Of Growth 1.3.9
		ring_of_miner: Ring Of Miner 1.4.11
			pugh_tools: Pugh Tools 1.3.10
		ring_of_teleport: Ring Of Teleport 1.2.10
		ringsofascension: Rings of Ascension 1.0
		roughlyenoughitems: Roughly Enough Items 9.1.517
		roughlyenoughprofessions: Roughly Enough Professions 1.1.0
		roughlyenoughresources: Roughly Enough Resources 2.6.0
		silkspawners: SilkSpawners 1.1.2
		simplechunkloader: Simple Chunkloader 1.0.2
		skylorlib: SkyLib 1.5.1
		sodium: Sodium 0.4.2+build.16
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.5+mc1.19-build.43
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		sspb: Sodium Shadowy Path Blocks 3.0.0
		starlight: Starlight 1.1.1+fabric.ae22326
		tempad: Tempad 1.2.5
		things: Things 0.2.19+1.19
			reach-entity-attributes: Reach Entity Attributes 2.2.1
		tokenablefurnaces: Tokenable Furnaces 2.0.1
		toms_storage: Tom's Simple Storage Mod 1.3.5
		toolstats: ToolStats 10.0.1
		tooltipfix: ToolTip Fix 1.0.5-1.19
		trade_cycling: Trade Cycling 1.19-1.0.3
		trashslot: TrashSlot 12.0.1
		travelersbackpack: Traveler's Backpack 1.19-8.0.1
		trinkets: Trinkets 3.4.0
		villainousfishai: Villainous Fish AI 1.1
		walllanterns: Lanterns Belong on Walls 1.2.1
		wirelessnetworks: Wireless Networks 1.6.0
			libgui: LibGui 6.0.0+1.19
				jankson: Jankson 4.1.1+j1.2.1
				libninepatch: LibNinePatch 1.1.0
		wooledboots: Wooled Boots 1.3.1
		wooltweaks-fabric: Wool Tweaks (Fabric) 1.7
		xaerominimap: Xaero's Minimap 22.12.0
		xaeroworldmap: Xaero's World Map 1.26.1
		yigd: You're in Grave Danger 1.4.1
	Server Running: true
	Player Count: 0 / 8; []
	Data Packs: vanilla, Fabric Mods, compressor (incompatible)
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: fabric-loader-0.14.8-1.19
	Client Crashes Since Restart: 0
	Integrated Server Crashes Since Restart: 1
	Suspected Mods: Minecraft (minecraft), Collective (Fabric) (collective-fabric), Fabric Lifecycle Events (v1) (fabric-lifecycle-events-v1)

**Comment by shartte** [comment]
See https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/6426

**Comment by ricksouth** [comment]
This has been fixed in the latest AE2 version. Thanks to the AE team for finding and fixing the problem.
