### ISSUE TITLE
fail to load correctly on forge 41.0.98+

### ISSUE THREAD

**Issue by ALeX400** [ricksouth/serilum-mc-mods#1178]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.19
Modloader: Forge 
Forge version: 41.0.98
Environment: Singleplayer ( just fot test )

Mod name: Collective
Mod version:4.28

## **Question**
an update is possible for forge 41.0.98+ ?

**Comment by ricksouth** [comment]
The latest version of the mod will work with the Forge changes. Thanks for the interest.
