### ISSUE TITLE
fail to load correctly on forge 41.0.98+

### ISSUE THREAD

**Issue by ALeX400** [ricksouth/serilum-mc-mods#1179]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.19.0
Modloader: Forge
Forge version: 41.0.98
Environment: Singleplayer ( just for testing )

Mod name: Tree Harvester
Mod version: 5.1

## **Question**
an update is possible for forge 41.0.98+ ?
collective must also be updated for this, because it doesn't work on version 41.0.98+ either

**Comment by ricksouth** [comment]
The latest version of the mod will work with the Forge changes. Thanks for the interest.
