### ISSUE TITLE
Realistic bees not changing bee size

### ISSUE THREAD

**Issue by EightBitBBQ** [ricksouth/serilum-mc-mods#1180]
## **Information**
Minecraft version: 1.19
Modloader: Forge 
Forge version: 41.0.17
Environment: Multiplayer

Mod name: Realistic Bees
Mod version: 1.19.0-2.5

## Bees dont change size
Changed config to make the bees the normal Minecraft size. (Changed it from 0.25 to 1.0)
Bees dont change size. Even after reloading the entire server

## ModConfig
[General]
	#When enabled, bees die after stinging a player. This takes roughly a few minutes.
	beesDieFromStingingPlayer = true
	#After a bee stings a player and its stinger is left behind, send the player a message.
	sendStungPlayerWithStingerAMessage = true
	#In order to make bees a little more common. Whenever a bee naturally spawns, the mod spawns an additional 'extraBeeSpawnsPerBee' bees.
	#Range: 0 ~ 50
	extraBeeSpawnsPerBee = 9
	#After a bee stings, it has a chance to leave its stinger inside the entity. It must be pulled out.
	beesLeaveTheirStinger = true
	#The chance the bee's stinger is pulled out by a player after right-clicking shears.
	#Range: 0.0 ~ 1.0
	chanceBeeStingerIsPulledOut = 0.5
	#The time in a seconds after a bee without its stinger dies.
	#Range: 0 ~ 600
	timeInSecondsBeeWithoutStingerDies = 60
	#The time in seconds a stinger that's left in an entity continues to pump poison.
	#Range: 0 ~ 300
	timeInSecondsStingerPumpsPoison = 30
	#This value determines the size of a bee. By default 0.25, which means they are 1/4th of their vanilla size. Set to 1.0 to disable the different bee size feature.
	#Range: 0.01 ~ 5.0
	beeSizeModifier = 1.0
	#The chance the bee's stinger lodges in the stung entity, resulting in death.
	#Range: 0.0 ~ 1.0
	chanceBeeLeavesItsStinger = 0.33
	#When enabled, bees die after stinging a mob. This takes roughly a few minutes.
	beesDieFromStingingMob = true
	#The smaller (baby) bees can sometimes do something unexpected with their AI and get suffocation damage. Preventing this damage fixes them disappearing.
	preventBeeSuffocationDamage = true
	#How many bees should be able to enter the hive in total. Minecraft's default is 3, but bees are a lot smaller so there should be more space.
	#Range: 0 ~ 50
	beeHiveBeeSpace = 3

**Comment by EightBitBBQ** [comment]
I want to make a honey farm, if any got a suggestion with the smaller bees, that would also bee great. The normal farms you see the can slip through

**Comment by ricksouth** [comment]
This should be fixed in version 2.7 of Realistic Bees. The config value wasn't being parsed correctly. Please let me know if the issue persists on your end. Thanks for opening the issue and using the mod!

https://www.curseforge.com/minecraft/mc-mods/realistic-bees/files

**Comment by EightBitBBQ** [comment]
Sadly, bees are still small. Changed value to 1.0
Deleted config. Rebooted server. Tried it all

**Comment by EightBitBBQ** [comment]
Even after modpack update 5.17, still not working.

Everything above was tried again (delete config, edit config and reboot server)

**Comment by EightBitBBQ** [comment]
I know there are a lot of issues atm.
But this issue still is going on for me. Even after TVE 5.23
Modversion is at 2.8
My current config:

[General]
	#This value determines the size of a bee. By default 0.25, which means they are 1/4th of their vanilla size. Set to 1.0 to disable the different bee size feature.
	#Range: 0.01 ~ 5.0
	beeSizeModifier = 1.0
	#When enabled, bees die after stinging a player. This takes roughly a few minutes.
	beesDieFromStingingPlayer = true
	#When enabled, bees die after stinging a mob. This takes roughly a few minutes.
	beesDieFromStingingMob = true
	#After a bee stings, it has a chance to leave its stinger inside the entity. It must be pulled out.
	beesLeaveTheirStinger = true
	#After a bee stings a player and its stinger is left behind, send the player a message.
	sendStungPlayerWithStingerAMessage = true
	#The chance the bee's stinger lodges in the stung entity, resulting in death.
	#Range: 0.0 ~ 1.0
	chanceBeeLeavesItsStinger = 0.33
	#The chance the bee's stinger is pulled out by a player after right-clicking shears.
	#Range: 0.0 ~ 1.0
	chanceBeeStingerIsPulledOut = 0.5
	#The time in seconds a stinger that's left in an entity continues to pump poison.
	#Range: 0 ~ 300
	timeInSecondsStingerPumpsPoison = 30
	#The time in a seconds after a bee without its stinger dies.
	#Range: 0 ~ 600
	timeInSecondsBeeWithoutStingerDies = 60
	#In order to make bees a little more common. Whenever a bee naturally spawns, the mod spawns an additional 'extraBeeSpawnsPerBee' bees.
	#Range: 0 ~ 50
	extraBeeSpawnsPerBee = 3
	#How many bees should be able to enter the hive in total. Minecraft's default is 3, but bees are a lot smaller so there should be more space.
	#Range: 0 ~ 50
	beeHiveBeeSpace = 3
	#The smaller (baby) bees can sometimes do something unexpected with their AI and get suffocation damage. Preventing this damage fixes them disappearing.
	preventBeeSuffocationDamage = true

I have no other mods installed next to this.
Any ETA?

**Comment by ricksouth** [comment]
This has been fixed in the latest version of Realistic Bees. Thanks for opening the issue!

https://www.curseforge.com/minecraft/mc-mods/realistic-bees/files
