### ISSUE TITLE
Right click with snowball does not auto refill

### ISSUE THREAD

**Issue by Matt577** [ricksouth/serilum-mc-mods#1185]
Minecraft version: 1.18.2
Modloader: Forge
Forge version: Forge-40.1.60
Environment: Singleplayer

Mod name: Stack Refill
Mod version: 1.18.2-2.1

Description
Throwing with, right click, snowball does not pull more from INV. Working as intended with Q

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 3.0 of Stack Refill.

https://www.curseforge.com/minecraft/mc-mods/stack-refill
