### ISSUE TITLE
Trading discounts don't work

### ISSUE THREAD

**Issue by frenchpig** [ricksouth/serilum-mc-mods#1187]
## **Information**
Minecraft version: 1.19
Modloader: Fabric
Fabric loader version: 0.11.0
Environment: Singleplayer

Mod name: Infinite Trading
Mod version: 2.2

## **Description**
I two villagers, a fletcher an a toolsmith, both of them have a little bit of discount, the more noticible is the armorsmith because it have an enchanted iron axe that is trading for arround 18 emerald (can't see well the cost because of the line that appears when it have a disscount) and it is on a discount where the axe now cost 5 emeralds, but it keeps taking the original price, and when you try to give less of the original price it make like the xp of the villager goes up, but in reality nothing happend.

(sorry if I spelled something wrong, I like the mod but english is not my primary language.)

**Comment by James103** [comment]
Does this occur if a villager has raised trade prices for a player?

To test:
1. Get a fresh villager and give it a profession.
2. Punch it or kill a nearby villager.
3. Open the trading GUI with the villager and notice that the villager has raised prices due to negative reputation.
4. Trade at the inflated price.
5. See whether only the original price is charged and not the inflated price.

**Comment by frenchpig** [comment]
No, it's the oposit, for example, the fletcher that I have trades me 32 sticks for 1 emerald, after trading a little, it says that is now trading 31 sticks for 1 emerald but when i try to trade it it doesnt take 31 stick, it take the original 32.

EDIT: I'm currently opening the game so I can test the things that you told me and post the result ASAP

**Comment by frenchpig** [comment]
> Does this occur if a villager has raised trade prices for a player?
> 
> To test:
> 
> 1. Get a fresh villager and give it a profession.
> 2. Punch it or kill a nearby villager.
> 3. Open the trading GUI with the villager and notice that the villager has raised prices due to negative reputation.
> 4. Trade at the inflated price.
> 5. See whether only the original price is charged and not the inflated price.

Tried inflating the prices and it didn't work.

It's now trading 35 sticks for 1 emerald, I put just right 35 sticks and it do the same, It's a little difficult to explain what happends with the bug but if you like I could record it and send you the video so it's easier to understand.

EDIT: Since I killed a villager now the armorer that I had inflated prices, but as usual with the bug, I doesnt tell the real price of the items, 
supposedly it sells an iron axe for 26 emeralds but when I put 27 it refuses to sell it.

For what I understand now the bug is that, villagers changes prices for items, but only visualy since the price that is asking could be lower or higer (since the expirience that I had now it tends to be higer) and when you try to trade with the visual price the game tries to do it but fails, making the xp bar of the villager "go up" (not really it's only visual) and not trading anything.

**Comment by ricksouth** [comment]
This has been fixed in version 3.0 of Infinite Trading. It has completely been rewritten. How the offers are reset has changed and it now accounts for demand correctly. Thanks for giving the mod a try and opening the issue!

https://www.curseforge.com/minecraft/mc-mods/infinite-trading-fabric/
