### ISSUE TITLE
Double Doors works with Dramatic Doors Mods

### ISSUE THREAD

**Issue by ScorchedPork** [ricksouth/serilum-mc-mods#1188]
## **Information**
Add functionality of working with Dramatic Doors mod.

## **Feature description**
When building a grand entrance with two doors with Dramatic Doors mod, it would be great to have the ability to have both open at once.

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! Support for modded doors has been added in version 5.3 of Double Doors.

https://curseforge.com/minecraft/mc-mods/double-doors/files
