### ISSUE TITLE
Crashes when I create a world

### ISSUE THREAD

**Issue by chelu671x** [ricksouth/serilum-mc-mods#1190]
## **Information**
Minecraft version: xx.xx.xx
Modloader: Forge / Fabric
Forge version: xx.xx.xx  OR  Fabric loader version: x.xx.x
Environment: Singleplayer / Multiplayer

Mod name: Mod
Mod version: x.x

## **Description**
Hey! This happened..
I can load MC but as soon as I create a world so I can use starter kit, once it gets to 100% the game crashes. I've tested it with AE2 and w/out AE2, when I didn't have AE2, it loaded. I didn't know if I should bring this to AE2 or here so I brought it here since the error said Collective

## **Crash report**
If available.
---- Minecraft Crash Report ----
// There are four lights!

Time: 7/20/22, 10:15 PM
Description: Exception ticking world

java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because the return value of "java.util.HashMap.get(Object)" is null
	at com.natamus.collective_fabric.events.CollectiveEvents.onWorldTick(CollectiveEvents.java:38)
	at com.natamus.collective_fabric.CollectiveFabric.lambda$onInitialize$1(CollectiveFabric.java:27)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$4(ServerTickEvents.java:84)
	at net.minecraft.class_3218.handler$dhf000$startWorldTick(class_3218.java:10723)
	at net.minecraft.class_3218.method_18765(class_3218.java:279)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.natamus.collective_fabric.events.CollectiveEvents.onWorldTick(CollectiveEvents.java:38)
	at com.natamus.collective_fabric.CollectiveFabric.lambda$onInitialize$1(CollectiveFabric.java:27)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$4(ServerTickEvents.java:84)
	at net.minecraft.class_3218.handler$dhf000$startWorldTick(class_3218.java:10723)
	at net.minecraft.class_3218.method_18765(class_3218.java:279)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 0
	Level dimension: ae2:spatial_storage
	Derived: true
	Level spawn location: World: (0,97,0), Section: (at 0,1,0 in 0,6,0; chunk contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1 game time, 1 day time
	Level name: New World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 29527 (now: false), thunder time: 57688 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1392752624 bytes (1328 MiB) / 3875536896 bytes (3696 MiB) up to 10536091648 bytes (10048 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600 6-Core Processor              
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: unknown
	Frequency (GHz): 3.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 3060 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2486
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7196
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 2.40
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 2.40
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 37514.91
	Virtual memory used (MB): 26268.25
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 581.81
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx10048m -Xms256m
	Fabric Mods: 
		additionaladditions: Additional Additions 5.0.1
		additionalstructures: Additional Structures 4.0.0
		adorn: Adorn 3.6.0+1.19
		advdebug: Advancements Debug 2.3.0
		adventurez: AdventureZ 1.4.14
		ae2: Applied Energistics 2 12.0.1-alpha
			noindium: No Indium? 1.0.2+1.18.2
		ae2wtlib: AE2WTLib 12.0.2-alpha
		ambientsounds: Ambiend Sounds (Fabric) 5.2.0
		animal_feeding_trough: Animal Feeding Trough 1.0.3+1.19
		animatica: Animatica 0.5+1.19
		another_furniture: Another Furniture 2.0.1-1.19
		appleskin: AppleSkin 2.4.0+mc1.19
		architects_palette: Architect's Palette Fabric 2.1.1
		architectury: Architectury 5.9.31
		artifacts: Artifacts 7.1.1+fabric
			com_github_llamalad7_mixinextras: MixinExtras 0.0.11
			expandability: ExpandAbility 6.0.0
			step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		attributefix: AttributeFix 15.0.2
		autoconfig1u: Auto Config v1 Updated 3.4.0
		auudio: Auudio 1.0.3
		axolotlitemfix: Axolotl Item Fix 1.1.3
		badpackets: Bad Packets 0.1.2
		bcc: BetterCompatibilityChecker fabric-2.0.1-build.15
		bclib: BCLib 2.0.16
		beaconoverhaul: Beacon Overhaul 1.7.0+1.19
			fabric-api-base: Fabric API Base 0.4.9+e62f51a3a9
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.27+7fe97409a9
			reach-entity-attributes: Reach Entity Attributes 2.3.0
		bedbenefits: BedBenefits 7.0.2
		betteradvancements: Better Advancements 0.2.1.134
		betteranimalsplus: Better Animals Plus 1.19-11.0.7
		betterend: Better End 2.0.9
		betterf3: BetterF3 1.3.1
		betternether: Better Nether 7.0.6
		betterthirdperson: Better Third Person 1.8.1
		bhmenu: BHMenu-Fabric 1.19-1.3
		biomeinfo: BiomeInfo 1.19-11
		biomemakeover: Biome Makeover 1.19-1.5.9
		blockus: Blockus 2.5.1+1.19
			terraform-wood-api-v1: Terraform Wood API (v1) 4.1.0
		blur: Blur (Fabric) 2.6.0
			satin: Satin 1.8.0
		bno: Basic Nether Ores 1.19-8.0.0-Fabric
		bookshelf: Bookshelf 14.1.7
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.4.1-1.19
			maelstrom_library: Maelstrom Library 1.3-1.19-pre1
			multipart_entities: MultipartEntities 1.2-1.19-pre1
		byg: Oh The Biomes You'll Go 2.0.0.7
		can-i-mine-this-block: cAn i MiNe thIS bLOCk? 1.3.0
		capybara: Capybara 1.0.5
		cardinal-components: Cardinal Components API 5.0.1
			cardinal-components-base: Cardinal Components API (base) 5.0.1
			cardinal-components-block: Cardinal Components API (blocks) 5.0.1
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.1
			cardinal-components-entity: Cardinal Components API (entities) 5.0.1
			cardinal-components-item: Cardinal Components API (items) 5.0.1
			cardinal-components-level: Cardinal Components API (world saves) 5.0.1
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.0.1
			cardinal-components-world: Cardinal Components API (worlds) 5.0.1
		carrier: Carrier 1.11.0
		cem: Custom Entity Models 0.7.1
		charm: Charm 4.1.2
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		charmofundying: Charm of Undying 6.0.0-beta.2+1.19
		charmonium: Charmonium 4.1.0
		cherishedworlds: Cherished Worlds 6.0.0-beta.2+1.19
		citresewn: CIT Resewn 1.1.1+1.19
			citresewn-defaults: CIT Resewn: Defaults 1.1.1+1.19
		cleancut: CleanCut 1.19-5.0-fabric
		cloth-api: Cloth API 4.0.65
			cloth-basic-math: cloth-basic-math 0.6.1
			cloth-client-events-v0: Cloth Client Events v0 4.0.65
			cloth-common-events-v1: Cloth Common Events v1 4.0.65
			cloth-scissors-api-v1: Cloth Scissors API v1 4.0.65
			cloth-utils-v1: Cloth Utils v1 4.0.65
		cloth-config: Cloth Config v6 7.0.73
		clumps: Clumps 9.0.0+3
		collective-fabric: Collective (Fabric) 4.27
			fiber: fiber 0.23.0-2
		colormatic: Colormatic 3.1.2+mc.1.19
		comforts: Comforts 6.0.0-beta.4+1.19
			spectrelib: SpectreLib 0.8.1+1.19
		completeconfig: CompleteConfig 2.0.0
			completeconfig-base: completeconfig-base 2.0.0
			completeconfig-gui-cloth: completeconfig-gui-cloth 2.0.0
			completeconfig-gui-coat: completeconfig-gui-coat 2.0.0
		continuity: Continuity 2.0.0+1.19
		controlling: Controlling For Fabric 10.0+3
		coralreef: Coral Reef 1.19-1.0.1
		crawl: Crawl 0.11.0
			mm: Manningham Mills 2.3
		creativecore: CreativeCore (Fabric) 2.7.2
		crusade: Crusade 1.2.8
		cull-less-leaves: Cull Less Leaves 1.0.4
			conditional-mixin: conditional mixin 0.3.0
		cullleaves: Cull Leaves 2.3.4
		darkpaintings: DarkPaintings 11.0.2
		darkutils: DarkUtilities 11.0.2
		dashloader: DashLoader 4.0.0+1.19
			com_github_luben_zstd-jni: zstd-jni 1.5.2-2
			dev_quantumfusion_hyphen: Hyphen 0.2.2
			dev_quantumfusion_taski: Taski 1.1.0
		dawn: Dawn API 3.5.0
		deepslatecutting: Deepslate Cutting 1.4.0
		diggusmaximus: Diggus Maximus 1.5.6-1.19
			kyrptconfig: Kyrpt Config 1.4.6-1.19
				blue_endless_jankson: jankson 1.2.1
		dragonloot: DragonLoot 1.1.1
		drippyloadingscreen: Drippy Loading Screen 1.6.4
		duckling: Duckling 2.0.3
		dungeons_arise: When Dungeons Arise 2.1.51
		dustrial_decor: Dustrial Decor 0.5
		dynamicfps: Dynamic FPS 2.2.0
		dynamicsoundfilters: Dynamic Sound Filters 1.3.0+1.19
		earthtojavamobs: Earth2Java 1.9.2
		easymagic: Easy Magic 4.0.0
		ecologics: Ecologics 2.1.4
		edenring: EdenRing 0.6.3
		effective: Effective 1.2.2
		ellemes_container_lib: Ellemes' Container Library 2.0.1
		enchdesc: EnchantmentDescriptions 11.0.4
		enhanced_attack_indicator: Enhanced Attack Indicator 1.0.4+1.19
		enhancedcelestials: Enhanced Celestials 2.0.0.0
		enhancedvisuals: Enhanced Visuals (Fabric) 1.5.7
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		equipmentcompare: Equipment Compare 1.3.1
		expandeddelight: Expanded Delight 0.2.1
		expandedstorage: Expanded Storage 8.0.1
		extended_armor_bars: Extended Armor Bars 1.2.1
		extragenerators: Extra Generators 1.2.1-BETA+1.19
			team_reborn_energy: Energy 2.2.0
		fabric: Fabric API 0.57.0+1.19
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.7+9ff28f40a9
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.14+b2a4a624a9
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.18+9ff28f40a9
			fabric-command-api-v1: Fabric Command API (v1) 1.2.6+f71b366fa9
			fabric-command-api-v2: Fabric Command API (v2) 2.1.2+0d55f585a9
			fabric-commands-v0: Fabric Commands (v0) 0.2.23+df3654b3a9
			fabric-containers-v0: Fabric Containers (v0) 0.1.27+df3654b3a9
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.0+07df213ea9
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d24a9
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4aa9
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.1+a680b9b4a9
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.28+a6d2f785a9
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f40a9
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f40a9
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.25+df3654b3a9
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+18990361a9
			fabric-item-api-v1: Fabric Item API (v1) 1.5.4+767db26ea9
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.25+9ff28f40a9
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.18+9ff28f40a9
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.16+df3654b3a9
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+33fbc738a9
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.0+03a4e568a9
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.3+9e7660c6a9
			fabric-message-api-v1: Fabric Message API (v1) 1.0.1+513f4a59a9
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.10+33fbc738a9
			fabric-models-v0: Fabric Models (v0) 0.3.15+9ff28f40a9
			fabric-networking-v0: Fabric Networking (v0) 0.3.14+df3654b3a9
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.7+9ff28f40a9
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553aa9
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.17+23c4cfefa9
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.8+9ff28f40a9
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.9+1f92344ea9
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.18+df3654b3a9
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f40a9
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f40a9
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.20+df3654b3a9
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.14+9ff28f40a9
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a3a9
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.5+a6d2f785a9
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.24+f05effafa9
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.6+9ff28f40a9
			fabric-textures-v0: Fabric Textures (v0) 1.0.18+9ff28f40a9
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.9+e62f51a3a9
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c6a9
		fabric-language-kotlin: Fabric Language Kotlin 1.8.1+kotlin.1.7.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.3
		fabricloader: Fabric Loader 0.14.8
		fallingleaves: Falling Leaves 1.12.1+1.19
		fallingtree: FallingTree 3.7.4
		fancymenu: FancyMenu 2.11.0
		farmersdelight: Farmer's Delight 1.19-0.3.0
		farmersknives: Farmer's Knives 2.0
		ferritecore: FerriteCore 4.2.1
		forgeconfigapiport: Forge Config API Port 4.0.0
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		frame: Frame 0.22.2+1.19
			frame-api-base: Frame Base 0.2.0
			frame-blocks-v0: Frame Blocks (v0) 0.1.2
			frame-config-v0: Frame Config (v0) 0.2.1
			frame-content-registries-v0: Frame Content Registries (v0) 0.4.0+2876b511a9
			frame-game-rules-v0: Frame Game Rules (v0) 0.2.3
			frame-items-v0: Frame Items (v0) 0.1.2
			frame-loot-tables-v0: Frame Loot Tables (v0) 0.1.4
			frame-rendering-v0: Frame Rendering (v0) 0.1.4
			frame-tabbed-item-groups-v0: Frame Tabbed Item Groups (v0) 0.2.1
			frame-toymaker-v0: Frame Data Generation Helpers (v0) 0.6.0+c2d5b470a9
			frame-woods-v0: Frame Woods (v0) 0.1.0+ea73347fa9
		friendsandfoes: Friends&Foes 1.5.5
		ftbchunks: FTB Chunks 1900.3.7-build.154
		ftblibrary: FTB Library 1900.3.7-build.131
		ftbteams: FTB Teams 1900.2.7-build.56
		fwaystones: Fabric Waystones 3.0.2+mc1.19
		geckolib3: Geckolib 3.1.5
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		geodes: More Geodes 1.4.4
		goblintraders: Goblin Traders 1.5.2
		graveyard: The Graveyard 1.10
		guardvillagers: Guard Villagers Fabric 1.19-1.0.16
		harvest_scythes: Harvest Scythes 2.5.3
		healthoverlay: Health Overlay 7.0.0
		highlighter: Highlighter 1.1.2
		iceberg: Iceberg 1.0.38
		identity: Identity 2.5.0-1.19
			omega-config: OmegaConfig 1.2.3-1.18.1
		immersive_weathering: Immersive Weathering 1.0.1-1.19_SNAPSHOT
		impactfulweather: Biome Particle Weather 4.0.0
		imst: Immersive structures 2.0.2
		indium: Indium 1.0.6+mc1.19
		infusion_table: Infusion Table 1.1.0
		inmis: Inmis 2.7.0-1.19
		inventoryhud: Inventory HUD + 3.4.2
		iris: Iris 1.2.5
			org_anarres_jcpp: jcpp 1.4.14
		itemmodelfix: Item Model Fix 1.0.3+1.19
		jamlib: JamLib 0.1.0
		java: OpenJDK 64-Bit Server VM 17
		journeymap: Journeymap 5.8.5rc2
			journeymap-api-fabric: JourneyMap API 1.19-1.8-fabric-SNAPSHOT
		just_end_anchor: Just An End Anchor 1.0.2
		kibe: Kibe 1.9.8-BETA+1.19
			playerabilitylib: Pal 1.6.0
		konkrete: Konkrete 1.3.3
		krypton: Krypton 0.2.0
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		lambdabettergrass: LambdaBetterGrass 1.3.0+1.19
			spruceui: SpruceUI 4.0.0+1.19
		lambdynlights: LambDynamicLights 2.1.2+1.19
			pride: Pride Lib 1.1.2+1.19
		lazydfu: LazyDFU 0.1.3
		lithium: Lithium 0.8.1
		magnumtorch: Magnum Torch 4.0.1
		mavm: More Axolotl Variants Mod 1.1.0
		memoryleakfix: memory Leak Fix 1.19-0.5.1
		merchantmarkers: Merchant Markers 1.2.2
		midnightlib: MidnightLib 0.5.2
		minecraft: Minecraft 1.19
		modid: Creatures Of The Snow 2.2.0+1.19
		modmenu: Mod Menu 4.0.4
		moonlight: Moonlight 1.19-2.0.2
		more-axolotls: More Axolotls 1.0.2
		more_babies: More Babies 0.5.2
		moremcmeta: MoreMcmeta 1.19-3.0.5
		moretotems: More Totems 2.11.0
		morevillagers: More Villagers 4.0.2
		mousetweaks: Mouse Tweaks 2.22
		mousewheelie: Mouse Wheelie 1.10.2+mc1.19-pre1
			amecsapi: Amecs API 1.3.6+mc22w17a
			coat: Coat 1.0.0-beta.18+mc22w17a
			tweed4_annotated: tweed4_annotated 1.3.1+mc22w17a
			tweed4_base: tweed4_base 1.6.0+mc22w17a
			tweed4_data: tweed4_data 1.2.1+mc22w17a
			tweed4_data_hjson: tweed4_data_hjson 1.1.1+mc22w17a
			tweed4_tailor_coat: tweed4_tailor_coat 1.1.3+mc22w17a
			tweed4_tailor_screen: tweed4_tailor_screen 1.1.1+mc22w17a
		musicplayer: Music Player 2.4.0.5
		mythicmounts: Mythic Mounts 1.19-7.0
		naturalist: Naturalist 2.0.1
		naturescompass: Nature's Compass 1.19-2.0.4-fabric
		nears: Nears 1.2.2
		nochatreports: No Chat Reports 1.19-v1.2.3
		notenoughanimations: NotEnoughAnimations 1.6.0
		onsoulfire: On Soul Fire 1.19-2
		openloader: OpenLoader 13.0.1
		optigui: OptiGUI 1.1.1
			org_apache_commons_commons-text: commons-text 1.9
		oxidized: Oxidized 1.7.1
		paintings: Paintings++ 10.0.0.0
		patchouli: Patchouli 1.19-74-FABRIC
		pigpen: PigPen 9.0.1
		plushies: Plushie Mod 1.2
		puzzle: Puzzle 1.3.4-1.19
			puzzle-base: Puzzle Base 1.3.4-1.19
			puzzle-gui: Puzzle GUI 1.3.4-1.19
			puzzle-models: Puzzle Models 1.3.4-1.19
			puzzle-splashscreen: Puzzle Splash Screen 1.3.4-1.19
		puzzleslib: Puzzles Lib 4.0.17
		quartzelv: Quartz Elevator 2.1.3+1.19
		randomium: Randomium 1.19-1.12
		reborncore: Reborn Core 5.3.2
		reeses-sodium-options: Reese's Sodium Options 1.4.3+mc1.19-build.43
		repurposed_structures: Repurposed Structures 6.1.1+1.19
		rightclickharvest: Right Click Harvest 2.2.1
		ringsofascension: Rings of Ascension 1.0
		rocks: This Rocks! 1.6.1
		roughlyenoughitems: Roughly Enough Items 9.1.517
		rpgstats: RPGStats 4.3.15+1.19
			libgui: LibGui 6.0.0+1.19
				jankson: Jankson 4.1.1+j1.2.1
				libninepatch: LibNinePatch 1.1.0
			server_translations_api: Server Translations API 1.4.14+1.19-rc2
				packet_tweaker: Packet Tweaker 0.3.0+1.18.2
		runelic: Runelic 12.0.1
		sdrp: Simple Discord Rich Presence 2.0.0-build.13+mc1.19
		seasons: Fabric Seasons 1.4-BETA+1.19
		secretrooms: Secret Rooms 1.3.2+1.19
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2
		simplylight: Simply Light 1.19-1.4.2
		skinlayers: 3d Skin Layers 1.4.7-mc1.19
		smoothboot: Smooth Boot 1.19-1.7.1
		sodium: Sodium 0.4.2+build.16
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.5+mc1.19-build.43
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		spark: spark 1.9.26
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		spirit: Spirit 2.1.2
		starlight: Starlight 1.1.1+fabric.ae22326
		starterkit-fabric: Starter Kit (Fabric) 3.3
		steves_vanilla: Steves Vanilla 1.0.0+1.19
		stoneholm: Stoneholm 1.4.4
		structory: Structory 1.0.1
		t_and_t: Towns and Towers - Structure Add-on 1.8
		techreborn: Tech Reborn 5.3.2
		terrablender: TerraBlender 2.0.0.120
		the_bumblezone: The Bumblezone - Fabric 6.0.1+1.19
			fake-player-api: Fake Player API 0.3.0
		thonkutil: ThonkUtil 2.15.3+1.19
			thonkutil-base: ThonkUtil Base 1.13.1+575521ba57
			thonkutil-capes-v1: ThonkUtil Capes (v1) 1.4.1+7ce8ef6257
			thonkutil-coords-v1: ThonkUtil Coords (v1) 1.1.1+8ff533c957
			thonkutil-customization-v1: ThonkUtil Customization (v1) 1.1.1+8ff533c957
			thonkutil-legacy: ThonkUtil Legacy 1.1.1+5d4263f557
			thonkutil-modchecker-v1: ThonkUtil ModChecker (v1) 1.1.1+8ff533c957
			thonkutil-potions-v0: ThonkUtil Potions (v0) 1.5.1+8ff533c957
			thonkutil-titlescreen-v1: ThonkUtil TitleScreen (v1) 1.2.1+8ff533c957
			thonkutil-trades-v1: ThonkUtil Trades (v1) 1.2.1+8ff533c957
		tipsmod: Tips 6.0.1
		toms_storage: Tom's Simple Storage Mod 1.3.5
		toolstats: ToolStats 10.0.1
		tooltipfix: ToolTip Fix 1.0.5-1.19
		tradingpost: Trading Post 4.0.0
		transparent: Transparent 5.1.0
		trinkets: Trinkets 3.4.0
		twigs: Twigs 2.0.0-beta.8+1.19
		universal_ores: Universal Ores 1.4.1
		upgradedshulkers: Upgraded Shulkers 1.1.2-1.19
			shulkerutils: shulkerutils 1.0.4-1.18
		uteamcore: U Team Core 4.0.0.4
		villagernames: Villager Names 4.0.5
		visuality: Visuality 0.5.0
		voidtotem: Void Totem 2.0.0
		voidz: VoidZ 1.0.8
		wandering_collector: Wandering Collector 1.1.3+mc1.19
		wardentools: Warden Tools 1.0
		windchimes: Windchimes 1.2.1
		wmitaf: WMITAF 3.0.0
		wolveswitharmor: Wolves With Armor 1.8.0-1.19
			maybe-data: Maybe data 1.3.2-1.19-rc2
			static-content: Static Content 1.0.1-1.16.2
				staticdata: Static Data 1.1.2
		wthit: wthit 5.6.1
		xp_storage: XP Storage 1.4.3+1.19
		xp_storage_trinkets: XP Storage - Trinkets 0.1+1.19
		yigd: You're in Grave Danger 1.4.1
		zoomify: Zoomify 1.7.1
			dev_isxander_settxi_settxi-core: settxi-core 2.4.0
			dev_isxander_settxi_settxi-kotlinx-serialization: settxi-kotlinx-serialization 2.4.0
			settxi-gui-cloth-config: Settxi Gui (Cloth Config) 2.4.0
	Loaded Shaderpack: (off)
	Server Running: true
	Player Count: 0 / 8; []
	Data Packs: vanilla, Fabric Mods
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: fabric-loader-0.14.8-1.19

**Comment by shartte** [comment]
See https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/6426

**Comment by ricksouth** [comment]
This has been fixed in the latest AE2 version. Thanks to the AE team for finding and fixing the problem.
