### ISSUE TITLE
Mod Doesnt Work, Forge 1.19

### ISSUE THREAD

**Issue by Alphashrimp** [ricksouth/serilum-mc-mods#1192]
This is for Tree Harvester
Like another post i saw, the time it takes to mine a tree while shifting is slower, but it just destroys normally
a gif/clip of this happening:
https://giphy.com/gifs/ZKVE26zFyzYJO08NQG

The server mod list is this if that helps:

Corpse
Serene Seasons
Easy Villagers
Simple Storage Network
Advanced Compass
Guard Villagers
Tree Harvester

**Comment by ricksouth** [comment]
Thanks for opening the bug report! Which tree did you chop? Is this on Forge or Fabric?

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 7.2 of Tree Harvester.

https://curseforge.com/minecraft/mc-mods/tree-harvester/files
