### ISSUE TITLE
Special Letters

### ISSUE THREAD

**Issue by SuomiIkuisesti** [ricksouth/serilum-mc-mods#1193]
## **Information**
Minecraft version: 1.18.2
Modloader: Forge
Forge version: 40.1.0 
Environment: Multiplayer

Mod name: Areas
Mod version: 2.9

## **Question**
Non-English letters like ñ, ğ, ş or ı don't work with the mod. When you name an area "Yañı", it does not work. But when you change it to Yani, it starts to function. Is it purposeful? If not, can you fix it?

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 5.0 of Areas, alongside other bug fixes and QoL features. Apologies it took so long for me to get to.

https://www.curseforge.com/minecraft/mc-mods/areas/files
