### ISSUE TITLE
"mustHaveItemsInInventoryForCreation" set to false not working

### ISSUE THREAD

**Issue by mateoromero2000** [ricksouth/serilum-mc-mods#1201]
## **Information**
Minecraft version: 1.18.2
Fabric loader version: 1.18.2
Environment: Singleplayer and Multiplayer

Mod name:  Your Items Are Safe
Mod version: [youritemsaresafe-fabric_1.18.x-1.1.jar](https://www.curseforge.com/minecraft/mc-mods/your-items-are-safe-fabric/files/3634293)

## **Description**

I changed the config file, setting "mustHaveItemsInInventoryForCreation" to false, but it still says: "Your items are not safe due to having insufficient materials. Missing: 11 planks."

Also, I can't change the config  via the "mod menu" mod.

![Screenshot 2022-07-25 231050](https://user-images.githubusercontent.com/107862923/180909833-b7d54f94-7a12-481c-a19c-6cbb71ad0764.png)

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 2.0 of Your Items Are Safe. Apologies it took so long for me to get to.

https://www.curseforge.com/minecraft/mc-mods/your-items-are-safe-fabric
