### ISSUE TITLE
[Advancement Screenshot / Fabric] No screenshots are taken

### ISSUE THREAD

**Issue by Paraxdq** [ricksouth/serilum-mc-mods#1204]
## **Information**
Minecraft version: 1.18.2
Modloader: Fabric
Fabric loader version: 0.14.8
Environment: Singleplayer

Mod name: Advancement Screenshot (Fabric)
Mod version: 3.2

## **Description**
Playing the Modpack Valhelsia Enhanced Vanilla, just started and noticed the mod doesn't make screenshots after getting for example Monster Hunter or Sweet Dreams.

## **Crash report**
No crash, it acts as if the mod is not availabe.

Log:
[2022-07-25-1.log](https://github.com/ricksouth/serilum-mc-mods/files/9199819/2022-07-25-1.log)

**Comment by ricksouth** [comment]
This has been fixed in the latest version of Advancement Screenshot. The modpack will have to update to see the changes. Thanks for opening the issue!

https://www.curseforge.com/minecraft/mc-mods/advancement-screenshot-fabric/files
