### ISSUE TITLE
Update Full Brightness Toggle (Fabric) 1.19.x

### ISSUE THREAD

**Issue by PweSol** [ricksouth/serilum-mc-mods#1205]
## **Information**
Mod name: [Full Brightness Toggle (Fabric)](https://www.curseforge.com/minecraft/mc-mods/full-brightness-toggle-fabric)

## **Feature description**
I've had this amazing idea. Update for 1.19.x would be glorious!

**Comment by ricksouth** [comment]
There were some difficulties updating. I'll be doing another attempt in the near future. I appreciate the interest!
