### ISSUE TITLE
Forge Version 42.0.1 fails to load. Brings back Launcher.

### ISSUE THREAD

**Issue by Ahley411** [ricksouth/serilum-mc-mods#1209]
## **Information**
Minecraft version: 1.19.1
Modloader: Forge
Forge version: 42.0.0 ~42.0.1
Environment: Singleplayer

Mod name: Configurable Extra Mob Drops (Forge)
Mod version: configurableextramobdrops_1.19.1-2.1

## **Description**
![crash](https://user-images.githubusercontent.com/72476191/181860892-af2370d7-1db0-4555-8a60-c08e9de36d81.jpg)

Fresh install on 42.+ and quick send back Minecraft Launcher. No crash report available.

Edit: After much searching have failed, I reinstall everything and installed OptiFine. Got this error. So possibly the cause of this. I thought I used optifine with this before.

**Comment by James103** [comment]
Do you have the latest.log from reproducing this issue? If so, can you please post it here?

**Comment by Ahley411** [comment]
> Do you have the latest.log from reproducing this issue? If so, can you please post it here?

Sadly, after many hours of going through stuff, I might have found that this mod is incompatible with OptiFine. Ill close this.

**Comment by ricksouth** [comment]
With an error log, I can take a look at fixing it. At the moment, all I can say is that Optifine causes many unforseen issues with mods. I can't reproduce the issue locally unfortunately. Thanks for the interest in using the mod nonetheless.
