### ISSUE TITLE
The leaves only fall in a chunk [Tree Harvester]

### ISSUE THREAD

**Issue by Yupoman** [ricksouth/serilum-mc-mods#1210]
Minecraft version: 1.18.2
Modloader: Forge
Forge version: 40.1.19
Environment: Singleplayer / Multiplayer

Mod name: Tree Harvester
Mod version: 5.1

When the tree is big, only the closest leaves within radius fall (I don't know if it's exactly a chunk or how much). The rest falls, but at normal minecraft speed.

![2022-07-29_21 04 11](https://user-images.githubusercontent.com/70600879/181862504-c425c60c-f6b9-441d-b809-d8fe122e405a.png)

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 7.2 of Tree Harvester.

https://curseforge.com/minecraft/mc-mods/tree-harvester/files
