### ISSUE TITLE
Stack Refill 2.4 and Recast 1.9 need Collective 4.36 but do not recognise Collective 4.36

### ISSUE THREAD

**Issue by ayykiri** [ricksouth/serilum-mc-mods#1213]
## **Information**
Minecraft version: 1.19.1
Modloader: Fabric
Forge version: xx.xx.xx  OR  Fabric loader version: x.xx.x
Environment: Singleplayer / Multiplayer

Mod name: Stack Refill and Recast
Mod version: 2.4 and 1.9

## **Description**
as title says: if i try to launch these two mods with Collective 4.36, most of the new 1.19.1 versions of your mods do not show errors except these two. These two report in the error report: ~"need collective 4.36", except that version is installed, using an older version of collective does not fix.

## **Crash report**
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Stack Refill (Fabric)' (stackrefill-fabric) 2.4 with any version that is compatible with:
		 - collective-fabric 4.36
	 - Replace mod 'Recast (Fabric)' (recast-fabric) 1.9 with any version that is compatible with:
		 - collective-fabric 4.36
Unmet dependency listing:
	 - Mod 'Recast (Fabric)' (recast-fabric) 1.9 requires an unsatisfiable version range of mod 'Collective (Fabric)' (collective-fabric), but only the wrong version is present: 4.36!
	 - Mod 'Stack Refill (Fabric)' (stackrefill-fabric) 2.4 requires an unsatisfiable version range of mod 'Collective (Fabric)' (collective-fabric), but only the wrong version is present: 4.36!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by ricksouth** [comment]
Thanks for letting me know. I'm uploading new versions right now, not sure how the error slipped into the code but I'll be double checking that for a while. Appreciate it!
