### ISSUE TITLE
Combine All Serilum into 1 Mods with Toggle for each Feature

### ISSUE THREAD

**Issue by ardissaps** [ricksouth/serilum-mc-mods#1217]
## **Information**
Consider combining aall Serilum into 1 mods with toggle for each feature modification.

## **Feature description**
Similiar with [Fabrication](https://www.curseforge.com/minecraft/mc-mods/fabrication).

**Comment by ricksouth** [comment]
This exists here: https://www.curseforge.com/minecraft/mc-mods/the-vanilla-experience but is unfortunately outdated. I'll keep this open and keep you updated when I give it another attempt. Thanks for the interest.
