### ISSUE TITLE
JMH crash with TOP

### ISSUE THREAD

**Issue by GabrielToth** [ricksouth/serilum-mc-mods#1219]
Minecraft version: 1.18.2
Modloader: Fabric
Fabric loader version: 0.14.8
Environment: Singleplayer

Mod name: Just Mob Heads
Mod version: 5.4 & 5.7

The games crash with TheOneProbe when i look to Charged Creeper's head.

**Comment by ricksouth** [comment]
Do you have the crash log? And did you open an issue at the TheOneProbe repo?
