### ISSUE TITLE
Spaces Cause Area not to be created

### ISSUE THREAD

**Issue by georgewesley** [ricksouth/serilum-mc-mods#1221]
## **Information**
Minecraft version: 1.18.2
Modloader: Forge 
Forge version: 40.1.68
Environment:  Multiplayer

Mod name: Areas
Mod version: 2.9

## **Description**
It seems as though whenever I use spaces in the names of areas they do not get created. For example: [Area] 50 VillageOnHill does get created but [Area] 50 Village On Hill does not get created. 

## **Crash report**
If available.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 5.0 of Areas, alongside other bug fixes and QoL features. Apologies it took so long for me to get to.

https://www.curseforge.com/minecraft/mc-mods/areas/files
