### ISSUE TITLE
Is Automatic Doors client-side or server-side?

### ISSUE THREAD

**Issue by ruddsix** [ricksouth/serilum-mc-mods#1223]
Minecraft version: 1.19.1
Modloader: Fabric
Fabric loader version: 0.14.8
Environment: Multiplayer

Mod name: Automatic Doors
Mod version: 2.7

Is Automatic Doors client-side only or server-side? There isn't anything on the mod page or in Mod Menu specifying.

**Comment by ricksouth** [comment]
Thanks for the interest. The mod is server-side only. But of course if you want it in single player it's also on the client. All client-only mods are specified, the rest is on the server or both.
