### ISSUE TITLE
Navigation bar has useless horizontal scrollbar, wasting screen space

### ISSUE THREAD

**Issue by James103** [ricksouth/serilum-mc-mods#1242]
## **Information**
Website: https://serilum.com/mods/

## **Expected result**
The navigation bar should not have a horizontal scroll bar with a large enough screen size.
![image](https://user-images.githubusercontent.com/37945304/183803611-6e71b077-b68e-4053-82b7-b70aaebdda1b.png)

## **Actual result**
The navigation bar has a horizontal scroll bar present regardless of screen size.
![image](https://user-images.githubusercontent.com/37945304/183803300-0b10255f-ede7-4cac-bdd2-b5843ffd33a9.png)

**Comment by ricksouth** [comment]
Interesting! I can't see the scrollbar myself. Which browser/OS are you using?

**Comment by ricksouth** [comment]
I believe I've fixed it, but as I'm unable to see the big scrollbar I can't check it. Could you let me know? :)

**Comment by James103** [comment]
The issue appears to be fixed for me. Closing.
Browser version: Chrome `104.0.5112.81 (Official Build) (64-bit) (cohort: Stable)`
![image](https://user-images.githubusercontent.com/37945304/183893338-100fcd0f-fe51-4351-95ee-e379fdd5827d.png)

**Comment by ricksouth** [comment]
Thanks for letting me know! Appreciate it. Also the other comments on the issue. Helps a lot. Almost done with backend stuff and then going to fix issues and add features.
