### ISSUE TITLE
Clicking on items in mod list on website opens corresponding pages immediately, instead of on mouse release

### ISSUE THREAD

**Issue by James103** [ricksouth/serilum-mc-mods#1243]
## **Information**
Website: https://serilum.com/mods/
OS: `Windows 10 Version 21H1 (Build 19043.1826)`
Browser: Chrome `104.0.5112.81 (Official Build) (64-bit) (cohort: Stable)`

## **Expected result**
As per the standard, clicking on an item on the mod list for the website should only navigate to the corresponding CurseForge page when releasing the mouse button.
If clicking on the "CL", the changelog for the mod pops up on releasing the mouse button.

## **Actual result**
As per the standard, clicking on an item on the mod list for the website immediately navigates to the corresponding CurseForge page when pressing the mouse button.
If clicking on the "CL", the changelog for the mod pops up immediately on pressing the mouse button.
The buttons that say "1.12", "1.16", "1.18", "1.19" on them, as well as the icons for the Collective and Fabric API dependencies, open the corresponding Curseforge pages on mouse release, as expected.

## **To reproduce**
1. Open https://serilum.com/mods/
2. Click on an item in the mod listing.
3. The corresponding CurseForge page opens when the mouse button is pressed, not when it is released.

**Comment by ricksouth** [comment]
Thanks! Fixed in the latest code push.
