### ISSUE TITLE
Beautified Chat [Server] (Fabric) Not working properly

### ISSUE THREAD

**Issue by BioTechproject27** [ricksouth/serilum-mc-mods#1244]
Minecraft version: 1.18.1
Modloader: Fabric
Fabric loader version: 0.14.8
Environment: Multiplayer

Mod name: Beautified Chat [Server] (Fabric)
Mod version: beautifiedchatserver-fabric_1.18.x-1.2.jar

Description:
So, for players that send a msg they see their msg formatted, but they don't see it formatted when it comes from other players.

**Comment by EightBitBBQ** [comment]
This issue was the same on Forge.
There have been multiple updates for fabric / the mod itself. 
Does this issue still occure
