### ISSUE TITLE
[Nutritious Milk] No saturation level applied, only hunger level increased.

### ISSUE THREAD

**Issue by RedBeast1959** [ricksouth/serilum-mc-mods#1245]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 43.0.7
Environment: Singleplayer

Mod name: Nutritious Milk Mod
Mod version: nutritiousmilk_1.19.2-2.0.jar

## **Description**
It seems drinking milk only increases hunger level, not the saturation level. Isolating mods step by step, checking with Appleskin mod(which shows saturation level), now I'm certain that milk saturation level increasing function is broken.

**Comment by ricksouth** [comment]
I've changed how saturation is applied in version 2.1 of Nutritious Milk. This should fix the problem you were having. Thanks for giving the mod a try and opening the issue!

https://www.curseforge.com/minecraft/mc-mods/nutritious-milk
