### ISSUE TITLE
Cannot find later versions of Areas Mod.

### ISSUE THREAD

**Issue by nhmhfv** [ricksouth/serilum-mc-mods#1246]
(Sorry if this is written in the wrong area or janky, this is my first time for both github and requesting mod support.)

When trying to load your random village names mod I get a crash saying it needs Areas version 4.30 or higher. But I cannot find that version in the file list on forge. It goes up to version 3.0.

Minecraft version: 1.19
Modloader: Forge 
Forge version: 41.1.0
Environment: Singleplayer 

Mod name: Areas
Mod version: 3.0

Is there a version of Areas 4.30 or higher for minecraft 1.19? If not, should i download a different version of Areas/Random Village Names? Or will I be unable to use this mod

**Comment by James103** [comment]
1. What do you get in the log files? Can you please post them if possible?
2. Can you please try installing the Collective mod, version 4.30 for MC 1.19? I think the actual error is referring to that mod not being present.
Link to mod file: https://www.curseforge.com/minecraft/mc-mods/collective/files/3879492

**Comment by ricksouth** [comment]
You're in the right place! What version of Random Village Names are you using?

If you're on Minecraft 1.19.0, version 1.8 should have the fix: https://www.curseforge.com/minecraft/mc-mods/random-village-names/files/3879754. Are you on 1.7 of RVN by any chance?

**Comment by nhmhfv** [comment]
I was using 1.7 for RVN. After updating to 1.8 it's no longer giving me an error. Thank you so much!

> You're in the right place! What version of Random Village Names are you using?
> 
> If you're on Minecraft 1.19.0, version 1.8 should have the fix: https://www.curseforge.com/minecraft/mc-mods/random-village-names/files/3879754. Are you on 1.7 of RVN by any chance?
