### ISSUE TITLE
Villager prices skyrocketing 

### ISSUE THREAD

**Issue by SporterMI** [ricksouth/serilum-mc-mods#1251]
Minecraft version: 1.18.2
Modloader: Fabric
Fabric loader version: 0.14.9
Environment: Multiplayer

Mod name: Infinite Villager Trading
Mod version: 2.4

I was playing in a multiplayer server with my friends and we were using this mod when I started to realise that the fletcher villager would trade me 1 emerald for 32 sticks even thought it showed 31 (with discount) in the GUI. Soon, things started to get much worse as the same villager would charge me 64 sticks for 1 emerald whereas the GUI would only say 31 (again, with the discount). 

Any idea as to why this may be occurring? I am on the latest version of everything; collective, infinite trading, and fabric api

**Comment by ricksouth** [comment]
This has been fixed in version 3.0 of Infinite Trading. It has completely been rewritten. How the offers are reset has changed and it now accounts for demand correctly. Thanks for giving the mod a try and opening the issue!

https://www.curseforge.com/minecraft/mc-mods/infinite-trading-fabric/

**Comment by Nataly171** [comment]
Prices still seem to be skyrocketing. After just a couple trades, my Librarian is selling bookshelves for a full stack of emeralds, even after having been cured. However the display issue has been fixed.

**Comment by ricksouth** [comment]
@Nataly171 How are you trading with the villager? Do you close the GUI in between trades?

**Comment by ricksouth** [comment]
I am now setting the demand variable to 0 every time someone trades with a villager. This is done via Collective, so Infinite Trading won't need an update, just Collective to 4.69+. That should fix the problem (again). It works for me locally.

Please let me know if it doesn't and also if it does <3

https://www.curseforge.com/minecraft/mc-mods/collective-fabric/files

**Comment by Nataly171** [comment]
Yep, it's working perfectly now! Thanks for working so hard on all these mods! :)

**Comment by ricksouth** [comment]
Great to hear! Thanks for using them :)
