### ISSUE TITLE
collective "mods" crashing when people log in the server

### ISSUE THREAD

**Issue by FullMetalMaster** [ricksouth/serilum-mc-mods#1260]
## **Information**
Minecraft version: 1.15.2
Modloader: Forge
Forge version: lastest 1.15.2 forge
Environment:  Multiplayer

Mod name: Mod
[collective-1.15.2-2.26.jar](https://www.curseforge.com/minecraft/mc-mods/collective/files/3283884)

## **Description**
Hey! game crahsing in the server with the other mods not sure why 
Villager Names was the issue but then another mod crashed and i traced bk to this mod?

## **Crash report**
[debug.log](https://github.com/ricksouth/serilum-mc-mods/files/9354959/debug.log)

If available.
[crash-2022-08-16_17.52.36-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/9354958/crash-2022-08-16_17.52.36-server.txt)

**Comment by ricksouth** [comment]
Unfortunately I can no longer support Minecraft 1.15.2. I'd suggest updating to 1.18+, also to receive updates for other mods. Apologies for the inconvenience, I appreciate you giving the mod a try.
