### ISSUE TITLE
[Suggestion] The Vanilla Experience mod for 1.12 (Forge)

### ISSUE THREAD

**Issue by vico93** [ricksouth/serilum-mc-mods#1271]
## **Information**
Mod name: The Vanilla Experience (Mod) (Forge)

## **Feature description**
I know 1.12.2 isn't the latest version of Minecraft for a while, but i realized the lack of this for 1.12 when i needed to reassembly my modpack  and, instead of installing one by one i tried to search if a version for this existed for that version.

I know you have a lot of priorities, but please, if there's any possibility, could you look to make a version of this for 1.12 as well?

**Comment by ricksouth** [comment]
At this moment I have no plans for a 1.12 version of the TVE mod. There are a few bugs in the code which prevent me from updating it for the latest Minecraft versions as well. 1.12 has drastically different code, and it would cause more issues. I appreciate the interest though!
