### ISSUE TITLE
Game HUD gets offset from GUI clock

### ISSUE THREAD

**Issue by TheRTGGaming** [ricksouth/serilum-mc-mods#1273]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 43.1.2
Environment: Singleplayer

Mod name: guiclock
Mod version: 1.19.2-3.3

## **Description**
When the clock is taking out of inventory the interactive screen gets offset from the game HUD. but once the clock is set into inventory it is corrected but shows 2 sets of time and date on screen.

![2022-08-21_04 07 53](https://user-images.githubusercontent.com/48783483/185788432-b4fb8c1f-513d-49f1-b812-5d1dfa3ce8b6.png)

![2022-08-21_04 08 47](https://user-images.githubusercontent.com/48783483/185788433-4f2eed49-5fd3-4f51-9bc5-95409ec1975a.png)

![2022-08-21_04 08 58](https://user-images.githubusercontent.com/48783483/185788435-52b29137-4d7f-4844-9c1d-77adf03e0882.png)

**Comment by ricksouth** [comment]
I think this is fixed in the latest version of GUI Clock. But I couldn't test it because I'm not able to replicate it locally. If it's not working, please let me know. Thanks for opening the issue and giving the mod a try!

https://www.curseforge.com/minecraft/mc-mods/gui-clock
