### ISSUE TITLE
Mod: Healing Soup clashing with Harvestcraft  (I think)

### ISSUE THREAD

**Issue by GITHUBJacques** [ricksouth/serilum-mc-mods#1275]
**Information**
Minecraft version: 1.12.2
Modloader: Forge
Forge version: v. 0.205.1.5800
Environment: Singleplayer

Mod name: Healing Soup (Forge)
Mod version: healingsoup_1.12-1.0.jar

## **Description**

Hey! I've installed the Healing Soup mod (as well as Collective) but I believe since certain items already exist with the same names such as chocolate milk and cactus soup within another mod (Harvestcraft), the two mods are clashing. Is there anyway to solve this?

**Comment by ricksouth** [comment]
The 1.12 version unfortately does not have the cactus soup and chocolate milk. This was added in version 2.0, after 1.12 support had dropped. Only the mushroom soup will heal hearts. You could add a custom recipe via a datapack to turn cactus/cocoa beans into stew as a workaround. Apologies for the inconvenience.
