### ISSUE TITLE
Just Mob Heads: Illusioner, Toast rabbit, White fox head missing

### ISSUE THREAD

**Issue by RedBeast1959** [ricksouth/serilum-mc-mods#1277]
## **Information**
Mod name: Just Mob Heads

## **Feature description**
Recently, I found out that illusioner doesn't have head. Illusioner is unused enemy but many mods bring them back from vanilla data. So I think we need Illusioner head as well.

Also, Toast rabbit doesn't have head(which is not natural spawn nor breedable, only name tag just like Jeb sheep).

And white fox(snowy biome fox) drops normal fox head, not white fox head.

**Comment by ricksouth** [comment]
Thanks! I'll leave this as a bug, since they're in the vanilla game. Appreciate it. I'll take a look soon.

**Comment by ricksouth** [comment]
I've added the Red Fox/Snow Fox head, Toast rabbit head and the Illusioner head in version 6.0 of Just Mob Heads. Appreciate the detective work, thanks for giving the mod a try :)

https://www.curseforge.com/minecraft/mc-mods/just-mob-heads/files
