### ISSUE TITLE
Suggestion: Config value to toggle the hoe un-till feature

### ISSUE THREAD

**Issue by MScott7** [ricksouth/serilum-mc-mods#1287]
## **Information**
Mod name: Hoe Tweaks

## **Feature description**
I was wondering if it'd be possible to add a config option to toggle the soil un-till feature. It's a bit annoying when off-handing seeds because the hoe un-till happens over the seed planting. Thanks!

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! I have added the _onlyUntillWithOtherHandEmpty_ config option in version 1.9 of Hoe Tweaks, enabled by default. This allows placing seeds while also holding the hoe. :)

https://www.curseforge.com/minecraft/mc-mods/hoe-tweaks
