### ISSUE TITLE
Passive Endermen 3.0 doesn't make any gameplay changes

### ISSUE THREAD

**Issue by HeroOfAlexandria** [ricksouth/serilum-mc-mods#1288]
## **Information**
Minecraft version: 1.18.2
Modloader: Forge
Forge version: 40.1.0
Environment: Singleplayer

Mod name: Passive Endermen
Mod version: 3.0

## **Description**
I've loaded Passive Endermen 3.0 with Forge, and it does show up in the Forge mod list, however, it does not seem to have any effect at all in-game. Endermen still pick up blocks, attack when looked at, and teleport as usual.

The mod does generate the config file as expected and the config can be edited use the Forge mod config GUI. 

I've tested with the config set with everything enabled and everything disabled, restarting the game after making any changes to the config file, and before tests. Behaviour was the same either way.

No errors are visible in the log, when starting the game, loading a world, or when Endermen are preforming unexpected behaviours.

**Comment by James103** [comment]
Did you also install the Collective library mod? If so, which version?

What other mods do you have loaded?

**Comment by HeroOfAlexandria** [comment]
I am using Collective 4.37.

Only Passive Endermen, Collective, and Forge.

I am using the MultiMC launcher, but I don't believe that should impact the mod's functionality at all, especially considering I don't see any errors in the log.

**Comment by ElfKing94** [comment]
im having this issue too for some reason. found an endermen holding a block and decided to test looking at it, sure enough it doesnt work for some reason. thanks

**Comment by ricksouth** [comment]
I've re-written the mod, this should be fixed in version 4.0 of Passive Endermen. Though I have thought that before. Please let me know if the issue persists. Thanks!

https://www.curseforge.com/minecraft/mc-mods/passive-endermen/files
