### ISSUE TITLE
Please define if your mods are client, server, or both. 

### ISSUE THREAD

**Issue by purejosh** [ricksouth/serilum-mc-mods#1289]
Specifically about Just Mob Heads, Just Player Heads, and Collective, I've been searching for an hour and still haven't found any documentation about if this is a server only mod, or if it needs to be installed on both the client and the server. 

It would be appreciated if you could update your modpages to include Client, Client/Server, or Server.

**Comment by ricksouth** [comment]
They're all server-side mods. All client-side only mods specify it on the page. I'll look into adding a specific tag to the pages. Thanks for the suggestion!

**Comment by purejosh** [comment]
Thank you.

**Comment by ricksouth** [comment]
For now, Modrinth specifies whether it's client or server side already: https://modrinth.com/user/Serilum as an alternative
