### ISSUE TITLE
Yo are you cool with me using this in a server modpack? I added it to mine without thinking if you were OK with it so I will remove it if you need me to. 

### ISSUE THREAD

**Issue by DrEpicSquidness** [ricksouth/serilum-mc-mods#1295]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: xx.xx.xx
Modloader: Forge / Fabric
Forge version: xx.xx.xx  OR  Fabric loader version: x.xx.x
Environment: Singleplayer / Multiplayer

Mod name: Mod
Mod version: x.x

## **Question**
?

**Comment by DrEpicSquidness** [comment]
I mean just all your mods but I got collective and a few select mods from the Vanilla Experience Pack

**Comment by DrEpicSquidness** [comment]
I don't know how to add Mod Labels Github is a mystery to me.

**Comment by ricksouth** [comment]
At the moment, adding a .jar to the server files is pretty much the only way to do it on CurseForge. As long as you add all mods on the client (which you should for the singleplayer experience anyways) it's fine. Thanks for asking and giving some of the mods a try!
