### ISSUE TITLE
It just...isn't working.

### ISSUE THREAD

**Issue by RemiTsai46** [ricksouth/serilum-mc-mods#1296]
## **Information**
Minecraft version: 1.18.2
Modloader: Fabric
Fabric loader version: 0.14.6
Environment: Multiplayer

Mod name: Replanting Crops Mod
Mod version: 2.9

## **Description**
I was farming in my friend's server(Fabric server), and when I harvest, it doesn't work with the "mustHoldHoeForReplanting" to be either true or false.

## **Crash report**
If available.

**Comment by ricksouth** [comment]
Can you post your modlist here?

**Comment by ricksouth** [comment]
This should be fixed in version 4.0. Please let me know if it isn't the case. Thanks for giving the mod a try!

https://www.curseforge.com/minecraft/mc-mods/replanting-crops-fabric
