### ISSUE TITLE
Double Doors: Not working at all in multiplayer

### ISSUE THREAD

**Issue by qfoxb** [ricksouth/serilum-mc-mods#1297]
## **Information**
Minecraft version: 1.19.2
Modloader: Fabric
Fabric loader version: 0.14.9
Environment: Multiplayer

Mod name: Double Doors
Mod version: 1.19.2-3.7

## **Description**
Not getting detected at all, not showing in the mod menu. Fabric log lists it in the enabled mods
I'm using optifabric, if that means anything. No further errors from the mod or crashes. Double doors just do not open together

**Comment by ricksouth** [comment]
Could you post your current mod list? Might be an incompatibility.

**Comment by qfoxb** [comment]
Here's my current mod list
AppleSkin
Armored-Elytra
Bedrockify
BetterDroppedItems
BetterPingDisplay
Boosted brightness
Cloth Config
Collective
Doubledoors
EmojiType
Essential
Fabric API 
FallingLeaves
FreeLook
Illuminations
Konkrete
Modmenu
NoChatReports
NoTelemetry
Optifabric & OptiFine
Replay Mod
ToroHealth
Simple ArmorHud
WorldEditCUI
Xaero's Minimap & Worldmap

**Comment by PastellePixie** [comment]
I'm also having this issue but on 1.19.3 and it used to work.

**Comment by Lexilina** [comment]
For me the double doors "work" but when trying to walk through them there's an invisible wall blocking me. I'm on 1.19.3

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 4.3 of Double Doors.

https://www.curseforge.com/minecraft/mc-mods/double-doors/files
