### ISSUE TITLE
AREA doesn't work in multiplayer.

### ISSUE THREAD

**Issue by blatantpotatoe** [ricksouth/serilum-mc-mods#1298]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge 
Forge version: 43.1.15
Environment: Multiplayer

Mod name: Areas(forge)
Mod version: 3.0

## **Description**
pregenerated titles(signs) show up on screen but as soon as one destroys the sign and use it again, the title doesn't show up. This happens only in multiplayer. The mod has been installed on both client and server. Switch to singleplayer and this issue doesn't occur.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 5.0 of Areas, alongside other bug fixes and QoL features. Apologies it took so long for me to get to.

https://www.curseforge.com/minecraft/mc-mods/areas/files
