### ISSUE TITLE
Waystones don't appear in starting village

### ISSUE THREAD

**Issue by AngleWyrm10** [ricksouth/serilum-mc-mods#1300]
## **Information**
Minecraft version: 1.18.2
Modloader: Forge
Forge version: 40.1.73
Environment: Singleplayer 

Mod name: Village Spawn Point
Mod version: 1.9

## **Description**
The starting village doesn't contain a Waystone structure. Other villages do.

This was [reported to the mod team at Better Villages](https://github.com/jtorleonstudios/HUB-Better-Villages/issues/2), whose tests also came to the conclusion the starting village doesn't appear to contain a waystone, but the rest do. This issue might be related to either this Village Spawn Point mod, or perhaps the Waystones mod.

> I don't know why the first village doesn't contain a waystone, maybe you should check the mod wiki and how it works or ask the mod creator.

**Comment by ricksouth** [comment]
I don't think this has anything to do with Village Spawn Point, as there's nothing in the code that can cause this issue. The original issue you referenced also does not have VSP mentioned. I think this is a problem with the Waystones mod.

Thanks for giving the mod a try!
