### ISSUE TITLE
Easy Elytra Takeoff compatible with Elytra Boosters

### ISSUE THREAD

**Issue by sharko789** [ricksouth/serilum-mc-mods#1301]
## **Information**
Mod name: Easy Elytra Takeoff (Fabric)

## **Feature description**
Compatibility with [Elytra Boosters](https://www.curseforge.com/minecraft/mc-mods/elytraboosters)

**Comment by ricksouth** [comment]
Thanks for open the issue and giving the mod a try! Version 3.1 of Easy Elytra Takeoff adds support for elytra boosters in Fabric. :)

https://www.curseforge.com/minecraft/mc-mods/easy-elytra-takeoff-fabric/files
