### ISSUE TITLE
Full Brightness Toggle (Fabric) marked as 1.19 compatible, yet latest is 1.18.2

### ISSUE THREAD

**Issue by PweSol** [ricksouth/serilum-mc-mods#1302]
Full Brightness Toggle (Fabric) (and Forge) is marked as 1.19 compatible on your website and your [changelogs](https://github.com/ricksouth/serilum-mc-mods/blob/master/changelog/full-brightness-toggle.txt). Yet there is no publicly available 1.19 build.

When trying to build it from source, I get an error saying it's missing fabric-loom. When I add it trough settings.gradle, I'm getting javaCompile errors (which I'm unable to solve further).

So either please update your public builds of this mod to 1.19 (best), or don't mark this mod as 1.19 compatible. Alternatively, you could make it easier for us to build from source. Thanks.

PS. I checked if you have Patreon only mods/updates, and it doesn't seem to be that case. So I don't think this is a mistake on my part.

**Comment by ricksouth** [comment]
The source existed after I made an attempt at updating, but came across some difficulties. It wasn't ready to be built from source, but forgot to remove it from the public repo.

I've just fixed the problem and released version 2.1 of Full Brightness Toggle, which works for 1.19 :) Thanks for the interest!

https://www.curseforge.com/minecraft/mc-mods/full-brightness-toggle-fabric/files
