### ISSUE TITLE
Stack Refill: Using water bottle on dirt makes glass bottle disappear

### ISSUE THREAD

**Issue by niekschoemaker** [ricksouth/serilum-mc-mods#1303]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 43.1.1
Environment: Multiplayer

Mod name: Stack Refill
Mod version: 2.3

## **Description**
When you use a water bottle on dirt (to turn it into mud) it replaces the glass bottle with a new water bottle.
This works server sided, this however does not sync to the client, so you see a glass bottle till you actually select the glass bottle, then it turns into a water bottle.

Furthermore the glass bottle also gets replaced, so instead of getting a glass bottle back (as it's supposed to do with potions, as read in source code) the glass bottle disappears.

## **Crash report**
Not applicable

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 3.0 of Stack Refill.

https://www.curseforge.com/minecraft/mc-mods/stack-refill
