### ISSUE TITLE
Passive Shield with mod shields

### ISSUE THREAD

**Issue by MC-Dad19** [ricksouth/serilum-mc-mods#1304]
## **Information**
Mod name: Passive Shield

## **Feature description**
Like this mod, sure wish it worked with shields from other mods!!

**Comment by XavierBit** [comment]
Hello ricksouth!

Thanks for coming back so quickly.

The only active (unziped) log would be this one. I'm not sure if this is going to help though.

[latest.log](https://github.com/ricksouth/serilum-mc-mods/files/9675498/latest.log)

**Comment by ricksouth** [comment]
Support has been added in the latest version. Thanks for opening the issue and giving the mod a try!
