### ISSUE TITLE
Wrong in-game day displayed.

### ISSUE THREAD

**Issue by LntlIntl** [ricksouth/serilum-mc-mods#1306]
## **Information**
Minecraft version: 1.19.2
Modloader: Fabric
Fabric loader version: 0.14.9
Environment: Singleplayer

Mod name: Gui-Clock
Mod version: 4.0.6

## **Description**
Holding a clock in game displays the day counter to be 27, wherein on the same world it displayed over day 160. At some point, the mod just reset itself, from 160 to 0, im not sure what has caused it and so far I have not been able to re-create it.

**Comment by James103** [comment]
What do you get when you run `/time query day` or in the '(Day X)' counter in F3?

**Comment by LntlIntl** [comment]
/time query day returns 27 as well

**Comment by ricksouth** [comment]
I think your actual world time was reset. You could do the following:

160-27 = 133 days

133×24000 = 3192000

So the following command:
/time add 3192000 

Should set the day counter to 160 again. I don't think it's a bug in the mod itself.

**Comment by LntlIntl** [comment]
It appears then that my internal vanilla daycounter reset itself somehow, rather than an issue with the mod. My apologies.

**Comment by ricksouth** [comment]
Glad you've fixed the problem! Thanks for giving the mod a try :)
