### ISSUE TITLE
Bug with recipe for Wool Tweaks

### ISSUE THREAD

**Issue by Vivid141** [ricksouth/serilum-mc-mods#1307]
## **Information**
Minecraft version: 1.18.2
Modloader: Fabric
Fabric loader version: 0.14.9
Environment: Multiplayer

Mod name: Wool Tweaks
Mod version: 1.9

## **Description**
Tried converting wool into string as the modpage shows, but the recipe isn't available. Tried in both crafting tables and with all colours of wool, still with no result. The recipe also isn't on JEI.

## **Crash report**
Not available since bug isn't game-breaking, sorry

**Comment by ricksouth** [comment]
I can't replicate this. I've tested it in both the dev environment, single and multiplayer and in the CurseForge launcher. Any wool can be turned into string. Is the mod installed on the server? Is there another mod that does something with wool?

**Comment by ricksouth** [comment]
Closing this for now, as I couldn't find the problem. If you can, please update to version 2.2 of Wool Tweaks I just released and if you still have problems reopen the issue. Appreciate you giving the mod a try!

https://www.curseforge.com/minecraft/mc-mods/wool-tweaks-fabric
