### ISSUE TITLE
Can't take off with Colytra OR Elytra Slot - Trinket. Only works with Elytra in Chest slot.

### ISSUE THREAD

**Issue by ThomMcLean** [ricksouth/serilum-mc-mods#1310]
## **Information**
Minecraft version: 1.19.2
Modloader:  Fabric
Forge version: Fabric loader version: 0.14.9
Environment: Singleplayer / Multiplayer (Occurs in both)

First mod name: Easy Elytra Takeoff - Fabric
First mod version: easyelytratakeoff-fabric_1.19.2-3.0.jar

Second mod name: Colytra - Fabric
Second mod version: colytra-fabric-6.0.0+1.19.2.jar

## **Description**
Have tested using Elytra attached to Iron Chest armor and take off from the ground does not happen. Have to double-click jump before the rocket will fire. Elytra alone in the chest slot works as intended. Have also tried using the Elytra Slots - Trinket mod with Elytra in the cape slot. Rocket will not fire when right-clicking and held in hand. Elytra in the chest slot again works as intended.

For testing purposes, if it matters, I used the /give command to give myself the elytra for testing and combined them with the chest armor in crafting slot.

## **Crash report** 
No Crash

**Comment by ricksouth** [comment]
Thanks for open the issue and giving the mod a try! Version 3.1 of Easy Elytra Takeoff adds support for modded elytra's in Fabric. :)

https://www.curseforge.com/minecraft/mc-mods/easy-elytra-takeoff-fabric/files

**Comment by ThomMcLean** [comment]
Thank you very much for the fast update! We really enjoy all of your mods.Thom McLeanOn Sep 19, 2022, at 1:24 PM, Rick South ***@***.***> wrote:﻿
Closed #1310 as completed.
