### ISSUE TITLE
Mods doesn't work on hosted minecraft server

### ISSUE THREAD

**Issue by wicioor** [ricksouth/serilum-mc-mods#1311]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 0.14.9
Environment: Multiplayer

Mod name: The Vanilla Experience (Modpack) | TVE
Mod version: 5.17

## **Question**
Hi, me and my friends want to host minecraft server. On the one of the online host website. When we install Forge engine we come to the fileZilla and insert config and mods files into main folder of the server. Unfortunetlly it is not working, any idea to repair it?

**Comment by James103** [comment]
Exactly which server host are you on?

**Comment by wicioor** [comment]
craftserve.pl

**Comment by ricksouth** [comment]
I don't know the server host, but I'm sure they can help you via the contact function: https://craftserve.pl/contact

You can link them to the latest server files: https://www.curseforge.com/minecraft/modpacks/the-vanilla-experience/files/3971620

I'm using the modpack myself and it's definitely working. Thanks for giving the modpack a try and I hope the server host can help you.
