### ISSUE TITLE
Is Beautified Chat abandoned?

### ISSUE THREAD

**Issue by Aces-and-Jacks** [ricksouth/serilum-mc-mods#1312]
## **Information**
Modloader: Fabric
Fabric loader version: 0.14.9
Environment: Multiplayer

Mod name: Beautified Chat [Client] (Fabric)
Mod version: 1.18.2

## **Question**
I was wondering if there was gonna be a 1.19 version or is this project abandoned or do you just not want to update for now?

**Comment by ricksouth** [comment]
There were some issues with updating the mod to 1.19, due to the new chat changes. But I'm definitely going to give it another try in the near future. Thanks for the interest!
