### ISSUE TITLE
Compact Help doesn't work 

### ISSUE THREAD

**Issue by Aces-and-Jacks** [ricksouth/serilum-mc-mods#1313]
## **Information**
Minecraft version: 1.19.2
Modloader: Fabric
Fabric loader version: 0.14.9
Environment: Multiplayer

Mod name: Compact Help Command (Fabric)
Mod version: 1.19.2

## **Description**
I typed in /help on a server but the mod didn't affect it. It did work for singleplayer though

## **Crash report**
If available.

**Comment by James103** [comment]
Is the mod installed on the server?

**Comment by Aces-and-Jacks** [comment]
no. I didn't know if this worked on client or needed a server mod

**Comment by ricksouth** [comment]
It has to be installed on the server, to receive the commands. Which is done server-side. It works in singleplayer as it basically simulates a server with the "client mods". Thanks for giving the mod a try!
