### ISSUE TITLE
[1.19.2] Beautified Chat [Server] (Forge): Can't start up owing to mixin loading problem

### ISSUE THREAD

**Issue by jellybean13** [ricksouth/serilum-mc-mods#1315]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 1.19.2-43.1.25
Environment: Multiplayer

Mod name: Beautified Chat [Server] (Forge)
Mod version: 1.19.2-1.3

## **Installed mods**

- Beautified Chat [Server] (Forge): 1.19.2-1.3
- Collective (Forge): 1.19.2-4.52

## **Description**
Server cannot start owing to mixin loading problem.

## **Crash report**
Here is the output from console.
https://pastebin.com/k842U8eQ
Here is the "debug.log".
https://pastebin.com/dNfgitmY

**Comment by ricksouth** [comment]
This has been fixed in version 1.5 of Beautified Chat Server. Thanks for letting me know and giving the mod a try!

https://www.curseforge.com/minecraft/mc-mods/beautified-chat-server/files
