### ISSUE TITLE
mustHoldHoeForReplanting: true Not Working

### ISSUE THREAD

**Issue by Redgycide** [ricksouth/serilum-mc-mods#1317]
## **Information**
Minecraft version: 1.19.2
Modloader: Fabric
Fabric loader version: 0.14.9
Environment: Singleplayer

Mod name: Replanting Crops
Mod version: 4.0

## **Description**
Hi! So the mod works as expected whenever the mustHoldHoeForReplanting value is set to true, however, when I set it to false, weird stuff happens. When I break a crop with or without a hoe, it disappears, then reappears after a few seconds. No crops are dropped, nothing happens except making it disappear for a few seconds.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 4.1 of the mod.

https://www.curseforge.com/minecraft/mc-mods/replanting-crops-fabric
