### ISSUE TITLE
Beautified Chat see messages in console/logs again

### ISSUE THREAD

**Issue by Pokihead** [ricksouth/serilum-mc-mods#1319]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge

Mod name: Beautified Chat [Server]

## **Feature description**
The mod is very nice and i like it but i have on problem with it.
Normally every chat message from a player is visible in the server console and logs too. 
With this mod all messages aren't in the console/logs.
The problem is i can't check if some player denounce some other for bad language if he is right.

**So the missing feature is that the messages are visible in server console/logs again if possible.**
edit:
best would be of course if the timestamp etc would be logged with it

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 1.6 of Beautified Chat Server :)

https://www.curseforge.com/minecraft/mc-mods/beautified-chat-server/files
