### ISSUE TITLE
Collective crash com.natamus.collective.functions.BlockPosFunctions.recursiveGetNextBlocksMaterial

### ISSUE THREAD

**Issue by Jetpack-Cat** [ricksouth/serilum-mc-mods#1321]
## **Information**
Minecraft version: 1.16.5
Modloader: Forge
Forge version: 36.2.39
Environment: multiplayer server

Mod name: Mod
Mod version: collective-1.16.5-4.50.jar

## **Description**
Crash when exploring 

## **Crash report**

[crash-2022-09-17_23.30.20-client.txt](https://github.com/ricksouth/serilum-mc-mods/files/9593102/crash-2022-09-17_23.30.20-client.txt)

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 4.64 of Collective.

https://www.curseforge.com/minecraft/mc-mods/collective
