### ISSUE TITLE
Better Spawner Control crashing intermittently

### ISSUE THREAD

**Issue by nekoyoubi** [ricksouth/serilum-mc-mods#1323]
## **Information**
Minecraft version: 1.19.2
Modloader: Fabric
Fabric loader version: 0.61.0
Environment: Singleplayer

Mod name: Better Spawner Control
Mod version: 2.0

## **Description**
Every few minutes of exploration, I guess I generate a new spawner that throws this. Doesn't seem to be all or all of the time, as in a case very recently: I crashed when near a new spawner (within a few blocks), came back in and stood and farmed that same spawner for quite a while. Also, I've not noticed this happening when I actually have spawners torched up; only on new creation/loading.

## **Crash report**
[crash-2022-09-17_23.43.01-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/9593857/crash-2022-09-17_23.43.01-server.txt)

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 4.64 of Collective. Better Spawner Control doesn't need an update.

https://www.curseforge.com/minecraft/mc-mods/collective
