### ISSUE TITLE
Inventory Totem (Fabric) 

### ISSUE THREAD

**Issue by ghost** [ricksouth/serilum-mc-mods#1327]
1.19.2
Fabric
 Multiplayer

Mod name: Inventory Totem (Fabric)

Is this supposed to work in multiplayer? if not is it possible that it can?

**Comment by ricksouth** [comment]
It should work in multiplayer, does it not?

**Comment by ricksouth** [comment]
It has to be installed on the server though. Since the server checks for a totem in the inventory. It's not client-side only
