### ISSUE TITLE
RBF should blacklist wither rose by default

### ISSUE THREAD

**Issue by kingstairs** [ricksouth/serilum-mc-mods#1331]
## **Information**
Minecraft version: 1.19.2
Modloader: Fabric

Mod name: Random Bonemeal Flowers v2.2

## **Feature description**
The **wither rose**, given its unusual nature (and origin), should be blacklisted by default in the _blacklist.txt_ configuration file. Having a few of these turn up while using this mod was a little surprising!

**Comment by ricksouth** [comment]
Chance has it I'm actually working on Random Bone Meal Flowers right now, and was about to push an update. Thinking about it, I do agree with you. Expect an update with this added in about 10 minutes :) Thanks!

**Comment by ricksouth** [comment]
Feature added in version 3.0 of Random Bone Meal Flowers. Appreciate it!

https://www.curseforge.com/minecraft/mc-mods/random-bone-meal-flowers-fabric/files

**Comment by ricksouth** [comment]
Feature added in version 3.0 of Random Bone Meal Flowers. Appreciate it!

https://www.curseforge.com/minecraft/mc-mods/random-bone-meal-flowers-fabric/files
