### ISSUE TITLE
Blocks not facing the correct way

### ISSUE THREAD

**Issue by GrandmaPork** [ricksouth/serilum-mc-mods#1332]
## **Information**
Minecraft version: 1.18.2
Modloader: Forge
Forge version: 
Environment: Multiplayer

Mod name: Nether Portal Spread
Mod version: 5.7

## **Description**
When a stair is replaced, it faces the wrong way. If doors are replaced, they are turned into items. If too slabs stacked on top of each other are replaced, only one is replaced.

**Comment by GrandmaPork** [comment]
I'd like to add to this - when trying to add compatibility with Dynamic Trees, the wood is replaced with much skinner branches yet they are somehow connected to the same tree. I wonder if you would be able to make it so the new blocks inherit the properties of the block being replaced

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed/added in version 8.0 of Nether Portal Spread. Apologies it took so long for me to get to.

https://curseforge.com/minecraft/mc-mods/nether-portal-spread/files
