### ISSUE TITLE
Doesn't seem to work on 1.19.2

### ISSUE THREAD

**Issue by XavierBit** [ricksouth/serilum-mc-mods#1337]
## **Information**
Minecraft version: 1.19.2
Modloader: Fabric
Fabric loader version: 0.19.4
Environment: Multiplayer

Mod name: Passive Shield
Mod version: 1.19.2-2.6

## **Description**
Hey there!
I had your mod working on 1.19 and had to update to 1.19.2. It seems there is something not working as the shield does not disappear.  It seems the mod isn't doing anything?

My passiveshield-fabric.json content:
{
	// When enabled, the shield will be hidden unless a player presses right-click.
	"hideShieldWhenNotInUse": true,
	// The percentage of damage that will be negated when a player is hit while holding a shield that's not held high.
	"passiveShieldPercentageDamageNegated": 1.0
}

## **Crash report**
No crash is happening.

Let me know if you need any more information.

Edit: I just discovered that the mod will not show up in the mods menu.

**Comment by ricksouth** [comment]
Do you have the debug.log file for me?

**Comment by ricksouth** [comment]
You posted it on the wrong issue :p

"Hello ricksouth!

Thanks for coming back so quickly.

The only active (unziped) log would be this one. I'm not sure if this is going to help though.

[latest.log](https://github.com/ricksouth/serilum-mc-mods/files/9675498/latest.log)"

**Comment by ricksouth** [comment]
I don't see Passive Shield installed nor Collective. Are they in your mods folder?

**Comment by XavierBit** [comment]
Oh... it's too early for me, sorry about that!
Yes, they are, both the most recent version and I double checked that Collective is the Fabric version.

**Comment by ricksouth** [comment]
Haha no problem.

I don't see them in the log at all. Can you remove them and redownload? Where did you download them from?

**Comment by XavierBit** [comment]
Passive Shield from Coursforge and there I followed the link to Collective

**Comment by XavierBit** [comment]
I deleted the two mods and redownloaded them from Courseforge. I checked the passiveshield-fabric.json and the content stayed the same.
It doesn't seem to have any changes, the shield still appears.

**Comment by ricksouth** [comment]
Please post the log file again

**Comment by XavierBit** [comment]
[latest.log](https://github.com/ricksouth/serilum-mc-mods/files/9675814/latest.log)

**Comment by ricksouth** [comment]
Now I do see Collective, but I don't see Passive Shield in the log. Hmm

**Comment by ricksouth** [comment]
Can you show a screenshot of your mods folder?

**Comment by XavierBit** [comment]
Please follow the link https://prnt.sc/Lb1II7_1fW2q

**Comment by ricksouth** [comment]
Ah the problem has showed itself! :) You downloaded Passive Shield for Forge.

You need Fabric: https://www.curseforge.com/minecraft/mc-mods/passive-shield-fabric/

**Comment by XavierBit** [comment]
ahhhhh!!!

**Comment by XavierBit** [comment]
And now it works!
Sorry for my partial blindness... 
I'm struggling with forge / fabric versions, got it right on collective but failed badly on passive shield.
Thanks for your help!

**Comment by ricksouth** [comment]
Haha no problem! Thanks for giving the mod a try! :) Glad you got it fixed.

**Comment by XavierBit** [comment]
Just to let you know, your mod is pure gold for me, thank you for your time and dedication to it!
