### ISSUE TITLE
Crash with Multimob Lib and The Summoner

### ISSUE THREAD

**Issue by Kasia1403** [ricksouth/serilum-mc-mods#1339]
[crash-2022-09-29_13.06.54-client.txt](https://github.com/ricksouth/serilum-mc-mods/files/9674050/crash-2022-09-29_13.06.54-client.txt)

and this 

[crash-2022-09-29_13.06.55-client.txt](https://github.com/ricksouth/serilum-mc-mods/files/9674074/crash-2022-09-29_13.06.55-client.txt)

**Comment by ricksouth** [comment]
Which mod are you referring to?

**Comment by Kasia1403** [comment]
Hatchery mod 1.12.2

**Comment by ricksouth** [comment]
I mean which mod of mine (Serilum) as this is a repo for all of them :)

**Comment by Kasia1403** [comment]
Multimob Lib and The Summoner ( both of them ).

**Comment by ricksouth** [comment]
These are both not mods of mine. I think you might have the wrong github issue link
