### ISSUE TITLE
Exception caught during firing event: null

### ISSUE THREAD

**Issue by OcrSu** [ricksouth/serilum-mc-mods#1341]
## **Information**
1.16.5- Forge 36.2.39
Singleplayer

Mod name: hiddenrecipebook
Mod version: 3.0-1.16.5

## **Description**
ingame crash when open "Chat Window" by using "/" Key
(I probably typed the first few letters in "forge tps")

## **Crash report**
[debug-1.log](https://github.com/ricksouth/serilum-mc-mods/files/9689931/debug-1.log)
The crash information is at the end of the log

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 3.1 of Hidden Recipe Book. Appreciate it!

https://www.curseforge.com/minecraft/mc-mods/hidden-recipe-book/files
