### ISSUE TITLE
Collective 1.19.2 Version 5.1 crashing minecraft

### ISSUE THREAD

**Issue by TheideaLAXE** [ricksouth/serilum-mc-mods#1343]
## **Information**
Minecraft version: 1.19.2
Modloader: Fabric
Fabric loader version: 0.14.9
Environment: Singleplayer / Multiplayer

Mod name: Collective
Mod version: 5.1

## **Description**
Made a post about it on r/fabricmc. The game was working fine before updating to the new update of the mod. After updating it would open up the minecraft window but it wouldn't respond and shortly after it would close. The minecraft launcher wouldn't even open up with some sort of error.

## **Crash report**
https://gist.github.com/TheideaLAXE/933790fced5cd772270fcb0721185389#file-crash-2022-10-01_14-44-06-server-txt

**Comment by ricksouth** [comment]
Thanks for taking the time to let me know! I've just uploaded version 5.2 which rolls back the changes made in 5.1. You can also use 5.0 for now, until the other update is processed. Appreciate it!

https://www.curseforge.com/minecraft/mc-mods/collective-fabric/files
