### ISSUE TITLE
Replanting crops Multiplayer

### ISSUE THREAD

**Issue by MattPlayGamez** [ricksouth/serilum-mc-mods#1346]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.19.2
Modloader: Fabric
Environment: Singleplayer / Multiplayer

Mod name: Replanting Crops
Mod version: 4.1

## **Question**
I can't get this to work in Multiplayer, is that by design or not.
PS. Single-player works.

**Comment by James103** [comment]
Do you have the mod installed on the server?

**Comment by MattPlayGamez** [comment]
No client sided

Op zo 2 okt. 2022 16:27 schreef James103 ***@***.***>:

**Comment by ricksouth** [comment]
The mod has to be installed on the server to work in multiplayer as it manipulates the world. Thanks for the interest!
