### ISSUE TITLE
Realistic Bees v2.7 not working

### ISSUE THREAD

**Issue by FireGeneral** [ricksouth/serilum-mc-mods#1350]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 43.1.1
Environment: Singleplayer & Multiplayer

Mod name: Realistic Bees (Forge)
Mod version: 2.7

## **Basic Description**
The mod don't work for unknown reason, I'm using the newest version of collective, version 5.0 for 1.19.2 right now.
Tested with only Realistic Bees v2.7, Optifine HD_U_H9 and Collective v5.0 installed, bee still behaves like original Minecraft.
Changing data in config file also yields no result.

## **Detailed Description**
I installed this mod to make bees survive their attack, my configuration:
beeSizeModifier = 1.0
beesDieFromStingingPlayer = false
beesDieFromStingingMob = false
beesLeaveTheirStinger = true (Default)
sendStungPlayerWithStingerAMessage = true (Default)
chanceBeeLeavesItsStinger = 0.1
chanceBeeStingerIsPulledOut = 0.5 (Default)
timeInSecondsStingerPumpsPoison = 30 (Default)
timeInSecondsBeeWithoutStingerDies = 60 (Default)
extraBeeSpawnsPerBee = 2
beeHiveBeeSpace = 20 (Default)
preventBeeSuffocationDamage = true (Default)

In-game (Only Realistic Bees v2.7, Optifine HD_U_H9 and Collective v5.0 were installed):
Spawned a bee -> Attacked it to make it attack me -> Bee attacked me -> Bee lost stinger and give me poison effect for 10 seconds
-> Bee stayed aggressive but lost its stinger -> Bee died approximately 1 minute after losing its stinger -> Repeat
-> Results: No "Stinger Message", Bees still die after stinging the player, Can't remove any stinger from body, Bees still die after stinging mobs, poison only lasts 10 seconds, Bees always lose their stingers after their first successful attack on either players or mobs
-> Conclusion: Something presumably went wrong, but I couldn't identify what may be the problem.

## **Crash report**
Game didn't crash, here's the debug log.
[debug.log](https://github.com/ricksouth/serilum-mc-mods/files/9697468/debug.log)

**Comment by ricksouth** [comment]
Thanks for giving the mod a try! This might be optifine's doing. There are other mods out there for performance. Could you give it a try without optifine installed?

**Comment by FireGeneral** [comment]
> Thanks for giving the mod a try! This might be optifine's doing. There are other mods out there for performance. Could you give it a try without optifine installed?

I'll go test it now!

**Comment by FireGeneral** [comment]
> Thanks for giving the mod a try! This might be optifine's doing. There are other mods out there for performance. Could you give it a try without optifine installed?

Tested without Optifine installed, sadly, same result, the mod still doesn't work for unknown reason.

**Comment by ricksouth** [comment]
Are the bees tiny? I'll do some testing. If you can post your modlist too that'd be great :)

**Comment by FireGeneral** [comment]
> Are the bees tiny? I'll do some testing. If you can post your modlist too that'd be great :)

Mod List:
Collective 5.0
Realistic Bees 2.7

Mod Config:
beeSizeModifier = 0.25 (Default)
beesDieFromStingingPlayer = false
beesDieFromStingingMob = false
beesLeaveTheirStinger = true (Default)
sendStungPlayerWithStingerAMessage = true (Default)
chanceBeeLeavesItsStinger = 1.0
chanceBeeStingerIsPulledOut = 0.5 (Default)
timeInSecondsStingerPumpsPoison = 30 (Default)
timeInSecondsBeeWithoutStingerDies = 60 (Default)
extraBeeSpawnsPerBee = 9 (Default)
beeHiveBeeSpace = 20 (Default)
preventBeeSuffocationDamage = true (Default)

Results:
Bees are now small but they still die after their first successful attack, Still no "Stinger Message" even when stinger chance is 100%, Poison only lasts 10 seconds instead of 30 seconds if stingers are indeed inside the body.

**Comment by ricksouth** [comment]
Interesting, thank you very much the research. Sounds like something is definitely wrong on my end 😅

**Comment by FireGeneral** [comment]
> Interesting, thank you very much the research. Sounds like something is definitely wrong on my end 😅

If you find anything that could be causing the problem, please let me know! Thank you for making all these mods!!

**Comment by FireGeneral** [comment]
> Interesting, thank you very much the research. Sounds like something is definitely wrong on my end 😅

**Comment by FireGeneral** [comment]
Sorry, I miss clicked! What I was trying to do was to tell you, if you can, could you check if your mod is compatible with "The Bumblezone (Forge)"? I'm planning on using it alongside with your mod! Thanks again!

**Comment by EightBitBBQ** [comment]
https://github.com/ricksouth/serilum-mc-mods/issues/1180

I posted this issue as well. Its been a long time its not working

**Comment by ricksouth** [comment]
This should be fixed in version 2.8 of Realistic Bees. Thanks for opening the issue and giving the mod a try!

https://www.curseforge.com/minecraft/mc-mods/realistic-bees/files

@EightBitBBQ I think the issue you have is a little different. I'll look at it soon.
