### ISSUE TITLE
[Fabric] Collective / No Hostiles Around Campfire Singleplayer Server Crash

### ISSUE THREAD

**Issue by AstromanGaming** [ricksouth/serilum-mc-mods#1351]
## **Information**
Minecraft version: 1.19.2
Modloader: Fabric
Fabric loader version: 0.14.9
Environment: Singleplayer

Mod name: 
- Collective
- No Hostiles Around Campfire

Mod version: 
- v5.4 (Collective)
- v4.6 (No Hostiles Around Campfire)

## **Description**
When I create or join a world, it crashes and tells me: Server closed

## **Crash report**
[latest.log](https://github.com/ricksouth/serilum-mc-mods/files/9698143/latest.log)

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 5.4 of No Hostiles Around Campfire.

https://www.curseforge.com/minecraft/mc-mods/no-hostiles-around-campfire/files
