### ISSUE TITLE
DISCORD: Modpack update instead of only mod updates

### ISSUE THREAD

**Issue by EightBitBBQ** [ricksouth/serilum-mc-mods#1355]
As spoken of in discord.

I am hosting my own MC server. Running TVE ofcourse.
I almost missed out on 5.20 update from the pack, maybe we can add a channel or bot command to post the updates for the modpack itself!

That way my server can be updated asap, ofcourse i hope this will be usefull for other players using this as well!

**Comment by ricksouth** [comment]
Done! :)

https://discord.gg/vFren9YzzN
https://discord.com/channels/905531994413350942/1032353949887512606
