### ISSUE TITLE
I follow on how to add names, but still not working.

### ISSUE THREAD

**Issue by Psychodeus** [ricksouth/serilum-mc-mods#1356]
## **Information**

Minecraft version: 1.19.2
Modloader: Fabric
Fabric loader version: 0.14.9
Environment: Singleplayer
Mod name: Villager Names
Mod version: 4.2

## **Question**
![2022-10-08_01 02 50](https://user-images.githubusercontent.com/93028949/194612517-ffedad74-6a75-46f5-a36f-5d8d30a38236.png)
My question is, who is **Garret**?!
[customnames.txt](https://github.com/ricksouth/serilum-mc-mods/files/9735864/customnames.txt) I never wrote it there.
I even tried to make a new world and use seeds near village, but still my custom names won't work.
![image](https://user-images.githubusercontent.com/93028949/194612894-63b1179a-aa8d-4b1a-89e1-ba0e6cf3b2b4.png)
![image](https://user-images.githubusercontent.com/93028949/194613411-b951d755-d80c-4382-83d4-3b06c6c217d3.png)

**Comment by ricksouth** [comment]
Disable male and female names in the config. That will make it so only custom names are given. Does that work?

**Comment by Psychodeus** [comment]
![2022-10-08_01 18 45](https://user-images.githubusercontent.com/93028949/194614251-a346fa2e-308e-4a3c-9e26-098e705b635b.png)
No, I'm even creating a new world to see if this works.

**Comment by ricksouth** [comment]
Can you show me your config file? Located in ./config/villagernames-fabric.json5

**Comment by Psychodeus** [comment]
Mmm... how to upload .json5? Github said not support that type of file.

**Comment by ricksouth** [comment]
You can just post the contents here. Appreciate the effort :)

**Comment by Psychodeus** [comment]
Alright, so I make an analysis, this config below is what I expected as soon as I perform the config from inside the **ModMenu**.
![image](https://user-images.githubusercontent.com/93028949/194616012-a47d2688-88c0-48e7-99d0-30ed16bf6f54.png)

BUUUT, I alt tab to config folder, and turns out it still look like this when I open the config from the file **villagernames-fabric.json5**

> {
> 	// Use the custom name list, editable in ./mods/villagernames/customnames.txt, seperated by a comma.
> 	"_useCustomNames": true,
> 	// Use the list of pre-defined female names when naming villagers.
> 	"_useFemaleNames": true,
> 	// Use the list of pre-defined male names when naming villagers.
> 	"_useMaleNames": true,
> 	// If enabled, also gives modded villagers a name. If you've found a 'villager'-entity that isn't named let me know by opening an issue so I can add it in.
> 	"nameModdedVillagers": true
> }

OK, then I restart the game, come back and the config changes, but the name don't. Only when I create new world it starts to work.

Now, my question is, how to make it use custom names when I already set it to "Yes" value on the first try? On my main world.
![image](https://user-images.githubusercontent.com/93028949/194616855-16c7d314-e96a-403e-abf8-c54ee887c244.png)
Will it change "**Garret**" into "**Uvuvuevuevue**"?

**Comment by ricksouth** [comment]
It won't rename villagers that already have a name, only unnamed. That's intentional, so names won't be overwritten. It's specified in the description, but sorry for the inconvenience. All new villager spawns will have the custom names.

**Comment by ricksouth** [comment]
You can open mod menu from the main menu, instead of from your world. For next time

**Comment by Psychodeus** [comment]
> It won't rename villagers that already have a name, only unnamed. That's intentional, so names won't be overwritten. It's specified in the description, but sorry for the inconvenience. All new villager spawns will have the custom names.

Oh no this is sad :(
But, what if I quarantine completely this specific mod and try to play my main world, the game still register the named villagers?
