### ISSUE TITLE
[Bug] Village Spawn Point doesn't work on servers

### ISSUE THREAD

**Issue by Pingu-Pox** [ricksouth/serilum-mc-mods#1357]
## **Information**
Minecraft version: 1.18.2
Modloader: Forge
Forge version: 40.1.80
Environment: Multiplayer

Mod name: Village Spawn Point
Mod version: 2.6

Library name: Collective
Library version: 5.0

## **Description**
Simply, in a server environment, the mod doesn't seem to work anymore. New worlds spawn players out in the wilderness. Server and client both just have collective and village spawn point loaded, and it won't work when players connect to the server.

## **Crash report**
N/A

**Comment by Pingu-Pox** [comment]
Downgraded versions of VSP and Collective, and it still happened with fresh configs and world.... maybe an issue introduced in newer Forge versions?

**Comment by ricksouth** [comment]
Thanks for opening the issue! Could you test if it's still not working on the latest Collective and Village Spawn Point? I pushed an update today regarding the get nearby village code.

**Comment by KeithLerner** [comment]
does not work with your proposed solution as of today.

Using Forge 1.18.2 - 40.1.84 and Version 2.9 of the mod

**Comment by S1mpleM0use** [comment]
Same issue
Forge 1.19.2 - 43.1.53 - VSP 2.9

**Comment by KeithLerner** [comment]
My work around was to generate the world in single player then upload it to the server. Must then match the folder name with what is in the properties file.

**Comment by ricksouth** [comment]
Thanks for opening the bug report and the patience! This has been fixed in Collective version 5.17, and Village Spawn Point has had a small update as well to fix the messages not being logged correctly. Also thanks for giving the mod a try!

https://www.curseforge.com/minecraft/mc-mods/collective
https://www.curseforge.com/minecraft/mc-mods/village-spawn-point

**Comment by KeithLerner** [comment]
You are awesome thank you for making and maintaining the mod <3
