### ISSUE TITLE
Configurable Despawn Timer (1.19.2)

### ISSUE THREAD

**Issue by kiollosmo** [ricksouth/serilum-mc-mods#1361]
Mod name: Configurable Despawn Timer
Mod version: 1.19.2 (fabric)

## **Question**
Will Configurable Despawn Timer ever be ported to fabric/1.19.2?

**Comment by ricksouth** [comment]
It wasn't as easy of a port as others, because Forge adds so much custom code regarding item lifespan. But I'll definitely give it another shot in the near future. Thanks for the interest!
