### ISSUE TITLE
1.19.2 Silent Gear + Random Bonemeal Flowers (Only Growing Flax)

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [ricksouth/serilum-mc-mods#1362]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 43.1.34 
Environment: Both

First mod name: Silent Gear + (Dependency Silent Lib)
First mod version: silent-gear-1.19.2-3.0.4 + silent-lib-1.19.2-7.0.3

Second mod name: Random Bonemeal Flowers + (Dependency Collective)
Second mod version: randombonemealflowers_1.19.2-3.0 + collective-1.19.2-5.0

## **Description**
When using bonemeal on grass it is only growing flax.

![r8Di0cJ 1](https://user-images.githubusercontent.com/10351221/194752332-0174372d-f874-4015-abad-82ee222b14ce.png)
![Q3RWtAm 1](https://user-images.githubusercontent.com/10351221/194752361-bebe01fc-305e-46f0-b545-39cac728c5b7.png)
![jUPOuKJ 1](https://user-images.githubusercontent.com/10351221/194752375-83e2b14b-045e-4667-ac92-5ab2771e914e.png)

**Comment by ricksouth** [comment]
This seems to have been fixed on Silent Gear's end. Thanks for giving the mod a try!
