### ISSUE TITLE
Collective Crash 1.19.2 once loaded it crashes

### ISSUE THREAD

**Issue by MelrikBirchJr** [ricksouth/serilum-mc-mods#1363]
## **Information**
Minecraft version: xx.xx.xx
Modloader: Forge / Fabric
Forge version: xx.xx.xx  OR  Fabric loader version: x.xx.x
Environment: Singleplayer / Multiplayer

Mod name: Mod
Mod version: x.x
Collective
2-5.0 October 1st
## **Description**
Hey! This happened.
When i load my game and good thing i have not enough crashes to help with this but once in mod menu to look at my mods list clicking on and idk if you can fix this cause its 1.19.2 Forge 43.1.34
## **Crash report**
_(Please either drag the file directly here, or use https://gist.github.com/ to prevent the paste from expiring)_

If available.
[crash-2022-10-09_21.16.11-fml.txt](https://github.com/ricksouth/serilum-mc-mods/files/9743091/crash-2022-10-09_21.16.11-fml.txt)

**Comment by James103** [comment]
Try reinstalling Collective in your modded instance, version 4.57 or later.

**Comment by ricksouth** [comment]
You'll need to install Collective in order for the mods to work. It's available here:
https://www.curseforge.com/minecraft/mc-mods/collective/files/all?filter-status=1&filter-game-version=1738749986:73407

**Comment by MelrikBirchJr** [comment]
i did have it installed it just kept crashing
