### ISSUE TITLE
Tree Harvester - server stop/crash in Auto Replace Sapling moment.

### ISSUE THREAD

**Issue by Reniel80** [ricksouth/serilum-mc-mods#1365]
## **Information**
Minecraft version: 1.18.2
Modloader: Forge
Forge version: 40.1.80  
Environment: Dedicated Forge Server

Mod name: Tree Harvester
Mod version: treeharvester_1.18.2-5.7

## **Description**
Forge server stop/crash in Auto Replace Sapling moment.

## **Crash report**

[crash-2022-10-13_14.44.47-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/9779713/crash-2022-10-13_14.44.47-server.txt)

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 7.2 of Tree Harvester.

https://curseforge.com/minecraft/mc-mods/tree-harvester/files
