### ISSUE TITLE
Totem inventory mod not giving fire resistance when using totems

### ISSUE THREAD

**Issue by triplelane** [ricksouth/serilum-mc-mods#1368]
## **Information**
Minecraft version: xx.xx.xx
Modloader: Forge / Fabric
Forge version: xx.xx.xx  OR  Fabric loader version: x.xx.x
Environment: Singleplayer / Multiplayer

Mod name: Inventory Totem
Mod version: any

## **Description**
Totem inventory mod not giving fire resistance when using totems

## **Crash report**
_(Please either drag the file directly here, or use https://gist.github.com/ to prevent the paste from expiring)_

If available.

**Comment by James103** [comment]
1. Can you reproduce with only Inventory Totem and Collective?
2. What Minecraft, Forge, and Fabric Loader versions did you test this on? If you tested on Fabric, please also specify the Fabric API versions you tested with (if any).
3. Does using a totem still give Absorption and Regeneration, or are those effects not given as well?

**Comment by ricksouth** [comment]
Good catch! I didn't notice they added the Fire Resistance effect in 1.16. This has been fixed in version 2.2 of Inventory Totem. Thanks!

https://www.curseforge.com/minecraft/mc-mods/inventory-totem
