### ISSUE TITLE
Crash when replanting sapling

### ISSUE THREAD

**Issue by SesameSlayer** [ricksouth/serilum-mc-mods#1370]
When I harvested a spruce tree, it crashed the game, and, interestingly, also the launcher, so I couldn't see a crash report. I believe that this is due to the replanting, as the crash happened when the items touched the ground. I believe this is due to this mod, but here's my mod list:
apexcore
AutoRegLib
BiomesOPlenty
blueprint
catalogue
collective
configured
corpse
create
fantasyfurniture
Jade
jei
open-parties-and-claims-forge
OptiFine
Quark
Terrablender-forge
treeharvester
woodworks
Xaeros_Minimap

**Comment by James103** [comment]
1. Are you able to reproduce this crash?
2. A crash report should have been generated in your Minecraft instance's `.minecraft/crash-reports` folder. Will you please attach it here?
3. Do you have the versions for the mods you were using at the time of crash? If so, can you please post them as well?
    This information should be included in the crash report.

**Comment by SesameSlayer** [comment]
1: I believe so, yes, unless it has to do with my system. #1365 has the same error, on a different version, so this crash seems due to this mod.
2: Crash report:
[crash-2022-10-16_17.41.36-client.txt](https://github.com/ricksouth/serilum-mc-mods/files/9805143/crash-2022-10-16_17.41.36-client.txt)
3: The versions go as follows:
apexcore-1.19.2-7.3.0
AutoRegLib-1.8-54
BiomesOPlenty-1.19.2-17.1.1.150
blueprint-1.19.2-6.1.0
catalogue-1.6.3-1.19
collective-1.19.2-5.7
configured-2.0.1-1.19.2
corpse1.19.2-1.0.0
fantasyfurniture-1.19.2-6.5.0
Jade-1.19.1-forge-8.3.0       -- works for 1.19.2 also
jei-1.19.2-forge-11.2.0.246
open-parties-and-claims-forge-1.19.2-0.15.1
OptiFine_1.19.1_HD_U_H9
Quark-3.3-371
TerraBlender-forge-1.19.2-2.0.1.127
treeharvester_1.19.2-5.7
woodworks-1.19.2-2.1.0
Xaeros_Minimap-22.15.1_Forge_1.19.1

**Comment by PhillipAshfordJr** [comment]
I made my account specifically for this, my friends and I were having the same issue and, at least for us, it was caused by modded trees not being able to be planted by tree harvester. So we just disabled the auto plant on trees/mushrooms and it fixed it for us!

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 7.2 of Tree Harvester.

https://curseforge.com/minecraft/mc-mods/tree-harvester/files
