### ISSUE TITLE
Make it so you can spawn in the game with items from other mods? or maybe this is a bug?

### ISSUE THREAD

**Issue by TheeMrCheeky** [ricksouth/serilum-mc-mods#1371]
Forge
Mod name: Starter Kit

At least when I try with first aid mod, When I it to spawn in with 3 bandages in inventory they don't appear.. I have Double checked multiple times to make sure my spelling was right.. But nothing.

**Comment by ricksouth** [comment]
I'd recommend using the

/starterkit set

command in-game. Just have what you want new players to spawn with in your inventory it'll create a new config. Bandages should be no problem. Does that work?

**Comment by TheeMrCheeky** [comment]
Ah.. Okay yeah that worked :D 

Quick side note what is the damage for ? Guessing like damage already done to that item? '{Count:1b,id:"minecraft:wooden_sword",tag:{Damage:0}}'

**Comment by ricksouth** [comment]
Yes that would be the durability of the item. 0 damage = 100% durability :)

**Comment by TheeMrCheeky** [comment]
Well thanks for letting me know that! haha. Keep up the good work.

**Comment by ricksouth** [comment]
Thanks for giving the mod a try!
