### ISSUE TITLE
[Collective] Feature suggestion: config option to disable file name checker

### ISSUE THREAD

**Issue by Nevrai** [ricksouth/serilum-mc-mods#1372]
## Information

**Mod name:** Collective
**Minecraft version:** 1.18.2
**Mod loader:** Forge

## Feature description

I added a number sign (`#`) to the beginning of the file names for all the library mods in my modpack, to make testing and troubleshooting easier. However, Collective apparently has a file name checker built-in, and it thinks that I downloaded the mod from an unsafe source, which I didn’t.

![KFmrdf4](https://user-images.githubusercontent.com/59761487/196432563-625bdf0a-0c8e-45be-b172-d14ac3f9f721.png)

The message won’t show up again in the same instance, but since I’m making a modpack that others will play, this message will show up for any player playing the pack for the first time, and it makes it seem like the modpack author, me, downloaded mods from unsafe sources, which definitely isn’t ideal.

My suggestion is to add a config option to Collective’s config that disables the file name checker. If this could be implemented, that’d be wonderful.

**Comment by James103** [comment]
That already exists. Set `enableAntiRepostingCheck = false` in the config file for the Collective mod in your mod pack.

**Comment by Nevrai** [comment]
Oh, my bad. I checked the config but couldn’t find this option. I see it now, though. Thank you!

**Comment by ricksouth** [comment]
Manually renaming files is indeed one of the problems with the check, sorry for that. But it redirects a lot of traffic from reposting sites like 9minecraft to curseforge. Thanks for giving the mod a try!

**Comment by Nevrai** [comment]
Yeah, it’s definitely understandable. Don’t get me wrong, I’m all for this feature. Sites like 9minecraft ruin everything, and I honestly have no idea how that site is still running and still gets near the top of Google search results. Surely it has to be illegal what they’re doing.
