### ISSUE TITLE
[Question] No Hostiles Around Campfire

### ISSUE THREAD

**Issue by Looodon** [ricksouth/serilum-mc-mods#1375]
## **Information**
Environment: Singleplayer / Multiplayer
Mod name: No Hostiles Around Campfire (Forge)
Mod version: 1.19.2-4.5

## **Question**
Hey! 
1) I was wondering how the "preventHostilesRadius" works. Does it apply on a y axis as well? if so is it a cube shape?
2) if i place it on top of a villager house will it still effect the floor around it? Can I place it 1 block underground? 
3) Also would the campfires effect pillagers from spawning during raids if placed outside and inside the villagers? 
Thanks!

**Comment by OysterStew** [comment]
I was wondering this too ...

**Comment by Estecka** [comment]
A quick look at the sources leads me to believe the area of effect is sphere-shaped, ([they use `getBlockPos().closerThan()`](https://github.com/Serilum/No-Hostiles-Around-Campfire/blob/310fdc35c50909a8529c8dfd96c9501c629dc17b/Common/src/main/java/com/natamus/nohostilesaroundcampfire/events/CampfireEvent.java#L90) to check the distance), so the radius would apply vertically as well.
