### ISSUE TITLE
"Your Items Are Safe"-Mod Helmet doens't appear on armorstand or in chest

### ISSUE THREAD

**Issue by Pokihead** [ricksouth/serilum-mc-mods#1377]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 43.1.43
Environment: Singleplayer / Multiplayer Both

Mod name: Your Items Are Safe
Mod version: 2.0

## **Description**
Since the 2.0 version of this mod the helmet does not spawn on the armor stand anymore like in earlier versions.
Furthermore it isn't in a chest too. It just lays around near the deathpoint. Of course i have "addPlayerHeadToArmorStand = false".
There are no Errors or Warnings in the logs.
But if you still want them i can add them if you wish.

## **Crash report**
---

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has (finally) been fixed in version 3.1 of Your Items Are Safe.

https://www.curseforge.com/minecraft/mc-mods/your-items-are-safe/files
