### ISSUE TITLE
Collective is not a dependency of Collective.

### ISSUE THREAD

**Issue by Obscure2020** [ricksouth/serilum-mc-mods#1379]
I use ATLauncher for its powers of easy mod installation and automatic dependency detection.
Today, I went to install your GUI Clock mod and I noticed something odd.

The installation popup for GUI Clock said it requires Collective as a dependency.
So I clicked on the inlaid Add button to install Collective first.
The installation popup for Collective said it requires Collective as a dependency.
That can't be right.
(Click on this image to take a closer look.)
![image](https://user-images.githubusercontent.com/69320464/197049928-8ba3652a-a623-4340-ba57-882497095bac.png)

So I went to Modrinth to see what was up, and sure enough, you have marked Collective as a dependency of Collective.
![image](https://user-images.githubusercontent.com/69320464/197050604-211c5035-de04-46e2-936a-7e671c322b66.png)
![image](https://user-images.githubusercontent.com/69320464/197050629-9337a552-946b-4a45-8916-10266e5ba834.png)
![image](https://user-images.githubusercontent.com/69320464/197050664-b703b652-209f-4ce0-a893-2c4821636e83.png)

This is both confusing and unnecessary.
Collective does not require Collective.
If it did, it would be technically impossible to install it, because Collective would require Collective, which would require Collective, which would require Collective, which would require Collective, which would require Collective, which would require Collective, which would require Collective...

Please fix this.
Collective requires ONE dependency: the Fabric API.
(And really, NO mod would EVER require ITSELF as a dependency. What practical purpose could that possibly serve????)

**Comment by ricksouth** [comment]
You're completely right. This is a bug that has slipped into the code that manages my uploads to Modrinth. I've changed the last files to not have the dependency, and it has been fixed for future releases. Appreciate you letting me know! This was something that has gone under the radar for me 😅

**Comment by ricksouth** [comment]
![](https://media2.giphy.com/media/E8rJEUMGs9cyWEtNXT/giphy.gif?cid=ecf05e47dxhveag3rxktwfit00a890won8kkmbol7b36dygn&rid=giphy.gif)

**Comment by Obscure2020** [comment]
Hey, that was quick!
I can confirm the dependency list has been fixed on the latest version on Modrinth.
Glad I could help!
