### ISSUE TITLE
[1.16.5 fabric] The welcomemessage-fabric doesn't have config in config folder

### ISSUE THREAD

**Issue by quentin452** [ricksouth/serilum-mc-mods#1382]
## **Information**

Mod name: welcomemessage-fabric
Mod version: 1.16.5-1.8

## **Description**

Even if i open the game , the config is empy

**Comment by jarocajavi** [comment]
IN 1.19.2 fabric version too

**Comment by JTModel3** [comment]
Yep same here

**Comment by netcore10** [comment]
same here

**Comment by ricksouth** [comment]
Thanks for opening the issue and confirming it everyone! This has been fixed in version 5.18 of Collective. Welcome Message doesn't need an update. Apologies for the inconvenience.

https://www.curseforge.com/minecraft/mc-mods/collective-fabric/files
