### ISSUE TITLE
Beautified Chat (Server) not working.

### ISSUE THREAD

**Issue by ZephemusX** [ricksouth/serilum-mc-mods#1384]
## **Information**
Minecraft version: 1.19.2
Modloader: Fabric
Fabric loader version: 0.14.10
Environment: Multiplayer

Mod name: Beautified Chat Server
Mod version: Latest

## **Description**
Beautified Chat Server doesn't seem to work at all, I have to change something in the config?

I have collective installed and this are the mods that I am using.
https://imgur.com/HyjsjlR

Only one datapack and is for world generation.

https://imgur.com/GG1y6GQ

## **Crash report**
The server starts but the mod doesn't work

**Comment by James103** [comment]
What do you get in the client and/or server logs when a player sends a chat message while the mod is installed on the server?

**Comment by ZephemusX** [comment]
https://mclo.gs/zruI5JL

**Comment by ZephemusX** [comment]
> What do you get in the client and/or server logs when a player sends a chat message while the mod is installed on the server?

https://mclo.gs/zruI5JL

**Comment by ZephemusX** [comment]
i removed all the mods, only collective, beautified chat and fabric api, still not working.

**Comment by ZephemusX** [comment]
I did a clean server installation with only the mods that I mentioned in my last comment, still not working.
I also tried to modify the config, but nothing happens.
This is the log of the "clean installation"
https://mclo.gs/xS8ZOOz

**Comment by ricksouth** [comment]
Hi, thanks for the interest in the mod! Beautified Chat Server for Fabric does not have a 1.19 version available. What is the full jar name you're using?

**Comment by ZephemusX** [comment]
> Hi, thanks for the interest in the mod! Beautified Chat Server for Fabric does not have a 1.19 version available. What is the full jar name you're using?

Probably a mistake? In modrinth appears that you put a 1.19.2 version.

name of the jar:
beautifiedchatserver-fabric_1.19.2-1.7.jar

modrinth link:
https://modrinth.com/mod/beautified-chat-server/version/1.19.2-1.7-fabric

Do you have plans to port this mod to 1.19.2?

thanks for answering and have a good day/night!

**Comment by ricksouth** [comment]
Ah, I removed them from CurseForge but forgot Modrinth. Did that now. There was a build that I thought was working, but it didn't work out that way. I'll definitely do another attempt in the near future. Appreciate the interest!
