### ISSUE TITLE
GUI Clock shows time larger than 24h

### ISSUE THREAD

**Issue by Shimoblk** [ricksouth/serilum-mc-mods#1387]
## **Infomation**
Minecraft version: 1.12.2
Modloader: Forge
Forge version: 14.23.5.2860
Environment: Singleplayer

Mod name: GUI Clock
Mod version: 1.3

## **Description**
The gui of mod shows ingame time larger than 24h as the left side.
![image](https://user-images.githubusercontent.com/83323703/197926802-ca5afd1a-e0ed-4598-9377-1fd7cece1314.png)
However it only happens in this save I am playing, when I turn to a test save it's correctly showed. Considering I did use /time set, maybe that's the reason?

## **Crash report**
No crash report

**Comment by ricksouth** [comment]
Unfortunately I no longer support version 1.12. Please update to a later version to receive the latest updates. Apologies for the inconvenience.
