### ISSUE TITLE
Datapack Version

### ISSUE THREAD

**Issue by EvanHsieh0415** [ricksouth/serilum-mc-mods#1388]
Can you allow me to make a Datapack version and upload it to CurseForge?

The source code for the Datapack version I made is here
https://github.com/EvanHsieh0415/WoolTweaks-Datapack

**Comment by ricksouth** [comment]
I appreciate that you'd ask, but no, you can't just copy my files and rehost it as your own. I have no control over you making the files yourself, but this is not a request I grant permission for.

**Comment by EvanHsieh0415** [comment]
But I didn't copy your file, I finished it by myself according to the screenshot, detailed records can see the GIhub commit record

**Comment by ricksouth** [comment]
I assume CurseForge is making you do this request because it uses the same name?

**Comment by EvanHsieh0415** [comment]
> But I didn't copy your file, I finished it by myself according to the screenshot, detailed records can see the GIhub commit record

I will add you to the Contributors of my repo and to the authors of CurseForge

**Comment by EvanHsieh0415** [comment]
> I assume CurseForge is making you do this request because it uses the same name?

I am not very sure, but the name is similar, but the icon is drawn separately, if you do not agree with me using the name, I can modify it

**Comment by EvanHsieh0415** [comment]
I'm sorry that I didn't get your permission after the beginning of the production.

**Comment by ricksouth** [comment]
I get that you didn't have bad intentions, and there are probably some who would want this as a datapack only. I have no control over what datapacks you make, this is just not something I can give explicit permission for. I recommend using a different name yes.

The recipes itself aren't copyrighted, and the idea has been done before too. With a name change it wouldn't be a problem, I think.

**Comment by EvanHsieh0415** [comment]
Thank you for your reply.
I hope I can put your name in the text and in the relevant places to express the reason for the creation

**Comment by ricksouth** [comment]
I do appreciate you asking permission. You could call it Wool Recipes maybe?

**Comment by EvanHsieh0415** [comment]
This sounds really good, thank you very much!

**Comment by ricksouth** [comment]
Glad you like it. You don't have to add me to the project, the reward points can be all yours. No worries ;)

**Comment by EvanHsieh0415** [comment]
Ok thanks and have a good day!
