### ISSUE TITLE
Areas should have an option to turn off "leaving" messages

### ISSUE THREAD

**Issue by dehen** [ricksouth/serilum-mc-mods#1393]
## **Information**
Minecraft version: 1.19
Modloader: Forge / Fabric

Mod name: Areas

## **Feature description**
Areas should have an option to disable "leaving" messages altogether. While entering messages add flavor, when you're quickly running through a village on your  way to somewhere else, the exit message can feel pretty spammy.

**Comment by TheOtherworldly** [comment]
I agree

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been added in version 5.0 of Areas, alongside other bug fixes and QoL features. Apologies it took so long for me to get to.

https://www.curseforge.com/minecraft/mc-mods/areas/files
