### ISSUE TITLE
Areas HUD font should have dropshadow or outline

### ISSUE THREAD

**Issue by dehen** [ricksouth/serilum-mc-mods#1394]
## **Information**
Minecraft version: 1.19
Modloader: Fabric

Mod name: Areas

## **Feature description**
The Areas HUD font needs a dropshadow, because the background colors are unpredictable and the text can be unreadable in some situations. Adding a dropshadow gives enough hinting that the text can still be read even when it's the exact color as the world.

Alternatively this could be implemented as a darkened box behind the text, or and outline. But most mod/vanilla text on the HUD just uses dropshadow.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been added in version 5.0 of Areas, alongside other bug fixes and QoL features. Apologies it took so long for me to get to.

https://www.curseforge.com/minecraft/mc-mods/areas/files
