### ISSUE TITLE
Areas HUD isn't going away when entering or leaving an area

### ISSUE THREAD

**Issue by AzrouStone** [ricksouth/serilum-mc-mods#1397]
Basically making a sign that is 95-100 radius for a server town, now anyone that entered the area had the name of the server town, Spawnville, stuck permanently to the top of their screen until the server reset.

**Comment by ricksouth** [comment]
Has this happened before, are you able to replicate it?

**Comment by AzrouStone** [comment]
Every time yes, it sticks to the top or doesn’t appear at all which can happen randomly but either one will always happen

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 5.0 of Areas, alongside other bug fixes and QoL features. Apologies it took so long for me to get to.

https://www.curseforge.com/minecraft/mc-mods/areas/files
