### ISSUE TITLE
Bone meal that comes from a dispenser does not have random flowers

### ISSUE THREAD

**Issue by Tourmi** [ricksouth/serilum-mc-mods#1398]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 43.1.47
Environment: Multiplayer

Mod name: Random Bone Meal Flowers (Forge)
Mod version: 3.0

## **Description**
Bone meal that comes from a dispenser does not have random flowers
Seems to be the same issue as #782

4 bone meals with dispenser, removing weeds every time
![image](https://user-images.githubusercontent.com/29369803/199613855-9389b35a-4c35-47da-a2de-4bddc2af720b.png)

4 manual bone meals, removing weeds every time
![image](https://user-images.githubusercontent.com/29369803/199614174-2f5d0365-7e97-44c9-9a8d-3c51387f9437.png)

**Comment by Tourmi** [comment]
Looked a bit more into the issue, and it seems like BoneMealEvent is not fired by Forge with dispensers, since those are specific to the Player

**Comment by Tourmi** [comment]
Went into debug with the mod, the flowers do not exist yet when the world.getServer().execute() task gets run

![image](https://user-images.githubusercontent.com/29369803/199824965-1b7ac1b6-a32e-4243-8758-199787d0c4d4.png)


When using bone meal manually, the task gets scheduled for later
![image](https://user-images.githubusercontent.com/29369803/199821388-d49a01d5-1bc2-44f3-8b33-5cba2dc74d89.png)

When using bone meal via dispenser, the task gets run immediately
![image](https://user-images.githubusercontent.com/29369803/199821752-8eecea6f-1a8b-4ba8-92a6-b2df6dbc5fe0.png)

**Comment by Tourmi** [comment]
Pre-fix video of #1401 
https://user-images.githubusercontent.com/29369803/199826755-3b2002fa-35f3-42e0-9867-ac9364039d43.mp4

Post-fix video of #1401 
https://user-images.githubusercontent.com/29369803/199825674-0be2932a-6778-41c3-837d-e1ffeb185a35.mp4

**Comment by EightBitBBQ** [comment]
Weird thing, this worked in the past (had same flower shaker setup as you.. 

Dont work on my side either

**Comment by ricksouth** [comment]
Thank you for the research and the Pull Request! I'll take a look at merging it soon. Appreciate it.

**Comment by RedW0lfStoneYT** [comment]
Glad to know its not just a me thing,
Any ETA on when this will be fixed? 
(Note this issue also occurs in fabric 1.19.2)

**Comment by ricksouth** [comment]
Thanks for the PR @Tourmi! The changes have been pushed and I've just uploaded version 3.3 of Random Bone Meal Flowers for both Forge and Fabric.

https://www.curseforge.com/minecraft/mc-mods/random-bone-meal-flowers/files
https://www.curseforge.com/minecraft/mc-mods/random-bone-meal-flowers-fabric/files
