### ISSUE TITLE
Is replanting crops a server side mod?

### ISSUE THREAD

**Issue by VeggeieDude** [ricksouth/serilum-mc-mods#1402]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.19.2
Modloader: Fabric
Forge version: xx.xx.xx  OR  Fabric loader version: x.xx.x
Environment: Multiplayer

Mod name: Replanting Crops (Fabric)
Mod version: x.x

## **Question**
Can you use this on a multiplayer server without having the clients install the mod?

**Comment by ricksouth** [comment]
Yes this should work server-side. Thanks for the interest!
