### ISSUE TITLE
Starterkit not working on 1.19.2

### ISSUE THREAD

**Issue by pokesmells** [ricksouth/serilum-mc-mods#1404]
## **Information**
Minecraft version: 1.19.2
Modloader: Fabric
Fabric loader version: 0.14.10
Environment:  Both in Singleplayer / Multiplayer

Mod name: Starter Kit
Mod version: starterkit-fabric_1.19.2-3.8.jar

## **Description**
Hey! So I used /starterkit set and it shows that I indeed do have a new kit in the config, but my kit isn't popping up whatsoever :p

-------------------------------------------
'offhand' : '',
'head' : '',
'chest' : '{Count:1b,id:"minecraft:leather_chestplate",tag:{Damage:0,selected:{}}}',
'legs' : '',
'feet' : '',
0 : '',
1 : '',
2 : '',
3 : '',
4 : '{Count:1b,id:"ftbquests:book"}',
5 : '{Count:1b,id:"dehydration:handbook"}',
6 : '{Count:1b,id:"cookingforblockheads:recipe_book"}',
7 : '{Count:1b,id:"adorn:guide_book"}',
8 : '',
9 : '{Count:1b,id:"adventurez:handbook"}',
10 : '{Count:1b,id:"bewitchment:book_of_shadows"}',
11 : '{Count:1b,id:"paradise_lost:lore_book"}',
12 : '{Count:1b,id:"patchouli:guide_book",tag:{"patchouli:book":"indrev:indrev"}}',
13 : '{Count:1b,id:"patchouli:guide_book",tag:{"patchouli:book":"extraalchemy:alchemist_guide"}}',
14 : '{Count:1b,id:"patchouli:guide_book",tag:{"patchouli:book":"doom:doom"}}',
15 : '{Count:1b,id:"powah:book"}',
16 : '{Count:1b,id:"simple_shelves:redstone_book"}',
17 : '{Count:1b,id:"xps:handbook"}',
18 : '',
19 : '',
20 : '',
21 : '',
22 : '',
23 : '',
24 : '',
25 : '',
26 : '',
27 : '{Count:1b,id:"minecraft:stone_sword",tag:{Damage:0}}',
28 : '{Count:1b,id:"minecraft:stone_pickaxe",tag:{Damage:0}}',
29 : '{Count:1b,id:"minecraft:stone_axe",tag:{Damage:0}}',
30 : '{Count:16b,id:"minecraft:bread"}',
31 : '{Count:64b,id:"minecraft:torch"}',
32 : '{Count:1b,id:"scout:pouch",tag:{Items:[{Slot:0,Stack:{Count:1b,id:"minecraft:air"}},{Slot:1,Stack:{Count:1b,id:"minecraft:air"}},{Slot:2,Stack:{Count:1b,id:"minecraft:air"}}]}}',
33 : '',
34 : '',
35 : '',
------------------------------------------------------------------------------------

**Comment by pokesmells** [comment]
[latest.log](https://github.com/ricksouth/serilum-mc-mods/files/9943298/latest.log)

Here is the latest log, should include all the mods I got just in case

**Comment by ricksouth** [comment]
How are you testing the starter kit? In a new world? Do you spawn with anything else?

**Comment by pokesmells** [comment]
I am using a new world yes, what I also did was deleted the world, but saved the config, and also on the server I set the starterkit and asked a friend to join to test it out.

I spawn with 4 books, from MCA, Paladins Furniture, and Modern Industrialization

**Comment by pokesmells** [comment]
The spawn with books is not the starterkit, it's the default, possibly the mods are messing with the starterkit

**Comment by pokesmells** [comment]
A bit confused here, so I did a bit of testing, and it seems as though by deleting the "playerdata" folder in the world after it's made and then rejoining, makes it so the kit works, but let's say my configs are set, and I delete the "world" folder and run the server and which proceeds to make a new world? it doesn't give me the kit

**Comment by pokesmells** [comment]
HA! I've figured it out, basically Modern Industrialization messes the ENTIRE thing up, if you don't disable it, your kit will never work

**Comment by pokesmells** [comment]
Luckily they have a property in the json which disables it phew

**Comment by ricksouth** [comment]
Glad you got it working! Thanks for doing the research. If you leave the issue open, I can take a look at adding compatibility. Appreciate it :)

**Comment by pokesmells** [comment]
I shall keep it open!, you're awesome dude thank you :)

**Comment by ricksouth** [comment]
This has been fixed in Starter Kit 4.0, together with the latest Collective update. Thanks for giving the mod a try and opening the issue!

https://www.curseforge.com/minecraft/mc-mods/starter-kit-fabric/files
https://www.curseforge.com/minecraft/mc-mods/collective-fabric/files
