### ISSUE TITLE
Issue with The Vanilla Experience multiplayer 

### ISSUE THREAD

**Issue by Treerex1** [ricksouth/serilum-mc-mods#1408]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.19.12
Modloader: Forge
Forge version: 43.1.47  
Environment:  Multiplayer

Mod name: The Vanillla Experience
Mod version: 5.21

## **Question**
After Installing Java server into the file, run.bat. only says Error: "Could not find or load main class @user_jvm_args.txt"
I only have little to no experience with files what do I do?

**Comment by ricksouth** [comment]
I think you might be missing a correct Java install. Otherwise the Forge discord in the #tech-support channel should be able to help you out. https://discord.gg/forge
