### ISSUE TITLE
Crash with All Loot Drops Active

### ISSUE THREAD

**Issue by Delfite** [ricksouth/serilum-mc-mods#1410]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 43.1.47
Environment: Singleplayer

Mod name: All Loot Drops (Forge)
Mod version: 2.6

## **Description**
Whenever I attempt to launch the game with the All Loot Drops mod enabled, the game crashes. Simple as that.

## **Crash report**
https://gnomebot.dev/paste/1039259579902603346

**Comment by James103** [comment]
Converted paste to text file as it is unknown whether pastes on the site will stay for more than a few hours or days: [crash-2022-11-07_14.22.31-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/9955005/crash-2022-11-07_14.22.31-server.txt)

**Comment by Delfite** [comment]
> Converted paste to text file as it is unknown whether pastes on the site will stay for more than a few hours or days: [crash-2022-11-07_14.22.31-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/9955005/crash-2022-11-07_14.22.31-server.txt)

My guy, it stays forever.

**Comment by ricksouth** [comment]
This has been fixed in the latest version of Passive Endermen and All Loot Drops. Thanks for opening the issue and giving the mods a try!
