### ISSUE TITLE
Biome Spawn Point (Fabric) backport to 1.17.1

### ISSUE THREAD

**Issue by justlukie** [ricksouth/serilum-mc-mods#1415]
Minecraft version: 1.17.1
Modloader: Fabric
Environment: Singleplayer

Mod name: Biome Spawn Point

Can you backport the mod to 1.17.1? There are versions for 1.16, 1.18, and 1.19, but not for 1.17.

**Comment by ricksouth** [comment]
No sorry, that version isn't supported anymore. There is no updated Collective version for it either. At the moment I already support 6 versions (forge+fabric), my brain won't handle 8.

Appreciate the interest though, I recommend updating to 1.19 :)
