### ISSUE TITLE
Hide Hand

### ISSUE THREAD

**Issue by LiberteIV** [ricksouth/serilum-mc-mods#1416]
I'm using your hide hand mode for 1.19, 
I found the config file in
C:\Users\User\AppData\Roaming\.minecraft\config\hidehands-fabric.json

Content:
{
	// If enabled, always hides the main hand. If disabled, hides the main hand when holding the items defined in hideMainHandWithItems.
	"alwaysHideMainHand": false,
	// The items which when held will hide the main hand if alwaysHideMainHand is disabled.
	"hideMainHandWithItems": "",
	// If enabled, always hides the offhand. If disabled, hides the offhand when holding the items defined in hideOffhandWithItems.
	"alwaysHideOffhand": false,
	// The items which when held will hide the offhand if alwaysHideOffhand is disabled.
	"hideOffhandWithItems": ""
}

I installed this mod with one purpose only, the hide the disgusting playerhand that is always visible when no item is held.
Problem is, this mod seems to not hide the hand by default but instead always hide it when changing the flag from false to true.
I don't intend to hide equiped items, i simply want to hide the disgusting hand nothing more, is that possible with this mod?

Is there a value/parameter for the playerhand without any item held?

**Comment by itssimple** [comment]
You can see the options that the mod handles in the source code

https://github.com/ricksouth/serilum-mc-mods/blob/master/sources/Hide%20Hands/src/main/java/com/natamus/hidehands/config/ConfigHandler.java#L32-L49

So the answer to your question, looks like, it's: No, it's not possible to hide the hand, if it's empty.

**Comment by ricksouth** [comment]
Take a look at version 3.0 I've just released. It adds a new config option 'alwaysHideEmptyMainHand', enabled by default, which should do exactly what you want it to! I've also added an extra feature to show the hand when it is swung. Thanks for giving the mod a try! Hope it's useful to you.

https://www.curseforge.com/minecraft/mc-mods/hide-hands-fabric/files

**Comment by LiberteIV** [comment]
> Take a look at version 3.0 I've just released. It adds a new config option 'alwaysHideEmptyMainHand', enabled by default, which should do exactly what you want it to! I've also added an extra feature to show the hand when it is swung. Thanks for giving the mod a try! Hope it's useful to you.
> 
> https://www.curseforge.com/minecraft/mc-mods/hide-hands-fabric/files

Thanks for the reply, sadly i don't think this new version will work for me, i'm still on 1.19.1.
Could i import the 'alwaysHideEmptyMainHand' function from the new version to the old one?
Asuming it would be relatively simply by copy pasting a few lines of code?

Edit is great that you added this feature anyways.

**Comment by ricksouth** [comment]
I'd recommend updating to 1.19.2. Unfortunately supporting the older version would mean having an extra file and an extra project, times two because of the library. Not something my mind can keep up with. Hopefully you can use it in the future!
