### ISSUE TITLE
[Areas] Range parameter induces very high TPS and causes the game to hang

### ISSUE THREAD

**Issue by moninformateur** [ricksouth/serilum-mc-mods#1418]
## **Information**
Minecraft version: 1.18.2
Modloader: Forge
Forge version: 40.1.73 
Environment: Both Singleplayer and Multiplayer

Mod name: Areas
Areas version: 1.18.2-3.1
Collective's version: 1.18.2-5.15

## **Steps to reproduce**
Enable "Areas" mod.
Change "radiusAroundPlayerToCheckForSigns" parameter to a valid value (0 to 1000), say 300.
While in a new or old world, move around so that you invoke new chunks.
The `com.natamus.collective.functions.FABFunctions.getBlockEntitiesAroundPosition()` process seems to enter a loop, causing excessive TPS and freezes on heavily modded games.

## **Crash report**
This behavior does not causes the game to crash. The game becomes unresponsive and freezes while in the loop, but does not crash.

[Spark profiler report showcasing the issue is available here.](https://spark.lucko.me/B2JcUxFNTE)

**Comment by clarence112** [comment]
I have just experienced this issue on fabric 1.19.2
here is a crash report (crashed due to watchdog timer on server)
[crash-2023-04-11_20.12.40-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/11206024/crash-2023-04-11_20.12.40-server.txt)

**Comment by alkerss** [comment]
Same Issue. 
Also on a heavily modded modpack.
Fabric 1.19.2
Areas 4.3

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 5.0 of Areas, alongside other bug fixes and QoL features. Apologies it took so long for me to get to.

https://www.curseforge.com/minecraft/mc-mods/areas/files
