### ISSUE TITLE
Bug: Right Clicking on Dyed Item Reverts Dye

### ISSUE THREAD

**Issue by AutoRunFail** [ricksouth/serilum-mc-mods#1421]
## **Information**
Minecraft version: 1.19.2
Modloader: Fabric
Fabric loader version: 0.14.10
Environment: Singleplayer (Not tested in Multiplayer)

Mod name: Wool Tweaks
Mod version: 1.19.2-2.3 and 1.19.2-2.2

## **Description**
After dying a bed, carpet or wool with the mod, right-clicking on the item with an empty hand (including to sleep) reverts the item back to its original color. For beds, it will revert only the half of bed you clicked on, unless slept in, in which case it reverts the whole bed back. 

This was tested multiple times on several single player versions, but has not been tested on multi-player. There are no errors in the log associated with the issue. 

![Screenshot_1](https://user-images.githubusercontent.com/105956312/201503998-5ebb4c6b-86ed-4fe1-a4f9-25ef11210882.png)

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 2.4 of Wool Tweaks. Appreciate it!

https://www.curseforge.com/minecraft/mc-mods/wool-tweaks-fabric/files
