### ISSUE TITLE
1.19.2 Forge - GUI Compass: GUI for Recovery Compass

### ISSUE THREAD

**Issue by RedBeast1959** [ricksouth/serilum-mc-mods#1422]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge

Mod name: GUI Compass

## **Feature description**
I think it would be much better if recovery compass also show coordinate / direction ui.

**Comment by ricksouth** [comment]
Thanks for the suggestion! Version 2.9 of GUI Compass adds compatibility for the recovery compass.

https://www.curseforge.com/minecraft/mc-mods/gui-compass/files
