### ISSUE TITLE
save and load inventories not working in multiplayer

### ISSUE THREAD

**Issue by capybara696** [ricksouth/serilum-mc-mods#1425]
## **Information**
Minecraft version: 1.19.2
Modloader: Fabric
Forge version:Fabric loader version: 1.14.10
Environment:Multiplayer

Mod name: save and load inventories
Mod version: 2.4

## **Description**
mod does not work in multiplayer, writes an unknown command

## **Crash report**
_(Please either drag the file directly here, or use https://gist.github.com/ to prevent the paste from expiring)_

If available.

**Comment by ricksouth** [comment]
Hi! Did you install the mod on the server as well?
