### ISSUE TITLE
HUD not appearing in multiplayer

### ISSUE THREAD

**Issue by Reegmeister** [ricksouth/serilum-mc-mods#1429]
## **Information**
Minecraft version: 1.16.5
Modloader: Forge
Forge version: 36.2.39
Environment: Multiplayer

Mod name: Areas
Mod version: 3.1

## **Description**
Area messages from newly configured signs do not appear on clientside HUD until server is restarted.

Edit:
- /areas shows that the sign should be working after placement, however HUD messages do not appear as expected.
- Creative mode copying the sign with NBT data + breaking and replacing seems to force an update which causes the area messages to function as expected without restarting.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 5.0 of Areas, alongside other bug fixes and QoL features. Apologies it took so long for me to get to.

https://www.curseforge.com/minecraft/mc-mods/areas/files
