### ISSUE TITLE
For some reason, the sound is absolutely loud when the leaves break

### ISSUE THREAD

**Issue by faahbio** [ricksouth/serilum-mc-mods#1430]
## **Information**
Minecraft version: 1.19.2
Modloader: Fabric
Fabric loader version: 0.14.10
Environment: Singleplayer

Mod name: Tree Harvester
Mod version: 5.9

## **Description**
I have the feature turned on that when I chop a tree, the leaves break with them
The problem is that when those leaves break, the sound is too loud, I had to turn the "blocks" sound to 10% to hear it the same way as the other sounds, but now I can't hear the breaking blocks sound anymore
Is there a possibility to maybe turn down the leaves break sound or put an option on the config folder to manage that?

## **Crash report**
No crash report needed

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 7.2 of Tree Harvester. Make sure the mod is installed on the client as well.

https://curseforge.com/minecraft/mc-mods/tree-harvester/files
