### ISSUE TITLE
Not Working SP world 1.19.2

### ISSUE THREAD

**Issue by OysterStew** [ricksouth/serilum-mc-mods#1431]
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 43.1.52
Environment: Singleplayer

Mod name: Village Spawn Point
Mod version: 2.9

## **Description**
Am using several world generation Mods. William Wythers Overhauled Overworld,  Biomes o Plenty, and Terralith. Structure mods  Repurposed Structures, Towns and Towers and Moog's Voyager Structures. Also using Biome Spawn Point but have not specified a biome in it yet. I'm not spawning anywhere close to a village

**Comment by OysterStew** [comment]
Ok just tried this without Biome Spawn Point installed and seems to be working. Strange since I never specified a biome in it's cfg.

**Comment by ricksouth** [comment]
Thanks for opening the bug report! This was due to the code not running the "find a village"-function when no biome was specified. This has been fixed in version 1.6 of Biome Spawn Point. Appreciate you giving the mod a try!

https://www.curseforge.com/minecraft/mc-mods/biome-spawn-point
