### ISSUE TITLE
Nether Portal Spread keeps crashing for me whenever i try to load minecraft

### ISSUE THREAD

**Issue by justawander** [ricksouth/serilum-mc-mods#1435]
Minecraft version: 1.18.2
Modloader: Forge
Forge version: 40.1.84
Environment: Singleplayer

Mod name: Nether Portal Spread 
Mod version: 1.18.2-6.5

https://pastebin.com/KCZZ1xru

**Comment by ricksouth** [comment]
Can you give some more information on what the problem is? I can't find any reference to Nether Portal Spread in the crash log. Does it crash with only NPS installed?
