### ISSUE TITLE
[Difficulty Lock] Locked difficulty not reflected in World Creation UI

### ISSUE THREAD

**Issue by thimblebird** [ricksouth/serilum-mc-mods#1438]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 43.1.47
Environment: Singleplayer

Mod name: Difficulty Lock
Mod version: 1.6

## **Description**
Even though the mod defaults to "Hard" difficulty, in the world creation UI, it always says "Normal" by default.

**Comment by ricksouth** [comment]
Thank you for opening the bug report and giving the mod a try! Version 4.0 of Difficulty Lock fixes the Create World Screen not being updated.

https://curseforge.com/minecraft/mc-mods/difficulty-lock/files
