### ISSUE TITLE
[Suggestion] Rename "Fall Through Slime" to "Non-Newtonian Slime"

### ISSUE THREAD

**Issue by OCsonic** [ricksouth/serilum-mc-mods#1440]
Just thought the name sounded funny, what are your thoughts?

**Comment by ricksouth** [comment]
I like the name, and it's probably a reference to something, but I don't really know what it means 😇 I like to keep the names as understandable as possible, so I'll keep the old one. Appreciate the suggestion though!

**Comment by OCsonic** [comment]
> I like the name, and it's probably a reference to something, but I don't really know what it means innocent I like to keep the names as understandable as possible, so I'll keep the old one. Appreciate the suggestion though!

The name idea is a physics joke because something being a non-newtonian fluid means basically means that at high velocity it acts like a solid and at low velocity it acts like a liquid, the term comes from the fact that it doesn't follow Newton's law of viscosity.
