### ISSUE TITLE
world border question

### ISSUE THREAD

**Issue by normaluser12354** [ricksouth/serilum-mc-mods#1442]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.19.2
 Fabric
 Multiplayer

Mod name: world border
Mod version: 3.2

## **how do you change the border for the server because i dont really know how to change the border for different dimentions
also is it possible to have one dimension with no border?**
?

**Comment by ricksouth** [comment]
You can change the border size in the config file. This will also generate on the server. Unfortunately at the moment it's not possible to change the border for custom dimensions. It's planned though! Thanks for the interest.
