### ISSUE TITLE
Baby Villager spawn with adults height 

### ISSUE THREAD

**Issue by DarthPepo** [ricksouth/serilum-mc-mods#1443]
## **Information**
Minecraft version: 1.18.2
Modloader: Forge
Forge version: 40.1.84
Environment: Singleplayer

Mod name: Pumpkillager
Mod version: 2.2

## **Description**
Hey! So, for some reason, and i tried this in a clean installation with no other mods, when this mod is installed all baby villagers spawn with the height of adult villagers 

## **Crash report**
no crash to report!

**Comment by ricksouth** [comment]
Good catch! Thanks for opening the issue and giving the mod a try. This has been fixed in version 2.3 of Pumpkillager's Quest. Appreciate it!

https://www.curseforge.com/minecraft/mc-mods/pumpkillagers-quest/files
