### ISSUE TITLE
Tree Harvesting Process Breaks Trapdoors Placed Near Leaves

### ISSUE THREAD

**Issue by sw684** [ricksouth/serilum-mc-mods#1444]
I'm using the default config and the 1.19.2-5.9 Fabric version.

Before Planting Tree:
![2022-12-02_09 37 09](https://user-images.githubusercontent.com/101212595/205353327-d952d8ce-14e8-41bc-adbd-d64b41ca4e20.png)

Tree Grown:
![2022-12-02_09 37 45](https://user-images.githubusercontent.com/101212595/205353375-09996b2c-fbc4-49fc-842f-504e2a036fa7.png)

Tree Harvested Using Tree Harvester:
![2022-12-02_09 38 42](https://user-images.githubusercontent.com/101212595/205353430-e3fadfc3-a31f-42f9-8c72-9df7460e872d.png)

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 7.2 of Tree Harvester.

https://curseforge.com/minecraft/mc-mods/tree-harvester/files
