### ISSUE TITLE
House from "Forestry" and "RailCraft"

### ISSUE THREAD

**Issue by FLAPIXCODE** [ricksouth/serilum-mc-mods#1448]
## **Information**
Minecraft version: 1.12.2
Modloader: Forge
Forge version: 14.23.5.2860
Environment: Singleplayer

First mod name: Forestry
First mod version: 5.8.2.422

Second mod name: RailCraft
Second mod version: 12.0.0-beta-5

## **Description**
Houses from Forestry and RailCraft do not spawn in villages.

## **Crash report**
If available.

**Comment by FLAPIXCODE** [comment]
In mod "Village Names"!

**Comment by ricksouth** [comment]
The mod Village Names is not made by me. And none of my mods change which houses spawn in villages. I think you have the wrong github repo. But feel free to correct me if I'm wrong.
