### ISSUE TITLE
Passive Endermen (Forge): server side only?

### ISSUE THREAD

**Issue by Fillet456** [ricksouth/serilum-mc-mods#1453]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 1.19.2-43.1.7
Environment: Multiplayer

Mod name: Passive Endermen (Forge)
Mod version: 1.19.2

## **Question**
Is this mod a server side only mod or do clients need it as well? I could not find an answer looking through the other git issues or in the repo.

**Comment by ricksouth** [comment]
The mod should work server-side only. But I believe there's still some issues with the mod working in certain cases that I haven't been able to fix yet. Will give it another attempt soon! Thanks for the interest.
