### ISSUE TITLE
I didn't spawn in village 

### ISSUE THREAD

**Issue by githubuser98k** [ricksouth/serilum-mc-mods#1454]
## **Information**
Minecraft version: 1.16.5
Modloader: Forge
Forge version:36.2.39
Environment: Singleplayer

Mod name: village spawn point
Mod version: villagespawnpoint_1.16.5-3.0.jar

## **Description**
It didn't spawn me in the village
mod list
![mods 2022_12_7 下午 05_32_53](https://user-images.githubusercontent.com/96261514/206344003-c980d437-ccb4-405e-997f-ae4b925be182.png)
![mods 2022_12_7 下午 05_33_12](https://user-images.githubusercontent.com/96261514/206344006-71be01d6-fc8e-4215-88e9-5f7c1e1336b7.png)

**Comment by ricksouth** [comment]
Do you have the latest.log and debug.log for me with the mod installed? It should say what's going wrong. Thanks!

**Comment by githubuser98k** [comment]
nope I reset my file so I can't found it

**Comment by githubuser98k** [comment]
But I still have some problem about it's mod though
