### ISSUE TITLE
Vanilla Zoom keybinding issues

### ISSUE THREAD

**Issue by webcatzz** [ricksouth/serilum-mc-mods#1457]
## **Information**
Minecraft version: 1.19.2
Modloader: Fabric
Fabric loader version: 0.14.2
Environment: Singleplayer / Multiplayer

Mod name: Vanilla Zoom
Mod version: 1.1

The way this mod works is it seems to put the spyglass in your offhand and then automatically press the right mouse button. I have my use and attack keybinds switched, so my use keybind is actually the left mouse button. Instead of still zooming in, the mod just puts the spyglass in my offhand and attacks.

**Comment by ricksouth** [comment]
Thanks for giving the mod a try and opening the issue! This has been fixed in version 2.1 of Vanilla Zoom.

https://www.curseforge.com/minecraft/mc-mods/vanilla-zoom/files
