### ISSUE TITLE
Giant Spawn (Forge) Questions

### ISSUE THREAD

**Issue by penturt** [ricksouth/serilum-mc-mods#1458]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 43.2.0
Environment: Singleplayer & Multiplayer

Mod name: Giant Spawn (Forge)
Mod version: 3.0

## **Question**

1. To what degree can spawn chance be decreased to? I see the min is 0, but if i'm looking for a very low rate is 0.01 the lowest or can i do something like 0.0001 as an example?

2.  Are Giants able to jump higher then the normal 1 block zombie do? I see they have a custom AI, just curious if that is part of this AI.

**Comment by ricksouth** [comment]
Thanks for the interest! A chance of 0.0001 should work. There isn't really a limit to it. The giants have an AI based on zombies, so they can't jump higher. I think the limit is just one block
