### ISSUE TITLE
GUI Clock resetting to Day 0

### ISSUE THREAD

**Issue by Solarissss** [ricksouth/serilum-mc-mods#1460]
## **Information**
Minecraft version: 1.19.2
Modloader: Fabric
Fabric loader version: 1.19.2
Environment: Singleplayer
Mod name: GUI Clock
Mod version: 3.8

## **Description**
After around 80 days, the clock reset to Day 0. This happened twice, once in my creative world and once in a survival world.

**Comment by James103** [comment]
What do you get when you run `/time query day` in both of your affected worlds?
If they both return 0 as well, try running `/time add 1920000` (`/time add 80d`) on each of them to bring the day counter back to where it's supposed to be.

**Comment by ricksouth** [comment]
Can you try what @James103 suggested?
