### ISSUE TITLE
Server Player Death error

### ISSUE THREAD

**Issue by A5ho9999** [ricksouth/serilum-mc-mods#1473]
## **Information**
Minecraft version: 1.19.2
Modloader: Fabric
Fabric loader version: 0.14.11
Environment: Multiplayer

Mod: Collective [Fabric] 1.19.2-5.22
Mod: Just Player Heads [Fabric] 1.19.2-2.5

## **Description**
Error and sometimes complete server crash on player deaths when attempting to get Player Heads. Error also causes no inventory items to be dropped at all. First believed it may be conflicting with the Servercore/Server Pause

## Error
https://gist.github.com/A5ho9999/5710754b0a1a0b8f986e80294b73f6b9

All Mods
- architectury 6.2.43
	- armor-stand-editor 2.0.0-beta.4+1.19.2
	- bookshelf 16.1.5
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 8.1.77
	- collective-fabric 5.22
	- com_electronwill_night-config_core 3.6.6 via servercore
	- com_electronwill_night-config_toml 3.6.6 via servercore
	- com_github_llamalad7_mixinextras 0.1.0 via servercore
	- completeconfig 2.0.0
	- completeconfig-base 2.0.0 via completeconfig
	- fabric-api 0.60.0+1.19.2
	- fabric-api-base 0.4.12+93d8cb8290 via servercore
	- fabric-api-lookup-api-v1 1.6.9+9ff28f4090 via fabric-api
	- fabric-biome-api-v1 9.0.17+aeb40ebe90 via fabric-api
	- fabric-command-api-v1 1.2.11+f71b366f90 via fabric-api
	- fabric-command-api-v2 2.1.8+93d8cb8290 via servercore
	- fabric-commands-v0 0.2.28+df3654b390 via fabric-api
	- fabric-containers-v0 0.1.34+df3654b390 via fabric-api
	- fabric-content-registries-v0 3.2.3+aeb40ebe90 via fabric-api
	- fabric-convention-tags-v1 1.1.1+7cd20a1490 via fabric-api
	- fabric-crash-report-info-v1 0.2.5+aeb40ebe90 via fabric-api
	- fabric-data-generation-api-v1 5.1.8+a680b9b490 via fabric-api
	- fabric-dimensions-v1 2.1.30+aeb40ebe90 via fabric-api
	- fabric-entity-events-v1 1.4.18+9ff28f4090 via fabric-api
	- fabric-events-interaction-v0 0.4.28+aeb40ebe90 via fabric-api
	- fabric-events-lifecycle-v0 0.2.28+df3654b390 via fabric-api
	- fabric-game-rule-api-v1 1.0.21+aeb40ebe90 via fabric-api
	- fabric-item-api-v1 1.5.7+35a03c4390 via fabric-api
	- fabric-item-groups-v0 0.3.28+aeb40ebe90 via fabric-api
	- fabric-language-kotlin 1.8.3+kotlin.1.7.10
	- fabric-lifecycle-events-v1 2.2.0+33ffe9ec90 via servercore
	- fabric-loot-api-v2 1.1.3+83a8659290 via fabric-api
	- fabric-loot-tables-v1 1.1.6+9e7660c690 via fabric-api
	- fabric-message-api-v1 5.0.3+176380a290 via fabric-api
	- fabric-mining-level-api-v1 2.1.14+33fbc73890 via fabric-api
	- fabric-networking-api-v1 1.2.4+5eb68ef290 via fabric-api
	- fabric-networking-v0 0.3.21+df3654b390 via fabric-api
	- fabric-object-builder-api-v1 4.0.11+aeb40ebe90 via fabric-api
	- fabric-particles-v1 1.0.10+aeb40ebe90 via fabric-api
	- fabric-permissions-api-v0 0.2-SNAPSHOT via servercore
	- fabric-registry-sync-v0 0.9.24+aeb40ebe90 via fabric-api
	- fabric-rendering-data-attachment-v1 0.3.14+aeb40ebe90 via fabric-api
	- fabric-rendering-fluids-v1 3.0.7+aeb40ebe90 via fabric-api
	- fabric-resource-conditions-api-v1 2.0.11+e62f51a390 via fabric-api
	- fabric-resource-loader-v0 0.6.1+aeb40ebe90 via fabric-api
	- fabric-screen-handler-api-v1 1.2.13+9ff28f4090 via fabric-api
	- fabric-transfer-api-v1 2.0.11+83a8659290 via fabric-api
	- fabric-transitive-access-wideners-v1 1.3.0+42d99c3290 via fabric-api
	- fabricloader 0.14.11
	- fiber 0.23.0-2 via collective-fabric
	- java 17
	- justmobheads-fabric 6.2
	- justplayerheads-fabric 2.5
	- keepheadnames 1.5.1
	- lithium 0.8.3
	- logprot 1.19.1-1.6
	- me_lucko_spark-api 0.1-SNAPSHOT via servercore
	- memoryleakfix 1.19.1-0.7.0
	- minecraft 1.19.2
	- mousewheelie 1.10.2+mc1.19-pre1
	- org_jetbrains_kotlin_kotlin-reflect 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlinx_atomicfu-jvm 0.18.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.4.0 via fabric-language-kotlin
	- packet_tweaker 0.3.0+1.18.2 via server_translations_api
	- placeholder-api 2.0.0-pre.1+1.19.2 via servercore
	- player-data-api 0.2.1+1.19 via armor-stand-editor
	- server_translations_api 1.4.16+1.19 via armor-stand-editor
	- servercore 1.3.3-1.19.2
	- serverpause 1.1.0
	- sgui 1.1.4+1.19.1 via armor-stand-editor
	- spark 1.9.26
	- starlight 1.1.1+fabric.ae22326
	- toolstats 12.0.2
	- tweed4_annotated 1.3.1+mc22w17a via mousewheelie
	- tweed4_base 1.6.0+mc22w17a via mousewheelie
	- tweed4_data 1.2.1+mc22w17a via mousewheelie
	- tweed4_data_hjson 1.1.1+mc22w17a via mousewheelie

**Comment by mtlballer** [comment]
I have a similar error happening #1472 . Letting you know if you don't already, changing the boolean playerDropsHeadOnDeath to false has fixed the inventory deletion for the time being.

**Comment by ricksouth** [comment]
Does this still happen? I assume it had something to do with the API being down, giving a strange output which the mod didn't expect. But when trying it in my dev environment, it just works.

**Comment by VirulentSlayer** [comment]
Things seem stable again now. 

Tested using 
fabric-server-mc.1.19.2-loader.0.14.10-launcher.0.11.1.jar
![image](https://user-images.githubusercontent.com/51087559/208163498-1f7c1d14-2fac-40cf-b8cc-ac8b9fe6b943.png)

![image](https://user-images.githubusercontent.com/51087559/208163379-870fa01e-e9ff-40eb-9ac8-afac642d3c55.png)

**Comment by ricksouth** [comment]
I think so too! I'm uploading a new Collective version right now which adds an extra check. So if the API is down, which I think was the problem, it won't crash but just not return a player head.

**Comment by VirulentSlayer** [comment]
> Things seem stable again now.
> 
> Tested using fabric-server-mc.1.19.2-loader.0.14.10-launcher.0.11.1.jar ![image](https://user-images.githubusercontent.com/51087559/208163498-1f7c1d14-2fac-40cf-b8cc-ac8b9fe6b943.png)
> 
> ![image](https://user-images.githubusercontent.com/51087559/208163379-870fa01e-e9ff-40eb-9ac8-afac642d3c55.png)

**Comment by VirulentSlayer** [comment]
Good stuff! Thank you for the update

**Comment by ricksouth** [comment]
I believe it was due to the API being down, which the mod did not like. Thanks for opening the issue and giving the mod a try! Everything should work again as normal, but just in case I've uploaded version 5.35 of Collective to prevent errors in the future. Apologies for the inconvenience.

https://www.curseforge.com/minecraft/mc-mods/collective-fabric/files
