### ISSUE TITLE
village spawn point didn't spawn me in village

### ISSUE THREAD

**Issue by githubuser98k** [ricksouth/serilum-mc-mods#1474]
## **Information**
Minecraft version: 1.16.5
Modloader: Forge
Forge version:36.2.39
Environment: Singleplayer

Mod name: village spawn point
villagespawnpoint_1.16.5-3.0.jar

## **Description**
after I join the game, I reliase that I didn't spawn in a village or even near village

## **log**
[latest.log](https://github.com/ricksouth/serilum-mc-mods/files/10251045/latest.log)

mod list:
![螢幕擷取畫面 2022-12-16 223058](https://user-images.githubusercontent.com/96261514/208228935-30b7c961-71dc-4fb5-852b-4c36793f915e.png)
![螢幕擷取畫面 2022-12-16 223233](https://user-images.githubusercontent.com/96261514/208228938-015ec146-a196-4ec2-83aa-7a5b5784966a.png)
![螢幕擷取畫面 2022-12-16 223138](https://user-images.githubusercontent.com/96261514/208228939-2b3883cf-5007-40ca-9915-d3e0270a98b5.png)

**Comment by ricksouth** [comment]
Yea it looks like the mod isn't finding a village. Can you export the modpack as a zip to import in the CurseForge launcher? Looks like an incompatibility.

**Comment by githubuser98k** [comment]
[modpack.zip](https://github.com/ricksouth/serilum-mc-mods/files/10256216/modpack.zip)

**Comment by githubuser98k** [comment]
did you find it out yet

**Comment by ricksouth** [comment]
Maybe! Can you try the latest version of Village Spawn Point and Collective? Did you by any chance have the language of Minecraft set to a different one than English?

**Comment by githubuser98k** [comment]
I think I set the language to Chinese (traditional) because of the RPMTW mod setting, since I can't understand English very well, but i'll try the lastest version

**Comment by githubuser98k** [comment]
It's fixed thank you

**Comment by ricksouth** [comment]
Thanks for confirming and giving the mod a try! Glad it's been fixed. Have a nice day!
