### ISSUE TITLE
Beautified Chat - 1.19 release for Fabric 

### ISSUE THREAD

**Issue by SyberiaK** [ricksouth/serilum-mc-mods#1475]
## **Information**
Minecraft version: >=1.19
Modloader: Fabric
Environment: Singleplayer / Multiplayer

Mod name: Beautified Chat

## **Question**
Beautified Chat actually got 1.19 releases for Forge but not for Fabric. **Why?**

**Comment by ricksouth** [comment]
Because Forge has an event I could hook into, and I didn't manage to get it to work on Fabric yet. Appreciate the interest though! I'll give it another try soon.
