### ISSUE TITLE
GUI Compass Fabric 1.19.3

### ISSUE THREAD

**Issue by ElectricBullet** [ricksouth/serilum-mc-mods#1477]
## **Information**
Minecraft version: 1.19.3
Modloader: **Fabric**

Mod name: GUI Compass

## **Feature description**
This mod looks perfect, but there is only a Forge version for Minecraft 1.19.3. I load Fabric because I use Sodium/Lithium/Phosphor for stability and performance. Will there be a 1.19.3 Fabric version? I don't know how difficult it would be to update the 1.19.2 version to work with 1.19.3.

**Comment by ricksouth** [comment]
I must've skipped over it in the list! I just uploaded a version for 1.19.3. Thanks for letting me know!

https://www.curseforge.com/minecraft/mc-mods/gui-compass-fabric-version/files
