### ISSUE TITLE
Generated starter structure gets corrupted and scattered

### ISSUE THREAD

**Issue by Inonedn** [ricksouth/serilum-mc-mods#1480]
## **Information**
Minecraft version: 1.19.3
Modloader: 44.0.30
Forge version: xx.xx.xx  OR  Fabric loader version: x.xx.x
Environment: Singleplayer / Multiplayer

Mod name: Starter Structure
Mod version: 

## **Description**
When I load a schematic from a .schem file, the model becomes corrupted and has parts scattered everywhere. It seems to happen when a structure is 16+ blocks tall
![2022-12-20_16 46 11](https://user-images.githubusercontent.com/36087299/208773580-8ccb0a06-0b8f-40e8-b520-613b7259d83b.png)
![2022-12-20_16 49 46](https://user-images.githubusercontent.com/36087299/208773646-8dc9abe9-70e5-4dc4-9ef6-9aad1c64b0eb.png)

**Comment by ricksouth** [comment]
Thanks for opening the issue! Do you have the schematic file you used for me?

**Comment by Inonedn** [comment]
.schem

**Comment by James103** [comment]
> .schem

You may not have uploaded the schematic file properly or it failed to upload. Will you please try attaching the file again?

**Comment by Inonedn** [comment]
I can't upload it, as it doesn't support that type of file

**Comment by James103** [comment]
> I can't upload it, as it doesn't support that type of file

Will you please zip the file first then upload the resulting ZIP?

**Comment by Inonedn** [comment]
[InonednsMansion.zip](https://github.com/ricksouth/serilum-mc-mods/files/10279315/InonednsMansion.zip)

**Comment by ricksouth** [comment]
Thanks for uploading it! I'll try to take a look at the problem soon.

**Comment by AliceTheKitsune** [comment]
Hello! Today I also faced same problem. Seems like bigger structure means bigger chance for being corrupted. This mod works fine with small houses, but when I built starter island with small village it became really scattered in every world I tried to load it. I also tried to remake my schematic (it is in .schem file, I made it using worldedit)
![2023-05-30_21 54 19](https://github.com/ricksouth/serilum-mc-mods/assets/71220794/53af297f-cf6c-44c1-9919-ff9472e32f34)

**Comment by James103** [comment]
Can you please zip the schematics you're trying to use for Starter Structure (especially the starting village) and post the resulting zip files here?

**Comment by AliceTheKitsune** [comment]
Yes, sure, but I already found solution, use .nbt format instead of .schem (I made .nbt structure via create mod)
So in this zip there are two structures, one in .nbt (works fine) and .schem (you can load it with worldedit, but when you trying load it by starter structure it become corrupted)
[schematics.zip](https://github.com/ricksouth/serilum-mc-mods/files/11625800/schematics.zip)

**Comment by aanthonyssandoval1999** [comment]
I am having the same issue. I created a village with no entities or nbts and the top half seems to keep getting distorted.
![Screenshot 2023-07-28 134022](https://github.com/ricksouth/serilum-mc-mods/assets/54611520/96d0e726-88dc-4895-8595-5fa8353bd129)
![2023-07-28_14 05 15](https://github.com/ricksouth/serilum-mc-mods/assets/54611520/9ea54c44-75e5-49e3-b1a3-5932bc77d837)
[MarketTown.zip](https://github.com/ricksouth/serilum-mc-mods/files/12197623/MarketTown.zip)

**Comment by aanthonyssandoval1999** [comment]
> Yes, sure, but I already found solution, use .nbt format instead of .schem (I made .nbt structure via create mod) So in this zip there are two structures, one in .nbt (works fine) and .schem (you can load it with worldedit, but when you trying load it by starter structure it become corrupted) [schematics.zip](https://github.com/ricksouth/serilum-mc-mods/files/11625800/schematics.zip)

Were you able to get this issue fixed?

**Comment by ricksouth** [comment]
Hey everyone, I'm sorry it took so long for me to get to this. The problem was unfortunately hidden quite well.

But I'm happy to say it has been fixed in Collective version 7.28! Starter Structure doesn't need an update. Thank you all for the research and uploads. I really appreciate it.

https://legacy.curseforge.com/minecraft/mc-mods/collective/files
