### ISSUE TITLE
Gatekeeper villager name missing

### ISSUE THREAD

**Issue by Bmedina82** [ricksouth/serilum-mc-mods#1481]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge

Mod name: Villager Names

## **Feature description**
Add name for Gatekeeper from Blue Skies mod.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been added in version 6.0 of Villager Names and version 6.80 of Collective. :) Apologies it took so long for me to get to.

https://legacy.curseforge.com/minecraft/mc-mods/villager-names/files
https://legacy.curseforge.com/minecraft/mc-mods/collective/files
