### ISSUE TITLE
Serverside?

### ISSUE THREAD

**Issue by Surpos0** [ricksouth/serilum-mc-mods#1482]
Minecraft version: 1.19.2
Modloader: Fabric

Mod name: spiders produce webs

Is this mod a serverside only or I must install it on clients too?

**Comment by ricksouth** [comment]
The mod doesn't have to be installed on the client, only on the server. But of course if you want it on singleplayer it does. I'll update the descriptions of the mods soon with the information. Appreciate the interest!

**Comment by Surpos0** [comment]
Thx for replying <3
