### ISSUE TITLE
Cannot Remove Books from Other Mods

### ISSUE THREAD

**Issue by Lyigh** [ricksouth/serilum-mc-mods#1483]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 43.2.0
Environment: Singleplayer / Multiplayer

Mod name: Starter Kit
Mod version: 4.1

## **Bug/Unsure**

Setting addExistingItemsAfterKitSet to "false" does not remove books from loading in.

**Comment by ricksouth** [comment]
Thanks for opening the issue! Which mods still add books?

**Comment by Lyigh** [comment]
> Thanks for opening the issue! Which mods still add books?

Hexcasting. The One Probe is also adding in it's paper, as well. I could disable that in the config but I want Starter Kit to remove all modded books/info.

**Comment by ricksouth** [comment]
Yep, it should work that way! Thanks, I'll take a look soon (will probably be after the holidays)

**Comment by Lyigh** [comment]
Awesome. Thanks for such a quick response!

**Comment by MLMII** [comment]
Same issue on Quilt  ...  Simply Swords & Minecraft Comes Alive both add their books as well.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! Appreciate it. This has been fixed in version 5.1 of Starter Kit!

https://curseforge.com/minecraft/mc-mods/starter-kit/files
