### ISSUE TITLE
1.19.2

### ISSUE THREAD

**Issue by elgordo42** [ricksouth/serilum-mc-mods#1484]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.19.2
Modloader: Fabric
Environment: Singleplayer

Hi!
Constant crash at startup because it needs a file for 1.19.2.
But every single file available for download won't work unless you have 1.19.3.
Even the older versions transformed into 1.19.3 and no longer works for 1.19.2.
Why???
I need an later version to get other mods to work, but I need it for 1.19.2.
How do i get them??

**Comment by elgordo42** [comment]
Mod 'Starter Kit (Fabric)' (starterkit-fabric) 4.1 requires version 5.22 or later of mod 'Collective (Fabric)' (collective-fabric), but only the wrong version is present: 5.16!

Mod 'Collective (Fabric)' (collective-fabric) 5.45 requires version 1.19.3 of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!

**Comment by ricksouth** [comment]
You'll need the files which have 1.19.2 in the name. The CurseForge app does this automatically for you.

https://www.curseforge.com/minecraft/mc-mods/starter-kit-fabric/files/all?filter-status=1&filter-game-version=1738749986:73407

https://www.curseforge.com/minecraft/mc-mods/starter-kit-fabric/files/4139801

And


https://www.curseforge.com/minecraft/mc-mods/collective-fabric/files/all?filter-status=1&filter-game-version=1738749986:73407

https://www.curseforge.com/minecraft/mc-mods/collective-fabric/files/4136183
