### ISSUE TITLE
[IDEA] Future MC support

### ISSUE THREAD

**Issue by vico93** [ricksouth/serilum-mc-mods#1485]
## **Information**
Minecraft version: 1.12.2
Modloader: Forge

Mod name: Applicable to any mod designed for post-1.13 or features that "target" post-1.13 things added by Mojang - given that Future MC backport the "target" item/block of course. Examples: _Campfire Spawn and Tweaks, Healing Campfire, Fish on the Line, Grindstone Sharper Tools, Kelp Fertilizer, and support for pufferfish and bees in Extract Poision_.

## **Feature description**
Basically, @thedarkcolour 's [Future MC](https://github.com/thedarkcolour/Future-MC) mod aims to backport features (ones that are able to be replicated in 1.12.x engine) from post-1.13 versions to 1.12.2.
Since the aim of the mod is to provide a 1:1 backport of the features, without deviations from what they appear in their vanilla counterparts, the very QoL changes your mods introduce to some of the post-1.13 things (like the ones i mentioned in Mod Name field) could be backported to 1.12 using Future MC stuff as the base.
I know that would be a huge task, but would benefit a lot we that use both mods.

**Comment by ricksouth** [comment]
Thanks for the interest! Unfortunately I can no longer support 1.12.2. My library hasn't been updated and it just takes too much time to justify doing it. Appreciate it though!
