### ISSUE TITLE
Text Shadows

### ISSUE THREAD

**Issue by RaptaG** [ricksouth/serilum-mc-mods#1487]
## Information
- Minecraft version: 1.19.3
- Mod Loader: Fabric

Mod name: GUI Clock

## Feature description
Text Shadows make the text more visible when there's the same color with the font in the background and they add really good aesthetics. Could please consider adding them in GUI Clock (and all of your mods with GUI text maybe)?

**Comment by ricksouth** [comment]
Text shadows with a config options have been added in the latest versions of the GUI mods. Thanks for the suggestion and giving the mods a try!

https://www.curseforge.com/minecraft/mc-mods/gui-clock/files
https://www.curseforge.com/minecraft/mc-mods/gui-compass/files
