### ISSUE TITLE
3 Blocks get deleted when placing beacon

### ISSUE THREAD

**Issue by Sneakery16** [ricksouth/serilum-mc-mods#1489]
## **Information**
Minecraft version: 1.19
Modloader: Fabric
Environment: Singleplayer

Mod version: betterbeaconplacement-fabric 1.19.x-1.6

When placing the blocks like gold or iron 3 blocks are missing every single time. I am sure I brought the right amount.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in the latest version of Better Beacon Placement.

https://www.curseforge.com/minecraft/mc-mods/better-beacon-placement
