### ISSUE TITLE
Omegamute does not work with Botania

### ISSUE THREAD

**Issue by uhloin** [ricksouth/serilum-mc-mods#1490]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 43.2.0
Environment: Singleplayer

First mod name: omegamute
First mod version: 2.8

Second mod name: botania
Second mod version: Botania-1.19.2-436-FORGE.jar

## **Description**
Omegamute can detect but cannot mute Botania sounds. Command "mute" says sound is muted but later "listen" command shows it is not muted and it can be heared. See screenshot.
![2022-12-26_02 42 52](https://user-images.githubusercontent.com/96169906/209483716-74462d2d-fd48-4490-8a69-5eca8ff3015d.png)

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! Apologies it took so long for me to get to. This has been fixed in version 4.0 of Omega Mute, alongside some other feature upgrades.

https://curseforge.com/minecraft/mc-mods/omega-mute/files

**Comment by uhloin** [comment]
Thank you for your work
