### ISSUE TITLE
wither skulls not.. always dropping :(

### ISSUE THREAD

**Issue by jorjaaa** [ricksouth/serilum-mc-mods#1491]
## **Information**
Minecraft version: 1.19.2
Modloader: Fabric
Fabric loader version: 0.14.11
Environment: Singleplayer 

Mod name: Always a Wither Skull
Mod version: 1.9 AND 2.0

## **Description**
just to be clear i don’t have both in the mods folder i just tested both of them. i’m playing with quite a few mods but when i kill wither skeletons it seems that normal drop rates are applying even with the mod installed and loaded. it doesn’t cause my game to crash. would i have to test the mod with every mod i have installed (75) or would i provide a list of the mods and that would be something you figure out? sorry i’m new to github :) thank you!!

**Comment by James103** [comment]
1. Can you please post the full mod list if possible?
2. Try restarting the server. If that doesn't cause Wither Skeletons to always drop wither skulls, try setting `loopsAmountUsedToGetAllEntityDrops` to 200 (default is 100) in the Collective config and restarting the server again.

Assuming the configs in Collective and All Loot Drops are default, the chance that All Loot Drops does not get the fact that Wither Skeletons have the chance to drop a Wither Skeleton Skull is:
$$(1 - (0.025 + 0.01 \times 10))^{100} = 0.875^{100} \approx 1.58\cdot10^{-6}$$
This is low enough that it is unlikely for this to be just a fluke (but it is still possible).

**Comment by jorjaaa** [comment]
i do not have all loot drops installed i have the always a wither skull mod installed because that’s all i care about their so hard to grind

**Comment by James103** [comment]
The mod "Always a Wither Skull" is just a datapack packaged as a mod that includes a loot table for the Wither Skeleton.
Do you have other mods installed that include a loot table for the Wither Skeleton? If so, one of those other loot tables may be overriding the one from Always a Wither Skull. (You may need to try bisecting for the exact mods, if any, causing this issue)

**Comment by jorjaaa** [comment]
so reseting the server fixes it but i don’t want to reset every time i kill a wither skeleton you know? and sorry i don’t have to patience to list 77 mods 😭

**Comment by jorjaaa** [comment]
wait yes i have a mod called mystical nature it’s like mystical agriculture but for fabric and it adds a drop from the wither skeleton, i want to keep that mod how do i fix this?
the mod mystical nature doesn’t have a config file i can see

**Comment by jorjaaa** [comment]
it’s not what i want to do but i could just take out mystical nature :/ i don’t really want to but if i have no choice i just want lots of nether stars

**Comment by ricksouth** [comment]
Alternatively you could also use https://www.curseforge.com/minecraft/mc-mods/configurable-extra-mob-drops to add an extra wither skull drup to the wither skeleton. :)

**Comment by ricksouth** [comment]
I'll take a look at adding compatibility soon, after the holidays

**Comment by jorjaaa** [comment]
thank you so much!!! i hope you had an amazing christmas or whatever you celebrate and have a great new year!

**Comment by ricksouth** [comment]
The mod has been rewritten in version 3.4, which fixes any compatibility issues with other mods. Thank you for opening the issue and giving the mod a try! Apologies it took so long for me to get to.

https://curseforge.com/minecraft/mc-mods/always-a-wither-skull/files
