### ISSUE TITLE
tridentUseDuration doesn't work

### ISSUE THREAD

**Issue by ANormalRaft** [ricksouth/serilum-mc-mods#1494]
## **Information**
Minecraft version: 1.18.2
Modloader: Forge
Forge version: 40.1.80
Environment: Singleplayer

Mod name: Transcending Trident
Mod version: 2.8

## **Description**
Changing the tridentUseDuration in the config doesn't change the charge time of the trident. It remains at 5.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in the latest version of Transcending Trident.

https://www.curseforge.com/minecraft/mc-mods/transcending-trident/files
