### ISSUE TITLE
Crying Portals 1.19.2 not working

### ISSUE THREAD

**Issue by spencer-n1** [ricksouth/serilum-mc-mods#1503]
## **Information**
Minecraft version: 1.19.2
Modloader: Fabric
Fabric loader version: 0.14.11
Environment: Singleplayer

Mod name: Crying Portals
Mod version: 1.8, 1.7

## **Description**
Mod simply is not working. Thought it was just a mod incompatibility, but tested it by itself (_V1.8/1.7_ including its dependencies _Fabric API 0.71.0_ and _Collective 5.22_) and the mod still wasn't working.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 2.3 of Crying Portals.

https://www.curseforge.com/minecraft/mc-mods/crying-portals/files
