### ISSUE TITLE
Server crash with latests version of Collective 1.18.2

### ISSUE THREAD

**Issue by DelviousCrafts** [ricksouth/serilum-mc-mods#1504]
## **Information**
Minecraft version: 1.18.2
Modloader: Forge
Forge version: 40.2.0
Environment: Multiplayer

Mod name: Collective
Mod version: 6.0

## **Description**
Crash on the initial load of the server. Single-player not affected. 

## **Crash report**

[crash-reports_crash-2023-01-04_08.30.01-fml.txt](https://github.com/ricksouth/serilum-mc-mods/files/10346018/crash-reports_crash-2023-01-04_08.30.01-fml.txt)

If available.

**Comment by ricksouth** [comment]
Thanks for opening the issue! I'll take a look right away. For now please use the previous version, this update is mainly for the new format I'm going to use. Appreciate it!

**Comment by lukepage04** [comment]
Will have been due to the update, revert back to the old version and it will be fine.

**Comment by ricksouth** [comment]
Yep! I've uploaded a fix to CurseForge with version 6.1, but seems like the file processing is stuck.

It is available on Modrinth: https://modrinth.com/mod/collective/versions

**Comment by ricksouth** [comment]
Also fixed on CurseForge. Thanks again!

https://www.curseforge.com/minecraft/mc-mods/collective/files
