### ISSUE TITLE
deathbackup not making a backup for geyser players

### ISSUE THREAD

**Issue by Ai-Kiwi** [ricksouth/serilum-mc-mods#1506]
## **Information**
Minecraft version: 1.19.3
Modloader: Fabric
Fabric loader version: latest of a few days ago (not sure how to check)
Environment: Multiplayer

Mod name: deathbackup
Mod version: 2.2

## **Description**
Someone on my server playing on bedrock under geyser ran into a chunk glitch then died of fall damage idk if it was fall damage or what but they have no death backup log file that has been made for them.

**Comment by ricksouth** [comment]
I can't support bedrock, as I don't play it myself. There can be many strange interactions between them. But thanks for giving the mod a try!
