### ISSUE TITLE
GUI Clock / GUI Compass (Fabric) are not automatically hidden in the debug screen.

### ISSUE THREAD

**Issue by MarkusBordihn** [ricksouth/serilum-mc-mods#1507]
## **Information**
Minecraft version: 1.19.3
Modloader: Fabric
Fabric loader version: 0.14.12
Environment: Singleplayer / Multiplayer

Mod name: GUI Clock / GUI Compass
Mod version: latest

## **Description**
The GUI Clock and GUI Compass are not automatically hidden in the debug screen, which makes it hard to read all values depending on their position.

![image](https://user-images.githubusercontent.com/12183293/210678766-546277fc-03ee-4bef-b9b5-382c09a8a437.png)

Would be great to automatically hide them when the debug screen is open.

**Comment by ricksouth** [comment]
This has been fixed in the latest versions of the GUI mods. Thanks for opening the issue and giving the mods a try!

https://www.curseforge.com/minecraft/mc-mods/gui-clock/files
https://www.curseforge.com/minecraft/mc-mods/gui-compass/files
