### ISSUE TITLE
Double Doors not working

### ISSUE THREAD

**Issue by TheSlowmaster** [ricksouth/serilum-mc-mods#1513]
## **Information**
Minecraft version: 1 .19.3
Modloader: Fabric
Fabric loader version: 0.14.12
Environment: Singleplayer
Mod name: Double Doors (Fabric)
Mod version: doubledoors-fabric_1.19.3-3.9.jar

## **Description**
Hey, 

I have the problem that I can open the doors by right-clicking, but if I put a pressure plate in front of it or a button, only one door opens

**Comment by ricksouth** [comment]
This has been fixed in the latest version of Double Doors. Thanks for opening the issue and giving the mod a try!

https://www.curseforge.com/minecraft/mc-mods/double-doors/files
