### ISSUE TITLE
Surface Mushrooms

### ISSUE THREAD

**Issue by sternschnaube** [ricksouth/serilum-mc-mods#1515]
## **Information**
Minecraft version: 1.19.3
Modloader: Fabric
Fabric loader version: 0.14.12
Environment: Server

Mod name: Mod
Mod version: 3.0

## **Description**
Hello, looks like the config can't be created. Using newest release of Collective too >>> v6.9.

## **Crash report**
https://pastebin.com/raw/Lv3z1Uwk

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! Luckily an easy fix, forgot to remove something. I've just uploaded version 3.1, should be available in half an hour or so. Appreciate it!

https://www.curseforge.com/minecraft/mc-mods/surface-mushrooms/

**Comment by venaminecraft** [comment]
Super fast, thanks 😊
