### ISSUE TITLE
carpet dyeing recipes not working as expected

### ISSUE THREAD

**Issue by frizzalot** [ricksouth/serilum-mc-mods#1516]
## **Information**
Minecraft version: 1.19.2
Modloader: Fabric
Fabric loader version: 0.14.10 and 0.14.12
Environment: Singleplayer and Multiplayer

Mod name: Wool Tweaks
Mod version: 2.4 and 3.0

## **Description**
When trying to dye carpets that have already been dyed the recipes added by the mod do not work. Also when putting in any dye color into the center of the crafting table it outputs 8 carpet of that dye color with no carpets in the crafting bench. Upon doing a little checking, it appears in each of the crafting recipes it uses the tag "minecraft:carpets". After looking at the minecraft taglist the correct tag should be "minecraft:wool_carpets".

## **Crash report**
Not a game crashing issue.

**Comment by ricksouth** [comment]
Thanks for opening the issue and doing the research for the solution! Seems like they changed the tag in 1.19, without me noticing. This has been fixed in version 3.1 of Wool Tweaks.

https://www.curseforge.com/minecraft/mc-mods/wool-tweaks
