### ISSUE TITLE
Drinking milk causes the saturation position to change

### ISSUE THREAD

**Issue by ghost** [ricksouth/serilum-mc-mods#1518]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge 
Forge version: xx.xx.xx  OR  Fabric loader version: x.xx.x
Environment: Singleplayer / Multiplayer
Singleplayer
Mod name: nutritiousmilk
Mod version: 1.19.2-2.1

## **Description**
Hey! This happened.
Drinking milk causes the saturation position to change.
https://imgloc.com/i/k7a7P

## **Crash report**
_(Please either drag the file directly here, or use https://gist.github.com/ to prevent the paste from expiring)_

If available.

**Comment by ricksouth** [comment]
This is not related to this mod, as I use the standard function to set the values. Please open the issue on the mod using the custom bar. Thanks for giving the mod a try!
