### ISSUE TITLE
Village Spawn Point doesn't work if MC language other than English is selected

### ISSUE THREAD

**Issue by bons66** [ricksouth/serilum-mc-mods#1519]
## **Information**
Minecraft version: 1.19.2 / 1.19.3
Modloader: Forge / Fabric
Forge version: 44.1.0  OR  Fabric loader version: 0.14.12
Environment: Singleplayer

Mod name: Village Spawn Point
Mod version: Fabric 1.19.2-3.0 / Fabric 1.19.3-3.1 / Fabric+Forge 1.19.3-4.0 / Fabric 1.19.2-4.0

## **Description**
Village Spawn Point doesn't work if MC language other than English is selected
Tested languages: English / Español / Français / Deutsch / اللغة العربية / Русский
Same seed (-2417771238675138994) or different seeds
Tested Minecraft  versions + Mods:
>>>  Minecraft 1.19.2 / Fabric Loader 0.14.12
collective-fabric-1.19.2-5.22.jar
fabric-api-0.70.0+1.19.2.jar
villagespawnpoint-fabric_1.19.2-3.0.jar
>>>  Minecraft 1.19.2 / Fabric Loader 0.14.12
collective-1.19.2-6.9.jar
fabric-api-0.71.0+1.19.2.jar
villagespawnpoint-1.19.2-4.0.jar
>>>  Minecraft 1.19.3 / Fabric Loader 0.14.12
collective-fabric-1.19.3-5.45.jar
fabric-api-0.70.0+1.19.3.jar
villagespawnpoint-fabric_1.19.3-3.1.jar
>>>  Minecraft 1.19.3 / Fabric Loader 0.14.12
collective-1.19.3-6.9.jar
fabric-api-0.71.0+1.19.3.jar
villagespawnpoint-1.19.3-4.0.jar
>>>  Minecraft 1.19.3 / Forge 44.1.0
collective-1.19.3-6.9.jar
villagespawnpoint-1.19.3-4.0.jar
No other mods

## **Crash report**
Game don't crash
[latest.log](https://github.com/ricksouth/serilum-mc-mods/files/10366433/latest.log)

**Comment by ricksouth** [comment]
Thanks for opening the issue! That's interesting. I think this is because commands in-game are also different on different languages. I'll take a look, appreciate it.

**Comment by ricksouth** [comment]
Or are commands not translated? 🤔

**Comment by ricksouth** [comment]
Ah, the output is translated! Which means I'm getting the coordinates incorrectly.

**Comment by bons66** [comment]
Commands not translated

**Comment by bons66** [comment]
Same issues with Biome Spawn Point mod. But I not full test it.

**Comment by ricksouth** [comment]
I'm using English to determine if a village/biome has been found:

`if (rawOutput.contains("nearest") && rawOutput.contains("[")) {`

Which is indeed incorrect, causing it to not find coordinates when on another language. Since the output of the /locate command is localized. Working on a fix right now, thank you for bring it to my attention!

**Comment by bons66** [comment]
Older versions of MC and yours mods work fine. MC 1.18.2 + Fabric loader 0.14.8 + collective-fabric-1.18.x-4.27.jar + villagespawnpoint-fabric_1.18.x-1.8.jar + other 204 mods with Optifne = OK. Thank you.

**Comment by ricksouth** [comment]
Thank you for doing the research! I think I've got a fix almost ready :)

**Comment by ricksouth** [comment]
I've just uploaded the fix, the files should be available in about an hour or so. Thanks for letting me know and giving the mods a try! Appreciate it.

https://www.curseforge.com/minecraft/mc-mods/collective/files

**Comment by ricksouth** [comment]
Only Collective needs to be updated. Village/Biome Spawn Point don't need one :)

**Comment by bons66** [comment]
Thanks for your mods. Work
