### ISSUE TITLE
Cant config Tree Harvester

### ISSUE THREAD

**Issue by MissMagz** [ricksouth/serilum-mc-mods#1520]
## **Information**
Minecraft version: 1.19.3
Modloader: Forge
Forge version: 
Environment: Multiplayer

Mod name: Tree Harvester
Mod version: 1.19

## **Description**
Hey! This happened.
I put tree harvester and a couple other mods that i dont remember the name of haha and the other mods work but i cannot see to get the tree harvester to work, ive tried crouching, using an axe, and when i tried to config the mod to see if i needed to change something, the tree harvester mod doesnt show up in my congi folder but i know for a fact that its in my mods folder. i downloaded it through curseforge and i see it in the mods option section of my game (if its needed ill figure out the names of the other mods) im not sure how else to contact someone for maybe some help to fixing this 

## **Crash report**
_(Please either drag the file directly here, or use https://gist.github.com/ to prevent the paste from expiring)_

If available.

**Comment by ricksouth** [comment]
Can you send me a screenshot of your mods folder, and post the latest.log here?

**Comment by MissMagz** [comment]
yes i can, i am currently at work was just on break and thought i could
send that issue report in ill get you that when i get back to my pc. thank
you for the fast response

**Comment by ricksouth** [comment]
Thanks!

**Comment by MissMagz** [comment]
This is the list of mods i have [image:
d769ef68-4e31-4169-8d72-c84307e7c3b3.png]

**Comment by ricksouth** [comment]
The image hasn't been uploaded unfortunately. And do you have the log file?

**Comment by MissMagz** [comment]
The list of mods is just Xaeros minimap and i did have your full brightness
toggle mod in my server because i didn't realize it was client side only
but i removed that since it was making my server crash, i havent tried the
tree harvester since i removed it could that of been the issue? and this is
the first time i have ever messed with my server files so i dont know how
to get the log file haha sorry

**Comment by ricksouth** [comment]
This should work in version 7.2 of Tree Harvester. Thanks for giving the mod a try!

https://curseforge.com/minecraft/mc-mods/tree-harvester/files
