### ISSUE TITLE
[Crash] "treeharvester" Crash on entering Tardis Refined interior for first time

### ISSUE THREAD

**Issue by AlienXtream** [ricksouth/serilum-mc-mods#1522]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 43.2.3
Environment: Singleplayer / Multiplayer

Mod name: Tree Harvester
Mod version: 1.19.2-7.0 (and older versions)

## **Description**
as title says, upon entering a given tardis for the first time the game crashes. i have a suspicion that its not related to tardis refined specifically but rather runtime dimension creation. since each tardis interior is its own dimension they are generated only as needed (i.e when a player enters a tardis for the first time). if my theory is correct then this would likely occur with other mods that do similar things such as RFTools dimensions. its rather perculiar however as i would not expect tree harvester to care about dimension stuff at all, let alone runtime dimensions. only reason im putting this here is because tree harvester is directly referenced in the crash report:

Description: Exception in server tick loop

java.lang.NullPointerException: Cannot invoke "java.util.concurrent.CopyOnWriteArrayList.size()" because the return value of "java.util.HashMap.get(Object)" is null

hope this is helpful in getting it resolved (assuming ofc it even is a treeharvester issue at all. if its not the obviously this issue is invalid and can be closed)
## **Crash report**
_(Please either drag the file directly here, or use https://gist.github.com/ to prevent the paste from expiring)_
[crash-2023-01-08_19.42.35-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/10368024/crash-2023-01-08_19.42.35-server.txt)

If available.

**Comment by ricksouth** [comment]
Thanks for providing the information. I think this would be because the dimensions aren't running the world load event on creation. But I shouldn't assume that always happens on my part.

I'll take a look, thanks!

**Comment by AlienXtream** [comment]
all good. also, sorry for double posting. github must have done something weird. was not intended

**Comment by ricksouth** [comment]
No problem!

**Comment by ricksouth** [comment]
This has been fixed in the latest version of Tree Harvester. Thanks for the patience and giving the mod a try!

https://www.curseforge.com/minecraft/mc-mods/tree-harvester/files
