### ISSUE TITLE
Giant AI still broken

### ISSUE THREAD

**Issue by SojwetUnion** [ricksouth/serilum-mc-mods#1523]
Minecraft version: 1.19.3

Mod name: Giant Spawn
Mod version: 1.19.3

## **Question**
How come giants still do not move or attack? I tried configuring the AI in mod configs but the giants seem to still have a lack of AI. Is there a solution for this?

**Comment by ricksouth** [comment]
This has (finally) been fixed in Giant Spawn version 4.3. Thanks for opening the issue and giving the mod a try!

https://www.curseforge.com/minecraft/mc-mods/giant-spawn/files
