### ISSUE TITLE
Refill from inventory mod

### ISSUE THREAD

**Issue by penturt** [ricksouth/serilum-mc-mods#1529]
## **Information**
Minecraft version: 1.19+
Modloader: Forge
Forge version: 1.19.2 - 43.2.3
Environment: Singleplayer and Multiplayer

Mod name: Stack Refill
Mod version: 1.19.2-4.0

## **Question**
Is there a way to have stacks/items refilled from other mod inventories such as Pocket Storage, Dank Storage, or Backpack mods?

**Comment by ricksouth** [comment]
Unfortunately not. This is outside of the scope of what I want the project to be. But thanks for the interest!
