### ISSUE TITLE
game is failing to launch 

### ISSUE THREAD

**Issue by cjmee132** [ricksouth/serilum-mc-mods#1530]
## **Information**
1.19.3
forge
Forge version: 44.1.4
Environment: Singleplayer 

Mod name: collective 
Mod version:1.19.3-6.15

## **Description**
after narrowing it down to collective its failing to launch my game. it takes me to launcher. with the error message as shown below  

## **Crash report**
The game crashed whilst initializing game
Error: java.lang.RuntimeException: null

If available.

**Comment by ricksouth** [comment]
Do you have the latest.log and debug.log for me?

**Comment by cjmee132** [comment]
> Do you have the latest.log and debug.log for me?

where can i find these?

**Comment by ricksouth** [comment]
They're in `.minecraft/logs/...`. There are probably a few zipped as well, but just the latest non-zipped file (ends with log) is fine :)

**Comment by cjmee132** [comment]
[2023-01-09-1.log.gz](https://github.com/ricksouth/serilum-mc-mods/files/10376904/2023-01-09-1.log.gz)

**Comment by cjmee132** [comment]
hope this is correct :/

**Comment by ricksouth** [comment]
This crash seems to be caused by campchair, is that possible?

**Comment by cjmee132** [comment]
yes ill try without it now

**Comment by cjmee132** [comment]
just tried it without campchair and still does the same thing

**Comment by ricksouth** [comment]
Can you upload the new log?

**Comment by cjmee132** [comment]
[2023-01-09-1.log.gz](https://github.com/ricksouth/serilum-mc-mods/files/10376937/2023-01-09-1.log.gz)

**Comment by ricksouth** [comment]
`Mod §estarterkit§r requires §6collective§r §o5.25 or above§r
§7Currently, §6collective§r§7 is §o§nnot installed`

You need to install Collective

**Comment by ricksouth** [comment]
Make sure to update all your mods. Are you using the CurseForge launcher?

**Comment by cjmee132** [comment]
i sent wrong file :/ 
[2023-01-09-1.log.gz](https://github.com/ricksouth/serilum-mc-mods/files/10377006/2023-01-09-1.log.gz)

**Comment by cjmee132** [comment]
that should be right sorry

**Comment by ricksouth** [comment]
Send the `latest.log` file, not the .log.gz files

**Comment by cjmee132** [comment]
[latest.log](https://github.com/ricksouth/serilum-mc-mods/files/10377023/latest.log)

**Comment by cjmee132** [comment]
sorry lad im such a melt 😞

**Comment by ricksouth** [comment]
No problem. I don't think Collective is the problem here. But for now:

effortlessbuildings seems to cause issues

**Comment by cjmee132** [comment]
im such a melt. it was effortless building. thank you 😄  hagd!

**Comment by ricksouth** [comment]
No problem! Thanks for giving some of my mods a try!
