### ISSUE TITLE
When using villager names mod and entering the trading box, the villagers profession is repeated twice and overlaps the name.

### ISSUE THREAD

**Issue by JosephTheMan** [ricksouth/serilum-mc-mods#1531]
fabric, villager names both most recent versions

**Comment by ricksouth** [comment]
Thanks for submitting the bug report! This should be fixed in version 5.1 of Villager Names. I've just uploaded it, the files should be available in an hour or so. Appreciate it!

https://www.curseforge.com/minecraft/mc-mods/villager-names/files
