### ISSUE TITLE
Villager names requires a version of collective that does not exist to the public.

### ISSUE THREAD

**Issue by JosephTheMan** [ricksouth/serilum-mc-mods#1532]
## **Information**
Minecraft version: 1.19.3
Modloader: Fabric
Fabric loader version: Latest
Environment: Startup

Mod name: Villager Names and Collective
Mod version: 5.1 & 5.50

## **Description**
Villager 5.1 names requires Collective 6.16 which does not exist as of now.

## **Crash report**
https://gist.github.com/JosephTheMan/22d881faad8886ca2c0fb633a1c97dd9

or

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install collective, version 6.16 or later.
Unmet dependency listing:
	 - Mod 'Villager Names' (villagernames) 5.1 requires version 6.16 or later of collective, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by ricksouth** [comment]
I'm currently in the middle of merging Forge and Fabric on one project page. I'll update the Fabric-specific mod pages soon, but you need the latest file from here: https://www.curseforge.com/minecraft/mc-mods/collective/files
