### ISSUE TITLE
constantly showing entering (area name)

### ISSUE THREAD

**Issue by HsPlaysYT** [ricksouth/serilum-mc-mods#1536]
## **Information**
Minecraft version: 1.19.2
Modloader: Fabric
Fabric loader version: 0.14.12
Environment: Singleplayer / Multiplayer

Mod name: areas
Mod version: 4.0

## **Description**
the "entering (area name) is constantly showing on top of screen even then im leaving and have gone well away from the area. i even restarted the server and game.

**Comment by ricksouth** [comment]
Are you playing on singleplayer or in a server?

**Comment by HsPlaysYT** [comment]
i only play on my server incase a friend wants to join.

**Comment by ricksouth** [comment]
Are you using LAN or a hosting a server via server files?
