### ISSUE TITLE
Move Minecarts doesn't work

### ISSUE THREAD

**Issue by sternschnaube** [ricksouth/serilum-mc-mods#1540]
## **Information**
Minecraft version: 1.19.3
Modloader: Fabric
Fabric loader version: 0.14.12
Environment: Singleplayer / Multiplayer

Mod name: Move Minecarts
Mod version: 3.1

## **Description**
Hello, the mod does not work on my server. After that failure, I installed the mod (and Move Boats) on Client side.
With enabled on both sides, it doesn't work either. I was testing the boats and they worked. 
(Having it on Client side is not requiered as the description says, but I wanted to give it a try.)

Thanks for porting both mods to Fabric, love them.

**Comment by venaminecraft** [comment]
Additional - from what I see currently, there is just one mod which affects Minecarts in some ways.
https://github.com/audaki/minecraft-cart-engine

Maybe it helps.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This should be fixed in version 3.2 of Move Minecarts, but please let me know if it isn't the case as I couldn't reproduce it locally.

https://www.curseforge.com/minecraft/mc-mods/move-minecarts/files
