### ISSUE TITLE
[Bug] Automatic Doors stopped working after updating Collective to the newest version

### ISSUE THREAD

**Issue by Zorklis** [ricksouth/serilum-mc-mods#1541]
## **Information**
Minecraft version: 1.19.3
Modloader: Fabric
Fabric loader version: 0.14.12
Environment: Singleplayer

Mod name: Automatic Doors
Mod version: [[Fabric] 1.19.3-3.0]

## **Description**
Automatic Doors always used to work without a hitch.
I updated Collective (the mod library required for A.D.) and it seems that while the mod loads it has no effect in-game.
I could have been using a very early 1.19.3 version of Collective (Collective [Fabric] 1.19.3-5.23), I can't recall but after updating it to the newer version Collective [Forge & Fabric] 1.19.3-6.21 and now  Collective [Forge & Fabric] 1.19.3-6.22, this mod A.D doesn't work like it should.
Going up near doors Iron/Wood it doesn't open the door. Opening iron doors with a button work and wood doors can be opened normally.

**Comment by Zorklis** [comment]
I tried Automatic Doors [Forge & Fabric] 1.19.3-4.0 and the mod works

**Comment by ricksouth** [comment]
Thanks for confirming! I've been hard at work updating all my mods to the new format. Glad it was fixed during this process. Appreciate you giving the mod a try.
