### ISSUE TITLE
[Collective-Fabric-MC1.19.2] Incompatibility results in crash on singleplayer button click

### ISSUE THREAD

**Issue by winnetrie83** [ricksouth/serilum-mc-mods#1545]
## **Information**
Minecraft version: 1.19.2
Modloader: Fabric
Fabric loader version: 0.14.12
Environment: Singleplayer

First mod name: Collective
First mod version: collective-1.19.2-6.22.jar

Second mod name: Quest Additions
Second mod version: questsadditions-fabric-1.19.2-1.4.1.jar

## **Description**
In my own custom modpack i deducted several mods from the problem and resulting in 10 mods wich was mainly FTB mods and questadditions.
Loading the game untill the main menu is no problem. As soon as i pressed single player the game crashes.
Furter deductions resulted in a clear conflict between Collective and QuestAdditons. Disabling 1 of both makes the game work properly, but both crashes the game.
In the latest log file you can also see the console spitting out the name Collective a few **times.**

## **Crash report**
Latest log: https://pastebin.com/YZWEhY7w

**Comment by ricksouth** [comment]
Thanks for giving the mod a try! Can you see if Collective version 6.26 fixes this issue?

https://www.curseforge.com/minecraft/mc-mods/collective/files

**Comment by winnetrie83** [comment]
Thanks for the fast respons and fix! I had to wait untill curse made the file available, but yes it seems to be fixed now.
