### ISSUE TITLE
Game Crashes when attacked by Killer Rabbit

### ISSUE THREAD

**Issue by kingweirdo** [ricksouth/serilum-mc-mods#1546]
## When the Killer Rabbit attacks me, the game crashes. I get exit code 255
Minecraft version: 1.19.3
Modloader: Forge
Forge version: 44.1.5
Environment: Singleplayer

Mod name: Breakable Killer Rabbit
Mod version: 3.0

## **Description**
I was testing out the Killer Rabbit Mod along with a few other mods made by Serilum. I had the Collective Mod installed. When it would attack me, the game would freeze and crash. There were many other mobs in the area. I have a M2 MacBook Air with 16gb ram.

## **Crash report**
[crash-2023-01-14_15.57.30-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/10418830/crash-2023-01-14_15.57.30-server.txt)

**Comment by ricksouth** [comment]
Thanks for opening the issue! This has been fixed in version 3.2 of Breedable Killer Rabbit. Appreciate it.

https://www.curseforge.com/minecraft/mc-mods/breedable-killer-rabbit/files
