### ISSUE TITLE
Giants have no AI

### ISSUE THREAD

**Issue by kingweirdo** [ricksouth/serilum-mc-mods#1547]
## When I get a Giant to spawn, it has no AI just like vanilla.
Minecraft version: 1.19.3
Modloader: Forge
Forge version: 44.1.5
Environment: Singleplayer 

Mod name: Giant Spawn
Mod version: 4.1

## **Description**
I was testing out the naturally spawning Giants with some other Serilum mods. When the Giant spawned, it had no AI, just like when you use "/summon minecraft:giant" in vanilla. I had the Collective mod installed.

**Comment by ricksouth** [comment]
This has (finally) been fixed in Giant Spawn version 4.3. Thanks for opening the issue and giving the mod a try!

https://www.curseforge.com/minecraft/mc-mods/giant-spawn/files
