### ISSUE TITLE
The Killer Rabbit might not get its default name cleared if the server's language is not English

### ISSUE THREAD

**Issue by James103** [ricksouth/serilum-mc-mods#1548]
## **Information**
Minecraft version: 1.19
Modloader: Forge
Forge version: 44.1.x (assuming 1.19.3)
Environment: Singleplayer (mostly)

Mod name: Breedable Killer Rabbit
Mod version: b3e265b90cc31f69ed26a2e4934e34d83f9b1a40

## **Description**
https://github.com/ricksouth/serilum-mc-mods/blob/b3e265b90cc31f69ed26a2e4934e34d83f9b1a40/sources/Breedable%20Killer%20Rabbit/src/main/java/com/natamus/breedablekillerrabbit/events/EntityEvent.java#L145
When Breedable Killer Rabbit attempts to clear the killer rabbit's default name, there is a check if the name's translated output is exactly `The Killer Bunny`. If that check succeeds, the rabbit's name is reset.

However, this check only works properly if the server language is English. If the server's language is not English, the check may fail because even though the translation string may remain the same, the translated output may be different.

When fixing this, I suggest checking for the translation string instead of the translated output if possible.

**Comment by ricksouth** [comment]
Thanks for opening the issue! This has been fixed in version 3.2 of Breedable Killer Rabbit. Appreciate it.

https://www.curseforge.com/minecraft/mc-mods/breedable-killer-rabbit/files
