### ISSUE TITLE
Passive Endermen for MC 1.19.3 Forge needs Collective Library Version 1.19.3-6.23 but it's missing

### ISSUE THREAD

**Issue by SubSonicEr** [ricksouth/serilum-mc-mods#1549]
Hey there,

thx for the real useful mod. It's really annoying that Endermens can pick up blocks and can destroy hard created structures. So I've decided in seconds to use your mod. Unfortunately this mod needs the "Collective" library Version 1.19.3-6.23. This version is missing on CurseForge. The actual version on CurseForge for "Collective" is 1.19.3-6.22

Big thx for your mods, I'm using a lot of your mods

Greetings

**Comment by ricksouth** [comment]
Thanks for the interest! This was unfortunately due to CurseForge's file processing not working correctly. The correct version is now available!
