### ISSUE TITLE
Collective Issue on Fabric

### ISSUE THREAD

**Issue by sternschnaube** [ricksouth/serilum-mc-mods#1550]
Hello, I was upgrading from v1.19.3-6-22 to v1.19.3-6-26, now I encounter this bug here:

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install collective-fabric, version 5.23 or later.
Unmet dependency listing:
	 - Mod 'Hand Over Your Items (Fabric)' (handoveryouritems-fabric) 2.2 requires version 5.23 or later of collective-fabric, which is missing!
	 - Mod 'Statement Vanilla Compatibility Module' (statement_vanilla_compatibility) 1.0.1+1.14.4-1.15.2 requires any version between 1.14.0-0 (inclusive) and 1.16.0-0 (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.3!
	 - Mod 'ViaFabric for 1.14' (viafabric-mc114) 0.4.9+23-main requires any 1.14.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.3!
	 - Mod 'ViaFabric for 1.15' (viafabric-mc115) 0.4.9+23-main requires any 1.15.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.3!
	 - Mod 'ViaFabric for 1.16' (viafabric-mc116) 0.4.9+23-main requires any 1.16.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.3!
	 - Mod 'ViaFabric for 1.17' (viafabric-mc117) 0.4.9+23-main requires any 1.17.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.3!
	 - Mod 'ViaFabric for 1.18' (viafabric-mc118) 0.4.9+23-main requires any 1.18.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.3!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[minecraft_server.jar:0.11.1]

**Comment by ricksouth** [comment]
Thanks for giving the mods a try!

I've moved the fabric versions to the main project page on Curseforge. All future versions will be uploaded on what used to be the Forge page.

In the case of Hand Over Your Items, you'll have to remove the -fabric file and download the new one at https://www.curseforge.com/minecraft/mc-mods/hand-over-your-items

Apologies for the inconvenience, but this will save me a lot of time in the future, and make my CF profile a lot cleaner by not having separate pages for each loader.

**Comment by venaminecraft** [comment]
Thank you -  I was updating already many mods who was merged with Fabric+Forge, but this one was still missing 😊
