### ISSUE TITLE
Does the instant grow feature work with modded crops?

### ISSUE THREAD

**Issue by Jaec0b** [ricksouth/serilum-mc-mods#1552]
Minecraft version: 1.12.2
Modloader: Forge
Forge version: 14.23.5.2860
Environment: Singleplayer

Mod name: Extended Bone Meal
Mod version: 1.3

Does the instant grow feature work with modded crops?

**Comment by ricksouth** [comment]
It does, but not in 1.12.2. This was added at a later date, after the support for that version was dropped. Thanks for the interest!
