### ISSUE TITLE
Crash on latest version Fabric 1.19.2

### ISSUE THREAD

**Issue by pokesmells** [ricksouth/serilum-mc-mods#1553]
## **Information**
Minecraft version: 1.19.2
Modloader: Fabric
Fabric loader version: 0.14.12
Environment: Singleplayer 
Mod name: Collective
Mod version: collective-1.19.2-6.28.jar

Crashed on start-up!

[crash-2023-01-16_11.50.18-client.txt](https://github.com/ricksouth/serilum-mc-mods/files/10428316/crash-2023-01-16_11.50.18-client.txt)

**Comment by ricksouth** [comment]
Thanks for opening the issue! This has been fixed in version 6.30 of Collective, apologies for the inconvenience.

https://www.curseforge.com/minecraft/mc-mods/collective/files
