### ISSUE TITLE
mod mobs blacklisting for manure mod in config

### ISSUE THREAD

**Issue by william7733** [ricksouth/serilum-mc-mods#1554]
## **Information**
Minecraft version: 1.16.5
Modloader: Forge 

Mod name: Manure

## **Feature description**
please add to the config, a way to blacklist mobs by id. project vibrant journeys mod adds things like flies and snails. other mods add things like moths and pixies, none of these mobs should be dropping manure piles

**Comment by ghost** [comment]
I’d like to also suggest the option to blacklist entire mods, and/or to use a whitelist instead. I’d like to configure things so only herbivores produce usable manure, which is basically how it works in real life. With both Alex’s Mobs and Exotic Birds (among others) installed on our server, this will probably mean blacklisting a *lot* of mobs.

**Comment by william7733** [comment]
> I’d like to also suggest the option to blacklist entire mods, and/or to use a whitelist instead. I’d like to configure things so only herbivores produce usable manure, which is basically how it works in real life. With both Alex’s Mobs and Exotic Birds (among others) installed on our server, this will probably mean blacklisting a _lot_ of mobs.

this is a good point/idea

**Comment by ricksouth** [comment]
Thanks for opening the issue! Version 3.0 of manure adds a blacklist to prevent certain animals from dropping manure. They can be disabled by adding an exclamation mark in front of the entity name. At the moment, disabling full mods isn't supported yet. But hope this helps!

https://www.curseforge.com/minecraft/mc-mods/manure/files

**Comment by william7733** [comment]
unfortunately i am using 1.16.5, so this does not help me. any chance for an update to this version of your mod?
