### ISSUE TITLE
Cannot walk through double doors

### ISSUE THREAD

**Issue by BaccarWozat** [ricksouth/serilum-mc-mods#1557]
## **Information**
Minecraft versions: 1.19.3, 23w03a
Modloader: Fabric
Fabric loader versions: 0.14.11 through 0.14.13
Environment: Singleplayer

Mod name: Double Door
Mod version: 4.0 (dual modloader)

## **Description**
I'm not fat, but I wasn't able to get through the double doors, even when they are open. Also when there is space above them (I'm not a headbanger either). It just sort of halts me at the doorway. Same effect if I try to go through from the other side.

Workaround, of course, is to remove either a door or a mod.

## **Crash report**
No crash, thankfully.

**Comment by ricksouth** [comment]
Thanks for opening the issue! This has been fixed in version 4.1 of Double Doors. Appreciate it :)

https://www.curseforge.com/minecraft/mc-mods/double-doors/files
