### ISSUE TITLE
William Wythers' Overhauled Overworld trees incompatibility

### ISSUE THREAD

**Issue by KostromDan** [ricksouth/serilum-mc-mods#1558]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 43.2.3
Environment: Singleplayer / Multiplayer

First mod name: Tree Harvester
First mod version: treeharvester-1.19.2-7.0.jar

Second mod name: William Wythers' Overhauled Overworld
Second mod version: WWOO-FORGE-3.1.9+1.19.x.jar

## **Description**
Hey! Some trees of this mod use not only logs and leaves, but also sometimes a wood block and with mangrove tree also roots as a part of the tree. This causes the mod to brakes only half of the tree.
A screenshot that demonstrates what can be part of a single tree:
![image](https://user-images.githubusercontent.com/90044015/213729239-ae3ca652-57ac-4619-b320-dff4206f274b.png)

https://user-images.githubusercontent.com/90044015/213734751-cf3f6ce1-50e6-4817-b15b-3a6420f7bc56.mp4

https://user-images.githubusercontent.com/90044015/213734768-23604186-ae26-44a7-bbb9-be39d9bc7e66.mp4

**Comment by KostromDan** [comment]
https://user-images.githubusercontent.com/90044015/213731820-d14e66c1-bfe0-4ea3-9e66-c6fbaccf8cb5.mp4


https://user-images.githubusercontent.com/90044015/213731835-5d17704d-5b07-4c14-aa10-f28d693ec530.mp4

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! Compatibility has been added in version 7.2 of Tree Harvester.

https://curseforge.com/minecraft/mc-mods/tree-harvester/files
