### ISSUE TITLE
no config

### ISSUE THREAD

**Issue by Denoxyy** [ricksouth/serilum-mc-mods#1559]
## **Information**
Minecraft version: 1.16.1
Modloader: Fabric
Fabric loader version: 0.14.13
Environment: Singleplayer

Mod name: Set World Spawn Point
Mod version: 1.3

Hey! there is no file related to edit the config of the mod in the config folder. Even after i start up the game.

**Comment by ricksouth** [comment]
1.16.1 is unfortunately no longer supported. Please update to the 1.18 or higher. Apologies for the inconvenience.
