### ISSUE TITLE
[Bug] NHAC Crash with runtime dimension (Tardis Refined. possibly RFTools dims)

### ISSUE THREAD

**Issue by AlienXtream** [ricksouth/serilum-mc-mods#1560]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 43.2.3
Environment: Singleplayer

Mod name: No Hostiles Around Campfire
Mod version 5.0

## **Description**
another one. presumably the same issue as tree chopper i reported a little while ago. entering the Tardis for the first time crashes the "server" (boots to server list even in SP). the thing to note here that is unique to Tardis Refined is the "proto tardis" interior has a campfire so that may be a factor. 

## **Crash report**
[crash-2023-01-21_12.37.16-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/10471301/crash-2023-01-21_12.37.16-server.txt)

If available.

**Comment by AlienXtream** [comment]
https://github.com/ricksouth/serilum-mc-mods/issues/1522 referenced tree "chopper" issue.

**Comment by ricksouth** [comment]
This has been fixed in the latest version of No Hostiles Around Campfire. Thanks for the patience and giving the mod a try!

https://www.curseforge.com/minecraft/mc-mods/no-hostiles-around-campfire/files
