### ISSUE TITLE
Special character support lost

### ISSUE THREAD

**Issue by Frzncore** [ricksouth/serilum-mc-mods#1561]
Special character support has been changed in GUI followers. I had working special characters but they have broken since a recent update? Could you revert this please?

**Comment by ricksouth** [comment]
What special characters do you mean? Which version? Fabric/Forge?

**Comment by Frzncore** [comment]
Forge, Latest version 3.0
It was working in 2.1
Characters I was using:     » « ▼

**Comment by ricksouth** [comment]
I believe this was caused by the automatic conversion of the .toml config file to .json5. I've fixed that in the latest release of Collective, but if you edit the config (again) to use those characters, it should work. Thanks for giving the mod a try!
