### ISSUE TITLE
Mod resolution encountered an Incompatible Mod Set!

### ISSUE THREAD

**Issue by ProducerMZ** [ricksouth/serilum-mc-mods#1562]
## **Information**
Minecraft version: 1.19.2
Modloader: Fabric
Fabric loader version: 0.14.12
Environment: Singleplayer

Mod name: Collective
Mod version: every update past 1.19.2-6.22

## **Description**
Hi! I love your unique mods, but unfortunately, for every update past 1.19.2-6.22 I get the following error is a small box at launch:

"
Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
Install collective-fabric, version 5.3 or later.
Unmet dependency listing:
Mod 'Areas (Fabric)' (areas-fabric) 3.2 requires version 5.3 or later of collective-fabric, which is missing!
<html>Mod 'GUI Followers (Fabric)' (guifollowers-fabric) 2.4 requires version 5.3 or later of collective-fabric, which is<br>missing!</html>
<html>Mod 'Healing Campfire (Fabric)' (healingcampfire-fabric) 4.0 requires version 5.3 or later of collective-fabric, which<br>is missing!</html>
Mod 'Husk Spawn (Fabric)' (huskspawn-fabric) 2.0 requires version 5.3 or later of collective-fabric, which is missing!
<html>Mod 'Random Village Names (Fabric)' (randomvillagenames-fabric) 2.1 requires version 5.3 or later of collective-fabric,<br>which is missing!</html>
<html>Mod 'Villager Death Messages (Fabric)' (villagerdeathmessages-fabric) 2.8 requires version 5.3 or later of<br>collective-fabric, which is missing!</html> 
"

... as if it isn't compatible. If I delete the update and reinsert the 1.19.2-6.22 file it loads fine. I would be incredibly surprised if this is the first you're hearing of this.,
Please let me know if I can provide any assistance or further information. I will respond as quickly as I am able.

**Comment by ricksouth** [comment]
Thanks for giving the mods a try!

I've moved the fabric versions to the main project page on Curseforge. All future versions will be uploaded on what used to be the Forge page.

So for the following mods:

Mod 'GUI Followers (Fabric)
Mod 'Healing Campfire (Fabric)
Mod 'Husk Spawn (Fabric)
Mod 'Random Village Names (Fabric)
Mod 'Villager Death Messages (Fabric)

You'll need to download them from the main project page. So in the case of GUI Followers you need the URL:
https://www.curseforge.com/minecraft/mc-mods/gui-followers, without the -fabric.

Apologies for the inconvenience, but this will save me a lot of time in the future, and make my CF profile a lot cleaner by not having separate pages for each loader.

**Comment by ProducerMZ** [comment]
Man. It took me far to long to realize what you meant. 
In order to use the newer "Forge/Fabric" versions of Collective, I will also have to update the mods I use to the "Forge/Fabric" versions of the mods as well  ! ....It all makes sense now, thank you! 
I will endeavor to re-download the appropriate versions..
Thank you for clearing that up, and I wish you the best in your work. . Take care. :)

**Comment by ProducerMZ** [comment]
Took me 10 minutes. Updated to latest Collective, all my old Serilum mods ( plus a couple new ones) and it worked perfectly.
Thank you again for your efforts, and for making my Minecraft 'down-time' that much more enjoyable. All the best to you! :)

**Comment by ricksouth** [comment]
Glad you got it working! Thanks for using them and the kind words. Appreciate it!
