### ISSUE TITLE
Passive Endermen doesn't work

### ISSUE THREAD

**Issue by jh05013** [ricksouth/serilum-mc-mods#1563]
## **Information**
Minecraft version: 1.19.3
Modloader: Forge
Forge version: 44.1.0
Environment: Singleplayer

Mod name: Passive Endermen
Mod version: 4.1

## **Description**
Endermen still teleport randomly and get angry when being looked at. Version 4.0 doesn't work either. Collective version is 1.19.3-6.38.

I haven't tested picking up blocks since I set mobGriefing to false.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has (finally) been fixed in version 4.2 of Passive Endermen.

https://www.curseforge.com/minecraft/mc-mods/passive-endermen/files
