### ISSUE TITLE
Crying Portals not working on Forge 1.19.2

### ISSUE THREAD

**Issue by tinytransfem** [ricksouth/serilum-mc-mods#1565]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 43.2.0
Environment: Singleplayer

Mod name: Crying Portals
Mod version: 2.0

## **Description**
Mod loads (is listed in the Mods screen) but creating portals using Crying Obsidian doesn't work.
![image](https://user-images.githubusercontent.com/74989701/213947483-107c7970-eefe-4e73-a8c8-1103dc65ef3b.png)

## **Crash report**
no crash report, only debug log:
[debug.log](https://github.com/ricksouth/serilum-mc-mods/files/10475825/debug.log)

**Comment by nuac87** [comment]
Same with 1.18.2 2.0

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 2.3 of Crying Portals.

https://www.curseforge.com/minecraft/mc-mods/crying-portals/files
