### ISSUE TITLE
Doesnt work.. at all. 

### ISSUE THREAD

**Issue by alexzzing** [ricksouth/serilum-mc-mods#1567]
This mod doesnt work at all. Downloaded the 1.19.3 version, and the required collective mod.
The auto recast doesnt work at all.

**Comment by ricksouth** [comment]
What did you expect the mod to do? It keeps the fishing bobber in the water, it doesn't automatically fish for you

**Comment by ricksouth** [comment]
If it's not working as shown in the description, let me know. It has to be installed on the server-side as well.
