### ISSUE TITLE
hello i set my followers to not be able to take damage for the max of 86400 secs and thats 24 hours so i tried to go into combat to test it and they still take damage sadly is this a bug?

### ISSUE THREAD

**Issue by Nathanos2256** [ricksouth/serilum-mc-mods#1569]
## **Information**
Minecraft version: xx.xx.xx
Modloader: Forge / Fabric
Forge version: xx.xx.xx  OR  Fabric loader version: x.xx.x
Environment: Singleplayer / Multiplayer

Mod name: Mod
Mod version: x.x

## **Description**
Hey! This happened.

## **Crash report**
_(Please either drag the file directly here, or use https://gist.github.com/ to prevent the paste from expiring)_

If available.

**Comment by Nathanos2256** [comment]
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 1.19.2-43.2.2
Environment: Singleplayer as a dedicated server 

Mod name: followers teleport too
Mod version: followersteleporttoo_1.19.2-1.1

**Comment by ricksouth** [comment]
This is not the intended feature. It's used so that followers don't take damage from the teleport. I think a different mod which disables damage would be better in this case. Thanks for the interest though!
