### ISSUE TITLE
Tree Harvester: Cutting azalea tree issue

### ISSUE THREAD

**Issue by DaijobuDes** [ricksouth/serilum-mc-mods#1570]
## **Tree Harvester: Cutting azalea issue**
Minecraft version: 1.19.3
Modloader: Forge
Forge version: 44.1.5
Environment: Singleplayer

Mod name: Tree Harvester
Mod version: 7.0

## **Description**
If `instantBreakLeavesAround` is set to false, not all azalea leaves are broken. But if set to true, it breaks all the leaves whether be it a regular azalea leaf or a flowering azalea leaf.

https://user-images.githubusercontent.com/38452446/214291178-4a8ba1ac-7b38-486d-af7c-24b99212451f.mp4

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 7.2 of Tree Harvester.

https://curseforge.com/minecraft/mc-mods/tree-harvester/files
