### ISSUE TITLE
[nether portal spread] Adding blocks from other mods to the spreadsettings.txt does not work.

### ISSUE THREAD

**Issue by Fokke456** [ricksouth/serilum-mc-mods#1571]
Minecraft version: 1.18.2
Modloader: Forge 
Forge version: 40.2.0
Environment: Singleplayer

Mod name: nether portal spread
Mod version: 7.1

**Description**
Hello! While I was working on making a modpack with this and create, I wanted to add some blocks from create to the spreadsettings.txt. However, this does not seem to work.  For me, the following is a minimal working example: `stone; [create:scoria>1],` In the log I get the output `[Nether Portal Spread] Unable to find to-block 'create:scoria' in the Forge block registry. Ignoring it`. I have tried blocks from other mods, and I get a similar output.

**Comment by ricksouth** [comment]
This has been fixed in version 7.4 of Nether Portal Spreads. Thanks for opening the issue and giving the mod a try!

https://www.curseforge.com/minecraft/mc-mods/nether-portal-spread/files
