### ISSUE TITLE
Doubledoors: doors and trapdoors behaves weirdly - don't allow passing through

### ISSUE THREAD

**Issue by lospejos** [ricksouth/serilum-mc-mods#1575]
## **Information**
Minecraft version: 1.19.3
Modloader: Fabric
Fabric loader version: 0.14.13
Environment: Singleplayer

Mod name: doubledoors
Mod version: 1.19.3-4.0

## **Description**
Doors and trapdoors when placed 2+ items behaves weirdly. They do not allow passing through them (doors and trapdoors). It's like a collision error or something like this. When placed one door / trapdoor, it allows passing through like a charm.

## **Crash report**
No crash occur.

Please see video with this weird behavior: https://www27.zippyshare.com/v/PAnUuatz/file.html

Mods installed:

`collective-1.19.3-6.43`
`doubledoors-1.19.3-4.0`
`fabric-api-0.73.0+1.19.3`
`modmenu-5.0.2`

**Comment by ricksouth** [comment]
This should be fixed in version 4.1! Can you update the mod?

https://www.curseforge.com/minecraft/mc-mods/double-doors/files

**Comment by lospejos** [comment]
After updating mod to version 4.1 everything went fine. I'm closing this issue. Thanks!

**Comment by ricksouth** [comment]
Glad it works. Thanks for giving the mod a try!
