### ISSUE TITLE
Issue with Collective and other serilum mods being detected

### ISSUE THREAD

**Issue by morkmorkmorkmork** [ricksouth/serilum-mc-mods#1577]
## **Information**
Minecraft version: 1.19.3
Modloader: Fabric
Fabric loader version: 0.14.13
Environment: Singleplayer / Multiplayer

Mod name: collective
Mod version: 6.43

## **Description**
Whenever I try to load fabric with serilum mods none of them work. I installed a mod manager and it shows that collective isn't being detected. The game launches fine and I can open single-player and join multiplayer worlds but none of the serilum mods work. I've tested with other non serilum mods which are all detected, I tested using older versions of collective 1.19.3 but they aren't being detected either. I've also tested fabric 1.19.2 with the 1.19.2 version of collective and it is still not being detected.

**Comment by ricksouth** [comment]
Thanks for opening the issue! Which launcher are you using? And do you have a screenshot of your mods folder and the mod menu in-game with libraries enabled?

**Comment by ricksouth** [comment]
Where did you download the mods from?

**Comment by morkmorkmorkmork** [comment]
using just the Minecraft launcher with the fabric loader installation

Mods Folder
![cd607c0adab6014cd094d55fa4946b78](https://user-images.githubusercontent.com/123606524/214742809-680b0348-dad2-48b0-bbab-ac8f893b74fc.png)

Mod Menu
![696164d9142a57491f622565c195e1d2](https://user-images.githubusercontent.com/123606524/214743126-97010051-23f2-4516-9c90-4beecfba53f9.png)
![b3ee2ad788184a0a30df70e4a0e1a181](https://user-images.githubusercontent.com/123606524/214743289-3cc1f0ce-87fa-40cd-a91d-1b4ba8287bb6.png)

**Comment by morkmorkmorkmork** [comment]
downloaded the mods from curse forge and also modrinth

**Comment by morkmorkmorkmork** [comment]
Didn't realize I had to enable seeing libraries, collective is showing up but other mods are not. Apologies if I'm being dumb I'm new to modding and tried figuring it out myself but couldn't.

![283f8cee1623ee86f9efef33e388aa4d](https://user-images.githubusercontent.com/123606524/214744445-e2249801-2827-4fbd-bdb1-91ccde309bcb.png)
![7fedec1b5510021069e7171b4a2904a9](https://user-images.githubusercontent.com/123606524/214744455-7402e3ad-4256-479d-9565-8da53e8266c8.png)
![850dc2a5ff885aaf2031286999c42974](https://user-images.githubusercontent.com/123606524/214744460-555972c1-ecae-4fbb-9c5e-ad6f6ba8b90f.png)

**Comment by ricksouth** [comment]
Thanks! Looks like it's only GUI Compass right? Can you post the latest/debug log files here? They're in .minecraft/logs

**Comment by morkmorkmorkmork** [comment]
[debug.log](https://github.com/ricksouth/serilum-mc-mods/files/10513983/debug.log)

**Comment by ricksouth** [comment]
I unfortunately can't find the issue on my end. It might work to update Fabric and the Fabric loader to the latest version, and reinstalling the mods. Hope you've figured it out by now, sorry I can't help. Thanks for giving the mods a try!
