### ISSUE TITLE
[1.19.2]  Areas.  Multiplayer game. Zone is created with an empty description.

### ISSUE THREAD

**Issue by hoxqot** [ricksouth/serilum-mc-mods#1579]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 43.2.0 
Environment: Multiplayer

Mod name: Areas
Mod version: 4.0
Submod: Collective 6.43

## **Description**
In a multiplayer game, when creating a sign, a zone is created with an empty description. For example, I create such a sign ""[Area] 10 test". I check with the "/areas" command, the result is "at x=.., y =..., z=... (... block)" , i.e. before the word "at" there is no description of the zone. And, accordingly, it is not displayed in the HUD information about the arrival and departure of the zone.

In single-user mode, everything is correct, the result is "test at x=.., y =..., z=... (... block)". Area have decription. Correctly displayed information about arrive or leave.

## **Crash report**
none, absent

**Comment by WildFyr16** [comment]
Same issue 1.19.2 Fabric Server works fine in single player, it also says "entering <area name>" and NEVER goes away, even after removing the sign or relogging

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 5.0 of Areas, alongside other bug fixes and QoL features. Apologies it took so long for me to get to.

https://www.curseforge.com/minecraft/mc-mods/areas/files
