### ISSUE TITLE
Compatibility with Immersive Portals

### ISSUE THREAD

**Issue by vico93** [ricksouth/serilum-mc-mods#1581]
## **Information**
Minecraft version: 1.19.3
Modloader: Fabric
Mod name: **Smaller Nether Portals**

## **Question**
Does Smaller Nether Portals works with [Immersive Portals](https://modrinth.com/mod/immersiveportals) ([GitHub](https://github.com/iPortalTeam/ImmersivePortalsMod))? I'm asking preemptively because [mod compatibility](https://qouteall.fun/immptl/wiki/#mod-compatibility) in IP is complicated due to how it works, and i dont know if any work on SNP's side need to be done to implement such compatibility, if still not exist.

**Comment by ricksouth** [comment]
Looks like Immersive Portals can have smaller portals themselves. Thanks for the interest!
