### ISSUE TITLE
Spawnpoint being moved on top of structure instead of inside it

### ISSUE THREAD

**Issue by T0mt4ru** [ricksouth/serilum-mc-mods#1582]
Minecraft version: 1.18.2
Modloader: Forge
Forge version: 40.2.0

Mod name: Starter Structure
Mod version: 2.0

Hello, I'm trying to make an underground bunker as my starter structure using WordEdit .schem files. The problem I'm having, is that I'm spawning on top of the bunker instead of inside it...

I did use the //copy and //schematic save commands from within the bunker, and I do spawn inside of it when I don't use the Yoffset. but then then bunker is no longer underground...

Is this a design flaw on my part?

**Comment by ricksouth** [comment]
I've added (too many) new config options which will make the underground bunker idea work! Doing some testing right now, but with the following settings you'll spawn inside :) Will publish soon!

![2023-03-05_15 06 15](https://user-images.githubusercontent.com/38502394/222965382-40951a89-075f-4b6a-8ef3-6061be755cf3.png)
![2023-03-05_15 03 56](https://user-images.githubusercontent.com/38502394/222965256-53332f82-d3f6-4051-b955-283268007cab.png)
![2023-03-05_15 03 58](https://user-images.githubusercontent.com/38502394/222965258-ba78f2a5-e9ca-4e77-98dc-703158972f8d.png)
![2023-03-05_15 04 01](https://user-images.githubusercontent.com/38502394/222965259-92784541-21ff-4ad2-96f0-f6bec3b07a0e.png)
![2023-03-05_15 04 03](https://user-images.githubusercontent.com/38502394/222965260-2db4f3c5-4b61-4fc1-949f-30d3e1c75f6a.png)

**Comment by T0mt4ru** [comment]
This is looking very promising!

**Comment by ricksouth** [comment]
This has been fixed in version 3.1 of Starter Structure, with various new config options. With exact coordinates and offsets for both the player and the structure, it should be much more configurable. Thanks for opening the issue and giving the mod a try!

https://www.curseforge.com/minecraft/mc-mods/starter-structure/files
