### ISSUE TITLE
Configurable Mob Potion Effect Questions

### ISSUE THREAD

**Issue by akirawav3** [ricksouth/serilum-mc-mods#1583]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.19.2
Modloader: Fabric
Environment : Multiplayer

Mod name: Configurable Mob Potion Effects

Not so much of an issue than a question, I'm trying to up boss health, but everytime I give them a Health Boost it still spawns them at normal health, how do I fix it so they spawn with full health?

**Comment by ricksouth** [comment]
As the mod gives status effects, I don't think it'll work to increase a mob's health. There should be other mods which can do this, as of now I think it's outside the scope of this one. Thanks for the interest though!
