### ISSUE TITLE
Can't set small negative coordinates for overworld

### ISSUE THREAD

**Issue by blahber** [ricksouth/serilum-mc-mods#1585]
Trying to do a simple:
500 x
-500 x
500 z 
-500 z

Both negative values are highlighted red and I cannot click "done" in config to get the mod to implement it. Playing on 1.19.3 Forge 44.1.8. No other mods except Collective (1.19.3-6.43) and World Border (1.19.3-4.0).

**Comment by ricksouth** [comment]
Thanks for opening the issue! This has been fixed in version 4.1 of World Border, along with the Collective update.

https://curseforge.com/minecraft/mc-mods/world-border/files
