### ISSUE TITLE
Zombie Horse Spawn mod horse drifting

### ISSUE THREAD

**Issue by ghost** [ricksouth/serilum-mc-mods#1588]
## **Information**
Minecraft version: 1.16.5
Modloader: Forge 
Forge version: 36.2.34
Environment: Singleplayer / Multiplayer

Mod name: Zombie Horse Spawn
Mod version: 3.0

## **Description**
![grafik](https://user-images.githubusercontent.com/45370592/215732008-a2ac73d1-325a-4171-8785-28530f9a4fa7.png)

They drifting sideways

**Comment by ricksouth** [comment]
This is vanilla behaviour unfortunately. The mod places the zombie on top of the horse, it does not influence its movements. Thanks for giving the mod a try!

**Comment by ghost** [comment]
Do you have discord?

**Comment by EightBitBBQ** [comment]
There is a discord:
https://discord.com/invite/vFren9YzzN

**Comment by ghost** [comment]
Why I can't accept invite?

**Comment by EightBitBBQ** [comment]
Do you get an error?

**Comment by KazIsKool** [comment]
Why was this mod even made when they didn't bother to fix the bug that had them removed from vanilla in the first place?
