### ISSUE TITLE
Can the "Areas" mod be ported to Fabric version 1.19?

### ISSUE THREAD

**Issue by AStrong34** [ricksouth/serilum-mc-mods#1589]
Minecraft version: 1.19
Modloader:  Fabric
Environment: Singleplayer / Multiplayer

I love this idea for the mod itself but have found no mod like it for the version of Fabric Minecraft I am using for me and my friends server. And I would love if this mod could be ported to work for Fabric version 1.19. Currently the only version it works for is Fabric versions 1.19.3 and 1.19.2. You have a Forge version for 1.19 but no Fabric port of it. 

It would be awesome if you would be willing to do this! Thank you!

**Comment by EightBitBBQ** [comment]
https://www.curseforge.com/minecraft/mc-mods/areas

Forge & Fabric are combined in one jar file now. If you download it here. It should work on fabric as long as you have the Collective mod installed

**Comment by AStrong34** [comment]
> https://www.curseforge.com/minecraft/mc-mods/areas
> 
> Forge & Fabric are combined in one jar file now. If you download it here. It should work on fabric as long as you have the Collective mod installed

it works on Fabric but the only files I see for Fabric is version 1.18.2, 1.19.2, and 1.19.3. Does not show a file for Fabric 1.19. I see the combined files but again, they are for versions higher than 1.19. The only one I see for Minecraft 1.19 is for Forge, so unless that Forge file is actually both Fabric and Forge even though the file name doesnt have it combined, then this mod skipped over version 1.19 and just went straight to 1.19.2 and higher

Just downloaded the one called, "<html>
<body>


areas_1.19.0-3.0.jar | 28.45 KB | Jul 17, 2022 | 1.19+1 | 2,051 |  
-- | -- | -- | -- | -- | --


<br class="Apple-interchange-newline">
</body>
</html>[areas_1.19.0-3.0.jar](https://www.curseforge.com/minecraft/mc-mods/areas/files/3879742)	28.45 KB	Jul 17, 2022	
1.19
+1
2,051" as this is the only file I see for the exact 1.19 version and it is labeled as Forge and not Fabric and it does not work as it is a Forge mod for that specific version

**Comment by EightBitBBQ** [comment]
Im not sure. But i dont think there is a 1.19 version of this mod:
https://modrinth.com/mod/areas/versions

What happens if you use an older version?
Or why not go to 1.19.2?

**Comment by AStrong34** [comment]
> Im not sure. But i dont think there is a 1.19 version of this mod: https://modrinth.com/mod/areas/versions
> 
> What happens if you use an older version? Or why not go to 1.19.2?

if only it was that simple as over half our mods for our server are not updated for 1.19.2/been abandon and 1.19 are the last version they work for. Also there's a 1.19 Forge version on the cursedforge website that i mentioned in my previous comment

**Comment by EightBitBBQ** [comment]
Sad to hear. 
Cant help you any further then this (wish i could)

Maybe the author has still some idea for you :-)

**Comment by ricksouth** [comment]
Thanks for the interest! Unfortunately the Fabric port of Areas was done when 1.19.2 was released. So there never has been a 1.19 version. I'm not planning on backporting it, as my library and development environment doesn't have 1.19.
