### ISSUE TITLE
Dont Work on 1.19.2

### ISSUE THREAD

**Issue by mcsnack** [ricksouth/serilum-mc-mods#1590]
## **Information**
Minecraft version: 1.19.2
Modloader: Fabric 
Forge version: xx.xx.xx  OR  Fabric loader version: 0.14.13
Environment: Multiplayer

Mod name: Better Beacon Placement
Mod version: 1.19.2-3.0

## **Description**
Hey! This happened.
The mod Installs very quickly but has no function on our 1.19.2 Paper Multiplayer Server. Is there a fix for this? 

With kind regards

**Comment by netcore10** [comment]
-- The mod Installs very quickly but has no function on our 1.19.2 Paper Multiplayer Server. Is there a fix for this?


This mod isn't for paper though?

**Comment by ricksouth** [comment]
The mod is for Fabric/Forge or Quilt. Paper is indeed not supported. Thanks for the interest.
