### ISSUE TITLE
When held shield in offhand,it negate the attack damage from player.

### ISSUE THREAD

**Issue by Greygreygod** [ricksouth/serilum-mc-mods#1591]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 43.2.0
Environment: Singleplayer / Multiplayer

Mod name: Passive Shield
Mod version: 3.0

## **Description**
When held shield in offhand,it negate the attack damage from player.
It's that a bug or just a setting?If i set the percentage to 50%,it will negate my atttack damage 50%.

**Comment by ricksouth** [comment]
Thanks for opening the issue! This has been fixed in version 3.2 of Passive Shield. Appreciate it.

https://www.curseforge.com/minecraft/mc-mods/passive-shield/files
