### ISSUE TITLE
I want advertise your mod "Starter Kit" to MCBBS.

### ISSUE THREAD

**Issue by imnotyangjiu** [ricksouth/serilum-mc-mods#1592]
The Starter Kit mod is nice and it helps me a lot!

I am a Chinese player and I like your mod "Starter Kit".

Could you please allow me to translate your mod and advertise it to MCBBS?

MCBBS is the largest MC forum in China.

You know not all of them are good at English, they can't read your post (Even with Google translator) they need a Chinese translator.

I'll NEVER claim it as mine and mark you as the author .

Looking forward that you can make more and more good mods!

**Comment by ricksouth** [comment]
This is OK if the downloads remains on CurseForge, with a direct link to the project page. Thanks for the interest.
