### ISSUE TITLE
Double Doors: Add config to disable specific openings

### ISSUE THREAD

**Issue by NekoLeila** [ricksouth/serilum-mc-mods#1593]
## **Information**
Minecraft version: 1.19.2 
Modloader: Forge 
Forge version: 43.1.55 
Environment: Singleplayer 

Mod name: Double Doors
Mod version: 1.19.2-4.1

## **Description**
I know this probably isn't your issue but idk who else to ask. 

I tried adding this mod to ATM8 and the double doors keep flip flopping (one is always closed and one is always open). 

This only happens when clicking doors, doors with pressure plates and gates and trapdoors all work fine. 

I also tried it with just Double Doors installed with same version and loader and it works fine, but I can't think of what might be wrong or what other mod might be causing the issue

**Comment by NekoLeila** [comment]
After making this, I noticed that apparently there's another mod in the pack that just does double doors, but it doesn't work on fences which I really like about your mod, so it's definitely just a conflict with that, but I just looked through the entire mod list and I can't think of which one it might be short of going through and disabling them one by one, so if you know, that'd be awesome

**Comment by NekoLeila** [comment]
Apparently Quark has an option for it, but it's not on in this pack

**Comment by ricksouth** [comment]
Double Doors has the following config options to disable specific things from opening:

enableDoors (default = true): When enables, the mod works with double doors.
enableFenceGates (default = true): When enables, the mod works with double fence gates.
enableTrapdoors (default = true): When enables, the mod works with double trapdoors.

Hope that's what you need :)

https://www.curseforge.com/minecraft/mc-mods/double-doors

**Comment by NekoLeila** [comment]
Omg, I didn't even think to look, tysm XD 

Sent from Yahoo Mail on Android 
 
  On Mon, Mar 6, 2023 at 1:02 PM, Rick ***@***.***> wrote:   


Double Doors has the following config options to disable specific things from opening:

enableDoors (default = true): When enables, the mod works with double doors.
enableFenceGates (default = true): When enables, the mod works with double fence gates.
enableTrapdoors (default = true): When enables, the mod works with double trapdoors.

Hope that's what you need :)

https://www.curseforge.com/minecraft/mc-mods/double-doors
