### ISSUE TITLE
Mojang API

### ISSUE THREAD

**Issue by calinado** [ricksouth/serilum-mc-mods#1594]
## **Information**
Minecraft version: 1.19.3
Modloader: Fabric
Fabric loader version: fabric-api 0.73.0+1.19.3
Environment: Multiplayer

Mod name: justplayerheads
Mod version: 3.0

## **Description**
Hey! the mod worked initially but then i soon realized with LuckPerms anyone without OP could not have a chance of receiving a head. I have searched for hours on end through your documentation trying to find permission nodes and I could not find anything. There is no discord, no contact no anything for support other than here which is extremely inconvenient. I guessed at some permission nodes and none of them worked, and now for some reason OP players cant even receive heads. 

when attempting the manual command to receive a head receiving an error saying "Unable to generate the player head. Either the player 'playername' does not exist or the Mojang API server has had too many requests in a short period of time."

I have cache set to true (like it is by default) and am running the command no more than once every 5-10 minutes for testing so I do not believe the Mojang API is overloaded. I saw some RU post talking about something with Mojang API and the only solution was the cache and that does not help me here. I also tried to reinstall the mod and that did not work either.

Here is a full list of mods installed on the multiplayer server:

02.02 01:20:38 [Server] [INFO] - antixray 1.3.0
02.02 01:20:38 [Server] [INFO] - clumps 9.0.0+16
02.02 01:20:38 [Server] [INFO] - collective 6.43
02.02 01:20:38 [Server] [INFO] - com_electronwill_night-config_core 3.6.5 via forgeconfigapiport
02.02 01:20:38 [Server] [INFO] - com_electronwill_night-config_toml 3.6.5 via forgeconfigapiport
02.02 01:20:38 [Server] [INFO] - com_github_llamalad7_mixinextras 0.1.1 via vanilla-permissions
02.02 01:20:38 [Server] [INFO] - com_moandjiezana_toml_toml4j 0.7.2 via antixray
02.02 01:20:38 [Server] [INFO] - conditional-mixin 0.3.1 via vanilla-permissions
02.02 01:20:38 [Server] [INFO] - ec-core 1.3.0-mc1.19.3 via essential_commands
02.02 01:20:38 [Server] [INFO] - essential_commands 0.31.0-mc1.19.3
02.02 01:20:38 [Server] [INFO] - fabric-api 0.73.0+1.19.3
02.02 01:20:38 [Server] [INFO] - fabric-api-base 0.4.20+afca2f3e85 via fabric-api
02.02 01:20:38 [Server] [INFO] - fabric-api-lookup-api-v1 1.6.19+49abcf7e85 via fabric-api
02.02 01:20:38 [Server] [INFO] - fabric-biome-api-v1 12.1.0+b5d379b085 via fabric-api
02.02 01:20:38 [Server] [INFO] - fabric-block-api-v1 1.0.4+e022e5d185 via fabric-api
02.02 01:20:38 [Server] [INFO] - fabric-command-api-v1 1.2.21+f71b366f85 via fabric-api
02.02 01:20:38 [Server] [INFO] - fabric-command-api-v2 2.2.0+3fc4752e85 via fabric-api
02.02 01:20:38 [Server] [INFO] - fabric-commands-v0 0.2.38+df3654b385 via fabric-api
02.02 01:20:38 [Server] [INFO] - fabric-containers-v0 0.1.46+df3654b385 via fabric-api
02.02 01:20:38 [Server] [INFO] - fabric-content-registries-v0 3.5.0+1d37d50285 via fabric-api
02.02 01:20:38 [Server] [INFO] - fabric-convention-tags-v1 1.2.1+8e4e694f85 via fabric-api
02.02 01:20:38 [Server] [INFO] - fabric-crash-report-info-v1 0.2.13+aeb40ebe85 via fabric-api
02.02 01:20:38 [Server] [INFO] - fabric-data-generation-api-v1 11.2.0+06937c4b85 via fabric-api
02.02 01:20:38 [Server] [INFO] - fabric-dimensions-v1 2.1.40+48349a3f85 via fabric-api
02.02 01:20:38 [Server] [INFO] - fabric-entity-events-v1 1.5.6+b83334a085 via fabric-api
02.02 01:20:38 [Server] [INFO] - fabric-events-interaction-v0 0.4.39+3baeb27a85 via fabric-api
02.02 01:20:38 [Server] [INFO] - fabric-events-lifecycle-v0 0.2.43+df3654b385 via fabric-api
02.02 01:20:38 [Server] [INFO] - fabric-game-rule-api-v1 1.0.29+99f9db8085 via fabric-api
02.02 01:20:38 [Server] [INFO] - fabric-item-api-v1 2.1.9+c3530bb185 via fabric-api
02.02 01:20:38 [Server] [INFO] - fabric-item-group-api-v1 2.1.11+1134c5b885 via fabric-api
02.02 01:20:38 [Server] [INFO] - fabric-lifecycle-events-v1 2.2.9+23a79c8a85 via fabric-api
02.02 01:20:38 [Server] [INFO] - fabric-loot-api-v2 1.1.19+75e9821185 via fabric-api
02.02 01:20:38 [Server] [INFO] - fabric-loot-tables-v1 1.1.23+9e7660c685 via fabric-api
02.02 01:20:38 [Server] [INFO] - fabric-message-api-v1 5.0.13+6ede1da985 via fabric-api
02.02 01:20:38 [Server] [INFO] - fabric-mining-level-api-v1 2.1.30+49abcf7e85 via fabric-api
02.02 01:20:38 [Server] [INFO] - fabric-networking-api-v1 1.2.16+4017a8cb85 via fabric-api
02.02 01:20:38 [Server] [INFO] - fabric-networking-v0 0.3.33+df3654b385 via fabric-api
02.02 01:20:38 [Server] [INFO] - fabric-object-builder-api-v1 5.4.0+eb2a3ba985 via fabric-api
02.02 01:20:38 [Server] [INFO] - fabric-particles-v1 1.0.19+f1e4495b85 via fabric-api
02.02 01:20:38 [Server] [INFO] - fabric-permissions-api-v0 0.2-SNAPSHOT via essential_commands
02.02 01:20:38 [Server] [INFO] - fabric-recipe-api-v1 1.0.0+5176f73d85 via fabric-api
02.02 01:20:38 [Server] [INFO] - fabric-registry-sync-v0 2.0.4+1134c5b885 via fabric-api
02.02 01:20:38 [Server] [INFO] - fabric-rendering-data-attachment-v1 0.3.24+afca2f3e85 via fabric-api
02.02 01:20:38 [Server] [INFO] - fabric-rendering-fluids-v1 3.0.17+f1e4495b85 via fabric-api
02.02 01:20:38 [Server] [INFO] - fabric-resource-conditions-api-v1 2.2.2+1134c5b885 via fabric-api
02.02 01:20:38 [Server] [INFO] - fabric-resource-loader-v0 0.10.4+a91e48b785 via fabric-api
02.02 01:20:38 [Server] [INFO] - fabric-screen-handler-api-v1 1.3.12+99f9db8085 via fabric-api
02.02 01:20:38 [Server] [INFO] - fabric-transfer-api-v1 2.1.14+ccd377ba85 via fabric-api
02.02 01:20:38 [Server] [INFO] - fabric-transitive-access-wideners-v1 2.3.0+5b9a588b85 via fabric-api
02.02 01:20:38 [Server] [INFO] - fabricloader 0.14.13
02.02 01:20:38 [Server] [INFO] - ferritecore 5.1.0
02.02 01:20:38 [Server] [INFO] - forgeconfigapiport 5.0.6
02.02 01:20:38 [Server] [INFO] - java 17
02.02 01:20:38 [Server] [INFO] - justplayerheads 3.0
02.02 01:20:38 [Server] [INFO] - lithium 0.10.4
02.02 01:20:38 [Server] [INFO] - luckperms 5.4.58
02.02 01:20:38 [Server] [INFO] - minecraft 1.19.3
02.02 01:20:38 [Server] [INFO] - openpartiesandclaims 0.16.6
02.02 01:20:38 [Server] [INFO] - org_yaml_snakeyaml 1.33 via essential_commands
02.02 01:20:38 [Server] [INFO] - phosphor 0.8.1
02.02 01:20:38 [Server] [INFO] - placeholder-api 2.0.0-pre.2+1.19.3 via essential_commands
02.02 01:20:38 [Server] [INFO] - playerabilitylib 1.7.0 via essential_commands
02.02 01:20:38 [Server] [INFO] - vanilla-permissions 0.1.3
02.02 01:20:38 [Server] [INFO] - vanilla-permissions-mc119 0.1.3 via vanilla-permissions

## **Crash report**
No crash report to show, and the mod still runs commands so I know that the server is reading it without problem.

**Comment by calinado** [comment]
I do not understand or know how to use github so I dont know how to add the JustPlayerHeads mod label.

**Comment by ricksouth** [comment]
The mod uses the Mojang API to get texture data. Is the access to this blocked in Russia ("RU post")? The cache is updated once a query to the Mojang API is made. It's empty when the server first boots.
