### ISSUE TITLE
Nether Portal Spread CTD modded items in spread list

### ISSUE THREAD

**Issue by LonelyBard** [ricksouth/serilum-mc-mods#1595]
Minecraft version: 1.19.2
Modloader: Fabric
Fabric loader version: 0.14.13
Environment: Singleplayer
Mod name: Nether Portal Spread + Random Village Names
Mod version: 7.1 for nether portal spread and 3.0 for Random Village Names

## **Description**
Hey! I was working on my modpack and decided to add some modded items to spreadsettings.txt in Nether Portal Spread and exited my test world with an active portal currently spreading. I had edited spreadsettings.txt and saved it and thought I should probably reload my game for it to take effect. I then relaunched my game and clicked on the world. Before it could finish loading, I got a CTD with this crash log that seemed to be blaming random village names, so I'm not sure what the issue may be other than the moded items in the spread list, but I'm unsure because of the crash log if you could help id be very happy. 

## **Crash report**
[crash-2023-02-02_00.24.48-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/10566017/crash-2023-02-02_00.24.48-server.txt)

spreadsettings.txt for Nether portal spread 
[spreadsettings.txt](https://github.com/ricksouth/serilum-mc-mods/files/10566028/spreadsettings.txt)

**Comment by LonelyBard** [comment]
Update: I removed Random Village names and areas, and my save loads

**Comment by ricksouth** [comment]
This has been fixed in version 7.4 of Nether Portal Spreads. Thanks for opening the issue and giving the mod a try!

https://www.curseforge.com/minecraft/mc-mods/nether-portal-spread/files
