### ISSUE TITLE
Hide Hands Configuration not doing anything

### ISSUE THREAD

**Issue by EightBitBBQ** [ricksouth/serilum-mc-mods#1598]
## **Information**
Minecraft version: 1.19.3
Modloader: Forge 
Forge version: 44.1.0
Environment: Singleplayer / Multiplayer

Mod name: Hide Hands
Mod version: 4.0

## **Description**
This is my config:

{
	// If enabled, always hides the main hand. If disabled, hides the main hand when holding the items defined in hideMainHandWithItems.
	"alwaysHideMainHand": false,
	// If enabled, always hides the main hand if it's empty. Will still be visible when swung empty.
	"alwaysHideEmptyMainHand": false,
	// The items which when held will hide the main hand if alwaysHideMainHand is disabled.
	"hideMainHandWithItems": "",
	// If enabled, always hides the offhand. If disabled, hides the offhand when holding the items defined in hideOffhandWithItems.
	"alwaysHideOffhand": false,
	// The items which when held will hide the offhand if alwaysHideOffhand is disabled.
	"hideOffhandWithItems": "minecraft:totem_of_undying"
}

Sadly no setting work.
Main hand is empty. Still not showing.
![2023-02-03_18 19 20](https://user-images.githubusercontent.com/107324400/216667169-4dfa16b8-5eac-4f74-81a6-445be2f1db08.png)

Having torches in off hand. Still not showing

**Comment by ricksouth** [comment]
After a Discord DM: Looks like the problem is that the config was edited on the server. As Hide Hands is a client-side mod, the config has to be edited on the client for changes to happen.
