### ISSUE TITLE
Tree Harverster: Fast decay Wart Blocks

### ISSUE THREAD

**Issue by EightBitBBQ** [ricksouth/serilum-mc-mods#1600]
## **Information**
Minecraft version: 1.19.3
Modloader: Forge / Fabric

Mod name: Tree Harvester

## **Feature description**
Since this mod is working with the nether trees. Why doesnt the "fast leave" option work with Nether Wart en Warped Wart blocks?
Maybe could be added :-)

**Comment by ricksouth** [comment]
This should work in version 7.2 of Tree Harvester! Thanks for giving the mod a try :)

https://curseforge.com/minecraft/mc-mods/tree-harvester/files
