### ISSUE TITLE
missing Netherite Block?

### ISSUE THREAD

**Issue by MBelhardi** [ricksouth/serilum-mc-mods#1601]
## **Information**
Minecraft version: 1.18.2
Modloader: Forge

Mod name: Better Beacon Placement
Mod version: 3.0

## **Question**
Hello,
today I tried your MOD (after a long time, that I didn't play Minecraft), because I try to make a modpack for my own use... but when I tried to use the Netherite Block (hope the english term is the same as in germany, when not, I'm sorry...) as mineral Block for the beacon, your mod didn't accept it. first I thougt, maybe the Netherite Block isn't a mineral Block for the beacon, but when I placed them by hand, the beacon accepted it.
So my question here, did you forget to implement the Netherite Block, or was it for a future update?

Best Regards
King MB (Marcel Belhardi)

**Comment by James103** [comment]
More specifically, blocks in the `#minecraft:beacon_base_blocks` tag should be usable with the Better Beacon Placement mod, instead of just hardcoding to `emerald_block, diamond_block, gold_block, iron_block`.

**Comment by MBelhardi** [comment]
Thanks for the quick answer... in other words Microsoft? Mojang? or whoever is programming Minecraft these days, forgot to put this tag on it... Not good... but not your problem...

**Comment by ricksouth** [comment]
Thanks for opening the issue! I should be able to fix that, not Mojang's fault this time haha! I'll take a look at it whenever I have some time :)

**Comment by ricksouth** [comment]
This has been fixed in version 3.1 Better Beacon Placement, thanks for opening the issue!

https://curseforge.com/minecraft/mc-mods/better-beacon-placement/files
