### ISSUE TITLE
[Fabric 1.16.5] Areas does't have a update for 1.16.5

### ISSUE THREAD

**Issue by Bekman120** [ricksouth/serilum-mc-mods#1602]
Areas mod doesn´t have a update for 1.16.5 Fabric
Minecraft version: 1.16.5
Modloader: Fabric
Fabric loader version: 0.14.13
Environment: Singleplayer

First mod name: Areas
First mod version: 2.4

Second mod name: Random Village Names
Second mod version: 2.0

So first of all, your mods are amazing and I'm trying Fabric in 1.16.5 so obviously downloaded the "Legacy Fabric" of Random Village Names and search for "Areas" mod with compatibility for 1.16.5 Fabric but without results. Am i missing something?

Thanks for your atention and your mods

**Comment by ricksouth** [comment]
It should be right here! https://www.curseforge.com/minecraft/mc-mods/areas-fabric, not sure why you couldn't find it. Thanks for the interest!

**Comment by Bekman120** [comment]
Thank you so much, I'm so dumb jej
