### ISSUE TITLE
Nether Portal Spread Error

### ISSUE THREAD

**Issue by Igilq** [ricksouth/serilum-mc-mods#1604]
## **Information**
Minecraft version: 1.18.2
Modloader: Forge 
Forge version: 40.2.1  
Environment: Singleplayer / Multiplayer

Mod name: Nether Portal Spread
Mod version: 5.7

## **Description**
Hey! This happened.
I wanted to launch minecraft it launched but it didn't let me play. Here is text which apeared.
Nether Portal Spread (netherportalspread) has failed to load correctly
java.lang.reflect.InvocationTargerExeption: null

## **Crash report**
_(Please either drag the file directly here, or use https://gist.github.com/ to prevent the paste from expiring)_
[crash-2023-02-05_16.20.10-fml.txt](https://github.com/ricksouth/serilum-mc-mods/files/10611379/crash-2023-02-05_16.20.10-fml.txt)

If available.

**Comment by ricksouth** [comment]
Please update Nether Portal Spread and Collective to the latest version, it'll fix this issue. Thanks for giving the mods a try!
