### ISSUE TITLE
Cycling paintings causes them to revert to the 'kebab' painting on chunk reload.

### ISSUE THREAD

**Issue by whyisitatoz** [ricksouth/serilum-mc-mods#1606]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version:43.2.0
Environment: Singleplayer

Mod name: Cycle Paintings
Mod version: 3.0

## **Description**
After placing multiple paintings of different sizes, I cycled them using the mechanic this mod provides. After I closed and reopened the world all the paintings had reverted to the 'kebab' painting. I tested this further by just placing a painting and not cycling it, then reloading the world and found that it did *not* convert into the 'kebab' painting. This also occurs if the chunks are unloaded by going far away and then returning. I believe the painting cycling is causing an error when saving that results in the cycled paintings reverting to the default? 'kebab' painting.

**Comment by ricksouth** [comment]
Thanks for opening the issue! Really appreciate it, as I've missed this during local testing. This has been fixed in version 3.1 of Cycle Paintings, apologies for the inconvenience.

https://www.curseforge.com/minecraft/mc-mods/cycle-paintings/files
