### ISSUE TITLE
1.18.2 - Log Support Missing for Ecologist

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [ricksouth/serilum-mc-mods#1607]
I deleted this because its just missing log support. 

https://beta.curseforge.com/minecraft/mc-mods/ecologics
treeharvester-1.18.2-7.0.jar

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! Compatibility has been added in version 7.2 of Tree Harvester.

https://curseforge.com/minecraft/mc-mods/tree-harvester/files
