### ISSUE TITLE
1.18.2 Forge Blocks & Mobs turn invisible.

### ISSUE THREAD

**Issue by nuac87** [ricksouth/serilum-mc-mods#1608]
## **Information**
Minecraft version: 1.18.2
Modloader: Forge
Forge version: 1.18.2-forge-40.2.1
Environment: Singleplayer

First mod name: Omega Mute
First mod version: Forge & Fabric 1.18.2-3.0

## **Description**
When using Omega Mute it makes the mobs  and some blocks modded and vanilla invisible and after I removed Omega Mute everything started worked properly again. I muted the nether portal ambient sound and this happened.
## **Crash report**
N/A

**Comment by ricksouth** [comment]
This doesn't seem like it should happen by Omega Mute. It doesn't use that code. Does it still happen without other mods installed?
