### ISSUE TITLE
Text Color Book

### ISSUE THREAD

**Issue by FableShift** [ricksouth/serilum-mc-mods#1610]
## **Information**
Minecraft version: 1.16.5 / 1.19.2
Modloader: Forge
Forge version: 36.2.39 / 43.2.0
Environment: Singleplayer

Mod name: Starter Kit
Mod version: 4.1 / 5.0

## **Description**
Hello,

Let me explain my issue. I am doing a modpack and in the book i made in the starter kit, i colored the text with the "§" MC feature. When the book is given on a new world, the color is bit buggy , adding "A" before every line where colors have been applied. I hope there is something to do because its ruining my idea :/ Thank you

## **Crash report**
X

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! Appreciate it. This has been fixed in version 5.1 of Starter Kit.

https://curseforge.com/minecraft/mc-mods/starter-kit/files
