### ISSUE TITLE
Advancement Screenshot: No screenshot gets taken

### ISSUE THREAD

**Issue by TheScienceDemon** [ricksouth/serilum-mc-mods#1611]
## **Information**
Minecraft version: 1.16.5
Modloader: Forge
Forge version: 36.2.34
Environment: Singleplayer

Mod name: Advancement Screenshot
Mod version: 3.6

## **Description**
Hey! This happened: No screenshot is getting taken
Is there a special folder where the screenshots are getting placed? Because after completing / getting an advancement there is no screenshot appearing in the normal screenshots folder.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 4.1 of Advancement Screenshot.

https://www.curseforge.com/minecraft/mc-mods/advancement-screenshot/files

**Comment by TheScienceDemon** [comment]
It seems like the 1.16.5 version of the mod didn't receive the 4.1 update. Was this made intentional / have you stopped supporting mods on 1.16.5?
