### ISSUE TITLE
1.18.2 - Question Why Do Multiple of your Mods cause an Error With Auto Reg 

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [ricksouth/serilum-mc-mods#1612]
Lots of your mods excluding the following mods

![Y1prBxL 1](https://user-images.githubusercontent.com/10351221/217966919-76f1ce81-a468-42c1-8cbf-5b19132a3f8c.png)

![PgYMk1U 1](https://user-images.githubusercontent.com/10351221/217966857-e4d2e645-39f6-4467-a441-0b7ee31db090.png)

![6hROrFv 1](https://user-images.githubusercontent.com/10351221/217966764-a37e24a4-141f-4666-9f13-7dffc95c59a3.png)

I hope this helps to increase your mod compatibility. 

https://gist.github.com/P3rf3ctXZer0/98a3434f56f7e2039958a656ea95d632

**Comment by James103** [comment]
See also https://github.com/VazkiiMods/AutoRegLib/issues/82

**Comment by P3rf3ctXZer0** [comment]
What would you like me to do? I cannot get the unofficial fixed version and its not public - its github only. If you want to close this you can I will just keep working around it for now.

**Comment by ricksouth** [comment]
How did you conclude my mods were incompatible?

**Comment by P3rf3ctXZer0** [comment]
Adding them to packs with autoreglib mainly things that spawn so like skeleton horse and passive shields caused crashes.
