### ISSUE TITLE
1.12.2 All Loot Drop mod doesn't work as expected.

### ISSUE THREAD

**Issue by vainlaind4in** [ricksouth/serilum-mc-mods#1616]
Mod Version: 1.3

It appears that All Loot Drops for 1.12.2 doesn't work as expected for two things. For one, it appears that there is only one configuration option for the mod, when in the description it states there is more than one.

The second thing is that looting doesn't work for the loot drops affected by the mod. The only things affected are the ones that are added to the loot tables of different mobs (ex. actually addition's solidified experience, quark's tallow for pigs, mystical agriculture's inferium, etc.) 

It might be that I'm using a modded version of looting, but the Advanced Looting from So Many Enchantments should function as normal vanilla looting, except buffed for each level.

If this is a result of the 1.12.2 being discontinued, then I can understand. I can assume that it is hard to develop mods for many different versions, even as a normal player who only uses mods.

**Comment by ricksouth** [comment]
This is indeed because the 1.12.2 version is no longer being developed. The description shows the features of the mod of the latest version. Apologies for the inconvenience, but thanks for the interest nonetheless!
