### ISSUE TITLE
(1.18.2) Realistic Bees not working (only mod installed)

### ISSUE THREAD

**Issue by Kaiserbow** [ricksouth/serilum-mc-mods#1617]
Minecraft version: 1.18.2
Modloader: Forge
Forge version: 40.1.85
Environment: Singleplayer

Mod name: Realistic Bees
Mod version: 3.1/3.0/2.8 (as well as Collective 6.43/6.42/6.40)

After having issues with this mod being reinstalled alongside other mods, I have attempted to only have RB and Collective installed (above versions), and RB is not working whatsoever. Bee size is not changing to config size of 0.25, no matter what changes may be made to .json file.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 3.3 of Realistic Bees.

https://www.curseforge.com/minecraft/mc-mods/realistic-bees/files

**Comment by Kaiserbow** [comment]
Just installed that version and it indeed works fine again (even with other mods). Thank you very much!
