### ISSUE TITLE
Fixed: Unable to start Minecraft

### ISSUE THREAD

**Issue by Scamper10** [ricksouth/serilum-mc-mods#1618]
## **Information**
Minecraft version: 1.16.5
Modloader: Fabric
Fabric loader version: 0.11.2

## **Description**
I am having the same error with several mods: Whenever I start the game, nothing happens for a while, then the launcher tells me the game crashed. In the small message that appears, it says "Could not execute entrypoint stage 'main' due to errors, provided by 'modname'!" where modname changes.

Which mod is stated stays constant if the files remain unchanged, however downgrading the affected mod (using the legacy fabric versions on curseforge) will change the error message. This was until it said collective was the issue, and now changing the version of collective has no visible efffect.

## **Crash report**
[crash-2023-02-13_16.54.10-client.txt](https://github.com/ricksouth/serilum-mc-mods/files/10724465/crash-2023-02-13_16.54.10-client.txt)

**Comment by ricksouth** [comment]
I've asked about this in the Fabric discord, and the problem seems to be an outdated version of the Fabric loader. Could you update it to the latest version?

**Comment by Scamper10** [comment]
I'll try it when I can and get back to you

**Comment by Scamper10** [comment]
Apologies for the wait, updating the mod loader has fixed the issue.
