### ISSUE TITLE
Still spawning mobs despite being "disabled"

### ISSUE THREAD

**Issue by LunarDev-git** [ricksouth/serilum-mc-mods#1619]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 43.2.4 & 43.2.0
Environment: Singleplayer & Multiplayer

Mod name: Better Spawner Control
Mod version: 1.19.2-4.0
(Collective version: 1.19.2-6.43)

## **Description**
Mobs still spawning despite being surrounded by 5 normal torches. 
I used a blaze spawn in the nether if that is relevant and tested it with JUST better spawner control, still happens.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 6.51 of Collective. Better Spawner Control doesnt need an update.

https://www.curseforge.com/minecraft/mc-mods/collective/files
