### ISSUE TITLE
Could I use some Collective code for my mod?

### ISSUE THREAD

**Issue by Sam-Chai** [ricksouth/serilum-mc-mods#1620]
## **Comment**
Hi! I'm Sam_Chai. Your collective lib mod have given me a lot of inspiration for development, now I wanna develop a set of mods for my own use.
These mods will opensource use MIT, and if you allow, I want publish my mods on CurseForge and MCMOD on Chinese and Japanese website

**Comment by ricksouth** [comment]
As my mods are licensed as All Rights Reserved, this is unfortunately not possible. You can use it for inspiration, but not copy complete sections of code.

**Comment by Sam-Chai** [comment]
> As my mods are licensed as All Rights Reserved, this is unfortunately not possible. You can use it for inspiration, but not copy complete sections of code.

Sure. Thank you for answer
