### ISSUE TITLE
Changing the Forge config file type in future (Or even existing ones) 

### ISSUE THREAD

**Issue by RandomGuy91** [ricksouth/serilum-mc-mods#1621]
Hey! I love your mods, and I  am making a modpack with about 20 of your mods. When I was editing the configs, I realised they are in a different format than most other ones. Is there anyway you can make them in the Forge config format (I think it's .toml) so people can edit it with mods like Config Menus for Forge by Fusz_ or similar? < This mod adds the ability to copy configs to default which is very useful, but I can't do it with your mods. Just a QoL suggestion. :) Have a good day!

**Comment by ricksouth** [comment]
Hi, glad you find them useful! You should be able to edit them in-game via the config button. Json5 is basically JSON with additional comments (the //'s). I can't use Forge's built-in config since the same code is used for both Forge and Fabric. You should be able to edit them in-game though!

**Comment by RandomGuy91** [comment]
Yeah, they really complement Vanilla really well. Ok, just wondering. Just a minor annoyance, but nothing I can't handle! :)

**Comment by ricksouth** [comment]
With "This mod adds the ability to copy configs to default which is very useful", what do you mean exactly? Do you have a link to this feature?

**Comment by RandomGuy91** [comment]
Yh, here https://drive.google.com/file/d/140M_rs69_o-zoSfjvEyFAyFwaC7F_VQx/view?usp=sharing
(sry bout the music)

**Comment by ricksouth** [comment]
Ah, I won't be able to add compatibility on my end. But maybe the other mod that adds this could add support for json/json5. Might be worth opening an issue on their end.

**Comment by RandomGuy91** [comment]
Oke, I'll try that. Thx!
