### ISSUE TITLE
[1.18.2] Conduits Prevent Drowned's attempts to prevent Drowned spawns sometimes crash the game

### ISSUE THREAD

**Issue by Thedeur** [ricksouth/serilum-mc-mods#1625]
## **Information**
Minecraft version: 1.18.2
Modloader: Forge
Forge version: 40.2.0
Environment: Singleplayer

Mod name: Conduits Prevent Drowned
Mod version: 3.0

I'm also using Prism Launcher 6.3

## **Description**
As the title suggests—and from my cursory reading of the crash log—it seems CPD's attempts at suppressing Drowned spawns causes it to sometimes instantly crash the game (it's happened twice now, though pretty sporadically) with no error messages. 

A possible guess is a mod conflict with PeacefulSurface, which also prevents certain mobs from spawning, but other than that I have no idea. 

## **Crash report**
https://gist.github.com/Thedeur/ed5f2c23b8319cf014e3b2b051b32a0b

(I have a crap-ton of mods, I know)

**Comment by ricksouth** [comment]
Thanks for opening the issue! This has been fixed in version 3.2 of Conduits Prevent Drowned. Appreciate it.

https://www.curseforge.com/minecraft/mc-mods/conduits-prevent-drowned/files
