### ISSUE TITLE
Chest Boats

### ISSUE THREAD

**Issue by NealSavage** [ricksouth/serilum-mc-mods#1628]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.19.2
Modloader: / Fabric
Forge version: xx.xx.xx  OR  Fabric loader version: x.xx.x
Environment: Singleplayer / Multiplayer

Mod name: Mod
Mod version: x.x

## **Question**
?

Will this pickup my chest boat with the items staying in the chest and not break anything so that I can retrieve my items from at the bottom of the ocean and make the boat sailable again?

**Comment by ricksouth** [comment]
I assume you mean the Move Boats mod? And yes, that should work :)
