### ISSUE TITLE
/deathbackup list no longer works

### ISSUE THREAD

**Issue by nbtc971** [ricksouth/serilum-mc-mods#1632]
## **Information**
Minecraft version: 1.19.3
Modloader: Fabric
Fabric loader version: 0.14.14-1.19.3
Environment: Multiplayer

Mod name: Death Backup
Mod version: 3.0

## **Description**
Died to a creeper, respawned, tried you use /deathbackup list and got nothing printed to chat window. I am able to load the backup however. I will mention that before this, I had used the Minecraft launcher to launch Optifine loader instead of the Fabric Loader because I was working on something else. Don't know if that matters but I thought I'd mention it. I have restarted server. Stopped server, and deleted the Deathbackup .jar from the server, restarted server, shut it down and reinstalled the jar file, but that didn't change anything.

## **Crash report**
_(Please either drag the file directly here, or use https://gist.github.com/ to prevent the paste from expiring)_

If available.

**Comment by ricksouth** [comment]
As mentioned in a DM on CurseForge, the author fixed it via:

/gamerule commandblockoutput true
/gamerule sendCommandFeedback true

@nbtc971 Thanks for giving the mod a try!
