### ISSUE TITLE
Players unable to use /track

### ISSUE THREAD

**Issue by nerdman0** [ricksouth/serilum-mc-mods#1633]
## **Information**
Minecraft version: 1.12.2
Modloader: Forge
Forge version: 14.23.5.2860
Environment: Multiplayer

Mod name: Player Tracking
Mod version: 1.4

## **Description**
Players unable to use the /track command (do not have permission)

## **Crash report**
Not a crash

**Comment by ricksouth** [comment]
I unfortunately don't support Minecraft 1.12 anymore. Thanks for the interest nonetheless!
