### ISSUE TITLE
Hoe Tweaks configuration being unintentionally reset

### ISSUE THREAD

**Issue by marianyp** [ricksouth/serilum-mc-mods#1639]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 43.2.3
Environment: Singleplayer

Mod name: Hoe Tweaks
Mod version: 1.9.2-3.1

## **Description**
Config values keep resetting. I'm setting all of the hoe range values to 0 (because I don't want their functionality, only the break speed and un-tilling features). However, every time I set those values, they get reset. I believe they are being reset every time I startup Minecraft.

**Comment by ricksouth** [comment]
Where are you setting the values? In-game or via the file? The config values don't reset for me
