### ISSUE TITLE
Incorrect descriptions for config settings for Hoe Tweaks

### ISSUE THREAD

**Issue by James103** [ricksouth/serilum-mc-mods#1640]
## **Information**
Minecraft version: 1.19.3
Modloader: Forge and Fabric (use latest loader version at time of writing)
Environment: Singleplayer and Multiplayer

Mod name: Hoe Tweaks
Mod version: https://github.com/ricksouth/serilum-mc-mod-sources/commit/c37dc6ef93f41477ded722c67eef8a1a94626a57

## **Description**
https://github.com/ricksouth/serilum-mc-mod-sources/blob/c37dc6ef93f41477ded722c67eef8a1a94626a57/sources/Hoe%20Tweaks/1.19.3/Common/src/main/java/com/natamus/hoetweaks/config/ConfigHandler.java#L52-L66

The config options listed in the above link have incorrect descriptions (currently, all of them say "wooden hoe" instead of the correct hoe tier). Fixed code attached below (descriptions corrected):

```
configMetaData.put("stoneTierHoeRange", Arrays.asList(
	"The stone hoe till range (default while crouching). 1 = 3x3"
));
configMetaData.put("goldTierHoeRange", Arrays.asList(
	"The golden hoe till range (default while crouching). 2 = 5x5"
));
configMetaData.put("ironTierHoeRange", Arrays.asList(
	"The iron hoe till range (default while crouching). 2 = 5x5"
));
configMetaData.put("diamondTierHoeRange", Arrays.asList(
	"The diamond hoe till range (default while crouching). 3 = 7x7"
));
configMetaData.put("netheriteTierHoeRange", Arrays.asList(
	"The netherite hoe till range (default while crouching). 4 = 9x9"
));
```

**Comment by ricksouth** [comment]
Thanks! This has been fixed in version 3.2 of Hoe Tweaks.

https://www.curseforge.com/minecraft/mc-mods/hoe-tweaks
