### ISSUE TITLE
Pumpkillager's Quest: prisoner camp didn't appear

### ISSUE THREAD

**Issue by DarkDestrov** [ricksouth/serilum-mc-mods#1642]
## **Information**
Minecraft version: 1.19.3
Modloader: Forge 
Forge version: 44.1.17 
Environment: Singleplayer

Mod name: Pumpkillager's Quest
Mod version: 3.2

## **Description**
Prisoner camp didn't appear when i came to the coordinates from paper. I check Guide on Curseforge mod page, and i did't have same things - there is nothing in the sky.
I tried to re-install mod (delete mod and config file, launch my world, exit the game, install mod), but when I complete the first ritual, I got message that it's useless and I need to find prisoner.

**Comment by ricksouth** [comment]
Thank you for opening the issue. I couldn't replicate this locally, but have just uploaded a version with various bug fixes. If the issue persists, please let me know.

https://www.curseforge.com/minecraft/mc-mods/pumpkillagers-quest/files
