### ISSUE TITLE
May I create a 1.12.2 backport for your Full Brightness Toggle mod, please?

### ISSUE THREAD

**Issue by Lightningtow** [ricksouth/serilum-mc-mods#1646]
## **May I backport Full Brightness Toggle to 1.12.2?**
Hi

I've been searching around and the only 1.12.2 fullbright mod I can find requires Liteloader, which is more trouble than its worth. I was wondering, would you be okay with me backporting your Full Brightness Toggle mod to 1.12.2, please? I only want it for my own personal use, you're free to release it under your own name and do what you wish with it. I'm not trying to steal your mod or attempt to gain profits from it, or anything lame like that. Assuming I'm able to get it working and you release it, I would appreciate a credit line commented somewhere but I don't care that much, as long as there's a way for me to include it on my future portfolio. (Which I assume GitHub has somewhere, I'm pretty new to collaborating via this platform though, so I'm not certain the best place to find it, but I'll figure it out lol.)

Thank you!

--Lightningtow

**Comment by ricksouth** [comment]
The following mod is for 1.12:
https://www.curseforge.com/minecraft/mc-mods/fullbright

It should work for 1.12.2 as well I think!

**Comment by Lightningtow** [comment]
That works perfectly! I'm not sure why I couldn't find that earlier, sorry for the inconvenience. Thank you!
