### ISSUE TITLE
Keybinds for GUI Clock?

### ISSUE THREAD

**Issue by Altif44** [ricksouth/serilum-mc-mods#1647]
I can't find any menus to show me the keybinds for the forge/fabric GUI Clock mod for 1.19, I turned it off somehow and can't get it back on even in the config. Are there any keybinds to turn the GUI on or off in game?

**Comment by ricksouth** [comment]
There are no keybinds. You need the clock item in your inventory for it to show. If you always want it to show, you can enable that in the config. Thanks for giving the mod a try!
