### ISSUE TITLE
Singular Fabric Mod Consideration

### ISSUE THREAD

**Issue by LunaByter** [ricksouth/serilum-mc-mods#1650]
## **Information**
Modloader: Fabric

## **Question**
Hi! I went to download The Vanilla Experience but realized there isn't a singular mod for Fabric. If you have the time do you think you could possibly combine everything into a single configurable mod? I don't know how the Forge version works, but I highly recommend taking a look at [Fabrication](https://modrinth.com/mod/fabrication). Everything is configurable within the game via simple GUI or commands! If it's already something you're working on I apologize.

Thanks for reading, hope you have a nice day! <3

**Comment by ricksouth** [comment]
I've attempted this in the past, but it didn't work correctly due to the amount of code, and it being designed to work modular. I might give it another attempt in the future. Thanks for the interest!
