### ISSUE TITLE
Grey drop shadow behind GUI and hide with F3 menu

### ISSUE THREAD

**Issue by 4zy1** [ricksouth/serilum-mc-mods#1652]
## **Information**
Minecraft version: 1.18.2/1.19.3
Modloader: Forge / Fabric

Mod name: GUI Clock & GUI Compass

## **Feature description**
The current text for the GUI has no drop shadow and is plain white and looks out of place compared to other text in the game. Also the text should be hidden when the F3 menu is open so it doesn't obfuscate anything.
![image](https://user-images.githubusercontent.com/64864278/222305779-6897ae29-e39b-459f-a54d-9579d6400cec.png)

**Comment by ricksouth** [comment]
Both have been added in the latest versions of GUI Clock and GUI Compass. Thanks for the suggestion and giving the mods a try!

https://www.curseforge.com/minecraft/mc-mods/gui-clock/files
https://www.curseforge.com/minecraft/mc-mods/gui-compass/files
