### ISSUE TITLE
Cycle Paintings Crash on SMP

### ISSUE THREAD

**Issue by katubug** [ricksouth/serilum-mc-mods#1653]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 43.2.4
Environment: Multiplayer

Mod name: Cycle Paintings
Mod version: 3.1

## **Description**
I was attempting to cycle paintings on my multiplayer server, and right clicking a painting with painting in hand fully crashed me to desktop. I do have several other painting-altering mods, which should be specified in the modlist inside the crash report.

## **Crash report**
https://pastebin.com/Zupxhfjy

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! I couldn't replicate the issue locally, but it should be fixed in version 3.2 of Cycle Paintings. But please let me know if that isn't the case.

https://www.curseforge.com/minecraft/mc-mods/cycle-paintings/files
