### ISSUE TITLE
Pumpkillager Summoning doesn't work

### ISSUE THREAD

**Issue by TheTanzer22** [ricksouth/serilum-mc-mods#1654]
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 43.2.0
Environment: Singleplayer
Mod name: Pumpkillager's Quest
Mod version: 3.2

I followed the instructions for the questline until the part where you do the summoning ritual for the Pumpkillager for the battle. I double checked that the ritual was structured properly, but nothing happened no matter how I did it.

This is my mod list, in case that helps:
<ul>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/yungs-api">YUNG's API (Forge) (by YUNGNICKYOUNG)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/autoreglib">AutoRegLib (by Vazkii)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/doggy-talents-next">Doggy Talents Next (by dashiedev)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/gobber">Gobber [FORGE] (by kwpugh)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/sophisticated-core">Sophisticated Core (by P3pp3rF1y)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/friendly-fire">Friendly Fire (by DarkhaxDev)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/akashic-tome">Akashic Tome (by Vazkii)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/botarium">Botarium (by CodexAdrian)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/apotheosis">Apotheosis (by Shadows_of_Fire)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/the-lost-cities">The Lost Cities (by McJty)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/cloth-config">Cloth Config API (Fabric/Forge) (by shedaniel)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/endremastered">End Remastered (by jack_bagel)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/drp-global-datapack">Global Packs (by JTK222)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer">Just Enough Resources (JER) (by way2muchnoise)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/createaddition">Create Crafts & Additions (by MRHminer)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/yungs-better-witch-huts">YUNG's Better Witch Huts (Forge) (by YUNGNICKYOUNG)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/patchouli">Patchouli (by Vazkii)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/item-nbt-viewer">(Forge) Item NBT Viewer (Tooltip) (+ Slot Numbers) (by xaero96)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks">Mouse Tweaks (by YaLTeR)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-config-lib">SuperMartijn642's Config Lib (by SuperMartijn642)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/yungs-better-mineshafts-forge">YUNG's Better Mineshafts (Forge) (by YUNGNICKYOUNG)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/i-like-wood">I Like Wood (by yamahari_)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/bookshelf">Bookshelf (by DarkhaxDev)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/jepp">Just Enough Painting Previews (JEPP) (by MehVahdJukaar)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/refined-storage-addons">Refined Storage Addons (by raoulvdberge)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/fast-leaf-decay">Fast Leaf Decay (by olafskiii)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/controlling">Controlling (by Jaredlll08)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/placebo">Placebo (by Shadows_of_Fire)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/better-beacon-placement">Better Beacon Placement (by Serilum)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/baubley-heart-canisters">Baubley Heart Canisters (by traverse_joe)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/ftb-backups-2">FTB Backups 2 (by FTB)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/yungs-better-desert-temples">YUNG's Better Desert Temples (Forge) (by YUNGNICKYOUNG)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/appleskin">AppleSkin (by squeek502)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/i-like-wood-biomes-o-plenty-plugin">I Like Wood - Biomes O' Plenty Plugin (by yamahari_)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest">The Twilight Forest (by Benimatic)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/pumpkillagers-quest">Pumpkillager's Quest (by Serilum)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/create-ore-excavation-plus">Create Ore Excavation Plus (by tiestoettoet08)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/hexal">Hexal (by talistan0)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/yungs-better-strongholds">YUNG's Better Strongholds (Forge) (by YUNGNICKYOUNG)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/domestication-innovation">Domestication Innovation (by sbom_xela)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/botania">Botania (by Vazkii)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked">Cosmetic Armor Reworked (by LainMI)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/not-enough-animations">Not Enough Animations (by tr9zw)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/configurable-extra-mob-drops">Configurable Extra Mob Drops (by Serilum)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib">SuperMartijn642's Core Lib (by SuperMartijn642)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/easy-piglins">Easy Piglins (by henkelmax)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/chunk-loaders">Chunk Loaders (by SuperMartijn642)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/immersive-portals-for-forge">Immersive Portals (for Forge) (by qouteall)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/first-person-model">First-person Model (Forge/Fabric) (by tr9zw)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty">Biomes O' Plenty (by Forstride)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge">Kotlin for Forge (by thedarkcolour)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/dungeon-crawl">Dungeon Crawl (by xiroc_)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/attributefix">AttributeFix (by DarkhaxDev)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/yungs-better-dungeons">YUNG's Better Dungeons (Forge) (by YUNGNICKYOUNG)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/curios">Curios API (Forge) (by TheIllusiveC4)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/rs-requestify">Refined Storage: Requestify (by Buuz135)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/better-third-person">Better Third Person (by Socolio)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/just-enough-professions-jep">Just Enough Professions (JEP) (by Mrbysco)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/ad-astra">Ad Astra (by AlexNijjar)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/dragon-mounts-legacy">Dragon Mounts: Legacy (by UnitKay9)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/resourceful-lib">Resourceful Lib (by ThatGravyBoat)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/l_ender-s-cataclysm">L_Ender 's Cataclysm (by mcl_ender)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/rubidium">Rubidium (by Asek3)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/jei">Just Enough Items (JEI) (by mezz)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/yungs-bridges">YUNG's Bridges (Forge) (by YUNGNICKYOUNG)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/quark-oddities">Quark Oddities (by Vazkii)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/mahou-tsukai">Mahou Tsukai (by stepcros)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/the-banished">The Banished (by Ddx11__)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/hexcasting">Hex Casting (by petrak_at)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/clumps">Clumps (by Jaredlll08)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/jade">Jade 🔍 (by Snownee_)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/codechicken-lib-1-8">CodeChicken Lib 1.8.+ (by covers1624)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/easy-villagers">Easy Villagers (by henkelmax)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/nbt-autocomplete">NBT Autocomplete (by mt1006x)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/hexerei">Hexerei (by JoeFoxe)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/yungs-better-ocean-monuments">YUNG's Better Ocean Monuments (Forge) (by YUNGNICKYOUNG)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/create">Create (by simibubi)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/clear-despawn">Clear Despawn [Forge] (by StrikerRocker)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/armor-toughness-bar">Armor Toughness Bar (by tfarecnim)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/auto-plant">Auto Planting Forests (by Lothrazar)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/refined-storage">Refined Storage (by raoulvdberge)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/doggy-talents">Doggy Talents (by percivalalb)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/ender-storage-1-8">Ender Storage 1.8.+ (by covers1624)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/yungs-extras">YUNG's Extras (Forge) (by YUNGNICKYOUNG)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/collective">Collective (by Serilum)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/resourceful-config">Resourceful Config (by ThatGravyBoat)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/polylib">PolyLib (by Official_CreeperHost)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/curios-quark-oddities-backpack">Curios Quark Oddities Backpack (by 6LeoY)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/storage-drawers">Storage Drawers (by Texelsaur)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/jade-addons">Jade Addons (Forge) (by Snownee_)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions">Enchantment Descriptions (by DarkhaxDev)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/mob-grinding-utils">Mob Grinding Utils (by vadis365)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/citadel">Citadel (by sbom_xela)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap">Xaero's Minimap (by xaero96)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/scaffolding-drops-nearby">Scaffolding Drops Nearby (by Serilum)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/paucal">PAUCAL (by petrak_at)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/tardis-refined">TARDIS Refined - Forge/Fabric (by commandrmooselive)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/create-ore-excavation">Create Ore Excavation (by tom54541)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/regeneration">Doctor Who - Regeneration (by Suff99)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks">Sophisticated Backpacks (by P3pp3rF1y)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/architectury-api">Architectury API (Fabric/Forge) (by shedaniel)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/quark">Quark (by Vazkii)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/terrablender">TerraBlender (Forge) (by TheAdubbz)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/just-enough-calculation">Just Enough Calculation (by towdium)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/i-like-wood-twilight-forest-plugin">I Like Wood - Twilight Forest Plugin (by yamahari_)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map">Xaero's World Map (by xaero96)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/moreiotas">MoreIotas (by talistan0)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/overloaded-armor-bar">Overloaded Armor Bar (by tfarecnim)</a></li>
</ul>

p.s. Although I have this listed as a bug, it may actually be an incompatibility.

**Comment by TheTanzer22** [comment]
Just to cover all my bases, [https://imgur.com/a/x3S5rY1](url)

**Comment by ricksouth** [comment]
Thank you for opening the issue. I couldn't replicate this locally, but have just uploaded a version with various bug fixes. If the issue persists, please let me know.

https://www.curseforge.com/minecraft/mc-mods/pumpkillagers-quest/files
