### ISSUE TITLE
Tree Harvester not working on Forge server, 1.19.3

### ISSUE THREAD

**Issue by Swedishdogs** [ricksouth/serilum-mc-mods#1657]
## **Information**
Minecraft version: 1.19.3
Modloader: Forge
Forge version: 44.1.21
Environment: Multiplayer

Mod name: Tree Harvester
Mod version: 1.19.3-7.3

## **Question**

Mod works fine in singleplayer but doesn't when installed on an Unraid Forge server. Other mods work fine, but for the sake of excluding potential compatibility issues we removed them and only left Tree Harvester (and its dependency).
We tried installing the mods both serverside + clientside and serverside only, but it just doesn't seem to work. No axes were blacklisted, no config parameters were changed and we're playing in survival mode.

**Comment by ricksouth** [comment]
This has been fixed in version 8.0 of Tree Harvester. Thanks for opening the issue and giving the mod a try!

https://www.curseforge.com/minecraft/mc-mods/tree-harvester
