### ISSUE TITLE
Client-side only version of Areas

### ISSUE THREAD

**Issue by Bros112** [ricksouth/serilum-mc-mods#1660]
## **Information**
Minecraft version: any
Modloader: any

Mod name: Areas

## **Feature description**
A client only version of areas could be made, or integrated into the main version, that works on signs in non-modded servers or servers that do not have the mod.
This could be done by looking at all signs and it one has the right format, it displays the area titles.
 This would allow a fully client-side implentation of the mod on a server while keeping to the functionality of the original mod.

**Comment by ricksouth** [comment]
Thanks for the suggestion and giving the mod a try! Version 5.0 of Areas does exactly this. All the GUI code is now client-side only. If you'd like the mod to generate area names randomly, it would still have to be installed on the server.

https://legacy.curseforge.com/minecraft/mc-mods/areas/files
