### ISSUE TITLE
All loot drop Bug

### ISSUE THREAD

**Issue by 0rgeneral** [ricksouth/serilum-mc-mods#1661]
## **Information**
Minecraft version: 1.16.5
Modloader: Forge 
Forge version: 36.2.34 
Environment: Singleplayer 

Mod name: all loot drop mod
Mod version: 2.6

## **Description**
when i add this mode after cant create new world just i see %1 thats it.  after i remove it  everything work properly, no making crash but no creating world. :/ and its really good one :( 

## **Crash report**
_(Please either drag the file directly here, or use https://gist.github.com/ to prevent the paste from expiring)_

If available.

**Comment by ricksouth** [comment]
Unfortunately 1.16.5 is no longer supported. I think this is an incompatibility with another mod which makes the world freeze. Apologies for the inconvenience.
