### ISSUE TITLE
Submitting issues with Quilt Modloader for Skeleton Horse Spawn, Giant Spawn, No Hostiles Around Campfire

### ISSUE THREAD

**Issue by retropele** [ricksouth/serilum-mc-mods#1662]
## **Information**
Minecraft version: 1.19.2
Modloader: Quilt
Quilt version: 0.18.3
Environment: Multiplayer

Mod names: No Hostiles Around Campfires, Giant Spawn, Skeleton Horse Spawn
Mod version: 1.19.2 Fabric, 1.19.2 Fabric, 1.19.2 Fabric

## **Question**
I tried a boat load of your mods (which are all AMAZING) and found that a few of them are seemingly incompatible with Dimensional Threading. However, I'm using Quilt, and I don't know if that's the actual issue, and if you don't support Quilt I don't want to clog up your issue management system with these reports.

I've attached the crash reports for all 3.
[crash-2023-03-09_05.55.18-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/10928369/crash-2023-03-09_05.55.18-server.txt)
[crash-2023-03-09_06.00.27-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/10928370/crash-2023-03-09_06.00.27-server.txt)
[crash-2023-03-09_06.05.35-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/10928382/crash-2023-03-09_06.05.35-server.txt)

(That being said, I am so desperate for these 3 mods, if you could figure out why they don't work on/with Quilt + DimThread I would be euphoric)

If it's okay to submit issues for each with them being ran on Quilt I will do so. :)

**Comment by ricksouth** [comment]
I've updated Collective and the three mods to fix this issue. I don't think it was Quilt specific, but just due to how Dimensional Threading works. But it should be all good now! Thanks for the kind words and opening the issue!
