### ISSUE TITLE
Double doors open and close instantly

### ISSUE THREAD

**Issue by Herobattler** [ricksouth/serilum-mc-mods#1663]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 43.1.52
Environment: Singleplayer

Mod name: Double doors
Mod version: [[Forge & Fabric] 1.19.2-4.3 | Double Doors](https://www.curseforge.com/minecraft/mc-mods/double-doors/files/4426053)

## **Description**
Double doors open and close instantly with a single click.

**Comment by ricksouth** [comment]
Do you have another mod that has the double door functionality?

**Comment by Herobattler** [comment]
This is the only mod modifying the function of doors

**Comment by ricksouth** [comment]
Could you test if it still does it with only Double Doors (and Collective)? Since I can't replicate the issue myself.

**Comment by Herobattler** [comment]
Its inconsistent, sometimes it does it during testing and sometimes it works fine. Iam pretty sure it startet to break after the update who "fixed it" It does malfunction when the game is slowing down (lots of entities spawned)

**Comment by Mysterious-thingy97** [comment]
i have the same issue, i thought i may add it is just the doors. fence gates and trapdoors do function normally.

**Comment by ricksouth** [comment]
I can't seem to replicate it. I'll try to do some more research, but please let me know if you've found a way to make it show.

![ezgif-3-5ba6da18fc](https://user-images.githubusercontent.com/38502394/224538565-367b4284-18a6-47b4-946e-a542b659e2e8.gif)

**Comment by ricksouth** [comment]
I've just uploaded version 4.4 which is an attempt to fix the issue. Could you see if that fixes the problem?

https://www.curseforge.com/minecraft/mc-mods/double-doors/files

**Comment by Mysterious-thingy97** [comment]
I've sent an email with a video of the issue

**Comment by ricksouth** [comment]
> I've sent an email with a video of the issue

I appreciate it, but don't really want to open the file due to safety reasons. Could you upload it to an unlisted video on youtube possibly?

**Comment by Mysterious-thingy97** [comment]
![videotogif_2023 03 12_13 38 56](https://user-images.githubusercontent.com/30652888/224545226-49c8e0e1-9221-42e3-a82e-72822e064a96.gif)

I've adder a GIF here if that's okay, you just have to trust me I'm not spamming the door since you can't hear it open and close with one click

**Comment by ricksouth** [comment]
Thanks! Hmm. Which Minecraft/Forge/Fabric etc versions are you on?

**Comment by Mysterious-thingy97** [comment]
Minecraft 1.19.2, forge version 43.2.0 

I have macaws doors and fence gates, removed them temporarily but it still stays.

I have an unlisted video aswell as I experimented a bit more and came across some weird stuff. Is there a way I can send it to you personally?

**Comment by ricksouth** [comment]
Sure, feel free to DM me on Discord:
Rick | Natamus#7863

**Comment by ricksouth** [comment]
I still can't replicate it locally, which makes this a difficult fix on my end, but I've just uploaded version 4.5 which attempts to fix the issue. Could you give it a try?

https://www.curseforge.com/minecraft/mc-mods/double-doors/files

**Comment by Herobattler** [comment]
Still broken for me on this latest patch

**Comment by Marius-jj** [comment]
I had the same problem, but after disabling Quark double doors function, it is now working as normal. Maybe you have Quark installed?

**Comment by EightBitBBQ** [comment]
@Herobattler Did you try the suggestion Marius suggested?

**Comment by ricksouth** [comment]
Yes I think it's Quark in this case. Thanks for giving the mod a try though!
