### ISSUE TITLE
HealingSoup removes hearts from Scaling Health mod

### ISSUE THREAD

**Issue by 5stigma** [ricksouth/serilum-mc-mods#1666]
## **Information**
Minecraft version: 1.18.2
Modloader: Forge
Forge version: 40.2.0  
Environment: Singleplayer / Multiplayer

Mod name: Mod Healing soup
Mod version: LAST

 **Description**
HealingSoup removes hearts from Scaling Health mod

1- heat the soup
2- extra hearts removed

If available.

**Comment by ricksouth** [comment]
Thank you for opening the issue. This has been fixed in version 4.9 of Healing Soup. Apologies it took so long for me to get to.

https://curseforge.com/minecraft/mc-mods/healing-soup/files
