### ISSUE TITLE
Double Iron doors don't open together when powered from above

### ISSUE THREAD

**Issue by JumperREDACTED** [ricksouth/serilum-mc-mods#1667]
## **Information**
Minecraft version: 1.19.3
Modloader: Fabric
Fabric loader version: 0.14.14
Environment: Multiplayer

Mod name: double doors
Mod version: 4.5

![image](https://user-images.githubusercontent.com/83337894/225098388-feb0df4a-83ee-46d8-96ad-86703fe866dd.png)

If you press any of the buttons on the sides, both doors open. 
If you press one of the buttons above, only one door opens.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 5.0 of Double Doors.

https://curseforge.com/minecraft/mc-mods/double-doors/files
