### ISSUE TITLE
Placeable Blaze Rods don't show the end rod particle animation

### ISSUE THREAD

**Issue by Goldenrevolver** [ricksouth/serilum-mc-mods#1672]
## **Information**
Minecraft version: 1.19.2 / 1.19.4
Modloader: both Fabric and Forge
Forge version: 43.2.0 (latest recommended)
Fabric loader version: 0.14.17 (latest recommended)
Environment: Singleplayer

Mod name: Placeable Blaze Rods
Mod version: 3.0 / 2.4

## **Description**
The end rod particle animation shown in [https://github.com/ricksouth/serilum-mc-mods/raw/master/cdn/placeable-blaze-rods/b.gif](url), added by BlazeRodBlock.animateTick in [https://github.com/ricksouth/serilum-mc-mod-sources/blob/main/sources/Placeable%20Blaze%20Rods/1.19.2/Common/src/main/java/com/natamus/placeableblazerods/blocks/BlazeRodBlock.java](url) does not show up at all for me.

All tests were done on a minimal setup using ONLY Collective and Placeable Blaze Rods (and Fabric API on Fabric) in a new world in the overworld.

I tested:
- 1.19.2 Fabric, mod 3.0, collective 6.53 (latest)
- 1.19.4 Fabric, mod 3.0, collective 6.53 (latest)
- 1.19.2 Forge, mod 3.0, collective 6.53 (latest)
- 1.19.2. Fabric mod 2.4 with Collective 5.22 (last 5.X version, as required to start)

No sodium, optifine, or resource/ data packs or anything else installed.

Opening the BlazeRodBlock class file in a decompiler (solely for the purpose of debugging) shows that the animateTick method signature exists, so it wasn't accidentally deleted from the build. Does it maybe need an override flag? I've seen those for some animateTick methods in other mods, but I'm new to writing minecraft mods.

Is there another dependency for the animation that I can't see in the code or is it maybe transparent?

All other features of the mod work (from looking at the code, the missing placement animation or missing sound effect seems intended).

If you need any more information let me know. Low priority issue of course. Thank you.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 3.1 of Placeable Blaze Rods.

https://www.curseforge.com/minecraft/mc-mods/placeable-blaze-rods/files
