### ISSUE TITLE
TVE 1.19.4 is Launching 1.19.3 Client

### ISSUE THREAD

**Issue by ShadowX116** [ricksouth/serilum-mc-mods#1673]
Minecraft version: 1.19.3/1.19.4
Modloader: Forge
Forge version: 1.19.4-45.0.9 
Environment: Multiplayer

Mod name: The Vanilla Experience 
Mod version: 6.8 

Myself, my brother and a friend updated our TVE server from pack version 6.5 (1.19.3) to 6.8 (1.19.4) and ported our world over. 
Everything was fine, though we quickly realized something was wrong when we couldn't pick up items not dropped by us. Ex. If I dropped a bread loaf, only I could pick it up. I went looking for similar bugs and attempted the player.dat nuke, which did not work. 

We then tried backing up the world folder and generating a new one. Same issue. As I was looking over my brother's (host) files, I spotted his client being marked as 1.19.3 despite having updated to a new profile. Lo and behold, my client was also loading marked as a 1.19.3 client. Is there anything we can do on our end to fix this without reverting versions? It's not the best idea to join a server with an outdated client, but I'm surprised we didn't run into more issues than just that. I'd also like to avoid reverting because the 1.19.4 patch supposedly fixes the horse breeding system in vanilla.

**Comment by ricksouth** [comment]
Apologies for the late response I'm not sure why this happened, sounds like a problem on CurseForge's end. I've uploaded version 6.9, which hopefully fixes it. Thanks for giving the modpack a try!
