### ISSUE TITLE
Double Messages

### ISSUE THREAD

**Issue by wincowski** [ricksouth/serilum-mc-mods#1674]
## **Information**
Minecraft version: 19.2
Modloader: Forge 
Forge version: 43.2.0
Environment: Singleplayer / Multiplayer

Mod name: Areas
Mod version: 1.19.2-4.3

## **Description**
The messages on the screen show twice, I dont understant why. There is no crash but I will share debug and latest log file, pls help

## **Crash report**
[<script src="https://gist.github.com/wincowski/59270be01d7145eb88cb07ae53ec8133.js"></script>](https://gist.github.com/wincowski/59270be01d7145eb88cb07ae53ec8133)
[debug.log](https://github.com/ricksouth/serilum-mc-mods/files/11007384/debug.log)
[latest.log](https://github.com/ricksouth/serilum-mc-mods/files/11007385/latest.log)

If available.
![2023-03-18_06 31 52](https://user-images.githubusercontent.com/120783071/226082569-8c5cda4b-f3bf-4fb2-9019-37082d497359.png)

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 5.0 of Areas, alongside other bug fixes and QoL features. Apologies it took so long for me to get to.

https://www.curseforge.com/minecraft/mc-mods/areas/files
