### ISSUE TITLE
Compact Help Command crashes upon launching

### ISSUE THREAD

**Issue by Telezhka-the-First** [ricksouth/serilum-mc-mods#1677]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 43.2.7
Environment: Launching (Singleplayer / Multiplayer)

Mod name: Compact Help Command
Mod version: 1.19.2-2.1

## **Description**
Crashes upon launching the game. If this mod is disabled, everything works fine.

## **Crash report**
[console.log](https://github.com/ricksouth/serilum-mc-mods/files/11024583/console.log)

**Comment by Telezhka-the-First** [comment]
Notably, 1.19.2-2.0 version works as intended.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 2.2 of Compact Help Command.

https://curseforge.com/minecraft/mc-mods/compact-help-command/files
