### ISSUE TITLE
Areas HUD and chat doesnt show up

### ISSUE THREAD

**Issue by Phoebius96** [ricksouth/serilum-mc-mods#1683]
## **Information**
Minecraft version: 1.19.2
Modloader: Fabric
Fabric loader version: 0.14.14
Environment: Singleplayer

Mod name: Areas
Mod version: areas-1.19.2-4.3.jar

Hey! Areas don't show up either on HUD nor in Chat.
Got them both enabled. (they showed up twice since install with current mod lsit, not ever after)

All the mods in using attached in screenshot
![Névtelen](https://user-images.githubusercontent.com/89929296/227264031-c118d9de-94eb-4947-a644-b4ce3e4474ef.png)

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 5.0 of Areas, alongside other bug fixes and QoL features.

https://www.curseforge.com/minecraft/mc-mods/areas/files
