### ISSUE TITLE
Collective / No hostiles around campfire error when launching

### ISSUE THREAD

**Issue by dollvader** [ricksouth/serilum-mc-mods#1685]
## **Information**
Minecraft version: 1.19.4
Modloader: Forge
Forge version: 45.0.23
Environment: Singleplayer

Mod name: Collective and Nohostilesaroundcampfire
Mod version: collective-1.19.4-6.53.jar
nohostilesaroundcampfire-1.19.4-5.4.jar

## **Description**
Crashes when launching. I have several Serilum mods installed but Collective and Nohostilesaroundcampfire are throwing the same errors.

## **Crash report**
_(Please either drag the file directly here, or use https://gist.github.com/ to prevent the paste from expiring)_

If available.
[crash-2023-03-23_16.26.42-fml.txt](https://github.com/ricksouth/serilum-mc-mods/files/11056439/crash-2023-03-23_16.26.42-fml.txt)

**Comment by ricksouth** [comment]
Yep, this is due to the changes made to the SpawnEvent in 45.0.23. I've updated almost all mods, just one left :)

**Comment by ricksouth** [comment]
Fixed in Collective version 6.54: https://www.curseforge.com/minecraft/mc-mods/collective/files
And No Hostiles Around Campfire version 5.5: https://www.curseforge.com/minecraft/mc-mods/no-hostiles-around-campfire/files

Thanks for giving the mods a try!
