### ISSUE TITLE
Cycle Paintings creating duplicate painting items

### ISSUE THREAD

**Issue by Bane-Ross** [ricksouth/serilum-mc-mods#1688]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge 
Forge version: 43.2.6
Environment: Singleplayer 

Mod name: Cycle Paintings
Mod version: 3.2

## **Description**

A few seconds after I cycle through the paintings, a certain amount of paintings just start popping out of the walls, possibly related to the number of times I've cycled through images. It's not caused any crashes, but it's kind of an unconventional way to get duplicate paintings. The only other painting related mods I'm using are DarkPaintings (https://www.curseforge.com/minecraft/mc-mods/dark-paintings) and minecraft style paintings (https://beta.curseforge.com/minecraft/mc-mods/minecraft-style-paintings).

**Comment by ricksouth** [comment]
I can't seem to replicate this. Does it still happen without other mods installed?

**Comment by Bane-Ross** [comment]
Apologies, I have since moved on to Minecraft 1.20.1 partly due to other of my favorite mods not working well on 1.19.2.

I deleted my instance of 1.19.2, and I can't remember all the mods I used for it, so I don't think I can reconstruct my problem for you anymore.

**Comment by ricksouth** [comment]
No problem, thank you for the response. I'll close it for now, but will check again if someone else encounters it.
