### ISSUE TITLE
Crash on startup with Collective and GTCEu. Possible Mixin conflict

### ISSUE THREAD

**Issue by ChromaPIE** [ricksouth/serilum-mc-mods#1689]
## **Information**
Minecraft version: 1.19.2
Modloader: Fabric (Maybe also on Forge)
Fabric loader version: 0.14.18
Environment: Not related

Related Serilum mod: Collective

Mod name: GregTech Community Edition Unofficial
Mod version: All

## **Description**
Game crashes on startup. Probably a mixin injection incompat.

## **Crash report**
See https://github.com/GregTechCEu/GregTechCEu-1.19/issues/8. You can also check the source code there since it's yet to be release on any sites.
It's more likely to be mainly on their side, but I'm posting it here just in case.

**Comment by ricksouth** [comment]
This is not something I can fix on my end I don't think. Otherwise I'd need a log file as well. If the authors of that mod need me to change anything I can though. Thanks for the suggestion.
