### ISSUE TITLE
Make Zombie Horse and Skeleton Horse spawning rate configurable

### ISSUE THREAD

**Issue by RobinRMC** [ricksouth/serilum-mc-mods#1698]
## **Information**
Minecraft version: 1.12.2
Modloader: Forge

Mod name: Zombie Horse Spawn & Skeleton Horse Spawn

## **Feature description**
Zombie horses and skeleton horses spawn way to often.

Sometimes I decide to kill all zombie/skeleton horses and the server responds with a message stating that around 800-1000 entities have been killed.

Please make the spawn chance/rate configurable.

**Comment by ricksouth** [comment]
Hi, thanks for giving the mod a try! The spawn rates are available in the config file. Please check the description for more information on how to edit it.

**Comment by RobinRMC** [comment]
This is not true. The only chance that is configurable is the chance a zombie or skeleton spawns on top of a horse.

**Comment by ricksouth** [comment]
The horses are only able to spawn whenever a zombie/skeleton spawns. The config changes how often a horse is added. So it does alter the amount of horses spawned.

**Comment by James103** [comment]
Do the zombie/skeleton horses despawn if far enough away from a player? If not, that may be causing the accumulation of zombie and skeleton horses over time.

**Comment by RobinRMC** [comment]
Oh, then it works a lot different in my server then it should be. My whole world is filled up with zombie and skeleton horses, with sometimes a zombie or skeleton on top of it.
