### ISSUE TITLE
(Giant Spawn) Giants wearing helmets will still burn in daylight

### ISSUE THREAD

**Issue by riley-9054** [ricksouth/serilum-mc-mods#1703]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 43.1.43
Environment: Singleplayer

Mod name: Giant Spawn
Mod version: 4.5

## **Description**
A giant wearing full leather armor burst into flames when the sun started rising.
![image](https://user-images.githubusercontent.com/117400609/230213556-68ba699b-77e5-4fd4-8074-6c35f0d7a7a0.png)

**Comment by James103** [comment]
Expected result: the giant's helmet should take durability damage when exposed to the sun (using the same rules as vanilla zombies). Only if the helmet breaks should the giant itself burst into flames.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 4.6 of Giant Spawn.

https://curseforge.com/minecraft/mc-mods/giant-spawn/files
