### ISSUE TITLE
Space between entering message and area name is merged after changing content of entering message.

### ISSUE THREAD

**Issue by KaroYT** [ricksouth/serilum-mc-mods#1708]
## **Information**
Minecraft version: 1.19.3
Modloader: Fabric
Fabric loader version: 0.14.18
Environment: Singleplayer

Mod name: Areas
Mod version: 4.3

## **Description**
As title says, when I change content of entering message, space between that message and area name disappears. There's no need to change default message, just replace letter with the same typed by me, and it merges. How to fix that?
Video record of bug:
https://youtu.be/NIsVoCrg8DM

**Comment by KaroYT** [comment]
I've found a workaround for this. Change message in config file, save it, in game you need to enter in mod config, do not make any change and click "done". This way space isn't missing.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 6.62 of Collective. Areas doesn't need an update, but I've also just now released one with lots of bug fixes and QoL features. :)

https://www.curseforge.com/minecraft/mc-mods/collective/files
