### ISSUE TITLE
TreeHarvester Incompatibility with Farmer's Respite Causing Server Crashes

### ISSUE THREAD

**Issue by Relaxing9** [ricksouth/serilum-mc-mods#1710]
## **Information**
Minecraft version: 1.18.2
Modloader: Forge
Forge version: 40.2.1
Environment: Multiplayer

Mod name: TreeHarvester
Mod version: treeharvester-1.18.2-8.0.jar

## **Description**
Seems to be incompatible with Farmer's Respite and every time Tree Harvester tries to change the state of this item in the **Nether**. It causes a server crash. And I got 7 of them...

## **Crash report**
[https://gist.github.com/Relaxing9/01e22cee6e94c67e1f4cae6120ef72c2](https://gist.github.com/Relaxing9/01e22cee6e94c67e1f4cae6120ef72c2)

**Comment by Relaxing9** [comment]
Tried to disable

```json
"enableNetherTrees": false,
```

But crashes still occur:
[crash-2023-04-09_03.20.23-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/11184994/crash-2023-04-09_03.20.23-server.txt)
[crash-2023-04-09_12.11.29-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/11186630/crash-2023-04-09_12.11.29-server.txt)
[crash-2023-04-09_12.39.40-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/11186631/crash-2023-04-09_12.39.40-server.txt)
[crash-2023-04-09_12.50.13-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/11186632/crash-2023-04-09_12.50.13-server.txt)
[crash-2023-04-09_19.39.21-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/11186633/crash-2023-04-09_19.39.21-server.txt)

**Comment by Relaxing9** [comment]
I have made the hard decision and had to remove TreeHarvester (and Collective) from my server because of these constant crashes. It has stopped crashing.

I have asked the Farmer's Respite dev just to double check if it was a problem on their end and I quote:
> 99% chance it's a problem on their end. It looks like they're trying to set the block but don't check the blocks max value correctly.  I would contact their dev

Until there's something done about this mod will have to keep it away from my server. :(

**Comment by Relaxing9** [comment]
Update:
I saw multiple people with this crash in the Farmer's Respite Discord and one user recommended a workaround to keep TreeHarvester on the server and I have tried that workaround and TreeHarvester hasn't crashed the server yet (and people have been in the nether). This option is the following:
```json
"automaticallyFindBottomBlock"
```
Setting this option to false prevents the mod from trying to find the bottom log when generating new nether chunks which _may or may not_ results in the aforementioned server crashes. Setting this option to false _may or may not_ let people explore the nether while still having TreeHarvester functionality. So based on all that was presented I would say the above setting _might be_ broken in finding the "blocks max value correctly" if set to true.

**Comment by Relaxing9** [comment]
We aren't getting crashes as frequently as before but still are getting crashes ever since TreeHarvester has been added back to the server. Is a bit of progress with that config option but doesn't completely solve the issue. There still seems to be a problem with TreeHarvester:

[crash-2023-04-12_20.40.51-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/11223648/crash-2023-04-12_20.40.51-server.txt)
[crash-2023-04-13_03.58.17-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/11223652/crash-2023-04-13_03.58.17-server.txt)

**Comment by Sshmoob** [comment]
For now, you can downgrade Tree Harvester to 7.4, but it would still be nice to go to the Nether with the otherwise less buggy 8.0 version of the mod.

**Comment by EightBitBBQ** [comment]
Thank you all for trying out multiple things.
Also thanks for your patience.  At this moment the author of the modpack is working on his new home IRL.
Hopefully he will be back as soon as possible. He knows that Treeharvester has multiple issues.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 8.1 of Tree Harvester.

https://curseforge.com/minecraft/mc-mods/tree-harvester
