### ISSUE TITLE
Incompatibility Crash with Ars Nouveau/Supplementaries

### ISSUE THREAD

**Issue by InteJason** [ricksouth/serilum-mc-mods#1712]
## **Information**
Minecraft version: 1.18.2
Modloader: Forge
Forge version: 40.2.1
Environment: Singleplayer

Mod name: Pumpkillager's Quest
Mod version: 1.18.2-3.2

## **Description**
When the Ars Nouveau spell "break" hits the skull pile from Supplementaries, the game crashes. The crash report mentions Pumpkillager's Quest. When Pumpkillager's Quest is removed, the crash doesn't occur again.

## **Crash report**
https://pastebin.com/ATJaramu

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 3.7 of Pumpkillager's Quest.

https://curseforge.com/minecraft/mc-mods/pumpkillagers-quest/files
