### ISSUE TITLE
Tree Harvester Crashes Server When Players Explore The Nether (Forge, 1.18.2)

### ISSUE THREAD

**Issue by PHANTOMk91** [ricksouth/serilum-mc-mods#1714]
## **Information**
Minecraft version: 1.18.2
Modloader: **Forge**
Forge version: 40.2.0
Environment: Multiplayer Server

Mod name: Tree Harvester
Mod version: treeharvester-1.18.2-8.0

## **Description**
Hey! We recently opened up the nether on our server, and this mod has been causing several server crashes whenever someone explores the nether. These crashes do not happen necessarily when a player uses the mod, and happen at random between 1-15 minutes of a player loading new nether chunks. This problem has made the server unplayable and we have had to remove the mod from our modpack, however, now players are complaining and want it back. 
We already asked the devs for Farmers Respite for help, and they told us that Tree Harvester is "99% the cause of your crashes". Any help would be greatly appreciated. 

## **Crash report**
[crash-2023-04-07_17.21.14-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/11205035/crash-2023-04-07_17.21.14-server.txt)
[crash-2023-04-07_17.31.29-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/11205038/crash-2023-04-07_17.31.29-server.txt)

**Comment by Sshmoob** [comment]
This is the same issue as #1710. Downgrading Tree Harvester to 7.4 fixes the issue, but it would be nice if we could continue using the latest version of the mod and still go to the Nether.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 8.1 of Tree Harvester.

https://curseforge.com/minecraft/mc-mods/tree-harvester
