### ISSUE TITLE
[1.19.2 | Multiplayer] Double doors & Stack refill not working

### ISSUE THREAD

**Issue by Nestaan** [ricksouth/serilum-mc-mods#1715]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 43.2.0+ 
Environment: Multiplayer

Mod name: Double Doors
Mod version: 4.5

Mod name: Stack Refill
Mod version: 4.0
## **Description**
Hej!

When playing in singleplayer mode, everything goes well: doors open in pairs, and the stacks fill up automatically. However, when I play in multiplayer mode, bugs appear. The doors only open one by one, and when a stack is automatically filled, it appears for half a second, then disappears. The only way to get it back is to click on the empty slot it leaves in the inventory.

I also want to say that a friend of mine, does not have this problem. He has the same versions of the mods, the only difference is that he plays on Windows and I play on Macos.

Here is my mods list if this can help : 
[Iceberg [Forge] (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/iceberg)
[Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
[Mob Plaques (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/mob-plaques)
[TerraBlender (Forge) (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/terrablender)
[SuperMartijn642's Core Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib)
[Architectury API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[Xaero's World Map (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map)
[Immersive Portals (for Forge) (by qouteall)](https://www.curseforge.com/minecraft/mc-mods/immersive-portals-for-forge)
[SimpleCore API (by skrallexy)](https://www.curseforge.com/minecraft/mc-mods/simplecore-api)
[Comforts (Fabric/Forge/Quilt) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/comforts)
[AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)
[libIPN (by mirinimi)](https://www.curseforge.com/minecraft/mc-mods/libipn)
[Equipment Compare [Forge] (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/equipment-compare)
[Small Ships [Fabric & Forge] (by talhanation)](https://www.curseforge.com/minecraft/mc-mods/small-ships)
[Winthor Medieval (by Studio_Winthor)](https://www.curseforge.com/minecraft/texture-packs/winthor-medieval-texture-pack-v2-6-wip-mc-1-14)
[Light Overlay (Rift/Forge/Fabric) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/light-overlay)
[Automatic Tool Swap (by MelanX)](https://www.curseforge.com/minecraft/mc-mods/automatic-tool-swap)
[Collective (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/collective)
[SimpleOres (by skrallexy)](https://www.curseforge.com/minecraft/mc-mods/simpleores)
[Balm (Forge Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/balm)
[Serene Seasons (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/serene-seasons)
[Double Slabs (by CJMinecraft01)](https://www.curseforge.com/minecraft/mc-mods/double-slabs)
[Kotlin for Forge (by thedarkcolour)](https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge)
[Cloth Config API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[Double Doors (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/double-doors)
[Xaero's Minimap (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap)
[Biomes O' Plenty (by Forstride)](https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty)
[Neat (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/neat)
[Storage Drawers (by Texelsaur)](https://www.curseforge.com/minecraft/mc-mods/storage-drawers)
[BetterNether (by Quiqueck)](https://www.curseforge.com/minecraft/mc-mods/betternether)
[Prism [Forge] (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/prism-lib)
[Inventory Essentials (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/inventory-essentials)
[Auto Third Person (by quat1024)](https://www.curseforge.com/minecraft/mc-mods/auto-third-person)
[BetterEnd (by Quiqueck)](https://www.curseforge.com/minecraft/mc-mods/betterend)
[Stack Refill (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/stack-refill)
[Puzzles Lib [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/puzzles-lib)
[Dynamic Lights (by atomicstrykergrumpy)](https://www.curseforge.com/minecraft/mc-mods/dynamic-lights)
[Replanter (by Areuthreateningme)](https://www.curseforge.com/minecraft/mc-mods/replanter)
[Legendary Tooltips [Forge] (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/legendary-tooltips)

Thanks in advance for your help !

**Comment by ricksouth** [comment]
I unfortunately don't own an Apple computer, and am unsure how to tackle this issue. It might be more related to Forge? Sorry I can't help with this. Appreciate you giving the mods a try though!
