### ISSUE TITLE
Mobs spawn near the campfire in forge 45.0.23+

### ISSUE THREAD

**Issue by Dizzy-Dizzy** [ricksouth/serilum-mc-mods#1716]
## **Information**
Minecraft version: 1.19.4
Modloader: Forge
Forge version: 45.0.40; 45.0.41; 45.0.43;
Environment: Singleplayer

Mod name: No Hostiles Around Campfire
Mod version: 1.19.4-5.5

## **Description**
Good morning! On a bunch of the latest version of your mod and forge 45.0.23+, mobs will spawn near the fire. I have tried different versions of your mod and versions of forge and have found that this problem appears on version 5.5 of the mod and forge 45.0.23 or later. If you use mod version 5.4 and forge 45.0.22 everything works without problems.

**Comment by ricksouth** [comment]
Thanks for opening the issue! This has been fixed in version 5.6 of No Hostiles Around Campfire.

https://www.curseforge.com/minecraft/mc-mods/no-hostiles-around-campfire/files
