### ISSUE TITLE
Beautified Chat unable to see massage in console

### ISSUE THREAD

**Issue by Rxstar-sq** [ricksouth/serilum-mc-mods#1717]
## **Information**
Minecraft version: 1.19.4
Modloader: Fabric
Fabric loader version: 0.14.19
Environment: Multiplayer

Mod name: Beautified Chat [Server]
Mod version: 2.2

## **Description**
It's a very good mod, and the in-game effects are great. But the thing is that generally every chat message from a player can be seen in the server console and logs.
However, when I use this mod, all messages sent by the player are not visible in the console/log (except for commands that start with slash).
The problem is that I can't check the chat messages sent by players within the server and they can't use the MCDreforge command if necessary (such commands usually start with !! instead of starting with a slash)
So the missing feature is messages are visible in server console (this feature was fixed in the original version 1.6, but now it's back in version 2.2)

## **Crash report**
_(Please either drag the file directly here, or use https://gist.github.com/ to prevent the paste from expiring)_

If available.

**Comment by ricksouth** [comment]
Thanks for opening the issue. This has been fixed in version 2.5 of Beautified Chat Server. Apologies it took so long for me to get to.

https://curseforge.com/minecraft/mc-mods/beautified-chat-server/files
