### ISSUE TITLE
The Vanilla Experience - Players cannot pick up items thrown by other entities - Fixed in Forge

### ISSUE THREAD

**Issue by TigerWalts** [ricksouth/serilum-mc-mods#1720]
## **Information**
Minecraft version: `1.19.4`
Modloader: `Forge`
Forge version: `45.0.9`
Environment: `Singleplayer` / `Multiplayer`

Modpack name: `The Vanilla Experience | TVE`
Mod version: `6.8`

## **Description**
`Forge-1.19.4-45.0.9` has a bug that prevents players picking up items thrown by other entities. i.e. Other players, Allays & Piglins.

This bug was fixed in `Forge-1.19.4-45.0.20`:

- https://github.com/MinecraftForge/MinecraftForge/issues/9412

**Comment by EightBitBBQ** [comment]
And i thought it was me.. Nice find.
I dont know if the code of the current mods is working with 45.0.20 or higher.
But can you try to update the Forge version?

**Comment by TigerWalts** [comment]
Sorry, I missed the notification for this.

Yes, the modpack worked with Forge-1.19.4-45.0.20.

**Comment by EightBitBBQ** [comment]
For now you can go with that. Since it has no impact on the rest of mods. 

We will have to wait untill the owner is back. Then he will have some backlog.
Hopefully will be fixed asap

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the modpack a try! The Vanilla Experience 6.9 has the new Forge update.
