### ISSUE TITLE
[1.19.2 StarterKit] StarterKit not spawning items in server, works fine in singleplayer

### ISSUE THREAD

**Issue by bixyfroot** [ricksouth/serilum-mc-mods#1722]
Minecraft version: 1.19.2
Modloader: Forge 
Forge version: 43.2.6
Environment: Multiplayer

Mod name: Starter Kit
Mod version: starterkit-1.19.2-5.2

## **Description**
I've set the Starter Kit and it works perfectly fine in Singleplayer (tested with multiple players and world) but new players do not spawn with it in a Multiplayer server (all players who first spawned did not received anything). The server configs are the exact same on the client and the server so I can't pinpoint what is wrong.

Singleplayer: Not sure if its worth noting but MCA Reborn still forcespawns its book despite the config option "addExistingItemsAfterKitSet" being set to false. Other mod's book was successfully removed.

May I also suggest having an extra command along the lines of /starterkit give player available? This would help immensely if starterkits are not being set for any reason so admins can simply run a command to spawn those in for players. 

[latest.log](https://github.com/ricksouth/serilum-mc-mods/files/11238341/latest.log)

**Comment by HaXrDEV** [comment]
Having the same issue in Fabric 1.18.2.  #1735 
(Didn't notice someone else had reported this issue already)

**Comment by ricksouth** [comment]
Thanks for giving the mod a try! I can't seem to replicate this. It might be another mod that causes an incompatibility but I'm not sure. Does it work without other mods installed?

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 6.0 of Starter Kit, alongside many new features! See the description for more details:

https://curseforge.com/minecraft/mc-mods/starter-kit
