### ISSUE TITLE
If Compact Help can't be used in the server console, how else will I be able to view all commands?

### ISSUE THREAD

**Issue by KateReller** [ricksouth/serilum-mc-mods#1726]
## **Information**
Minecraft version: 1.19.4
Modloader: Fabric
Fabric loader version: 0.14.19
Environment: Multiplayer

Mod name: Compact Help
Mod version: 2.1

## **Question**
So Compact Help won't work on a server console, spitting out, "A player is required to run this command here". This feels intentional so I have to ask, how else can I view all the commands without the `help` command?

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 2.3 of Compact Help Command. You can use it from the server console.

https://curseforge.com/minecraft/mc-mods/compact-help-command/files
