### ISSUE TITLE
Beautiful Chat Client/Server (1.19.2) not working with Discord bot & Bisect Chat

### ISSUE THREAD

**Issue by gamerpotion** [ricksouth/serilum-mc-mods#1727]
Hi, I recently installed Beautiful Chat client and server editions on my modpack - https://www.curseforge.com/minecraft/modpacks/darkrpg  Fabric 1.19.2 all latest versions of mods installed.

We also use Discord bot which shows in-game chat on discord (this mod - https://www.curseforge.com/minecraft/mc-mods/simple-discord-link-bot-forge-fabric-spigot)  @hypherionmc fyi also

After installing the chat mods, I can no longer see any chats in the discord server and interestingly even the Bisect chat section in my server control panel.

Is there a way to fix this?

![](https://media.discordapp.net/attachments/1003407908463190073/1098260216862216232/image.png)

![](https://media.discordapp.net/attachments/1003407908463190073/1098263735774220298/image.png)

![](https://media.discordapp.net/attachments/1003407908463190073/1098263736134926416/image.png)

**Comment by gamerpotion** [comment]
closing as mod has been removed now.

**Comment by hypherionmc** [comment]
Just adding this for anyone else that happen to find this in the future, we do now support Beautified Chat Server in newer versions :)
