### ISSUE TITLE
Chat text spam when volume is changed

### ISSUE THREAD

**Issue by renandadalte** [ricksouth/serilum-mc-mods#1728]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 46.2.6
Environment: Singleplayer

Mod name: Omega Mute
Mod version: 3.0

## **Description**
I noticed that when I change my volume, a text message is printed in my chat:

"Reloading Omega Mute Soundmap File Now. New soundmap changes sucessfully loaded."

That happens when I use my keyboard shortcut for volume up and down (FN + F2 and FN + F3), this happens with my mouse shortcut for volume up and down too (I use buttons G7 and G8 from G502 X). When changing volume using windows volume slider it doesn't happen.

## **Crash report**
No crash at all, just chat spam.

Thanks in advance if you find a fix for this!

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 4.0 of Omega Mute. I've removed the hotkey entirely, as the /omegamute reload command can be used instead.

https://curseforge.com/minecraft/mc-mods/omega-mute/files
