### ISSUE TITLE
Settings don't work.

### ISSUE THREAD

**Issue by Chris-Creates** [ricksouth/serilum-mc-mods#1730]
## **Information**
Minecraft version: 1.19.2
Modloader: Fabric
Fabric loader version: idk the latest for 1.19.2
Environment: Singleplayer

Mod name: Tree Harvester
Mod version: latest for 1.19.2 fabric

## **Description**
The settings for only harvest while sneaking and find bottom block don't seem to work properly. It harvests entire tree whether im sneaking or not, no matter the setting. And same with find bottom block, even if I set it to false it still harvests the entire tree.

Tested with no other mods installed.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 8.1 of Tree Harvester.

https://curseforge.com/minecraft/mc-mods/tree-harvester
