### ISSUE TITLE
Can't get 'Starter Kit' to work in multiplayer on 1.18.2

### ISSUE THREAD

**Issue by HaXrDEV** [ricksouth/serilum-mc-mods#1735]
## **Information**
Minecraft version: 1.18.2
Modloader: Fabric
Fabric loader version: 0.14.19
Environment: Multiplayer

Mod name: Starter Kit
Mod version: 5.2

## **Description**
Can't get 'Starter Kit' to work in multiplayer on 1.18.2 with the modpack i am putting together. In singleplayer is works completely fine however. 
There is no crashing or any mentions of Starter Kit doing anything at all for that matter (except one line when the mod loads). 
It also doesn't matter which items I set it to. Setting it to just give a wool block gets the same result.
I should also mention that I use the "/starterkit set" command to create the starterkit.txt file.
Any known incompatibilities I should be aware of?

**Comment by ricksouth** [comment]
Thanks for giving the mod a try! I can't seem to replicate this. It might be another mod that causes an incompatibility but I'm not sure. Does it work without other mods installed?

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 6.0 of Starter Kit, alongside many new features! See the description for more details:

https://curseforge.com/minecraft/mc-mods/starter-kit
