### ISSUE TITLE
Server Crashes when 'infinitetrades' mod is in the mods folder

### ISSUE THREAD

**Issue by SkubiDupapa** [ricksouth/serilum-mc-mods#1740]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 43.2.8
Environment: Multiplayer

Mod name: Infiniter trading
Mod version: [Forge & Fabric] 1.19.2-4.0 

## **Description**
Whenever I try to start the server with the infinite trading mod it crashes and it says something with the version range 4.32 

## **Crash report**
_(Please either drag the file directly here, or use https://gist.github.com/ to prevent the paste from expiring)_

If available.

**Comment by James103** [comment]
Do you have the server logs from the crash? If so, can you please post them here?

**Comment by ricksouth** [comment]
Please use the latest version of Collective.
