### ISSUE TITLE
treeHarvestWithoutSneak not working on latest version for both Collective and Tree Harvester 

### ISSUE THREAD

**Issue by RiskE80** [ricksouth/serilum-mc-mods#1741]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 43.2.8
Environment: Singleplayer

Mod name: Tree Harvester
Mod version: 8.0

treeHarvestWithoutSneak doesnt change anything true or false, sneak and no sneak both harvest entire tree

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 8.1 of Tree Harvester.

https://curseforge.com/minecraft/mc-mods/tree-harvester
