### ISSUE TITLE
Config reset of Automatic Doors

### ISSUE THREAD

**Issue by Telezhka-the-First** [ricksouth/serilum-mc-mods#1744]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 43.2.10
Environment: Singleplayer / Multiplayer

Mod name: Automatic Doors
Mod version: 1.19.2-4.4

## **Description**
Basically every time I start Minecraft the open time for this mod resets to the default 2500.

**Comment by ricksouth** [comment]
Confirmed working in the latest version. Thanks for giving the mod a try!
