### ISSUE TITLE
Catastrophic miscalculation - TreeHarverster

### ISSUE THREAD

**Issue by bvngee** [ricksouth/serilum-mc-mods#1750]
## **Information**
Minecraft version: 1.19.4
Modloader: Fabric
Fabric loader version: 0.14.19
Environment: Multiplayer

Mod name: Tree Harvester
Mod version: 8.0

## **Description**
I've loved this mod so far. But this afternoon when working on a building (made of wood) I seem to have come across a rare yet terrible case in which the algorithm that decides what blocks to break goes way overboard. It completely destroyed the building we were working on; I was above working on the roof (far behind my location in the screenshot below), and as I broke an already stripped warped log while shifting, the game froze for a second followed by almost all stripped logs in the entire building (on all sides of me, above and below) breaking into items. It seems to have only affected stripped logs, but it did so without any hesitance. I would estimate at least over 300-500+ were broken. I have one screenshot, but it is only after we started repairs.

![2023-05-06_16 04 27](https://user-images.githubusercontent.com/69218859/236651533-5db66ae8-efb9-4e3b-b5b7-3f433d58353a.png) *(this was after we had filled a lot back in)*
All of the stripped logs in the checkerboard pattern were removed, as well as the stripped dark oak pillars, the stripped mangrove logs in the hallway in front, and much much more.

(no crash report as there was no crash)

I wish I had more information to give. Thanks in advance for any help.

**Comment by ricksouth** [comment]
I'm sorry this happened, apologies. This has been fixed in version 8.1 of Tree Harvester, by ignoring logs that have been stripped.

https://curseforge.com/minecraft/mc-mods/tree-harvester
