### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by 1Saj** [ricksouth/serilum-mc-mods#1766]
## **Information**
Minecraft version:1.19.4
Modloader:  Fabric
Fabric loader version: 6.53
Environment: Singleplayer

Mod name: Easy Elytra Takeoff
Mod version: 1.19.4

## **Description**
i think the mod shoud update

## **Crash report**
https://cdn.discordapp.com/attachments/791623715896557592/1106241113347604540/image.png

If available.

**Comment by EightBitBBQ** [comment]
Did you only install Easy Elytra Takeoff?
Because the screenshot added is saying you need the Collective mod as well (Missing right now)
You can download it here: https://www.curseforge.com/minecraft/mc-mods/collective
Add this mod to the mods folder and try again
