### ISSUE TITLE
Frog head does not drop in 1.19.3

### ISSUE THREAD

**Issue by JDN233** [ricksouth/serilum-mc-mods#1770]
## **Information**
Minecraft version: 1.19.3
Modloader: Fabric
Fabric loader version: 0.14.19-1.19.3
Environment: Both Singleplayer and Multiplayer

Mod name: Just Mob Heads
Mod version: 1.19.3-7.1

## **Description**
For Multiplayer, on my server, I used mods such as Origins, simplehats, justmobheads, and justplayerheads. And when I try to collect a frog head today, it just won't drop, I have killed at least 100 with a drop rate of 0.1. After changing the drop rate to 1, it still won't drop for all types of frogs. But I can still use the /jmh command to get the frog head.

I use the same mods from my server in a single-player world and got 0 frog heads after killing thousands with a default drop rate. I then test all other mobs, and they all drop their heads. 

I thought it is just a mod incompatibility problem, so I try to sort it out in a single-player world. But the frog head still won't drop after I only use these mods: [collective-1.19.3-6.53.jar][fabric-api-0.76.1+1.19.3.jar][justmobheads-1.19.3-7.1.jar][malilib-fabric-1.19.3-0.14.0.jar][tweakeroo-fabric-1.19.3-0.15.0.jar]

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 7.2 of Just Mob Heads. Apologies for the time you spent hunting for the frog heads.

https://legacy.curseforge.com/minecraft/mc-mods/just-mob-heads/files
