### ISSUE TITLE
Incompatible with AdvancementPlaques

### ISSUE THREAD

**Issue by qznfbnj** [ricksouth/serilum-mc-mods#1773]
## **Information**
Minecraft version: 1.18.2
Modloader: Forge
Forge version: 40.2.1
Environment: Singleplayer

First mod name: Advancement Screenshot
First mod version: 4.1

Second mod name: AdvancementPlaques
Second mod version: 1.4.5.1

## **Description**
With the AdvancementPlaques mod installed, the Advancement Screenshot mod cannot take screenshot one second after an advancement be completed.
https://github.com/AHilyard/AdvancementPlaques/issues/25

**Comment by zeid0ne** [comment]
Same with fabric 1.20.1

Edit : related issue here https://github.com/AHilyard/AdvancementPlaques/issues/25

**Comment by ricksouth** [comment]
Looks like this was fixed on Advancement Plague's end: https://github.com/Serilum/.issue-tracker/issues/2312

Thanks for giving the mod a try!
