### ISSUE TITLE
[1.18.2] Passive Shield failed to load correctly

### ISSUE THREAD

**Issue by SheReyy** [ricksouth/serilum-mc-mods#1774]
## **Information**
Minecraft version: 1.18.2
Modloader: Forge
Forge version: 40.2.0
Environment: Singleplayer

Mod name: Passive Shield
Mod version: passiveshield_1.18.2-2.0.jar

## **Description**
Hey! This happened: After launching the game, it crashes with this error: Passive Shield (and QuickPaths) failed to load correctly. I can also open an issue for Quickpaths if needed. I'll leave just this one for now, as the log contains both of the errors.

## **Crash report**
[latest.log](https://github.com/ricksouth/serilum-mc-mods/files/11489806/latest.log)
[crash-2023-05-16_18.56.15-fml.txt](https://github.com/ricksouth/serilum-mc-mods/files/11489809/crash-2023-05-16_18.56.15-fml.txt)

If available.

**Comment by ricksouth** [comment]
Hi! Apologies for the late response. This is fixed by updating Passive Shield and Quick Paths to their latest version. You need the file that's for both Forge and Fabric
