### ISSUE TITLE
VillagerNames crashes when attempting to register

### ISSUE THREAD

**Issue by AdalynBlack** [ricksouth/serilum-mc-mods#1775]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 43.2.11
Environment: Launching

Mod name: Villager Names
Mod version: 4.3

## **Description**
Game crashes while launching with Villager Names installed

## **Crash report**
https://cdn.discordapp.com/attachments/883478770151985172/1108291582777630730/latest.log

Note: provided latest.log and not the crash log because the crash log reports a different mod as the issue, but VillagerNames appears to be the culprit. Removing VillagerNames fixes the issue. From my sleuthing, it seems that it is unable to import the register function from the collective, despite the collective being installed. All mods were installed and managed through Curseforge.

**Comment by ricksouth** [comment]
Hi! Apologies for the late response. This is fixed by updating Villager Names and Collective to their latest version. You need the file that's for both Forge and Fabric
