### ISSUE TITLE
Crash when cutting down trees

### ISSUE THREAD

**Issue by sanguinecypress** [ricksouth/serilum-mc-mods#1776]
## **Information**
Minecraft version: 1.16.5
Modloader: Forge
Forge version: 36.2.20
Environment: Singleplayer

Mod name: Tree Harvester
Mod version: 1.19.4

## **Description**
Every time I try to shift to cut down a tree, the game crashes with the error "exception in server tick loop." I am a little confused considering I have never had a running server...

## **Crash report**

[crash-2023-05-17_20.41.18-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/11503360/crash-2023-05-17_20.41.18-server.txt)

**Comment by ricksouth** [comment]
Unfortunately I no longer support Minecraft version 1.16.5. Apologies for the inconvenience.
