### ISSUE TITLE
Config option for GUI Compass

### ISSUE THREAD

**Issue by krookodilehunter** [ricksouth/serilum-mc-mods#1783]
## **Information**
Minecraft version: 1.17.1
Modloader: Forge 
Forge version: 37.1.1
Environment: Singleplayer
Mod name: GUI Compass
Mod version: 1.17.1-2.2

## **Question**
The config file for GUI Compass 1.17.1-2.2 does not have an option to add a shadow to the text. Is it possible to add that in myself?

**Comment by ricksouth** [comment]
Unfortunately that feature was added in a later version and 1.17 wasn't supported anymore at that time. Thanks for giving the mod a try!

**Comment by krookodilehunter** [comment]
Thank you for making the mod!
