### ISSUE TITLE
Mineral Chance triggers on player placed stone

### ISSUE THREAD

**Issue by FireStryker** [ricksouth/serilum-mc-mods#1786]
## **Information**
Minecraft version: 1.18.2
Modloader: Forge
Forge version: 40.2.4
Environment: Multiplayer

Mod name: Mineral Chance
Mod version: 1.18.2-3.1

## **Description**
Minerals can spawn when breaking player placed stone. It is infinity farmable using silk touch.

**Comment by ricksouth** [comment]
I don't consider them dropping from placed blocks a bug, but I'll leave this open to disable mineral drops from blocks mined with silk touch. Thanks!

**Comment by ricksouth** [comment]
Mineral Chance 3.2 adds the 'disableMineralDropsWithSilkTouch' config option, enabled by default. This stops mineral drops from stone mined with a silk touch pickaxe. Thanks for the suggestion and giving the mod a try!

https://curseforge.com/minecraft/mc-mods/mineral-chance/files
