### ISSUE TITLE
Enhancement Request

### ISSUE THREAD

**Issue by K4N0** [ricksouth/serilum-mc-mods#1787]
Greetings,

If possible.
It would be great for modpack creators if we could lock a modpack to only allow it to be played on Hard Difficulty or other.
Essentially remove certain difficulty options when creating new worlds. For Server owners, it's an easy config, so no support needed there except for a mod mis-match issue. 
I understand experienced players can just remove the mod.

**Comment by ricksouth** [comment]
I've already got a mod for this :D

https://www.curseforge.com/minecraft/mc-mods/difficulty-lock
