### ISSUE TITLE
Doesn't mute Better Call Saul

### ISSUE THREAD

**Issue by SigmaFlame** [ricksouth/serilum-mc-mods#1790]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge 
Forge version: 43.2.11
Environment: Singleplayer

First mod name: Better Call Saul
First mod version: 1.19

## **Description**
I'm playing a modpack that sadly have the mod Better Call Saul.
Omega Mute cannot mutes the irritating mob added by this mod.

It well identifies that "saulneutrals" is played, but closing the game, adding a ! before the line, then re-open the game doesn't mute the mob. It plays its sound at every second. Tryed to mute every sound from this mob as well, doesn't work.

## **Crash report**
No crash report.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! Apologies it took so long for me to get to. This has been fixed in version 4.0 of Omega Mute, alongside some other feature upgrades.

https://curseforge.com/minecraft/mc-mods/omega-mute/files
