### ISSUE TITLE
Harvest Time Not Working

### ISSUE THREAD

**Issue by LunarDev-git** [ricksouth/serilum-mc-mods#1791]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 43.2.11
Environment: Multiplayer

Mod name: Tree Harvester
Mod version: treeharvester-1.19.2-8.0.jar

## **Description**
No matter what I do the config for longer harvest time doesn't seem to work. I want to make it much longer. 

Here's my config.
https://hastebin.com/share/binoleroda.json

**Comment by James103** [comment]
Text file of paste, as pastes on Hastebin expire within 7 days (and likely earlier): [config.txt](https://github.com/ricksouth/serilum-mc-mods/files/11618976/config.txt)

**Comment by LunarDev-git** [comment]
Thank you

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 8.2 of Tree Harvester and version 6.61 of Collective.

https://www.curseforge.com/minecraft/mc-mods/tree-harvester/files
https://www.curseforge.com/minecraft/mc-mods/collective/files
