### ISSUE TITLE
Doesn't seem to work client side only.

### ISSUE THREAD

**Issue by WoodenJoe** [ricksouth/serilum-mc-mods#1793]
## **Information**
Minecraft version: 1.19.4
Modloader: Forge
Forge version: 45.0.66  
Environment: Multiplayer

Mod name: Replanting Crops
Mod version: 5.1

## **Description**
I've been testing and it works in single-player, but not on servers.

**Comment by EightBitBBQ** [comment]
I dont think this is a client side only mod. 
Most likely this mod needs to run on the server as well

**Comment by WoodenJoe** [comment]
I apologize if true, I thought I had read that this only needed client side. In past there were other replanting mods that only required client side.

**Comment by EightBitBBQ** [comment]
No problem ofcourse. Dont need to apologize.
Sadly due to some hardware issues on my side i can not test this out.

**Comment by ricksouth** [comment]
Yep, this mod is needed on the server as it's manipulating blocks. Otherwise it would be considered cheating as well. Thanks for giving it a try!
