### ISSUE TITLE
How to configure?

### ISSUE THREAD

**Issue by Aceplante** [ricksouth/serilum-mc-mods#1798]
I am confused on how to configure nutritious milk. This is what is there by default:

{
	// The hunger level decreased. Example values: cookie = 2, bread = 5, salmon = 6, steak = 8.
	// min: 0, max: 20
	"hungerLevelIncrease": 2,
	// The saturation increase. Example values: melon = 1.2, carrot = 3.6, chicken = 7.2, steak 12.8.
	// min: 0.0, max: 20.0
	"saturationLevelIncrease": 2.0
}

where do I add cookie = 2 etc? can you provide an example? Also do I do iceandfire:cannoli = 3 or something to support foods of other mods?

**Comment by ricksouth** [comment]
You edit the values ' "hungerLevelIncrease": 2 ' and ' "saturationLevelIncrease": 2.0 '. The other values are examples to compare it with. If you want milk to increase the same hunger as bread, you do ' "hungerLevelIncrease": 5 ' for example.

**Comment by Aceplante** [comment]
how do I change the food values of foods other than milk?

**Comment by ricksouth** [comment]
That's outside of the scope of this mod. This gives milk a nutritious value, hence the title
