### ISSUE TITLE
Omega Mute on 1.19.2 Forge with Collective 6.53 cannot load at all

### ISSUE THREAD

**Issue by Syampuuh** [ricksouth/serilum-mc-mods#1799]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 43+
Environment: Any

Mod name: Omega Mute
Mod version: 2.3+

## **Description**
When starting Minecraft with Omega Mute and Collective installed, the game fails to load. I have tested in isolation with all 3 versions available for 1.19.2, as well as checked the first, recommended, and latest versions of Forge 43.
This seems like a library issue: I cannot load with the latest version of Collective available for 1.19.2, 6.53, but rolling back to the version available the day that Omega Mute was last updated, 6.15, the game can launch.

## **Crash report**
https://gist.githubusercontent.com/Syampuuh/1223012e7704b5f98c82338e657862a5/raw/e81ea4fe2e28408460f2efe1022c5a85efda1ba1/crash-2023-06-06_06.24.07-fml.txt

**Comment by ricksouth** [comment]
Did you use the 3.0 version of Omega Mute?

https://www.curseforge.com/minecraft/mc-mods/omega-mute/files/4324177

**Comment by Syampuuh** [comment]
Aw heck, I think I straight up blinded this version while looking through the file list on CurseForge. I think my brain just saw "Fabric" and skipped over it, but I will deflect the blame to the new layout 😛

**Comment by ricksouth** [comment]
I agree, the new layout is missing a lot of essential information. Glad it works and thanks for giving the mods a try :)
