### ISSUE TITLE
Doesn't work on the server 

### ISSUE THREAD

**Issue by towux** [ricksouth/serilum-mc-mods#1800]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.18.2
Modloader: Fabric
Fabric loader version: 0.14.21
Environment: Multiplayer

Mod name: Replanting Crops
Mod version: 5.1

## **Question**
Why is the mod not working on the server?

**Comment by ricksouth** [comment]
Is the mod installed on the server, or only on the client?

**Comment by towux** [comment]
> 

Only on the client

**Comment by ricksouth** [comment]
As the mod manipulates blocks, planting crops in this case, it's not client-side only. You'll have to have it installed on the server, otherwise it's considered a cheat.

**Comment by Towux** [comment]
> 

Есть ли подобные моды которые будут высаживать растения?

**Comment by towux** [comment]
> As the mod manipulates blocks, planting crops in this case, it's not client-side only. You'll have to have it installed on the server, otherwise it's considered a cheat.

Are there similar mods that will work without server mod?

**Comment by ricksouth** [comment]
Not that I'm aware of. Again, it's in the realm of cheating which is not what the mod is made for. Ask the server owner to install it. Thanks for giving it a try nonetheless!

**Comment by towux** [comment]
> 

Okay, thanks
