### ISSUE TITLE
Configurable Despawn Timer Crash with Lycanites Mobs

### ISSUE THREAD

**Issue by Kasia0314** [ricksouth/serilum-mc-mods#1803]
[crash-2023-06-09_13.58.57-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/11706011/crash-2023-06-09_13.58.57-server.txt)
[latest.log](https://github.com/ricksouth/serilum-mc-mods/files/11706021/latest.log)

**Comment by Kasia0314** [comment]
@ricksouth  What is mod label ?

**Comment by EightBitBBQ** [comment]
Mod label is the mod. So in this case Configurable Despawn Timer
@ricksouth will add this later on

**Comment by ricksouth** [comment]
Thanks for giving the mod a try! Unfortunately 1.12 is no longer supported, apologies.
