### ISSUE TITLE
Tree Harvester is out of sync with the server

### ISSUE THREAD

**Issue by Dr-WeiAL** [ricksouth/serilum-mc-mods#1807]
## **Information**
Minecraft version: 1.20
Modloader: Fabric
Fabric loader version: 0.14.21
Environment: Multiplayer

Mod name: Tree Harvester
Mod version: 8.1

## **Description**
In the single-player game can be correctly based on the size of the tree to determine the speed of felling, but on the server does not seem to take effect, and must also cut the corresponding time to cut down the tree
![1](https://github.com/ricksouth/serilum-mc-mods/assets/47446553/a022add0-c833-40a5-862d-28a8f8c85cef)

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 8.2 of Tree Harvester and version 6.61 of Collective.

https://www.curseforge.com/minecraft/mc-mods/tree-harvester/files
https://www.curseforge.com/minecraft/mc-mods/collective/files

**Comment by Dr-WeiAL** [comment]
It seems that the effect is not quite the same as expected, now there will be no extra felling time for cutting trees on the server, but rather cutting a log and the whole tree falls down
