### ISSUE TITLE
Helmet doesn't get placed into chest if `addPlayerHeadToArmorStand` is on

### ISSUE THREAD

**Issue by nonnorm** [ricksouth/serilum-mc-mods#1811]
## **Information**
Minecraft version: 1.20
Modloader: Fabric
Fabric loader version: 0.14.21
Environment: Singleplayer and Multiplayer

Mod name: Your Items Are Safe
Mod version: 3.3

## **Description**
If you die wearing a helmet while `addPlayerHeadToArmorStand` is on, the helmet will disappear and not go into the chest. In addition, the player head will not appear on top of the armor stand. It works as expected if `addPlayerHeadToArmorStand` is off, or if the player is not wearing a helmet.

Appears to maybe be similar to #1377, however the helmet is not found anywhere near the death site.

## **Crash report**
N/A

**Comment by bitomic** [comment]
Can confirm. Interestingly, it used to be correctly generated the first time, and subsequent ones fail and the helmet completely disappears.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 3.4 of Your Items Are Safe. Apologies for the inconvenience.

https://curseforge.com/minecraft/mc-mods/your-items-are-safe/files
