### ISSUE TITLE
Placeable Blaze Rods - No Arm Swing, No Block Placing Sound

### ISSUE THREAD

**Issue by ringprod** [ricksouth/serilum-mc-mods#1815]
## **Information**
Minecraft version: 1.20.1
Modloader: Fabric

Mod name: Placeable Blaze Rods 3.0

## **Feature description**
When placing a blaze rod, the player's hand does not swing (ActionResult.SUCCESS). The item is just removed from the inventory and the block appears with no block placing sound.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 3.1 of Placeable Blaze Rods.

https://www.curseforge.com/minecraft/mc-mods/placeable-blaze-rods/files
