### ISSUE TITLE
1.20.1 not working on dedicated fabric server

### ISSUE THREAD

**Issue by MorganMode** [ricksouth/serilum-mc-mods#1821]
## **Information**
Minecraft version: 1.20.1
Modloader: Fabric
Fabric loader version: 0.14.21
Environment: Multiplayer

Mod name: Tree Harvester
Mod version: 8.1

## **Description**
I installed the mod in my dedicated server as well as my loader, and the mod just doesn't work. I can access the settings in my mods list but in-world it does nothing.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 8.2 of Tree Harvester and version 6.61 of Collective.

https://www.curseforge.com/minecraft/mc-mods/tree-harvester/files
https://www.curseforge.com/minecraft/mc-mods/collective/files
