### ISSUE TITLE
Advancement Screenshot does not Screenshot the Advancements

### ISSUE THREAD

**Issue by dazednova** [ricksouth/serilum-mc-mods#1823]
## **Information**
Minecraft version: 1.20.1
Modloader: Fabric
Fabric loader version: 0.14.21
Environment: Singleplayer

Mod name: Advancement Screenshot
Mod version: 4.1

## **Description**
Basically, the mod does not do anything. If I recall correctly there were issues like this in earlier Minecraft versions that were resolved and closed, so I can't really explain why this is happening, but it is. The other mods I'm using Advancement Screenshot with are listed below. I tried enabling and again disabling the option to show the screenshot message in chat, it did not change anything. I added Mod Menu to confirm that the game actually recognized the mod, and it did, but it continued to not work, so I removed it. I was also using the BlazeAndCave's advancements datapack, which i removed, and it did not work for vanilla advancements either.
![Screenshot 2023-06-18 143038](https://github.com/ricksouth/serilum-mc-mods/assets/101843423/0eceeb4e-7523-4c28-915b-75c5def73a2f)

**Comment by ricksouth** [comment]
Thanks for opening the issue! The mixin triggering the screenshot no longer worked in 1.20 due to parameter changes. I missed that when updating, apologies. This has been fixed in version 4.2 of Advancement Screenshot.

https://curseforge.com/minecraft/mc-mods/advancement-screenshot/files
