### ISSUE TITLE
Area name only config option does nothing

### ISSUE THREAD

**Issue by TheOtherworldly** [ricksouth/serilum-mc-mods#1824]
I set it to on, but it still displays both the entering and leaving message. I just want it to show the area :/ The enter and Leave message ruins it because my areas are not perfect squares. I want it to just display the name like the option says it should but the option doesnt do anything

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 5.0 of Areas, alongside other bug fixes and QoL features.

https://www.curseforge.com/minecraft/mc-mods/areas/files
