### ISSUE TITLE
Areas mod: Game crashes and semi-hardlocks world when large number is used for area radius.

### ISSUE THREAD

**Issue by TotallyCool0** [ricksouth/serilum-mc-mods#1825]
## **Information**
Minecraft version: 1.20.1
Modloader: Fabric
Forge version: Fabric loader version: 0.14.21 (Going off of what Prism MC says...)
Environment: Singleplayer / Multiplayer

Mod name: Areas
Mod version: 4.4

## **Description**
I entered a ridiculously large number for the area radius (something like 10000000 just spammed 0s) and the
game promptly crashed. I imagine some kind of scan or check or something attempted to iterate through all of the
blocks and it just could not keep up and crashed. The world is now unjoinable because of this. Of course, there *are*
ways to fix this such as removing the mod, or editing the sign externally.

## **Crash report**
[_(Snippet of crash report.)_](https://gist.github.com/TotallyCool0/fa42fc5a4dc36b41157bf6794875c6d0)

**Comment by ricksouth** [comment]
You're in luck! I've been working on Areas all day and should have an update ready in about 20 minutes :)

**Comment by TotallyCool0** [comment]
Awesome! That's great timing! I'm looking forward to it! 😄

**Comment by ricksouth** [comment]
I'll do an extra test just to make sure. Did you mean the radius on the sign, or in the config?

**Comment by ricksouth** [comment]
![2023-06-21_23 58 24](https://github.com/ricksouth/serilum-mc-mods/assets/38502394/211ba927-988a-4db3-84df-ab59752c365c)
![2023-06-21_23 58 33](https://github.com/ricksouth/serilum-mc-mods/assets/38502394/6fbcd2d9-deea-4310-96d9-54b249be9d63)

If you mean the sign, that has been fixed :)

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 5.0 of Areas, alongside other bug fixes and QoL features.

https://www.curseforge.com/minecraft/mc-mods/areas/files

**Comment by TotallyCool0** [comment]
Sorry for the late reply. Yes, that is what I meant! Thank you for fixing this so quickly! I have been enjoying this and your other mods!
