### ISSUE TITLE
Modded signs do not work with /areas

### ISSUE THREAD

**Issue by Ch1216** [ricksouth/serilum-mc-mods#1827]
## **Information**
Minecraft version: 1.18.2
Modloader: Forge
Forge version: 40.2.6
Environment: Singleplayer

First mod name: Areas
First mod version: 5.0

Second mod name: Biomes O' Plenty
Second mod version: 16.0.0.109

## **Description**
Modded signs work to make areas, however the /areas command does not recognize them. also hanging signs from supplementaries do not work at all

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 5.4 of Areas.

https://curseforge.com/minecraft/mc-mods/areas/files
