### ISSUE TITLE
Items not spawning in when I increase spawn radius

### ISSUE THREAD

**Issue by AIdanNCo** [ricksouth/serilum-mc-mods#1830]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge 
Forge version: 43.2.14
Environment: Singleplayer

Mod name: starter kit
Mod version: starterkit-1.19.2-5.2

## **Description**
The issue occurs when spawning outside or particularly far from the normal spawn radius. I've increased it from 10 to 100/1000, I've found that if I spawn within the regular spawning radius of ten (while having it increased past that) the items still spawn, but if I spawn further out they do not load in.

**Comment by ricksouth** [comment]
Where are you increasing the spawn radius? Is that a server.properties setting?

**Comment by AIdanNCo** [comment]
It's a game rule.

**Comment by ricksouth** [comment]
This has been fixed in Collective version 7.9, Starter Kit doesn't need an update. Apologies it took so long for me to get to. Thanks for giving the mod a try!

https://modrinth.com/mod/collective
