### ISSUE TITLE
[Welcome Message] Is this mod required on client, or is it server only?

### ISSUE THREAD

**Issue by katubug** [ricksouth/serilum-mc-mods#1834]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 43.2.8
Environment: Multiplayer

Mod name: Welcome Message
Mod version: any

## **Question**
As in title! I want to know if I can just add this to my server, or if it needs to be on client as well. Collective is already present on both server and client in our modpack.

**Comment by ricksouth** [comment]
Thanks for giving the mod a try! It's only necessary on the server :) Unless you want it to work in Singleplayer as well.

**Comment by katubug** [comment]
Excellent, thank you so much!
