### ISSUE TITLE
Dawncraft 1.24 incompatibility

### ISSUE THREAD

**Issue by Varesh** [ricksouth/serilum-mc-mods#1841]
## **Information**
Minecraft version: 1.18.2
Modloader: Forge
Forge version: 40.2.9
Environment: Singleplayer

First mod name: Modpack Dawncraft
First mod version: 1.24

Second mod name: Altered Damage
Second mod version: 1.6

## **Description**
Hey! This happened.
I wanted to use your mod Altered Damage with the new modpack : Dawncraft, but it doesn't seems compatible.
Could you help me with that ?

## **Crash report**
If available.
[crash-2023-06-28_11.55.07-fml.txt](https://github.com/ricksouth/serilum-mc-mods/files/11892810/crash-2023-06-28_11.55.07-fml.txt)

**Comment by James103** [comment]
Have you tried updating the version of Collective included in the modpack instance to the latest version that supports 1.18.2?

**Comment by Varesh** [comment]
I just tried and it failed.
[crash-2023-06-28_13.49.07-fml.txt](https://github.com/ricksouth/serilum-mc-mods/files/11893663/crash-2023-06-28_13.49.07-fml.txt)

**Comment by ricksouth** [comment]
You'll need to use the latest version of Altered Damage as well. The one for both Forge and Fabric

**Comment by Varesh** [comment]
![image](https://github.com/ricksouth/serilum-mc-mods/assets/546850/423a411e-8d77-4695-9f39-c56871060f9e)
This one ?

**Comment by ricksouth** [comment]
You should take th 3.1 above that :) But yes that'll work

**Comment by Varesh** [comment]
And it worked ! :')
My bad, I didn't loaded the correct versions !
Thank's a lot for your help !
And thank you for the mods !

**Comment by ricksouth** [comment]
No problem, thanks for giving the mods a try!

(And @James103 thanks for the quick response too!)
