### ISSUE TITLE
Create an area with a name

### ISSUE THREAD

**Issue by ForionOG** [ricksouth/serilum-mc-mods#1849]
Create an area with a name
Minecraft version: 1.20
Modloader: Fabric
Fabric loader version: 0.14.21
Environment: Multiplayer

Mod name: Mod
Mod version: 4.4

Hey, I tried making an area sign with a name and it wouldn't show the areas name or anything so I tried making one without a name and that worked but its not the name that I wanted of course xD.

I also tried making one without a name so it would autogenerate and rename the area after with the new 1.20 update but that did not work either it just showed the random name still.
Haven't tried in Singleplayer yet.

**Comment by ricksouth** [comment]
Thanks for giving the mod a try! Please update to Areas version 5.0, as it has fixed many issues. Let me know if the problem persists

**Comment by ForionOG** [comment]
I couldnt download it from the curseforge application so now i downloaded it from the site and will try it out!

**Comment by ricksouth** [comment]
I think it's because you're still on 1.20. you should consider updating to 1.20.1 :)

**Comment by ForionOG** [comment]
its working thank u! I was indeed considering it but I am playing on a server which was originally 1.19.2 but my gf wanted to play 1.20 so I picked the version which had most of the mods we were using
