### ISSUE TITLE
mushroom cutting misbehaving

### ISSUE THREAD

**Issue by kfmgnv** [ricksouth/serilum-mc-mods#1851]
## **Information**
Minecraft version: 1.20.1
Modloader: Fabric 
 Fabric loader version: 1.14.21
Environment: Singleplayer 

Mod name: Mod
Mod version: -8.2

## **Description**
NO matter what I type in config file, brown mushrooms don't work.  And Red mushrooms always plant mushroom sapling.  Trees work as expected

## **Crash report**
_(Please either drag the file directly here, or use https://gist.github.com/ to prevent the paste from expiring)_

If available.

**Comment by kfmgnv** [comment]
Updated fabric api just now.  Red mushrooms behaving correctly.  Brown still only cutting as if not covered in the mod

**Comment by SnowwyAI** [comment]
This is happening in the Forge version as well. Don't know if I should create a separate issue for it.

Minecraft version: 1.20.1
Modloader: Forge
Forge loader version: 47.0.35
Environment: Singleplayer

Mod name: Tree Harvester
Mod version: 8.2

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 9.1 of Tree Harvester. Appreciate it.

https://curseforge.com/minecraft/mc-mods/tree-harvester/files
