### ISSUE TITLE
Client or Server

### ISSUE THREAD

**Issue by DocBroek** [ricksouth/serilum-mc-mods#1852]
## **Information**
Minecraft version: xx.xx.xx
Modloader: Forge / Fabric
Fabric loader version: 1.20.1
Environment: Singleplayer / Multiplayer

Mod name: Better Beacon Placementz
Mod version: 3.1

Is this mod server or client side? For me, I watched a video that contained this mod, and a couple others such as Double Doors, and they don't work for me. I've tried them on a realm and they won't work, but they do on single player worlds. Please help. 
Thanks.

**Comment by ricksouth** [comment]
The mod has to be installed on the server, since it manipulates block data. Thanks for the interest!
