### ISSUE TITLE
Crash, Tree Harvester: timeout when harvesting big modded trees

### ISSUE THREAD

**Issue by rxay579** [ricksouth/serilum-mc-mods#1854]
## **Information**
Minecraft version: 1.19.4
Modloader: Fabric
Fabric loader version: 0.14.21
Environment: Singleplayer and Multiplayer

Mod name: Tree Harvester
Mod version: 8.0 / 8.2

## **Description**
When harvesting large or dense modded trees from BetterEnd, the server stops responding.
This hasn't been an issue yet with modded vanilla tree generation or other trees we've encountered from other mods, but those have tended to be smaller or less densely connected to each other.

In a multiplayer environment, the server watchdog timer eventually times out, stops the server, and generates a crash log.
When resumed, the world is in a state from before the harvesting was attempted.

In a single player environment, the server component also seems to hang.
Things appear somewhat normal, but block updates don't seem to happen.
Attempting to save and quit leads to the client hanging.

Also tested in single player with updated Tree Harvester v8.2, BetterEnd, and their requirements with the same results.

Likely related to some other reports / requests where large modded trees are involved.
A setting for a maximum logs to check / break may be helpful.
A setting for an exclude list may also be helpful.

Hopefully some of this is helpful.

## **Crash report**
Crash report from 1st time it happened on a local multiplayer server with Tree Harvester v8.0 and many other mods:
[crash-2023-06-30_22.14.52-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/11933253/crash-2023-06-30_22.14.52-server.txt)
Crash report from 2nd time it happened on a local multiplayer server with Tree Harvester v8.0 and many other mods:
[crash-2023-06-30_22.26.43-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/11933260/crash-2023-06-30_22.26.43-server.txt)

Crash report from single player instance with only Tree Harvester v8.0, BetterEnd, and their requirements:
[crash-2023-07-03_00.09.11-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/11933272/crash-2023-07-03_00.09.11-server.txt)

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 9.1 of Tree Harvester. Appreciate it.

https://curseforge.com/minecraft/mc-mods/tree-harvester/files
