### ISSUE TITLE
Incompatibility with Tinted Campfires

### ISSUE THREAD

**Issue by Octelly** [ricksouth/serilum-mc-mods#1859]
## **Information**
Minecraft version: ``1.19.2``
Modloader: ``Forge``
Forge version: ``43.2.3``
Environment: ``N/A``

First mod name: ``Healing Campfire`` / ``No Hostiles Around Campfire``
First mod version: ``5.1`` / ``5.4``

Second mod name: ``Tinted Campfires``
Second mod version: ``1.19.2-1.2.6``

## **Description**
Neither of your 2 campfire mods work with modded campfires ([Tinted Campfires](https://www.curseforge.com/minecraft/mc-mods/tinted-campfires) in this case).

## **Crash report**
N/A

**Comment by Octelly** [comment]
I think a good solution would be to allow players to add more blocks which should be considered as campfires in the config.

**Comment by Jadan1213** [comment]
> I think a good solution would be to allow players to add more blocks which should be considered as campfires in the config.

I agree with this. This would remove the need to add explicit compatibility and allow us to add whatever we'd like.

**Comment by Jadan1213** [comment]
> I think a good solution would be to allow players to add more blocks which should be considered as campfires in the config.

I've submitted files to the tinted campfires dev to add to his mod that will make them work with Healing campfires, as well as be mineable faster with an axe. He's going to add them to his next mod release on 1.20.1. i've asked him if he's willing to submit the fix to other mc versions too.

**Comment by Jadan1213** [comment]
Tinted campfires has been updated, and the fix will make it compatible with healing campfires like it should have been. 


This thread can probably be closed as it was an issue on the tinted campfires side.
