### ISSUE TITLE
Ghosting powered rails on nether roof 1.2 forge

### ISSUE THREAD

**Issue by Tsukino-Kaji** [ricksouth/serilum-mc-mods#1864]
## **Information**
Minecraft version: 1.2
Modloader: Forge
Forge version: 46.0.14
Environment: Server(not host)
Mod name: Stack Refill
Mod version: [Forge & Fabric] 1.20.1-4.0 | Stack Refill by Serilum

Laying powered rail on the nether roof causes ghosting and does not work at all.

**Comment by Tsukino-Kaji** [comment]
Fabric 0.14.21 does the same.

**Comment by ricksouth** [comment]
Do you have the mod installed in the client as well?
