### ISSUE TITLE
MoreDoors & SWDM Incompatability

### ISSUE THREAD

**Issue by darkangel8xt** [ricksouth/serilum-mc-mods#1865]
## **Information**
Minecraft version: 1.18.2
Modloader: Forge
Forge version: 40.0.9 
Environment: Multiplayer

First mod name: MoreDoors
First mod version: 1.0.2

Second mod name: SWDM
Second mod version: 3.0.1

Third mod name: Double Doors (Yours!)
Third mod version: 5.0

## **Description**
Both MoreDoors and Star Worm Decor Mod (SWDM) have new door designs, and glitches when DoubleDoors tries to open them. If I place two doors next to each other, both bottom halves close and one top half closes, the other top half stays open.  This also inverts if I try to do the opposite; three halves open, and one half stays closed. Maybe add compatibility or a whitelist of what doors or mods we want to allow DoubleDoors to work with?

## **Crash report**
Not Applicable.

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! Support for modded doors has been added in version 5.3 of Double Doors.

https://curseforge.com/minecraft/mc-mods/double-doors/files
