### ISSUE TITLE
[Bug] Spawn kit won't delete/remove existing items after kit properly.

### ISSUE THREAD

**Issue by Darkmega18** [ricksouth/serilum-mc-mods#1868]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 43.2.14
Environment: Single, and likely multi

Mod name: Starter Kit
Mod version: starterkit-1.19.2-5.2.jar

## **Description**
The starter kit option for "addExistingItemsAfterKitSet" is not working. I have about an entire lines worth of inventory of books which spawn in which I'm trying to override but they still sneaking through and some of them can't just be configured off manually, so you're my only hope. :<

can you delay the kit's spawn to wait a moment, delete inventory/save the items in the inventory, spawn the kit, then add it back/no add it back after so that it catches most cases of inventory start adds?

## **Crash report**
no crash per-se. just mod not working as advertised.

**Comment by ricksouth** [comment]
Can you give me some examples of the mods that still put their books in the inventory? It should work exactly like you mentioned, the mod does wait a bit and checks for items added. But maybe I'll have to increase that delay, or make it configurable

**Comment by Darkmega18** [comment]
Uh, Alex mobs book, simply swords book, weaponmaster book, apotheosis book, enigmatic legacy's ring and amulet, parcool, iron's spell, one probe... just about everything.

but I am noticing I'm not getting my 16 torches. so despite installing the mod, and having set up the torches which are universal throughout all my origin start kits so I put them there just so you delete the inventory of books, it seems to be not working at all for me. :V

even though at one point I did have it set up with some colored armor and food etc. before I decided to do start locations and kits via origins.

**Comment by Darkmega18** [comment]
With a bit more testing. I'm feeling like maybe it's because of the origins interface coming up?

the books I can hear pop into my inventory when I start the world, but when I select my origin gear and it falls into my inventory it's like nothing has happened, I don't have the 16 torches I set as the only item of the set cause I give torches to every setup regardless. I also deleted my configs for it and let them get regenerated and it's still playing up.

I had been testing the pack previously before deciding to do origin based start kits and spawn locations. So it's like it's not even working at all. Since previously all my "origins" had been auto selected immediately cause they had just been hidden side mechanics to gameplay and such which I programmed in via origin based datapacks. The start kit which was some stone tools and leather armor and a shield had worked just fine. although at the time I allowed the books to continue spawning cause I started people with a backpack. :V

**Comment by Darkmega18** [comment]
oh no... and this time, it ACTUALLY worked, but the starter kit came in AFTER my origins gear, and it caused my inventory to get wiped except for the torches. god damn. X_X

**Comment by SigmaFlame** [comment]
ic2classic manual cannot be deleted as well, and the author refuses to give an option to disable it.
An option to delay the removal for at least one second should be necessary.

**Comment by James103** [comment]
> ic2classic manual cannot be deleted as well, and the author refuses to give an option to disable it. An option to delay the removal for at least one second should be necessary.

A workaround for this, assuming you know the item ID of the ic2classic manual, is likely to be something along these lines:
1. Create an advancement which triggers whenever the player obtains the ic2classic manual or has one in their inventory.
2. In the advancement, specify an `mcfunction` as the reward.
3. In the `mcfunction`, run `clear @s X`, replacing `X` with the item ID of the ic2classic manual.

This can be done in a datapack, including, if KubeJS is installed, the `data` folder inside the `kubeJS` directory of your Minecraft instance. In the case of the latter, the datapack should be added during world creation.

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 6.0 of Starter Kit, alongside many new features! See the description for more details:

https://curseforge.com/minecraft/mc-mods/starter-kit
