### ISSUE TITLE
java.lang.RuntimeException: Error creating Mixin config collective.mixins.json for mod collective

### ISSUE THREAD

**Issue by palapapa** [ricksouth/serilum-mc-mods#1871]
## **Information**
Minecraft version: 1.19.2
Modloader: Fabric
Fabric loader version: 0.14.21
Environment: Singleplayer

Mod name: Collective
Mod version: 6.64

## **Description**
Crash on startup. No further information was given in the log.
These are the mods installed before the crash happened. Prior to their installation, the game started just fine. Maybe they caused this issue? But it's impossible to tell from the log which somehow gave very little information.
![image](https://github.com/ricksouth/serilum-mc-mods/assets/61058728/d1901383-7720-4dfe-9c7d-2be25764ff29)

## **Crash report**
[latest.log](https://github.com/ricksouth/serilum-mc-mods/files/12026475/latest.log)

**Comment by ricksouth** [comment]
My fix hadn't worked apparently. Please refer to version 6.62 for now, working in it right now. Thanks for opening the issue!

**Comment by ricksouth** [comment]
I've just uploaded Collective version 6.65, which should fix the issues. Please let me know if the problem persists, due to how I merge Forge and Fabric it was a bit difficult to find.

**Comment by palapapa** [comment]
The issue was resolved. Thank you!
