### ISSUE TITLE
Tree Harvester: Cutting azalea tree issue

### ISSUE THREAD

**Issue by wc7086** [ricksouth/serilum-mc-mods#1876]
## **Information**
Minecraft version: 1.20.1
Modloader: Forge
Forge version: 47.1.0
Environment: Multiplayer

Mod name: Tree Harvester
Mod version: 8.2

## **Description**
Azalea leaf saplings do not AUTOMATICALLY REPLACE when `replaceSaplingOnTreeHarvest` is on.

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 9.1 of Tree Harvester. Appreciate it.

https://curseforge.com/minecraft/mc-mods/tree-harvester/files
