### ISSUE TITLE
Ignore Structure Voids

### ISSUE THREAD

**Issue by DaedalusGame** [ricksouth/serilum-mc-mods#1877]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Mod name: Starter Structure

## **Feature description**
Structure Blocks and Jigsaw Blocks are already ignored when placing a schematic, it would be nice if Structure Voids would also be ignored the same way, making a worldedit schematic with Structure Blocks in place of Structure Voids increases the schematic file size 50-100x because each Structure Block holds a small amount of TE data.

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 3.4 of Starter Structure.

https://curseforge.com/minecraft/mc-mods/starter-structure/files
