### ISSUE TITLE
Villager Names for Villager Recruits

### ISSUE THREAD

**Issue by laptoppunk** [ricksouth/serilum-mc-mods#1882]
## **Information**
Minecraft version: 1.18.2+
Modloader: Forge

Mod name: Villager Names

## **Feature description**
I've had this amazing idea! In the Curseforge description, it mentions that if a villager-like entity that's not named is found to let the devs know so they can add it to the compatibility list. Well I've found a couple in [talhanation's Villager Recruits](https://www.curseforge.com/minecraft/mc-mods/recruits)! It's a mod that adds new villager types that spawn in villages and around the world that the player can hire and command to perform a series of many combat related tasks. Support for these mobs would be greatly appreciated!

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been added in version 6.0 of Villager Names and version 6.80 of Collective. :) Apologies it took so long for me to get to.

https://legacy.curseforge.com/minecraft/mc-mods/villager-names/files
https://legacy.curseforge.com/minecraft/mc-mods/collective/files
