### ISSUE TITLE
[Passive Shield] Is client-side required?

### ISSUE THREAD

**Issue by HatTrkPatrk** [ricksouth/serilum-mc-mods#1883]
## **Information**
Mod name: Passive Shield

## **Question**
Is this mod required on client-side?

**Comment by ricksouth** [comment]
If you'd like the hiding of the shield, it has to be on the client. If you'd only like the damage reduction when holding it, it had to be on both

**Comment by Ankeltor** [comment]
This should be indicated on the Client Bundle page, to avoid confusion, as it is the only mod in the bundle that is both-sided. @ricksouth 
It would also be great to have a Server Bundle, for an easy Vanilla-like setup in NeoForge, if possible.
