### ISSUE TITLE
Full Bright enabled on startup?

### ISSUE THREAD

**Issue by JorenSB** [ricksouth/serilum-mc-mods#1885]
## **Information**
Minecraft version: 1.20.1
Modloader: Fabric
Fabric loader version: 0.14.21-1.20.1
Environment: Singleplayer / Multiplayer

Mod name: Full Brightness Toggle
Mod version: 1.20.1-3.0

## **Question**
Is there a way to automatically have Full Brightness enabled on startup? Instead of having to toggle it every time on startup.

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! Full Brightness Toggle version 4.0 has the fullbright state persistent across game launches. So it'll remember if it was on/off and keep it that way.

https://www.curseforge.com/minecraft/mc-mods/full-brightness-toggle/files
