### ISSUE TITLE
Unable to get custom items to spawn anymore

### ISSUE THREAD

**Issue by AlwaysHave** [ricksouth/serilum-mc-mods#1888]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 43.2.21
Environment: Singleplayer

Mod name: Starter Kit
Mod version: 5.2

## **Description**
I'm unable to get custom items to spawn anymore. I've looked at the item ID and it doesn't seem to work.

**Comment by ricksouth** [comment]
Did you use the /starterkit set command?

**Comment by AlwaysHave** [comment]
> Did you use the /starterkit set command?

I did not and that's what fixed it. Thank you. Thought you could only edit it in the text file.
