### ISSUE TITLE
Tree Harvester not working properly on multiplayer server

### ISSUE THREAD

**Issue by rice-and-sugar** [ricksouth/serilum-mc-mods#1889]
## **Information**
Minecraft version: 1.16.5
Modloader: Forge
Forge version: 36.2.20
Environment: Multiplayer (Shockbyte Server)

Mod name: Tree Harvester
Mod version: 5.9

## **Description**
I have Tree Harvester on a single player world, which works perfectly, but for some reason it only works about half of the time on a multiplayer server. My bf and I play together and strangely... it works just fine for him but not for me. Small trees are less finnicky, while large trees are completely un-choppable. Again, he can do it no problem. 

I also know that when chopping a larger tree, it takes a long time, but while crouching & trying to use the mod, the game acts as though its not registering the crouch and just chops one log out of the tree. 

## **Crash report**
N/A

**Comment by ricksouth** [comment]
Unfortunately I no longer support Minecraft version 1.16. Please update to a newer version, it also contains bug fixes that aren't present in version 5.9 of Tree Harvester. Apologies for the inconvenience.
