### ISSUE TITLE
When /gamerule spawnRadius is set to higher than default, players do not receive items.

### ISSUE THREAD

**Issue by AmphyEX** [ricksouth/serilum-mc-mods#1891]
## **Information**
Minecraft version: 1.18.2
Modloader: Forge
Forge version: 40.2.10 
Environment: Singleplayer / Multiplayer

Mod name: Mod
Mod version: 5.2

## **Description**
When /gamerule spawnRadius is set to higher than default, players do not receive items. This can be replicated on a multiplayer server by setting the gamerule spawnRadius to higher than 10. This can be replicated in a singleplayer world with the Global Gamerules mod, and having the gamerule spawnRadius be higher than 10.

**Comment by James103** [comment]
1. Which mod are you referring to? From the description, I assume "Starter Kit."
2. Do you get similar behavior on 1.19.2 on Forge and/or Fabric? When testing on that version (and later), you can change `/gamerule spawnRadius` from the world creation screen > "Edit Game Rules" > scroll down.

**Comment by ricksouth** [comment]
This has been fixed in Collective version 7.9, Starter Kit doesn't need an update. Apologies it took so long for me to get to. Thanks for giving the mod a try!

https://modrinth.com/mod/collective
