### ISSUE TITLE
mod does not work

### ISSUE THREAD

**Issue by 3ZRA2EEL** [ricksouth/serilum-mc-mods#1897]
## **Information**
Minecraft version: 1.16.5
Modloader: Forge
Forge version: xx.xx.xx  OR  Fabric loader version: x.xx.x
Environment: Singleplayer

Mod name: starter structure
Mod version: 1.2

## **Description**
the mod does work at all
the signs don't work the structure always spawns at y=7
i don't spawn at the coordinates I specified

## **Crash report**
_(Please either drag the file directly here, or use https://gist.github.com/ to prevent the paste from expiring)_

If available.

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 3.5 of Starter Structure.

https://curseforge.com/minecraft/mc-mods/starter-structure/files
