### ISSUE TITLE
Deleting and Creating a New World with the Same Name not Giving You the Starter Items (Starter Kit Mod)

### ISSUE THREAD

**Issue by blacknazgul13** [ricksouth/serilum-mc-mods#1902]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 0.226.2.1
Environment: Singleplayer

Mod name: Starter Kit
Mod version: 5.2

## **Description**
So basically, I'm playing a modpack called Medieval Minecraft (the 1.19.2 Forge version), and I noticed that if I deleted my world and made another one with the same name, I didn't get the quest book and starter weapons/armour I got in the first world of that name. One of the devs of that modpack suggested it was an issue with the Starter Kit mod and so I came here to report this issue, since it seems that perhaps when the world is deleted from Minecraft, it isn't deleted from the starter kit mod so it thinks you still have whatever stuff it gave you the first time. I don't know if that's really what's happening but it might be, idk. Of course I could just work around it and make a new name for every new world, but I'd rather be able to keep the name and have things work properly. 

This is me loading into a world with a name I haven't done before:
![2023-07-31_01 05 17](https://github.com/ricksouth/serilum-mc-mods/assets/94561662/f4fc4c5a-8088-4dcc-b18f-664341221199)

And this is me after I deleted that world and made a new world with the same name:
![2023-07-31_01 14 37](https://github.com/ricksouth/serilum-mc-mods/assets/94561662/3f50a861-78f5-41f7-bf22-13e035c45762)

**Comment by EightBitBBQ** [comment]
Did you only delete the world ingame?
If im correct (not at home) there is still an instance in the installation folder with your player data.

You will need to delete that as well. Otherwise the files will be linked. Making it think you already had a Starter kit

**Comment by blacknazgul13** [comment]
Hm, I didn't think about it. What is the default location for those files?

**Comment by EightBitBBQ** [comment]
Depends on your launcher.
Normally they are in your appdata folder.

You can also open the menu resource packs ingame. You should have an option to open the Resource folder.
After that go a folder up and look for a folder called Saves

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 6.0 of Starter Kit, alongside many new features! See the description for more details:

https://curseforge.com/minecraft/mc-mods/starter-kit
