### ISSUE TITLE
mod not working

### ISSUE THREAD

**Issue by wolfie0112** [ricksouth/serilum-mc-mods#1903]
mod loader: forge
version 47.1.43
Minecraft version: 1.20
Environment: Singleplayer 

Mod name: tree harvester
Mod version: 1.20.1-8.2

Hi!

i have the mod tree harvester installed i also have collective but when i try to chop down a tree nothing happens

https://github.com/ricksouth/serilum-mc-mods/assets/141035785/13565f58-502d-4e8c-861f-7be80d71c1ae

**Comment by EightBitBBQ** [comment]
Did you also try crouch chopping the tree?
Or did you change the config?

**Comment by wolfie0112** [comment]
crouch chopping did solve my problem

**Comment by EightBitBBQ** [comment]
Good to hear!

You can always change it in the config file if you want.
Go to the config file and change this option from false to true:

// If enabled, tree harvesting works when not holding the sneak button. If disabled it's reversed, and only works when sneaking.
	"treeHarvestWithoutSneak": false
