### ISSUE TITLE
[1.20.1 Fabric] java.lang.Error: Watchdog at com.natamus.collective_common_fabric

### ISSUE THREAD

**Issue by gamerpotion** [ricksouth/serilum-mc-mods#1905]
Hi,
one of our server users has reported a constant crash on their server and cant make out if this is collective issue or no hostiles around campfire issue.

They are using DarkRPG modpack - https://legacy.curseforge.com/minecraft/modpacks/darkrpg

Issue was originally reported on discord - https://discord.com/channels/1131899131703603343/1135651397967294616
https://discord.gg/suSQ3WmT5S

They wrote the following in the post:-

_Currently running a server using BisectHosting on the lastest version of DarkRPG Fabric, 7.1.5
When playing alone or when all players are in the same area, there has never been a problem. However, when players specifically seem to be off on their own or loading chunks, the server very consistently crashes. I thought it may be due to them using an origin that allows basically Elytra flight, but I recently had them stop using the flight during exploration and the crashes still occur very frequently. Massive lag also begins to occur when someone loads chunks. I've played other modpacks using this host too, and have never seen this issue. The server we're running is also using 18GB of RAM, 10 GB above the recommended. The crash log, however, always shows the same thing. Any idea what this could be?_

Full crash log - https://pastebin.com/p717G41y

**Comment by TigerWalts** [comment]
Also running into this problem on DarkRPG.

It looks like the `FABFunctions.getBlockEntitiesAroundPosition()` method's access to world data is being blocked by a world generation task running in a worker thread.

The user who reported this problem mentions that they are approaching a bastion in the Nether when it happens.

**Comment by ricksouth** [comment]
Thank you for giving the mod a try and opening the issue. This has been fixed in version 7.0 of No Hostiles Around Campfire. Apologies it took so long for me to get to.

https://curseforge.com/minecraft/mc-mods/no-hostiles-around-campfire/files
