### ISSUE TITLE
Not working for brown mushroom after enabling in config

### ISSUE THREAD

**Issue by hatimkapadia2030** [ricksouth/serilum-mc-mods#1910]
## **Information**
Minecraft version: 1.20
Modloader: Fabric
Fabric loader version: 11.0.99
Environment: Singleplayer

Mod name: Mod
Mod version: 8.1

## **Description**
Hey! 
I have enable for huge mushrooms set to true in the config, but tree harvester does not for brown mushrooms.
It works just for the red one's, but not for the brown one. 
All other type also work fine
Assuming this is bug, since I have tried to enable and disable the config and it only does not work for brown ones

**Comment by hatimkapadia2030** [comment]
> Mod: Tree harvester

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 8.5 of Tree Harvester.

https://www.curseforge.com/minecraft/mc-mods/tree-harvester/files
