### ISSUE TITLE
Tree Harvester: Turbo-fast Tree Harvest

### ISSUE THREAD

**Issue by salisiumide** [ricksouth/serilum-mc-mods#1915]
## **Information**
Minecraft version: 1.20.1
Modloader: Forge
Forge version: 47.1.43
Environment: Singleplayer

Mod name: Tree Harvester
Mod version: 8.2

## **Description**
If I use the default settings of the mod, by which I mean that I have to crouch to harvest the entire tree, uncrouching while still mining one of the log blocks speeds up the harvesting speed of that tree, resulting in a bug that lets me harvest the tree quicker _(increaseHarvestingTimePerLog = true)_.

**To recreate:**
1. Approach a tree (preferably a big one, just to see the vast difference), look at one of the log blocks;
2. Crouch and start chopping;
3. Keep chopping, but uncrouch;
4. You should have harvested that tree quicker than normal.
 
I hope this is helpful info.

**Comment by MikiP98** [comment]
I'm using fabric, can confirm and say it also works the other way around.
You can start chopping a tree fast, then crounch for in the last second to cut down the whole tree.

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 9.1 of Tree Harvester. Appreciate it.

https://curseforge.com/minecraft/mc-mods/tree-harvester/files
