### ISSUE TITLE
Create sliding doors and Double doors incompat

### ISSUE THREAD

**Issue by Aquiles089** [ricksouth/serilum-mc-mods#1918]
When opening 2 Create sliding doors when they are side by side, they create a opened sprite even though they are sliding doors, doubling it.

![2023-08-16_02 23 46](https://github.com/ricksouth/serilum-mc-mods/assets/132104320/c7c4a75b-ccde-4618-b35f-d258a4c621d3)

Double doors 5.0
Create 5.1.c
Minecraft 1.18.2
Forge 40.2.10

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! Support for modded doors has been added in version 5.3 of Double Doors.

https://curseforge.com/minecraft/mc-mods/double-doors/files
