### ISSUE TITLE
Double Doors not working in multiplayer

### ISSUE THREAD

**Issue by mi3key** [ricksouth/serilum-mc-mods#1921]
Minecraft version: 1.20.1
Modloader: Forge 
Forge version: 47.1.43
Environment: Singleplayer "**Working**" / Multiplayer "**Not Working**"

Mod name: Double Doors
Mod version: 5.0

Hello, I just downloaded the mod and it's working fine on a single player server. but in both realms and multiplayer it isn't functioning at least for me.
how do I get this fixed?

in case of incompitibality, here is my
Modslist:

Balm
Better Third Person
Better F3
Borderless Window
Cloth Confing v10 API
Collective 6.65
Crafting Tweaks
Double Doors
Equipment Compare
Forge
Iceberg
NotEnoughAnimations
ShulkerBox
Spyglass Improvements
Tiny Item Animations
WaveyCapes

_________________________________________________________________________________________________________________

I also have a feature suggestion for the Fence Doors:
if we place 2 doors next to each others, could you make them become as "One 2 blocks door" and get the middle piece to disappear visually? or at least as a visual option where the middle pieces all visually disappear and the side ones still appear.

Kind Regards

**Comment by ricksouth** [comment]
The problem here is that the mod has to be installed on the server for it to work. It's not client-side only, since it modifies block states. Thanks for giving it a try!
