### ISSUE TITLE
double doors plays the incorrect sound relative to material

### ISSUE THREAD

**Issue by notandvm** [ricksouth/serilum-mc-mods#1922]
## **Information**
Minecraft version: 1.20.1
Modloader: Fabric
Fabric loader version: 0.14.22
Environment: Singleplayer / Multiplayer

Mod name: Double Doors
Mod version: 5.0

## **Description**
when opening a double door/trapdoor/gate made of either crimson, warped, bamboo, cherry, or iron, instead of playing their respective open/close sounds it instead plays the default wooden sound effect used for oak through mangrove wood

while not too noticeable overall it's especially noticeable on iron doors, which doesn't seem intended

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 5.3 of Double Doors.

https://curseforge.com/minecraft/mc-mods/double-doors/files
