### ISSUE TITLE
GUI Clock disappearing when joining new match PVP

### ISSUE THREAD

**Issue by skypsyco-git** [ricksouth/serilum-mc-mods#1923]
Whenever I join a new match in a PVP server the GUI Clock mod randomly disappears. However when I go back to the lobby it magically reappears again. Is there any way for me to fix this such that I can see what time it is while I'm in a match so I know how long I've been playing?

**Comment by James103** [comment]
Which PvP server are you playing on?

**Comment by ricksouth** [comment]
Not something I can fix on my end without extra information. They might have limited the information players can have in the game. Thanks for giving the mod a try nonetheless!
