### ISSUE TITLE
Bone meal that comes from a dispenser does not have random flowers (same issue as closed issue #1398 but for version 1.20.1)

### ISSUE THREAD

**Issue by Malefic007** [ricksouth/serilum-mc-mods#1928]
## **Information**
Minecraft version: x1.20.1
Modloader: Forge 
Forge version: 47.1.3
Environment: Singleplayer 

Mod name: Mod
Mod version: 4.1

## **Description**
As per the prior issue #1398 back in December, using bonemeal via hand or a deployer (create mod) the flowers are random but when used from a dispenser it is vanilla flowers for the given biome only.

Sorry I do not see how to add a label but this is concerning the "Random Bone Meal Flowers" mod

**Comment by ricksouth** [comment]
This has been fixed in version 4.3 of Random Bone Meal Flowers. Thanks for opening the issue and giving the mod a try!

https://www.curseforge.com/minecraft/mc-mods/random-bone-meal-flowers/files
