### ISSUE TITLE
When in dark environments, the mod doesn't work when I press G

### ISSUE THREAD

**Issue by BirdoGunner** [ricksouth/serilum-mc-mods#1929]
## **Information**
Minecraft version: 1.20.1
Modloader: Forge 
Forge version: 47.1.0
Environment: Singleplayer (going to do multi soon)

Mod name: Full Brightness Toggle
Mod version: 3.0

## **Description**
So I put myself in a dark room, no light sources and deep underground. Whenever I press G, I don't get any lighting difference.

It's weird.

**Comment by ricksouth** [comment]
I can't reproduce the issue. Make sure to update the mods to their latest version. If you still have the problem, please open another issue with a log file attached.
