### ISSUE TITLE
[Villager Names] villages should also have names

### ISSUE THREAD

**Issue by PItlosTails** [ricksouth/serilum-mc-mods#193]
okay i really love your mods, i wish they were a bit bigger since you're a great author but that doesnt matter for this suggestion. Since villagers have names i think villages should have names aswell, So if you have ever played on like a minecraft server some servers make it so that when enter a area text pops up with the name of the area, it would be cool if you could do something a la the same where in as you enter a village for the first time, or after a certain time/distance  (as to not make it annoying) maybe even have it configurable and make it so that it syncs with waystones so that instead of waystones having a village name like [random name] plains ect it would be [random name] village or  village [random name], i think it would be a great addition to the mod and make it a lot more popular. also just a tip but you should make the compatiable mod names larger on your mods page because i missed it (and im pretty observante) and i would have downloaded this mod over any other and a lot faster had i seen it, anyway keep being great your mods are awesome ;D

**Comment by ricksouth** [comment]
As of now I won't be adding village names, but you could do it yourself using signs with the following mod:
https://www.curseforge.com/minecraft/mc-mods/areas

Just place it in the middle of the village (can be underground as well) and it should do exactly as described! Thanks for using my mods :)
