### ISSUE TITLE
Questions ( Sleep Sooner ) 1.12.2

### ISSUE THREAD

**Issue by Kasia1403** [ricksouth/serilum-mc-mods#1933]
1. Does this mod work with Millenaire ?
2. Is it possible to set the night time to 22.00 and sleep time to 22.00 ( for player and for Millenaire villagers ) ?

**Comment by Kasia1403** [comment]
What is mod label ?

**Comment by ricksouth** [comment]
No the mod will only work for players. Thanks for the interest!
