### ISSUE TITLE
Heads dont drop (Just Player Heads)

### ISSUE THREAD

**Issue by DasVanish** [ricksouth/serilum-mc-mods#1935]
Hey, I have a minecraft server with some mods. This mod is also on it, but unfortunately the heads don't drop :( I don't know why that could be, so the question is: Are there mods that are incompatible, does the mod not work on servers or do I have to change a certain setting first. The only thing What comes to mind is that the server is in hardcore mode. Maybe that's why? I actually use the mod quite often, so thanks for the ultra nice mod <3

Mod: Just Player Heads

**Comment by James103** [comment]
Do you have the full mod list or a `latest.log`? If so, can you please post it here?

**Comment by DasVanish** [comment]
Mod list: Simple Voice Chat, API architectury, Balm, Collective, Ender Trigon, Hardcore Revival, JEI, Just Player Heads, Mouse Tweaks (not on the Server), Mutant Monsters, Nexus (Tower Defense Battle Mode), Optifne (not on the Server), Puzzel Lib, The End of Herobrine, Walkie Talkie

**Comment by DasVanish** [comment]
Ups that was an accident

**Comment by ricksouth** [comment]
It should work on a server. Which version were you playing on? Still having the issue?
