### ISSUE TITLE
Can't rename villagers

### ISSUE THREAD

**Issue by allanonmage** [ricksouth/serilum-mc-mods#1936]
## **Information**
Minecraft version: 1.19.2
Modloader: Fabric
Fabric loader version: fabric-server-mc.1.19.2-loader.0.14.19-launcher.0.11.2.jar
Environment: Multiplayer

Mod name: Mod
Mod version: 5.2

## **Description**
Hey! This happened. I can't rename villagers.  I'm trying to use Stillagers, a mod, or Silence Me, a datapack from Vanillatweaks.net, and neither can affect villagers.  The names revert back to the villager names from this mod

## **Crash report**
_(Please either drag the file directly here, or use https://gist.github.com/ to prevent the paste from expiring)_

If available.

**Comment by James103** [comment]
For each of the following commands, does the name revert to the default set by Villager Names after running the command?
1. `/data merge entity @e[type=villager,limit=1,sort=nearest] {CustomName:'"12345"'}`
2. `/data merge entity @e[type=villager,limit=1,sort=nearest] {CustomName:'""'}`
3. `/data merge entity @e[type=villager,limit=1,sort=nearest] {CustomName:''}`

**Comment by allanonmage** [comment]
I kept working on it and just came back.  Ultimately, I had to remove the mod for me to get Stillager the nametag to stick.  Now that datapack seems to be working.  I had tried to disable the custom names feature using the config file and it didn't resolve my problem.

I'll reinstall the mod and try those commands.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 6.0 of Villager Names and version 6.80 of Collective.

https://legacy.curseforge.com/minecraft/mc-mods/villager-names/files
https://legacy.curseforge.com/minecraft/mc-mods/collective/files
