### ISSUE TITLE
structure_void blocks ignored

### ISSUE THREAD

**Issue by theshadowake** [ricksouth/serilum-mc-mods#1937]
## **Information**
Minecraft version: 1.18.2
Modloader: Forge
Forge version: 40.2.10
Environment: Singleplayer & Multiplayer

Mod name: Starter Structure
Mod version: 3.1

## **Description**
As title, structure_void blocks are directly placed with the structure instead of keeping the existing block as they do in vanilla structures.

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 3.4 of Starter Structure.

https://curseforge.com/minecraft/mc-mods/starter-structure/files

**Comment by theshadowake** [comment]
Any chance of backporting to 1.18.2 as that's the version bug was present in, thanks.

**Comment by ricksouth** [comment]
Unfortunately I can't, sorry. :\ Since my library also isn't updated for that version, and I'm already keeping 4 sub versions updated
