### ISSUE TITLE
Unconfigureable Name Lists

### ISSUE THREAD

**Issue by RiverHYH** [ricksouth/serilum-mc-mods#1939]
## **Information**
Minecraft version: 1.20.1
Modloader: Forge
Forge version: 47.1.0
Environment: Singleplayer

Mod name: VillagerNames
Mod version: 5.2

## **Description**
Hey! This happened. The TOML file of this mod is missing where there is only a js file. With all the configs options enabled in the js, the mod still can't rename new villagers with name lists in customnames.txt, which is written in Chinese characters and English commas.(As shown in the picture)
![image](https://github.com/ricksouth/serilum-mc-mods/assets/90681811/13372022-8880-4a02-a053-a250df633b25)

## **Crash report**
_(Please either drag the file directly here, or use https://gist.github.com/ to prevent the paste from expiring)_

If available.

**Comment by RiverHYH** [comment]
Some supplementary info for this issue: preset customnames.txt only has 3 names included, but in fact, there are a few unique names in the game that are coming from nowhere. I am just wondering if I amend the files in an incorrect directory.

**Comment by RiverHYH** [comment]
Never mind. I found a closed bug report and fixed it! Thank you for your time! 

> https://github.com/ricksouth/serilum-mc-mods/issues/1356

**Comment by RiverHYH** [comment]
Bug Fixed

**Comment by ricksouth** [comment]
Glad you figured it out! Thanks for giving the mod a try.
