### ISSUE TITLE
1.16.5

### ISSUE THREAD

**Issue by manu1978** [ricksouth/serilum-mc-mods#1943]
Good morning.
I'm a big fan of your mods and I wanted to know if you could release a 1.16.5 version of it.
I don't really like what 1.18/1.20 offers and I went back to an older version of Minecraft.
Thank you.

**Comment by ricksouth** [comment]
I'm currently actively developing 1.18, 1.19 and 1.20. I won't be going back to 1.16. It's not as simple as releasing just one mod, since the library would have to be ported as well. Thanks for the interest though!
