### ISSUE TITLE
Conflicting With The Oculus Mod (Iris Fork For Forge)

### ISSUE THREAD

**Issue by poloniumiscool** [ricksouth/serilum-mc-mods#1944]
## **Information**
Minecraft version: 1.20.1
Modloader: Forge
Forge version: 47.1.46

Mod name: GUI Compass And GUI Clock
Mod version: The Latest

## **Description**
Everytime I Started Up Minecraft It Showed The Forge Loading Screen And While I Was Waiting For The Loading Screen To Load It Crashed!

## **Crash report**

The game crashed whilst initializing game
Error: java.lang.IncompatibleClassChangeError: class net.coderbot.iris.gui.option.ShadowDistanceOption cannot inherit from final class net.minecraft.client.OptionInstance

**Comment by ricksouth** [comment]
Looks to be an issue with the Iris mod. Can't see anything related to GUI Compass/Clock. Thanks for giving them a try and hope you figured out the problem.
