### ISSUE TITLE
Creeper protection for death chest

### ISSUE THREAD

**Issue by janusfenix** [ricksouth/serilum-mc-mods#1950]
## **Information**
Minecraft version: 1.20.1
Modloader: Forge 

Mod name: Your Items Are Safe

## **Feature description**
Currently, creepers render this mod void, because when you die they immediately explode the chest too. Would it be possible to give the chest temporary creeper prevention, or perhaps wait 1 second (or so) before spawning the chest? (Just to give the explosion a chance to subside)

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 4.0 of Your Items Are Safe.

https://curseforge.com/minecraft/mc-mods/your-items-are-safe/files
