### ISSUE TITLE
Remember state between sessions

### ISSUE THREAD

**Issue by esvarc** [ricksouth/serilum-mc-mods#1954]
## **Information**
Minecraft version: 1.19.4
Modloader: Forge

Mod name: Full Brightness Toggle (fullbrightnesstoggle-1.19.4-3.0.jar)

## **Feature description**
Is possible to configure/remember brightness state between sessions? I would like start game with full brightness ON.

**Comment by esvarc** [comment]
Adding details and possible solution. In MC version 1.16.5 was possible to store gamma in options.txt with value **gamma:15.0**. Newer versions of MC ignoring this option and revert to default. So MOD need to store actual value elsewhere preferably in config and restore gamma at every game restart.

Tested on MC V1.20.1 where I manually put gamma:15.0 into options.txt and game ingoring this value. If I set gamma on video options lower than 100% it sets gamma:0.45 and game honor it. It seems there is now internal check for gamma and ignoring value bigger than 1. MOD as is still work, when I use bind key it sets gama to 1500%, but doesn't store it in options.txt, because is bigger than 100%

**Comment by esvarc** [comment]
Update. My fault. I did upgrade to fullbrightnesstoggle-1.20.1-3.2.jar and collective-1.20.1-7.22.jar. Reporting this as fixed. It now remember brigthness state between sessions. 

Thank you! Happy New year to you.

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! Full Brightness Toggle version 4.0 has the fullbright state persistent across game launches. So it'll remember if it was on/off and keep it that way.

https://www.curseforge.com/minecraft/mc-mods/full-brightness-toggle/files
