### ISSUE TITLE
Wandering Winemaker (Vinery) and Wandering Baker (Bakery) Don't Have Names

### ISSUE THREAD

**Issue by RiftSpatial** [ricksouth/serilum-mc-mods#1959]
## **Information**
Minecraft version: 1.19.2
Modloader: Fabric
Fabric loader version: 0.14.22
Environment: Singleplayer / Multiplayer

First mod name: Villager Names
First mod version: 5.2

Second mod name: Vinery/Bakery
Second mod version: 1.3.9/1.0.6

## **Description**
Currently, the Wandering Winemaker and Wandering Baker do not receive names. If you can add compatibility for Vinery and Bakery, that'll be great!

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been added in version 6.0 of Villager Names and version 6.80 of Collective. :)

https://legacy.curseforge.com/minecraft/mc-mods/villager-names/files
https://legacy.curseforge.com/minecraft/mc-mods/collective/files
