### ISSUE TITLE
1.19.2 - Does not work while ``holding something to shift right click``

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [ricksouth/serilum-mc-mods#1960]
I am not filling out a giant form for a basic issue. The solution is add support while holding something for shift right click right now it only works with empty hand. Easy example is my sword.

**Comment by P3rf3ctXZer0** [comment]
Thank you :)

**Comment by ricksouth** [comment]
That "giant form" is because there are many mods that use the same issue tracker and the information is a necessity.

**Comment by P3rf3ctXZer0** [comment]
I know :) Its just in this case it was straight forward as a creator I understand. In actual issues I do report correctly ;)
