### ISSUE TITLE
Brown Mushrooms can't  be harvested

### ISSUE THREAD

**Issue by Hng-Vit** [ricksouth/serilum-mc-mods#1962]
### ## **Information**
Minecraft version: 1.20.1
Modloader: Fabric
Fabric loader version: 0.14.21
Environment: Singleplayer 

Mod name: Tree Harvester
Mod version: 8.2

## **Description**
I have changed over and over again the settings but the mod doesn't work for big brown mushrooms like the descriptions, but the red ones are okay. Can you fix it ?

## **Crash report**
_(Please either drag the file directly here, or use https://gist.github.com/ to prevent the paste from expiring)_

If available.

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 8.5 of Tree Harvester.

https://www.curseforge.com/minecraft/mc-mods/tree-harvester/files
