### ISSUE TITLE
[double doors] Doors are getting triggered from a button 2 blocks away

### ISSUE THREAD

**Issue by jinkhya** [ricksouth/serilum-mc-mods#1966]
## **Information**
Minecraft version: 1.20.1
Modloader: Forge
Forge version: 47.1.3
Environment: Singleplayer and Multiplayer

Mod name: Double Doors
Mod version: 5.0

## **Description**
When pressing a button 2 blocks away to minimum 2 connected trapdoors or doors, it closes them. 
Here is a video of what happens : https://streamable.com/9zzv5s

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 5.3 of Double Doors.

https://curseforge.com/minecraft/mc-mods/double-doors/files
