### ISSUE TITLE
Can't use /st without OP

### ISSUE THREAD

**Issue by Nihilanthy** [ricksouth/serilum-mc-mods#1968]
## **Information**
Minecraft version: 1.20
Modloader: Fabric
Fabric loader version: 0.14.22
Environment: Server

Mod name: Silence Mobs
Mod version: 1.20.0-3.0

## **Description**
I can't use the /st or /silencestick when i'm not on OP, is there any permission required?

## **Crash report**
No crashes

**Comment by ricksouth** [comment]
You can set in the config whether everyone or only OP'd players can use the command. Thanks for giving the mod a try!
