### ISSUE TITLE
Possibility to allow non-op players to use /jph commands

### ISSUE THREAD

**Issue by Bwapt** [ricksouth/serilum-mc-mods#1969]
## **Information**

Minecraft version: 1.20.1
Modloader: Fabric
Fabric loader version: 0.14.22
Environment: Multiplayer

Mod name: Just Player Heads
Mod version: 3.1

## **Question**
Is it possible to allow non-op players to use /jph commands on Fabric server ? I tried to use Luckperms to share commands to non-op players but Just Player Heads doesn't seems to be linked to Luckperms, at least this is what I think with the small knowledge I have...

**Comment by ricksouth** [comment]
Due to the difficulty of dependent mods, and not much usage, I unfortunately don't support permission nodes. The user will have to be OP'd to use the commands. Apologies for the inconvenience.
