### ISSUE TITLE
Spawning outside of bunker

### ISSUE THREAD

**Issue by BlueDuckYT** [ricksouth/serilum-mc-mods#1970]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge 
Forge version: 43.2.23
Environment: Singleplayer / Multiplayer

Mod name: Starter Structure
Mod version: 3.1

## **Description**
When trying to make the player spawn in an underground bunker, the player sometimes spawns in a nearby cave. When the player spawns in the bunker, it is always in the same far corner. Modifying the spawn offsets seems to change structure placement and doesn't solve the issue. I used a structure block to create the structure.

**Comment by ricksouth** [comment]
Sorry for the late response. Could you upload the .nbt file you used?

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 3.5 of Starter Structure.

https://curseforge.com/minecraft/mc-mods/starter-structure/files
