### ISSUE TITLE
Random Village Names - Cant find config

### ISSUE THREAD

**Issue by LordDecay26** [ricksouth/serilum-mc-mods#1971]
Minecraft version: 1.19.2
Modloader: Forge /
Forge version: 43.2.3

Mod name: Random Village Names
Mod version: 3.2

## **Question**
please tell me the directory for the config file. i cant find it.

**Comment by ricksouth** [comment]
The mod doesn't have config files. If you'd like to make changes to how the text disappears, that can be done via Areas. Thanks for giving the mod a try!

**Comment by LordDecay26** [comment]
cant find the areas mod config either.
