### ISSUE TITLE
Do I need the client side mod to for people to see the features on a server?

### ISSUE THREAD

**Issue by Noahfrechette** [ricksouth/serilum-mc-mods#1975]
Do I need the client side mod to for people to see the features on a server? in the mod Beautified Chat

**Comment by James103** [comment]
Which mod or mods are you referring to?

**Comment by Noahfrechette** [comment]
Beautified Chat

**Comment by Noahfrechette** [comment]
@ricksouth can you help @James103 or you?

**Comment by James103** [comment]
Do you have the mod titled "Beautified Chat [Server]" on the server? That mod is the server-side implementation of Beautified Chat which changes the chat message format for all players, including vanilla players. In contrast, "Beautified Chat [Client]" is designed to be used client-side.

**Comment by Noahfrechette** [comment]
so I need the client side mod aight

**Comment by Noahfrechette** [comment]
@James103 wait is the client side mod needed aswell?

**Comment by ricksouth** [comment]
If you'd like to have all players in a server see it, pick the server mod. If you want only you to see the different chat, choose the client one. For the server mod, players don't have to have it installed on the client.
