### ISSUE TITLE
Your Items Are Safe- chest fails to generate when player dies in the void

### ISSUE THREAD

**Issue by TheHypeTrain** [ricksouth/serilum-mc-mods#1979]
## **Information**
Minecraft version: 1.20.1
Modloader: Fabric
Fabric loader version: 0.14.22
Environment: Singleplayer 

Mod name: Your Items Are Safe
Mod version: 1.20.1-3.4

## **Description**
Whenever I die in the void, I cannot find the chest or armour stand.

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 4.0 of Your Items Are Safe. The chest is created above the death coordinates, with a cobblestone platform.

https://curseforge.com/minecraft/mc-mods/your-items-are-safe/files
