### ISSUE TITLE
[1.20.1] [NHACF] crash when a villager transforms

### ISSUE THREAD

**Issue by Bass2style** [ricksouth/serilum-mc-mods#1984]
## **Information**
Minecraft version: 1.20.1 (not tested on other versions of the game)
Modloader: Forge
Forge version: 47.2.1
Environment: Singleplayer (not tested in smp environment.)

Mod name: No Hostile Around Campfire
Mod version: 5.6

## **Description**
when a zombie can travel to a villager located around a campfire, and transform it into a zombie villager, the game crash.
when you come back, you have the zombie and the zombie villager from the transformed villager.

## **Crash report**
i provide a few of them, tryed the bug a lot of time, and it's happening everytime.

[crash-2023-10-08_22.31.22-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/12841708/crash-2023-10-08_22.31.22-server.txt)
[crash-2023-10-08_22.37.25-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/12841709/crash-2023-10-08_22.37.25-server.txt)
[crash-2023-10-08_21.52.16-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/12841710/crash-2023-10-08_21.52.16-server.txt)
[crash-2023-10-08_22.20.17-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/12841711/crash-2023-10-08_22.20.17-server.txt)

it's actually being worked by YT, but here is a record : https://www.youtube.com/watch?v=2JeOJtEtxbY

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 5.9 of No Hostiles Around Campfire.

https://curseforge.com/minecraft/mc-mods/no-hostiles-around-campfire/files
