### ISSUE TITLE
Permission nodes?

### ISSUE THREAD

**Issue by Nymorph** [ricksouth/serilum-mc-mods#1985]
What are the Permission nodes so i can add ec cmds to ranks?

**Comment by James103** [comment]
What mod are you referring to with the "ec cmds"?

**Comment by Nymorph** [comment]
The enchant command.

**Comment by Nymorph** [comment]
The enchant mod

**Comment by ricksouth** [comment]
Due to the difficulty of dependent mods, and not much usage, I unfortunately don't support permission nodes. The user will have to be OP'd to use the commands. Apologies for the inconvenience.
