### ISSUE TITLE
Infinite Trades mod won't turn off 

### ISSUE THREAD

**Issue by alfa98516** [ricksouth/serilum-mc-mods#1986]
## **Information**
Minecraft version: 1.20.1
Modloader: Fabric
Forge version: xx.xx.xx  OR  Fabric loader version: 0.14.22
Environment: Singleplayer 

Mod name: Infinite Trades
Mod version: 1.20.1-4.0

## **Description**
I wanted to play around with this mod for a bit, but then decided i didn't want to have infinite trades anymore, first i went into the mod config to turn off the infinite trades function, but that didn't work, so i naturally uninstalled the mod, but the problem resisted, all my current villagers always have infinite trades

**Comment by alfa98516** [comment]
If you replace the villagers work block, it disables infinite trading, silly me

**Comment by ricksouth** [comment]
Glad you figured out a solution :) Thanks for giving the mod a try.
