### ISSUE TITLE
Bug: chat messages not logged in console

### ISSUE THREAD

**Issue by Nicolol1234** [ricksouth/serilum-mc-mods#1989]
## **Information**
Minecraft version: 1.20.1
Modloader: Fabric
Fabric loader version: loader.0.14.22-launcher.0.11.2
Environment: Multiplayer

Mod name: beautifiedchatserver
Mod version: 1.20.1-2.2

## **Description**
When a player write a message in chat, it doesn't appear in console

**Comment by james-ben** [comment]
Same issue on
Minecraft version: 1.20.4
Modloader: Fabric
Fabric loader version: loader.0.15.3-launcher.0.11.2.jar
Environment: Multiplayer

Mod name: beautifiedchatserver
Mod version: 1.20.4-2.4

**Comment by ricksouth** [comment]
Thanks for opening the issue. This has been fixed in version 2.5 of Beautified Chat Server. Apologies it took so long for me to get to.

https://curseforge.com/minecraft/mc-mods/beautified-chat-server/files
