### ISSUE TITLE
Mod isn't working for me, might be because of other mods

### ISSUE THREAD

**Issue by Commodares** [ricksouth/serilum-mc-mods#1990]
## **Information**
Minecraft version: 1.20.1
Modloader: Fabric
Fabric loader version: 0.14.22-1.20.1
Environment: Singleplayer

Mod name: Areas
Mod version: 5.0

## **Description**
So after placing signs and using the correct format = [Area] 50...etc, I try to move in and out of the space the sign would normally activate but it won't work. It does work when I enter different biomes and dimensions like the nether. I think it might be because of another mod though. I'm feeling like it has something to do with VanillaRefresh or VTweaks, but I haven't tested that yet. Apologies for the trouble. :(, Thank you for your time.
![Screenshot 2023-10-11 184253](https://github.com/ricksouth/serilum-mc-mods/assets/147668587/1121aed6-c2cf-48d9-9b84-7b5ab8696dc6)

**Comment by ricksouth** [comment]
I unfortunately can't fix the issue by just seeing the mod list. Apologies for the inconvenience. If you find the other incompatible mod out, I can take a look
