### ISSUE TITLE
Multiplayer compatibility (Replanting Crops)

### ISSUE THREAD

**Issue by leviathan13** [ricksouth/serilum-mc-mods#1994]
## **Information**
Minecraft version: 1.20.1
Modloader: Fabric
Fabric loader version: 0.14.22
Environment: Multiplayer

Mod name: Replanting Crops
Mod version: 5.1

Is this mod just client-side or must it be added on the server-side as well? I can't make it work on a multiplayer server, but it does work in single-player which makes me think that unfortunately is the latter.

**Comment by ricksouth** [comment]
Apologies for the late response. The mod is server-side only. It can't be used to replant crops on a server where it isn't installed. Singleplayer works since it simulates a server in the background. Thanks for the interest!

**Comment by Banderi** [comment]
> Apologies for the late response. The mod is server-side only. It can't be used to replant crops on a server where it isn't installed. 

Please, PLEASE add this information to the mod's pages. This is extremely crucial information that needs be in the mods descriptions.
