### ISSUE TITLE
JPH Cache command not work

### ISSUE THREAD

**Issue by CronaG** [ricksouth/serilum-mc-mods#1997]
## **Information**
Minecraft version: 1.16.5
Modloader: Forge
Forge version: 36.2.39
Environment: Multiplayer

Mod name: Just Players Heads
Mod version: 2.0

## **Description**
At first everything was fine but a few days ago the jph cache command started to stop working, every time I run it it gives me the following error

[20:09:54] [Server thread/INFO] [minecraft/DedicatedServer]: Unknown or incomplete command, see below for error
[20:09:54] [Server thread/INFO] [minecraft/DedicatedServer]: jph cache<--[HERE]

## **Logs**

[debug.log](https://github.com/ricksouth/serilum-mc-mods/files/12920638/debug.log)
[latest.log](https://github.com/ricksouth/serilum-mc-mods/files/12920639/latest.log)

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 3.4 of Just Player Heads.

https://curseforge.com/minecraft/mc-mods/just-player-heads/files
