### ISSUE TITLE
Death delay when using the just player heads mod

### ISSUE THREAD

**Issue by kuba26038** [ricksouth/serilum-mc-mods#2010]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge 
Forge version: 43.3.2
Environment: Singleplayer / Multiplayer (happens in both)

Mod name: just player heads
Mod version: justplayerheads-1.19.2-3.1

## **Description**
it's been something that's been bothering me for a while now. basically, whenever i die, the game lags out for a second or two, before continuing as usual.

it can be recreated by using just the mod and collective, no other mods are needed

here's a clip of me dying right after i joined the game, then dying again, to showcase that it only happens when you die for the first time when you join a world/server: 

https://github.com/ricksouth/serilum-mc-mods/assets/81324988/19be40a7-4ad0-4d32-9ef2-3863e42095e3

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 7.38 of Collective and 3.6 of Just Player Heads. It now caches the player head on login, so it doesn't need to make any query when a player dies.

https://curseforge.com/minecraft/mc-mods/just-player-heads/files
