### ISSUE TITLE
Blacklist for flower mimics

### ISSUE THREAD

**Issue by Sunconure11** [ricksouth/serilum-mc-mods#2022]
## **Information**
Minecraft version: 1.19.2
Modloader: Quilt

Mod name: Flower mimics

## **Feature description**
One should be able to blacklist certain flowers from this mod from being affected by flower mimics. I could see this being screwy with Botania, for instance.

**Comment by ricksouth** [comment]
Version 1.1 makes sure modded flower blocks don't spawn mimics by default. This can be added in the config. That should solve any functional flower issues. Thanks for the suggestion!

https://curseforge.com/minecraft/mc-mods/flower-mimics/files
