### ISSUE TITLE
No Hostiles Around Campfire Server Thread Usage Way Too High

### ISSUE THREAD

**Issue by RegalRuffRaff** [ricksouth/serilum-mc-mods#2026]
## **Information**
Minecraft version: 1.20.1
Modloader: Forge
Forge version: forge-1.20.1-47.2.4
Environment: Singleplayer

Mod name: No Hostiles Around Campfire
Mod version: 5.6

Collective Version: 6.72 + 6.80

## **Description**
With the No Hostiles Around Campfire mod, the game seems to constantly check any structure campfires from structure mods. This causes some stuttering. The initial chunks loaded through making a world are the only chunks that seem to work normally. I have checked the new Collective version too, the issue persists.

## **Crash report**
N/A

## **Chunk Lag Via Spark Profile**
![Serili2](https://github.com/ricksouth/serilum-mc-mods/assets/76569328/5d1a3e08-ec78-4406-a424-ffc3c72d8f96)
![Serili](https://github.com/ricksouth/serilum-mc-mods/assets/76569328/e36b834e-c22f-4ef9-ac0e-59a94d5bd8e6)

**Comment by James103** [comment]
Do you get a similar lag if you
1. Create a new world,
2. Don't include any modded structures (leaving only vanilla structures),
3. Run `/fill ~-10 ~-10 ~-10 ~9 ~9 ~9 minecraft:campfire`, and wait?

**Comment by RegalRuffRaff** [comment]
1. New worlds drop frames if near naturally spawned Vanilla campfires (I checked with a Taiga Village)
2. Tried with no modded structures at all, similar results.
3. Waiting around with that /fill still has major lag. I dropped from 120+(I set my fps to that) to a consistent 2-4fps.

**Comment by Arutheed** [comment]
Same issue. NHAC has an even higher thread load than create, while standing in a massive chunkloaded factory (~10x10 chunks) with at maximum 2-3 manually placed campfires in that area (and no other chunks loaded or players online). I'd also like to add, that the config is set to only block spawns on burning campfires.

Sorry, should add:
Minecraft 1.19.2
Forge
Mod vers 5.9

I also believe it's an compatibility issue, as I'm pretty sure this issue only developed in the last couple of weeks, so probably some other mod update that is causing issues? 
Maybe InControl?

**Comment by ricksouth** [comment]
Thank you for giving the mod a try and opening the issue. This has been fixed in version 7.0 of No Hostiles Around Campfire. Apologies it took so long for me to get to.

https://curseforge.com/minecraft/mc-mods/no-hostiles-around-campfire/files
