### ISSUE TITLE
Please remove NeoForge Tag

### ISSUE THREAD

**Issue by TarantelTM** [ricksouth/serilum-mc-mods#2028]
## **Information**
Minecraft version: 1.20.2
Modloader: NeoForge
NeoForge version: 1.20.2-1.20.X
FML Version: 1.X
Environment: Singleplayer / Multiplayer

Mod names: [Collective, Villager Names, Areas, 
Current Game Music Track, Pet Names, Sleep Sooner, Flower Mimics]
Mod version: latest

## **Description**
Currently all Mods i named here are incompatible with NeoForge in 1.20.2.
But all Mods newest Versions are listed as 1.20.2 who supports NeoForge, Forge, Fabric and Quilt.
Forge works.
Quilt and Fabric works too.
NeoForge cant work.
NeoForge and Forge are complete different Modloaders in 1.20.2.
Please remove the NeoForge Tag in your Modfiles in Curseforge so ppl dont get irritated.
If Curseforge add official Support for NeoForge inside the Launcher u get a lot of Issue Reports for your Mods from ppl who try to run them on NeoForge.

**Comment by ricksouth** [comment]
I am aware. I set that tag before they planned on doing a breaking change for 1.20.2. As soon as Multiloader Template is updated I'll be supporting NeoForge. I'm not going to remove 150+ tags on the mod files manually. But appreciate the concern.

**Comment by ricksouth** [comment]
I've just released an update for all files so they're compatible with the new NeoForge. They're still in the same jar :)
