### ISSUE TITLE
Used to be able to sneak to do default/vanilla behavior of opening just one door/trap/gate, can't anymore?

### ISSUE THREAD

**Issue by HatTrkPatrk** [ricksouth/serilum-mc-mods#2030]
## **Information**
Minecraft version: 1.20.2
Modloader: Fabric
Fabric loader version: 0.14.24
Environment: Multiplayer

Mod name: Double Doors
Mod version: 5.0

## **Description**
As long as I can remember I was always able to sneak and right-click on a door/trapdoor/fencegate to bypass the mod's recursive behavior and just open only the one I was pointing/looking at. I don't exactly know when it changed but I can't do this anymore.

## **Crash report**
_(Please either drag the file directly here, or use https://gist.github.com/ to prevent the paste from expiring)_

If available.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 5.3 of Double Doors.

https://curseforge.com/minecraft/mc-mods/double-doors/files
