### ISSUE TITLE
Question about Pet Names and Villager Names mod.

### ISSUE THREAD

**Issue by Minebrah** [ricksouth/serilum-mc-mods#2032]
If I use the mods, and the mobs are given names, does that mean they are given a nametag and therefore cannot despawn? Will having alot of mobs that cannot despawn lead to mob count issues, like where more mobs won't spawn because there is already alot of persistent mobs around? Is there any way to make named baby mobs despawn or is this already a vanilla mechanic?

**Comment by ricksouth** [comment]
In vanilla Minecraft, passive mobs already don't despawn. So the names wouldn't influence that game mechanic. Should be all good. Thanks for giving the mod a try!
