### ISSUE TITLE
Biome Spawn Point - No flooded caves at spawn?

### ISSUE THREAD

**Issue by generikb** [ricksouth/serilum-mc-mods#2036]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.20.1
Modloader: Forge

Mod name: Biome Spawn Point

## **Question**
I'm putting together a modpack and was hoping that Biome Spawn Point might help with a conundrum I'm having (if not, maybe you have suggestions for an alternate solution)

In a nutshell, I want to make sure that the player spawns in an area that does *not* have flooded caves.  They'll only have access to a "starting chunk" at first, and it would be a nightmare to force a player to have to de-flood an underground lake just to access the lower levels.

Thanks for your help!

**Comment by ricksouth** [comment]
Unfortunately this is a bit outside of the scope of the mod. It doesn't have any "don't include" functionality. It basically uses the logic of the /locate biome command, and sets the world spawn to that location.

I do have the mod https://legacy.curseforge.com/minecraft/mc-mods/starter-structure available. You could make a structure file of the entire chunk, and use that? Though it maybe wouldn't have the randomized ability you're looking for.

**Comment by generikb** [comment]
No worries, thanks for the reply!  I *might* have at least reduced the chance of it by selecting specific cave biomes using Biome Spawn Point.  A janky workaround, but pretty much everything is janky with Modded Minecraft haha

Thanks again!

**Comment by ricksouth** [comment]
I _could_ of course whip up a "No Flooded Caves At Spawn"-type of mod 🤔 It would be able to just replace the water blocks below a certain y-level in the spawn chunk. Would it matter if there were still flooded caves beyond that?

**Comment by generikb** [comment]
It would be kinda weird if it were only the starting chunk, ya.  Don't worry about it! I tested several new worlds with my cave biome selections and it seemed to work.  Not looking for perfection, really appreciate it though!

**Comment by ricksouth** [comment]
Good! Glad the mod has been useful, thanks for giving it a try :)
