### ISSUE TITLE
Bugs with Aether mods

### ISSUE THREAD

**Issue by minecraftscy** [ricksouth/serilum-mc-mods#2038]
## **Information**
Minecraft version: 1.20.1
Modloader: Forge
Forge version: 47.1.43
Environment: Singleplayer

Mod name:   Starter Kit
Mod version: 5.2

## **Description**
Forge 1.20.1 Returning from the mod aether dimension will give the item again, and swallow the armor and off-hand items

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 6.0 of Starter Kit, alongside many new features! See the description for more details:

https://curseforge.com/minecraft/mc-mods/starter-kit
