### ISSUE TITLE
game crashes when loading world with random village names

### ISSUE THREAD

**Issue by Zer0c00L6981** [ricksouth/serilum-mc-mods#2039]
## **Information**
Minecraft version:23w45a
Modloader: Fabric
Forge version: xx.xx.xx  OR  Fabric loader version: 0.14.24
Environment: Singleplayer

Mod name: Random Village Names
Mod version: [Fabric/Forge/Neo] 1.20.2-3.4

## **Description**
anytime i try to load mod game crashes after loading world.

## **Crash report**
[latest.log](https://github.com/ricksouth/serilum-mc-mods/files/13325567/latest.log)

If available.

**Comment by ricksouth** [comment]
Snapshots aren't officially supported, does the crash also happen on 1.20.2?

**Comment by Zer0c00L6981** [comment]
the crash only happens in this world
i have a virgin world also same version running the same datapacks and mods that loads just fine

**Comment by Zer0c00L6981** [comment]
[latest.log](https://github.com/ricksouth/serilum-mc-mods/files/13325920/latest.log)

**Comment by Zer0c00L6981** [comment]
![Capture](https://github.com/ricksouth/serilum-mc-mods/assets/99812085/c2ca26f7-2934-4b2e-82ea-d853e8eecabb)
your other plugins work perfect.

**Comment by Zer0c00L6981** [comment]
i had some errors in which data pack i downloaded, however with the correct installs, i have same issue. please disregard last latest log and use this one.
[latest.log](https://github.com/ricksouth/serilum-mc-mods/files/13325965/latest.log)

**Comment by ricksouth** [comment]
I can't replicate this unfortunately, sorry. Please let me know if it still happens on non-snapshots. Closing this for now.
