### ISSUE TITLE
[Villager Names] Bug Causes Server Crash - java.lang.NoSuchFieldError: femalenames

### ISSUE THREAD

**Issue by skeddles** [ricksouth/serilum-mc-mods#2041]
## **Information**
Minecraft version: 1.20.2
Modloader: Fabric
Fabric loader version: 0.14.24
Environment: Multiplayer

Mod name: Villager Names
Mod version: villagernames-1.20.2-5.2

## **Description**
My server started crashing when someone entered a specific area. If other people went to that area, it also caused it to crash.

Removed the mod from the server and was able to log back in (still at the crashing area) and it loaded fine without crashing.

## **Crash report**
[crash-2023-11-13_17.03.29-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/13338397/crash-2023-11-13_17.03.29-server.txt)

**Comment by ricksouth** [comment]
Thanks for giving the mod a try! I see you updated Collective, but please update Villager Names as well. That'll fix the issue.
