### ISSUE TITLE
Mod Incompatibility  - Simply Swords manual still spawns at character creation

### ISSUE THREAD

**Issue by MLMII** [ricksouth/serilum-mc-mods#2042]
The Runic Grimore from simply swords is still added to the character's inventory even with the 'add extra items after kit' option trued false.  For reference I also have the 'starting kit' set as empty.

Thank you for your time.

Quilt 1.20.1

https://modrinth.com/mod/simply-swords

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 6.0 of Starter Kit, alongside many new features! See the description for more details:

https://curseforge.com/minecraft/mc-mods/starter-kit
