### ISSUE TITLE
Villagers do not show with names.

### ISSUE THREAD

**Issue by Andy608** [ricksouth/serilum-mc-mods#2044]
## **Information**
Minecraft version: 1.20.1
Modloader: Forge
Forge version: 47.1.47
Environment: Multiplayer

Mod name: Villager Names
Mod version: 7.0

## **Description**
Hello, I installed this mod and noticed that villagers do not have any names over their heads. I have tried on a few different forge versions as well as Villager Names version 6.4 and 7.0. 

Do I need to do anything special to get them working or should the names be on by default?

**Comment by ricksouth** [comment]
It should just work when installed. Do you have Collective as well? Did you install any other mods that modify villagers?
