### ISSUE TITLE
[Villager Names] Names are never Capitalized

### ISSUE THREAD

**Issue by wrsgwergergwer** [ricksouth/serilum-mc-mods#2052]
Minecraft version: 1.20.2
Modloader: Fabric
Fabric loader version: 0.14.24
Environment: Singleplayer / Multiplayer

Mod name: Villager Names
Mod version: 7.0

Description:
Regardless of how customnames.txt is formatted, the villagers never recieve the names properly capitalized.

**Comment by akra73** [comment]
Same with the Forge modloader on 1.20.1

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 7.1 of Villager Names. Apologies for any inconvenience.

https://curseforge.com/minecraft/mc-mods/villager-names
