### ISSUE TITLE
Villager names just crashes

### ISSUE THREAD

**Issue by Arathorne** [ricksouth/serilum-mc-mods#2053]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 43.2.23 
Environment: Singleplayer maybe Multiplayer

Mod name: Mod Villager Names
Mod version: villagernames-1.19.2-7.0

## **Description**
Hello, whenever i tried to spawn a villager, it causes to crash minecraft, i didnt have any custom names

## **Crash report**
[debug.log](https://github.com/ricksouth/serilum-mc-mods/files/13401390/debug.log)
[latest.log](https://github.com/ricksouth/serilum-mc-mods/files/13401392/latest.log)
[crash-2023-11-18_20.59.39-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/13401395/crash-2023-11-18_20.59.39-server.txt)

**Comment by ricksouth** [comment]
Looks like it's a problem with the Female Villagers mod, that is still using old Villager Names code. Could you open an issue on their side?

**Comment by ricksouth** [comment]
A solution for now would be to either remove Female Villagers, or downgrade Villager Names to version 5.x

**Comment by Arathorne** [comment]
Damn, ok, let me look if female villagers are updated, if not im opening an issue on their side

**Comment by ricksouth** [comment]
They'll have to update their mod, nothing I can do on my end unfortunately.
