### ISSUE TITLE
Harvester not working

### ISSUE THREAD

**Issue by Lukatony1000** [ricksouth/serilum-mc-mods#2054]
## **Information**
Minecraft version: 1.20.1
Modloader:  Fabric
  Fabric loader version: 0.14.22
Environment: Singleplayer 

Mod name: Treeharvester
Mod version: 8.3

## **Description**
Hey! This happened.
> installed the mod with a modpack(didnt kow it was in but happy for it)
> go into same singleplayer world 
>instant leaf decay and tree harvester not working
>new World same issue
>reinstall mod(found out i had this installed)
>same issue(but now fast leaf decay not instant
>look into config
>cant find instantly break leaves around in json file
> still no harvester
>pls help

**Comment by ricksouth** [comment]
Did you install Collective as well? Can you post the log?

**Comment by The-furf-of-July** [comment]
Are you pressing shift while mining?
