### ISSUE TITLE
Chocolate Milk Logic

### ISSUE THREAD

**Issue by Sweek9** [ricksouth/serilum-mc-mods#2055]
## **Information**
Minecraft version: 1.20.2
Modloader: Forge

Mod name: Healing Soup

## **Feature description**
The Chocolate Milk recipe is weird; where's the milk and sugar? My suggestion would be to add sugar to the recipe, and make it produce an inconsumable bowl of Chocolate Powder instead of Chocolate Milk. Then when the bowl of Chocolate Powder is used on a normal cow it becomes the Chocolate Milk item. Using the bowl on the cow parallels with how one can use a bowl on a mooshroom to obtain Mushroom Stew.

**Comment by ricksouth** [comment]
The mod is a throwback to the mcpvp.com server, from a while ago. I'm not planning on changing the recipe. Thanks for the suggestion though!
