### ISSUE TITLE
Healing Soup Scope

### ISSUE THREAD

**Issue by Sweek9** [ricksouth/serilum-mc-mods#2056]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.20.2
Modloader: Forge
Forge version: 48.0.39
Environment: Singleplayer

Mod name: Healing Soup
Mod version: 4.1

## **Question**
Does this mod also change the Mushroom Stew obtained from using an empty bowl on a mooshroom to the 4 heart healing Mushroom Soup (or just the crafting recipe)? Does the Cactus Stew and/or Chocolate Milk also have healing? Are there name changes and/or healing added to Suspicious Stews, Beetroot Soup, and/or Rabbit Stew?

**Comment by ricksouth** [comment]
Normal stew heals hearts. Cactus soup and chocolate milk heal too. Other stews aren't changed.
