### ISSUE TITLE
[Vanilla Zoom] [Bug] Spyglass appears in your offhand even if you don't have one in your inventory

### ISSUE THREAD

**Issue by leftbones** [ricksouth/serilum-mc-mods#2061]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 43.3.5
Environment: Singleplayer

Mod name: Vanilla Zoom
Mod version: 1.19.2-2.2

## **Description**
If you press the zoom hotkey without a spyglass in your inventory, your player will still hold the spyglass in their offhand, they just won't use it. Releasing the key makes it go away like normal.

Not sure if this is a bug or intended behavior.

**Comment by ricksouth** [comment]
Yes this is intended. It simulates the player using it. Thanks for giving the mod a try!
