### ISSUE TITLE
Tree Harvester: "Find Bottom Block" option doesn't work

### ISSUE THREAD

**Issue by robosoup2** [ricksouth/serilum-mc-mods#2067]
Minecraft version: 1.20.1
Modloader: Forge
Forge version: 47.2.6
Environment: Singleplayer

Mod name: Tree Harvester
Mod version: 1.20.1-8.3

If I mine a block which isn't at the bottom of the tree, it destroys the whole tree without leaving a stump. This happens whether the option is toggled on or off, even if i reload the world.
tested with no other mods.

**Comment by Orhun365** [comment]
I still have the same issue when will this be fixed?

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 9.1 of Tree Harvester. Appreciate it.

https://curseforge.com/minecraft/mc-mods/tree-harvester/files
