### ISSUE TITLE
Map color should not be used to check for metal doors

### ISSUE THREAD

**Issue by XFactHD** [ricksouth/serilum-mc-mods#2070]
## **Information**
Minecraft version: 1.20.1/1.20.2
Modloader: Both
Forge/Fabric version: any
Environment: Both

Mod name: Double Doors
Mod version: any 1.20.1 or 1.20.2 version

## **Description**
Double Doors currently uses the `MapColor` of the door/trapdoor/fence gate that was clicked to determine whether it can be opened by hand. This is a bad idea in the light of modded doors that may be made from some non-iron metal and therefore use a different map color but should still behave like iron doors. Instead of checking the map color, the `BlockSetType` should be retrieved from the door or trapdoor to then call `BlockSetType#canOpenByHand()` for this check.

**Comment by ricksouth** [comment]
Thanks! This has also been fixed. Not sure why the BlockSetType is protected/private for trap doors, but oh well. Had to add some AT's. Updated in Collective 7.37 and Double Doors 5.4.

https://curseforge.com/minecraft/mc-mods/double-doors/files
