### ISSUE TITLE
Double Doors breaks camo application on FramedBlocks framed doors

### ISSUE THREAD

**Issue by XFactHD** [ricksouth/serilum-mc-mods#2071]
## **Information**
Minecraft version: 1.20.1
Modloader: Forge
Forge version: any
Environment: Both

First mod name: Double Doors
First mod version: any 1.20.1 version

Second mod name: FramedBlocks
Second mod version: any 1.20.1 version

## **Description**
FramedBlocks applies block camos in `Block#use()`. Due to Double Doors using the interaction events to add its functionality and those firing before the block's own use code is called, my code is entirely bypassed when two framed doors or framed trapdoors are placed next to each other, therefore preventing camo application. The only way I have seen this kind of feature implemented that is compatible with additional behaviour in `Block#use()` is to do this in a mixin into `DoorBlock#use()` and `TrapDoorBlock#use()`. Unfortunately I can't think of any better solution to this problem and as such I'm opening this issue more as documentation and not necessarily with the expectation of it being fixed.

**Comment by ricksouth** [comment]
Thanks for opening the issue and providing the solution to add compatibility! Appreciate it. I've moved away from the event in favour of mixins and the mods are now compatible in version 5.3 of Double Doors.

https://curseforge.com/minecraft/mc-mods/double-doors/files

![6748464eb0bf0eb338dc3489aae21f67](https://github.com/Serilum/.issue-tracker/assets/38502394/e7b7131e-9bdb-4d28-97ca-cb52e243553c)

**Comment by XFactHD** [comment]
Awesome, thank you
