### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by NotNikku** [ricksouth/serilum-mc-mods#2073]
## **Information**
Minecraft version: 1.18.2
Modloader: Forge
Forge version: 40.2.9
Environment: Singleplayer

Mod name: World Border
Mod version: 2.6

## **Description**
Loading the mod in a big modpack (Vault Hunters) which worked perfectly fine without the mod but when I added World Border to it it doesnt wanna work anymore and says worldborder failed to load correctly with code: java.lang.reflect.InvocationTargetException:null

## **Crash report**
https://gist.github.com/NotNikku/f974da2314a06a3cb075a3ff8e772118

**Comment by ricksouth** [comment]
As specified on the project page and the dependencies, you'll need to install Collective as well :)

https://legacy.curseforge.com/minecraft/mc-mods/collective/files/all?filter-status=1&filter-game-version=1738749986:73250

**Comment by NotNikku** [comment]
It automatically added Collective (Curseforge dependencies and all) but I
think it must have installed a version of Collective (7.7) that didn't work
with the version of World Borders then. I also tried it with Collective
6.53 (The one with the most installs for 1.18) and that didn't work either.

Op vr 1 dec 2023 om 18:37 schreef Rick South ***@***.***>:

**Comment by ricksouth** [comment]
What version of World Border did you install? The latest is 4.2

**Comment by NotNikku** [comment]
I think I installed 2.6 since that was the most recent one i saw for 1.18.2.
Does 4.2 work for 1.18.2 aswell then?

**Comment by ricksouth** [comment]
I don't understand where you're looking exactly. The file says 1.18.2-4.2 as a version

**Comment by NotNikku** [comment]
I'm such an idiot, I'm so sorry!
I somehow convinced myself that 4.2 was for 1.20 Minecraft, it works
perfectly fine with 4.2. Thank you so much for helping!

Op vr 1 dec 2023 om 21:38 schreef Rick South ***@***.***>:

**Comment by ricksouth** [comment]
No problem, glad you got it working. Thanks for giving the mod a try!
