### ISSUE TITLE
Mute/Limiter Doesn't work on Exotic Birds mod

### ISSUE THREAD

**Issue by xFirefalconx** [ricksouth/serilum-mc-mods#2077]
## **Information**
Minecraft version: 1.18.2
Modloader: Forge 
Forge version: 40.2.14
Environment: Singleplayer / Multiplayer

First mod name: Omegamute
First mod version: 3.1

Second mod name: Exotic Birds
Second mod version: 1.8.0

## **Description**
Muting or limiting swan sounds (tested) doesn't do anything. 
Another issue is that this also happened when using a mod called "extreme sound muffler", the swans were still happily honking in full volume. The sounds get listed by omegamute, but changing the settings and then saving, reloading doesn't have an effect at all. It's as if exoticbirds is using a different channel or bypasses the mute. 

## **Crash report**
N/A

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 4.0 of Omega Mute, alongside some other feature upgrades.

https://curseforge.com/minecraft/mc-mods/omega-mute/files
