### ISSUE TITLE
Server crashed potentially by Flower Mimics based on Crash Report

### ISSUE THREAD

**Issue by ZiLenTz** [ricksouth/serilum-mc-mods#2079]
## **Information**
Minecraft version: 1.20.1
Modloader: Fabric
Fabric loader version: 0.14.24
Environment: Multiplayer

Mod name: Flower Mimics
Mod version: 1.3

## **Description**
Server immediately crashed after a player moved into certain area while strip mining.
After starting the server and let other people joined again, everything went smoothly until that player logged in and spawned at the exact same location.
We made multiple attempts including letting that player joined first, to make sure that the cause was related to that player.

To tackle the issue, all of crash reports were exactly the same and were related to Flower Mimics.
So we tried to remove this mod and the issue was gone as everyone could join specifically that player without crashing the server again.

## **Crash report**
https://mclo.gs/IwmTWTK
https://mclo.gs/kntASnh
https://mclo.gs/JV1AXCh

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 1.5 of Flower Mimics.

https://curseforge.com/minecraft/mc-mods/flower-mimics/files
