### ISSUE TITLE
Nether portal spread and spelunkery incompatibility

### ISSUE THREAD

**Issue by redlemonsydney** [ricksouth/serilum-mc-mods#2081]
## **Information**
Minecraft version: 1.20.1
Modloader: Fabric
Fabric loader version: 0.14.25
Environment: Singleplayer

First mod name: Nether Portal Spread
First mod version: 1.20.1-7.6-forge+fabric

Second mod name: Spelunkery
Second mod version: 1.20.1-0.3.4

## **Description**
When I light a nether portal with flint and steel, nothing breaks and everything works fine. When I tried to use Spelunkery's bottle of dimensional tears to light a portal however, my game crashed. I checked the crash log and it mentioned NPS, so i turned it off, and after that, it worked fine.

## **Crash report**
[crash-2023-12-05_11.08.58-client.txt](https://github.com/ricksouth/serilum-mc-mods/files/13559273/crash-2023-12-05_11.08.58-client.txt)

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 7.7 of Nether Portal Spread.

https://curseforge.com/minecraft/mc-mods/nether-portal-spread/files
