### ISSUE TITLE
Tree Harvester - Hang/crash during load

### ISSUE THREAD

**Issue by Omnimetatron** [ricksouth/serilum-mc-mods#2083]
## **Information**
Minecraft version: 1.20.2
Modloader: NeoForge
Forge version: 20.2.86
Environment: Singleplayer / Multiplayer

Mod name: Tree Harvester
Mod version: 1.20.2-8.3-forge+fabric

## **Description**
Hang/crash during load, RAM shown above limit in Task Manager, PC will continue tio do nothing for 10+ minutes, Softlocked.

## **Crash report**
None created.

**Comment by ricksouth** [comment]
I can't really do much with this issue report unfortunately. Does it also happen with just Collective/Tree Harvester installed? And it works correctly without?

**Comment by Omnimetatron** [comment]
Yes, I performed a binary search and determined that this mod when removed will allow Minecraft to load. Would the debug.log or latest.log help?

**Comment by ricksouth** [comment]
If you can send the logs, I can take a look. Thanks.

Does the problem still occur when other mods are removed?

**Comment by Omnimetatron** [comment]
https://gist.github.com/Omnimetatron/0d8dae362bf70fae41dea041b38622aa

https://gist.github.com/Omnimetatron/5c53640c6b81a19277ea24d685613d03

The mod loads fine with just Collective.

**Comment by Omnimetatron** [comment]
A bit odd, but I thought I'd mention. The addition of the modernfix mod allows Minecraft to load correctly, even with TH installed.

**Comment by ricksouth** [comment]
In that case it sounds like it could be an issue in NeoForge, that modernfix fixes. Could you open an issue on their end?

**Comment by ricksouth** [comment]
Closing this for now, as I'm unable to replicate it. Thank you for giving the mod a try!
