### ISSUE TITLE
Crashed randomly do to Villager Names?

### ISSUE THREAD

**Issue by Jirodyne** [ricksouth/serilum-mc-mods#2087]
## **Information**
Minecraft version: 1.20.1
Modloader: Forge
Forge version: 47.2.0
Environment: Singleplayer

Mod name: Villager Names
Mod version: 1.20.1-5.2

## **Description**
Was running back to village, and game crashed without warning. Error seems to be:

Description: Exception ticking world
java.lang.NoSuchFieldError: femalenames

## **Crash report**
https://gist.github.com/Jirodyne/0de7cdfce3643efebe9930e19dcdb762

**Comment by ricksouth** [comment]
Since you have updated Collective, Villager Names needs an update too. Please update it to version 7.1, that'll fix the issue. Thanks for giving the mod a try!

https://legacy.curseforge.com/minecraft/mc-mods/villager-names/files
