### ISSUE TITLE
Ore Discovery Broadcast - Ore size detection

### ISSUE THREAD

**Issue by sternschnaube** [ricksouth/serilum-mc-mods#2088]
Hello Serilum, first - thank you sooooo much for releasing a mod like this! 💖 

It has been years since I was using a plugin like it: https://dev.curseforge.com/projects/ore-broadcast
(Since then, almost no one made something similar like it.)

My wish would be, could you add a detection check how big a ore size is, like the plugin was doing it? 😊 
That would be fantastic - just a scan, how many ores from the same are connected to each other.

It was super fun, which player was finding the largest ore vein, back then 😄

**Comment by ricksouth** [comment]
I really liked the idea! Thank you for the suggestion. I've just uploaded version 1.1 of Ore Discovery Broadcast which adds the feature :)

There's the config option 'addOreCountToMessage', disabled by default, which will add the ore count to the broadcasted message.

https://modrinth.com/mod/ore-discovery-broadcast/versions (CurseForge is having some processing issues)
https://legacy.curseforge.com/minecraft/mc-mods/ore-discovery-broadcast/files

**Comment by venaminecraft** [comment]
Awesome, thank you so much @ricksouth 🥰

I was testing it right now, it works good.
But - could you maybe add another rule, that if "addOreCountToMessage" is true, just the initial message will be displayed. That's it.

I could play with a higher delay, but if I mine then another ore shortly after, I just don't get any message from it.

As bonus - custom color support for each defined ore.

I didn't wanted to open another ticket, I hope that's fine 😊

**Comment by ricksouth** [comment]
Thank you for the suggestions. I've reopened the issue, I'll try to do it when I have time. Appreciate it! :)

**Comment by ricksouth** [comment]
Ok, I definitely need a break from this mod now. But both have been added!

Any block counted by the ore count will now be ignored.
There is now a config file in ./config/orediscoverybroadcast/colourmap.txt where you can specify a message colour for each specific ore.

And some other tweaks, I've updated the project description. Thanks for the suggestions! Hope you enjoy the mod :)

https://legacy.curseforge.com/minecraft/mc-mods/ore-discovery-broadcast

**Comment by ricksouth** [comment]
![](https://github.com/ricksouth/serilum-mc-mods/raw/master/cdn/ore-discovery-broadcast/g.gif)

**Comment by venaminecraft** [comment]
Can't put my thanks enough into words.
I will test it later out 😊
