### ISSUE TITLE
Alternative World Save Location config broken

### ISSUE THREAD

**Issue by PukPukov** [ricksouth/serilum-mc-mods#2090]
## **Information**
Minecraft version: 1.20.4
Modloader: Fabric
Fabric loader version: 0.15.1
Environment: Singleplayer

Mod name: Alternative World Save Location
Mod version: 1.20.4-3.3

## **Description**
Only one row is shown in the config at a time, row changes when scrolling mouse wheel. Logic still works, i.e. you still can change world save location, but you have to deal with that like looking config.

**Comment by ricksouth** [comment]
Thank you for opening the bug report! This has been fixed in Collective version 7.15.

https://modrinth.com/mod/collective/versions (CurseForge is having some processing issues)
https://legacy.curseforge.com/minecraft/mc-mods/collective/files
