### ISSUE TITLE
Repeated giving of items

### ISSUE THREAD

**Issue by 1936268516** [ricksouth/serilum-mc-mods#2097]
Starter Kit：Forge-1.20.1-5.3
Minecraft：Forge-47.2.17

Upon death and respawn, the initial items are given and a new set of items are given, if the secondary again items are also replaced with the set items

**Comment by ricksouth** [comment]
Do you mean this as a bug or a feature? It gives the starter kit again whenever a player dies and respawns?

**Comment by 1936268516** [comment]
> 你的意思是这是一个错误还是一个功能？每当玩家死亡并重生时，它都会再次提供入门套件？
yes

**Comment by 1936268516** [comment]
> Do you mean this as a bug or a feature? It gives the starter kit again whenever a player dies and respawns?

It's a bug that resurrecting after death re-gives the item and will replace the item I put in my secondary hand with the initial equipment that was set up.

**Comment by 1936268516** [comment]
> 你的意思是这是一个错误还是一个功能？每当玩家死亡并重生时，它都会再次提供入门套件？

It's a bug that resurrecting after death gives the initial kit again and replaces the item I put in my secondary hand with the one I initially set up. This causes the items I put on my secondary hand to be deleted and replaced

**Comment by Daniels1377** [comment]
Im also getting this issue with 1.18.2  Players who die respawn with a duplication of the starter items

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 6.0 of Starter Kit, alongside many new features! See the description for more details:

https://curseforge.com/minecraft/mc-mods/starter-kit
