### ISSUE TITLE
[TrackingCompass] Open a branch for the 1.16.5 version

### ISSUE THREAD

**Issue by rathmerdominik** [ricksouth/serilum-mc-mods#2105]
## **Information**
Minecraft version: 1.16.5
Modloader: Forge
Forge version: latest
Environment: Multiplayer

Mod name: TrackingCompass
Mod version: latest

## **Question**
It would be very kind if you could add the 1.16.5 branch to the now open sourced mod as well ^^

I would love to make a tailored version for the Mine Mine no Mi mod that searches for player with high doriki

**Comment by ricksouth** [comment]
Appreciate the intererest! For now I've only uploaded the sources that use Multiloader. But with some searching I found the old source of Player Tracking Compass here: https://github.com/Serilum/.issue-tracker/tree/0d9984f6a30f868fb2d41618ab8e3d96089dfaa4/sources/Player%20Tracking%20Compass

I'll think about how/if to put the source in another branch. :)
