### ISSUE TITLE
barebackhorseriding-1.19.2-1.1 CRASH

### ISSUE THREAD

**Issue by Minebrah** [ricksouth/serilum-mc-mods#2106]
https://gist.github.com/Minebrah/f0dfcbe3e463e8a8f97563769e7a11f1

**Comment by Minebrah** [comment]
.......so the crash caused by this mod was so bad that my game file is literally gone. Its unplayable, un openable, un editable, everything. I can't even click on the instance.
 It says LOCKED BY ANOTHER RUNNING INSTANCE OF MINECRAFT.
Hours of progress, lost...

**Comment by ricksouth** [comment]
I'm sorry it crashed. Looks like it's just the renderer. Remove the mod and reboot your computer will fix that. Thank you for opening the issue, I'm going to take a look

**Comment by ricksouth** [comment]
This has been fixed in 1.2 of Bareback Horse Riding.

https://curseforge.com/minecraft/mc-mods/bareback-horse-riding/files
