### ISSUE TITLE
Cave Spider Spawn - Config option for deepslate-only spawns

### ISSUE THREAD

**Issue by Typhonidite** [ricksouth/serilum-mc-mods#2114]
## **Information**
Minecraft version: _1.20.1_
Modloader: _Forge_

Mod name: **Cave Spider Spawn**

## **Feature description**
While the surface-only option is nice, a config option to have natural cave spiders spawns occur only within the deepslate level would be nicer.

**Comment by ricksouth** [comment]
This has been added in version 1.1 of Cave Spider Spawn. It has to be enabled in the config settings. Thanks for the suggestion!

https://curseforge.com/minecraft/mc-mods/cave-spider-spawn
