### ISSUE TITLE
#Just Mod Heads not working. /jmh does nothing yet no error

### ISSUE THREAD

**Issue by cookiemo729** [ricksouth/serilum-mc-mods#2115]
## **Information**
Minecraft version: 1.20.1
Modloader: Fabric
Fabric loader version: 0.15.3
Environment: Multiplayer

Mod name: Just Mob Heads
Mod version: 7.5

## **Description**
I downloaded this mod plus collective-1.20.1-7.23.jar into the server's mods folder.

When I type /jmh into the command bar, it acts as if it is working e.g. it suggests "head" to me after I typed "jmh", and lastly suggested "list". 

But when I pressed enter for the command "/jmh head list", nothing happened. Of course nothing happened for "/jmh head turtle 1" also. No error message.

Please help. Thanks!

**Comment by James103** [comment]
Can you please post the server logs from attempting to use the `/jmh` commands you mentioned?

**Comment by ricksouth** [comment]
Unable to replicate it, and unfortunately no logs. Closing this for now. Please let me know if the issue persists.
