### ISSUE TITLE
Harvest time feature doesn't work properly on servers

### ISSUE THREAD

**Issue by suohcnamiD** [ricksouth/serilum-mc-mods#2121]
## **Information**
Minecraft version: 1.20.1
Modloader: Forge / Fabric
Forge version: 1.20.1 - 47.2.18
Environment: Multiplayer

Mod name: Tree Harvester
Mod version: 1.20.4-8.4

## **Description**
When installed on both server and client and using the `increaseHarvestingTimePerLog` feature, the animation of breaking the block is not right (it just plays like for one block and then the whole tree gets chopped down after i have waited the time). In singleplayer everything works fine.
I figured out the issue: if the server's and client's `increasedHarvestingTimePerLogModifier` mismatch, this happens.

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 9.1 of Tree Harvester. Appreciate it.

https://curseforge.com/minecraft/mc-mods/tree-harvester/files
