### ISSUE TITLE
[CRASH] Sudden crash when fighting zombies.

### ISSUE THREAD

**Issue by Yokisan249** [ricksouth/serilum-mc-mods#2130]
## **Information**
Minecraft version: 1.20.1
Modloader: Forge
Forge version: 47.2.0
Environment: Singleplayer

Mod name: No Hostiles Around Campfire
Mod version: 5.8

## **Description**
I was fighting a horde of zombies and then suddenly my game crashed saying "java.lang.UnsupportedOperationException: Late invocations of Mob#setSpawnCancelled are not permitted."

## **Crash report**
[crash-2023-12-27_15.28.08-server.txt](https://github.com/Serilum/.issue-tracker/files/13780555/crash-2023-12-27_15.28.08-server.txt)

## **Latest Log**
[latest.log](https://github.com/Serilum/.issue-tracker/files/13780559/latest.log)

**Comment by ricksouth** [comment]
Thank you for opening the issue. This has been fixed in version 5.9 of No Hostiles Around Campfire.

https://curseforge.com/minecraft/mc-mods/no-hostiles-around-campfire/files
