### ISSUE TITLE
How much is the "Areas" mod maximum range and what exactly is its range?

### ISSUE THREAD

**Issue by Gilteca** [ricksouth/serilum-mc-mods#2131]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.16.5
Modloader: Forge
Forge version: 36.2.41
Environment: Multiplayer

Mod name: Areas
Mod version: areas_1.16.5-3.1.jar

## **Question**
How much is the "Areas" mod maximum range for a set area? is it configurable?

Also what exactly is its range? Like, lets say its a 30 range area, is it 30 blocks or 30x30 chunks area? i noticed on the gif in curseforge that it looks to be a very small range

**Comment by ricksouth** [comment]
The range is the diameter. It's basically a circle around the sign. The mod checks if a player is within that distance to it. I'm not sure what the maximum range would be, I think it's the rendering distance of the server.

**Comment by Gilteca** [comment]
Aight got it, tyvm for answering it!

**Comment by ricksouth** [comment]
You can always have two signs with the same name to increase the total area. It will only show the join/leave message once :)
