### ISSUE TITLE
Difficulty defaults to peaceful and only peaceful, config does not change it.

### ISSUE THREAD

**Issue by captinwill** [ricksouth/serilum-mc-mods#2136]
## **Information**
Minecraft version: 1.12.2
Modloader: Forge
Forge version: 14.23.5.2860
Environment: Singleplayer

Mod name: Difficulty Lock
Mod version: 1.2

## **Description**
Difficulty defaults to peaceful and only peaceful, config does not change it.

## **Game Logs**
[latest.log](https://github.com/Serilum/.issue-tracker/files/13791384/latest.log)
[debug.log](https://github.com/Serilum/.issue-tracker/files/13791409/debug.log)

**Comment by ricksouth** [comment]
Unfortunately 1.12 is no longer supported. Please update to a later version.
