### ISSUE TITLE
Tree Harvester: Exit Code 1 on launch

### ISSUE THREAD

**Issue by LunarDev-git** [ricksouth/serilum-mc-mods#2143]
## **Information**
**Minecraft version:** 1.20.1
**Modloader:** Forge
**Forge version:** 47.2.19
**Environment:** N/A

**Mod name:** Tree Harvester
**Mod version:** 1-8.5

## **Description**
Upon Launch I get an exit code 1, I tested in an isolated environment with just it's dependancy and it still crashes.

## **Crash report**
Don't have a crash log but here's the latest.log 
[latest.log](https://github.com/Serilum/.issue-tracker/files/13804665/latest.log)

**Comment by ricksouth** [comment]
Thank you for opening the issue, I've found the problem and am working on a fix right now

**Comment by ricksouth** [comment]
I've just released version 8.6 of Tree Harvester which fixes the issue. Thanks again!

https://curseforge.com/minecraft/mc-mods/tree-harvester/files
