### ISSUE TITLE
TreeHarvester - Trees/Nether Tree Leaves Not Being Harvested

### ISSUE THREAD

**Issue by Dragonsissiy** [ricksouth/serilum-mc-mods#2147]
## **Information**
Minecraft version: 1.20.1
Modloader: Forge 
Forge version: 47.2.1  
Environment: Multiplayer
(Minecolonies Dimensional Adventures modpack, but with mostly updated versions of each mod and some mods removed.)

Mod name: TreeHarvester
Mod version: 1-1.20.1-8.4.jar

## **Description**
Harvested logs don't always cut down the tree, even when using whitelisted axes. - seems to be due to how fast I'm able to cut down a tree/log. Slower axes seem more reliable but still have this issue.

Mod doesn't clear warped blocks or crimson hyphae after chopping down stems. (nether tree leaves)

## **Crash report**
N/A

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 9.1 of Tree Harvester. Appreciate it.

https://curseforge.com/minecraft/mc-mods/tree-harvester/files
