### ISSUE TITLE
Improved Sign Editing should work with hanging signs

### ISSUE THREAD

**Issue by Simplebenja** [ricksouth/serilum-mc-mods#2151]
## **Information**
Minecraft version: 1.20.4
Modloader: Neoforge 20.4.77

Mod name: Improved Sign Editing

Well... that, works great with normal signs, but doesn´t work with hanging signs

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 1.3 of Improved Sign Editing.

https://curseforge.com/minecraft/mc-mods/improved-sign-editing/files

**Comment by Simplebenja** [comment]
Thx dude
