### ISSUE TITLE
Persistent Leaves Count as Part of a Tree when Harvesting

### ISSUE THREAD

**Issue by SealTheTiel** [ricksouth/serilum-mc-mods#2159]
## **Information**
Minecraft 1.20.4
Fabric 0.15.3
Singleplayer / Multiplayer

Mod name: Tree Harvester 8.6

Other Mods:
 - Fabric API 0.92.1
 - Collective 7.30

## **Description**
Creating a man-made tree gets harvested by the mod.

https://github.com/Serilum/.issue-tracker/assets/38400820/cee18ffd-1c1c-4018-984f-bcf177a29cb6

This can be an issue for configurations of Tree Harvester that have a high max broken blocks and/or max range. A custom tree, or even log houses with some `persistent` leaves may get flagged by the mod to be "tree-like" and pose a risk to accidental harvesting.

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try. This has been fixed in version 8.7 of Tree Harvester thanks to @zf-moth.

https://curseforge.com/minecraft/mc-mods/tree-harvester/files
