### ISSUE TITLE
Crash with the /omegamute listen command when Sounds mod is enabled

### ISSUE THREAD

**Issue by BlueJayofEvil** [ricksouth/serilum-mc-mods#2163]
## **Information**
Minecraft version: 1.20.4
Modloader: Fabric
Fabric loader version: 0.15.3
Environment: Singleplayer and Multiplayer

Mod name: Sounds
Mod version: 0.4.0
Link: https://modrinth.com/mod/sound

## **Description**
Crash occurs when /omegamute listen is used with this mod enabled.
I'm fairly certain it's due to the mod playing a sound when text is typed or messages in chat are received, creating a loop when Omegamute's listen command is used which causes the game to crash.

## **Crash report**
https://mclo.gs/XHoD1sp

**Comment by ricksouth** [comment]
Thanks for opening the issue, I'll take a look!

[log.txt](https://github.com/Serilum/.issue-tracker/files/13960540/log.txt)

**Comment by ricksouth** [comment]
Thanks again for opening the issue and giving the mod a try! This has been fixed in version 4.0 of Omega Mute.

https://curseforge.com/minecraft/mc-mods/omega-mute/files
