### ISSUE TITLE
Difficulty button on New World screen always disabled no matter the configuration

### ISSUE THREAD

**Issue by vico93** [ricksouth/serilum-mc-mods#2164]
## **Information**
Minecraft version: 1.20.1
Modloader: Fabric
Fabric loader version: 0.15.3
Environment: Singleplayer

Mod name: Difficulty Lock
Mod version: 4.0

## **Description**
While reassembling my modpack, when i installed Difficulty Lock and tried to create a test world i noticed regardless of how i change the settings in the mod options, the *Difficulty* button on New World screen always was inactive, while I type anything in the *Name* field it flashes enabled for a couple of frames but resumes being disabled.

At first i thought it was an incompatibility with [Reimagined World Menu](https://modrinth.com/mod/reimagined-world-menu/), but [after reporting on their repository](https://github.com/lamaprogramer/ReimaginedMenus/issues/24) @lamaprogramer did a quick test with only Difficulty Lock and was able to reproduce the issue without RWM.

**Comment by vico93** [comment]
Just tested here and also happens in 1.20.4 with 4.0

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 4.1 of Difficulty Lock.

https://curseforge.com/minecraft/mc-mods/difficulty-lock/files
