### ISSUE TITLE
bugs/problems with versions 20.2 and 20.4

### ISSUE THREAD

**Issue by coyotteslayer** [ricksouth/serilum-mc-mods#2165]
## **Information**
Minecraft version: 1.20.2 and 1.20.4
Mod loader: Forge and Neoforge
Forge version: 48.0.34 and Neoforge version 20.4.50 newest wouldn't work with a different mod 
Environment: Singleplayer 

Mod name: Tree Harvester
Mod version: 1.20.2 and 1.20.4

## **Description**
in 1.20.2 the mod wouldn't work on only brown mushrooms. everything else including red mushrooms worked fine.
in 1.20.4 it does now work on the brown mushrooms too, however silk touch doesn't work on mushrooms in any version to my knowledge. this was a large portion of my reason for downloading as i need several thousand stems for a project.

## **Crash report**
N/A

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 9.1 of Tree Harvester. Appreciate it.

https://curseforge.com/minecraft/mc-mods/tree-harvester/files
