### ISSUE TITLE
Bug and giant name

### ISSUE THREAD

**Issue by 0KratosGamer** [ricksouth/serilum-mc-mods#2171]
## **Information**
Minecraft version: 1.20.1
Modloader: Forge
Forge version: 47.2.19
Environment: Singleplayer

Mod name: Villager Names
Mod version: 7.3

## **Description**
Every villager has this big name, that seems to be their code.

![imagem_2024-01-15_210552947](https://github.com/Serilum/.issue-tracker/assets/156726853/cec7cd8d-60d0-40ea-a33d-ad2f378a9ca4)

## **Crash report**
_(Please either drag the file directly here, or use https://gist.github.com/ to prevent the paste from expiring)_

If available.

**Comment by 0KratosGamer** [comment]
It's another mod bug, not the Villagers Names. Sorry

**Comment by ricksouth** [comment]
Does it still happen with Villager Names removed? And with only Villager Names installed?
