### ISSUE TITLE
better disruptions

### ISSUE THREAD

**Issue by Nathanos2256** [ricksouth/serilum-mc-mods#2177]
## **Information**
Minecraft version: irrelevant 
Modloader: Forge / Fabric irrelevant

Mod name: Mod
all of them that dont list this

## **Feature description**
I've had this amazing idea!
could you please add weather the mod is client or server or both.

**Comment by ricksouth** [comment]
I'm not sure what you mean exactly. Are you asking to port a mod? I'm not planning on doing that at the moment. But thank you for the request!
