### ISSUE TITLE
Compatibility with other shield mods

### ISSUE THREAD

**Issue by Facundo-Guarnier** [ricksouth/serilum-mc-mods#2182]
## **Information**
Minecraft version: 1.20.1
Modloader: Fabric
Fabric loader version: 0.15.3
Environment: Singleplayer 

Mod name: Passive Shield
Mod version: 1.20.1 - 3.4 fabric

## **Question**
Hello, is there a way to add some shields from other mods to the configuration so that they work with this mod? Example: Basic Shields [Fabric] (https://modrinth.com/mod/basic-shields-fabric)
👋🏻
Sorry for my basic English

**Comment by ricksouth** [comment]
They should work already! If they use the correct Fabric shield tag. Not much I can add on my end to change that if it's not working. Thanks for giving the mod a try
