### ISSUE TITLE
Uses material instead of chest

### ISSUE THREAD

**Issue by SkylordBrebro** [ricksouth/serilum-mc-mods#2184]
## **Information**
Minecraft version: 1.20.4
Modloader: Fabric
Fabric loader version: 0.15.6
Environment: Singleplayer

Mod name: Your Items Are Safe
Mod version: 3.6

## **Description**
Hey! Instead of using a chest that I have in my inventory, the mod decided to use raw materials. Is there a way to make it use chests first, then raw materials if no chest?

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 4.0 of Your Items Are Safe.

https://curseforge.com/minecraft/mc-mods/your-items-are-safe/files
