### ISSUE TITLE
Curse Of vanishing Conflict with Your items are safe

### ISSUE THREAD

**Issue by leonx132** [ricksouth/serilum-mc-mods#2186]
## **Information**
Minecraft version: 1.20.4
Modloader: Fabric
Fabric loader version: 1.20.4
Environment: Multiplayer

Mod name: Your items are safe
Mod version: 3.6

## **Description**
Curse Of vanishing should disappear when the player dies but instead its put into the chest, would very much like this curse effect to remain 

If available.

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 4.0 of Your Items Are Safe.

https://curseforge.com/minecraft/mc-mods/your-items-are-safe/files
