### ISSUE TITLE
Recipe Book - Persistent Inventory Search

### ISSUE THREAD

**Issue by Typhonidite** [ricksouth/serilum-mc-mods#2189]
## **Information**
Minecraft version: **_1.20.1_**
Modloader: **_Forge_**

Mod name: _Persistent Inventory Search_

## **Feature description**
Could this idea be extended to other menus, such as the recipe book?

**Comment by Typhonidite** [comment]
...this is already a feature

**Comment by deftesthawk** [comment]
It doesn't seem to work for the recipe book for me, here's a video of it not working:
https://github.com/user-attachments/assets/e8ea2f15-256f-47ef-9299-bcbbb189102f

I tested on a clean modpack no other mods installed other than the required ones, I also looked for a config file in case it needed to be enabled somehow but couldn't find one.
