### ISSUE TITLE
Starter Kit not working

### ISSUE THREAD

**Issue by leonx132** [ricksouth/serilum-mc-mods#2194]
## **Information**
Minecraft version: 1.20.4
Modloader: Fabric
Fabric loader version: 1.20.4
Environment:  Multiplayer

Mod name: Starter Kit
Mod version: 5.5

## **Description**
i have some books and some armor that people are supposed to get when joining but they never do

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 6.0 of Starter Kit, alongside many new features! See the description for more details:

https://curseforge.com/minecraft/mc-mods/starter-kit
