### ISSUE TITLE
Exception Ticking World Modrinth 

### ISSUE THREAD

**Issue by Driestcombee** [ricksouth/serilum-mc-mods#2196]
## **Information**
Minecraft version: 1.20.1
Modloader: Fabric
Environment: Singleplayer

Mod name: Realistic Bees/ Collective
Mod version: x.x

## **Description**
 Exception ticking world error

**Comment by James103** [comment]
Can you please attach the full logs and crash report?

**Comment by Driestcombee** [comment]
Nvm, turns out it was another mod that caused the error, specifically Sleep Tight
