### ISSUE TITLE
Set World Spawn Point - server side only or required on client?

### ISSUE THREAD

**Issue by katubug** [ricksouth/serilum-mc-mods#2197]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.20.3
Modloader: Forge 
Forge version: 47.2.19
Environment: Multiplayer

Mod name: Set World Spawn Point 

## **Question**
As in title: is this required on the client as well or can it work only server side?

**Comment by ricksouth** [comment]
Thanks for the interest! The mod will work server-side only. Unless you want to use it in singleplayer of course.

**Comment by katubug** [comment]
Thank you!
