### ISSUE TITLE
Iron doors still open despite config settings being "false"

### ISSUE THREAD

**Issue by L1nger05** [ricksouth/serilum-mc-mods#2202]
## **Information**
Minecraft version: 1.16.5
Modloader: Forge
Forge version: 36.2.39
Environment: Singleplayer

Mod name: Automatic Doors by Serilum
Mod version: Tried on 1.8 and 2.4, don't know if other versions have this bug too

## **Description**
First installed the 2.4 version of the mod had this issue when despite ShouldOpenIronDoors being false, it keeps opening in all gamemodes (except spectator, of course). The same issue in 1.8 version. To my surprise, the config doesn't reset whenever I enter the game: door closing delay change through the config pretty obediently, as well as doorsOpenWhileCrouched setting.

## **Crash report**
automaticdoors_1.16.5-1.8.jar
automaticdoors_1.16.5-2.4.jar

If available.

**Comment by ricksouth** [comment]
I can't seem to replicate this in the latest versions. Unfortunately I no longer support Minecraft 1.16.5. Apologies for the inconvenience.
