### ISSUE TITLE
Game Crashes when 'Bigger Sponge Absorption Radius' and 'Carpet Extra' are both installed

### ISSUE THREAD

**Issue by ScorchedPork** [ricksouth/serilum-mc-mods#2206]
## **Information**
Minecraft version: 1.20.4
Modloader: Fabric
Fabric loader version: 0.15.6
Environment: Singleplayer

Mod name: Bigger Sponge Absorption Radius
Mod version: 3.5

## **Description**
When they are both installed it crashes when trying to load.

## **Crash report**
[crash-2024-02-07_08.49.24-client.txt](https://github.com/Serilum/.issue-tracker/files/14194591/crash-2024-02-07_08.49.24-client.txt)

**Comment by ricksouth** [comment]
Thank you for opening the issue! This has been fixed in version 3.6 of Bigger Sponge Absorption radius. Apologies it took so long for me to get to.

https://curseforge.com/minecraft/mc-mods/bigger-sponge-absorption-radius/files
