### ISSUE TITLE
Backport fixes for Double Doors to 1.16.5

### ISSUE THREAD

**Issue by pointydev** [ricksouth/serilum-mc-mods#2207]
## **Information**
Minecraft version: 1.16.5
Modloader: Forge
Forge version: 36.2.34
Environment: N/A

Mod name: Double Doors
Mod version: 33

## **Question**
Is it possible that fixes from later versions could be backported to 1.16.5? I am currently playing a custom modpack with some friends and we're running into #956 constantly. We've been building custom versions of other mods to fix issues, however we cannot do so in this case as the source is not available.

Thanks,
pointy

**Comment by ricksouth** [comment]
That's unfortunately not easily possible, sorry. I have to drop some versions due to time contraints. It'd mean setting up the entire environment again. Apologies for the inconvenience.
