### ISSUE TITLE
1.19.2 server crashing from No Hostiles Around Campfire

### ISSUE THREAD

**Issue by MoonMoonShark** [ricksouth/serilum-mc-mods#2210]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 43.3.0
Environment: Multiplayer

Mod name: No Hostiles Around Campfire
Mod version: nohostilesaroundcampfire-1.19.2-5.9

## **Description**
Hey there! A couple different times now we've had players flying around the world, exploring new areas, and the server crashed. The crash logs indicate that it may be caused by No Hostiles Around Campfire. I know you did something in 5.9 that was supposed to fix it, so I hate to bring this to you, but we really do love your mod, have used it on the last 3 versions of our server, and would love to be able to use it again. Please let me know if there is anything I can help with, and thank you so much for all of your hard work!

## **Crash report**
[crash-2024-02-05_18.38.30-server.txt](https://github.com/Serilum/.issue-tracker/files/14227581/crash-2024-02-05_18.38.30-server.txt)
[crash-2024-02-03_16.59.43-server.txt](https://github.com/Serilum/.issue-tracker/files/14227582/crash-2024-02-03_16.59.43-server.txt)

**Comment by ricksouth** [comment]
Thank you for giving the mod a try and opening the issue. This has been fixed in version 7.0 of No Hostiles Around Campfire. Apologies it took so long for me to get to.

https://curseforge.com/minecraft/mc-mods/no-hostiles-around-campfire/files

**Comment by MoonMoonShark** [comment]
OMG YOU ARE MY HERO! thank you thank you thank you!!!

**Comment by MoonMoonShark** [comment]
i don't want to be a pill but i just noticed there's no 1.19.2 version, only 1.20.x and 1.21.x. would it be possible to get one for 1.19? i know it's a couple years old now but because we were waiting for a couple other mods to get updated to 1.20, we're still running on that older version.
