### ISSUE TITLE
[Question] Make mod compatible as resourcepack?

### ISSUE THREAD

**Issue by Kamvurus** [ricksouth/serilum-mc-mods#2212]
## **Question**
Is there a possibility of making the "Hide Hands" mod a resourcepack of some sort? Just like for 1.8 specifically. I want to be able to hide my hand at all times with a resourcepack at all times.

**Comment by ricksouth** [comment]
Not that I'm aware of, I have no experience with making resourcepacks. But thanks for the interest!
