### ISSUE TITLE
Incompatibility with Bigger Sponge Absorption Radius and Quark

### ISSUE THREAD

**Issue by ElasticKnife** [ricksouth/serilum-mc-mods#2221]
## **Information**
Minecraft version: 1.20.1
Modloader: Forge
Forge version: 47.2.20
Environment: Game startup

Mod name: Bigger Sponge Absorption Radius
Mod version: 3.5

## **Description**
Crash on game startup.

## **Crash report**
https://gist.github.com/ElasticKnife/eaafd0456d5614062253716b9d470514

**Comment by Sonifluous** [comment]
Riiiiiick! Moo here, this right here is the issue! I'll send my launcher where I caught the error, skip to line 3260 to see the details!
[launcher_log2.txt](https://github.com/user-attachments/files/15779853/launcher_log2.txt)

**Comment by ricksouth** [comment]
Thank you for opening the issue! This has been fixed in version 3.6 of Bigger Sponge Absorption radius. Apologies it took so long for me to get to.

https://curseforge.com/minecraft/mc-mods/bigger-sponge-absorption-radius/files
