### ISSUE TITLE
Is there a list of your mods for client only, server only, and client & server?

### ISSUE THREAD

**Issue by mikes4b22** [ricksouth/serilum-mc-mods#2222]
## **Information**
Minecraft version: 1.20.1
Modloader: Forge
Environment: Multiplayer

Mod name: All

## **Question**
First, thanks for the great work! Is there a list of all your mods and whether the need to be installed client only, server only, or client & server? I'm trying to compile a modpack for some friends to play (and maybe general release) but want to minimize the size on the client end. Basically just trying to see what mods I can get away with not installing only client-side, only server-side, and which are needed on both ends. Cheers!

**Comment by ricksouth** [comment]
Glad you're enjoying them! I haven't gotten to adding the info to CurseForge yet, but you can find it on my Modrinth profile here: https://modrinth.com/user/Serilum

Hope that helps :)

**Comment by mikes4b22** [comment]
Cheers!
