### ISSUE TITLE
[Areas] No randomly assigned area name - causes server to crash 

### ISSUE THREAD

**Issue by Rhazio** [ricksouth/serilum-mc-mods#2225]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 43.3.5
Environment:  Multiplayer

Using FEAR NIGHTFALL modpack, latest version

Mod name: Areas
Mod version: 5.0

## **Description**
I installed Areas 5.0 on the client side and server side for my local server. When creating an area, I would expect it to randomly assign a name if I don't put a name. Instead, it causes the server to crash. I did remove the mod from the server, and instead just have it client side.

By doing that, no name is randomly assigned - therefore not creating an area. 

Assigning a name myself, it does create the area just fine. It's just an issue with the random name generation. 

## **Crash report**

[crash-2024-02-24_14.26.17-server.txt](https://github.com/Serilum/.issue-tracker/files/14394233/crash-2024-02-24_14.26.17-server.txt)

**Comment by ricksouth** [comment]
I believe this is caused by a mismatch in the Areas and Collective version. What made you install version 5.0, and not 5.3?

Does it work correctly with Areas 5.3 and Collective version 7.36?

**Comment by Rhazio** [comment]
Hello, yes seems like it worked after updating Collections and Areas to the version number you suggested.

Thank you
