### ISSUE TITLE
double door sound

### ISSUE THREAD

**Issue by nEONcReepER990** [ricksouth/serilum-mc-mods#2226]
## **Information**
Minecraft version: 1.20.4
Modloader: Fabric
Fabric loader version: 0.15.6
Environment: Multiplayer

Mod name: Double Doors
Mod version: 5.2

## **Description**
Using double doors purely on my local server(not on client side), makes the open/close door sound play with each pressure plate interaction.

video:
https://github.com/Serilum/.issue-tracker/assets/95697642/95be0bc4-d29d-4ebe-98fc-fc1c0a3f2869

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 5.3 of Double Doors.

https://curseforge.com/minecraft/mc-mods/double-doors/files
