### ISSUE TITLE
Request: Suppress Connected Open/Close on Sneak?

### ISSUE THREAD

**Issue by StarlightSovereign** [ricksouth/serilum-mc-mods#2228]
## **Information**
Minecraft version: 1.20.1
Modloader: Forge 

Mod name: Double Doors

## **Feature description**
Could you please add a config option to suppress the function of connected opening/closing on sneak or shift please? 
Sometimes when building things, you want to use trapdoors for decor, for example, and if you have this mod on, it's really hard because as you place them on different edges, and try to close, it will close one set, open another, etc. 
It would really help if you could suppress the multi-toggle with sneak or shift please. Thank you!

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 5.3 of Double Doors.

https://curseforge.com/minecraft/mc-mods/double-doors/files
