### ISSUE TITLE
Pumpkillager stuck on dialog? 

### ISSUE THREAD

**Issue by JaidenLo** [ricksouth/serilum-mc-mods#2231]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge 
Forge version: 43.3.5 
Environment: Multiplayer

Mod name: Pumpkillager Quest
Mod version: 3.3

## **Description**
We tried step 2 of the ritual with the redstone and tnt, when it exploded and summoned him, he had a few lines of dialog and then cut off and was stuck there. I tried resummoning him a few times and he still did nothing. We are playing Fear Nightfall and i'm not sure if this is due to mod conflict or a bug.

If available.
![image_2024-02-28_014240108](https://github.com/Serilum/.issue-tracker/assets/79215781/54d9d1ec-26ec-424d-aa63-d424f8e03e77)

**Comment by ricksouth** [comment]
Can you upload the server/client logs?

**Comment by JaidenLo** [comment]
server restart fixed it, apologies for taking your time.
