### ISSUE TITLE
ArrayIndexOOB in StackRefill

### ISSUE THREAD

**Issue by Aivech** [ricksouth/serilum-mc-mods#2232]
## **Information**
Minecraft version: 1.18.2
Modloader: Forge
Forge version: 40.2.14
Environment: Singleplayer / Multiplayer

Mod name: StackRefill
Mod version: 4.1

## **Description**
Right-clicking a Tinker's Construct Seared Faucet with a Gold Ingot, immediately after picking up said ingot from a Seared Casting Table with an ingot mold in it, crashed the game.

## **Crash report**
https://paste.ee/p/y5Tkq

**Comment by James103** [comment]
Crash report from the paste, as it has an expiration date: 
[crash.log](https://github.com/Serilum/.issue-tracker/files/14438838/crash.log)

**Comment by ricksouth** [comment]
Thank you for opening the issue and the crash reports. Apologies it took a while for me to get to. This has been fixed in version 4.4 of Stack Refill.

https://curseforge.com/minecraft/mc-mods/stack-refill/files
