### ISSUE TITLE
Starter Kit version 6.0 issue on MC 1.20.1 version(s) not rendering custom inventory image

### ISSUE THREAD

**Issue by nanonestor** [ricksouth/serilum-mc-mods#2233]
## **Information**
Minecraft version: 1.20.1
Forge 47.2.20 / Neoforge 47.1.100 / Fabric 0.15.7

Environment: Singleplayer

Mod name: Starter Kit
Mod version: 1.20.1-6.0

## **Description**
The custom inventory image isn't rendering - instead the screen only renders the item icons.
Issue happens with 1.20.1 for both Forge/Neoforge/Fabric and only the collective and starterkit mods loaded.

[screenshots of forge and neoforge with issue - imgur](https://imgur.com/a/LvdXPqd)

## **Crash report**
Log files for a 1.20.1 Forge 47.2.20 profile with only:
```
collective-1.20.1-7.36.jar
starterkit-1.20.1-6.0.jar
```

[latest.log](https://paste.gg/p/anonymous/3998566b83814653bf377128f14b4326)
[debug.log](https://paste.gg/p/anonymous/4cdce6736ce04981b3c2f77f02844066)

* I tested every version available for Starter Kit 6.0 - Also wanted to note that the Forge 1.19.2 version has the button graphics clipped at the bottom.  1.20.4 for all modloaders works fine.
[1.19.2 / Forge 43.3.8 inventory image clipped at bottom ](https://imgur.com/a/DzPvo1n)

**Comment by ricksouth** [comment]
This has been fixed in version 6.2 of Starter Kit. Thanks for opening the issue and giving the mod a try!

https://www.curseforge.com/minecraft/mc-mods/starter-kit
