### ISSUE TITLE
[BUG] Invenventory Resets when updating to v6.0

### ISSUE THREAD

**Issue by CathieNova** [ricksouth/serilum-mc-mods#2234]
## **Information**
Minecraft version: 1.20.1
Modloader: Forge
Forge version: 47.2.20
Environment: Singleplayer & Multiplayer

Mod name: starterkit
Mod version: 1.20.1-6.0

## **Description**
I use this in my modpack Haven: Veni de Nova, recently updated it from Version 5.5 to 6.0 and several users have reported that their inventory has been replaced with the starting inventory after the update, but not everyone has had their inventory replaced, only select few.

I tried to replicate this myself but i haven't succeeded.

**Comment by ricksouth** [comment]
Apologies for the inconvenience. I hadn't thought of the update scenario. I've just uploaded version 6.1 which adds backwards compatibility with version 5.5, and should fix the problem. Thanks for opening the issue!

https://www.curseforge.com/minecraft/mc-mods/starter-kit
