### ISSUE TITLE
Crash using quarry mod

### ISSUE THREAD

**Issue by THEH4CK3RMAN** [ricksouth/serilum-mc-mods#2240]
## **Information**
Minecraft version: 1.20.4
Modloader: Forge 
Forge version: 49.0.30
Environment: Singleplayer

Mod name: Mineral Chance
Mod version: 1.20.4

I Have been using this for a while and recently set up a quarry. whenever the quarry mines something and it triggers a mineral drop the game crashes.

Crash report is attached

[crash-2024-03-02_15.03.47-server.txt](https://github.com/Serilum/.issue-tracker/files/14469694/crash-2024-03-02_15.03.47-server.txt)

**Comment by ricksouth** [comment]
Thank you for opening the issue! This has been fixed in version 3.6 of Mineral Chance.

https://curseforge.com/minecraft/mc-mods/mineral-chance/files
