### ISSUE TITLE
Dragon Drops Elytra contains a virus

### ISSUE THREAD

**Issue by enduum** [ricksouth/serilum-mc-mods#2248]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge

Mod name: Dragon drops elytra
Mod version: 3.3

## **Description**
Jar contains a trojan virus and is flagged by Windows defender when performing a scan or trying to install it via MultiMC.

**EDIT:** Same issue with version 3.3 of Name Tag Tweaks, not going to try any others.

![dde trojan 3-9-2024](https://github.com/Serilum/.issue-tracker/assets/73849784/f5d32c9c-f535-40aa-ac0a-a2f36516e75c)

**Comment by ricksouth** [comment]
My mods do not contain any viruses. As a moderator on the CurseForge Discord server I have seen an increase in false flags. Please report them as a false positive.
