### ISSUE TITLE
Windows Defender mark Collective 7.39 as malware

### ISSUE THREAD

**Issue by michalcz17** [ricksouth/serilum-mc-mods#2252]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 43.2.21
Environment: None

Mod name: Collective
Mod version: 7.39

## **Description**
I recently updated Collective to newest version, but Windows Defender marked them as malware, specifically Trojan:Script/Sabsik.FL.A!ml, I hope this is false positive, but still wanted to report it.

**Comment by michalcz17** [comment]
What I found so far:
- After the update, when the game was started for the first time, there was created folder called `downloads`, that is for now empty
- There is missing log from the first run, and its only missing log so far
- There wasnt added or updated any other mod, so I assume it must to do something with the Collective

**Comment by ricksouth** [comment]
Thank you for the report, but unfortunately there is nothing I can do on my end. Windows Defender has targeted many Minecraft mods, from all authors, by detecting a trojan. It is a false positive, and please report the file to Defender as such. I can assure you there is no virus in there. I have double checked my files locally, and what has been uploaded to CurseForge. I'm not the only one getting these reports unfortunately.
