### ISSUE TITLE
Windows Defender Detected starterkit-1.20.1-6.5.jar as a Trojan

### ISSUE THREAD

**Issue by InputandOutput** [ricksouth/serilum-mc-mods#2253]
Hello, all. I have received a notification about Windows Defender blocking starterkit.1.20.1-6.5.jar for containing a Trojan:Script/Wacatac.B!ml when downloading from the mod from Prism Launcher under a mod pack. Is it a false positive, and if so: should I ignore it?

**Comment by uberswe** [comment]
I am also getting this via CurseForge. Links to this page: `https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3AScript%2FWacatac.B!ml&threatid=2147735503`

Specifically this is from a mod in a modpack: `Create Chronicles Bosses and Beyond\mods\starterkit-1.20.1-6.5.jar`

**Comment by InputandOutput** [comment]
> I am also getting this via CurseForge. Links to this page: `https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3AScript%2FWacatac.B!ml&threatid=2147735503`
> 
> Specifically this is from a mod in a modpack: `Create Chronicles Bosses and Beyond\mods\starterkit-1.20.1-6.5.jar`

The same thing happened when I downloaded Fantasy MC modpack. I think it is modpack independent?

**Comment by ricksouth** [comment]
Thank you for the report, but unfortunately there is nothing I can do on my end. Windows Defender has targeted many Minecraft mods, from several authors, by detecting a trojan. It is a false positive, and please report the file to Defender as such. I can assure you there is no virus in there. I have double checked my files locally, and what has been uploaded to CurseForge. I'm not the only one getting these reports unfortunately.

**Comment by uberswe** [comment]
Thanks @ricksouth. I also wanted to mention that I fixed the false positive by following the steps in this comment as the false positive seems to have been removed https://github.com/TheCSMods/mc-better-stats/issues/111#issuecomment-1986990489

**Comment by ricksouth** [comment]
Appreciate you letting me know! Sounds like updating Defender's database will also fix it. Hopefully everyone will have that update over the next few days. I've been receiving quite a few messages about it 😅

I of course totally understand it. It's good to be vigilant. But happy once it's over!
