### ISSUE TITLE
Collective gets detected as a Trojan

### ISSUE THREAD

**Issue by timo-steinbrech** [ricksouth/serilum-mc-mods#2254]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 43.3.8
Environment: Singleplayer / Multiplayer

Mod name: Collective
Mod version: 1.19.2-7.39

## **Description**
Hey! This happened.

when I try to Update to Version 7.39 Microsoft Defender detects the Plugin as a High Risk with the Reason "The Application was trying to run bad code we detected this Application as a Trojan:Script/Wacatac.B!ml

**Comment by ricksouth** [comment]
Thank you for the report, but unfortunately there is nothing I can do on my end. Windows Defender has targeted many Minecraft mods, from several authors, by detecting a trojan. It is a false positive, and please report the file to Defender as such. I can assure you there is no virus in there. I have double checked my files locally, and what has been uploaded to CurseForge. I'm not the only one getting these reports unfortunately.

I've heard from other users that updating Microsoft Defender via Windows Updates should fix it.
