### ISSUE TITLE
Starter kits commands

### ISSUE THREAD

**Issue by SolarReborn** [ricksouth/serilum-mc-mods#2259]
## **Information**
Minecraft version: 1.20.2
Modloader: Forge 
Environment: Multiplayer

Mod name: Starter kits
Mod version: 1.20.2-5.5

## **Question**
I am only able to use the command /starterkit set
No other command works for me, anything I can do?

**Comment by ricksouth** [comment]
Hi! The new commands are added in version 6.0 of Starter Kit. I'm currently only actively developing 1.19.2, 1.20.1 and 1.20.4. So you'll need to update to use any of those versions to be able to use the new features of Starter Kit. Apologies for the inconvenience.
