### ISSUE TITLE
Double Fence-Gates: Opens One Only

### ISSUE THREAD

**Issue by Lukuro-Zaw** [ricksouth/serilum-mc-mods#2262]
## **Information**
Minecraft version: 1.20.1
Modloader: Forge
Forge version: 0.247.1.16850
Environment: Singleplayer

Mod name: Double Doors
Mod version: 1.20.1-5.4

## **Description**
Fence Gates that are side by side only open one at a time like default Minecraft. Redstone does activate both gates but only fence gates paired with manually opening that they don't both open.

I am using Minecraft 1.20.1 due to my modpack and comfortability.

**Comment by Magnogen** [comment]
Bump! I also have this problem on 1.20.4

![an image of a fence gate surrounded by closed fence gates](https://github.com/Serilum/.issue-tracker/assets/25611707/97fe3a6d-55d3-40df-9aa4-5c6cb8da437a)

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 5.5 of Double Doors.

https://curseforge.com/minecraft/mc-mods/double-doors/files
