### ISSUE TITLE
Nether Portal Spread not swapping blocks with metadata

### ISSUE THREAD

**Issue by GoldMikeDev** [ricksouth/serilum-mc-mods#2265]
Minecraft version: 1.12.2
Modloader: Forge
Forge version: 14.23.5.2860
Environment: Singleplayer

Mod name: Nether Portal Spread
Mod version: 5.4

So I'm not 100% sure if this is a bug or if I'm not doing the syntax correctly but when I use the spreadsettings.txt to add blocks with metadata they just don't seem to work at all. All the blocks in the list without metadata work perfectly and get swapped out fine but it's like the ones with just get skipped over. I've read through the curseforge page multiple times but none of the examples given use metadata so I was beginning to wonder if it just isn't supported?

This is my current spreadsettings.txt if that helps.
[spreadsettings.txt](https://github.com/Serilum/.issue-tracker/files/14622562/spreadsettings.txt)

**Comment by ricksouth** [comment]
This has been fixed in the latest version of Nether Portal Spread, but unfortunately I am no longer supporting Minecraft 1.12.2. I also can't do that easily, without having to set up a dev environment and updating the library. Apologies for the inconvenience.
