### ISSUE TITLE
java.util.ConcurrentModificationException: Async entity load

### ISSUE THREAD

**Issue by Romans96** [ricksouth/serilum-mc-mods#2271]
## **Information**
Minecraft version: 1.20.1
Modloader:  Fabric
Fabric loader version: 0.15.7
Environment: Singleplayer / Multiplayer

Mod name: Dimount Entity
Mod version: 3.2

## **Description**
Hello! Using the mods *Happiness is a Warm Gun* and the relative lib *AzureLIb*, the game crashes on a Gun Shot.
Remoing this Mod HWG works perfectly. Otherwise if i remove HWG Dismount Entity works perfectly with no crashes

## **Crash report**
https://pastebin.com/8wbQ5SiZ

**Comment by James103** [comment]
The paste you linked to contains the logs leading up to the crash. Do you have the actual corresponding crash report? If not, can you please try reproducing this issue again and post the full mod list?
