### ISSUE TITLE
[Fabric 1.20.1] Choosing kit GUI client crash

### ISSUE THREAD

**Issue by RyoidenshiRyu** [ricksouth/serilum-mc-mods#2278]
## **Information**
Minecraft version: 1.20.1
Modloader: Fabric
Fabric loader version: 0.15.7
Environment: Singleplayer | Multiplayer (Dedicated Server)

Mod name: Starter Kit
Mod version: 1.20.1-6.5

## **Description**
Hello. Was making kits for my server, through chat it works fine. But when I tried to use choosing kit GUI, game crashes.
Server continues to work after client crashes.
Since it's saying something about rendering screen, first I'm used Sodium, after Embeddium, but game still crashes.

## **Crash report**
Here are 2 logs and 1 crash-report:
[ClientLog-latest.log](https://github.com/Serilum/.issue-tracker/files/14681334/ClientLog-latest.log)
[crash-2024-03-21_09.49.48-client.txt](https://github.com/Serilum/.issue-tracker/files/14681335/crash-2024-03-21_09.49.48-client.txt)
[ServerLog-latest.log](https://github.com/Serilum/.issue-tracker/files/14681337/ServerLog-latest.log)

**Comment by RyoidenshiRyu** [comment]
Tested it with Starter Kit version 6.7. Game still crashes when on dedicated server.
Although works on LAN (local) server or singleplayer.
[crash-2024-05-22_15.05.59-client.txt](https://github.com/Serilum/.issue-tracker/files/15400023/crash-2024-05-22_15.05.59-client.txt)
And sorry for the delay.
Fabric Modloader 0.15.11
Mods used:
Starter Kit 6.7
Collective 7.57
Fabric API 0.92.1-1.20.1

**Comment by SomeGuyEight** [comment]
Hey, same issue here. on a client using at launcher logging into a server hosted on a machine in the same network. I can log in with accounts that don't need a starter kit and use most commands. It is only when logging in for the first time. 

[crash-2024-05-29_17.31.21-client.txt](https://github.com/Serilum/.issue-tracker/files/15492148/crash-2024-05-29_17.31.21-client.txt)

Fabric Modloader 0.15.10
Minecraft 1.20.1
Java 17.0.8

Starter Kit 6.7
Collective 7.6.1
Fabric API 0.92.1-1.20.1

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 6.9 of Starter Kit.

https://www.curseforge.com/minecraft/mc-mods/starter-kit/files
