### ISSUE TITLE
Fence Gates not oppening together with Double Doors

### ISSUE THREAD

**Issue by Piratefox1987** [ricksouth/serilum-mc-mods#2281]
**Information**
Minecraft version: 1.20.1
Modloader: Forge
Forge version: 47.2.0
Environment: Singleplayer

Mod name: Double Doors
Mod version: 5.4

**Description**
I was figureing out why the normal doors were oppening and imediately shutting when I tried to open them, which turns out to have been due to having Quark installed aswell becuase both mods add in the same feature, and I noticed that the fence gates weren't opening together. I thought it was due to Quark again aswell, but that doesn't seem to be the case.

Mod List:

Amendments
AppleSkin
Balm (Forge Edition)
Cary On
Collective
Connected Glass
Customizable Player Models
Double Doors
Duckling
ESSENTIAL Mod
Fusion (Connected Textures)
GeckoLib
Iris Shaders
JourneyMap
Just Enough Items (JEI)
Macaw's Bridges
Macaw's Doors
Macaw's Fences and Walls
Macaw's Furniture
Macaw's Trapdoors
Moonlight Lib
Pehkui
Quark
Skin Layers 3D (Fabric/Forge)
Skinned Lanterns (Forge)
Sound Physics Remasterd
SuperMartijn642's Core Lib
Supplementaries
Waystones
WorldEdit
YDM's Weapon Master
Zeta

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 5.5 of Double Doors.

https://curseforge.com/minecraft/mc-mods/double-doors/files
