### ISSUE TITLE
Game crash after I turn on "Advance Section"

### ISSUE THREAD

**Issue by YixiongZhou** [ricksouth/serilum-mc-mods#2283]
## **Information**
Minecraft version: 1.20.1
Modloader:  Fabric
Fabric loader version: 0.92.0
Environment: Multiplayer

Mod name: Starter Kit
Mod version: 6.5

## **Description**
Hey! This happened.
After I activated all kits on the server, I used the reset command and tried to log into the server again to test it. And it crashed every time. I have not tried it on a private game yet, since I thought it wouldn't work either.

## **Crash report**
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2024-03-23 05:59:58
Description: Rendering screen

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1703.method_34255()" because "this.menu" is null
	at com.natamus.starterkit_common_fabric.inventory.StarterKitAbstractContainerScreen.renderTooltip(StarterKitAbstractContainerScreen.java:180)
	at com.natamus.starterkit_common_fabric.inventory.StarterKitInventoryScreen.method_25394(StarterKitInventoryScreen.java:169)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.method_3192(class_757.java:945)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.natamus.starterkit_common_fabric.inventory.StarterKitAbstractContainerScreen.renderTooltip(StarterKitAbstractContainerScreen.java:180)
	at com.natamus.starterkit_common_fabric.inventory.StarterKitInventoryScreen.method_25394(StarterKitInventoryScreen.java:169)
	at net.minecraft.class_437.method_47413(class_437.java:110)

-- Screen render details --
Details:
	Screen name: com.natamus.starterkit_common_fabric.inventory.StarterKitInventoryScreen
	Mouse location: Scaled: (2147483647, 2147483647). Absolute: (1637.000000, 363.000000)
	Screen size: Scaled: (854, 480). Absolute: (2560, 1440). Scale factor of 3.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:945)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['Icefloor233'/447, l='ClientLevel', x=14.15, y=117.00, z=11.29]]
	Chunk stats: 1024, 453
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,117,0), Section: (at 0,5,0 in 0,7,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 74738 game time, 74738 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:821)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, Moonlight Mods Dynamic Assets

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 576670328 bytes (549 MiB) / 3011510272 bytes (2872 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 32
	Processor Vendor: GenuineIntel
	Processor Name: 13th Gen Intel(R) Core(TM) i9-13950HX
	Identifier: Intel64 Family 6 Model 183 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 2.42
	Number of physical packages: 1
	Number of physical CPUs: 24
	Number of logical CPUs: 32
	Graphics card #0 name: NVIDIA GeForce RTX 4080 Laptop GPU
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x27e0
	Graphics card #0 versionInfo: DriverVersion=31.0.15.5123
	Graphics card #1 name: Intel(R) UHD Graphics
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0xa788
	Graphics card #1 versionInfo: DriverVersion=31.0.101.3425
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 5.60
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 5.60
	Memory slot #1 type: Unknown
	Virtual memory max (MB): 44565.87
	Virtual memory used (MB): 39205.82
	Swap memory total (MB): 12151.23
	Swap memory used (MB): 1066.34
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m
	Fabric Mods: 
		appleskin: AppleSkin 2.5.1+mc1.20
		archers: Archers (RPG Series) 1.0.7+1.20.1
			com_github_zsoltmolnarrr_tinyconfig: TinyConfig 2.3.2
			structure_pool_api: Structure Pool API 1.0+1.20.1
		architectury: Architectury 9.2.14
		artifacts: Artifacts 9.3.1
			cardinal-components-base: Cardinal Components API (base) 5.2.2
			cardinal-components-entity: Cardinal Components API (entities) 5.2.2
			expandability: ExpandAbility 9.0.0
			step-height-entity-attribute: Step Height Entity Attribute 1.2.0
		attributefix: AttributeFix 21.0.4
		azurelibarmor: AzureLib Armor 2.0.3
		bclib: BCLib 3.0.14
			wunderlib: WunderLib 1.1.5
		bettercombat: Better Combat 1.8.4+1.20.1
		betterdeserttemples: YUNG's Better Desert Temples 1.20-Fabric-3.0.3
			org_reflections_reflections: reflections 0.10.2
		betterdungeons: YUNG's Better Dungeons 1.20-Fabric-4.0.3
		betterend: Better End 4.0.11
		betterendisland: YUNG's Better End Island 1.20-Fabric-2.0.5
		betterfortresses: YUNG's Better Nether Fortresses 1.20-Fabric-2.0.6
		betterjungletemples: YUNG's Better Jungle Temples 1.20-Fabric-2.0.4
		bettermineshafts: YUNG's Better Mineshafts 1.20-Fabric-4.0.4
		betternether: Better Nether 9.0.10
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.20-Fabric-3.0.4
		betterstrongholds: YUNG's Better Strongholds 1.20-Fabric-4.0.3
		betterthirdperson: Better Third Person 1.9.0
		betterwitchhuts: YUNG's Better Witch Huts 1.20-Fabric-3.0.3
		bookshelf: Bookshelf 20.1.9
		cloth-config: Cloth Config v11 11.1.118
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 12.0.0.3
		collective: Collective 7.40
		combatroll: Combat Roll 1.3.1+1.20.1
		configured: Configured 2.2.3
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
		create: Create 0.5.1-f-build.1335+mc1.20.1
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			flywheel: Flywheel 0.6.10-2
			forgeconfigapiport: Forge Config API Port 8.0.0
			milk: Milk Lib 1.2.60
				dripstone_fluid_lib: Dripstone Fluid Lib 3.0.2
			porting_lib_accessors: Porting Lib Accessors 2.3.0+1.20.1
			porting_lib_base: Porting Lib Base 2.3.0+1.20.1
				porting_lib_attributes: Porting Lib Attributes 2.3.0+1.20.1
				porting_lib_common: Porting Lib Common 2.3.0+1.20.1
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.3.0+1.20.1
				porting_lib_utility: Porting Lib Utility 2.3.0+1.20.1
			porting_lib_brewing: Porting Lib Brewing 2.3.0+1.20.1
			porting_lib_client_events: Porting Lib Client Events 2.3.0+1.20.1
			porting_lib_entity: Porting Lib Entity 2.3.0+1.20.1
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.3.0+1.20.1
			porting_lib_extensions: Porting Lib Extensions 2.3.0+1.20.1
			porting_lib_models: Porting Lib Models 2.3.0+1.20.1
				porting_lib_fluids: Porting Lib Fluids 2.3.0+1.20.1
				porting_lib_model_loader: Porting Lib Model Loader 2.3.0+1.20.1
			porting_lib_networking: Porting Lib Networking 2.3.0+1.20.1
			porting_lib_obj_loader: Porting Lib Obj Loader 2.3.0+1.20.1
			porting_lib_tags: Porting Lib Tags 3.0
			porting_lib_tool_actions: Porting Lib Tool Actions 2.3.0+1.20.1
				porting_lib_core: Porting Lib Core 2.3.0+1.20.1
			porting_lib_transfer: Porting Lib Transfer 2.3.0+1.20.1
			reach-entity-attributes: Reach Entity Attributes 2.4.0
			registrate-fabric: Registrate for Fabric 1.3.62-MC1.20.1
				porting_lib_data: Porting Lib Data 2.1.1090+1.20
				porting_lib_model_generators: Porting Lib Model Generators 2.1.1090+1.20
					porting_lib_gametest: Porting Lib GameTest 2.1.1090+1.20
					porting_lib_model_materials: Porting Lib Model Materials 2.1.1090+1.20
		deeperdarker: Deeper and Darker 1.2.6
			customportalapi: Custom Portal Api 0.0.1-beta64-1.20
		dummmmmmy: MmmMmmMmmMmm 1.20-1.8.14
		dungeon_difficulty: Dungeon Difficulty 2.0.6+1.20.1
		dungeons_arise: When Dungeons Arise 2.1.56.1
		dungeons_arise_seven_seas: When Dungeons Arise: Seven Seas 1.0.2
		enchdesc: EnchantmentDescriptions 17.0.14
		fabric-api: Fabric API 0.92.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577
			fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.1+1802ada577
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.4+1802ada577
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabricloader: Fabric Loader 0.15.7
			mixinextras: MixinExtras 0.3.5
		findme: FindMe 3.2.1
		fpsdisplay: FPS-Display 3.1.0+1.20.x
		fwaystones: Fabric Waystones 3.3.2+mc1.20.1
		gazebo: Gazebos 1.1.1+1.20.1
		geckolib: GeckoLib 4 4.4.4
			com_eliotlash_mclib_mclib: mclib 20
		handcrafted: Handcrafted 3.0.6
		immersive_aircraft: Immersive Aircraft 0.7.5+1.20.1
			org_mariuszgromada_math_mathparser_org-mxparser: MathParser.org-mXparser 5.2.1
		indium: Indium 1.0.30+mc1.20.4
		inventorysorter: Inventory Sorter 1.9.0-1.20
			kyrptconfig: Kyrpt Config 1.5.6-1.20
		iris: Iris 1.6.17
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		jade: Jade 11.7.0
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 15.3.0.1
		jewelry: Jewelry (RPG Series) 1.2.4+1.20.1
		journeymap: Journeymap 5.9.18p1
			journeymap-api-fabric: JourneyMap API 1.20-1.9-fabric-SNAPSHOT
		lambdynlights: LambDynamicLights 2.3.2+1.20.1
			pride: Pride Lib 1.2.0+1.19.4
			spruceui: SpruceUI 5.0.0+1.20
		letmedespawn: Let Me Despawn 1.2.0
		mcdw: MC Dungeons Weapons 9.0.1
		minecraft: Minecraft 1.20.1
		moonlight: Moonlight 1.20-2.11.9
		mythicmounts: Mythic Mounts 1.20.1-7.4
		naturalist: Naturalist 4.0.3
		nyfsquiver: Nyf's Quivers 1.20.1-fabric-1.0.4
		owo: oωo 0.11.0+1.20
			blue_endless_jankson: jankson 1.2.2
		paladins: Paladins & Priests (RPG Series) 1.0.5+1.20.1
		patchouli: Patchouli 1.20.1-84-FABRIC
			fiber: fiber 0.23.0-2
		player-animator: Player Animator 1.0.2-rc1+1.20
		projectile_damage: Projectile Damage Attribute 3.2.2+1.20.1
		puffish_skills: Pufferfish's Skills 0.11.3
		resourcefullib: Resourceful Lib 2.1.23
			com_teamresourceful_bytecodecs: bytecodecs 1.0.2
			com_teamresourceful_yabn: yabn 1.0.3
		runes: Runes 0.9.11+1.20.1
		simplehats: SimpleHats 1.20.1-0.2.0
		simplyskills: SimplySkills 1.2.1+1.20.1
		simplyswords: Simply Swords 1.54.0-1.20.1
		skinlayers3d: 3d-Skin-Layers 1.6.2
		sodium: Sodium 0.5.8+mc1.20.1
		soulsweapons: Marium's Soulslike Weaponry 1.1.1-1.20-fabric
		spell_engine: Spell Engine 0.12.5+1.20.1
		spell_power: Spell Power Attribute 0.9.19+1.20.1
		starterkit: Starter Kit 6.5
		terralith: Terralith 2.4.11
		travelersbackpack: Traveler's Backpack 1.20.1-9.1.9
		trinkets: Trinkets 3.7.2
		villagernames: Villager Names 7.3
		wizards: Wizards (RPG Series) 1.0.5+1.20.1
		yet_another_config_lib_v3: YetAnotherConfigLib 3.2.2+1.20
			com_twelvemonkeys_common_common-image: common-image 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-io: common-io 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0-SNAPSHOT
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		yungsapi: YUNG's API 1.20-Fabric-4.0.4
			org_javassist_javassist: javassist 3.29.2-GA
		yungsbridges: YUNG's Bridges 1.20-Fabric-4.0.3
		yungsextras: YUNG's Extras 1.20-Fabric-4.0.3
	Loaded Shaderpack: Bliss-Shader-main.zip
		Profile: Custom (+0 options changed by user)
	Flywheel Backend: Off
	Launched Version: fabric-loader-0.15.7-1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 4080 Laptop GPU/PCIe/SSE2 GL version 3.2.0 NVIDIA 551.23, NVIDIA Corporation
	Window size: 2560x1440
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: fabric
	Current Language: zh_cn
	CPU: 32x 13th Gen Intel(R) Core(TM) i9-13950HX

**Comment by YixiongZhou** [comment]
I just tried a couple of times. It's only crashing on the server.

**Comment by YixiongZhou** [comment]
*misclicked

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 6.9 of Starter Kit.

https://www.curseforge.com/minecraft/mc-mods/starter-kit/files
