### ISSUE TITLE
saplings not dropping properly

### ISSUE THREAD

**Issue by SauceThe2nd** [ricksouth/serilum-mc-mods#2289]
## **Information**
Minecraft version: 1.20.1
Modloader:  Fabric
Forge version:  Fabric loader version: 0.15.7-1.20.1
Environment: Singleplayer / Multiplayer

Mod name: Tree Harvester
Mod version: 8.7

## **Description**
I planted a 4x4 patch of oak sapplings, they all grew, then i chopped it down using the mod. I got enough sapplings to plant 50% back, at first i thought i got unlucky with the 5% drop chance from leaves. Then it happened to my other 2 plots as well and 3 times in a row, now that i am mining manually i have a lot of "luck" again. Dunno, maybe it is nothing, but would appreciate i set of expirienced eyes to look at it

## **Crash report**
_(Please either drag the file directly here, or use https://gist.github.com/ to prevent the paste from expiring)_

If available.

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 9.1 of Tree Harvester. Appreciate it.

https://curseforge.com/minecraft/mc-mods/tree-harvester/files
