### ISSUE TITLE
Starter Kit has only 1 command

### ISSUE THREAD

**Issue by bic060** [ricksouth/serilum-mc-mods#2303]
## **Information**
Minecraft version: 1.16.5
Modloader: Forge 
Forge version: 36.2.34  
Environment: Multiplayer

First mod name: Pixelmon modpack
First mod version: 9.1.11

SpongeAPI Plugin 

Luckperms Plugin

## **Description**
As mentioned in the title, I can only execute 1 command of the starter kit (/starterkit set), and I can't even set a name for the kit. I've tried adding a permission command node of the starter kit (minecraft.command.starterkit), but seems it didn't help. 

## **Crash report**
If available.

**Comment by ricksouth** [comment]
The extra functionality was added in version 6.0 of Starter Kit. I don't actively develop for 1.16.5 anymore, so the new commands aren't included in that. Apologies for the inconvenience.
