### ISSUE TITLE
[Pumpkillager's Quest] Quest Book text formatting broken 

### ISSUE THREAD

**Issue by brokeAK** [ricksouth/serilum-mc-mods#2309]
## **Information**
Minecraft version: 1.20.4
Modloader: Fabric
Fabric loader version: x.xx.x
Environment: Singleplayer / Multiplayer

Mod name: Pumpkillager's Quest
Mod version: 3.7

## **Description**
Hello! The Pumpkillager's quest book shows up without formatting. Can't complete the quests with how it's not showing any useful information. 
![Screenshot 2024-04-15 125409](https://github.com/Serilum/.issue-tracker/assets/34329701/0dfb00d1-d9c5-4fc1-8a44-36b9ff48ea12)
![Screenshot 2024-04-15 125357](https://github.com/Serilum/.issue-tracker/assets/34329701/2e785862-ba5a-4140-90b1-f2639f549747)
![Screenshot 2024-04-15 125344](https://github.com/Serilum/.issue-tracker/assets/34329701/7cae94c3-d03e-4396-ac06-91e7af84084b)
![Screenshot 2024-04-15 125330](https://github.com/Serilum/.issue-tracker/assets/34329701/9d5fd188-d0eb-42fe-a829-d14dd7cc33a3)
Any support would be appreciated!

**Comment by brokeAK** [comment]
I see you've added the tag. If you need any further data from me let me know :D

**Comment by brokeAK** [comment]
I see you've added the tag. If you need any further data from me let me know :D

**Comment by ricksouth** [comment]
Thank you for opening the issue, and giving the mod a try! This has been fixed in version 4.3 of Pumpkillager's Quest. Apologies for the inconvenience.

https://www.curseforge.com/minecraft/mc-mods/pumpkillagers-quest/files
