### ISSUE TITLE
Incompatibility Issue with Advancement Plaques

### ISSUE THREAD

**Issue by FatalUserK** [ricksouth/serilum-mc-mods#2312]
## **Information**
Minecraft version: 1.20.4
Modloader: Fabric
Fabric loader version: 1.15.9
Environment: Singleplayer

Mod name: Advancement Screenshot
Mod version: 4.7

## **Description**
Obtaining an advancement with Advancement Plaques 1.5.1 enabled causes the screenshot to not be taking, I suspect the mod is not recognising the advancement properly due to AP displaying advancements differently than vanilla

**Comment by FatalUserK** [comment]
Being used in a client-side modpack, highly unlikely to be relevant but I have some other mods in there, however the screenshots only fail when enabling Advancement Plaques specifically

**Comment by FatalUserK** [comment]
Confirmed that the mod happens even when no other mods are enabled, full modlist here:

Advancement Plaques 1.5.1
Iceberg 1.1.18 (AP Dependency)
Forge Config API Port 20.4.3 (AP Dependency)
Advancement Screenshot 4.7
Collective 7.40 (AS Dependency)
Fabric API (Everything Dependency)

Bare minimum mods and the bug still persists

**Comment by FatalUserK** [comment]
didnt clarify the literal observable effect, somehow forgot that, basically obtaining an advancement causes nothing to happen, no screenshot, not mention in chat, you just get an advancement, my assumption is that it's failing to recognise the advancement due to how AP displays advancements differently

**Comment by FatalUserK** [comment]
might have a fix soon on Advancement Plaques' end soon

**Comment by FatalUserK** [comment]
### **UPDATE:** 
Issue has been resolved on **Advancement Plaques**' end, mod now takes a screenshot correctly when an advancement is obtained, **incompatibility has been resolved**


_(meant to make this yesterday lmao)_

**Comment by ricksouth** [comment]
Glad it was fixed, thanks for letting me know!

**Comment by Shodelat** [comment]
> ### **UPDATE:**
> Issue has been resolved on **Advancement Plaques**' end, mod now takes a screenshot correctly when an advancement is obtained, **incompatibility has been resolved**
> 
> _(meant to make this yesterday lmao)_

this needs to be fixed for 1.20.1 fabric😭

**Comment by VaOnechezz** [comment]
@ricksouth is there any way to fix this thing please <3 ? 
I play neoforge minecraft 1.21.1, got same issue (screenshots don't being made with plaques mod)
I have the most fresh versions of both mods
