### ISSUE TITLE
Double doors instantly close when you try to open them.

### ISSUE THREAD

**Issue by Nejliika** [ricksouth/serilum-mc-mods#2317]
## **Information**
Minecraft version: 1.20.1
Modloader: Forge 
Forge version: 47.2.0
Environment: Multiplayer

Mod name: Double doors
Mod version: 1.20.1-5.4

## **Description**
When me and my friend try to open double doors they open and closes instantly and we don't know why. We play on a multiplayer server one of our friends made themselves.

## **Crash report**
It doesn't crash our game, it is just annoying.

**Comment by ricksouth** [comment]
Do you have Quark installed by chance? I think they have double door functionality as well, which makes the doors open and close

**Comment by Nejliika** [comment]
Oh that's why! Thank you so much for the help (:
