### ISSUE TITLE
Develop older versions of Starter Kit

### ISSUE THREAD

**Issue by Froggjarl** [ricksouth/serilum-mc-mods#2318]
## **Information**
Minecraft version: 1.18.2
Modloader: Forge

Mod name: Starter Kit

## **develop older versions**
I think that upgrading older versions of this mod with the commands and other features from the newer versions would make it a better mod and allow it to be used in more mod packs.

**Comment by ricksouth** [comment]
While I'd love to keep all versions updated, it's just not feasable with the time. I can't easily update older versions without setting up a dev environment, and updating the library as well. Apologies for the inconvenience.
