### ISSUE TITLE
mod flagged as malware

### ISSUE THREAD

**Issue by papamaionise** [ricksouth/serilum-mc-mods#2320]
![Screenshot (1410)](https://github.com/Serilum/.issue-tracker/assets/126779287/56a05a17-4ebb-4ad9-9556-16f6be3dedf8)

**Comment by ricksouth** [comment]
It's a false positive, which OS are you on?

**Comment by papamaionise** [comment]
> It's a false positive, which OS are you on?

windows

**Comment by papamaionise** [comment]
> It's a false positive, which OS are you on?

using brave browser

**Comment by ricksouth** [comment]
You'll need to update Windows Defender, see the following issue for more information on it:

https://github.com/Serilum/.issue-tracker/issues/2255

But basically just go to Windows Update and update there. That should fix the false flag

**Comment by papamaionise** [comment]
> You'll need to update Windows Defender, see the following issue for more information on it:
> 
> #2255
> 
> But basically just go to Windows Update and update there. That should fix the false flag

Thanks a lot for your help it worked for me was having same problem with    do a barrel role mod    too

**Comment by ricksouth** [comment]
Good to hear! Thank you for giving the mods a try :)
