### ISSUE TITLE
Weird Visual Artifacts on Latest Collective

### ISSUE THREAD

**Issue by RyanSalad** [ricksouth/serilum-mc-mods#2327]
## **Information**
Minecraft version: 1.19.2
Modloader: Fabric
Fabric loader version: 0.15.10
Environment: Singleplayer

Mod name: Collective
Mod version: 7.50

## **Description**
Hey! Upon loading up my modpack with the latest version of Collective, I noticed that block entities were not visible where they were placed, and that for some reason they appeared to be rendered weirdly inverted and off into the edge of my screen and kind of orbit my field of view as I rotate my camera. Here's a screenshot that I took and then cropped a bit to make it easier to see.

![collectivebug](https://github.com/Serilum/.issue-tracker/assets/130966747/66ceb2eb-e660-41c7-a60f-7fac039bc8dd)

## **Crash report**
No crashing or anything, but I can add the log if necessary.

**Comment by ricksouth** [comment]
Thank you for opening the issue, that's strange! From which version did you upload?

**Comment by RyanSalad** [comment]
> Thank you for opening the issue, that's strange! From which version did you upload?

Minecraft version was 1.19.2. Collective version was 7.50

**Comment by ricksouth** [comment]
Yea that's the current version think right? But what did you have before? Trying to determine what could've caused it, and if downgrading again makes it disappear

**Comment by RyanSalad** [comment]
Before I had 7.49. I did downgrade to 7.49 and it was immediately fixed so that's when I decided to come here

**Comment by ricksouth** [comment]
I only added a helper class in 7.50, not sure why it would've caused this. Could you maybe see if it also happens on a clean install of 1.19.2 and Collective 7.50?

**Comment by RyanSalad** [comment]
> I only added a helper class in 7.50, not sure why it would've caused this. Could you maybe see if it also happens on a clean install of 1.19.2 and Collective 7.50?

Will do. Give me just a moment

**Comment by RyanSalad** [comment]
It appears to be working fine with no weird visual bugs on a completely fresh install

**Comment by ricksouth** [comment]
Even stranger! Could you maybe try updating from 7.49 -> 7.50 again in your main pack to see if it still happens?

**Comment by RyanSalad** [comment]
Yes I can do that. One moment

**Comment by RyanSalad** [comment]
Okay this is kind of insane, but it's fine now. Updating to 7.50 this time was fine! Same world, same blocks, and the same mods

**Comment by ricksouth** [comment]
That's... good? 😅 Appreciate you opening the issue nonetheless. I'll keep an eye out for other bug reports, and please let me know if it happens again.

**Comment by RyanSalad** [comment]
Yeah haha. I'm glad it didn't happen again, but I'm perplexed as to why it happened the first time. I'll definitely let you know if it happens again!
