### ISSUE TITLE
Cannot combine enchanted items in an anvil

### ISSUE THREAD

**Issue by icehorse2401** [ricksouth/serilum-mc-mods#2337]
## **Information**
Minecraft version: 1.20.6
Modloader: Fabric
Fabric loader version: 0.15.10
Environment: Singleplayer and Multiplayer

Mod name: What Durability?
Mod version: 1.1

## **Description**
Although no items have durability, no items can be combined in an anvil anymore. Trying to combine two undamaged items does not work in an anvil, and coming two enchanted items does not combine the items or the enchantments.

To reproduce, go into creative, place an anvil, enchant one sword with sharpness and the other sword with unbreaking. Try to combine both swords in an anvil, it will not work. Hopefully this can be fixed.

Here's a similar mod that fixed this issue already, but they are slow at updating and don't have a 1.20.6 version available: https://modrinth.com/mod/nodurability/versions

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 1.3 of What Durability. Appreciate it.

https://curseforge.com/minecraft/mc-mods/what-durability/files
