### ISSUE TITLE
Just mob heads crash, off screen

### ISSUE THREAD

**Issue by Voidmaster01** [ricksouth/serilum-mc-mods#2339]
## **Information**
Minecraft version: 1.20.1
Modloader: Fabric
\Fabric loader version: 0.15.11
Environment: Singleplayer

Mod name: Just Mob Heads
Mod version: 7.6

## **Description**
I crashed when working on mod updates and other stuff for my Modpack, but it only crashed after a head from a mob that was no where near me dropped.

## **Crash report**
https://gist.github.com/Voidmaster01/69ccf21a0761b1b817159ea8febd98b2
https://gist.github.com/Voidmaster01/56328030eab776982ef2014f370f51f4

**Comment by Voidmaster01** [comment]
I do not know how to add labels

**Comment by ricksouth** [comment]
Are you on the latest Collective version?

**Comment by ricksouth** [comment]
Yea I think the issue is that Collective is updated but Just Mob Heads isn't. Version 7.7 of JMH should fix the issue

**Comment by Voidmaster01** [comment]
thank you, i thought i updated all of my mods but apparently the execution did not go through.

**Comment by ricksouth** [comment]
Thanks for giving the mod a try! :)

**Comment by Voidmaster01** [comment]
we have been using this mod for months now, on the Landscapes Reimagined Genesis Modpack
