### ISSUE TITLE
Double doors don't door doubly

### ISSUE THREAD

**Issue by jarbarsi** [ricksouth/serilum-mc-mods#2340]
## **Information**
Minecraft version: 1.20.6
Modloader: Fabric
Fabric loader version: 0.15.11
Environment: Both Multiplayer and Singleplayer

Mod name: Double Doors
Mod version: 5.5

## **Description**
Simple as, right clicking on one door only opens one door, both doors only open on redstone input
![image](https://github.com/Serilum/.issue-tracker/assets/44042848/4d2dd3fb-396c-4f0e-a6da-ed83cc87028d)
![image](https://github.com/Serilum/.issue-tracker/assets/44042848/52231837-7ce5-44ca-a2d1-83685fe4f314)

## **Crash report**
No errors logged, no crash, not applicable.

**Comment by ricksouth** [comment]
Thank you for opening the issue! This has been fixed in version 5.6 of Double Doors.

https://curseforge.com/minecraft/mc-mods/double-doors/files
