### ISSUE TITLE
No Recepie

### ISSUE THREAD

**Issue by YahMooBoo324000** [ricksouth/serilum-mc-mods#2342]
Minecraft version: 1.20.5
Modloader: Fabric
Environment: Singleplayer
Mod name: Name Tag Tweaks

Hi! 
For some reason the mod's features do work, all excpet the recepie, which is a bummer because the recepie is the whole reason I downloaded the mod in the first place, Mod's version is 3.3 and I am on Fabric 0.15.11, please tell me what happened wrong so there will be a recepie to craft the name tag :)

**Comment by ricksouth** [comment]
Thank you for opening the issue! This has been fixed in version 3.4 of Name Tag Tweaks.

https://curseforge.com/minecraft/mc-mods/name-tag-tweaks/files
