### ISSUE TITLE
Placing a melon/pumpkin next to farmland and breaking it changes the block underneath the melon/pumpkin to farmland

### ISSUE THREAD

**Issue by ildiem** [ricksouth/serilum-mc-mods#2344]
## **Information**
Minecraft version: 1.20.1
Modloader: Forge
Forge version: 47.2.30
Environment: Singleplayer

Mod name: Keep My Soil Tilled
Mod version: 2.2

## **Description**
If you have a patch of farmland and you place a melon/pumpkin directly next to it and one block up, it will change the block underneath the melon/pumpkin into farmland, regardless of what block was there previously.

https://github.com/Serilum/.issue-tracker/assets/81544216/a7a62914-8987-45b0-980c-e8857b4c7c81

**Comment by ricksouth** [comment]
Thank you for opening the issue! This has been fixed in version 2.3 of Keep My Soil Tilled.

https://curseforge.com/minecraft/mc-mods/keep-my-soil-tilled/files
