### ISSUE TITLE
Game crashes due to GUI Compass format settings

### ISSUE THREAD

**Issue by TonyAki** [ricksouth/serilum-mc-mods#2347]
## **Information**
Minecraft version: 1.20.6
Modloader: Fabric
Fabric loader version: 0.15.11
Environment: Singleplayer (not tested on Multiplayer)

Mod name: GUI Compass
Mod version: 4.4

## **Description**
In the mod settings for GUI Compass, deleting everything in the "Format" box causes the game to crash.

## **Crash report**
[crash-2024-05-06_11.24.01-client.txt](https://github.com/Serilum/.issue-tracker/files/15224895/crash-2024-05-06_11.24.01-client.txt)

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 4.6 of GUI Compass.

https://curseforge.com/minecraft/mc-mods/gui-compass/files
