### ISSUE TITLE
1.20.6 (Stack Refill) Random Crashing 

### ISSUE THREAD

**Issue by DrSkywalker** [ricksouth/serilum-mc-mods#2348]
## **Information**
Minecraft version: 1.20.6
Modloader: Fabric
Fabric loader version: 0.15.11
Environment: Singleplayer

Mod name: Stack Refill
Mod version: 1.20.6-4.3-fabric+forge+neo

## **Description**
Random Crashing with the Crash log Reporting 
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 10

## **Crash report**
https://gist.github.com/DrSkywalker/d358856ce1738852535b5169b57a05e9

If available.

**Comment by DrSkywalker** [comment]
https://gist.github.com/DrSkywalker/492dc6dd5508f5a3c9c7b75212a3463e
This is another Crash that happened earlier as well

**Comment by ffuentesm** [comment]
Also got a crash when I tried to sleep 
Minecraft version: 1.20.6
Modloader: NeoForge
NeoForge loader version: 20.6.72
Environment: Singleplayer

Mod name: Stack Refill
Mod version: stackrefill-1.20.6-4.3.jar  

[crash-2024-05-18_23.48.41-client.txt](https://github.com/Serilum/.issue-tracker/files/15367494/crash-2024-05-18_23.48.41-client.txt)

**Comment by ricksouth** [comment]
Thank you for opening the issue and the crash reports. Apologies it took a while for me to get to. This has been fixed in version 4.4 of Stack Refill.

https://curseforge.com/minecraft/mc-mods/stack-refill/files

**Comment by DrSkywalker** [comment]
Its all good rick thanks for the updates !!! hopefully it helped!
