### ISSUE TITLE
Compatibility With Netherite Elytra

### ISSUE THREAD

**Issue by Tofugrass** [ricksouth/serilum-mc-mods#235]
Wondering if you could add easy take off to the Netherite Elytra in this mod https://www.curseforge.com/minecraft/mc-mods/netherite-elytra. 

label:"Mod: Easy Elytra Takeoff"

**Comment by ricksouth** [comment]
This is not something I can do on my end. I've asked the author to extend ElytraItem instead of Item in his code, which should make the mods compatible. Thanks for using the mod!

**Comment by DrunkBlood** [comment]
1.16.3 has now the change
