### ISSUE TITLE
[Name Tag Tweaks] Error loading mod

### ISSUE THREAD

**Issue by WalkerWilder** [ricksouth/serilum-mc-mods#2351]
## **Information**
Minecraft version: 1.20.6
Modloader: Forge
Forge version: 50.0.7
Environment: Multiplayer

Mod name: Name Tag Tweaks
Mod version: 3.3

## **Description**
Loading the server with this mod shows error messages.
The server loads as normal and I found no issues, but the mod does nothing.

I'm new to modded, please let me know if it's something I'm doing wrong.

## **Crash report**
[name_tag_bug.txt](https://github.com/Serilum/.issue-tracker/files/15236997/name_tag_bug.txt)

**Comment by ricksouth** [comment]
Thank you for opening the issue! This has been fixed in version 3.4 of Name Tag Tweaks.

https://curseforge.com/minecraft/mc-mods/name-tag-tweaks/files

**Comment by WalkerWilder** [comment]
Updated Name Tag Tweaks and Collectives on my server for this version and everything worked well.
Thank you for the fast response.
Amazing work on the projects.
