### ISSUE TITLE
Zombie Villager Crashes Server

### ISSUE THREAD

**Issue by TheWanderingTrader** [ricksouth/serilum-mc-mods#2352]
## **Information**
Minecraft version: 1.20.6
Modloader: Fabric
Fabric loader version: 0.15.11
Environment: Multiplayer

Mod name: Zombie Villagers from Spawners
Mod version: 3.8

## **Description**
Zombie Villager spawned and crashed the server due to "illegal name".

## **Crash report**
[crash-2024-05-07_16.26.44-server.txt](https://github.com/Serilum/.issue-tracker/files/15238605/crash-2024-05-07_16.26.44-server.txt)

If available.

**Comment by ricksouth** [comment]
Thank you for opening the issue. This has been fixed in version 7.57 of Collective.

https://curseforge.com/minecraft/mc-mods/collective/files
