### ISSUE TITLE
doors not staying open

### ISSUE THREAD

**Issue by heavytfc** [ricksouth/serilum-mc-mods#2353]
## **Information**
Minecraft version: 1.20.1
Modloader: Forge 
Forge version: 47.2.30
Environment: Singleplayer
double doors won't stay open when clicked on, but will open with redstone signal
what I mean by doors not staying closed is that the doors close immediately after opening when clicked on/ only one frame of the door being open

**Comment by ricksouth** [comment]
Do you have Quark installed? As they have a double door functionality as well. Often conflicting with Double Doors.

**Comment by heavytfc** [comment]
just now checked that and yes that was what it was

**Comment by ricksouth** [comment]
I've just uploaded Double Doors version 5.7 which adds an extra check for this, and edit their config file. That should prevent the issue from coming up again in the future. As Double Doors has extra functionality with e.g. recursive opening. Thanks for giving the mod a try!

https://curseforge.com/minecraft/mc-mods/double-doors/files
