### ISSUE TITLE
[1.20.5+] Name tags dropped don't work

### ISSUE THREAD

**Issue by donottellmetonottellyou** [ricksouth/serilum-mc-mods#2356]
## **Information**
Minecraft version: 1.20.5-1.20.6
Modloader: Fabric
Fabric loader version: 0.15.11
Environment: Singleplayer

Mod name: Name Tag Tweaks
Mod version: 3.4

## **Description**
In 1.20.5, changes were made to the datapack format which haven't been added to the Name Tag page on Minecraft Wiki as of yet. (I believe this is the first version with this issue, but I haven't tested it). You can see the full changes [here](https://minecraft.wiki/w/Java_Edition_1.20.5).

![image](https://github.com/Serilum/.issue-tracker/assets/115233539/02e5e226-d3f4-4f94-8198-263061aa09f7)

The change is that `minecraft:item_name` is no longer used for Name Tag naming. Instead, you must use `minecraft:custom_name`. As you can see in the following image, the Name Tag with the name of "Ernest", which came from a poor villager, is using `item_name`. It cannot be used to name anybody else Ernest, because Minecraft treats it like it doesn't have a name (as indeed it doesn't have a `custom_name`). However, the Name Tag with the name of "frog" (which I named on an anvil) properly uses `custom_name`, and therefore can be used to name a Mob.

![2024-05-09_21 34 25](https://github.com/Serilum/.issue-tracker/assets/115233539/850e7da9-0c3c-41c6-a1f8-c3f85a9cb0e1)

Note that you can tell if an item has a `custom_name` as opposed to a `item_name`, because the `custom_name` defaults to being italic. I haven't modded Minecraft myself, so I don't know if this is an issue you can fix or if this is because of Fabric Loader's datapack generation.

![image](https://github.com/Serilum/.issue-tracker/assets/115233539/41f5a5ed-9e19-4cf6-b747-19b3bc240f9e)
![image](https://github.com/Serilum/.issue-tracker/assets/115233539/1cf92593-ccd3-471d-881d-01433776a8bb)

Thank you for providing your free mods!

**Comment by donottellmetonottellyou** [comment]
I just tested 1.20.4, and it appears that the bug doesn't exist there.

**Comment by donottellmetonottellyou** [comment]
Turns out, `custom_name` actually was the original tag and is still the default, so not sure why the mod would use the non-default `item_name`.

**Comment by ricksouth** [comment]
Thank you for opening the issue and for the detailed description of the problem! It was difficult porting all the mods to the new data format. I have just uploaded version 3.5 of Name Tag Tweaks which correctly uses the `custom_name` field. Appreciate it.

https://curseforge.com/minecraft/mc-mods/name-tag-tweaks/files
