### ISSUE TITLE
[1.20.6] [Neoforge] Crash on lauch

### ISSUE THREAD

**Issue by ffuentesm** [ricksouth/serilum-mc-mods#2359]
## **Information**
Minecraft version: 1.20.6
Modloader: NeoForge 
Forge version: 20.6.53
Environment: Singleplayer 

Mod name: Mod
Mod version: collective-1.20.6-7.57

## **Description**
![image](https://github.com/Serilum/.issue-tracker/assets/44974827/9dec0939-8405-4da9-a145-b26808ae9ebb)

## **Crash report**
https://pastebin.com/QEKCrTNn

**Comment by ricksouth** [comment]
Thank you for opening the issue! Appreciate it. Looks like NeoForge removed the FinalizeSpawn method in 20.6.50-beta. I've just uploaded Collective version 7.58 which will make it compatible again.

https://curseforge.com/minecraft/mc-mods/collective/files
