### ISSUE TITLE
toggle each edible item

### ISSUE THREAD

**Issue by imliterallydoingthistoreportabug** [ricksouth/serilum-mc-mods#236]
## **Information**
Mod name: Edibles

## **Feature description**
would really like the ability to toggle each item's edibility, or even just glowstone tbh. i use another mod that affects glowstone (places a model of it when sneaking) that's unusable cos you just end up eating it

**Comment by ricksouth** [comment]
You can set the duration values to 0 for the item you want to disable. See the description for more details. Thanks for using the mod!

https://www.curseforge.com/minecraft/mc-mods/edibles
