### ISSUE TITLE
GUI Compass 4.6 (NeoForge) Crashes server

### ISSUE THREAD

**Issue by smmmadden** [ricksouth/serilum-mc-mods#2360]
## **Information**
Minecraft version: 1.20.4
Modloader: NeoForge
NeoForge version: 20.4.234
Environment: Multiplayer

Mod name: GUI Compass
Mod version: 4.6 (for 1.20.4) 

## **Description**
As soon as the server started up, it crashed.  Downgrading to 4.4 I don't have this issue.

## **Crash report**
https://pastebin.com/MT83p48E

If available.

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 4.7 of GUI Compass.

https://legacy.curseforge.com/minecraft/mc-mods/gui-compass/files
