### ISSUE TITLE
Structure biome spawning

### ISSUE THREAD

**Issue by Thunderrock424242** [ricksouth/serilum-mc-mods#2368]
## **Information**
Minecraft version: 1.20.1
Modloader: Forge 

Mod name: starter Structure 

## **Feature description**
in the config maybe make a section to define the biome for the starter structure to spawn in.

**Comment by ricksouth** [comment]
You can use the mod in combination with Biome Spawn Point (https://www.curseforge.com/minecraft/mc-mods/biome-spawn-point) which should accomplish what you're trying to do :)
