### ISSUE TITLE
Crash when picking up blank player head

### ISSUE THREAD

**Issue by NoxyNixie** [ricksouth/serilum-mc-mods#2369]
## **Information**
Minecraft version: 1.20.1
Modloader: Forge
Forge version: 47.2.32
Environment: Singleplayer

Mod name: Just Mob Heads
Mod version: 7.7

## **Description**
Crashed when picking up a blank player head that was spawned in using REI and dropped on the ground by the player.

## **Crash report**
[crash-2024-05-16_08.58.39-server.txt](https://github.com/Serilum/.issue-tracker/files/15330945/crash-2024-05-16_08.58.39-server.txt)

**Comment by ricksouth** [comment]
Thank you for opening the issue! This has been fixed in version 7.8 of Just Mob Heads. Appreciate it.

https://curseforge.com/minecraft/mc-mods/just-mob-heads/files
