### ISSUE TITLE
Nametags named using /nametag can not be used. (1.20.6/1.20.5)

### ISSUE THREAD

**Issue by ForestMinecraft** [ricksouth/serilum-mc-mods#2374]
Nametags named using /nametag can not be used on mobs.
Minecraft version: 1.20.6
Modloader: Fabric
Fabric loader version: 0.15.11
Environment: Singleplayer

Mod name: Name Tag Tweaks
Mod version: 3.4

**Comment by ForestMinecraft** [comment]
I looked at the components of regular nametags and ones named using /nametag. A fix would to change it so the command changes minecraft:custom_name instead of minecraft:item_name.

**Comment by ricksouth** [comment]
Thank you for opening the issue! This has been fixed in version 3.5 of Name Tag Tweaks. Appreciate it.

https://curseforge.com/minecraft/mc-mods/name-tag-tweaks/files
