### ISSUE TITLE
Harvester mod does not work on Realms

### ISSUE THREAD

**Issue by Zooluplays** [ricksouth/serilum-mc-mods#2378]
Minecraft version: 1.20.4
Modloader: Forge
Forge version: 49.0.39
Environment: Multiplayer

Mod name: treeharvester
Mod version: 8.7

Hey! when I play singer player it works perfectly fine but it does not work in my realm, not sure why, all my other mods are working properly in it.

Can someone let me know if there is a fix or if I am just missing something.

**Comment by ricksouth** [comment]
The mod must be installed on the server, and a Realms server doesn't use your mod list. Only client-side mods will work there unfortunately.
