### ISSUE TITLE
Armadillo and Wolf Variants Don't Drop Heads

### ISSUE THREAD

**Issue by Puls0r1** [ricksouth/serilum-mc-mods#2381]
## **Information**
Minecraft version: 1.20.6
Modloader: Fabric
Forge version: Fabric loader version: 0.97.8
Environment: Singleplayer 

Mod name: Just Mob Heads
Mod version: 7.8

## **Description**
The Armadillo and new wolf variants do not drop heads. Even when changing to global drop modifier of 1.0, they do not drop heads. When setting global to 1.0 all other mobs drop heads except for the new additions in 1.20.5.

## **Crash report**
No crash report
If available.

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 8.0 of Just Mob Heads.

https://www.curseforge.com/minecraft/mc-mods/just-mob-heads/files
