### ISSUE TITLE
Ore harvester mod crash on startup

### ISSUE THREAD

**Issue by Drakamos** [ricksouth/serilum-mc-mods#2383]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge 
Forge version: 43.3.0
Environment: Singleplayer 
Mod name: Ore Harvester
Mod version: 1.0 release (oreharvester-1.19.2-1.0.jar)

## **Description**
Just a failure to launch the game with this mod active. works fine without, tried other harvester/vein mine mods, works great, got 'error code 1' which ought to be a drivers thing (I checked, it's not), but given that other vein miner mods work fine I wondered if it was something else.

**Comment by ricksouth** [comment]
Can you upload the log? It's located in `/logs/debug.log` or `/logs/latest.log`.

**Comment by ricksouth** [comment]
Managed to find the problem, thank you for opening the issue! This has been fixed in version 1.1 of Ore Harvester.

https://curseforge.com/minecraft/mc-mods/ore-harvester/files
