### ISSUE TITLE
Slimes still spawn on superflat 1.19,2

### ISSUE THREAD

**Issue by mapyDayton22** [ricksouth/serilum-mc-mods#2384]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 43.3.13
Environment: Singleplayer

Mod name: No Slimes Superflat
Mod version: 3.2

## **Description**
I installed the mod but slimes still spawn on superflat worlds

**Comment by ricksouth** [comment]
I've confirmed it working in Forge 1.19.2. Please reinstall or check other mod incompatibilities. Thanks for giving the mod a try!
