### ISSUE TITLE
Dont work

### ISSUE THREAD

**Issue by m4kii420** [ricksouth/serilum-mc-mods#2387]
## **Information**
Minecraft version: 1.20.5
Modloader: Fabric
Fabric loader version: 0.15.11
Environment: both

Mod name: Save and Load Inventories
Mod version: 1.20.5-3.3 fabric
I also added Collective mod

## **Question**
For some reason mod wont load

**Comment by James103** [comment]
1. Which Collective version did you use?
2. Can you please post the logs from attempting to start the game?
