### ISSUE TITLE
Slow crafting after updating to 7.60

### ISSUE THREAD

**Issue by Kishku7** [ricksouth/serilum-mc-mods#2394]
## **Information**
Minecraft version: 1.20.4
Modloader:  Fabric
Fabric loader version: 0.15.10
Environment:  Multiplayer

Mod name: Collective 
Mod version: 7.60

## **Description**
In combination with the mod Quickcraft version 1.2.5 (released June 25th 2022)

Quickcraft allows you to quickly craft by holding down the activation key (in my case Control) to craft a stack at a time. with all versions of Collective prior to 7.60 this worked as designed very quickly.
With Collective 7.60 installed, the quickcrafting takes about 5-10 seconds of delay, and often will not craft at all. After reverting to 7.59 everything works again.

Test: Craft 64 x 9 Iron Ingots into 64 blocks

## **Crash report**
No crashes.

**Comment by ricksouth** [comment]
I shouldn't have touched anything in 7.60 that changes the functionality compared to 7.59. I think it might have been another mod that causes it, but as a start could you see if 7.61 that I just uploaded has the same issue?

**Comment by Kishku7** [comment]
After some extensive testing, I can confirm this was not a mod bug, but in fact an issue on the server I was connected.

Further details:
 - The bug was repeatable using EMI as the quickcraft tool
 - The bug happened even when Collective was not loaded.

**Comment by ricksouth** [comment]
Thank you for confirming! Happy it's not Collective, but hope you will manage to fix the connectivity issues. Appreciate you giving some of the mods a try :)
