### ISSUE TITLE
1.12.2 version?

### ISSUE THREAD

**Issue by dyslixic4859** [ricksouth/serilum-mc-mods#2395]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.12.2
Modloader: Forge
Forge version: 14.23.5.2860
Environment: Singleplayer

Mod name: Giant Spawn

## **Question**
Will a 1.12.2 version be available?

**Comment by ricksouth** [comment]
No unfortunately I no longer support 1.12.2. But thank you for the interest!
