### ISSUE TITLE
Double Doors not working currectly on 1.12.2

### ISSUE THREAD

**Issue by RobinRMC** [ricksouth/serilum-mc-mods#2396]
## **Information**
Minecraft version: 1.12.2
Modloader: Forge
Forge version: 14.23.5.2855
Environment: Multiplayer
Server software: CatServer (git-CatServer-1.12.2-4837c74)

Mod name: Double Doors
Mod version: 2.5

## **Description**
Double Doors function properly when placed, but stop working after a server restart.

## **Crash report**
_No._

**Comment by ricksouth** [comment]
Unfortunately I no longer support 1.12.2, apologies for the inconvenience.

**Comment by RobinRMC** [comment]
Bruh :(
