### ISSUE TITLE
Kit not given

### ISSUE THREAD

**Issue by ItzLucaGER** [ricksouth/serilum-mc-mods#2398]
## **Information**
Minecraft version: 1.20.1
Modloader:  Fabric
Fabric loader version: 0.15.11
Environment: Singleplayer / Multiplayer

Mod name: starter kit
Mod version: 6.7

## **Description**
Added starter kit mod to my modded server (client doesn't have it). Added a kit with orb of origins from the origins mod, strange potion from levelz mod and 2 patchouli books. I then deleted my playerdata from the server and joined so it thinks Im a new player. I am not getting a kit and when I try to use the command it says I am not eligible for a kit

**Comment by ricksouth** [comment]
The mod doesn't use the playerdata, but has its own file in the world folder. You can use the commands to reset a player's kit data. See the description for the exact command

**Comment by ItzLucaGER** [comment]
Oh my god. Lemme try that :D

**Comment by ItzLucaGER** [comment]
Command worked, I saw that I got the items and then the game (not server) crashed. 
[crash-2024-05-30_00.11.51-client.txt](https://github.com/Serilum/.issue-tracker/files/15491331/crash-2024-05-30_00.11.51-client.txt)

**Comment by ItzLucaGER** [comment]
I think it might be due to the LightOverlay mod?

**Comment by ricksouth** [comment]
That's very strange, I don't see anything related to Starter Kit. But REI is mentioned: `java.lang.ClassCastException: class me.shedaniel.rei.api.client.entry.renderer.EntryRendererRegistry$1 cannot be cast to class me.shedaniel.rei.api.client.entry.renderer.BatchedEntryRenderer`

**Comment by ricksouth** [comment]
Which command did you use?

**Comment by ItzLucaGER** [comment]
I used the command /starterkit reset and then rejoined

**Comment by ricksouth** [comment]
Are you using the choice GUI or just setting the kit?

**Comment by ItzLucaGER** [comment]
No GUI, for that the client needs the mod if I read it correctly?

**Comment by ricksouth** [comment]
Ah yes that's correct. Could you see if it works without Roughly Enough Items? I don't see any mention of Starter Kit causing it, but it might be an incompatibility

**Comment by ItzLucaGER** [comment]
I just tried it two more times without changing anything and it just.. didn't crash this time?

**Comment by ItzLucaGER** [comment]
I don't know what happened but it just seems to work fine now? Im so confused, sorry if Im annoying with this

**Comment by ricksouth** [comment]
Might be something unrelated. It mentions the rendering, but with Starter Kit not on the client that shouldn't be able to trigger it either way.

No worries. Glad the command works and hopefully that answers your question :)

**Comment by ItzLucaGER** [comment]
Oh well, guess I was just unlucky, the server did show this in the log when I crashed but I doubt that thats useful
![image](https://github.com/Serilum/.issue-tracker/assets/114831048/95dae14e-cae4-4af6-a592-5b51432fe073)


Thanks for the help :)

**Comment by ricksouth** [comment]
Might be worth it to open an issue on REI's issue tracker with that crash log

**Comment by ItzLucaGER** [comment]
I'll do that

**Comment by ricksouth** [comment]
> Oh well, guess I was just unlucky, the server did show this in the log when I crashed but I doubt that thats useful ![image](https://private-user-images.githubusercontent.com/114831048/334982825-95dae14e-cae4-4af6-a592-5b51432fe073.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwMjE5MDgsIm5iZiI6MTcxNzAyMTYwOCwicGF0aCI6Ii8xMTQ4MzEwNDgvMzM0OTgyODI1LTk1ZGFlMTRlLWNhZTQtNGFmNi1hNTkyLTViNTE0MzJmZTA3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOVQyMjI2NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYTAyOTBlOTNkYWUwY2EyYmVlMmEwMTUxMmQzM2Y1YzY4MDM3ZmQzMWVhNzY4YTMxODg2ODViYjExZTE0YjAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1gcR6kt3UVIKLts9mVVevSZqJCbK4uZEWpW20bd39jw)
> 
> Thanks for the help :)

Yep also not seeing anything useful in there unfortunately.

Glad it's working now 👍
