### ISSUE TITLE
[Difficulty Lock] Backporting Hardcore locking to 1.12.2

### ISSUE THREAD

**Issue by Tanker1238** [ricksouth/serilum-mc-mods#2405]
## **Information**
Minecraft version: 1.12.2
Modloader: Forge

Mod name: Difficulty Lock

## **Feature description**
I was wondering if the "forceHardcoreMode" config option could be backported to 1.12.2? Would be nice for a modpack dev such as myself, who want to force players to use hardcode mode.

**Comment by ricksouth** [comment]
Unfortunately I no longer support 1.12.2, apologies for the inconvenience.
