### ISSUE TITLE
Allow Command Blocks to use Starterkit Commands

### ISSUE THREAD

**Issue by JaklMUSIC** [ricksouth/serilum-mc-mods#2406]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge / Fabric

Mod name: Starterkits

## **Feature description**
I'm trying to setup a system that rewards players for completing various challenges with starterkits, and automate the entire process with command blocks. SK commands have a higher permission level than that of command blocks, so I cannot achieve this. Is there a 4 that I can change into a 2 somewhere, or would this feature need to be implemented as a "**allow command block SK usage=true**" config option?

Thanks for your time.

**Comment by ricksouth** [comment]
![image](https://github.com/Serilum/.issue-tracker/assets/38502394/81c62f1a-b86e-4c31-9303-9a2f4dd6b281)

StarterKit already checks for permission level 2, so this should be possible. Is that not the case?

**Comment by JaklMUSIC** [comment]
No sir, in my testing I could not get a command block to give starter kits.
A command that works in text & console  doesn't work in the command block.
I do have command blocks enabled, and the server properties permission
level is unmodified (if that matters).

**Comment by James103** [comment]
What do you get when you run the starter kit command inside a command block, then stand on top of said command block and run `/data get block ~ ~-1 ~`?

**Comment by JaklMUSIC** [comment]
![command block output](https://github.com/Serilum/.issue-tracker/assets/24709197/9756e36e-349e-41be-8a7e-b2dc967f34cd)

**Comment by ricksouth** [comment]
I have found the issue, and will upload an update in the next couple of minutes. While the permission was set to 2, the commands were only working for Players.

I've also added the /sk info <kit_name> <player_> command (the <player_> part is extra). So you can show info when clicking a button:
![2024-06-25_17 32 36](https://github.com/Serilum/.issue-tracker/assets/38502394/602c34ed-656a-4d6a-95fe-3e8d7745ff5b)

Thought that might be nice as well :)

**Comment by ricksouth** [comment]
I've just uploaded version 7.0 of Starter Kit, which will allow you to use Command Blocks. I don't use them that often, so please let me know if any issues persists. Appreciate you opening the issue and giving the mod a try!

https://curseforge.com/minecraft/mc-mods/starter-kit/files
