### ISSUE TITLE
Collective: When jumping while riding a horse, it takes fall damage

### ISSUE THREAD

**Issue by alescobar99** [ricksouth/serilum-mc-mods#2410]
## **Information**
Minecraft version: 1.20.6
Modloader: Fabric
Fabric loader version: 0.15.11
Environment: Singleplayer and Multiplayer

Mod name: Collective
Mod version: 7.61

## **Description**
To replicate the issue, create a world and use the mod collective, get a horse, ride it and jump (at least three blocks heigh), then the horse takes damage for no reason

**Comment by James103** [comment]
Does this occur in a pure vanilla instance (without a mod loader install)? If so, this is a vanilla bug.

If not, does this occur with just the Fabric Loader and latest Fabric API? If so, its probably a bug in those mods.

**Comment by alescobar99** [comment]
This doesn't occur in pure vanilla, it's a bug from the collective mod, it tested it

**Comment by alescobar99** [comment]
I use other mods, i tested it with vanilla and with each mod individually. This only happens with collective. Fabric api is not the problem

**Comment by VindSole** [comment]
Can confirm. narrowed down the issue to this library,

**Comment by ricksouth** [comment]
Thank you for the research in helping find the issue. This has been fixed in version 7.62 of Collective. Apologies for the inconvenience.

https://curseforge.com/minecraft/mc-mods/collective/files
