### ISSUE TITLE
Dismounting Players Bug

### ISSUE THREAD

**Issue by Fyoncle** [ricksouth/serilum-mc-mods#2414]
## **Information**
Minecraft version: 1.20.1
Modloader: Fabric

Mod name: Dismount Entity

## **Feature description**
Other players can dismount you from your OWN horse, that is so annoying, a config definetely needed to disable this.

**Comment by ricksouth** [comment]
Thank you for opening the issue, this has been fixed in version 3.3 of Dismount Entity. I've added a config option to re-enable it.

https://curseforge.com/minecraft/mc-mods/dismount-entity/files

**Comment by Fyoncle** [comment]
> Thank you for opening the issue, this has been fixed in version 3.3 of Dismount Entity. I've added a config option to re-enable it.
> 
> https://curseforge.com/minecraft/mc-mods/dismount-entity/files

Thanks Serilum ❤️
