### ISSUE TITLE
Stuck in Full bright

### ISSUE THREAD

**Issue by Jpearson0904** [ricksouth/serilum-mc-mods#2415]
## **Information**
Minecraft version: 1.20.6
Modloader: Fabric
 Fabric loader version: 1.20.6
Environment: Singleplayer 

Mod name: Full Bright Toggle
Mod version: 4.0

## **Description**
Im stuck in full bright and if I push G it doesn't revert back to normal brightness.

**Comment by ricksouth** [comment]
I am unable to replicate this. Did a game reboot fix it?

**Comment by Jpearson0904** [comment]
> I am unable to replicate this. Did a game reboot fix it?

I forgot to edit my comment saying I managed to fix it when I went into the settings and managed to revert my brightness back to normal by changing it manually in settings. I haven't had the same issue since then so I'm not sure what made it occur. I remember just going to press G to turn it off and it didn't work.

**Comment by ricksouth** [comment]
Closing this for now then, please let me know if the issue persists again. Thank you for giving the mod a try!
