### ISSUE TITLE
Suspected Mods: All Loot Drops (alllootdrops), Minecraft (minecraft), Galosphere (galosphere), Collective (collective), Taterzens (taterzens), Fabric Lifecycle Events (v1) (fabric-lifecycle-events-v1)

### ISSUE THREAD

**Issue by zc1108aaa** [ricksouth/serilum-mc-mods#2416]
[crash-2024-06-08_00.27.33-client.txt](https://github.com/user-attachments/files/15742577/crash-2024-06-08_00.27.33-client.txt)
1
![image](https://github.com/Serilum/.issue-tracker/assets/155424398/265a08a0-54e8-4cc9-a8a2-249c202e99c3)
1
![image](https://github.com/Serilum/.issue-tracker/assets/155424398/ccc3b244-3047-41ff-97f1-e817c1a5e1a8)

**Comment by ricksouth** [comment]
This looks to be a problem with Taterzens:

`at org.samo_lego.taterzens.npc.TaterzenNPC.constructFakePlayer(TaterzenNPC.java:211)`

`java.lang.NullPointerException: Cannot invoke "com.mojang.authlib.GameProfile.getId()" because "$$0" is null`

Please open an issue on their tracker.
