### ISSUE TITLE
Removing all names?

### ISSUE THREAD

**Issue by RosivDamotil** [ricksouth/serilum-mc-mods#2419]
Minecraft version: 1.20.4
Modloader: Fabric
Environment: Multiplayer

Mod name: Villager Names

Is it possible to remove - somehow - all villager names given until now, or will they stay even when disabling the mod?

**Comment by ricksouth** [comment]
It's not possible to remove names automatically, since the mod basically gives the villagers a name tag. But I'll leave this open as a feature request to add a command for it. Appreciate the suggestion!

**Comment by taimatime** [comment]
Commenting because this is a feature I'd like as well! As someone who clumsily managed to forget to add a "," in a custom name list I'm now stuck with a buncha guys with mile long names oops. :''D (Forge, 1.20.1)

**Comment by ricksouth** [comment]
I've just uploaded version 8.0 of Villager Names which adds commands to unname, name and rename loaded villagers. I've also made sure the custom name config now splits on commas and new lines.

Thanks for the suggestion, and hope the feature doesn't come too late 😅

https://curseforge.com/minecraft/mc-mods/villager-names/files
