### ISSUE TITLE
Ore Harvester does not drop Ores

### ISSUE THREAD

**Issue by felonese** [ricksouth/serilum-mc-mods#2423]
## **Information**
Minecraft version: 1.19,2
Modloader: Forge
Forge version: 43.3.5
Environment: Multiplayer

Mod name: Ore Harvester
Mod version: 1.19.2-1.2-fabric+forge

## **Description**
I am playing a multiplayer server via Essential Mod, and my friend and I have discovered a bug whereas when using either Vanilla or modded tools (such as the Obsidian Survival Tool in the Cell (Vanilla+) mod) on Iron Ore (Though we haven't yet tested on other ores as of yet), the harvester feature causes the ores to disappear completely, not dropping the ore. We've observed so far that occasionally the ore reappears after an unknown yet short duration of time (perhaps 5 minutes or so) where is was mined. 

We're unsure so far if this is a mod conflict or a bug. I'll attach the .mrpack for the modpack (we're using Modrinth) we've been using as well as a .txt document of all the mods in case the .mrpack fails. It's worth noting we've disabled ItemPhysics Lite since we at first theorized it was flinging due to the physics, however that was proven not to be the case shortly after.

Please let me know if there is any logs or files I could attach here to make things easier. It's not producing a CTD or anything like that so I didn't think there would be any sort of logs or console stuff to attach. Thanks!

https://drive.google.com/file/d/1BlyTqjLrsyHGYBP8p1J3YFA9Z04_ZanK/view?usp=sharing (Modpack)
[Modlist Backup.txt](https://github.com/user-attachments/files/15778736/Modlist.Backup.txt)

**Comment by ricksouth** [comment]
This looks to me like a bug with Essential, which can have strange incompatibilities with mods due to how they set up a server. It's not something I can fix on my end. Please let me know if the issue persists without Essential
