### ISSUE TITLE
All Loot Drops Incompatibility with Friends and Foes

### ISSUE THREAD

**Issue by Sonifluous** [ricksouth/serilum-mc-mods#2425]
## **Information**
Minecraft version: 1.20.1
Modloader: Forge
Forge version: 47.3.0
Environment: Singleplayer

First mod name: Friends and Foes (plus addons)
First mod version: 2.0.10

Second mod name: All Loot Drops
Second mod version: 3.3

## **Description**
Riiiiiick I found another one! Latest log included, poke me if ya want more logs! Skip to 34844 to see the beginning of the mess :3

## **Crash report**
[2024-06-11-1.log](https://github.com/user-attachments/files/15794229/2024-06-11-1.log)

**Comment by ricksouth** [comment]
Thanks for opening the issue Moo, this has been fixed in version 7.84 of Collective. Apologies it took so long to get to.

https://curseforge.com/minecraft/mc-mods/collective/files
