### ISSUE TITLE
Crash on 1.21

### ISSUE THREAD

**Issue by Avakining** [ricksouth/serilum-mc-mods#2428]
## **Information**
Minecraft version: 1.21
Modloader: Fabric
Fabric loader version: 0.15.11
Environment: Singleplayer / Multiplayer

Mod name: Collective
Mod version: 7.61

## **Description**
Currently, the game crashes while loading on 1.21.
No pressure to update immediately, I'm making this issue more as a tracker to say "this isn't done yet"

## **Crash report**

[crash-2024-06-13_13.25.27-client.txt](https://github.com/user-attachments/files/15826286/crash-2024-06-13_13.25.27-client.txt)

**Comment by ricksouth** [comment]
All mods have been updated to Minecraft version 1.21. Appreciate your enthusiasm ;)
