### ISSUE TITLE
Fabric Server fails to start on version 4.4

### ISSUE THREAD

**Issue by br3tt5952** [ricksouth/serilum-mc-mods#2429]
## **Information**
Minecraft version: 1.21
Modloader: Fabric
Fabric loader version: 0.15.11
Environment: Multiplayer

Mod name: Your Items Are Safe
Mod version: 4.4

## **Description**
Server fails to load with mod installed. Dependencies load fine.

## **Crash report**
https://gist.github.com/br3tt5952/d6f3e4248781c8798c1c44eef5e27010

**Comment by ricksouth** [comment]
You'll need Collective and Fabric API:

https://legacy.curseforge.com/minecraft/mc-mods/collective
https://legacy.curseforge.com/minecraft/mc-mods/fabric-api

**Comment by br3tt5952** [comment]
Both Collective version 7.61 & Fabric API 0.100.1 are installed.

**Comment by ricksouth** [comment]
Not according to the log 🤔

`Mod 'Your Items Are Safe' (youritemsaresafe) 4.4 requires any version of fabric, which is missing!`
`Mod 'Your Items Are Safe' (youritemsaresafe) 4.4 requires version 7.61 or later of collective, which is missing!`

**Comment by br3tt5952** [comment]
My apologies, my ftp client only uploaded .fileparts instead of the .jar

**Comment by ricksouth** [comment]
Ah no problem. :) Is it working correctly now?

**Comment by br3tt5952** [comment]
It is, thank you for the quick replies!
