### ISSUE TITLE
Ore Harvester bug

### ISSUE THREAD

**Issue by FetidEnma** [ricksouth/serilum-mc-mods#2430]
## **Information**
Minecraft version: 1.21
Modloader: CurseForge
Forge version: 51.0.1 
Environment: Singleplayer / Multiplayer

Mod name: Ore Harvester
Mod version: 

## **Description**
When you crouch mine iron ore with a 'stone' pickaxe. The iron ore is destroyed.

**Comment by ricksouth** [comment]
Do you have any other mods installed? Essentials?

**Comment by ricksouth** [comment]
I can't seem to reproduce it. Can you see if it still happens with just Collective and Ore Harvester?

**Comment by FetidEnma** [comment]
I retested with just the two, was fine. Starting adding one mod back at a time. It seems the conflict was with a different mod that ended up getting updated so I believe the issue is resolved. I use mostly your mods. I love what you make man, keep up the good work.

Yahoo Mail: Search, Organize, Conquer 
 
  On Fri, Jun 14, 2024 at 3:10 PM, Rick ***@***.***> wrote:   


I can't seem to reproduce it. Can you see if it still happens with just Collective and Ore Harvester?
