### ISSUE TITLE
Infinite trading crashing game

### ISSUE THREAD

**Issue by Flowroll94** [ricksouth/serilum-mc-mods#2433]
## **Information**
Minecraft version: 1.21
Modloader:  Fabric
Forge version: xx.xx.xx  OR  Fabric loader version: 1.21
Environment: Singleplayer 

Mod name: Infinite Trading
Mod version: 1.21

## **Description**
While infinite trading is in my mod list if I attempt to open villager trades my game crashes

## **Crash report**
[crash-2024-06-14_11.24.54-client.txt](https://github.com/user-attachments/files/15840401/crash-2024-06-14_11.24.54-client.txt)

If available.

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 4.4 of Infinite Trading.

https://curseforge.com/minecraft/mc-mods/infinite-trading/files
