### ISSUE TITLE
MERGING

### ISSUE THREAD

**Issue by dwnsdp** [ricksouth/serilum-mc-mods#2436]
Hi. Just wondering if there would be any chance of merging mods or allowing me to do so. I am imagining all of your amazing tiny tweaks as one master mod with a hefty conifg like quark or supplementaries. No worries if not, just an idea I had.

**Comment by ricksouth** [comment]
I've tried this before, but it was very difficult to keep up-to-date and compatible within one mod. I know some people prefer this, and I'll probably attempt it again in the future. Thanks for the suggestion
