### ISSUE TITLE
Ore Harvester Veins of 2 Block not mining

### ISSUE THREAD

**Issue by HelixOW** [ricksouth/serilum-mc-mods#2437]
## **Information**
Minecraft version: 1.21
Modloader: Fabric
Fabric API version: 0.100.1 + 1.21
Environment: Multiplayer

Mod name: Ore Harvester
Mod version: 1.2

## **Description**
Mining Veins of 2 Block tall ores don't yield any result. Blocks get destroyed, but items aren't dropped

**Comment by ricksouth** [comment]
I believe this was because the drop would go into the block above, which has been fixed in version 1.3 of Ore Harvester. Thanks for opening the issue and giving the mod a try!

https://curseforge.com/minecraft/mc-mods/ore-harvester/files
