### ISSUE TITLE
CreateMod & WhatDurability item incompatibility

### ISSUE THREAD

**Issue by AmeliaIsAwake** [ricksouth/serilum-mc-mods#2441]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge 
Forge version:  
Environment: Singleplayer / Multiplayer

First mod name: Create
First mod version: 0.5.1.f

Second mod name: What Durability?
Second mod version: 1.0

## **Description**
Currently, using Super Glue (a function which reduces the durability of a given item by the quantity of blocks altered [glued]) does not work, as Create mod believes the Super Glue "does not have enough durability" to function properly, even with an undamaged Superglue. 

![2024-06-17_16 49 58](https://github.com/Serilum/.issue-tracker/assets/72473660/15b178e9-e2be-456b-b7e6-23af139b4323)

## **Crash report**
No Crash.

**Comment by GarnetAnimations** [comment]
This also effects sand paper in a deployer at least in in 1.20.1 where the item is destroyed, though this bug is also present in 1.201 as well

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 1.3 of What Durability. Appreciate it.

https://curseforge.com/minecraft/mc-mods/what-durability/files
