### ISSUE TITLE
New Players Client Crashes when joining due to StarterKit

### ISSUE THREAD

**Issue by 704Prod** [ricksouth/serilum-mc-mods#2442]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge
Forge version: 43.3.5
Environment: Multiplayer (Server)

Mod name: Starterkit
Mod version: starterkit-1.19.2-6.7.jar

## **Description**
Any time a new player joins the server, they're kicked out whenever multiple kits are enabled

## **Crash report**
**Latest Log:** https://gist.github.com/704Prod/0d8709677274cee360bf7de4e193fc00
**Crash Report:** https://gist.github.com/704Prod/8d85fae47045b049548030f7624821b5

Deactivating kits allowed the player to immediately join with no crashes.

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 6.9 of Starter Kit.

https://www.curseforge.com/minecraft/mc-mods/starter-kit/files
