### ISSUE TITLE
Recipe Doesn't show up or even work

### ISSUE THREAD

**Issue by Vojta2311** [ricksouth/serilum-mc-mods#2443]
Minecraft version: 1.21
Modloader: Fabric
Fabric loader version: 0.15.11
Environment: Singleplayer

Mod name: Paper Books
Mod version: 3.3

## **Description**
I Tried the recipe for crafting books out of paper and it doesn't show up in JEI and i can't even craft it.

**Comment by ricksouth** [comment]
Thank you for opening the issue. This has been fixed in version 3.4 of Paper Books.

https://curseforge.com/minecraft/mc-mods/paper-books/files
