### ISSUE TITLE
Enchanted pickaxe drop blocks

### ISSUE THREAD

**Issue by JulienLhui** [ricksouth/serilum-mc-mods#2444]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.21
Modloader:  Fabric
Forge version: xx.xx.xx  OR  Fabric loader version: 0.15.11
Environment: Singleplayer

Mod name: Ore Harvester
Mod version: 1.2

## **Comment**
Hi! 
I don't know why but enchanted pickaxe without the Silk Touch effect have this effect... That means, a pickaxe with Fortune 3 doesn't work with ores... 

Here is my modpack curseforge link: 
[Decouverte_1.21.zip](https://github.com/user-attachments/files/15891655/Decouverte_1.21.zip)

Let me know when it's okay 
Thanks :) 
Julien

**Comment by JulienLhui** [comment]
Ok I removing the mod is not this mod, I found it, it's another mod :) 
Sorry for the ticket,
Julien

**Comment by ricksouth** [comment]
Glad you figured out the issue. Thanks for giving the mod a try!
