### ISSUE TITLE
[Difficulty Lock] Hardcore backport for 1.19.2?

### ISSUE THREAD

**Issue by CDRAGONN44** [ricksouth/serilum-mc-mods#2445]
## **Information**
Minecraft version: 1.19.2
Modloader: Forge

Mod name: Difficulty Lock

## **Question**
I was wondering if you will backport the hardcore option to 1.19.2?

**Comment by ricksouth** [comment]
Appreciate the interest, but I won't unfortunately. Lots was changed in 1.20 related to the in-game menu and buttons, and it required a complete rewrite. Apologies for the inconvenience.
