### ISSUE TITLE
Tools with enchantments that cant be on the same tool cant be combined in an anvil

### ISSUE THREAD

**Issue by Willio2000** [ricksouth/serilum-mc-mods#2447]
## **Information**
Minecraft version: 1.20.4
Modloader: Quilt
Quilt loader version: 0.26.1-beta
Environment: Singleplayer
Mod name: What Durability?
Mod version: 1.0

## **Description**
Lets say for example you have a sword with sharpness and another sword with smite and looting, you would usually be able to combine them, but with the mod installed you cant, hope this gets fixed, but for now im gonna have to disable the mod, combine my items, and then enable it again (edit: nvm i found another mod that does the exact same thing)

## **Gif**
![BaseProfile2024 06 19-22 40 07 01-ezgif com-video-to-gif-converter](https://github.com/Serilum/.issue-tracker/assets/65547044/a38a8dcb-c50b-48aa-a8cc-bb0812c256b1)

**Comment by mandie722** [comment]
Having the same issue. With this mod installed, we can no longer combine enchants with an anvil.
Minecraft: 1.21
Forge: 51.0.24
What Durability: 1.1

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 1.3 of What Durability. Appreciate it.

https://curseforge.com/minecraft/mc-mods/what-durability/files
