### ISSUE TITLE
Latest update breaks blocks

### ISSUE THREAD

**Issue by Neekodesu** [ricksouth/serilum-mc-mods#2449]
## **Information**
Minecraft version: 1.20.1
Modloader: Fabric
Fabric loader version: latest
Environment: Singleplayer / Multiplayer

Mod name: Creative
Mod version: 1.20.1-7.62

## **Description**
After updating tons of blocks were bugged, receiving a water block instead of idk, tree leaves for example. Also i could see mini creepers and stuff inside a water block all around the map.

## **Crash report**
_(Please either drag the file directly here, or use https://gist.github.com/ to prevent the paste from expiring)_

If available.

**Comment by Neekodesu** [comment]
Nevermind it wasn't Collective

**Comment by ricksouth** [comment]
Glad you figured out the issue, thanks for giving the mods a try :)
