### ISSUE TITLE
Does not work with modded trees in skyfactory 4

### ISSUE THREAD

**Issue by JCNicholsLOL** [ricksouth/serilum-mc-mods#2450]
## **Information**
Minecraft version: 1.12.2
Modloader: Forge
Environment: Singleplayer

Mod name: Tree Harvester
Mod version: 1.12-1.0

Does not work with the modded trees in skyfactory 4

**Comment by ricksouth** [comment]
I'm no longer support Minecraft version 1.12.2, apologies for the inconvenience.
