### ISSUE TITLE
Inclusion of Letter in Radius Results in Perpetual Crashing

### ISSUE THREAD

**Issue by maxhightower** [ricksouth/serilum-mc-mods#2453]
## **Information**
Minecraft version: 1.20.1
Modloader: Forge
Forge version: 46.2.20
Environment: Multiplayer

Mod name: Areas
Mod version: 5.6

## **Description**
Accidentally typed the letter "d" after the 120 radius resulting in the game crashing with the error 

The game crashed whilst unexpected error
Error: java.lang.NumberFormatException: For input string: "120d"

And I can't access the area to fix it because getting within the radius causes the crash.

## **Crash report**

[crash-2024-06-22_16.01.32-client.txt](https://github.com/user-attachments/files/15938308/crash-2024-06-22_16.01.32-client.txt)

**Comment by ricksouth** [comment]
Give me a few minutes and I'll push out a fix, apologies for the inconvenience.

**Comment by ricksouth** [comment]
I've just pushed version 5.9 of Areas which fixes the problem. Thanks for opening the issue!

https://curseforge.com/minecraft/mc-mods/areas/files
