### ISSUE TITLE
Ore Harvest Not Dropping in Correct Spot

### ISSUE THREAD

**Issue by MrPineapplez** [ricksouth/serilum-mc-mods#2454]
## **Information**
Minecraft version: 1.21
Modloader: Fabric
Fabric loader version: 0.15.11
Environment: Multiplayer

Mod name: Ore Harvester
Mod version: x.x

## **Description**
When mining a vein of multiple ores, the items dropped do not land at the original block mined. Instead, it gets thrown somewhere random or inside of a block.

**Comment by PoeticRainbow** [comment]
Having this same issue. Dropped items clip into the blocks next to or above the ore vein which makes them slowly climb up to the next air block, making them inaccessible. Most often happens with ore veins on the ceilings of caves. Using Ore Harvester 1.2 on 1.20.1.

**Comment by ricksouth** [comment]
This has been fixed in version 1.3 of Ore Harvester. I'm spawning the items in the middle of the block and removing their velocity. Please let me know if the problem persists. Thanks for opening the issue and giving the mod a try!

https://curseforge.com/minecraft/mc-mods/ore-harvester/files
