### ISSUE TITLE
Beautified Chat [Server] messages are not logged to console

### ISSUE THREAD

**Issue by MissPotato** [ricksouth/serilum-mc-mods#2461]
## **Information**
Minecraft version: 1.21
Modloader: Fabric
Forge version: xx.xx.xx  OR  Fabric loader version: x.xx.x
Environment: Multiplayer

Mod name: Beautified Chat [Server]
Mod version: 1.21.0-2.4

## **Description**
Messages sent to the server with this mod installed do not display in console or latest.log. 

## **Crash report**
_(Please either drag the file directly here, or use https://gist.github.com/ to prevent the paste from expiring)_
[latest.log](https://github.com/user-attachments/files/15960498/latest.log)

If available.

**Comment by MissPotato** [comment]
I did not mean to post this yet, so sorry for the double comment. Attached is a log in which I logged into the server, said "test" and then disconnected. As you can see, the test message did not appear.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 2.5 of Beautified Chat Server.

https://curseforge.com/minecraft/mc-mods/beautified-chat-server/files
