### ISSUE TITLE
1.21 Neoforge Crash - 

### ISSUE THREAD

**Issue by MokahTGS** [ricksouth/serilum-mc-mods#2463]
## **Information**
Minecraft version: 1.21
Modloader: Neoforge
21.0.37
Environment: Singleplayer

Mod name: Passive Shield, Pumpkillerger, Boatbreaker Fix

## **Description**
Client Crash

## **Crash report**
https://pastebin.com/mALdDxd6

**Comment by ricksouth** [comment]
Working on a fix right now actually :D Should be done in about 30 minutes

**Comment by ricksouth** [comment]
I've just pushed an update for all mods that needed one. Updating should add compatibility for the latest NeoForge update. Thanks for giving the mods a try!
