### ISSUE TITLE
/the-vanilla-experience/1.21/7.15 Less mods

### ISSUE THREAD

**Issue by zc1108aaa** [ricksouth/serilum-mc-mods#2465]
no fullbrightnesstoggle-
no randommobeffects-
no placeableblazerods-
no configurableextramobdrops-
no biomespawnpoint-
no hiddenrecipebook-

**Comment by ricksouth** [comment]
fullbrightnesstoggle - feels to cheaty. If people need it for accessibility, they can add it manually.
randommobeffects - Don't feel like it fits in the vanilla feel
placeableblazerods - Adds a new block, so it's not compatible with vanilla saves
configurableextramobdrops - Don't need it, as it's not configured
biomespawnpoint - Also don't need it, we have village spawn point
hiddenrecipebook - I prefer to have the book shown personally.

But appreciate the suggestions
