### ISSUE TITLE
[1.21] Library Crash on load - Version typo

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [ricksouth/serilum-mc-mods#2468]
## **Information**
Minecraft version: 1.21
Modloader: NeoForge
NeoForge version: 21.0.40-beta
Environment: Yes

Mod name: Collective
Mod version: 7.65 / Dev- Current codebase

## **Description**
Mod crashes on load due to type in the mods.toml which should be 
"21.0.40-beta" instead of "21.0.40"

## **Crash report**
https://mclo.gs/pxhAeFK

**Comment by ricksouth** [comment]
Oops! Thanks for letting me know, I've just uploaded Collective version 7.66 which has the version range set correctly.

https://curseforge.com/minecraft/mc-mods/collective/files
