### ISSUE TITLE
Passive Endermen causes more griefing

### ISSUE THREAD

**Issue by A5ho9999** [ricksouth/serilum-mc-mods#2469]
## **Information**
Minecraft version: 1.21
Modloader: Fabric
Fabric loader version: 0.15.11
Environment: Singleplayer / Multiplayer

Mod name: Passive Endermen
Mod version: 1.21.0-4.6-fabric+forge+neo

## **Description**
Tags weren't updated, Enderman pick up blocks and they get deleted.

`tags/blocks` -> `tags/block`

**Comment by ricksouth** [comment]
Thank you for opening the issue. I've just uploaded version 4.7 of Passive Endermen with the fix. Appreciate it.

https://modrinth.com/mod/passive-endermen
