### ISSUE TITLE
[QUESTION] Will Player Death Kick auto kick an player when disconnects from server due to internet loss or leaves the game?

### ISSUE THREAD

**Issue by md500** [ricksouth/serilum-mc-mods#2478]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.20.1
Modloader: Forge / Fabric
Fabric loader version: 0.15.11
Environment: Singleplayer / Multiplayer

Mod name: Player Death Kick
Mod version: 1.20.1-3.2-fabric+forge+neo

## **Question**
Will this mod kick user when disconnects due to lag? I'm using EasyAuth (I know that mod is not yours, so i reported the issue to NikitaCartes) to let users to log, but when disconnects when player loses internet, it says "User leave the game" in log, and when connects, it says "user is already online".

Will this mod work for this issue?
![photo_2024-07-01_09-41-00](https://github.com/Serilum/.issue-tracker/assets/3111925/436d77a8-5213-4a72-8cd2-2ed6f9ba7db9)

Here's the log: https://mclo.gs/ouJrZl3

**Comment by ricksouth** [comment]
No I don't think the mod will help with your issue. Unless you somehow kill the lagging players with a command block. But thanks for the interest!
