### ISSUE TITLE
[Bug] House Breaking

### ISSUE THREAD

**Issue by Fyoncle** [ricksouth/serilum-mc-mods#2479]
## **Information**
Minecraft version: 1.20.1
Modloader: Forge / Fabric
Fabric version: 0.15.11
Environment: Both Happens

Mod name: Tree Harvester
Mod version: 1.20.1-8.7-fabric+forge+neo

## **Description**
My... my house got broken because of Tree Harvester's weird wood detection
![image](https://github.com/Serilum/.issue-tracker/assets/63975256/02328ecd-8853-426a-a22a-58ffc3bc97f9)
All the logs in the floor now...

## **Crash report**
No crashes

If available.

**Comment by Fyoncle** [comment]
Also you can destroy the WHOLE ChoiceTheorem's Villages by just using tree harvester, and for faster breaking houses, using https://github.com/Serilum/.issue-tracker/issues/2126

**Comment by ricksouth** [comment]
How did you create your house? It shouldn't do this as there are checks in place to prevent it

**Comment by Fyoncle** [comment]
> How did you create your house? It shouldn't do this as there are checks in place to prevent it

With my hand, i literally just placed wood casually in survival.

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 9.1 of Tree Harvester. Appreciate it.

https://curseforge.com/minecraft/mc-mods/tree-harvester/files
