### ISSUE TITLE
Wither skeleton mod won't work

### ISSUE THREAD

**Issue by ARandomGamer5** [ricksouth/serilum-mc-mods#2481]
Minecraft version: 1.21
Modloader: Fabric
Fabric loader version:1.21
Environment: Singleplayer

Mod name: Always A Wither Skull
Mod version: 1.21.0-3.3

## **Description**
when i try to kill wither skeletons they dont drop their head

**Comment by ricksouth** [comment]
The mod has been rewritten in version 3.4, which fixes any compatibility issues with other mods. Thank you for opening the issue and giving the mod a try!

https://curseforge.com/minecraft/mc-mods/always-a-wither-skull/files
