### ISSUE TITLE
Bigger Sponge Absorption Radius | Can you make this work client side? It's not working client side in 1.21 Fabric

### ISSUE THREAD

**Issue by ChimeraGaming** [ricksouth/serilum-mc-mods#2484]
## **Information**
Minecraft version: 1.21
Modloader: Fabric

Mod name: Bigger Sponge Absorption Radius

## **Feature description**
Can you make it work client side Thanks

**Comment by ricksouth** [comment]
Since it manipulates block data that is done on the server, this is impossible to do. But thank you for the interest.
