### ISSUE TITLE
Crash When Pumpkillager Summoned

### ISSUE THREAD

**Issue by ElfNoir88100** [ricksouth/serilum-mc-mods#2485]
## **Information**
Minecraft version: 1.21
Modloader: Fabric
Fabric loader version: 0.15.11
Environment: Singleplayer

Mod name: Mod Pumpkillager's Quest
Mod version: 4.2

## **Description**
When I try to complete the ritual to summon the Pumpkillager (for the boss fight) and also during the dialogue with the Prisoner, the game closes as if it were a server even if I'm playing solo. Because of this, I can't complete the quest...

![Capture d'écran 2024-07-03 134948](https://github.com/Serilum/.issue-tracker/assets/174611834/642bcfdc-f725-4656-8a41-c8a0e972c43f)

**Comment by ricksouth** [comment]
Thank you for opening the issue, and giving the mod a try! This has been fixed in version 4.3 of Pumpkillager's Quest. Apologies for the inconvenience.

https://www.curseforge.com/minecraft/mc-mods/pumpkillagers-quest/files
