### ISSUE TITLE
Always a Wither Skull not working

### ISSUE THREAD

**Issue by runcidavid** [ricksouth/serilum-mc-mods#2487]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.21
Modloader: Fabric
Fabric loader version: 0.15.11
Environment: Multiplayer

Mod name: Always a Wither Skull
Mod version: 3.3

## **Question**

Do i need to turn on an option to be able to get the head on every drop because i have killed a lot of withers and none dropped their head?

Thank you!

**Comment by ricksouth** [comment]
The mod has been rewritten in version 3.4, which fixes any compatibility issues with other mods. Thank you for opening the issue and giving the mod a try!

https://curseforge.com/minecraft/mc-mods/always-a-wither-skull/files
