### ISSUE TITLE
[1.16.5] The profession of villagers cannot be translated

### ISSUE THREAD

**Issue by GoldenTotem** [ricksouth/serilum-mc-mods#2488]
## **Information**
Minecraft version: 1.16.5
Modloader: Forge
Forge version: 36.2.35
Environment: Singleplayer

Mod name: Villager Names
Mod version: 4.3

## **Description**
Mod villager names add the profession of a villager after its name. But the profession cannot not be translated and always be english.
![PixPin_2024-07-04_01-55-17](https://github.com/Serilum/.issue-tracker/assets/70516358/3c00de24-942f-4c83-b2c1-bd15ac8ade9f)

It should be  "name" + "-" + "entity.minecraft.villager.butcher" + "-" + "merchant.level.1"

**Comment by ricksouth** [comment]
This has been fixed in later versions, but unfortunately after I dropped support for 1.16.5. Apologies for the inconvenience.
