### ISSUE TITLE
We need Full Brightness Toggle Mod for 1.12.2 Forge!

### ISSUE THREAD

**Issue by lowkeyrenato** [ricksouth/serilum-mc-mods#2498]
## **Information**
Minecraft version: 1.12.2
Modloader: Forge 

Mod name: Full Brightness Toggle Mod

## **Feature description**
It would be nice if this mod were available for Forge 1.12.2 because there is currently no such mod for this version, and the Optifine solution with a texture pack is not a solution for everyone.

**Comment by ricksouth** [comment]
I won't be porting the mod to 1.12, but I think this should work: https://curseforge.com/minecraft/mc-mods/fullbright
