### ISSUE TITLE
Ore Discovery Broadcast not working even though I have both mods 

### ISSUE THREAD

**Issue by Ereshkigal101** [ricksouth/serilum-mc-mods#2505]
## **Information**
Minecraft version: xx.xx.xx
Modloader: Forge / Fabric
Forge version: xx.xx.xx  OR  Fabric loader version: x.xx.x
Environment: Singleplayer / Multiplayer

Mod name: Mod
Mod version: x.x

## **Description**
Hey! This happened.

## **Crash report**
_(Please either drag the file directly here, or use https://gist.github.com/ to prevent the paste from expiring)_

If available.

**Comment by ricksouth** [comment]
Make sure to check the config whether "only on dedicated server" is disabled if you're not in one. Let me know if the issue persists.
