### ISSUE TITLE
Ore Discovery Broadcast not working even though I have both mods (the mod itself and the dependency mod)

### ISSUE THREAD

**Issue by Ereshkigal101** [ricksouth/serilum-mc-mods#2506]
## **Information**
Minecraft version: 1.21
Modloader: Fabric
Fabric loader version: 0.15.11
Environment: Multiplayer / Server

Mod name: Ore Discovery Broadcast
Mod version: 1.21.0-2.1

## **Description**
Simply putting it, both mods are installed (independent mod and dependency) and it's not announcing ore that I have whitelisted.

**Comment by Ereshkigal101** [comment]
![image](https://github.com/Serilum/.issue-tracker/assets/66820531/f2ed5c7c-3b15-4899-afc4-86a6be5efdf2)
![opera_ybqM6AwXeQ](https://github.com/Serilum/.issue-tracker/assets/66820531/3e2070d9-7eb7-447a-b3ad-7d2b6898bda1)
![opera_pOlE97glnC](https://github.com/Serilum/.issue-tracker/assets/66820531/db722026-cf05-4478-b473-998f7ca3a4a1)
![opera_kQc1Non1dJ](https://github.com/Serilum/.issue-tracker/assets/66820531/38c5dcae-30e1-4cce-8f61-88fc8e0fc013)
![opera_lFFk8nJ6jE](https://github.com/Serilum/.issue-tracker/assets/66820531/a37e06b9-0d27-4873-ad48-90f9d6eba94c)

Here's all the mods that are currently on the server.

**Comment by ricksouth** [comment]
I see you closed it, did you solve the issue?

**Comment by Ereshkigal101** [comment]
Yeah I fixed it. I think it was cause I had put two !!’s in the blacklist
config by accident. Regardless it’s working now.
