### ISSUE TITLE
Slime Head is Pure White

### ISSUE THREAD

**Issue by TommyChristmas** [ricksouth/serilum-mc-mods#2509]
## **Information**
Minecraft version: 1.21
Modloader: Fabric
Fabric loader version: 0.15.11
Environment: Singleplayer

Mod name: Just Mob Heads
Mod version: 8.1

Description: Slime head collected upon killing Slime is stark white. Same for Slime Heads given by command.

![2024-07-10_10 58 15](https://github.com/Serilum/.issue-tracker/assets/175233273/c7dbc43b-e6bf-44bd-9f67-ba3c55fa6983)

**Comment by James103** [comment]
See also https://github.com/Serilum/.issue-tracker/issues/2466#issuecomment-2198915819.

**Comment by LyoGyo** [comment]
Here's the slime head data in case anyone needs it
![image](https://github.com/user-attachments/assets/2321303c-21a6-45a2-9e9f-1bc8147f7c99)
Weirdly enough the only people on my server having issues are the two people with Fresh Animations, no idea if that correlates with anything but it's worth mentioning

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 8.2 of Just Mob Heads.

https://curseforge.com/minecraft/mc-mods/just-mob-heads/files
