### ISSUE TITLE
Piglin Names

### ISSUE THREAD

**Issue by SuperFanatic** [ricksouth/serilum-mc-mods#2510]
Just a silly idea I had that I imagine would be easy to implement, given it's most of the Villager Names mod but on piglins.
The idea is simple: give piglins names. Their method of trading may be more crude than villagers and a chunk of their population may want you dead no matter your attire, but they definitely seem smart enough to have names. I'm thinking something more alien than the villager's names, like "Galrod" or "Quaaloth" or things like that.

**Comment by ricksouth** [comment]
Here you go! :) It uses the same names, but you can set a custom name list via the config. Thanks for the idea!

https://curseforge.com/minecraft/mc-mods/piglin-names
https://modrinth.com/mod/piglin-names
