### ISSUE TITLE
New version of Ore Harvester

### ISSUE THREAD

**Issue by Giaioneg** [ricksouth/serilum-mc-mods#2512]
Minecraft version: 1.18.2
Modloader: Forge / Fabric
Forge version: 40.2.15  OR  Fabric loader version: x.xx.x
Environment: Singleplayer / Multiplayer

Mod name: Ore Harvester
Mod version: Does not exist

Could you make the mod compatible with version 1.18.2? Please, I would appreciate it very much.

**Comment by ricksouth** [comment]
Unfortunately I no longer support 1.18. There is also no updated Collective version for it available, so I can't easily upload it. But thank you for the interest!
