### ISSUE TITLE
Fish on the Line does not work on 

### ISSUE THREAD

**Issue by strong541** [ricksouth/serilum-mc-mods#2522]
## **Information**
Minecraft version: 1.21
Modloader: Fabric
Forge version:  Fabric loader version: 0.15.11
Environment: Multiplayer

Mod name: Fish on the Line 
Mod version: 1.21.0-3.3

## **Description**
Fish on the Line does not work on the Server I am playing on but it does work in singleplayer. The server is a paper server and it is on 1.21.

## **Crash report**
No Crash Report avalible

If available.

**Comment by ricksouth** [comment]
The mod has to be installed on the server to work. I'm not familiar with Paper, but that's why it's only working in SP. Thanks for giving the mod a try!

**Comment by Terraphice** [comment]
I'm going to piggyback on this closed issue and ask why that's the case, beyond the sound effect itself being played server-side? Assuming it's possible, could we possibly see a client-side version in the future?
