### ISSUE TITLE
BUG: flower mimic continuously respawns and replaces flower on death

### ISSUE THREAD

**Issue by the-david-wang** [ricksouth/serilum-mc-mods#2523]
## **Information**
Minecraft version: 1.21
Modloader: Forge / Fabric
Fabric loader version: 0.15.11
Environment: Multiplayer

Mod name: Flower Mimic
Mod version: 1.8

## **Description**
mimic spawn was activated after server reboot on a player placed flower
Lilac flower mimic spawns with default mob of shulker - this shulker has mimic name tag. (will refer as RED)
2nd shulker spawns with it as pair - this shulker does NOT have name tag. (refer as PINK)
both shulkers teleport away on non flower placeable blocks
when killing RED it drops mimic loot and replaces flower in original position
when killing PINK it drops regular shulker loot
after about a minute both shulkers respawn
when killing ONLY RED it drops mimic loot and replaces flower in original position; respawns after a minute in the position it died
when killing ONLY PINK it drops regular shulker loot and does NOT replace flower; respawns after a minute in the position it died
if removing block where flower originally was, killing red drops flower entity at original position; respawns after a minute in the position it died

## **Crash report**
_(Please either drag the file directly here, or use https://gist.github.com/ to prevent the paste from expiring)_

If available.

**Comment by ricksouth** [comment]
Do you have Respawning Shulkers installed as well?

**Comment by the-david-wang** [comment]
> Do you have Respawning Shulkers installed as well?

i feel dumb, yeah, sorry

**Comment by ricksouth** [comment]
If you don't mind, I'll leave this open for a bit. I think Respawning Shulkers should ignore the flower mimics entirely to prevent unwanted behaviour. Thanks for letting me know :)

**Comment by ricksouth** [comment]
I've just uploaded version 3.9 of Respawning Shulkers, where it ignores shulker flower mimics. Thanks for giving both mods a try!

https://curseforge.com/minecraft/mc-mods/respawning-shulkers/files
