### ISSUE TITLE
What durability breaks create mod glue

### ISSUE THREAD

**Issue by R1CHT3AS** [ricksouth/serilum-mc-mods#2525]
What durability doesn't work with create mod glue
Minecraft version: 1.20.1
Modloader: Forge
Forge version: 47.3.0
Environment: Singleplayer and Multiplayer

First mod name: What durability
First mod version: 1.0

Second mod name: Create
Second mod version: 0.5.1

## **Description**
When attempting to use glue in combination with what durability in survival the game say you don't have enough glue in your inventory despite trying it many times with different amounts. This is likely due to glue tracking how many blocks you can stick together with durability.

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 1.3 of What Durability. Appreciate it.

https://curseforge.com/minecraft/mc-mods/what-durability/files
