### ISSUE TITLE
Alternative World Save Location question

### ISSUE THREAD

**Issue by Bukz** [ricksouth/serilum-mc-mods#2527]
## **Information**
Minecraft version: 1.21
Modloader: NeoForge
Version: 21.0.98-beta
Environment: Singleplayer

Mod name: Alternative World Save Location
Mod version: 1.21.0-3.5

## **Question**
Can this mod be used to load saves from a different drive (other than C:\) ?

**Comment by Bukz** [comment]
Also can it be used to define a custom path for newly created worlds?

**Comment by ricksouth** [comment]
Yes that should both work, thanks for giving the mod a try!
