### ISSUE TITLE
Wither Skulls not dropping in 1.21

### ISSUE THREAD

**Issue by PixelPally** [ricksouth/serilum-mc-mods#2528]
## **Information**
Minecraft version: 1.21
Modloader: Fabric
Fabric loader version: 0.15.11
Environment: Singleplayer

Mod name: Always a Wither Skull
Mod version: 1.21.0-3.3

## **Description**
This is my first time trying the mod Always A Wither Skull. I added it recently along with several other new (to me) mods from The Vanilla Experience. I had Collective for 1.21 already added as well. Today in my long-term SSP game (which I've been playing, modded, ever since Caves&Cliffs p2) I went exploring in the nether to find a fortress so that I could kill some Wither Skeletons in order to test whether this mod is working. I found a fortress, I found some Wither Skelleys, and I killed 2 of them but neither one dropped a skull. I closed the game and started looking around to see if I could figure anything out. I noticed Collective had a new update a few days ago so I updated it, then got back into my game and killed another W.S. but it also did not drop its skull. I looked in the configs folder of my minecraft installation and I see config files for many mods that I use but there isn't one for this mod. I have no more ideas, I can only assume the mod isn't working.

Here is a list of all the mods I am using:

Always a Wither Skull
AppleSkin
Collective
Crying Ghasts
Double Doors
Fabric API
Infinite Trading
Inventory Totem
Tax Free Levels
Tree Harvester
Xaero's Minimap
Xaero's World Map

And these datapacks (all from "Vanilla Tweaks"):

Anti-Creeper Grief
Anti-Ghast Grief
Cauldron Concrete
Cauldron Mud
Double Shulker Shells
Dragon Drops
Fast Leaf Decay
Glass Always Drops
...I used to also use a datapack More Mob Heads that gave every mob in game a chance to drop its head (as a decorative player head), but I deleted it about the same time I installed the aforementioned "Vanilla Experience" mods (including AAWS)

## **Crash report**
There is no crashing so there is no crash report.

**Comment by ricksouth** [comment]
The mod has been rewritten in version 3.4, which fixes any compatibility issues with other mods. Thank you for opening the issue and giving the mod a try!

https://curseforge.com/minecraft/mc-mods/always-a-wither-skull/files
