### ISSUE TITLE
Server crashes whenever I spawn and then kill the Pumpkillager

### ISSUE THREAD

**Issue by Bloons1** [ricksouth/serilum-mc-mods#2531]
## **Information**
Minecraft version: 1.21
Modloader: Forge
Forge version: 51.0.24 
Environment: Singleplayer and Multiplayer (I tried both just to test)

Mod name: Pumpkillager's Quest
Mod version: I don't know, it's the latest as of 7/19/2024

## **Description**
Whenever I summon the boss ritual (16 candles + Pumpkin). the game crashes and gives me a packet loss failure, saying, Internal Exception: io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:damage_event'
I found a way to bypass this was to use the 3 seconds of invincibility whenever you join the server, but that only works to summon him as when you leave, he disappears, so I can't get those three seconds when I kill him and the explosion happens again.

## **Crash report**
_(Please either drag the file directly here, or use https://gist.github.com/ to prevent the paste from expiring)_

If available.

**Comment by ricksouth** [comment]
Thank you for opening the issue, and giving the mod a try! This has been fixed in version 4.3 of Pumpkillager's Quest. Apologies for the inconvenience.

https://www.curseforge.com/minecraft/mc-mods/pumpkillagers-quest/files
