### ISSUE TITLE
What Durability? Anvil Problems

### ISSUE THREAD

**Issue by ghost** [ricksouth/serilum-mc-mods#2539]
## **Information**
Minecraft version: 1.20.1
Modloader: Forge
Forge version: 47.3.5
Environment: Singleplayer

Mod name: What Durability?
Mod version: 1.0

## **Description**
i was trying to combine 2 picks on an anvil with fortune II into fortune III but it wouldnt combine. i turned off the mod and it worked.

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 1.3 of What Durability. Appreciate it.

https://curseforge.com/minecraft/mc-mods/what-durability/files

**Comment by ghost** [comment]
thank you! and thank you for updating it all the way back in 1.20.1, that will very greatly improve my playthrough. thanks again! your mods are awesome!
