### ISSUE TITLE
FPS drops to 20 when holding up a shield 

### ISSUE THREAD

**Issue by Shichiha** [ricksouth/serilum-mc-mods#2543]
## **Information**
Minecraft version: 1.21
Modloader: Forge / Fabric
Forge version: Fabric loader version: 0.16.0
Environment: Singleplayer 

Mod name: Advancement Screenshot
Mod version: 4.8

## **Description**
FPS drops to 20 when holding up a shield. I get 240 FPS (on average), but the moment I hold a shield (with the mod active), it goes all the way down to 20 (stable), like, exactly 20

**Comment by ricksouth** [comment]
That's very strange. And if you remove Advancement Screenshot, this doesn't happen?

**Comment by Shichiha** [comment]
> That's very strange. And if you remove Advancement Screenshot, this doesn't happen?

yes, it doesn't happen when the mod is removed

**Comment by ricksouth** [comment]
And if you reinstall the mod, it happens again? Just making sure.

**Comment by Shichiha** [comment]
Spoke too soon, it looks like another mod was causing the issue, I just didn't consider it :v:

**Comment by ricksouth** [comment]
That was my guess, as I wouldn't understand why it would've done that. But thanks for confirming, and giving the mod a try!
