### ISSUE TITLE
Windows Defender Flagged Collective 7.78 For Minecraft 1.20.1 As Trojan:Script/Wacatac.B!ml

### ISSUE THREAD

**Issue by akharding91** [ricksouth/serilum-mc-mods#2546]
Minecraft version: 1.20.1
Mod name: Collective
Mod version: 7.78

Download & windows defender flagged the downloaded file as a Trojan:Script/Wacatac.B!ml virus. This is most likely a false positive but I'd thought I'd let you know.

File was download from the curseforge website - https://www.curseforge.com/minecraft/mc-mods/collective

**Comment by ricksouth** [comment]
Ah, this was an issue a while ago. If you follow these steps:

https://github.com/Serilum/.issue-tracker/issues/2255

Does it still falsely flag it?

**Comment by ricksouth** [comment]
An alternative is to just run the Windows Updates, that should fix it as well

**Comment by akharding91** [comment]
ah i didn't see the other post, thanks for the help.

**Comment by ricksouth** [comment]
Hopefully that fixed it. Thanks for giving some of the mods a try! :)
