### ISSUE TITLE
Unable to load with EMI

### ISSUE THREAD

**Issue by stlouisn** [ricksouth/serilum-mc-mods#2547]
## **Information**
Minecraft version: 1.21
Modloader: Fabric
Fabric loader version: 0.16.0
Environment: Singleplayer

Mod name: Collective
Mod version: 7.79

## **Description**
Since latest update to collective, game cannot load with EMI mod

**Comment by ricksouth** [comment]
Can you upload your logs?

**Comment by stlouisn** [comment]
[latest.log](https://github.com/user-attachments/files/16403115/latest.log)

**Comment by ricksouth** [comment]
Thank you for letting me know! I've archived version 7.79 and released 7.80 which reverts the changes. Apologies for the inconvenience.

https://curseforge.com/minecraft/mc-mods/collective/files
