### ISSUE TITLE
Collective 7.79 mixin crash with EMI

### ISSUE THREAD

**Issue by emneo-dev** [ricksouth/serilum-mc-mods#2548]
## **Information**
Minecraft version: 1.21
Modloader: Fabric
Fabric loader version: 0.16.0
Environment: N/A

Mod name: Collective
Mod version: 7.79

## **Description**
Collective 7.79 crashes on startup if EMI is installed, this behaviour doesn't happen with Collective 7.78

## **Crash report**
https://mclo.gs/HKf4k3V
Permanent link:
https://gist.github.com/emneo-dev/0924086e2af165ccbe906dc162b48ed5

## **Mod list**
![image](https://github.com/user-attachments/assets/cbb13c6c-acad-42b8-bf28-f76a1ba68ff4)
![image](https://github.com/user-attachments/assets/95c97bd9-f0b8-452a-b1bd-f20dc8ec03ad)

Prism Launcher instance:
[collective_emi_crash_mixin_7_79.zip](https://github.com/user-attachments/files/16403842/collective_emi_crash_mixin_7_79.zip)

**Comment by emneo-dev** [comment]
Just saw there was another issue about this exact problem.

**Comment by ricksouth** [comment]
Thank you for letting me know! I've archived version 7.79 and released 7.80 which reverts the changes. Apologies for the inconvenience.

https://curseforge.com/minecraft/mc-mods/collective/files
