### ISSUE TITLE
1.20.1 Server Startup Crash after upgrading from 7.78 to 7.79

### ISSUE THREAD

**Issue by Konclan** [ricksouth/serilum-mc-mods#2549]
## **Information**
Minecraft version: 1.20.1
Modloader: Forge
Forge version: Neoforge 47.1.106
Environment: Multiplayer

Mod name: Collective
Mod version: 7.79

## **Description**
After upgrading from 7.78 to 7.79, the server crashes on startup. The client seems unaffected and I can still load singleplayer worlds. I can launch the server if I downgrade back to 7.78

## **Crash report**
https://gist.github.com/Konclan/cf44323e105f32ab14667a03eb11264a

**Comment by brisingraerowing** [comment]
I get this exact crash in singleplayer.

**Comment by ricksouth** [comment]
Thank you for letting me know! I've archived version 7.79 and released 7.80 which reverts the changes. Apologies for the inconvenience.

https://curseforge.com/minecraft/mc-mods/collective/files
