### ISSUE TITLE
Possible crash/incompatibility with DivineRPG

### ISSUE THREAD

**Issue by D3SL** [ricksouth/serilum-mc-mods#2561]
## **Information**
Minecraft version: 1.20.1
Modloader: Forge
Forge version: 47.3.0
Environment: Singleplayer 

Mod name: All Loot Drops
Mod version: 3.4 (collective 7.80)

## **Description**
During/at the end of worldgen the game CTDs. The "duplicate id" error message and console log explicitly listing one of divinerpg's bosses strongly suggested the issue was tied to All Loot Drop's functionality. Removing it cleared the crash.

## **Crash report**
[all loot drops divinerpg ctd.txt](https://github.com/user-attachments/files/16482370/all.loot.drops.divinerpg.ctd.txt)

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 7.84 of Collective.

https://curseforge.com/minecraft/mc-mods/collective/files
