### ISSUE TITLE
Fabric 1.20.1 

### ISSUE THREAD

**Issue by SqueezeyMe** [ricksouth/serilum-mc-mods#2569]
Minecraft version: 1.20.1
Fabric loader version: 0.15.11
Environment: Singleplayer

i used essentials mod installer thing to make a server for me and my friend and this new crash happened and i dont know what it is

## **Crash report**
Uncaught exception in thread "main"Uncaught exception in thread "main"java.lang.RuntimeException: Error creating Mixin config mixins.feather.json for mod feather at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:96) at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151) at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config mixins.feather.json at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153) at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100) at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87) at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:94) ... 3 moreCaused by: java.lang.IllegalArgumentException: The requested compatibility level JAVA_21 could not be set. Level is not supported by the active JRE or ASM version (Java 17.0, ASM 9.6 (ASM10_EXPERIMENTAL)) at org.spongepowered.asm.mixin.MixinEnvironment.setCompatibilityLevel(MixinEnvironment.java:1627) at org.spongepowered.asm.mixin.transformer.MixinConfig.initCompatibilityLevel(MixinConfig.java:557) at org.spongepowered.asm.mixin.transformer.MixinConfig.postInit(MixinConfig.java:502) at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:430) at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1293) at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148) ... 6 more

**Comment by ricksouth** [comment]
This doesn't seem related to one of my mods. I see a reference to feather, but otherwise not sure
