### ISSUE TITLE
When teleporting in and out of areas with area signs, no messages pop up until I redo the signs 

### ISSUE THREAD

**Issue by Rafixtheneko** [ricksouth/serilum-mc-mods#2571]
## **Information**
Minecraft version: 1.20.4
Modloader: Fabric
Fabric loader version: 0.15.10
Environment: Singleplayer

Mod name: Areas Mod
Mod version: 5.6

## **Description**
When I walk in and out of areas, everything works correctly, however if I use wormholes or waypoints at all, the areas where I've teleported out of get perma broken. No messages pop up anymore until I destroy those signs and redo completely.

**Comment by Rafixtheneko** [comment]
Found a workaround, just make areas smaller to make sure you always exit them before teleporting. Not elegant but works

**Comment by NNowakowski** [comment]
This is still happening. Any actual fix for it? I can't even re-use the same name after destroying the sign, it just stays broken.
