### ISSUE TITLE
Did you break something? 1.21 7.80 released but says 1.21.1

### ISSUE THREAD

**Issue by Zelioth** [ricksouth/serilum-mc-mods#2572]
Minecraft 1.21
Neoforge 21.0.167
Collective 1.21.1-7.80 

Looks like you released 1.21.1 on versino 1.21 so it causes and error that requires 1.21

![image](https://github.com/user-attachments/assets/0fdbc62a-539a-41ef-b857-d5bfb138c6e3)

**Comment by ricksouth** [comment]
Thank you for letting me know! I've removed the 1.21 tag from the Collective file and removed the NeoForge 21.1 requirement for future releases. Appreciate it.
