### ISSUE TITLE
Bewitchment 1.12.2

### ISSUE THREAD

**Issue by AlaricEngel** [ricksouth/serilum-mc-mods#2574]
## **Information**
Minecraft version: xx.xx.xx
Modloader: Forge / Fabric
Forge version: xx.xx.xx  OR  Fabric loader version: x.xx.x
Environment: Singleplayer / Multiplayer

First mod name: Mod
First mod version: x.x

Second mod name: Mod
Second mod version: x.x

## **Description**
Hey! This happened.
I would like to be able to configure to allow this mod to cut down trees for Bewitchment for my 1.12.2 modpack, the same it does for every other tree it has compatibility with such as quark, etc. Thank you!

## **Crash report**
If available.

**Comment by ricksouth** [comment]
I've dropped 1.12.2 support a long time ago. Apologies for the inconvenience.

**Comment by AlaricEngel** [comment]
OH! lmao!!! No problems! I thought I was missing something obvious. Tyvm for your time <3
