### ISSUE TITLE
Crash on startup: Mixin apply failed simplemenu_forge.mixins.json:ScreenMixin

### ISSUE THREAD

**Issue by J0B10** [ricksouth/serilum-mc-mods#2576]
## **Information**
Minecraft version: `1.20.1`
Modloader: `Neoforge`
Neoforge version: `1.20.1-4.7.1.106`
Environment: `Singleplayer`

Mod name: `Simple Menu`
Mod version: `1.20.1-1.4-fabric+forge+neo`

Library name: `Collective`
Library version: `1.20.1-7.81-fabric+forge+neo`

Java version: `zulu17.48.15-ca-jre17.0.10-win_x64`

## **Description**
I can't get SimpleMenu to run. It always crashes on startup with a `Mixin apply failed`-Error (see Crashlog).  
I tried using older versions (SimpleMenu `1.20.1-1.4-fabric+forge+neo`), using an older version of Collective (`1.20.1-7.81-fabric+forge+neo`) and using Forge (version `1.20.1-47.2.17`) instead of NeoForge, but the error seems to persist. 

I conducted all the tests in a clean minecraft instance where only Collective and SimpleMenu are installed, no other mods.
The java version I used is the default version delivered with the modrinth app. 

## **Crash report**
[latest.log](https://github.com/user-attachments/files/16573829/latest.log)
No crash report was created in `crash-reports` directory.

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 1.5 of Simple Menu. Appreciate it.

https://modrinth.com/mod/simple-menu

**Comment by J0B10** [comment]
Thx for the quick fix, runs fine now! Great mod, I appreciate your work. Keep it up!
