### ISSUE TITLE
[Incompatibility]: Create

### ISSUE THREAD

**Issue by Fyoncle** [ricksouth/serilum-mc-mods#2578]
## **Information**
Minecraft version: 1.20.1
Modloader: Fabric
Fabric loader version: 0.15.11
Environment: *

First mod name: Create
First mod version: Create 1.20.1 v0.5.1.f Patch 1

Second mod name: Crying Portals???
Second mod version: 1.20.1-2.8

Third mod name: Double Doors???
Third mod version: 1.20.1-5.9

## **Description**
When i remove Crying Portals and Double Doors from my mod list, it stops crashing.
Heres the log file https://mclo.gs/bYYZOEq

Just so you know, i use Elysium Days 3.2.0 version of the modpack.

**Comment by ricksouth** [comment]
This doesn't seem related to it. I see errors from `dripstone_fluid_lib` and `advanced_runtime_resource_pack`. Did you manage to solve this?

**Comment by Fyoncle** [comment]
> This doesn't seem related to it. I see errors from `dripstone_fluid_lib` and `advanced_runtime_resource_pack`. Did you manage to solve this?

It is completely happens when your mods added, the mod standalone doesn't give any errors.

**Comment by Fyoncle** [comment]
Any news on this?

**Comment by Fyoncle** [comment]
> This doesn't seem related to it. I see errors from `dripstone_fluid_lib` and `advanced_runtime_resource_pack`. Did you manage to solve this?

![image](https://github.com/user-attachments/assets/26b66ca5-036f-4d53-891e-c64877733b7d)
Devs said that btw, and that early loading caused by your mods.

**Comment by Fyoncle** [comment]
Mysteriously that crash gone in my modpcak few days ago, not sure what but i updated some mods.

## Updated;
- 3D Skin Layers
- [EMF] Entity Model Features 2x
- [ETF] Entity Texture Features 3x
- Better Combat
- Deeper and Darker 3x
- Entity Culling 2x
- AmbientSounds 2x
- ModernFix 3x
- Enchanted Vertical Slabs
- Not Enough Animations
- Wavey Capes
- Geckolib 2x
- Philips Ruins
- fast-ip-ping
- Snow Under Trees 4x
- Exposure
- Supplementaries
- Smarter Farmers 2x
- Fabric Language Kotlin 2x
- Sodium Shadowy Path Blocks
- Shoulder Surfing Reloaded 2x
- Tree Harvester
- Soul Fire'd
- Xaero's Minimap
- Xaero's World Map
- Better Archeology
- Villages & Pillages
- Better Statistics Screen
- Moonlight Lib 6x
- Elytra Trims 2x
- Balm 3x
- Simple HUD Enhanced
- Just Enough Breeding 2x
- Resourceful Lib
- Puzzles Lib
- TCDCommons API
- You're in Grave Danger 9x
- ImmediatelyFast 3x
- Chat Heads 2x
- M.R.U 4x
