### ISSUE TITLE
about inventory totem mod in multiplayer

### ISSUE THREAD

**Issue by Browney1019** [ricksouth/serilum-mc-mods#2580]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.20.6
Modloader:  Fabric
 Fabric loader version: 1.20.6
Environment:  Multiplayer

Mod name: inventory totem
Mod version: 1.20.6

**Comment by ricksouth** [comment]
Yes it works in multiplayer, but the mod must be installed on the server as well. No it can't be done client-side only, as the server runs the code for respawning.
