### ISSUE TITLE
DoubleDoors 1.12.2 issue; placed doors revert to single door opening on server start, have to pick up doors and replace them to make double door opening work again

### ISSUE THREAD

**Issue by divineyoukai** [ricksouth/serilum-mc-mods#2589]
## **Information**
Minecraft version: 1.12.2
Modloader: Forge 
Forge version: 14.23.5.2860
Environment: Multiplayer (haven't tested singleplayer)

Mod name: Double Doors
Mod version: 1.12.2-2.5

## **Description**
placed doors revert to single door opening when we start the server, have to pick up doors and replace them to make double door opening work again

## **Crash report**
no crash

**Comment by ricksouth** [comment]
Unfortunately I've stopped supporting Minecraft 1.12.2 a long time ago. Apologies for the inconvenience.

**Comment by divineyoukai** [comment]
understandable, no possible idea what could be the cause of this before you go? I'm assuming it's something on my end since I can't find anyone ever talking about this happening online anywhere
