### ISSUE TITLE
Custom names are being chosen too frequently over random names

### ISSUE THREAD

**Issue by LessThanBenji** [ricksouth/serilum-mc-mods#2598]
## **Information**
Minecraft version: 1.20.4
Modloader: Fabric
Fabric loader version: 0.15.11
Environment: Multiplayer

Mod name: Villager Names
Mod version: 7.3

## **Description**
The names in ./config/villagernames/customnames.txt are being chosen too frequently alongside the default random names. I have useCustomNames = true, useDefaultFemaleNames = true, useDefaultMaleNames = true, and useBothCustomAndDefaultNames = true. The mod seems to alternate every second Villager between a custom and a random name (ie. one spawned Villager will be named a custom name, the next a random, the next a custom, then a random, and so on).

This is causing it to be extremely common to find Villagers named as per customnames.txt over the random names. I'm ideally going for majority random (90-95%) and minority from the custom list (5-10%).

Thanks in advance for any help, and great mod btw!

**Comment by ricksouth** [comment]
It's a 1/3 chance for each list to be chosen. And afterwards it chooses a random name from the list. A solution could be to only use the custom list, but implement all names in there.

The full default name list should be located in ./config/collective/entity_names.json. You would need to convert that to the txt list

**Comment by LessThanBenji** [comment]
I see, that's a good idea! I'll do that. Thank you :)
