### ISSUE TITLE
mob heads appear as alex and steve heads

### ISSUE THREAD

**Issue by garfieldmaconha** [ricksouth/serilum-mc-mods#2645]
Minecraft version: 1.21.1
Modloader: Fabric
Fabric loader version: 0.16.5
Environment: Singleplayer

Mod name: Just Mob Heads
Mod version: 8.3

I installed the vanilla experience modpack and the just mob heads mod doesn't seem to be working correctly, the heads of dropped mobs are appearing as alex and steve heads

**Comment by James103** [comment]
What do you get when you run `/data get entity @s SelectedItem` while holding these heads?

**Comment by garfieldmaconha** [comment]
![image](https://github.com/user-attachments/assets/e3c5787f-03e9-457d-96ff-12ea39bab423)

**Comment by ricksouth** [comment]
Do you own the game and are you in online mode?

**Comment by garfieldmaconha** [comment]
No, I don't own the game, I'm playing through legacy tlauncher, and I'm in singleplayer mode

**Comment by ricksouth** [comment]
That would be it then. I can't offer support for a pirated version. It's because the game can't connect to the Mojang API to receive the textures.
