### ISSUE TITLE
Allow Daily Quests's Quest List to self-position below Bedrockify's save indicator

### ISSUE THREAD

**Issue by vico93** [ricksouth/serilum-mc-mods#2668]
## **Information**
Minecraft version: 1.21.1
Modloader: Fabric
Fabric loader version: 0.16.5
Environment: Singleplayer

First mod name: [Daily Quests](https://modrinth.com/mod/daily-quests) ([GH](https://modrinth.com/mod/daily-quests))
First mod version: 1.3

Second mod name: [Bedrockify](https://modrinth.com/mod/bedrockify) ([GH](https://github.com/juancarloscp52/BedrockIfy))
Second mod version: 1.10.1+mc1.21

## **Description**
Basically, Daily Quests's Quest List doesn't give space to Bedrockify's save indicator like it does with status effects icons:
![image](https://github.com/user-attachments/assets/f4048e66-1cd7-444d-be1d-5b593e28f190)
![image](https://github.com/user-attachments/assets/18aca035-55f6-485d-966c-36fc5296f268)

If possible, add a check for whetever Bedrockify is installed and the save indicator is enabled, if true just make the quest list go below the save indicator when it shows, just like when a status effect is applied to the player.

Pingging @juancarloscp52 (author of Bedrockify) as well, don't know if he likes me to create a correspondent issue on Bedrockify's repo (if he needs to do something on his side).

**Comment by ricksouth** [comment]
I've just uploaded version 1.4 of Daily Quests that adds compatibility with the BedrockIfy save icon. Thanks for the suggestion and giving the new mod a try! :)

**Comment by ricksouth** [comment]
![7d9ead3a8624083b8b1dc258a3480d3b](https://github.com/user-attachments/assets/127bcad9-d6df-493f-9d77-01d66b3c4c0d)

**Comment by vico93** [comment]
Thank you so much!
