### ISSUE TITLE
Game crashes everytime I select and try to play a world

### ISSUE THREAD

**Issue by Rezpit** [ricksouth/serilum-mc-mods#2678]
## **Information**
Minecraft version: 1.21.1
Modloader: Forge 
Forge version: 52.0.16
Environment: Singleplayer

Mod name: Daily Quests
Mod version: 1.7

## **Description**
Anytime I try to play any world I have, the world loads at 0% and crashes

## **Crash report**

[crash-2024-09-29_21.14.05-server.txt](https://github.com/user-attachments/files/17180886/crash-2024-09-29_21.14.05-server.txt)

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try. I wasn't able to replicate it, but added an extra check where the error from your log ran. It should be fixed in version 1.8, but please let me know if it isn't.

https://curseforge.com/minecraft/mc-mods/daily-quests/files

**Comment by Rezpit** [comment]
Hello Rick,

thank you for your fast reply. The version 1.8 really fixed it, thank you
so much!

Best wishes,
Rezpit/Nate

ne 29. 9. 2024 v 22:11 odesílatel Rick South ***@***.***>
napsal:
