### ISSUE TITLE
Theres a huge problem

### ISSUE THREAD

**Issue by swordturf87** [ricksouth/serilum-mc-mods#2704]
## **Information**
Minecraft version: 1.21.1
Modloader: Forge
Forge version: 50.1.20
Environment: Singleplayer 

First mod name: GUI Clock - Serilum
First mod version: 1.21

Second mod name: Mod
Second mod version: x.x

## **Description**
I really want to install this mod but theres one problem. after i learned how to install the clock mod, i ran into some issues. the first one was that i needed to install another mod called collective, and add it to minecraft. i tried adding it the same way i did the clock mod, and it says i need to install it and i have no idea how. im using TLauncher for minecraft and every time i try to install collective it says that i still havent installed it and then i download curseforge and i have the same problem. please help

## **Crash report**
If available.

**Comment by ricksouth** [comment]
Pirated launchers such as Tlauncher are not supported. Please buy the game.

**Comment by swordturf87** [comment]
Well guess what I figured it out so smd and it does work on TLauncher
