### ISSUE TITLE
Paper Books recipe missing

### ISSUE THREAD

**Issue by BaccarWozat** [ricksouth/serilum-mc-mods#2720]
## **Information**
Minecraft version: 1.21.3
Modloader: NeoForge
NeoForge version: 21.3.2-beta
Environment: Singleplayer

Mod name: Paper Books
Mod version: 3.5

## **Description**
Mod does not add recipe.

## **Crash report**
No crash.
![2024-10-25_06 40 17](https://github.com/user-attachments/assets/267c5441-dc63-4251-85b2-d298bf783b33)

**Comment by BaccarWozat** [comment]
Relevant error from latest.log seems to be:
`[25Oct2024 06:37:16.494] [Worker-Main-16/ERROR] [net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener/]: Couldn't parse data file 'paperbooks:paper_book' from 'paperbooks:recipe/paper_book.json': DataResult.Error['Map entry 'P' : Failed to parse either. First: Input does not contain a key [type]: MapLike[{"item":"minecraft:paper"}]; Second: Failed to parse either. First: Not a string: {"item":"minecraft:paper"}; Second: Failed to parse either. First: Not a json array: {"item":"minecraft:paper"}; Second: Not a string: {"item":"minecraft:paper"}; Input does not contain a key [neoforge:ingredient_type]: MapLike[{"item":"minecraft:paper"}]']
`

**Comment by BaccarWozat** [comment]
Fixed in 3.6. Thank you!

**Comment by ricksouth** [comment]
I fixed it after reading your opened issue, just didn't have time to close it. Appreciate it!
