### ISSUE TITLE
Double Doors opens only one door

### ISSUE THREAD

**Issue by BaccarWozat** [ricksouth/serilum-mc-mods#2721]
## **Information**
Minecraft version: 1.21.3
Modloader: NeoForge
NeoForge version: 21.3.2-beta
Environment: Singleplayer

Mod name: Double Doors
Mod version: 5.9

## **Description**
Mod does not allow simultaneous opening of two adjacent doors.

## **Crash report**
No crash.
![2024-10-25_06 39 59](https://github.com/user-attachments/assets/f9706487-1382-4929-ab53-d9d8f14cdcce)

**Comment by BaccarWozat** [comment]
Unfortunately version 6.0 of DD did not fix it. Now it crashes:

https://paste.ee/p/ceVqM

**Comment by ricksouth** [comment]
Make sure to update Collective as well, I see you're running an old version. Does that fix it?

**Comment by BaccarWozat** [comment]
Works now! Thanks again!
The version of Collective had the same version number (7.89) so I didn't notice it still said 1.21.2 in the file name. Blame MultiMC for just showing the version number.
