### ISSUE TITLE
Missing Textures

### ISSUE THREAD

**Issue by Raven-dreams** [ricksouth/serilum-mc-mods#2783]
## **Information**
Minecraft version: 1.21.4
Modloader: Fabric
  Fabric loader version: 0.16.9
Environment: Singleplayer / Multiplayer

Mod name: Healing Soup
Mod version:  1.21.4-5.2

## **Description**
I'm getting missing textures on the items for the soup (ie. the purple black checkerboard image)

I just downloaded and used the most recent version of the mod that was posted sometime today (Dec. 6th)

I'm not sure if I've got something installed wrong or what, I deleted the mod and tried to reinstall it by just downloading the mod file and putting it in the mods folder, also tried reinstalling it via the curse forge launcher.  but both attempts still show the missing textures.

**Comment by ricksouth** [comment]
Thank you for opening the issue! This has been fixed in version 5.3 of Healing Soup. Appreciate it.

https://curseforge.com/minecraft/mc-mods/healing-soup/files
