### ISSUE TITLE
Multiple bees spawned when breeding bees

### ISSUE THREAD

**Issue by Parva-Ovis** [ricksouth/serilum-mc-mods#703]
## **Information**
Minecraft version: 1.16.5
Modloader: Forge
Forge version: 32.2.0
Environment: Singleplayer

Mod name: Realistic Bees
Mod version: 2.2

## **Description**
When breeding bees, if the player is not within a few blocks of the bees, multiple adult bees are spawned in addition to the baby bee.

No other mods are installed besides Collective 1.16-2.64.

**Comment by James103** [comment]
When fixing this, if the intention is to spawn multiple bees from each breeding, make sure that the extra bees are spawned as babies and not adults.

**Comment by ricksouth** [comment]
Thanks for giving the mod a try and opening the bug report! This has been fixed in version 2.3 of the mod.

https://www.curseforge.com/minecraft/mc-mods/realistic-bees/files
