### ISSUE TITLE
[smallernetherportals-fabric] does not work

### ISSUE THREAD

**Issue by MSandro** [ricksouth/serilum-mc-mods#708]
## **Information**
Minecraft version: 1.16.5
Modloader: Fabric
Fabric loader version: 0.11.6
Environment: Singleplayer

Mod name: SmallerNetherPortals-fabric
Mod version: 1.8

## **Description**
I can not ignite smaller nether portals!
![2021-09-20_10 37 25](https://user-images.githubusercontent.com/10937159/133975851-a2915c88-c01e-4bcb-a915-5e27d23a915d.png)

## **Crash report**
sorry, I can't find errors in the latest.log cuased by this mod.

**Comment by ricksouth** [comment]
Can you still upload the latest.log so I can see which mods load up?

**Comment by ricksouth** [comment]
Are you using a (custom) flint and steel to light the portal? Or custom obsidian?
