### ISSUE TITLE
[1.12.2] Holding 1 empty glass bottle and right-clicking will hurt you, but not produce any XP bottle.

### ISSUE THREAD

**Issue by MagmaSlime123** [ricksouth/serilum-mc-mods#709]
## **Information**
Minecraft version: See title.
Modloader: Forge.
Forge version: 2855.
Environment: Singleplayer.

Mod name: Bottle Your XP.
Mod version: 1.5.

## **Description**
Holding 1 empty glass bottle and right-clicking will hurt you, but not produce any XP bottle. However, holding 2 or more, will.

## **Crash report**
N/A

**Comment by ricksouth** [comment]
Thanks for giving the mod a try and opening the bug report. I can't reproduce this locally. It works as intended. It might be an incompatibility with other mod, closing this for now but please let me know if the problem persists along with your mod list.

Kind regards,
Rick

**Comment by MagmaSlime123** [comment]
Apparently issue is fixed on my end as well. Might've been a mod I had that I removed without noticing.

**Comment by ricksouth** [comment]
Alright! Glad it works.
