### ISSUE TITLE
Removal of Automatic Doors

### ISSUE THREAD

**Issue by Killertree123** [ricksouth/serilum-mc-mods#710]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.16.5 
Modloader: Forge /1.16.5-36.2.4
Forge version: 32.2.4
Environment: Multiplayer

Mod name: The Vanilla Experience
Mod version: 1.1

## **Question**
Is there a way to disable to Automatic doors. I personally like everything in the mod except the automatic doors.

**Comment by ricksouth** [comment]
You can disable the automatic doors inside the config.

See here on how to get to the config files: https://github.com/ricksouth/serilum-mc-mods/wiki/How-To-Configure-mods
