### ISSUE TITLE
Unable to create a world

### ISSUE THREAD

**Issue by ghost** [ricksouth/serilum-mc-mods#711]
## **Information**
Minecraft version: 1.16.5
Modloader: Forge
Forge version: 36.2.0
Environment: Singleplayer

Mod name: Realistic Bees
Mod version: 2.2

## **Description**
I'm not getting any errors I'm in go see in the thread.
With halogen I had no problem just that the mod did nothing.

Can be incompatible with other mods ?

## **Crash report**
https://hastebin.com/hejuxebidi.apache

**Comment by ricksouth** [comment]
Unfortunately there's no log. Might be a compatibility issue. If the problem persists please let me know the modlist so I can attempt a fix in the future. As of now unsure how to reproduce it. Thanks for giving the mod a try though!
