### ISSUE TITLE
uh

### ISSUE THREAD

**Issue by mika37** [ricksouth/serilum-mc-mods#714]
## **Information**
Minecraft version: 1.17.1
Modloader:  Fabric
 Fabric loader version: latest
Environment: Multiplayer

Mod name: Tree Harvester (Fabric)
Mod version: latest

## **Question**
is this a server side mode?

**Comment by ricksouth** [comment]
Yes you can use it server side only, though if you use the config option to break all leaves instantly you'll probably want it on the client to prevent the sound from going crazy.
