### ISSUE TITLE
Lag Spike When Minerals found while mining

### ISSUE THREAD

**Issue by sweetsosweet** [ricksouth/serilum-mc-mods#716]
## **Information**
Minecraft version: 1.17.1
Modloader: Fabric
Fabric loader version: 0.11.6
Environment: Singleplayer

Mod name: Mineral Chance (Fabric)
Mod version: mineralchance-fabric_1.17.x-1.6

## **Description**

While mining normally, every time a mineral is found there will be a lag spike. Sometimes small, but sometimes the game will freeze totally (with windows spinning mouse symbol) for a few seconds before whatever mineral is received in the inventory.

## **Crash report**

No crash, but maybe log will help?

[latest.log](https://github.com/ricksouth/serilum-mc-mods/files/7230458/latest.log)

**Comment by ricksouth** [comment]
My guess this is optifine which is not playing nicely. I'd recommend Sodium: https://www.curseforge.com/minecraft/mc-mods/sodium

The mod itself isn't doing anything crazy, just adding an item entity into the world. Thanks for giving the mod a try though!
