### ISSUE TITLE
Support For Modded Campfires

### ISSUE THREAD

**Issue by Seikikai** [ricksouth/serilum-mc-mods#718]
## **Information**
Mod name: No Hostiles Around Campfire/Healing Campfire

## **Feature description**
Would Be Good If You Can Apply The Campfire Bonus To Any Modded Campfire -Any Block With The Tag: minecraft:campfires-.

**Comment by ricksouth** [comment]
Support for modded campfires has been added in the latest version. Thanks for the suggestion and giving the mods a try!

https://www.curseforge.com/minecraft/mc-mods/no-hostiles-around-campfire/files
https://www.curseforge.com/minecraft/mc-mods/healing-campfire/files
