### ISSUE TITLE
Enchanting Commands: Add Third Party Modded Enchantment Support

### ISSUE THREAD

**Issue by TheNickm2** [ricksouth/serilum-mc-mods#720]
## **Information**
Mod name: Enchanting Commands

## **Feature description**
It would be fantastic if the enchanting commands mod supported modded enchantments. For example, I have the [Enchanting Fever](https://www.curseforge.com/minecraft/mc-mods/enchanting-fever) mod installed on my server, and would love to be able to apply the modded enchants (like Frost Aspect) via this mod.

**Comment by elhertz** [comment]
+1
Auto-completion of modded enchantments should also work with vanilla clients

**Comment by ricksouth** [comment]
This has been added in the latest release of Enchanting Commands. Thanks for the suggestion and giving the mod a try!

https://www.curseforge.com/minecraft/mc-mods/enchanting-commands/files

**Comment by gwynhefar** [comment]
Any chance of adding this feature to the 1.12.2 version?
