### ISSUE TITLE
[Just Mob Heads] Grammatically incorrect text for error generating head chance config file

### ISSUE THREAD

**Issue by James103** [ricksouth/serilum-mc-mods#723]
## **Information**
Mod name: Just Mob Heads
Mod version: 9c376dd1be8ce7c287692f42ae5e991dd0c6f026

## **Description**
The text in the following line of code is grammatically incorrect.
https://github.com/ricksouth/serilum-mc-mods/blob/9c376dd1be8ce7c287692f42ae5e991dd0c6f026/sources/Just%20Mob%20Heads/src/main/java/com/natamus/justmobheads/util/HeadData.java#L233

The correct text is:
`[Just Mob Heads] Something went wrong while generating a head chance config file.`

**Comment by ricksouth** [comment]
Thanks detective James! :) FIxed in version 5.0.

https://www.curseforge.com/minecraft/mc-mods/just-mob-heads/files/all
