### ISSUE TITLE
Disable lightning when charged creeper spawns

### ISSUE THREAD

**Issue by elhertz** [ricksouth/serilum-mc-mods#726]
## **Information**
Mod name: Naturally Charged Creepers

## **Feature description**
I've set a high chance of charged creepers spawning and the lightning it's getting very annoying.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 2.3 of Naturally Charged Creepers. You'll also need to update Collective to the latest version.

https://www.curseforge.com/minecraft/mc-mods/naturally-charged-creepers/files
