### ISSUE TITLE
1.16.5 Fabric v2.6 doesn't seem to impliment on the next game after save.

### ISSUE THREAD

**Issue by Kilroy5150** [ricksouth/serilum-mc-mods#727]
## **Information**
Minecraft version: 
Modloader:  Fabric
Forge version:Fabric loader version: 1.16.5
Environment: Singleplayer

Mod name: Starterkit
Mod version: 2.6

BTW - The Forge 1.16.5 version works perfectly....This one, not so much.

I do a /starterkit set in the previous game and in the next, new game....it doesn't remember. It writes the file but i won't implement.

I'm not techie enough, in this game, to know all the versions of all the libraries. I got the file directly from forge, not some 3rd party site.

I hope the logfile gives the necessary information.

[latest.log](https://github.com/ricksouth/serilum-mc-mods/files/7255924/latest.log)
## **Description**
Hey! This happened..

## **Crash report**
If available.

**Comment by ricksouth** [comment]
Thanks for submitting the bug report and giving the mod a try! Starter Kit version 2.7 should fix the issues you were having. Let me know if you have any more problems.

https://www.curseforge.com/minecraft/mc-mods/starter-kit-fabric/files
