### ISSUE TITLE
[Compatibility Request] The Farlanders - Rebel Farlander Treated As A Villager

### ISSUE THREAD

**Issue by Seikikai** [ricksouth/serilum-mc-mods#728]
The [Rebel Farlander](https://www.curseforge.com/minecraft/mc-mods/farlanders) Is Treated As A Villager By **Villager Names** And **Villager Death Messages**.

**Comment by ricksouth** [comment]
That's correct. Should they not be? It's added on purpose

**Comment by Seikikai** [comment]
No, They're The Counterpart Of The Farlanders, In Other Words They're Farlander Illagers.

**Comment by ricksouth** [comment]
Thanks for letting me know. I've removed the Farlander Rebel named feature in Collective 2.65.

https://www.curseforge.com/minecraft/mc-mods/villager-names
https://www.curseforge.com/minecraft/mc-mods/collective

**Comment by Seikikai** [comment]
I've Spawned A Couple Of Farlander Rebels With The Latest Versions Of Collective And Villager Names. The Rebel Farlanders Still Spawning With Names And Sending Death Messages. Also Spawned Other Mobs From The Mod And Found That The Wanderer (Farlander Wandering Trader) Is Now Spawning Without A Name. Can You Check That You Removed The Correct Entity From The List?

**Comment by ricksouth** [comment]
I did mess up a little there! I've fixed it in the latest release of Collective. Thanks for letting me know.
