### ISSUE TITLE
(Feature Suggestion) Add config option for axe durability use modifier

### ISSUE THREAD

**Issue by FastBoye127** [ricksouth/serilum-mc-mods#730]
## **Information**
Mod name: Tree Harvester

## **Feature description**
Treecapitator had a great feature wherein the user could define the multiplier for axe durability use. It feels odd to chop down a few 2x2 trees and have your axe break. I realize that 1 durability per wood block harvested is more balanced, but a config option would be very nice.

Thank you for making this wonderful mod!

**Comment by ricksouth** [comment]
I've just released version 4.0 of Tree Harvester which adds the config option 'loseDurabilityModifier'. This should add the functionality you've requested. Thanks for giving the mod a try and submitting the sugestion!

https://www.curseforge.com/minecraft/mc-mods/tree-harvester/files
