### ISSUE TITLE
Easy Elytra doesn't work

### ISSUE THREAD

**Issue by Kasprenius** [ricksouth/serilum-mc-mods#732]
## **Information**
Minecraft version: 1.17.1
Modloader:  Fabric
Environment: Singleplayer

Mod name: Easy Elytra Takeoff
Mod version: 1.41

## **Description**
I can't seem to get the mod to work.. at all? Help? XD

**Comment by ricksouth** [comment]
Thanks for giving the mod a try and opening the bug report! This has been fixed in version 2.2 of the mod.

https://www.curseforge.com/minecraft/mc-mods/easy-elytra-takeoff-fabric/files/all
