### ISSUE TITLE
[1.16] Questions about the World Border mod

### ISSUE THREAD

**Issue by tanyan-tanyan** [ricksouth/serilum-mc-mods#734]
## **Information**

Mod name: World Border (Forge)
Mod version: 1.6.5 - 2.4

## **Question**
Hi, I am hosting an ATM6 server and I have an issue in relation to world borders, so I want to ask a couple questions to find out if this mod is what I need to fix that issue. 

1. As our server is intended for public use, getting players to install extra mods is out of question. Is this a purely server-side mod?
2. Is it possible to set up different world border sizes for each dimension with the use of your mod? For example 10k x 10k for the Overworld, and then 50k x 50k for The End, etc.

**Comment by James103** [comment]
1. The mod appears to be server side only, as it has the label "Server Utility" in Modrinth.
2. Check the following settings. There's one set for each of the vanilla dimensions.
NOTE: Custom dimensions are not limited by the World Border mod. A dynamic config is required to implement that feature.
For details, see #412.

```
overworldBorderPositiveX (default = 5000, min 0, max 100000): The overworld border located at the positive x coordinate.
overworldBorderNegativeX (default = -5000, min -100000, max 0): The overworld border located at the negative x coordinate.
overworldBorderPositiveZ (default = 5000, min 0, max 100000): The overworld border located at the positive z coordinate.
overworldBorderNegativeZ (default = -5000, min -100000, max 0): The overworld border located at the negative z coordinate.

netherBorderPositiveX (default = 625, min 0, max 100000): The nether border located at the positive x coordinate.
netherBorderNegativeX (default = -625, min -100000, max 0): The nether border located at the negative x coordinate.
netherBorderPositiveZ (default = 625, min 0, max 100000): The nether border located at the positive z coordinate.
netherBorderNegativeZ (default = -625, min -100000, max 0): The nether border located at the negative z coordinate.

endBorderPositiveX (default = 5000, min 0, max 100000): The end border located at the positive x coordinate.
endBorderNegativeX (default = -5000, min -100000, max 0): The end nether border located at the negative x coordinate.
endBorderPositiveZ (default = 5000, min 0, max 100000): The end nether border located at the positive z coordinate.
endBorderNegativeZ (default = -5000, min -100000, max 0): The end nether border located at the negative z coordinate.
```

**Comment by ricksouth** [comment]
Thanks @James103 for answering. That's correct.
