### ISSUE TITLE
Server wide stutter when using tree harvester

### ISSUE THREAD

**Issue by JakeFromStateFarm101** [ricksouth/serilum-mc-mods#738]
causes all users fps to drop from typical fps to around 15, does not matter distance to tree for users

**Comment by ricksouth** [comment]
I've just released version 4.0 of Tree Harvester which optimizes some code and hopefully fixes the issues you were having. I can't reproduce it locally. My only other guess is that the server can't handle the amount of calculations which are necessary for the fast leaf decay. Setting instant break leaves on in the config might fix it as well. Thanks for giving the mod a try!

https://www.curseforge.com/minecraft/mc-mods/tree-harvester/files
