### ISSUE TITLE
Crash when MAVM Axolotl Dies

### ISSUE THREAD

**Issue by milkev** [ricksouth/serilum-mc-mods#742]
## **Information**
Minecraft version: 1.17.1
Modloader: Fabric
FAPI: 40.8
Fabric loader version: 11.7
Environment: Singleplayer

Mod name: Just Mob Heads (Fabric)
Mod version: 4.2
Collective version: 1.41
Other Mod: MAVM (#TerribleFileName) aka [More Axolotl Variants Mod](https://www.curseforge.com/minecraft/mc-mods/mavm)
Version: 1.0.5

## **Description**
When an axolotl from more axolotl variants dies the game crashes. . .
this happens just randomly while running around your world... axolotls die a lot more than one would expect

My best guess at whats happening is that the axolotl variant int is above the expect value of your mod, so your mod just throws an 'index out of bounds' error since it didnt expect a value outside vanilla limitations

## **Crash report**
[https://pastebin.com/nsi163nd](https://pastebin.com/nsi163nd)

**Comment by James103** [comment]
Likely a duplicate of #722

**Comment by milkev** [comment]
so it seems, i only searched through the Just mob heads tagged issues so i didnt see it

**Comment by ricksouth** [comment]
Apologies for the late response. I've fixed the problem in version 5.0 of Just Mob Heads. Thanks for giving the mod a try and opening the bug report!

https://www.curseforge.com/minecraft/mc-mods/just-mob-heads-fabric/files/all
