### ISSUE TITLE
[Start Kits] Lose my items when I create a new island with FTB Team Islands

### ISSUE THREAD

**Issue by savosdarkran** [ricksouth/serilum-mc-mods#747]
## **Information**
Minecraft version: 1.16.5
Modloader: Forge
Forge version: 36.2.8  OR  Fabric loader version: x.xx.x
Environment:  Multiplayer

Mod name: startkits
Mod version: 2.5

## **Description**
When setting up a server and joining. I spawn on the default lobby island with my starting items. When I type the command /ftbteamislands create the obvious thing happens in that I spawn to the new island. What I am not sure of is whether or not I should lose my items.

I found in the configuration file that there is a parameter clearInvWhenTeamLeft = true. I expected that this meant that I would lose my items when I leave a team. So by default am I in a team on my own when I join the server? If not, is this the expected behaviour for this particular parameter by default?

When I set the parameter to false it works as expected and I spawn on my island with my starting items.

Please see the following link for further reference.  Their proposed solution doesn't make much sense and this is in SkyFactory One so I'm not about to do random recipes and futz with Darkosto and team's hard work.
[https://github.com/FTBTeam/FTB-Mods-Issues/issues/83](url)

## **Crash report**
Not Available

**Comment by ricksouth** [comment]
Starter Kit 3.0 adds support to FTB Team Islands! The kit will be re-set after the '/ftbteamislands create' command. The functionality can also be turned off in the config. Thanks for using the mod and opening the suggestion!

https://www.curseforge.com/minecraft/mc-mods/starter-kit/files

**Comment by ricksouth** [comment]
Just wondering, is there also a Join command for other players? That need to have their inventory set as well?
