### ISSUE TITLE
Passive Endermen doesn't seem to work

### ISSUE THREAD

**Issue by FyraFire** [ricksouth/serilum-mc-mods#748]
## **Information**
Minecraft version: 1.16.5
Modloader: Forge
Forge version: 36.2.0
Environment: Singleplayer

Mod name: Passive Endermen
Mod version: 1.16.5 - 1.5

## **Description**
The mod doesn't seem to be working at all. Endermen attack when looked at, teleport and pick up blocks no matter what is selected in the config.

**Comment by ricksouth** [comment]
Apologies for the late reply. This has been fixed in version 2.0 of Passive Endermen. Thanks for giving the mod a try and opening the issue!

https://www.curseforge.com/minecraft/mc-mods/passive-endermen/files/all
