### ISSUE TITLE
Fabric server crashing with Collective versions after 1.44

### ISSUE THREAD

**Issue by GhostRiderGrey** [ricksouth/serilum-mc-mods#752]
## **Information**
Minecraft version: 1.17.1
Modloader: Fabric
Fabric loader version: 0.8.1
Environment: Server

Mod name: Collective
Mod version: 1.44 working, anything above is crashing server start

## **Description**
Collective 1.44 is working fine, any version I've tried above that is crashing server start.  I've included logs from the 1.44 start and the 1.48 start.  Looks like things start to go sideways at about line 514.  Thanks for taking a look and I appreciate all you do for the Minecraft modding community.

## **Crash report**

[latest-Collective 1.48.log](https://github.com/ricksouth/serilum-mc-mods/files/7405801/latest-Collective.1.48.log)
[latest-Collective 1.44.log](https://github.com/ricksouth/serilum-mc-mods/files/7405802/latest-Collective.1.44.log)
.

**Comment by GhostRiderGrey** [comment]
Fabric loader is actually 0.11.7-1.17.1     The 0.8.1 I listed above was the Fabric installer version.

**Comment by ricksouth** [comment]
Looks like Neutrino is overwriting the CropBlock function randomTick.
https://github.com/FrostWizard4/Neutrino/blob/1.17.1/src/main/java/com/frostwizard4/Neutrino/mixin/CropBlockMixin.java

Not sure how to fix this yet. Overwriting is usually a bad practice to do. Does it work when you remove Neutrino? Preferablly they'd work together but that'll require some more research on my end

I inject code into that function

**Comment by GhostRiderGrey** [comment]
ricksouth, thank for the quick reply! I removed Neutrino and put Collective 1.48 in.  The server starts just fine so I've think you've found the culprit.  While Neutrino is nice, I'd rather use your wide variety of mods (gots to have GUI Followers, Hoe Tweaks and Pet Names, lol) so if a work around cannot be found, at least I know what I have to do (pull Neutrino out).  Thanks!

**Comment by ricksouth** [comment]
I'm glad you like them! :)

Could you test out Collective 1.49 for me? This adds compatibility with Neutrino and other mods that might overwrite functions. They still shouldn't have overwritten that function but it should work now.

https://www.curseforge.com/minecraft/mc-mods/collective-fabric/files/all

**Comment by GhostRiderGrey** [comment]
Tested with Collective 1.49 and Neutrino 0.4.8. Server and client both load now and work.  Thank you very much!

**Comment by ricksouth** [comment]
Great! Thanks for testing and using the mods :)
