### ISSUE TITLE
Giant Spawn Fabric Port

### ISSUE THREAD

**Issue by topkekistani** [ricksouth/serilum-mc-mods#754]
## **Information**
Minecraft version: 1.117.1

Mod name: Giant Spawn
Mod version: giantspawn_1.17.1-2.7.jar

## **Comment**
!Will you be adding a Fabric port to this mod?

**Comment by ricksouth** [comment]
Giant Spawn has had its Fabric version released :)

https://www.curseforge.com/minecraft/mc-mods/giant-spawn-fabric
