### ISSUE TITLE
Death Backup missing several items upon restoration

### ISSUE THREAD

**Issue by kaladinsa** [ricksouth/serilum-mc-mods#755]
## **Information**
Minecraft version: 1.16.5
Modloader: Forge
Forge version: 36.2.4
Environment: Singleplayer / Multiplayer

Mod name: Death Backup
Mod version: 1.16.5-1.5

## **Description**
Ello. I had a player die and when restoring his items, a large portion was missing when loading in the death backup (even items shown on file). Items from Artifacts, Sophisticated backpacks and castle in the sky, along with the netherite armour (helm, chest, legs, boots) didn't appear. They loaded several other death backup times yet this case of missing items happened every time. There was also one item, a bezoar from BountifulBaubles, that didn't show up on the death backup file (player had it worn in the curio slot when dying). Happy to provide any more info if needed. Thanks!

## **Restoration file in question**
'offhand' : '',
'head' : '{id:"minecraft:netherite_helmet",Count:1b,tag:{RepairCost:63,Damage:12,Enchantments:[{lvl:3s,id:"ensorcellation:exp_boost"},{lvl:3s,id:"minecraft:unbreaking"},{lvl:1s,id:"minecraft:mending"},{lvl:4s,id:"minecraft:protection"},{lvl:1s,id:"uniquee:treasurers_eyes"},{lvl:3s,id:"minecraft:respiration"},{lvl:1s,id:"minecraft:aqua_affinity"}]}}',
'chest' : '{id:"minecraft:netherite_chestplate",Count:1b,tag:{RepairCost:15,Damage:10,Enchantments:[{lvl:4s,id:"minecraft:protection"},{lvl:3s,id:"minecraft:thorns"},{lvl:3s,id:"minecraft:unbreaking"},{lvl:1s,id:"minecraft:mending"},{lvl:4s,id:"survive:cooling"}]}}',
'legs' : '{id:"minecraft:netherite_leggings",Count:1b,tag:{RepairCost:15,Damage:11,Enchantments:[{lvl:4s,id:"minecraft:protection"},{lvl:3s,id:"minecraft:thorns"},{lvl:3s,id:"minecraft:unbreaking"},{lvl:1s,id:"minecraft:mending"},{lvl:1s,id:"survive:adjusted_warming"}]}}',
'feet' : '{id:"minecraft:netherite_boots",Count:1b,tag:{RepairCost:31,Damage:8,Enchantments:[{lvl:4s,id:"minecraft:protection"},{lvl:3s,id:"minecraft:depth_strider"},{lvl:3s,id:"minecraft:thorns"},{lvl:3s,id:"minecraft:unbreaking"},{lvl:1s,id:"minecraft:mending"}]}}',
0 : '{id:"spartanweaponry:rapier_diamond",Count:1b,tag:{RepairCost:15,Damage:2,Enchantments:[{lvl:3s,id:"minecraft:unbreaking"},{lvl:6s,id:"minecraft:sharpness"},{lvl:2s,id:"uniquee:ranged"},{lvl:2s,id:"uniquebattle:ifrits_judgement"},{lvl:5s,id:"uniquebattle:ifrits_blessing"},{lvl:3s,id:"minecraft:looting"},{lvl:4s,id:"ensorcellation:leech"},{lvl:1s,id:"minecraft:mending"},{lvl:3s,id:"uniquee:sages_blessing"},{lvl:3s,id:"uniquee:swiftblade"}]}}',
1 : '{id:"spartanweaponry:greatsword_diamond",Count:1b,tag:{RepairCost:1,Damage:5,Enchantments:[{lvl:3s,id:"minecraft:sweeping"},{lvl:5s,id:"minecraft:sharpness"},{lvl:3s,id:"uniquee:focus_impact"},{lvl:3s,id:"uniquee:sages_blessing"},{lvl:1s,id:"minecraft:mending"},{lvl:3s,id:"minecraft:unbreaking"}]}}',
2 : '{id:"minecraft:netherite_pickaxe",Count:1b,tag:{RepairCost:31,Damage:0,Enchantments:[{lvl:3s,id:"minecraft:unbreaking"},{lvl:1s,id:"minecraft:mending"},{lvl:1s,id:"minecraft:silk_touch"},{lvl:5s,id:"minecraft:efficiency"},{lvl:1s,id:"veinmining:vein_mining"}]}}',
3 : '{id:"minecraft:diamond_pickaxe",Count:1b,tag:{Damage:1,Enchantments:[{lvl:4s,id:"minecraft:fortune"},{lvl:3s,id:"uniquee:sages_blessing"},{lvl:1s,id:"minecraft:mending"},{lvl:4s,id:"minecraft:efficiency"},{lvl:3s,id:"minecraft:unbreaking"},{lvl:1s,id:"veinmining:vein_mining"}]}}',
4 : '{id:"minecraft:cooked_porkchop",Count:59b}',
5 : '{id:"minecraft:netherite_scrap",Count:21b}',
6 : '{id:"minecraft:enchanted_book",Count:1b,tag:{StoredEnchantments:[{lvl:1s,id:"alexsmobs:serpentfriend"}]}}',
7 : '{id:"artifacts:steadfast_spikes",Count:1b}',
8 : '{id:"sophisticatedbackpacks:diamond_backpack",Count:1b,tag:{inventorySlots:108,openTabId:4,upgradeSlots:5,sortBy:"count",contentsUuid:[I;-1890659908,-397130730,-2069874286,1895209117]}}',
9 : '{id:"artifacts:power_glove",Count:1b}',
10 : '{id:"magicaljewelry:silver_ring",Count:1b,tag:{Rarity:"legendary",LegendaryEffect:2,Attributes:1,GemColor:"pink",Effects:[I;1,3,0,2,4,5],UUID:"f5a6474b-d602-481a-a431-1b5d7251ed9b"}}',
11 : '{id:"magicaljewelry:gold_ring",Count:1b,tag:{Rarity:"legendary",LegendaryEffect:1,Attributes:1,GemColor:"black",Effects:[I;0,2,5,4,3,1],UUID:"bf4797c4-334e-4eb7-b19d-7bae738f03b4"}}',
12 : '',
13 : '',
14 : '',
15 : '',
16 : '',
17 : '',
18 : '{id:"castle_in_the_sky:red_key",Count:1b}',
19 : '{id:"castle_in_the_sky:blue_key",Count:1b}',
20 : '{id:"castle_in_the_sky:yellow_key",Count:1b}',
21 : '',
22 : '',
23 : '',
24 : '',
25 : '',
26 : '{id:"minecraft:golden_apple",Count:1b}',
27 : '{id:"minecraft:diamond_axe",Count:1b,tag:{Damage:36,Enchantments:[{lvl:1s,id:"veinmining:vein_mining"},{lvl:5s,id:"minecraft:efficiency"},{lvl:3s,id:"minecraft:unbreaking"}]}}',
28 : '{id:"minecraft:water_bucket",Count:1b}',
29 : '{id:"minecraft:golden_boots",Count:1b,tag:{Damage:0,Enchantments:[{lvl:2s,id:"minecraft:soul_speed"}]}}',
30 : '{id:"minecraft:gold_nugget",Count:6b}',
31 : '{id:"minecraft:enchanted_book",Count:1b,tag:{StoredEnchantments:[{lvl:1s,id:"ensorcellation:excavating"},{lvl:1s,id:"minecraft:flame"},{lvl:4s,id:"ensorcellation:magic_protection"}]}}',
32 : '{id:"minecraft:diamond_block",Count:1b}',
33 : '{id:"minecraft:iron_block",Count:5b}',
34 : '{id:"minecraft:gold_ingot",Count:33b}',
35 : '{id:"minecraft:iron_ingot",Count:8b}',

**Comment by James103** [comment]
There is likely two problems here:
1. Death Backups is not recognizing items that are not in the `minecraft:` namespace.
2. Items worn in inventory slots that are not in vanilla Minecraft (such as Curios slots) are not saved.

To reproduce the first problem:
1. Install a mod that adds modded items.
2. Die while holding a modded item and a vanilla item.
3. Load the resulting Death Backup.
4. Notice that the modded item is not automatically restored.

To reproduce the second problem:
1. Install a mod that adds extra slots to your inventory such as Curios.
2. Die while you have any item in these extra slots.
3. Load the resulting Death Backup.
4. Notice that the item is not automatically restored.
5. Inspect the Death Backup file.
6. Notice that the item is not even saved.

**Comment by kaladinsa** [comment]
For some reason, everything is working on the server now. Backups are loading modded items, both in the inventory and worn in curio slots. I was able to replicate both problems in a smp, but again, not the server. Mods, configs and all are the same between the two. For now I guess things are working - I'll do more in-depth testing if the issue happens again. Thanks for the reply!

**Comment by ricksouth** [comment]
Thanks @kaladinsa for using the mod. Glad it's working. Please reopen the issue if the problem happens again.
