### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by noxic-dev** [ricksouth/serilum-mc-mods#756]
So I use The Mod! But It Dont Deploy The Elytra, Im Lagging and Dont Happy

**Comment by James103** [comment]
Which mod are you referring to?

**Comment by noxic-dev** [comment]
Elytra mod

**Comment by ricksouth** [comment]
Thanks for giving the mod a try and opening the bug report! This has been fixed in version 2.2 of the mod.

https://www.curseforge.com/minecraft/mc-mods/easy-elytra-takeoff-fabric/files/all
