### ISSUE TITLE
Mod Compatibility question

### ISSUE THREAD

**Issue by tillasiren** [ricksouth/serilum-mc-mods#757]
Minecraft version: 1.16.4
Modloader: Forge
Environment: Singleplayer
Mod name: Follower GUI

## **Question**
Hi I recently downloaded your mod and found it quite lovely... until I went and tamed some foxes from one of my mods. Which apparently show up constantly as I don't have a method to make them sit (my alternative was to make a non following version that was still tamed) is there anyway I could make your mod count them on the list when they aren't following?  I'll attach a link to my mod so you can see for yourself. Apologies for posting here but I couldn't find any other way to contact you.

https://www.curseforge.com/minecraft/mc-mods/more-domesticated-foxes

also realizing if it does this with my foxes when tamed... my spider mod is likely also gonna have the same thing happen.

**Comment by ricksouth** [comment]
I appreciate you wanting to add the compatibility!

I can't read your source code, but I'm using:
`			if (te.isInSittingPose()) {
				continue;
			}`
			
If you can overwrite that function in your own entity and have that return true when they are not following, it should add compatibility to my mod and others as well. Let me know if I can help further.

**Comment by ricksouth** [comment]
The function in Minecraft's code:
`
public boolean isInSittingPose() {
      return (this.entityData.get(DATA_FLAGS_ID) & 1) != 0;
   }
`
