### ISSUE TITLE
Can you add 1.12 support?

### ISSUE THREAD

**Issue by acompleteidiot** [ricksouth/serilum-mc-mods#762]
The mod I'm asking for you to add 1.12 support for is Grass Seeds, if you don't want to add 1.12 support, thats ok! [Minecraft mod]

**Comment by ricksouth** [comment]
Grass Seeds for Forge has a 1.12 version: https://www.curseforge.com/minecraft/mc-mods/grass-seeds/files/all?filter-status=1&filter-game-version=1738749986:628

The 1.12 version for Fabric is not planned. Thanks for the interest!
