### ISSUE TITLE
Add a In-game config to your all of your mods

### ISSUE THREAD

**Issue by tankyap** [ricksouth/serilum-mc-mods#763]
## **Information**
Add a In-game config from a mod called **Mod menu** (Fabric only because they dont wanted to port to Forge)

## **Feature description**

> - Can you add a In-game config feature`(basically a feature can let you config while you were opening the game without open the file)` to all of your Fabric mods with **Mod menu**?If you seen this,you probably think its impossible, `but actually it did existed.`

> -  The reason I need this feature is because it would be pretty annoying if you want to config and test it out by open and closing over and over till its perfect for you.

> - You [check the mod here](https://www.curseforge.com/minecraft/mc-mods/modmenu) for the more imformation of this mod

BTW,I also forgot that theres a mod that looks like mod menu is [Configured ](https://www.curseforge.com/minecraft/mc-mods/configured). Basically Mod menu but for Forge

**Comment by FireController1847** [comment]
+1 on this, would absolutely love Mod Menu support!!! Basically a requirement for Fabric mods at this point! :)

**Comment by ricksouth** [comment]
It has taken a while and quite a bit of effort, but every mod in 1.16.5, 1.18.2 and 1.19.2 is now compatible with Mod Menu. Mods that have a config are now also configurable via Mod Menu's in-game config screen. Thank you for the patience and using the mods! 🥳
