### ISSUE TITLE
Move Boats doesn't seem to work with Quark boats

### ISSUE THREAD

**Issue by Star-X555** [ricksouth/serilum-mc-mods#764]
## **Information**
Minecraft version: 1.12.2
Modloader: Forge
Forge version: Latest one for 1.12.2 as of October 2021
Environment: Singleplayer / Multiplayer

Mod name: Move Boats
Mod version: Latest 1.12.2 build as of October 2021

## **Description**
When trying to use Move Boats' functionality to move a boat while Quark's Boat Extensions are active, nothing happens.  It's as if the boat was simply not there at all.

## **Crash report**
None, game doesn't crash when doing this thankfully.

**Comment by ricksouth** [comment]
Seems like an incompatibility issue I can't change on my end unfortunately. I'm checking for "instanceof BoatEntity", as there are no EntityTags available I can't make it more compatible at this moment. Thanks for the interest though!
