### ISSUE TITLE
Auto Totem isn't working

### ISSUE THREAD

**Issue by jonjon1322** [ricksouth/serilum-mc-mods#765]
## **Information**
Minecraft version: 1.17.1
Modloader: Fabric
Fabric loader version: Optifine_1.17.1_HD_U_G9
Environment: Multiplayer (server) client

Mod name: Inventory Totem (Fabric)
Mod version: x.x

## **Description**
When i going a server then while not holding a totem i die

## **Crash report**
If available.

**Comment by ricksouth** [comment]
Optifine is not Fabric. Do you have Fabric installed?
