### ISSUE TITLE
Passive Shield modded shields compatibility

### ISSUE THREAD

**Issue by ricksouth** [ricksouth/serilum-mc-mods#770]
## **Information**
Mod name: Passive Shield

**Comment by ghost** [comment]
i would love to see modded shield compatibility :D

**Comment by ricksouth** [comment]
If another mod wants to add compatibility, they'll have to extend the ShieldItem in their Shield class. I can't seem to see another solution for now. If anyone has a better idea, I'd love to hear it. Closing this for now
