### ISSUE TITLE
small bug with Aether Reborn

### ISSUE THREAD

**Issue by NamePend-ing** [ricksouth/serilum-mc-mods#772]
Minecraft version: 1.16.5
Modloader: Fabric
Fabric loader version: 0.11.7
Environment: Singleplayer

Mod name: Village Spawn w/ Aether Reborn

Hey! When I go through the Aether portal, I load into the dimension and then get teleported away from my portal, I presume it's because the mods assuming i'm creating a new world and is teleporting me where a village would normally be. 

thank you for reading.

**Comment by ricksouth** [comment]
I've tested it in my dev environment, and looked through their source code. Village Spawn Point is not the problem in this case, hope you find the solution elsewhere. Thanks for giving the mod a try though!
