### ISSUE TITLE
Where the 🅱's is the "collective" mod‽‽‽

### ISSUE THREAD

**Issue by MCAlexisYT** [ricksouth/serilum-mc-mods#773]
I wanted a hassle-free way to enchant my gear to ridiculous levels to test out a physics mod, but **W H Y  D O  I  H A V E  T O  H U N T  F O R  A N  U N L I N K E D M O D**
![W H Y](https://user-images.githubusercontent.com/78766083/141657057-86997313-8175-4a4e-97ed-2ccebae8408e.PNG)

**Comment by ricksouth** [comment]
It's not unlinked. Read the description or download via the CurseForge launcher.

**Comment by ricksouth** [comment]
https://curseforge.com/minecraft/mc-mods/enchanting-commands
https://curseforge.com/minecraft/mc-mods/collective

**Comment by MCAlexisYT** [comment]
I didn't see the link 😂

**Comment by MCAlexisYT** [comment]
oof...
