### ISSUE TITLE
command permissions

### ISSUE THREAD

**Issue by AjdamkoCz1** [ricksouth/serilum-mc-mods#774]
## **Information**

Modloader: Forge 
 1.12.2
Environment:  Multiplayer

Mod name: starter kit
Mod version: latest for 1.12.2

## **Question**
what is the permission for command /starterkit set ? im using luck perms plugin so i need to give perms to myself if i want ot use this mod thanks

**Comment by ricksouth** [comment]
Currently you just need cheat-access or be an operator (/op). There are no permissions available, unless there is an OP permission I'm not sure. I can take a look at it to see if I can add compatibility. Thanks for giving the mod a try!

You can also create the starterkit in singleplayer and copy over the config file.
