### ISSUE TITLE
Collective (Fabric) Crash

### ISSUE THREAD

**Issue by efffauw** [ricksouth/serilum-mc-mods#775]
Minecraft version: 1.17.1
Modloader: Fabric
Fabric loader version: 0.11.7
Environment: Singleplayer

Mod name: Collective (Fabric)
Mod version: 1.62

---- Minecraft Crash Report ----
// Why did you do that?

Time: 11/15/21, 6:40 PM
Description: Exception ticking world

java.lang.AbstractMethodError: Receiver class com.natamus.conduitspreventdrowned.Main$$Lambda$4874/0x0000000800d8d090 does not define or inherit an implementation of the resolved method 'abstract boolean onMobCheckSpawn(net.minecraft.class_1308, net.minecraft.class_3218, net.minecraft.class_2338, net.minecraft.class_3730)' of interface com.natamus.collective_fabric.fabric.callbacks.CollectiveSpawnEvents$Mob_Check_Spawn.
	at com.natamus.collective_fabric.fabric.callbacks.CollectiveSpawnEvents.lambda$static$0(CollectiveSpawnEvents.java:15)
	at net.minecraft.world.SpawnHelper.localvar$dfk000$NaturalSpawner_spawnCategoryForPosition(SpawnHelper:1622)
	at net.minecraft.world.SpawnHelper.spawnEntitiesInChunk(SpawnHelper:271)
	at net.minecraft.world.SpawnHelper.spawnEntitiesInChunk(SpawnHelper:199)
	at net.minecraft.world.SpawnHelper.spawn(SpawnHelper:187)
	at net.minecraft.server.world.ServerChunkManager.method_20801(ServerChunkManager:368)
	at java.util.ArrayList.forEach(ArrayList.java:1511)
	at net.minecraft.server.world.ServerChunkManager.tickChunks(ServerChunkManager:355)
	at net.minecraft.server.world.ServerChunkManager.tick(ServerChunkManager:324)
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld:372)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:891)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:831)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer:96)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:270)
	at java.lang.Thread.run(Thread.java:831)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.natamus.collective_fabric.fabric.callbacks.CollectiveSpawnEvents.lambda$static$0(CollectiveSpawnEvents.java:15)
	at net.minecraft.class_1948.localvar$dfk000$NaturalSpawner_spawnCategoryForPosition(class_1948.java:1622)
	at net.minecraft.class_1948.method_24930(class_1948.java:271)
	at net.minecraft.class_1948.method_8663(class_1948.java:199)
	at net.minecraft.class_1948.method_27821(class_1948.java:187)
	at net.minecraft.class_3215.method_20801(class_3215.java:368)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at net.minecraft.class_3215.method_14161(class_3215.java:355)
	at net.minecraft.class_3215.method_12127(class_3215.java:324)
	at net.minecraft.class_3218.method_18765(class_3218.java:372)

-- Affected level --
Details:
	All players: 1 total; [class_3222['Werlitra4446'/629, l='ServerLevel[Survival Main]', x=-15.94, y=68.25, z=184.70]]
	Chunk stats: 2025
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,64,112), Section: (at 0,0,0 in 0,4,7; chunk contains blocks 0,0,112 to 15,255,127), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 22481 game time, 33785 day time
	Level name: Survival Main
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 49876 (now: false), thunder time: 67054 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:891)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831)
	at net.minecraft.class_1132.method_3748(class_1132.java:96)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:831)

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2254688192 bytes (2150 MiB) / 4194304000 bytes (4000 MiB) up to 4194304000 bytes (4000 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx  
	Identifier: AuthenticAMD Family 23 Model 24 Stepping 1
	Microarchitecture: Zen / Zen+
	Frequency (GHz): 2.10
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: AMD Radeon(TM) Vega 8 Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x15d8
	Graphics card #0 versionInfo: DriverVersion=27.20.11044.5003
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 15284.55
	Virtual memory used (MB): 13417.95
	Swap memory total (MB): 9192.94
	Swap memory used (MB): 0.00
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmn128M -Xmx4000M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.4.3
		advancementplaques: Advancement Plaques 1.4.2
		alloy_forgery: Alloy Forgery 2.0.5
		amecsapi: Amecs API 1.1.5+mc21w16a
		animatica: Animatica 0.1+1.17
		antighost: AntiGhost 1.17.1-fabric0.36.1-1.1.4
		appleskin: AppleSkin mc1.17-2.1.3
		aqupdgrizzly: Grizzly Bear mob 1.17-1.2.0
		architectury: Architectury 2.6.35
		autoconfig1u: Auto Config v1 Updated 3.2.2
		backslot: BackSlot 1.2.2
		backslotaddon: BackSlot Addon 1.0.7
		balm-fabric: Balm 1.3.0+0
		basicshields: Basic Shields [Fabric] 1.1.0-1.17.1
		betterbeds: Better Beds 1.2.0
		betterdungeons: YUNG's Better Dungeons 1.17-1.0.2
		betterthirdperson: Better Third Person 1.5.0
		bfapi: BFAPI 1.1.11
		blur: Blur (Fabric) 2.4.0
		bottledair-fabric: Bottled Air (Fabric) 1.0
		caelus: Caelus API 0.0.16-1.17
		candlestick: Candlestick 1.1.1
		capes: Capes 1.2.2+1.17
		cardinal-components-base: Cardinal Components API (base) 3.1.1
		cardinal-components-entity: Cardinal Components API (entities) 3.1.1
		cardinal-components-item: Cardinal Components API (items) 3.0.0-nightly.1.17-pre2
		carrier: Carrier 1.8.1
		cavebiomes: Cave Biomes 0.6.3
		cem: Custom Entity Models 0.6.2
		citresewn: CITResewn 0.8.1
		cleancut: CleanCut 1.17-4.0-fabric
		clear-skies: Clear Skies 1.5.70
		cloth-api: Cloth API 2.0.54
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config2: Cloth Config v5 5.1.40
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		coat: Coat 1.0.0-beta.12
		collective-fabric: Collective (Fabric) 1.62
		colormatic: Colormatic 2.3.0+mc.1.17.1
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_toml: toml 3.6.3
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		companion_bats: Companion Bats 1.18.4
		conduitspreventdrowned-fabric: Conduits Prevent Drowned (Fabric) 1.4
		connectiblechains: Connectible Chains 1.2.3
		continuity: Continuity 1.0.2+1.17
		copperequipment: Copper Equipment 1.7
		cosmetica: Cosmetica 0.2.1
		couplings: Couplings 1.5.0+1.17
		cozy_camping: Cozy Camping 1.0.0-1.17
		crawl: Crawl 0.9.3
		crowdin-translate: CrowdinTranslate 1.3+1.17
		cullleaves: Cull Leaves 2.3.2
		cursormod: Custom Cursor Mod 1.3.0
		custom-fog: Custom Fog 2.0.0
		customportalapi: Custom Portal Api 0.0.1-beta45-1.17
		cyanide: Cyanide (Fabric) 1.2.1
		darkpaintings: Dark Paintings 4.0.2
		dawn: Dawn API 2.0.6
		deathknell: Example Mod 1.0.1
		deathlog: DeathLog 0.2.1
		ditn: Deep In The Night 0.1.2
		doublejump: Double Jump Mod 1.0.1+mc1.17
		dsurround: §6Dynamic Surroundings§r: §eFabric Edition 0.0.4
		dynamicfps: Dynamic FPS 2.0.6
		eatinganimationid: Eating Animation 1.2
		elytratrinket: Elytra Trinket 2.0.1-1.17
		emeraldextendedfabric: EmeraldExtendedFabric 1.0
		enchant_giver: Enchant Giver 1.1.0
		enchantmentdescriptions: Enchantment Descriptions 4.0.1
		enderscape: Enderscape 0.1.1
		endgoblintraders: End Goblin Traders 1.2.1
		entityculling: EntityCulling-Fabric 1.3.3
		extractpoison-fabric: Extract Poison (Fabric) 1.5
		fab: Foodables 1.1.0
		fabric: Fabric API 0.41.3+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+cbda931818
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.1+ffbe6d8f18
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+cbda931818
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.0+cbda931818
		fabric-copper-golem: Copper Golem 1.0.1+1.17.1
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.12+ffbe6d8f18
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.3.0+57bef5a318
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.10+fc40aa9d18
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+cbda931818
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b4463d5
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.0+ef17126d18
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+cbda931818
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-language-kotlin: Fabric Language Kotlin 1.6.5+kotlin.1.5.31
		fabric-language-scala: Fabric Language Scala 1.1.0+scala.2.13.6
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b44633d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.13+cbda931818
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afad5
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab6121d5
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.12+81e15a8918
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+cbda931818
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+cbda931818
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.4+7931163218
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446313
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.14+4658223018
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.5+7931163218
		fabric-rendering-v1: Fabric Rendering (v1) 1.9.0+7931163218
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+198a96213d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+cbda931818
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.1+81e15a8918
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab6121d5
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.4.1+ffbe6d8f18
		fabricloader: Fabric Loader 0.11.7
		fabricshieldlib: Fabric Shield Lib 1.4.5+1.17
		fabricsit: FabricSit 1.6.4
		fabrishot: Fabrishot 1.5.1
		fallingleaves: Falling Leaves 1.7.4+1.17.1
		fallingtree: FallingTree 2.14.3
		farmersdelight: Farmer's Delight 1.17.1-0.1.2
		ferritecore: FerriteCore 3.0.3
		fiber: fiber 0.23.0-2
		fluidtank: Fluid Tank 17.1.3-fabric
		fractalportals: FractalPortals 1.2.0
		geckolib3: Geckolib 3.0.16
		gildedarmor: Gilded Armor 1.3.1+fabric-1.17.1
		gobber2: Gobber2 2.4.58
		goblintraders: Goblin Traders 1.2.0
		harvest_scythes: Harvest Scythes 2.0.6
		healingcampfire-fabric: Healing Campfire (Fabric) 3.3
		hellish-materials: Hellish Materials 0.13.1
		hydrogen: Hydrogen 0.3
		iceberg: Iceberg 1.0.23
		illuminations: Illuminations 1.10
		imperishableitems: Imperishable Items 1.1.2-mc1.17
		indium: Indium 1.0.0+mc1.17.1
		inmis: Inmis 2.3.2-1.17.1
		inspecio: Inspecio 1.1.0+1.17
		inventorytotem-fabric: Inventory Totem (Fabric) 1.5
		iris: Iris 1.1.2+build.9
		itemmodelfix: Item Model Fix 1.0.2+1.17
		java: OpenJDK 64-Bit Server VM 16
		jumpoverfences: JumpOverFences 1.16-0.0.3
		kirin: Kirin UI 1.9.1
		krypton: Krypton 0.1.4
		lambdabettergrass: LambdaBetterGrass 1.2.1+1.17
		lambdynlights: LambDynamicLights 2.0.2+1.17
		lazydfu: LazyDFU 0.1.2
		libblockattributes: LibBlockAttributes 0.9.2
		libblockattributes_core: LibBlockAttributes (Core) 0.9.2
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.9.2
		libblockattributes_items: LibBlockAttributes (Items) 0.9.2
		libcd: LibCapableData 3.0.3+1.16.3
		libzoomer: LibZoomer 0.2.1+1.17
		lithium: Lithium 0.7.4
		lovely_snails: Lovely Snails 1.0.3+1.17
		mavm: More Axolotl Variants Mod 1.0.5
		maybe-data: Maybe data 1.0.1-1.17
		midnightlib: MidnightLib 0.3.0
		minecraft: Minecraft 1.17.1
		mining_dims: Mining Dimensions 1.1.13
		mm: Manningham Mills 2.3
		mo_glass: Mo Glass 1.5-MC1.17.1
		modify-drops-api: Modify Drops API 0.3.2
		modmenu: Mod Menu 2.0.14
		morebannerfeatures: More Banner Features 1.0.9
		morevillagers-fabric: MoreVillagersFabric 2.1.1-SNAPSHOT
		morevillagesmod: More Villages Mod 1.0.0
		mostructures: Mo' Structures 1.2.1-1.17
		mythicmetals: Mythic Metals 0.10.0
		nauticality: Nauticality 0.1.2
		notenoughanimations: NotEnoughAnimations 1.3.3
		notenoughcrashes: Not Enough Crashes 3.7.2+1.17.1
		npcvariety: NPC Variety 2.2.0
		observed: Observed 1.2.1
		okzoomer: Ok Zoomer 5.0.0-beta.2+1.17
		omega-config: OmegaConfig 1.0.8
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_codehaus_groovy_groovy: groovy 3.0.8
		org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.8
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.0
		org_openjdk_nashorn_nashorn-core: nashorn-core 15.3
		owo: oωo 0.3.0
		oxidized: Oxidized 1.4.0
		packet_tweaker: Packet Tweaker 0.2.0+1.17.1
		paperdoll: PaperDoll 1.0.0-mc1.17.1
		particlerain: Particle Rain 1.5.0
		perorate: Perorate 1.2.0
		pling: Pling 1.4.0
		presencefootsteps: Presence Footsteps r32-1.17-rc1
		promenade: Promenade 2.1.2
		pugh_lib: Pugh Lib ${version}
		pugh_tools: Pugh Tools ${version}
		quickspyglasser: Quick Spyglasser 0.3.0
		rare-ice: Rare Ice 0.3.0
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		reeses-sodium-options: Reese's Sodium Options 1.2.0
		rocks: This Rocks! 1.5.1
		roughlyenoughitems: Roughly Enough Items 6.1.329
		satin: Satin 1.6.4
		scorch: Scorch 1.1.2
		shwfox: Shadew's Foxes 1.1+fabric
		silkspawners: SilkSpawners 1.0.2
		simplyimprovedterrain: Simply Improved Terrain 0.4.0.3-Fabric-1.17
		skinlayers: 3d Skin Layers 1.2.1
		slight-gui-modifications: 'Slight' GUI Modifications 2.0.2
		smoothboot: Smooth Boot 1.16.5-1.6.0
		smoothscrollingeverywhere: Smooth Scrolling Everywhere 3.0.3-unstable
		snowballsfreezemobs-fabric: Snowballs Freeze Mobs (Fabric) 1.5
		snowundertrees: Snow Under Trees 1.0.0
		sodium: Sodium 0.3.2+IRIS2-build.9
		sodium-extra: Sodium Extra 0.3.5
		spruceui: SpruceUI 3.3.0+1.17
		squirrels: Squirrels 1.2.0-1.17
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		strawdummy: Straw Dummy 1.5.0
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.4
		terrarianslimes: Terrarian Slimes 1.1-BETA+1.17
		thonkutil: ThonkUtil 1.2
		toolstats: Tool Stats 2.0.1
		torohealth: ToroHealth Damage Indicators 1.17.1-fabric-12
		transliterationlib: TRansliterationLib 1.2.2
		trident_return: TridentReturn 1.2.4
		trinketofundying: Trinket of Undying 2.0.0-1.17
		trinkets: Trinkets 3.0.4
		trinketshulkerboxes: Trinket Shulker Boxes 2.0.0-1.17
		tweed4_annotated: tweed4_annotated 1.2.0
		tweed4_base: tweed4_base 1.3.1
		tweed4_data: tweed4_data 1.2.0
		tweed4_data_hjson: tweed4_data_hjson 1.1.0
		tweed4_tailor_coat: tweed4_tailor_coat 1.0.1
		tweed4_tailor_screen: tweed4_tailor_screen 1.0.1
		vanillaplusbiomes: Vanilla Plus Biomes 0.3.2
		villagernames: Villager Names 2.0.0
		visuality: Visuality 0.3.0
		visualoverhaul: VisualOverhaul 3.3.0
		wandering_collector: Wandering Collector 1.0.3+mc1.17
		waveycapes: WaveyCapes 1.0.4
		waystones: Waystones 8.1.1+0
		weaponthrow: Weapon Throw 1.17.1-1.4
		wfw: Warhammer Fantasy Weapons 0.1.3-1.17.1
		woods_and_mires: Woods and Mires 1.1.1+1.17
		yungsapi: YUNG's API 1.17-Fabric-19
	Player Count: 1 / 8; [class_3222['Werlitra4446'/629, l='ServerLevel[Survival Main]', x=-15.94, y=68.25, z=184.70]]
	Data Packs: vanilla, fabric-copper-golem/copper_golem, Fabric Mods
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'
	Suspected Mods: Collective (Fabric) (collective-fabric)

**Comment by ricksouth** [comment]
Thanks for opening the bug report! This has been fixed in version 1.5 of the mod. Sorry for the inconvenience.

https://www.curseforge.com/minecraft/mc-mods/conduits-prevent-drowned-fabric/files/all
