### ISSUE TITLE
Kelp Fertilizer only works on grass

### ISSUE THREAD

**Issue by Gitte96** [ricksouth/serilum-mc-mods#776]
## **Information**
Minecraft version: 1.17.1
Modloader: Fabric
Fabric loader version: 0.11.6-1.17.1
Environment: Singleplayer

Mod name: Kelp Fertilizer
Mod version: kelpfertilizer-fabric_1.17.x-1.7.jar

## **Description**
Hey.
The Kelp Fertilizer mod only works on growing grass. I can't get it to work on saplings or crops, which is a shame, as I really like the mod.
These are the other types of mods I have installed:

![image](https://user-images.githubusercontent.com/94362763/141768618-14cde91e-8fdc-4be5-9d81-b3e5c0c6e471.png)

I hope I'm just missing something and that you can help me with it :)

Thank you!

- Gitte

**Comment by ricksouth** [comment]
Thanks! I'll take a look at it soon.

**Comment by ricksouth** [comment]
Thanks for opening the bug report and giving the mod a try! I've fixed it in version 1.8 of the mod. You'll need an updated Collective version as well.

https://www.curseforge.com/minecraft/mc-mods/kelp-fertilizer-fabric/files/all
https://www.curseforge.com/minecraft/mc-mods/collective-fabric/files/all

**Comment by Gitte96** [comment]
Thank you so much for the update! It works like a charm now 😄

**Comment by ricksouth** [comment]
Great! No problem :)
