### ISSUE TITLE
Steel Hoe from Simply Steel is incompatible

### ISSUE THREAD

**Issue by Mikzoru** [ricksouth/serilum-mc-mods#778]
Minecraft version: 1.16.5
Modloader: Forge
Forge version: 36.2.4
Environment: Tested in singleplayer, but my modpack is intended for both singleplayer and multiplayer play

Mod name: Hoe Tweaks (Forge) and Simply Steel [Forge]
Mod version: 1.0 and 1.1.0, respectively

Steel Hoe from the Simply Steel (Forge) mod does not work with this mod. Expected result was for it to act the same as the iron hoe or gold hoe, tilling a 5x5 area.
(Also I'm sorry for not tagging this or any of my other issues properly; I can't figure out how to change the labels) :(

**Comment by James103** [comment]
> (Also I'm sorry for not tagging this or any of my other issues properly; I can't figure out how to change the labels)

Labels can only be edited by people with write access to the repository where you have posted the issue.

**Comment by ricksouth** [comment]
Thanks for opening the issue and using the mod! Version 1.1 of Hoe Tweaks adds compatibility for Simply Steel.

https://www.curseforge.com/minecraft/mc-mods/hoe-tweaks/files/all
