### ISSUE TITLE
Infernal Paintings get included in painting cycle pool

### ISSUE THREAD

**Issue by Mikzoru** [ricksouth/serilum-mc-mods#779]
Minecraft version: 1.16.5
Modloader: Forge
Forge version: 36.2.4
Environment: Tested in singleplayer, but my modpack is intended for both singleplayer and multiplayer play

Mod name: Cycle Paintings (Forge) and Infernal Expansion
Mod version: 2.0 and 2.4.0, respectively

The Infernal Painting is a separate item from vanilla Paintings, crafted with 4 blaze rods, 4 sticks, and wool. I wanted to exclude these paintings and the item from my modpack, since I feel like the artwork doesn't fit a vanilla Minecraft style, and they look out of place next to the other paintings that are available. I can simply remove the crafting recipe via CraftTweaker, but unfortunately using Cycle Paintings still allows you to turn a regular painting into an Infernal Painting simply by right-clicking on it enough times.
In the meantime I suppose I can just use a resource pack to change the Infernal Painting's textures to be the same as some vanilla ones, but I hope that someday I can fully remove these paintings from my modpack entirely.

**Comment by ricksouth** [comment]
Thanks for opening the bug report and using the mod! I've added a blacklist feature via the config in version 2.1 of Cycle Paintings. By default the Infernal Expansion paintings are already excluded so you should be good to go by just updating!

https://www.curseforge.com/minecraft/mc-mods/cycle-paintings
