### ISSUE TITLE
What does it mean to "tame" the Killer Rabbit?

### ISSUE THREAD

**Issue by Mikzoru** [ricksouth/serilum-mc-mods#780]
Minecraft version: 1.16.5
Modloader: Forge
Forge version: 36.2.4  OR  Fabric loader version: x.xx.x
Environment: Tested in singleplayer, but my modpack is intended for both singleplayer and multiplayer play

Mod name: Breedable Killer Rabbit (Forge)
Mod version: 1.5

Does "taming" the Killer Bunny with a golden carrot make it a pet that will follow you and fight for you, or does it simply make it act like a regular bunny, becoming passive towards the player?

**Comment by ricksouth** [comment]
It prevents the damage the rabbit does when tamed. It does not add any custom AI though, that's beyond my capabilities currently. So it's just a way to get them into your world, more so as a trophy. Thanks for the interest though!
