### ISSUE TITLE
Bone meal from dispenser not affected

### ISSUE THREAD

**Issue by chimericdream** [ricksouth/serilum-mc-mods#782]
## **Information**
Minecraft version: 1.17.1
Modloader: Fabric
Fabric loader version: 0.11.7
Environment: Singleplayer

Mod name: Random Bone Meal Flowers (Fabric)
Mod version: 1.5

## **Description**
If a dispenser uses bone meal on a grass block, the generated flowers are not randomized as expected.

## **Screenshots**
Bone meal placed by player
![2021-11-17_01 45 55_sm](https://user-images.githubusercontent.com/198075/142158156-8e52816f-54d4-42f4-ab7e-c171f3d1cd75.png)

Bone meal placed by dispenser
![2021-11-17_01 47 09_sm](https://user-images.githubusercontent.com/198075/142158169-0fa14476-4799-4c6e-b333-2b17dc8b0566.png)

**Comment by ricksouth** [comment]
Thanks for letting me know and using the mod! I've fixed it in version 1.7.

https://www.curseforge.com/minecraft/mc-mods/random-bone-meal-flowers-fabric/files/all

**Comment by ricksouth** [comment]
You'll need Collective 3.2 as well.

https://www.curseforge.com/minecraft/mc-mods/collective-fabric/files
