### ISSUE TITLE
Collective 1.17.1 Unsure what crash is mentioning

### ISSUE THREAD

**Issue by DatrixTHLK** [ricksouth/serilum-mc-mods#787]
## **Information**
Minecraft version: 1.17.1
Modloader: Fabric
Fabric loader version: 0.12.5
Environment: Singleplayer

Mod name: Collective
Mod version: 1.63

## **Description**
I had a crash and  mentioned Collective as the culprit.

## **Crash report**
https://bytebin.lucko.me/Cj0C8BsufR

**Comment by James103** [comment]
Converted the crash to a text file as (almost?) all Pastebin-clone sites eventually expire their pastes
[crash.log](https://github.com/ricksouth/serilum-mc-mods/files/7572044/crash.log)

**Comment by ricksouth** [comment]
I think the problem is with the battletower mod: https://www.curseforge.com/minecraft/mc-mods/draylars-battle-towers

Can you see if the problem still occurs with that removed? I can't see any reference to Collective elsewhere.

**Comment by DatrixTHLK** [comment]
Problem still occurs even without battletowers.

**Comment by ricksouth** [comment]
Do you have another crash log?

**Comment by DatrixTHLK** [comment]
Crash Log File: https://gist.github.com/DatrixTHLK/b25f1884ab16c94b9225178508a6bbb5

**Comment by ricksouth** [comment]
In this case it looks like Immersive Portals is the problem. Collective isn't mentioned

**Comment by DatrixTHLK** [comment]
I'll see if the mod has updated and then let them know of the issue if it still happens.Thanks for the help.

**Comment by ricksouth** [comment]
No problem! Hope you get the pack working.
