### ISSUE TITLE
Collective causes Server Tick Loop Error

### ISSUE THREAD

**Issue by Delfite** [ricksouth/serilum-mc-mods#790]
Minecraft version: 1.12.2
Forge version: 14.23.5.2855
Mod version: collective-1.12.2-2.65.jar

Description: Whenever I try to load into my main LP world the game will freeze on the "Loading Terrain" screen which then leads to the game never loading the world, forcing me to click on the window to crash it.

Crash Report: https://pastebin.com/PzjDPvn4
Latest.log: File size exceeds 512KB limit of pastebin

Here's what the launcher spits at me on crash:
`The game crashed whilst exception in server tick loop
Error: java.lang.NullPointerException: Exception in server tick loop
Exit Code: -805306369`

Guess I'll have to make my 5th survival world now due to all the bugs I've encountered over time, damn and I was just starting to get into the mid-game phase >:(

**Comment by ricksouth** [comment]
Thanks for using some of my mods and opening the issue! I couldn't replicate it but this should be fixed in the 2.66 release of Collective.

https://www.curseforge.com/minecraft/mc-mods/collective/files/all

**Comment by Delfite** [comment]
Nevermind, turns out it still happens :|

**Comment by ricksouth** [comment]
Do you have the new crashlog?

**Comment by Delfite** [comment]
Well no, since it didn't produce one. The launcher just said "An unexpected error occurred" as if I had crashed it using task manager's "End Task" button, which as you would know does not produce a log file. Disabling collective fixed this issue so I'll see if I can't get Forge to produce another log file, should have it in about 10 minutes.
Though something to note is that this crash seems to happen randomly which definitely doesn't help...

**Comment by Delfite** [comment]
Okay so I figured something out. Apparently it's not the Library itself that's the problem it's one of the following mods:

betterspawnercontrol_1.12.2-1.5.jar
despawningeggshatch_1.12.2-2.2.jar
milkallthemobs_1.12.2-1.4.jar
nutritiousmilk_1.12.2-1.8.jar
sleepsooner_1.12.2-2.4.jar
smallernetherportals_1.12.2-1.6.jar
superflatworldnoslimes_1.12.2-1.3.jar
zombievillagersfromspawner_1.12.2-1.4.jar

Seems like a lot but if I had to guess before actually looking into what may have caused it, since it's a Server Tick Loop Error that I had gotten I would assume it's either better spawner control, despawning eggs hatch, or zombie villagers from spawner. Though let's not eliminate the possibility of it being both if not all the mods listed causing a combined issue, this could explain why the crash seems to happen at random.

**Comment by ricksouth** [comment]
Does the problem still occurr when all mods are removed?

**Comment by Delfite** [comment]
No, the game doesn't crash nor does it prevent me from loading my world. Like I said, the Library isn't the problem it's one of the above-mentioned mods.

**Comment by ricksouth** [comment]
It's a compatibility problem with another mod, as I can't reproduce this locally. 1.12 is also no longer supported and I haven't seen others with the same problem before. Not something I can fix at this moment. Thanks for the interest though!
