### ISSUE TITLE
Проблема с API Mojang 

### ISSUE THREAD

**Issue by CommanderRex004** [ricksouth/serilum-mc-mods#793]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.16.5
Modloader: Forge 
Forge version: xx.xx.xx  OR  Fabric loader version: x.xx.x
Environment: Multiplayer

Mod name: Mod Just Player Heads
Mod version: 1.16.5-1.17

## **Question**
Возникает проблема с модом. Пишет, что возникает много запросов и API Mojang не отвечает. Что делать?

**Comment by ricksouth** [comment]
English please.

**Comment by James103** [comment]
From Google Translate:
> There is a problem with the mod. Writes that there are many requests and the Mojang API is not responding. What to do?

**Comment by ricksouth** [comment]
"Mojang API request limitations
The mod uses the UUID -> Profile + Skin/Cape function of the Mojang API. This has quite a strict rate limit: You can request the same profile once per minute, however you can send as many unique requests as you like. This means that sometimes the mod is unable to generate a head if the API limits its generation. The texture caching feature can fix this by saving the head texture data locally."
