### ISSUE TITLE
crash on entity spawn

### ISSUE THREAD

**Issue by TheNimbleNinja** [ricksouth/serilum-mc-mods#797]
## **Information**
Minecraft version: 1.16.5
Modloader: Forge 
Forge version: 3.6.2.9
Environment: Singleplayer

Mod name: Mod Collective
Mod version: 1.16.5-3.7

## **Description**
Hey! This happened..

## **Crash report**
](https://gist.github.com/TheNimbleNinja/298f29a61bc36b8e8e90c4e5068ef203)

**Comment by ricksouth** [comment]
Did it happen on first load or after a while?

**Comment by TheNimbleNinja** [comment]
it happened once on first load i think then after reloading the world

**Comment by TheNimbleNinja** [comment]
i updated the mod thinking it got fixed but it was still in the new update

**Comment by devcshort** [comment]
I think I'm having this same issue on the Fabric version. Causing my server to occasionally crash while traveling

**Comment by ricksouth** [comment]
Thanks for opening the issue, apologies the fix took so long. This has been fixed in version 4.56 of Collective.

https://www.curseforge.com/minecraft/mc-mods/collective/files
https://www.curseforge.com/minecraft/mc-mods/collective-fabric/files
