### ISSUE TITLE
Issue with your website

### ISSUE THREAD

**Issue by K0-RR** [ricksouth/serilum-mc-mods#799]
When hovering over any mod from the last row you can't see its description. I guess the easiest fix would be to expand the height of the footer.

![image](https://user-images.githubusercontent.com/43277609/144130051-4680f6f7-b592-4cc8-95df-f00605699fd2.png)

Also, the Github repository for your website has issues disabled so I'm reporting this here. The website also says you have 136 mods but your CF pages say it's 142 mods.

**Comment by ricksouth** [comment]
Redundant because https://serilum.com/ is the new website. But thanks nonetheless for letting me know!
