### ISSUE TITLE
Possible conflict with Indexed: Ticking Entity Crash

### ISSUE THREAD

**Issue by RubyRezal** [ricksouth/serilum-mc-mods#801]
## **Information**
Minecraft version: 1.18
Modloader: Fabric
Fabric loader version: 0.12.5
Environment: Multiplayer

Mod name: Easy Elytra Takeoff
Mod version: fabric_1.18.x-2.2

## **Description**
Server crashed on takeoff, "ticking entity"

## **Crash report**
[crash-2021-12-01_02.50.21-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/7630603/crash-2021-12-01_02.50.21-server.txt)

**Comment by RubyRezal** [comment]
This issue may be a conflict with (or caused by) Indexed.  Indexed modifies the properties of firework_rocket the player's elytra has  "Slow Burn" or "Quick Flight".

Log spam from Indexed when a player fires an unenchanted bow may indicate Indexed modifies the properties of an arrow even when it isn't necessary, it may also modify firework_rocket even if a player's elytra doesn't have the relevant enchantments.

**Comment by RubyRezal** [comment]
This hasn't happened since I took Indexed out of the modpack.  Should probably change this from a bug report to a mod conflict report.

**Comment by ricksouth** [comment]
Unfortunately 1.12 is no longer supported. I can also not find any reference to my code in the crash log, and as it is a mod imcompatibility there isn't much I can do at the moment. I appreciate you giving the mod a try, and glad it's been fixed since you took out the other mod.
