### ISSUE TITLE
[FABRIC 1.18]The requested compatibility level JAVA_17 could not be set. Level is not supported by the active JRE or ASM version (Java 17.0, ASM 9.0 (ASM10_EXPERIMENTAL))

### ISSUE THREAD

**Issue by SuryaRajgor** [ricksouth/serilum-mc-mods#802]
## **Information**
Minecraft version:1.18
Modloader:  Fabric
Fabric loader version: 0.12.5
Environment:  Multiplayer

Mod name: collective-fabric
Mod version: 1.18.x-3.9

## **Description**
Not Work With 1.18
 also Used this Mod But not work because of dependency
fullbrightnesstoggle-fabric_1.18.x-1.3
dragondropselytra-fabric_1.18.x-1.4
infinitetrading-fabric_1.18.x-2.0.jar
inventorytotem-fabric_1.18.x-1.5
randombonemealflowers-fabric_1.18.x-1.7
treeharvester-fabric_1.18.x-4.1

## **Crash report**
https://pastebin.com/kUebyai5

**Comment by ricksouth** [comment]
1.18 needs Java 17 to run. To you have that installed and is the server using it? Does it run without these mods?

**Comment by SuryaRajgor** [comment]
yes its already on java 17 and the server runs fine with these mods  Also I tried on local (win) and Linux Hosting

![image](https://user-images.githubusercontent.com/9131487/144208276-da70017a-0f2f-494c-9fa2-63e4bb562fdf.png)

**Comment by ricksouth** [comment]
Can you update to Fabric loader 0.12.8?

**Comment by ricksouth** [comment]
Yes seems like the problem has been fixed in Fabric loader 0.12.6, so updating to the latest version will fix the issues you're having. But please let me know if it persists.

**Comment by SuryaRajgor** [comment]
yes, thank you for your help. its work on 0.12.8
