### ISSUE TITLE
[Double doors] mod prevents single doors from working

### ISSUE THREAD

**Issue by CapoFantasma97** [ricksouth/serilum-mc-mods#803]
## **Information**
Minecraft version: 1.17.1
Modloader: Fabric 0.12.8 (also tested with 0.12.5)
Environment: Singleplayer and Multiplayer

Mod name: Double Doors
Mod version: 3.0

## **Description**
This mod prevents single door from opening (they'll close immediately after interacting with them). Double doors instead work as intended.

**Comment by ricksouth** [comment]
Thanks for submitting the bug report and giving the mod a try! I've fixed it in version 3.1 of Double Doors.

https://www.curseforge.com/minecraft/mc-mods/double-doors-fabric/files
