### ISSUE TITLE
Mob Movement

### ISSUE THREAD

**Issue by Quaras3** [ricksouth/serilum-mc-mods#804]
## **Information**
Minecraft version: 1.18
Modloader: Forge
Forge version: 38.0.5
Environment: Singleplayer

Mod name: Zombie Horse Spawn
Mod version: 3.0

## **Description**
Hey! Submitting this as a bug as I am guessing that you didn't intend for the Zombie Horse Rider & it's Horse to move around sideways, or rather slide?

I tried two worlds and it seems to move around in the same way.

Thanks!

**Comment by Quaras3** [comment]
https://we.tl/t-Sgcjoymw6R

Above might help! Just a .gif showing the movement I mention :)

**Comment by James103** [comment]
The GIF is 314 MB. Could you try re-testing, recording, and uploading as an mp4 video instead?

**Comment by Quaras3** [comment]
https://we.tl/t-UoLTF6WXYS

Sorry, hopefully this is better for you.

Again, not really sure if it is a "bug", but after installing the mod it just felt a bit odd/weird to be how the new mob moved and instantly thought that maybe this wasn't intended?

Thanks, :)

**Comment by James103** [comment]
I see the same behavior as shown in the video, in vanilla. To reproduce, run this command:
`/summon zombie_horse ~ ~ ~ {Passengers:[{id:"minecraft:zombie"}]}`

Edit: This occurs with any type of horse or horse-like and any (humanoid) rider.

**Comment by ricksouth** [comment]
This is indeed vanilla behaviour, the mod only spawns the zombie horse and makes the zombie ride it. The zombie wants to go a certain direction, and the horse follows that movement. It does not however face the direction it's going on. Kind of like a player holding the right arrow key to move to the right without facing it.

It looks a bit silly and I appreciate you opening the issue, but I don't consider this a bug. Hope you can live with it in your world! Thanks for giving the mod a try and the video footage.
