### ISSUE TITLE
[1.18 | Double doors (Fabric)] Unable to close/open single door when not sneaking

### ISSUE THREAD

**Issue by Aphyxia** [ricksouth/serilum-mc-mods#805]
## **Information**
Minecraft version: 1.18
Modloader: Fabric
Fabric loader version: 0.12.6
Environment: Singleplayer

Mod name: Double Doors (Fabric)
Mod version: 3.0

## **Description**
I'm unable to close or open single doors. Works when sneaking. Tested with minimal mods and the problem persists.
Video: https://gyazo.com/5ce14dcdb1a98b6081d8e3021faf16a3

**Comment by ricksouth** [comment]
Thanks for submitting the bug report and giving the mod a try! I've fixed it in version 3.1 of Double Doors.

https://www.curseforge.com/minecraft/mc-mods/double-doors-fabric/files
