### ISSUE TITLE
Crash when launching the vanilla experience modpack

### ISSUE THREAD

**Issue by rickarockFR** [ricksouth/serilum-mc-mods#808]
## **Information**
The Vanilla Experience modpack
1.18.0-5.2

## **Description**
When launching, I get an error from the Java Virtual Machine Launcher saying :
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occured. Program will exit.

![image_2021-12-02_180434](https://user-images.githubusercontent.com/69355533/144468879-a7481dd9-4d9e-4ed5-ab49-50f8a47f7a60.png)

**Comment by ricksouth** [comment]
Do you have Java 17 installed? Do other 1.18 instances work?

**Comment by ricksouth** [comment]
This is not a bug with the modpack. You can get more support in the CurseForge Discord: https://discord.gg/USnHMEMW

Thanks for trying out the pack!
