### ISSUE TITLE
Config for extramobdrops

### ISSUE THREAD

**Issue by BishopBone** [ricksouth/serilum-mc-mods#809]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.18
Modloader: Forge
Forge version: 38.0.10
Environment: Singleplayer

Mod name: configurableextramobdrops
Mod version: 1.18.0

## **Question**
What am I doing wrong?

'minecraft:enderman' : '{id:"minecraft:obsidian",Count:1b,tag:{dropchance:.5d}}}',

Is what I have added for giving enderman a 50% dropchance of 1 obsidian.

**Comment by ricksouth** [comment]
Are you using the in-game commands?

**Comment by ricksouth** [comment]
Using the in-game commands is the easiest to add extra drops. The correct syntax is:

`'minecraft:enderman' : '{Count:1b,id:"minecraft:obsidian",tag:{dropchance:0.5d}}',`

**Comment by ricksouth** [comment]
Command (while holding obsidian):
`/cemd addhand enderman 0.5`

Thanks for giving the mod a try! :)
