### ISSUE TITLE
Any way to see villager's name only when I look him ?

### ISSUE THREAD

**Issue by Axelouuu-dev** [ricksouth/serilum-mc-mods#811]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.16.5
Modloader: Forge
Forge version: 36.2.4
Environment: Multiplayer

Mod name: Villager name
Mod version: 3.3

## **Question**
Is there any way to only see villagers names when I look right at them ?

**Comment by ricksouth** [comment]
Aren't they already? Or do you have another mod installed that changes it? It gives them a name, like giving a nametag to an entity.

**Comment by Axelouuu-dev** [comment]
I installed the mod only on server, could it come from that ?

**Comment by ricksouth** [comment]
No that should be fine. Can you take a screenshot?

**Comment by Axelouuu-dev** [comment]
Yep !

![villagersname](https://user-images.githubusercontent.com/19538750/144635665-c35a5cd5-9321-4048-934e-3dd15459115f.png)

I remeber I've installed Name Pain Mod. It display in red the name of player and mob when his health is not full

**Comment by ricksouth** [comment]
Yea that's not vanilla behaviour, it's another mod doing that to the names. You can probably disable it in a config, maybe check the name pain mod? Or see if it's not happening when removed

**Comment by Axelouuu-dev** [comment]
Oh yes you're right !
It went from Name Pain.

Thank you and sorry for the inconvenience :')

**Comment by ricksouth** [comment]
No problem, glad you got it sorted! Thanks for giving the mod a try.
