### ISSUE TITLE
Error With config

### ISSUE THREAD

**Issue by epicyeeto** [ricksouth/serilum-mc-mods#813]
## **Information**
Minecraft version: 1.18
Modloader: Forge 
Forge version: 38.0.12
Environment: Singleplayer

Mod name: Mod
Mod version: 1.3

## **Description**
So i Edited the desc And the color and then after I edited that it would crash and idk why

## **Crash report**
[crash-2021-12-03_17.31.35-client.txt](https://github.com/ricksouth/serilum-mc-mods/files/7652742/crash-2021-12-03_17.31.35-client.txt)
and here is my Config File

[General]
	#The message players will receive when they join a world for the first time.
	firstJoinMessage = "Welcome to Bruhpak don't forget some great mods like slashblade, xplosives mod, subpocket (infinte storage), rune craft and other mods Always check the rei menu for what to do next
	more mods the more we get into 1.18"
	#The colour of the message. The possible values are; 0: black, 1: dark_blue, 2: dark_green, 3: dark_aqua, 4: dark_red, 5: dark_purple, 6: gold, 7: gray, 8: dark_gray, 9: blue, 10: green, 11: aqua, 12: red, 13: light_purple, 14: yellow, 15: white.
	#Range: 0 ~ 15
	firstJoinMessageTextFormattingColourIndex = 3

**Comment by ricksouth** [comment]
You can't have the newline after "what to do next", removing that should fix it,

**Comment by James103** [comment]
Alternatively, replace the real newline with a `\n`, so that the text reads:
```
firstJoinMessage = "Welcome to Bruhpak don't forget some great mods like slashblade, xplosives mod, subpocket (infinte storage), rune craft and other mods Always check the rei menu for what to do next\nmore mods the more we get into 1.18"
```

**Comment by ricksouth** [comment]
> Alternatively, replace the real newline with a `\n`, so that the text reads:
> 
> ```
> firstJoinMessage = "Welcome to Bruhpak don't forget some great mods like slashblade, xplosives mod, subpocket (infinte storage), rune craft and other mods Always check the rei menu for what to do next\nmore mods the more we get into 1.18"
> ```

Hmm not sure if the mod parses that correctly though :P

**Comment by ricksouth** [comment]
[General]
#The message players will receive when they join a world for the first time.
firstJoinMessage = "Welcome to Bruhpak don't forget some great mods like slashblade, xplosives mod, subpocket (infinte storage), rune craft and other mods Always check the rei menu for what to do next. more mods the more we get into 1.18"
#The colour of the message. The possible values are; 0: black, 1: dark_blue, 2: dark_green, 3: dark_aqua, 4: dark_red, 5: dark_purple, 6: gold, 7: gray, 8: dark_gray, 9: blue, 10: green, 11: aqua, 12: red, 13: light_purple, 14: yellow, 15: white.
#Range: 0 ~ 15
firstJoinMessageTextFormattingColourIndex = 3

**Comment by epicyeeto** [comment]
thanks that fixed it!
