### ISSUE TITLE
Crash with latest Collective 3.12

### ISSUE THREAD

**Issue by GhostRiderGrey** [ricksouth/serilum-mc-mods#814]
## **Information**
Minecraft version: 1.18
Modloader: Fabric
Fabric loader version: 0.12.8
Environment: Singleplayer / Multiplayer

Mod name: Collective
Mod version: collective-fabric-1.18.x-3.12

## **Description**
Serilum, hate to be the bearer of bad news (again!).  Updated to your latest version of Collective and am getting the following server crash (see log attached).  Reverting to Collective 3.9 allows the server to start.  Apologies, and thanks!

## **Crash report**
If available.
[latest.log](https://github.com/ricksouth/serilum-mc-mods/files/7653105/latest.log)

**Comment by ricksouth** [comment]
Not at all Grey, appreciate you letting me know! I thought I fixed a warning but apparently just made it worse ;)

Should be resolved in Collective 3.13. Thanks!

https://www.curseforge.com/minecraft/mc-mods/collective-fabric/files/all
