### ISSUE TITLE
Refuses to create new world in singleplayer

### ISSUE THREAD

**Issue by BaccarWozat** [ricksouth/serilum-mc-mods#816]
## **Information**
Minecraft version: 1.18
Modloader: Fabric
Fabric loader version: 0.12.8
Environment: Singleplayer

Mod name: Collective (Fabric)
Mod version: 3.12

## **Description**
Attempting to start a new world, or load an existing one in singleplayer, causes the following:

![image](https://user-images.githubusercontent.com/8357501/144700303-2b0b495d-68bf-44d6-8fde-ef707f5f72c9.png)

Clicking on "Safe Mode" does nothing. 
If click on Datapacks when creating world, when clicking on Done it crashes (see below).
Game works properly when downgraded to Collective 3.9.

Other mods loaded:
Better Recipe Book 1.5.2
Cloth Config v6 6.0.42
Crawl 0.10.0
Fabric API 0.44.0
ModMenu 3.0.0
WI Zoom 1.3
WTHIT 4.3.0

## **Crash report**
(https://paste.ee/p/GJJU1)

**Comment by ricksouth** [comment]
Thanks for letting me know and using the mod! I've fixed it in version 3.13 of Collective.

https://www.curseforge.com/minecraft/mc-mods/collective-fabric/files/all
