### ISSUE TITLE
Just mob heads and custom npcs mobs

### ISSUE THREAD

**Issue by TyrusJames** [ricksouth/serilum-mc-mods#817]
Minecraft version: 1.12.2
Forge
Environment: Singleplayer / Multiplayer
Mod name: just mob heads forge
Mod version: the 1.12.2 one
## **Question**
Can you get the mob heads from the mod "custom npcs" mobs that i create?

**Comment by ricksouth** [comment]
At this moment only vanilla mobs drop their head. I did work on a custom head drop feature but it's currently not implemented. Thanks for the interest though!
