### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Daniels451** [ricksouth/serilum-mc-mods#819]
## **Information**
Minecraft version: 1.18.
Modloader: Fabric
Fabric loader version: 0.12.8
Environment: Singleplayer

Mod name: Infinite Trading
Mod version: 2.0

## **Description**
Hey! I traded sticks to a villager. After some time his price was 64 sticks, but game was showing that his price is 31 sticks.

**Comment by James103** [comment]
1. Can you please make sure that you are actually using Infinite Trading version 2.0 for Fabric?
2. Can you please post the output from the following command: `/execute as @e[type=villager] run data get entity @s`

**Comment by Daniels451** [comment]
![image](https://user-images.githubusercontent.com/78527004/144751054-6ca87abe-942d-482c-9461-de13e23de7eb.png)

**Comment by James103** [comment]
That doesn't show the important information.
Can you please close the game and attach your instance's `.minecraft/logs/latest.log`? (You can always restart the game to keep testing; just make sure you copy the latest.log before doing so)

**Comment by Daniels451** [comment]
[latest.log](https://github.com/ricksouth/serilum-mc-mods/files/7656102/latest.log)

**Comment by James103** [comment]
> After some time his price was 64 sticks

That might be a bug (possibly a desync).

> but game was showing that his price is 31 sticks

This is likely correct as the default price is 32 sticks per emerald and you must have traded some sticks or other items to that same villager recently.
