### ISSUE TITLE
Request: End Portal Recipe for Fabric?

### ISSUE THREAD

**Issue by Nekkok** [ricksouth/serilum-mc-mods#820]
Just like that, I think Fabric would benefit so much to have this awesome mod. Sure a posible stupid request, but I've seen every mod updated to last 1.18 version, and it is strange this one not.

Minecraft version: 1.18.xx
Modloader: Fabric
Fabric loader version: 0.12.8
Environment: Singleplayer / Multiplayer

Mod name: End Portal Recipe

**Comment by ricksouth** [comment]
It's been a while, but a fabric version has been released now. Appreciate the intererest!

https://www.curseforge.com/minecraft/mc-mods/end-portal-recipe-fabric/files
