### ISSUE TITLE
Bulk Download for 1.18

### ISSUE THREAD

**Issue by Modeeves** [ricksouth/serilum-mc-mods#822]
## **Information**
Minecraft version: 1.18
Modloader: Forge

## **Question**
Hi, there! I wanted to download all of your mods in a few clicks for 1.18, but it seems like it isn't available yet on your website when I try to bulk download it. When will it be available?

Thanks!!!

**Comment by ricksouth** [comment]
Should be available now! :) Thanks for using it!
