### ISSUE TITLE
Tree Harvester break block speed config feature

### ISSUE THREAD

**Issue by chrisgates301** [ricksouth/serilum-mc-mods#823]
## **Information**
Minecraft version: 1.16.5
Modloader: Forge
Forge version: Latest
Environment: Singleplayer

Mod name: Tree Harvester
Mod version: Latest for 1.16.5

Chopping down a tree with increase exhaustion per harvested block enabled does not increase the time it takes to chop it down like it should

## **Crash report**
If available.

**Comment by ricksouth** [comment]
That's not how the exhaustion works. Exhaustion is basically how often you need to eat after an action. How fast the hunger bar depletes.

**Comment by ricksouth** [comment]
I'll leave this as a feature request for a config value of block break speed in a tree.

**Comment by chrisgates301** [comment]
> 

Ahh i see, i must be confusing myself then with other mod probably, just dont remember coz usually i use this mod, it basically added the time it would take to break a log, for every log in the tree, and the sum of all of it would be the time it would take to chop it down, kinda hard to explain but yeah, it would be amazing to have this feature added, thanks for your reply

**Comment by ricksouth** [comment]
Thanks for the suggestion! This has been added in version 5.0 of Tree Harvester. You can change the 'increasedHarvestingTimePerLogModifier' config option to determine the speed.

https://www.curseforge.com/minecraft/mc-mods/tree-harvester/files
