### ISSUE TITLE
1.18  Fab Float converting to interger in config

### ISSUE THREAD

**Issue by itsdinkd** [ricksouth/serilum-mc-mods#826]
This mod, your skeleton horse, and zombie horse mods are converting floats into integers. you put 0.05 down, it will convert to 0. 

![image](https://user-images.githubusercontent.com/35115304/145016467-b97c1aa5-d708-4426-b4a4-4157acc2e88b.png)
that's default.

**Comment by ricksouth** [comment]
They shouldn't, in the code they remain Doubles. Where did you find this information?

**Comment by James103** [comment]
Are you able to reproduce this with the latest versions of the following mods?
* Zombie Horse Spawn
* Skeleton Horse Spawn
* Giant Spawn

If not, this can be closed.

**Comment by itsdinkd** [comment]
I no longer use these mods as serilium conflicted with Blockbot. Thanks
