### ISSUE TITLE
Will it cut down my custom tree?

### ISSUE THREAD

**Issue by doreilly935** [ricksouth/serilum-mc-mods#827]
I am currently making a custom tree, heavily based off this one https://www.youtube.com/watch?v=_qCN1eX2iE4&t=626s&ab_channel=GlitchNOut
I am wondering if i build this tree, and i am destroying something with an axe e.g. a crafting table inside the tree, if i accidently harvest one wooden block will it destroy my whole tree? I have currently put many hours into this project and will be heartbroken if it just disappears in a flash. Also, if it would destroy the tree, i would be very grateful if i could change a setting that would make it not destroy the tree.

Many Thanks, Daniel.

**Comment by ricksouth** [comment]
I think Tree Harvester would indeed think that was a tree if you sneak chop a block. I'll think of a config feature to add which can prevent something like this. Maybe a max amount of blocks? Let me know if you have an idea for it. I'll leave this on as a feature issue
