### ISSUE TITLE
DisFabric functionality issue with Collective

### ISSUE THREAD

**Issue by BaccarWozat** [ricksouth/serilum-mc-mods#828]
## **Information**
Minecraft version: 1.18, 1.18.1
Modloader: Fabric
Fabric loader version: 0.12.8, 0.12.11, 0.12.12
Environment: Multiplayer

Mod name: Collective
Mod version: 3.13, 3.14

## **Description**
When Collective is running alongside discord bridge mod DisFabric [https://www.curseforge.com/minecraft/mc-mods/disfabric](https://www.curseforge.com/minecraft/mc-mods/disfabric), DisFabric will not send any player chat text from the server to the discord, though everything else works (discord to server chat, and join/quit/death/advancement messages).
Confirmed working properly when Collective is removed. Not caused by any of the other Serilum mods as this was also tested without them.
DisFabric does not work in singleplayer so was unable to test with that.
EDIT Dec. 16: Tried and failed with 3.14

Fabric API version 0.44.0
DisFabric version 1.3.5

**Comment by BaccarWozat** [comment]
The solution to my problem has been found in the other issue:
https://github.com/ricksouth/serilum-mc-mods/issues/840#issuecomment-1002927063
No apparent disfunctionalities with Collective mods have manifested yet. Will keep you posted if anything else happens.

**Comment by ricksouth** [comment]
This has been fixed in version 3.20 of Collective. Apologies for the late fix and thanks for opening the issue!

https://www.curseforge.com/minecraft/mc-mods/collective-fabric/files
