### ISSUE TITLE
Village Spawn Point (Forge Mod Loader) Not Working

### ISSUE THREAD

**Issue by h4rrish4wk** [ricksouth/serilum-mc-mods#831]
As mentioned when I contacted over Curse Forge - Village Spawn Point is one of my absolute fave must-have mods. So this has been an issue for a while for me with a mix of mod combinations - in 1.17 it'd spawn me in the overworld jus' above the nearest abandoned Mineshaft although since 1.18 that is not the case - but it doesn't spawn me at a village like I would like NOR at spawn - just random spawn.

I don't know if perhaps its a mod conflict the list of Mods I have is:

1. Slab Machines
2. No More Wandering Trader
3. Double Doors
4. Awesome Flooring
5. Flat Bedrock
6. Villagers Drop Emeralds on Death
7. Areas
8. Snad
9. Superflat World No Slimes
10. Reap Mod
11. Klee Slabs
12. Villager Names
13. Realistic Bees
14. Gravel Miner
15. Clumps
16. Xaero's World Map
17. Just Another Rotten Flesh to Leather mod
18. Comforts
19. Humbling Bundle
20. Curio of Undying
21. Squat Grow
22. Grass Seeds
23. Set World Spawn Point
24. Keep My Soil Tilled
25. Balm
26. Copper Equipment
27. Move Minecarts
28. Cloth Config v4 API (for Forge)
29. Mineral Chance
30. Supplementaries
31. Mo'Blocks
32. Wool Tweaks
33. Selene
34. Weaker Spiderwebs
35. More Villagers
36. No Hostiles Around Campfire
37. Better Spawner Control
38. Tool Swap
39. Inventory Totem
40. Rapid Leaf Decay
41. Edit Sign
42. Zombie Proof Doors
43. Horizontal Glass Panes
44. Village Spawn Point
45. Roughly Enough Items
46. Roughly Enough Items (JEI Stub)
47. What The Hell Is That (Forge)
48. Move Boats
49. Curios API
50. Xaero's Minimap
51. Collective
52. Cycle Paintings
53. Sit
54. Random Village Names
55. Surface Mushrooms
56. Builders Crafts and Additions
57. Better Conduit Placement
58. Starter Kit
59. Sleep Sooner
60. Architectury
61. AppleSkin
62. Name Tag Tweaks
63. Crying Portals
64. Trample Stopper
65. Falling Tree
66. Craftable Horse Armor and Saddle (CHA&S Forge)
67. Smaller Nether Portals
68. Infinite Trading
69. Cosmetic Armor Reworked
70. Vein Mining
71. All Loot Drops

I'm sorry for not providing links but I was pressed for time as I wrote this - some of these are obviously dependents of others (such as all the mods dependant on Collective being there etc). Hope this helps for tracking down any possible conflicts or letting me know if the problem is just my computer.

**Comment by ricksouth** [comment]
Do you have them as a profile in the CurseForge launcher? If so, can you export the modpack as a zip?

**Comment by h4rrish4wk** [comment]
I don't have a profile on launcher but I do have experience copy/pasting to separate drive and then zipping mods folder - zip can be found here: https://www.dropbox.com/s/zcu0g82t2pt8rjh/modspack118.zip?dl=0

**Comment by ricksouth** [comment]
This is a problem with Village Spawn Point and Set World Spawn point. I'll take a look at fixing the incompatibility soon. Thanks for the patience!

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 2.5 of Set World Spawn Point.

https://www.curseforge.com/minecraft/mc-mods/set-world-spawn-point/files
https://www.curseforge.com/minecraft/mc-mods/set-world-spawn-point-fabric/files
