### ISSUE TITLE
[1.18-BUG] Surface Mushrooms causes a crash

### ISSUE THREAD

**Issue by Delfite** [ricksouth/serilum-mc-mods#835]
## **Information**
Minecraft version: 1.18
Modloader: Fabric
Fabric loader version: Fabric-0.12.8
Environment: None

Mod name: Surface Mushrooms
Mod version: surfacemushrooms-fabric_1.18.x-1.0.jar

## **Description**
Hey, my modpack crashes before the loading screen even renders. Pretty cringe bro, not gonna lie!

## **Crash report**
https://pastebin.com/cZug9vay

**Comment by Delfite** [comment]
Gonna report a bug on your OP Permissions Fallback mod. Expect that within a couple minutes.

**Comment by ricksouth** [comment]
Update your Fabric Loader version to above 0.12.5.

**Comment by ricksouth** [comment]
https://fabricmc.net/use/

**Comment by Delfite** [comment]
It is above 0.12.5 wdym
Unless curseforge mis-labeled it which is unlikely

**Comment by ricksouth** [comment]
I think this has to do with a mod incompatibility. Can you export your profile in the app and upload the exporerted zip here?

**Comment by Delfite** [comment]
[Content Pack 1.zip](https://github.com/ricksouth/serilum-mc-mods/files/7691011/Content.Pack.1.zip)

**Comment by ricksouth** [comment]
Thanks, I'll take a look at it. Does the mod work on an empty instance in the CF launcher with just collective/surface mushrooms?

**Comment by Delfite** [comment]
Yes, the mod by itself works fine.

**Comment by Delfite** [comment]
Hey so turns out cardinal components may be what was causing those crashes to happen. I've opened an issue on their github about it: https://github.com/OnyxStudios/Cardinal-Components-API/issues/106
