### ISSUE TITLE
Collective 1.18.1 Crashing; Error initialising mixin config serilumforgemod.mixins.json

### ISSUE THREAD

**Issue by Coraline77447** [ricksouth/serilum-mc-mods#839]
Minecraft: 1.18.1
Modloader Version: Forge
Forge version: 39.0.0  
Environment: Singleplayer

Mod name: Collective
Mod version: 1.18.1-3.8

Description: Collective 1.18.1 is crashing in 1.18.1 in early mod loading. In the main thread of: serilumforgemod.mixins.json
Also to see if Collective was the cause of this was by taking out all of your other mods (for 1.18.1 btw even tho I can load 1.18 mods still) and the same thing happened like the first time that it happened when I was testing if I can still load 1.18 mods in forge 1.18.1 39.0.0. 

Even tho I'm actually planning on playing 1.17.1 modded for one of my modded 1.17.1 worlds called Cora World T.F* for my play session today. (till T.F gets ported to 1.18/1.18.1 along with all of the other mods I'm playing with in that world)
(*Twilight Forest)

Crash Report (if Available):  Unfortunately there's no actual crash report that's usually located in the crash reports folder in .minecraft but what the development console shows should be enough but it kept repeating itself the same thing so what I'm going to paste (from pastbin.com btw) is what it was showing the first time around;

https://pastebin.com/KQqmkLBd

**Comment by ricksouth** [comment]
What other mods do you have installed?

**Comment by Coraline77447** [comment]
My last test (which was 5 min ago or so) to see if Collective was causing the game to crash was with just Collective itself.
EDIT: before the last test I was taking out the mods you've updated to 1.18.1 to see if either one of them was the cause of this and none of them were causing this. 
Also I'm using Tlauncher. 
I do have the official launcher but the thing is is that the official launcher uses more resources than im willing to let it use for modded gameplay for more performace and framerates which is why I'm sticking with Tlauncher, less background processes and more framerates and better performace..

**Comment by ricksouth** [comment]
Doesn't seem to crash for me. Are you using the CurseForge launcher or something else?

**Comment by ricksouth** [comment]
You do need the 1.18.1 version in the case for my mods. I can't seem to replicate the crash though

**Comment by Coraline77447** [comment]
I've updated the mods that you've made to 1.18.1 but I don't play with all of them tho, only the ones I like best like Villager Death Messages, really helps me find out where the guard villagers (from guard villagers mod) died to retrieve their items

**Comment by ricksouth** [comment]
Could you try with three fresh 1.18.1 installs with just Collective, Collective and Advancement Screenshot and Collective and Villager Death Messages? Would help a lot to find the issue.

**Comment by ricksouth** [comment]
Downloading Tlauncher gives me a 404 Not Found error so I can't use that myself at the moment.

**Comment by Coraline77447** [comment]
I'll try Collective+Villager Death Messages as of the files I currently have downloaded, then try the fresh ones.

**Comment by ricksouth** [comment]
Thanks!

**Comment by Coraline77447** [comment]
just tried the currently downloaded files and they didn't work..

![Screenshot (39)](https://user-images.githubusercontent.com/72243304/145686393-5785f1b6-fac7-4305-95e6-a76e19dd67f4.png)

So now I'll try the fresh ones to see if they'll work (and where are they precisely? Can't find 'em on curseforge yet to try 'em out..)

**Comment by ricksouth** [comment]
I think it might only be in Tlauncher. Does GD launcher for example do the same thing for you?

https://www.curseforge.com/minecraft/mc-mods/collective
https://www.curseforge.com/minecraft/mc-mods/advancement-screenshot
https://www.curseforge.com/minecraft/mc-mods/villager-death-messages

**Comment by Coraline77447** [comment]
I don't use any other launcher than Tlauncher for modded MC, since I only had to make an acc on their website instead of subscribing to a subscription which I don't like to do, also I haven't used GD Launcher before.
Btw for vanilla MC I do use the official launcher like I did the day 1.18 was released up till I started a semi-modded vanilla world for 1.18 which that world only has quality of life mods and performance enhancement mods like OptiFine.
(But now I do have a fully modded world for 1.18 but won't be playing on that world as often since I'm no finished with my semi-modded 1.18 world yet and still want to experience 1.18 in it's entirety alongside with what I've said above this sentence)

**Comment by ricksouth** [comment]
It's strange as only Advancement Screenshot of these mods contains a "serilumforgemod.mixins.json". So my guess is that it's cached somewhere wrong.

**Comment by ricksouth** [comment]
Does the error happen in an instance you've used before? -- not a fresh one?

**Comment by Coraline77447** [comment]
I don't know if Tlauncher uses different instances. Thought that it does but what I've figured out is that when I launch modded mc on Tlauncher then try to do the same on the official launcher modded and it crashes which causes me to reinstall forge for the official launcher (that was before I decided to stick with Tlauncher for better performace and more framerates for modded). So that tells me that both launchers uses the same instance(s)..

**Comment by ArchieBeepBoop** [comment]
I'm actually using ATLauncher and having this issue as well with collective 1.18.1 and forge 39.0.0.

**Comment by Coraline77447** [comment]
Btw replaying to fresh files part of this convo that i've just figured out that the last upload of Collective for 1.18.1 for me was 11 hours ago, I was either doing other things or was asleep 11 hours ago, so to me that's not fresh uploads of new files.. 
What I think as a fresh upload of new files is like 30 minutes ago or an hour ago, not 11 hours ago. (I'm being honest about what I've said in the sentences above btw)
Also I hope I'm not wasting your time with this problem that I face atm with Collective not working for me...

(I also hope you wouldn't mind if I continue to check if any of my 1.18 mods that I have will work or mostly work in forge 1.18.1 39.0.0, like a mod called Ancient Classes (1.18 currently) works in 1.18.1. Unfortunately AtomicStricker's Infernal Mobs doesn't work in 1.18.1, despite it's file name saying 1.18.1 which I thought that was the game version it was made for but that's actually it's mod version not the game version that it was made for...)

**Comment by Corvus20** [comment]
I'm using GDLauncher, and I am also getting this issue. It isn't limited to any specific launcher it seems.

**Comment by ricksouth** [comment]
Hmm everything besides the CurseForge launcher it seems like. I'm going to take a look, thanks everyone.

**Comment by ricksouth** [comment]
1.18.0 works but 1.18.1 causes issues for everyone?

**Comment by Coraline77447** [comment]
I think that the reason why you (ricksouth) aint' having this issue is cause your code seems to work just fine based off of curseforge launcher which is obvious that not everyone prefers to use that launcher and the fact that that launcher may still be in beta for all I know while other launchers may have been around for years like ATLauncher or the tecnic launcher or FTB launcher (or even Tlauncher), just sayin btw. Also I haven't tested out 1.18 version of your mods yet since I'm doing my testing in alphabetical order (A-Z). Currently on the P's right now while S's are next to test for 1.18.1 compatibility.

**Comment by ricksouth** [comment]
GD Launcher seems to work with 1.18.1 and Collective for me

**Comment by ricksouth** [comment]
Alright so the problem isn't specifically with Collective, just with other mods. I'm working on it

**Comment by unholyv3ng3anc3** [comment]
Crashes Forge 39.0.0 Server as well. Collective works fine until you add another Serilum mod, such as village spawn, giant spawn, random mob effects, etc. Worked fine on 1.18. Have all disabled for now.

**Comment by Coraline77447** [comment]
Btw, I've now just tested out Collective 1.18 along with Villager Death Messages, Replanting Crops, and Villager Names for 1.18 and this is what I'm seeing;

*Mod Collective requires minecraft 1.18*
*Currently, minecraft is 1.18.1*

So trying out 1.18 version of Collective for 1.18.1 doesn't work since you didn't specify to the version checker to have compatibilities with 1.18.1 alongside with 1.18 like how nearly all of my 1.18 mods are compatible with 1.18.1 despite currently being for 1.18. (EDIT: That's mostly cause the authors of those mods have put 1.18.0 and 1.18.1 in their names or somethin since I can't really explain why they're able to load in 1.18.1 even tho they're only made for 1.18...)
Also ricksouth, try testing with just Collective 1.18.1 without any other mods installed, same goes with everyone else who's running into this same issue, it's not the mods that depends on Collective, the problem is coming from Collective itself...

UPDATE!: Ok... Collective 1.18.1-3.8 now seems to work since I managed to get past mod loading...
So the issue is NOT coming from Collective as I had thought but then how can I explain why it wasn't working for me before without any of your other mods installed???...

**Comment by ricksouth** [comment]
> Btw, I've now just tested out Collective 1.18 along with Villager Death Messages, Replanting Crops, and Villager Names for 1.18 and this is what I'm seeing;
> 
> _Mod Collective requires minecraft 1.18_ _Currently, minecraft is 1.18.1_

Yes for 1.18 you need the files with 1.18.0 in the name.

**Comment by ricksouth** [comment]
> Crashes Forge 39.0.0 Server as well. Collective works fine until you add another Serilum mod, such as village spawn, giant spawn, random mob effects, etc. Worked fine on 1.18. Have all disabled for now.

Yep that seems to be it! Going to have to upload new versions for all mods for 1.18.1 unfortunately. But working on it right now.

**Comment by Coraline77447** [comment]
> (I also hope you wouldn't mind if I continue to check if any of my 1.18 mods that I have will work or mostly work in forge 1.18.1 39.0.0, like a mod called Ancient Classes (1.18 currently) works in 1.18.1. Unfortunately AtomicStricker's Infernal Mobs doesn't work in 1.18.1, despite it's file name saying 1.18.1 which I thought that was the game version it was made for but that's actually it's mod version not the game version that it was made for...)

Btw I've finished checking my 1.18 mods that I play/played with in 1.18 even tho it took me like an hour of my time to do but at least now I know that 52 out of 58 mods are compatible with 1.18.1. Minus Serilum mods, Easy Emerald and More (may have an update already but need to check tho), AtomicStricker's Infernal Mobs, *"Global XP"*, *"Macau's Doors"*, *"UnionLib"*, and ItemPhysicLite (currently not using cause of ItemPhysicFull.

*"Already updated to 1.18.1"*

Also, has anyone tried the official launcher to see if the problem accursed on there as well? I would've liked to try that out and see for myself but I'm all tired out from testing out all 58 mods for 1.18.1 compatibility..

**Comment by ricksouth** [comment]
Alright, thanks @Coraline77447. I'm about to upload 1.18.1 versions which will work. Exporting as we speak.

**Comment by Coraline77447** [comment]
Your welcome @ricksouth! Always enjoyed Villager Death Messages and Villager Names the most out of all the others. Like I've said that Villager Death Messages has helped me find where the guard villagers (from Guard Villagers mod) have died to retrieve their gear along with them having names instead of no names apoun death! :)

**Comment by ricksouth** [comment]
Glad you enjoy them! :) Going to upload 140 files now ^^

**Comment by ricksouth** [comment]
All Forge mods have a new 1.18.1 version uploaded, that should fix the issues. Thanks everyone for the research and giving the mods a try. Apologies for the inconvenience!
