### ISSUE TITLE
Styled Chat mod partially not working with Collective

### ISSUE THREAD

**Issue by RawPineapple** [ricksouth/serilum-mc-mods#840]
## **Information**
Minecraft version: 1.18.1
Modloader: Fabric
Fabric loader version: 0.12.11
Environment: Server-side

Mod name: Collective-fabric
Mod version: 3.13

## **Description**
Collective causes "chat" format in [styled chat mod](https://github.com/Patbox/StyledChat) to not work. Removing collective makes it work again.

**Comment by BaccarWozat** [comment]
I bet it's the same or similar problem as https://github.com/ricksouth/serilum-mc-mods/issues/828 and likely any other discord bridge mod.

**Comment by Neubulae** [comment]
Encountered this issue too.

**Comment by Neubulae** [comment]
By removing [this](https://github.com/ricksouth/serilum-mc-mods/blob/master/sources-fabric/Collective%20(Fabric)/src/main/java/com/natamus/collective_fabric/fabric/mixin/ServerGamePacketListenerImplMixin.java) I managed to restore order. I guess this returns too early therefore interrupting other mixins that do things later in the method.

**Comment by BaccarWozat** [comment]
The previous post's solution is confirmed to work on my server. Besides deleting
`ServerGamePacketListenerImplMixin.java`,
the following two files have to have references to that file removed:
`collective_fabric.mixins.json` and `collective-fabric-1.18.x-refmap.json`.

**Comment by ricksouth** [comment]
This has been fixed in version 3.20 of Collective. Apologies for the late fix and thanks for opening the issue!

https://www.curseforge.com/minecraft/mc-mods/collective-fabric/files
