### ISSUE TITLE
Crashes after hitting play

### ISSUE THREAD

**Issue by keleckie** [ricksouth/serilum-mc-mods#841]
## **Information**
Minecraft version: 1.18.1
Modloader: Forge 
Forge version: 39.0.0 
Environment: Singleplayer

Mod name: Configurable Extra Mob Drops 
Mod version: 1.9 (happened with 1.8 too)

## **Description**
Just a few mods on 1.18, started fine with the others including just with Collective but as soon as I enable this mod it crashes after I hit play.

## **Crash report**
Error
Game Crashed
Exit code: 0
![image](https://user-images.githubusercontent.com/66268435/145715938-c10249fb-c36d-4d0d-8a10-f932960eafd0.png)

**Comment by ricksouth** [comment]
Do you have the latest.log and debug.log for me?

**Comment by keleckie** [comment]
Uninstalling and reinstalling worked :) Starts fine now.
