### ISSUE TITLE
[Question] {Starter Kit) Named Items

### ISSUE THREAD

**Issue by ShadoUrufu** [ricksouth/serilum-mc-mods#843]
## **Information**

Minecraft version: 1.18.1
Modloader: Fabric
Fabric loader version: 0.10.2 (I think)
Environment: Singleplayer 

Mod name: Starter Kit

## **Question**
So, I'm just wondering if it's possible to name the items you start with? Ex: A wooden sword called 'Starter Sword' or something like that. 

Idea being for something like a RPG kind of start, where you're given a set of tools at the start of the world, and then set off from your village to search for some dungeons or something like that. specifics not important lol. Just giving the theme idea I had in mind for this question.

**Comment by ricksouth** [comment]
Yep, definitely possible! Just go in-game into creative mode, use an anvil to set the name and other items in your inventory and use the /starterkit set command.

**Comment by ShadoUrufu** [comment]
Alright kool. Thank you very much.
