### ISSUE TITLE
[Suggestion] Increase number of bees that can be in hive

### ISSUE THREAD

**Issue by pkseverance** [ricksouth/serilum-mc-mods#845]
The bees that spawn from the multiplier aren't returning to their hives at night as each hive is capped at 3 in vanilla. Might be nice to have a config for hive size.

Mod: Realistic Bees

**Comment by ricksouth** [comment]
Thanks for the suggestion! I totally agree. I've just released Realistic Bees version 2.5 which adds the feature. By default now 20 bees can enter a hive, but this can be changed in the config.

https://www.curseforge.com/minecraft/mc-mods/realistic-bees/files
