### ISSUE TITLE
Request: Player Tracking Compass for Fabric

### ISSUE THREAD

**Issue by the-unheard** [ricksouth/serilum-mc-mods#846]
[Player Tracking Compass](https://www.curseforge.com/minecraft/mc-mods/player-tracking-compass)

I humbly request for a 1.18.1 Fabric version of this mod. We badly need this on our server.

**Comment by ricksouth** [comment]
There were some issues with the fabric port, but I'll definitely give it another attempt in the future. I appreciate the intererest!

**Comment by V-lpen** [comment]
I would also heavily be interested in a fabric port!
