### ISSUE TITLE
Not working on fabric server

### ISSUE THREAD

**Issue by Carnage15** [ricksouth/serilum-mc-mods#847]
## **Information**
Minecraft version: 1.18.1
Modloader: Fabric
Fabric loader version: 0.12.11
Environment:  Multiplayer

Mod name: Tree Harvester
Mod version: 4.1

## **Description**
Hey! It´s not working in multiplayer and idk why. I have everything in my folder and in server folder.

**Comment by ricksouth** [comment]
I can't seem to replicate the issue. If you can, please try version 4.3. If the problem persists, could you open another issue including your modlist? It might be a compatibility problem. Thanks for giving the mod a try!
