### ISSUE TITLE
Not working on server

### ISSUE THREAD

**Issue by Carnage15** [ricksouth/serilum-mc-mods#850]
## **Information**
Minecraft version: 1.18.1
Modloader: Fabric
Fabric loader version: 0.12.12
Environment: Singleplayer / Multiplayer

Mod name: Tree Harvester
Mod version: 4.1

## **Description**
On server it doesn´t work at all. Trees are acting like in vanilla.

**Comment by jupiter-august** [comment]
Same issue here on forge.

**Comment by ricksouth** [comment]
It works in my development environment. If the problem persists, please open an issue with your complete mod list.

**Comment by Anonymaru-tv** [comment]
Does not work on my forge server..chopping down trees slowly but not instantly
