### ISSUE TITLE
[Collective]Getting "Invalid player data" on singleplayer worlds (Fabric)

### ISSUE THREAD

**Issue by EztraDev** [ricksouth/serilum-mc-mods#855]
Getting "invalid player data" when using Collective with minecraft 1.18.1, latest Fabric API and working without it. Tested with and without other of your mods (those have dependency on Collective). 
Confirmed working with it removed.
Confirmed working joining server (non fabric so I guess it doesn't matter? sry i am totally new to this)
Using vanilla minecraft launcher.
Sry, not that good at troubleshooting minecraft modding myself as I am just starting

Have tested to change Collective version:
collective-fabric-1.18.x-3.14
collective-fabric-1.18.x-3.13

Fabric API:
fabric-api-0.44.0+1.18

Other mods working and in use:
cloth-config-6.1.48-fabric
architectury-3.2.51
Xaeros_Minimap_21.22.5_Fabric_1.18
lambdynamiclights-2.1.0+1.17
WI-Zoom-1.3-MC1.18.1
modmenu-3.0.0
RoughlyEnoughItems-7.1.356
sodium-fabric-mc1.18-0.4.0-alpha5
iris-mc1.18.1-1.1.3
waystones-fabric-1.18.1-9.0.1
balm-fabric-2.3.0+0

**Comment by EztraDev** [comment]
This issue do not only exist on pre-made worlds. It happens when I generate new once too. gives "Invalid player data" and on confirming error sends you to the Multiplayer server tab (although I'm trying to join singleplayer maps)

**Comment by ricksouth** [comment]
This is my fault for not asking it sooner, but I'm going to need crashlogs/debug logs to find the problem. Closing this for now, but if anyone else has the issue please let me know! Apologies for the inconvenience.
