### ISSUE TITLE
Spider webs break when u are in spectator mode

### ISSUE THREAD

**Issue by bozmund** [ricksouth/serilum-mc-mods#861]
## **Information**
Minecraft version: 1.18.1
Modloader: Forge
Forge version: 39.0.7
Environment: Singleplayer

Mod name: Weaker Spiderwebs
Mod version: 2.1

## **Description**
Spider webs break even in spectator mode idk if it s intended

## **Crash report**
If available.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! Apologies it took so long for me to get to. This has been fixed in version 2.7 of Weaker Spiderwebs.

https://www.curseforge.com/minecraft/mc-mods/weaker-spiderwebs
