### ISSUE TITLE
[Fabric / 1.18.1 ] When Breaking Beacon it doesn't return fully the blocks

### ISSUE THREAD

**Issue by kalinzange** [ricksouth/serilum-mc-mods#863]
## **Information**
Minecraft version: 1.18.1
Modloader: Fabric
Fabric loader version: 0.12.12
Environment: SinglePlayer & Multiplayer

Mod name: Mod - Better Beacon Placement
Mod version: 1.4

## **Description**
Hey! Whenever you place a 100 block (or more) into the beacon and break it, it drops less than what was placed.
In my video it shows there's 2 blocks missing after breaking the beacon, there were times in my multiplayer server it didn't return a full stack of emerald blocks.

Video: https://youtu.be/mRQYx7ah5hc

## **Crash report**
N/A

**Comment by ricksouth** [comment]
This has been fixed in the latest version of Better Beacon Placement. Thanks for giving the mod a try!

https://curseforge.com/minecraft/mc-mods/better-beacon-placement/files
