### ISSUE TITLE
Areas & Random Village Names for Fabric?

### ISSUE THREAD

**Issue by chimericdream** [ricksouth/serilum-mc-mods#866]
## **Question**
Pretty much what the title says. I'm curious if the Areas and Random Village Names mods will be ported to Fabric. I see a folder for Areas under the `sources-fabric` folder, but obviously don't know if it is functional yet since you haven't uploaded it to CurseForge.

Thanks, and I hope you get some time to relax over the holidays without users like me annoying you with silly requests. :-)

**Comment by ricksouth** [comment]
I did attempt to port Areas to Fabric, but had some issues in the process. I'll definitely be giving the remaining forge mods that need to be ported a try in the near future. Appreciate the interest!
