### ISSUE TITLE
Mod Effect Persists After Removing

### ISSUE THREAD

**Issue by ChestnutTheOwl** [ricksouth/serilum-mc-mods#867]
## **Information**
Minecraft version: 1.18
Modloader: Forge
Forge version: 38.0.17
Environment: Singleplayer and Multiplayer

Mod name: Tree Harvester
Mod version: Release

## **Description**
After removing Tree Harvester from the modlist, the effect of the mod persists in both singleplayer and in servers. Manually deleting either the jar or configs does not fix this issue either.

**Comment by ricksouth** [comment]
I believe this is a caching issue. Fixed by removing the .fabric folder in the instance root.
