### ISSUE TITLE
World not loading with realistic bees

### ISSUE THREAD

**Issue by FelixRobotics** [ricksouth/serilum-mc-mods#869]
## **Information**
Minecraft version: 1.15.2
Modloader: Forge
Forge version: 31.2.55
Environment: Singleplayer

Mod name: Realistic Bees
Mod version: 2.3

## **Description**
my world stays stuck loading on 100%; i don't know if realistic bees is specifically causing it but when i remove that jar, it loads

## **Crash report**
If available.

**Comment by ricksouth** [comment]
Minecraft 1.15.2 is no longer supported. Thanks for giving the mod a try though!
