### ISSUE TITLE
Underwater Enchanting

### ISSUE THREAD

**Issue by kreezxil** [ricksouth/serilum-mc-mods#870]
I would like to see it ported to Fabric for 1.17.1 or 1.18.1, maybe both. Soon as LimeShulkerBox ports up "You're a Fish" to either of those, I've got a new mod pack in mind that will involve both mods.

**Comment by ricksouth** [comment]
There were some issues with the first attempt to port, but I'll definitely give it another go in the near future. I appreciate the interest!
