### ISSUE TITLE
areas command not showing sign locations

### ISSUE THREAD

**Issue by zhovan8** [ricksouth/serilum-mc-mods#871]
## **Information**
Minecraft version: 1.18.1
Modloader: Forge
Forge version: 39.0.7
Environment: Multiplayer

Mod name: Areas / RandomVillageNames
Mod version: 2.9 / 1.5

## **Description**
There are really two issues, one leading me to the other.
The first one is not really a bug, just kind of inconvenient.
Auto-generated Signs for villages from randomVillageNames is creating signs that are sometimes underground because of all of the cave systems introduced with 1.18. The fact that they are underground is not really a bug. It just makes it annoying to try to find them. Even if I destroy them (like with worldEdit if I cannot find it) they will regenerate again back in the same place, even if I have already placed another sign up on the surface somewhere.
Like I said, not a bug, just a bit annoying. 
When I use the "areas" command to try to find the sign, it comes back and says "there are no area signs around you" even if I am standing directly in front of one that I just created.

Great mod. Several great mods. You are doing awesome work. I just setup a Patron right now to support you. zhovan8 on here and on Patron, but sgt__rainbow on Minecraft.

## **Crash report**
No report as it is not crashing.
![No areas while in front of sign](https://user-images.githubusercontent.com/19777664/147514690-dc5e3df9-6bd1-40bc-af19-6732dd8b1540.png)

**Comment by tungstonminer** [comment]
+1 on this bug.  I'll create a sign, see the notification that I've entered the area, and then immediately run the `/areas` command only to have it tell me there are no areas nearby.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 5.0 of Areas, alongside other bug fixes and QoL features. Apologies it took so long for me to get to.

https://www.curseforge.com/minecraft/mc-mods/areas/files
