### ISSUE TITLE
Giant Spawn hit box is only legs

### ISSUE THREAD

**Issue by LegendaryTot** [ricksouth/serilum-mc-mods#880]
## **Information**
Minecraft version:1.18.1
Modloader: Forge
Forge version: 39.0.9
Environment: Singleplayer

Mod name: Giant Spawn
Mod version: 2.8

## **Description**
The hit box of giants only seems to be their legs. When attacking, or even just looking at them with Jade, anything above the legs is as if it's not there. Makes it not too fun for ranged gear as it's not obvious that only the legs are attackable and not the head or torso.

**Comment by James103** [comment]
This may be caused by vanilla anticheat - you can't hit entities from more than about 6-8 blocks away, but that distance is calculated *to the entity's feet*, not *to the nearest point on the entity's hitbox*.

**Comment by ricksouth** [comment]
![2022-03-06_16 53 23](https://user-images.githubusercontent.com/38502394/156930827-3b631cbb-870c-4eb2-bcd3-aea1f3717e6e.png)

Seems like the hitbox is indeed as it should be. Thanks for giving the mod a try!
