### ISSUE TITLE
Changing the possible colors in the config files for both Random Sheep Colours (Fabric) 1.6 and Random Shulker Colours (Fabric) 1.3 appears to have no effect

### ISSUE THREAD

**Issue by Darkiceflame** [ricksouth/serilum-mc-mods#881]
After making the below changes to these two configs and creating a new world, I still found the corresponding entities in colors outside of the lists in the config.

>{
	// The possible sheep colours which the mod chooses from, divided by a comma.
	"possibleSheepColours": "black,brown,gray,light_gray,white"
}

>{
	// The possible shulker colours which the mod chooses from, divided by a comma.
	"possibleShulkerColours": "normal,black,blue,cyan,gray,light_blue,light_gray,magenta,pink,purple"
}

![2021-12-31_21 04 48](https://user-images.githubusercontent.com/5132968/147858414-6b6d9245-2425-4f00-8ad5-e39b475ba13a.png)
![2022-01-01_12 16 44](https://user-images.githubusercontent.com/5132968/147858416-082183c4-e375-4f83-81e6-b2263a146ccb.png)

**Comment by ricksouth** [comment]
Apologies it took so long for me to get to this. I have it confirmed working, but it does require a restart of the game. I think that might've been the issue. I'll add it to the description on the mod pages to avoid confusion for other users. Thanks for giving the mod a try!
