### ISSUE TITLE
Stack Refill and Tree Harvester not working together...

### ISSUE THREAD

**Issue by mouse0270** [ricksouth/serilum-mc-mods#883]
## **Information**
Minecraft version: 1.18.1
Modloader: Forge 
Forge version: 39.0.9
Environment: Multiplayer

Mod name: Stack Refill and Tree Harvester
Mod version: Stack Refill (2.1) Tree Harvester (4.2)

## **Description**
When using stack refill and tree harvester together, you axe does not get replaced. If I am holding shift and chop down a tree and my axe breaks a new one isn't refilled if it breaks. However if I am not holding shift and my axe breaks, it is replaced.

**Comment by ricksouth** [comment]
Thanks for the opening the issue and giving the mod a try! This has been fixed in version 5.0 of Tree Harvester.

https://www.curseforge.com/minecraft/mc-mods/tree-harvester/files
