### ISSUE TITLE
Throwing Blocks out of Inv, puts same blocks from inv in to off hand.

### ISSUE THREAD

**Issue by EvilEtho** [ricksouth/serilum-mc-mods#885]
## **Information**
Minecraft version: 1.18.1
Modloader: Forge
Forge version: 39.0.9
Environment: Singleplayer / Multiplayer

Mod name: Stack refill
Mod version: 2.1

## **Description**
Lets say you have 3 stacks of Cobble in your Inv, and your want to clear it out. You throw one stack on the ground, Then the mod will take another stack of Cobble and move it to your offhand.

**Comment by benbenlaw** [comment]
https://github.com/benbenlaw/skyopolis-5/issues/13

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! Apologies this took so long for me to get to. This has been fixed in version 3.0 of Stack Refill.

https://www.curseforge.com/minecraft/mc-mods/stack-refill
