### ISSUE TITLE
Clock Icon not changing

### ISSUE THREAD

**Issue by zachsai** [ricksouth/serilum-mc-mods#889]
## **Information**
Minecraft version: 1.18.1
Modloader: Forge 
Forge version: 39.0.9 Forge
Environment: Singleplayer

Mod name: ClockGUI
Mod version: 3.1

## **Description**
The clock icon does not update with the clock in the hotbar, as you can see in this picture
![image](https://user-images.githubusercontent.com/63996164/148459182-48cda605-03ed-4559-ad0a-15e847e1f45d.png)

## **Crash report**
If available.

**Comment by ricksouth** [comment]
![2022-03-06_17 47 34](https://user-images.githubusercontent.com/38502394/156933044-4024e402-1c72-435a-bade-10c4dcf2f7f1.png)

For me it does work. Does it still happen on the latest Forge version?

**Comment by zachsai** [comment]
Quark has a feature that needed to be disabled to fix the issue, you can close the thread :)

**Comment by ricksouth** [comment]
Glad you found it! Which feature had to be disabled?

**Comment by zachsai** [comment]
![image](https://user-images.githubusercontent.com/63996164/157171843-8f712ba0-2032-46ec-ba75-e427703371d4.png)
