### ISSUE TITLE
no name just player head

### ISSUE THREAD

**Issue by wackoamd1** [ricksouth/serilum-mc-mods#890]
## **Information**
Minecraft version: 1.18.1
Modloader: Fabric
Forge version: xx.xx.xx  OR  Fabric loader version: 1.12.2
Environment: Multiplayer

Mod name: just mob heads
Mod version: 5.2

## **Description**
the heads that drop doesnt even have a name on wthit its just player head
before i installed this mod , i had a head on my wall which read player head with a the mob name below it.
now i took it down to compare them but now your mod messed with that one too. they both read just player head now ;-(
since i use the villagernames mod i was hoping your mod would retain the name of the villager , but it doesnt do that , hell it doesnt even retain the standard vanilla name ;-( 

## **Crash report**
If available.

**Comment by ricksouth** [comment]
Apologies for the inconvenience. This has been fixed in version 4.0 of Just Player Heads. Thank you for opening the issue and giving the mod a try!

https://www.curseforge.com/minecraft/mc-mods/just-player-heads/files
