### ISSUE TITLE
Bonemealing causes hang on server, unknown circumstances.

### ISSUE THREAD

**Issue by Canada-LaVearn** [ricksouth/serilum-mc-mods#893]
## **Information**
Minecraft version: 1.18.1
Modloader: Forge
Forge version: 39.0.10
Environment: Multiplayer Server

Mod name: Random Bone Meal Flowers
Mod version: 1.6

## **Description**
A user on my server was bonemealing, and it caused a hang. The incident did not produce a crash report, as the server closed itself after it noticed that a tick took more than 60 seconds. I had changed the blacklist to only contain the wither flower.
I would love to give more info, but I'm not an expert at reading logs...

## **Crash report**
Attached.
[latest.log](https://github.com/ricksouth/serilum-mc-mods/files/7836474/latest.log)

**Comment by James103** [comment]
According to the stack trace, there seems to be some kind of deadlock.

As you are on version 1.18.1, can you please try the following?
1. Run `/perf start` if possible.
2. Press F3+L.
3. Wait 10 seconds.
4. Attach the resulting `debug/profiling/YYYY-MM-DD_HH_MM_SS-[world_name]-1_18_1.zip` files from both the server and the client.

**Comment by Canada-LaVearn** [comment]
Both files are attached
[2022-01-10_21_07_22-world-1_18_1.zip](https://github.com/ricksouth/serilum-mc-mods/files/7841896/2022-01-10_21_07_22-world-1_18_1.zip)
[2022-01-10_16_07_27-Create-ive Cogs-1_18_1.zip](https://github.com/ricksouth/serilum-mc-mods/files/7841898/2022-01-10_16_07_27-Create-ive.Cogs-1_18_1.zip)

**Comment by ricksouth** [comment]
This has been fixed in version 3.0 of Random Bone Meal Flowers. Please let me know if you're still experiencing issues. Thanks for giving the mod a try and opening the issue! Apologies it took so long for me to get to.

https://www.curseforge.com/minecraft/mc-mods/random-bone-meal-flowers/files
