### ISSUE TITLE
Areas Mod causes Corruption of World (at least I think so)

### ISSUE THREAD

**Issue by Alpha-Flyte** [ricksouth/serilum-mc-mods#897]
## **Information**
Minecraft version: 1.18.1
Modloader: Forge
Forge version: 39.0.19
Environment: Singleplayer

Mod name: Areas
Mod version: 2.9

## **Description**
When Areas is installed, the world shows symptoms of corruption (from what I've heard). Entities and mobs do not move and cannot be interacted with, Items thrown do not appear, Skin does not render outer layer. When saving and exiting, game gets stuck on saving world screen, and must be closed using task manager. Issue disappears when Areas is uninstalled/deleted/shoved into a folder to never see the light of day

Tested on Windows 10, Java Edition, Singleplayer, Creative Mode, Tested with other mods installed, Did not run a dedicated test with only Areas and Collective

Other Mods included (which may be the cause of conflict or not):
Quark, Create, Aquaculture, Artifacts, Backpacked, Big Brain, Bonsai trees, Farmer's Delight, JEI, a few other Serilum mods (which work fine), etc. (these are the most major ones)

## **Crash report**
No actual crash report exists, the game simply ceases to respond

**Comment by ricksouth** [comment]
It seems very unlikely that Areas causes this issue. Not sure how it would interact with the problems you've mentioned. But it might be a mod incompatibility. 

Could you export your modpack profile and upload it here?

**Comment by Alpha-Flyte** [comment]
![image](https://user-images.githubusercontent.com/75723066/149443918-f9af9d5e-996d-4922-9156-bd1056ba6fb3.png)
![image](https://user-images.githubusercontent.com/75723066/149443961-841f11ad-0d10-44e0-bb9d-4562703eaad6.png)
![image](https://user-images.githubusercontent.com/75723066/149443990-26918f9d-91eb-468e-b833-82c8ab169a73.png)
![image](https://user-images.githubusercontent.com/75723066/149444012-f3f97cfc-160a-4a47-a675-776eb81e5388.png)
![image](https://user-images.githubusercontent.com/75723066/149444056-2990cc5b-03e8-43e3-9d88-7bbb30e6ec19.png)
![image](https://user-images.githubusercontent.com/75723066/149444078-8f846e93-e155-4a88-8cf5-d4aea8cb25c4.png)

Github is acting weirdly, doesn't want to let me attach a zip, so here are screenshots of all the mods I'm using.

**Comment by ayrus02** [comment]
I've encounter this same problem, but when entering the nether for the first time. The entities on nether are frozing, and I cannot interact with the entity, after about 60 second, I got disconnected from my Forge Minecraft server and the server is crashing. My environment are using Linux as a server with OpenJDK 17. and not running as a SinglePlayer Server.

I've try to disable all the mods I use (about 62 mods) and found out that after I disabled the Areas and RandomVillageNames mod from Serilum, the server can run flawlessly on nether without crashing,

Below I've also attach the Forge Minecraft server crash report.
[crash-2022-02-03_20.08.16-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/7999849/crash-2022-02-03_20.08.16-server.txt)
.

**Comment by plackyfantacky** [comment]
I've experienced similar on 1.18.2 but I got a hunch it might be RandomVillageNames being the one that causes it. 

- With areas_1.18.2-2.9.jar and randomvillagenames_1.18.2-1.6.jar enabled I get lag with mobs moving, block breaking, and chest opening. 
- When I disable both mods, everything runs normal with no issues.
- When I disable just RandomVillageNames, I don't seem to get the long lag spikes I was experiencing, though I do get a fair bit of stutter or frame skipping.

**Comment by thepriz** [comment]
I can confirm that I've experienced what @plackyfantacky experienced with Area and RandomVillageNames. I removed them and the issues were gone. Forge 40.1.0, Areas (Forge) 1.18.2-2.9, Random Village Names (Forge) 1.18.2-1.6

**Comment by ricksouth** [comment]
This has been fixed in the latest release of Random Village Names, together with a complete rewrite. Thanks for opening the issue and apologies for any inconvenience caused!

https://www.curseforge.com/minecraft/mc-mods/random-village-names/files
