### ISSUE TITLE
2 questions actually

### ISSUE THREAD

**Issue by DatrixTHLK** [ricksouth/serilum-mc-mods#900]
## **Information** 
Minecraft version: x1.17.1
Modloader: Fabric
 Fabric loader version: 1.17.1
Environment: Singleplayer

Mod name: Mineral Chance
Mod version: 1.8

## **Question**
Is it normal to get a mineral after breaking every block? In the config there is normally a 1/50 chance to get a mineral. I put in a 5 for chance so I would think that would make it a 5/50 chance to get a mineral.

Also, what is the chance to get coal from breaking blocks? I don't seem to get any from breaking blocks with this mod installed well unless I break cola ore

**Comment by ricksouth** [comment]
For a 5/50 or 1/10 chance you'll need to input 0.1, not 5. At the moment coal does not drop from stone type blocks. Thanks for giving it a try!

**Comment by DatrixTHLK** [comment]
Oh is that why? I see. Thanks for the information!
