### ISSUE TITLE
Please add compatibility with Elytra Trinket for Fabric

### ISSUE THREAD

**Issue by jockrint** [ricksouth/serilum-mc-mods#901]
## **Information**
Mod name: Easy Elytra Takeoff (Fabric)

## **Feature description**
Currently, the Fabric version of Easy Elytra Takeoff does not work with the Elytra Trinket mod, which seems to be the only "Elytra slot" mod available. I think adding this compatibility would be important for Fabric users who don't like/want the functionality of Colytra.

**Comment by ricksouth** [comment]
Thanks for open the issue and giving the mod a try! Version 3.1 of Easy Elytra Takeoff adds support for modded elytra's and trinkets in Fabric. :)

https://www.curseforge.com/minecraft/mc-mods/easy-elytra-takeoff-fabric/files
