### ISSUE TITLE
No Heads from Axolotls

### ISSUE THREAD

**Issue by ShinyRayquaza9923** [ricksouth/serilum-mc-mods#903]
## **Information**
Minecraft version: 1.18.1
Modloader: Forge
Forge version: 39.0.44
Environment: Singleplayer & Multiplayer (Aternos Server)

Mod name: Just Mob Heads
Mod version: 5.3

## **Description**
I wanted an axolotl head so I killed one in survival from the multiplayer world so I checked the config .txt file where we can change the mob specific head drop chance and I don't see any of axolotls. So I checked the curse forge page and I see that it does exist in the mod. Then I tried killing axolotls in single player world both in creative and survival mod with and without looting and still no head drop just EXP. How can I fix this?
I also don't see a setting for the goat and glow squid so I think they have the same problem but I haven't tested.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! Apologies that it took so long. I've just released version 5.4 which fixes the problem.

https://www.curseforge.com/minecraft/mc-mods/just-mob-heads/files
