### ISSUE TITLE
Leaf Decay Speed Config

### ISSUE THREAD

**Issue by ZeldasWetDream** [ricksouth/serilum-mc-mods#905]
## **Information**
Mod name: Tree Harvester

## **Feature description**
Any chance of adding a config option to increase/decrease the decay speed of leaves after felling a tree?

**Comment by ricksouth** [comment]
Thanks for the suggestion! This has been added in version 5.0 of Tree Harvester. You can change the 'amountOfLeavesBrokenPerTick ' config option to determine the speed.

https://www.curseforge.com/minecraft/mc-mods/tree-harvester/files
