### ISSUE TITLE
Non-admin players aren't able to define areas

### ISSUE THREAD

**Issue by tungstonminer** [ricksouth/serilum-mc-mods#907]
## **Information**

Minecraft version: 1.18.1
Modloader: Forge
Forge version: 39.0.40
Environment: Multiplayer

Mod name: Areas
Mod version: 2.9
Mod pack: [Austere Caves](https://github.com/tungstonminer/austere-caves)

## **Description**

As an admin on the server, I could enter: `[Area] 20\nArea Name` and see it successfully create a new area (i.e., the HUD pops up with the "Entering Area Name" message).  However, it doesn't work every time: perhaps 1 in 3 attempts are successful.  However, none of my players has been able to define any areas at all when logged in to the server.  They *are* able to create areas it their own single-player worlds.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 5.0 of Areas, alongside other bug fixes and QoL features. Apologies it took so long for me to get to.

https://www.curseforge.com/minecraft/mc-mods/areas/files
