### ISSUE TITLE
Crash when Kelp is used via Dispenser when Extended Bone Meal is installed

### ISSUE THREAD

**Issue by Dekamir** [ricksouth/serilum-mc-mods#909]
## **Information**
Minecraft version: **1.18.1**
Modloader: **Forge**
Forge version: **38.0.44** 
Environment: **Singleplayer / Multiplayer**

Mod name: **Kelp Fertilizer, Extended Bone Meal**
Mod version: **1.8, 1.5**

## **Description**
When Extended Bone Meal and Kelp Fertilizer are installed at the same time, Dispenser event crashes the server.

![2022-01-24_00 59 14](https://user-images.githubusercontent.com/28929300/150785876-c0eec4e0-4be6-4090-83ea-93a4ca568dd4.png)

## **Crash report**

> [00:55:34] [Server thread/ERROR]: Exception caught during firing event: Cannot invoke "net.minecraft.world.entity.player.Player.m_6144_()" because "player" is null
> 	Index: 1
> 	Listeners:
> 		0: NORMAL
> 		1: ASM: com.natamus.extendedbonemeal.events.ExtendedEvent@41c75abd onBoneMeal(Lnet/minecraftforge/event/entity/player/BonemealEvent;)V
> java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.player.Player.m_6144_()" because "player" is null
> 	at TRANSFORMER/extendedbonemeal@1.5/com.natamus.extendedbonemeal.events.ExtendedEvent.onBoneMeal(ExtendedEvent.java:33)
> 	at net.minecraftforge.eventbus.ASMEventHandler_330_ExtendedEvent_onBoneMeal_BonemealEvent.invoke(.dynamic)
> 	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
> 	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
> 	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
> 	at TRANSFORMER/forge@39.0.19/net.minecraftforge.event.ForgeEventFactory.onApplyBonemeal(ForgeEventFactory.java:379)
> 	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.item.BoneMealItem.applyBonemeal(BoneMealItem.java:67)
> 	at TRANSFORMER/kelpfertilizer@1.8/com.natamus.kelpfertilizer.dispenser.BehaviourKelpDispenser.m_6115_(BehaviourKelpDispenser.java:33)
> 	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.level.block.DispenserBlock.m_5824_(DispenserBlock.java:90)
> 	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.level.block.DispenserBlock.m_7458_(DispenserBlock.java:113)
> 	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60616_(BlockBehaviour.java:675)
> 	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.level.ServerLevel.m_184112_(ServerLevel.java:636)
> 	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.ticks.LevelTicks.m_193272_(LevelTicks.java:215)
> 	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.ticks.LevelTicks.m_193225_(LevelTicks.java:98)
> 	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:269)
> 	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:868)
> 	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:328)
> 	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808)
> 	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668)
> 	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258)
> 	at java.base/java.lang.Thread.run(Thread.java:833)
> 
> [00:55:34] [Server thread/ERROR]: Encountered an unexpected exception
> net.minecraft.ReportedException: Exception ticking world
> 	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:872) ~[server-1.18.1-20211210.034407-srg.jar%23200!:?]
> 	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:328) ~[server-1.18.1-20211210.034407-srg.jar%23200!:?]
> 	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[server-1.18.1-20211210.034407-srg.jar%23200!:?]
> 	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[server-1.18.1-20211210.034407-srg.jar%23200!:?]
> 	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%23200!:?]
> 	at java.lang.Thread.run(Thread.java:833) [?:?]
> Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.player.Player.m_6144_()" because "player" is null
> 	at com.natamus.extendedbonemeal.events.ExtendedEvent.onBoneMeal(ExtendedEvent.java:33) ~[extendedbonemeal_1.18.1-1.5.jar%23104!:1.0]
> 	at net.minecraftforge.eventbus.ASMEventHandler_330_ExtendedEvent_onBoneMeal_BonemealEvent.invoke(.dynamic) ~[?:?]
> 	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!:?]
> 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?]
> 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?]
> 	at net.minecraftforge.event.ForgeEventFactory.onApplyBonemeal(ForgeEventFactory.java:379) ~[forge-1.18.1-39.0.19-universal.jar%23204!:?]
> 	at net.minecraft.world.item.BoneMealItem.applyBonemeal(BoneMealItem.java:67) ~[server-1.18.1-20211210.034407-srg.jar%23200!:?]
> 	at com.natamus.kelpfertilizer.dispenser.BehaviourKelpDispenser.m_6115_(BehaviourKelpDispenser.java:33) ~[kelpfertilizer_1.18.1-1.8.jar%23136!:1.0]
> 	at net.minecraft.world.level.block.DispenserBlock.m_5824_(DispenserBlock.java:90) ~[server-1.18.1-20211210.034407-srg.jar%23200!:?]
> 	at net.minecraft.world.level.block.DispenserBlock.m_7458_(DispenserBlock.java:113) ~[server-1.18.1-20211210.034407-srg.jar%23200!:?]
> 	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60616_(BlockBehaviour.java:675) ~[server-1.18.1-20211210.034407-srg.jar%23200!:?]
> 	at net.minecraft.server.level.ServerLevel.m_184112_(ServerLevel.java:636) ~[server-1.18.1-20211210.034407-srg.jar%23200!:?]
> 	at net.minecraft.world.ticks.LevelTicks.m_193272_(LevelTicks.java:215) ~[server-1.18.1-20211210.034407-srg.jar%23200!:?]
> 	at net.minecraft.world.ticks.LevelTicks.m_193225_(LevelTicks.java:98) ~[server-1.18.1-20211210.034407-srg.jar%23200!:?]
> 	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:269) ~[server-1.18.1-20211210.034407-srg.jar%23200!:?]
> 	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:868) ~[server-1.18.1-20211210.034407-srg.jar%23200!:?]
> 	... 5 more

**Comment by ricksouth** [comment]
Thanks for letting me know! This has been fixed in version 1.6 of Extended Bone Meal.

https://www.curseforge.com/minecraft/mc-mods/extended-bone-meal-fabric/files/all
