### ISSUE TITLE
1.16 - Surface Mushrooms - Not working, still won't plant in daylight

### ISSUE THREAD

**Issue by Sixdd6** [ricksouth/serilum-mc-mods#910]
As the title says, I get a mushroom (red or brown, makes no difference) and right click on dirt/grass that is in direct sunlight and nothing happens.

Mod Version: surfacemushrooms_1.16.5-1.2
Collective Version: collective-1.16.5-3.8
Forge Version: 36.2.23

[latest.log](https://github.com/ricksouth/serilum-mc-mods/files/7932044/latest.log)

**Comment by Cinderheart** [comment]
Doesn't work for me either. Is the mod even functional?
My version is surfacemushrooms_1.18.1-1.2.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try. I've just released version 1.4 of Surface Mushrooms with the mod completely rewritten. This should fix the problem you were having. Let me know if it persists!

https://www.curseforge.com/minecraft/mc-mods/surface-mushrooms
