### ISSUE TITLE
Realistic bees causing world to stay on 100% loading

### ISSUE THREAD

**Issue by FelixRobotics** [ricksouth/serilum-mc-mods#911]
## **Information**
Minecraft version: 1.15.2
Modloader: Forge
Forge version: 13.2.55
Environment: Singleplayer

Mod name: Realistic Bees
Mod version: 1.2

## **Description**
The title.  I may have already posted an issue about this but either way, I'm doing it again.  This mod caused me to sit waiting for hours trying to find a solution.  I really like the mod so I want it to work.

## **Crash report**
If available.
[crash-2022-01-26_00.00.57-client.txt](https://github.com/ricksouth/serilum-mc-mods/files/7939949/crash-2022-01-26_00.00.57-client.txt)

## **LATEST.LOG**
[latest.log](https://github.com/ricksouth/serilum-mc-mods/files/7939953/latest.log)

**Comment by ricksouth** [comment]
1.15.2 is unfortunately no longer supported. I've archived the version to prevent others from having the same the problem. Sorry for the inconvenience. I'd suggest updating to at least 1.16.5, other mods might have the same problem.

**Comment by ekiplier** [comment]
unfortunately, this is also happening to me on 1.16.5 :( I've recently submitted an issue related to this, but getting a crash report is very rare as most times it just stays in the world loading screen forever. I'm glad I found this issue here
