### ISSUE TITLE
[Request] Fabric Version of Realistic Bees

### ISSUE THREAD

**Issue by ong-yinggao98** [ricksouth/serilum-mc-mods#913]
Will there be a Fabric port of Realistic Bees? It's a cool mod and I really love the idea of making bees smaller especially, I always found it weird that Minecraft made them so grossly oversized when they clearly could make small mobs like rabbits and bats.

**Comment by Some-Doofus** [comment]
I'd like to second this request, just in case it's been forgotten or pushed to the bottom of the priority list. I too find it ridiculous that bees were made so grossly oversized, and they look 100x better being small like they are in this mod, but us fabric players don't have any options for such a mod yet.

**Comment by Sunconure11** [comment]
I'd third this request. Also, add compat with Charm, Quark, and any other mod that adds changes to bee textures and/or models.

**Comment by ricksouth** [comment]
There were some issues when attempting the port, but I'll definitely give it another try in the future. I appreciate the interest!
