### ISSUE TITLE
Quark LGBT Bees reverts bees to their normal size

### ISSUE THREAD

**Issue by OreoTheAvali** [ricksouth/serilum-mc-mods#915]
## **Information**
Minecraft version: 1.18.1
Modloader: Forge
Forge version: 39.0.59
Environment: Singleplayer & Multiplayer

Mod name: Realistic Bees
Mod version: 2.4

## **Description**
When using this mod along side of [Quark](https://www.curseforge.com/minecraft/mc-mods/quark) the bees do not spawn in their smaller sizes. This is presumably due to texture change caused by the "L G B T Bees" setting in Quark's Client-side settings located in "Variant Animals Textures. Disabling this setting and restarting the game resumes Realistic Bee's smaller settings.

**Comment by ricksouth** [comment]
This has been fixed on Quark's end. Thanks for giving the mod a try!
