### ISSUE TITLE
Tree Harvester harvesting my house, even if I am not sneaking

### ISSUE THREAD

**Issue by Xesxx** [ricksouth/serilum-mc-mods#921]
## **Information**
Minecraft version: 1.18.1
Modloader: Forge
Forge version: 39.0.43
Environment: Singleplayer AND Multiplayer

Mod name: Tree Harvester
Mod version: 4.2

## **Description**

Running into this issue whilst playing All the Mods 7

Hello, Tree Harvester seems to think my house is a tree, and every time I break a block it harvests my house. Normally, this wouldn't be an issue, but it does it when I am not sneaking. I went into the config settings in-game to see if anything would be causing it but I didn't find anything. Even if I am not sneaking (And I made sure that "Tree harvest without sneak" was off) it harvests trees, as well as any structure I make out of logs. The weird part is that this issue only seems to happen if I am using vanilla logs and vanilla tools. This issue doesn't occur if I am either using modded logs, or modded tools. 

I tried changing "Tree Harvest without sneak" to on, just to see if that would maybe fix it; as well as turning off "Automatically find bottom block" to off, but nothing seemed to solve it. If I can think of anything else I will update it here. 

EDIT: If I sneak while breaking a tree, or log structure, Tree harvester doesn't work. So it seems that it is backwards in the sense that it works if I don't sneak and doesn't work if I sneak. 

Thank you

**Comment by ricksouth** [comment]
Could you post a screenshot of your house? Does it have lots of logs and leaves?

**Comment by Xesxx** [comment]
I got off my world after it happened, but I just quickly remade the gist of what the house was, aside from it previously being acacia instead of oak. Mostly logs and slabs, no leaves. 

Made a gif showing if I crouch it doesn't break and if I am not crouched it veinmines it. 

Thank you :D

https://media.giphy.com/media/chg8jvDtxw0xFvt0Oy/giphy.gif

**Comment by ricksouth** [comment]
Thanks! Are you sure this is Tree Harvester? Could you post your modlist? Because TH doesn't actually change the speed of breaking the logs, which makes me think another mod does this

**Comment by ricksouth** [comment]
There should also be a check for leaves around, and with no leaves in theory it shouldn't run at all

**Comment by Xesxx** [comment]
https://www.modpackindex.com/modpack/35650/all-the-mods-7-atm7-1181

Mod list^

It could be Ore Excavation, I just thought it was Tree Harvester, apologies. I looked at both Ore excavation and Tree Harvester config when it happened, but couldn't figure out which caused it for certain; because they both handle breaking trees.

**Comment by ricksouth** [comment]
Might be Ore excavation then! Could you test if it still does this to your house with it removed? I think the ATM team would also appreciate an issue being opened on this. You could link this issue there

**Comment by ricksouth** [comment]
Seems to be the Reap mod! :) Thanks for giving Tree Harvester a try.
