### ISSUE TITLE
doubledoors_1.12.2-3.0.jar Forge causing rapid open/close door glitch Mod:Double Doors

### ISSUE THREAD

**Issue by InuYasha86000** [ricksouth/serilum-mc-mods#922]
This seems to be the same issue that others had on versions 1.16 and 1.18 although I don't think there was an update for the 1.12.2 Forge version for a V3.1 release.

**Comment by ricksouth** [comment]
Unfortunately I can't update 1.12 anymore as it's not part of my development area. I've archived the 3.0 version for now. Version 2.5 works without issues (without being recursive). Sorry for the inconvenience.
