### ISSUE TITLE
is this something from your mod?

### ISSUE THREAD

**Issue by LuigiTP** [ricksouth/serilum-mc-mods#923]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.18.1
Modloader: Forge 
Forge version: 39.0.59
Environment: Multiplayer

Mod name: Villager Names?
Mod version: villagernames_1.18.1-3.5

## **Question**
a bunch of mobs started spawning randomly with names like joker(2019), Hilary Clinton, Joe Biden, ButtSlapper, and your name followed by neopronouns 
is this your mod doing it if so how i disable it?
![image](https://user-images.githubusercontent.com/46649309/152056149-78e24715-d206-4033-a7dc-624738feba28.png)

**Comment by James103** [comment]
Can you please post the full mod list?

**Comment by LuigiTP** [comment]
[Modlist.txt](https://github.com/ricksouth/serilum-mc-mods/files/7982184/Modlist.txt)
sorry took a while

**Comment by LuigiTP** [comment]
i have some more named entities if that helps

**Comment by ricksouth** [comment]
This is obviously not my mod.

If I remember a discord conversation correctly in the curseforge dev server, it's "quick world gen"

**Comment by ricksouth** [comment]
quickwgen.jar

Disguised as a performance mod, I believe it's been removed from CurseForge already.

**Comment by LuigiTP** [comment]
really ?? thx this has been really fucking weird

**Comment by ricksouth** [comment]
Yea that mod was made for nothing but trouble. Glad I could help! And thanks for giving my mods a try.
