### ISSUE TITLE
Chunk Loading Around Campfires

### ISSUE THREAD

**Issue by Raycoms** [ricksouth/serilum-mc-mods#924]
## **Information**
Minecraft version: 1.18.1
Modloader: Forge

Mod name: Healing Campfire

## **Description**
When campfires are placed close to unloaded chunks, the range scans load neighboring chunks which may cause lag. Optimally it would only scan loaded chunks.

**Comment by ricksouth** [comment]
Thanks for opening the issue! This has been fixed in Collective version 6.59. Appreciate it.

https://www.curseforge.com/minecraft/mc-mods/collective/files
