### ISSUE TITLE
GUI Followers: Name duplication

### ISSUE THREAD

**Issue by gh0stf1sh** [ricksouth/serilum-mc-mods#928]
## **Information**
Minecraft version: 1.18.1
Modloader: Forge
Forge version: 39.0.59
Environment: Multiplayer

Mod name: GUI Followers
Mod version: 1.8

## **Description**
I noticed at some point my pets started duplicating on the list? And the newer dupes would be the accurate distance while the older ones (closer to the top) would be pretty far away despite said pets being right next to me.

Edit: For context I only have 4 Shibas and 2 cats.

![Screenshot (5558)](https://user-images.githubusercontent.com/88052255/152118602-161e769a-6494-47fd-8747-faa1d3ce27fe.png)

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! I've fixed it in version 1.9 of GUI Followers.

https://www.curseforge.com/minecraft/mc-mods/gui-followers/files
