### ISSUE TITLE
Ability to cut down fungi 

### ISSUE THREAD

**Issue by Rayskiz** [ricksouth/serilum-mc-mods#930]
Would it be possible to add the ability to use this function to also cut down giant mushrooms, such as in a dark forest or mushroom island.

**Comment by ricksouth** [comment]
As this is a hub for all mods, I think you mean for Tree Harvester right?

**Comment by ricksouth** [comment]
Thanks for the suggestion! This has been added in version 5.0 of Tree Harvester.

https://www.curseforge.com/minecraft/mc-mods/tree-harvester/files
