### ISSUE TITLE
[RGB] and Naming Features not working for areas on server

### ISSUE THREAD

**Issue by h-coble** [ricksouth/serilum-mc-mods#932]
## **Information**
Minecraft version: 1.18.1
Modloader: Forge 
Forge version:  39.0.55
Environment: Multiplayer

Mod name: Areas
Mod version: 2.9

## **Description**
When trying to define an area and using [RGB] while on my server, the area does not get created.
When tested in singleplayer, the feature worked with no issue. The same is true when naming an area using multiple lines such as

_[Area] 5
Area
Name_

## **Crash report**
N/A

**Comment by James103** [comment]
Are you sure that Areas is installed on both client and server?

**Comment by h-coble** [comment]
Yes, I can confirm it is installed on both server and client

**Comment by lannior** [comment]
Same issue here. [RGB] works very inconsistently and most of the time it doesnt let me create the area at all.
All clients as well as the server have the mod installed.

**Comment by ForionOG** [comment]
I dont know about the RGB function but when i add a name to my area sign it doesnt work but if i leave it blank i do get a random name

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 5.0 of Areas, alongside other bug fixes and QoL features. Apologies it took so long for me to get to.

https://www.curseforge.com/minecraft/mc-mods/areas/files

**Comment by h-coble** [comment]
No worries! I just thought you'd like to know about it, as I didn't see
anyone else mention it at the time. Thanks for creating the mod; my friends
and I found it both entertaining and useful for our builds.
