### ISSUE TITLE
Furnace Recycle server-side only?

### ISSUE THREAD

**Issue by xenetiVe** [ricksouth/serilum-mc-mods#933]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.18.1
Modloader: Fabric
Forge version: Fabric loader version: 0.12.12
Environment: Multiplayer

Mod name: Furnace Recycle
Mod version: 1.0

## **Question**
Will it work if installed server side only?

**Comment by ricksouth** [comment]
Yes! :)
