### ISSUE TITLE
Collective - can't open any worlds or create new ones with 4.0

### ISSUE THREAD

**Issue by ThinkWithPbody** [ricksouth/serilum-mc-mods#935]
Using it on 1.18.1 Fabric latest version. 

When I load a save file or create a new one it says there's an error in datapacks and it lets me choose between safe mode (which doesn't do anything) and return to the main menu. I went back and downgraded my recently updated mods and figured out it was related to collective 4.0, but I don't have the knowledge/time to give more details. 

Had to downgrade to 3.2 to play.

**Comment by ricksouth** [comment]
Thanks for opening the issue so quickly. Could you test Collective version 4.1? It should fix the problem you were having.

https://www.curseforge.com/minecraft/mc-mods/collective-fabric/files/all

**Comment by ThinkWithPbody** [comment]
Collective version 4.1 worked perfectly for me, no more issues. I really appreciate all the quality mods you're providing the community with, cheers!

**Comment by ricksouth** [comment]
Thanks for confirming and the kind words! Glad they're of some use to you. :)
