### ISSUE TITLE
most recent version of collective is causing crashes on game launch

### ISSUE THREAD

**Issue by Flame115** [ricksouth/serilum-mc-mods#936]
## **Information**
Minecraft version: 1.18.1
Modloader: Fabric
Fabric loader version: 0.12.12
Environment: Singleplayer 

Mod name: Collective
Mod version: 1.18.x-4.0

## **Description**
Game crashes on launch

## **Crash report**
cant really provide one that shows this mod is to blame, crashlogs all point to different mods causing issues, but when I disable collective the crashing stops. 

ill provide one of the logs regardless:
https://pastebin.com/JfFhEbgQ

**Comment by ricksouth** [comment]
Thanks for opening the issue so quickly. Could you test Collective version 4.1? It should fix the problem you were having.

https://www.curseforge.com/minecraft/mc-mods/collective-fabric/files/all

**Comment by ricksouth** [comment]
Should be fixed in version 4.1. Let me know if you encounter any issues!
