### ISSUE TITLE
Is The Vanilla Experience (the mod) coming to Fabric?

### ISSUE THREAD

**Issue by vico93** [ricksouth/serilum-mc-mods#937]
Really sorry if it already exists (i cant find in both CF and Google search, only Forge version).

That would be immensely useful for my fabric modpack, since i have interest to use a lot of his mods.

**Comment by ricksouth** [comment]
Thanks for the interest!

There were (are) some issues with the vanilla experience mod for Forge at the moment. Some mods didn't play nice with each other and it was registering a lot of separate events. I've got a few things to catch up on and a few fabric ports left but after that I'll work on getting it updated again. With a fabric port included.
