### ISSUE TITLE
Version 4.1 deletes all items

### ISSUE THREAD

**Issue by Scamper10** [ricksouth/serilum-mc-mods#938]
Very simple, if collective 4.1 for 1.16.5 is installed, all items in the world are instantly deleted every tick

**Comment by James103** [comment]
Can you please try reproducing this problem? If you can, will you please post the mod list and latest.log file?

**Comment by Scamper10** [comment]
Problem happened on multiple computers, with collective and fabricAPI and no other mods, let me find the log file

**Comment by ricksouth** [comment]
Forge or Fabric?

**Comment by Scamper10** [comment]
Fabric, I couldn't find the log file, so here is a new one (with extension txt) with the issue present

[latest.txt](https://github.com/ricksouth/serilum-mc-mods/files/8010454/latest.txt)

**Comment by ricksouth** [comment]
I'm able to reproduce it locally, thanks for letting me know! Working on a fix right now

**Comment by ricksouth** [comment]
Fixed in version 4.2. Indeed only affected the 1.16 version. Again, thanks for letting me know and giving some of my mods a try. Apologies for the inconvenience.

https://www.curseforge.com/minecraft/mc-mods/collective-fabric/files/all
