### ISSUE TITLE
Shift + right-clicking with hoe makes hoe durability negative

### ISSUE THREAD

**Issue by Dekamir** [ricksouth/serilum-mc-mods#939]
## **Information**
Minecraft version: 1.18.1
Modloader: Forge
Forge version: 39.0.66

Mod name: Hoe Tweaks
Mod version: 1.3

## **Description**
_Title self explanatory._
Also, due to vanilla behaviour with negative durability, it doesn't break unless you use it normally.

**Comment by ricksouth** [comment]
Thanks for letting me know and using the mod! This has been fixed in version 1.4 of Hoe Tweaks.

https://www.curseforge.com/minecraft/mc-mods/hoe-tweaks
