### ISSUE TITLE
Can we get a directions only option?  

### ISSUE THREAD

**Issue by tjp77** [ricksouth/serilum-mc-mods#942]
Just found this mod, and it's what I was hoping for expect that it would be nice to have the option to show just the direction since I don't care about the coordinates, so it's not taking up screen space.

**Comment by ricksouth** [comment]
I've just released GUI Compass version 2.0 which adds the feature you've requested. There's a config option '**guiCompassFormat**'. By default it's "FXYZ". To get only the direction (facing) you can change that to "**F**". Thanks for the suggestion and using the mod!

https://www.curseforge.com/minecraft/mc-mods/gui-compass

**Comment by tjp77** [comment]
Thanks!
