### ISSUE TITLE
Set World Spawn Point and Starter Kit not triggering

### ISSUE THREAD

**Issue by JDtheHutt** [ricksouth/serilum-mc-mods#943]
## **Information**
Minecraft version: 1.18.1
Modloader: Fabric
Fabric loader version: 0.13.2
Environment: Multiplayer

Mod name: Set World Spawn Point
Mod version: 1.8

Mod name: Starter Kit
Mod version: 3.1

## **Description**
Neither mod does anything.  I have used the command to set the spawn point ingame, and it said it worked, but the config file in the server did not change.  I manually set the co-ordinates in the config file and new players do spawn around that location but not exactly, though _forceExactSpawn is set to true.  I have tried repeatedly by deleting a test player's data from the server and spawning them again, but same result each time.

New players also do not get the starter kit equipment set in the config file, which did set correctly when I ran that command.

Not sure whether a separate ticket for each is needed, but possibly related due to the set spawn not working and thereby not triggering the starter kit.

## **Crash report**
No crash.

**Comment by ricksouth** [comment]
Could you provide your modlist? Are there any mods that put items in the inventory on first spawn, before starter kit should do it?
