### ISSUE TITLE
Grindstone Sharpening Doesn't Work on Server.

### ISSUE THREAD

**Issue by TheTennessee** [ricksouth/serilum-mc-mods#944]
## **Information**
Minecraft version: 1.18.1
Modloader: Fabric
Fabric loader version: 1.12.12
Environment: Multiplayer

Mod name: Grindstone Sharpen Tools
Mod version: 1.6

On a server, I can't seem to use a sword on the grindstone. I use it in singleplayer just fine, but it won't work on the server running the same mods. Trying to shift-right click on the grindstone just doesn't have any effect.

**Comment by ricksouth** [comment]
I've just tested it to confirm and the mod works fine in multiplayer. Could you do another test, and if it still not works export your modpack and upload it here? It might be incompatible with another mod installed.

**Comment by TheTennessee** [comment]
I cannot share the modpack itself. I put it together and it has a lot of unreleased mods in it among other things. I can share the mod list though.

`[08:31:09] [main/INFO]: Loading 288 mods:
	- additionaladditions 3.0.1
	- adorn 3.0.0-rc.1+1.18-rc3
	- advanced_runtime_resource_pack 0.2.9 via carrier
	- advancednetherite 1.4.0-1.18.1
	- alloy_forgery 2.0.6+1.18
	- allstackable 1.5.4-1.18.1
	- amecsapi 1.3.3+mc1.18-pre1 via backslot
	- amplified_nether 1.0.1
	- annotateddi 2.0.4+1.18 via fireplacelib
	- aopalliance_aopalliance 1.0 via annotateddi
	- apoli 2.2.2 via origins
	- appleskin mc1.18-2.2.0
	- aqupdgrizzly 1.18-1.2.0
	- archeology 0.1.8
	- architectury 3.0.39
	- artifacts 6.0.0+fabric
	- awesomedungeon_ocean 1.0.3
	- backslot 1.2.4
	- backslotaddon 1.0.7
	- balm-fabric 2.4.1+0
	- basicshields 1.2.1-1.18.1
	- bclib 1.3.0
	- betterdungeons 1.18-0.1.0
	- betterend 1.0.2
	- bettermineshafts 1.18-0.2.0
	- betternether 6.0.10
	- betterstrongholds 1.18-0.1.2
	- blue_endless_jankson 1.2.1 via jankson
	- bountiful 2.0.1
	- bugfixes 1.0
	- calio 1.4.2 via apoli
	- cardinal-components-base 4.0.1 via xp_storage
	- cardinal-components-entity 4.0.1 via xp_storage
	- cardinal-components-item 4.0.1 via xp_storage
	- carrier 1.9.0
	- cenchants 1.9.0
	- chord 1.8.0+1.18-fabric via wilderworld
	- chunky 1.2.153
	- cloth-basic-math 0.6.0 via cloth-config
	- cloth-config 6.1.48 via doublejumpattribute
	- collective-fabric 3.14
	- com_electronwill_night-config_core 3.6.5 via couplings
	- com_electronwill_night-config_toml 3.6.5 via couplings
	- com_eliotlash_mclib_mclib 18 via geckolib3
	- com_eliotlash_molang_molang 18 via geckolib3
	- com_google_inject_guice 5.0.1 via annotateddi
	- com_moandjiezana_toml_toml4j 0.7.2 via deepslatecutting
	- com_typesafe_config 1.4.1 via confabricate
	- comforts 1.0.0-1.18
	- conduitspreventdrowned-fabric 1.5
	- confabricate 2.2.0-SNAPSHOT+4.1.1 via croptopia
	- convenient-mobgriefing 2.0.2
	- copper_pipe r1.9
	- cosmetica 0.3.2 via visuality
	- couplings 1.7.1+1.18
	- croptopia 1.7.1
	- crowdin-translate 1.4+1.18 via enchantment_lore
	- cryingghasts-fabric 1.4
	- cryingportals-fabric 1.2
	- customfood 0.2.0
	- dark-enchanting 0.6.0-1.18
	- darkwaters 0.0.9
	- deepslatecutting 1.3.0
	- diamondshards 1.0.4
	- dimheight 1.1.0
	- dimores 1.0.2
	- disable_custom_worlds_advice 1.4
	- doublejumpattribute 1.18.1-fabric-1.0.3
	- dragondropselytra-fabric 1.4
	- dragonloot 1.0.9
	- drinkbeer 3.0
	- dual_riders 1.0.5
	- dualwielding 1.0.7
	- ducts 1.1.6
	- dungeonvanilla 1.0.0
	- dynamicsoundfilters 1.3.0+1.18
	- earthtojavamobs 1.7.4+1.18
	- enchant_giver 1.1.0 via mcdw
	- enchantment_lore 1.2.3+MC1.18-1.18.1
	- enhancedcelestials 2.0.6
	- erodingstoneentities-fabric 2.5
	- expandability 5.0.0 via artifacts
	- extraalchemy 1.7.0
	- extractpoison-fabric 1.6
	- extraorigins 1.18-5
	- fabric 0.45.2+1.18
	- fabric-api-base 0.4.1+b4f4f6cdc8 via couplings
	- fabric-api-lookup-api-v1 1.5.0+17be577f65 via fabric
	- fabric-biome-api-v1 6.0.1+ded849a965 via fabric
	- fabric-blockrenderlayer-v1 1.1.9+3ac43d9565 via fabric
	- fabric-command-api-v1 1.1.6+3ac43d9565 via fabric
	- fabric-commands-v0 0.2.5+b4f4f6cd65 via fabric
	- fabric-containers-v0 0.1.18+d154e2c665 via fabric
	- fabric-content-registries-v0 0.4.5+6f53a73d65 via fabric
	- fabric-crash-report-info-v1 0.1.8+3ac43d9565 via fabric
	- fabric-dimensions-v1 2.1.9+a1d9bbf565 via fabric
	- fabric-entity-events-v1 1.4.5+6b21378a65 via fabric
	- fabric-events-interaction-v0 0.4.16+bfa23f1765 via fabric
	- fabric-events-lifecycle-v0 0.2.6+b4f4f6cd65 via fabric
	- fabric-game-rule-api-v1 1.0.10+3ac43d9565 via fabric
	- fabric-item-api-v1 1.3.0+691a79b565 via fabric
	- fabric-item-groups-v0 0.3.3+3ac43d9565 via fabric
	- fabric-key-binding-api-v1 1.0.8+c8aba2f365 via fabric
	- fabric-keybindings-v0 0.2.6+b4f4f6cd65 via fabric
	- fabric-language-kotlin 1.7.0+kotlin.1.6.0
	- fabric-lifecycle-events-v1 1.4.10+c15ca33565 via fabric
	- fabric-loot-tables-v1 1.0.8+3ac43d9565 via fabric
	- fabric-mining-level-api-v1 1.0.3+3ac43d9565 via fabric
	- fabric-mining-levels-v0 0.1.8+b4f4f6cd65 via fabric
	- fabric-models-v0 0.3.3+3ac43d9565 via fabric
	- fabric-networking-api-v1 1.0.18+3ac43d95c8 via couplings
	- fabric-networking-v0 0.3.5+b4f4f6cd65 via fabric
	- fabric-object-builder-api-v1 1.11.1+3b82842e65 via fabric
	- fabric-object-builders-v0 0.7.9+3ac43d9565 via fabric
	- fabric-particles-v1 0.2.9+526dc1ac65 via fabric
	- fabric-registry-sync-v0 0.9.0+befed49e65 via fabric
	- fabric-renderer-api-v1 0.4.9+3ac43d9565 via fabric
	- fabric-renderer-indigo 0.4.12+3ac43d9565 via fabric
	- fabric-renderer-registries-v1 3.2.7+b4f4f6cd65 via fabric
	- fabric-rendering-data-attachment-v1 0.3.4+7242e9d765 via fabric
	- fabric-rendering-fluids-v1 0.1.18+3ac43d9565 via fabric
	- fabric-rendering-v0 1.1.9+b4f4f6cd65 via fabric
	- fabric-rendering-v1 1.10.3+6b21378a65 via fabric
	- fabric-resource-loader-v0 0.4.11+3ac43d9565 via fabric
	- fabric-screen-api-v1 1.0.7+3ac43d9565 via fabric
	- fabric-screen-handler-api-v1 1.1.11+3ac43d9565 via fabric
	- fabric-structure-api-v1 2.0.8+295197a765 via fabric
	- fabric-tag-extensions-v0 1.2.5+3ac43d9565 via fabric
	- fabric-textures-v0 1.0.9+3ac43d9565 via fabric
	- fabric-tool-attribute-api-v1 1.3.5+fb3b57b465 via fabric
	- fabric-transfer-api-v1 1.5.6+b4f4f6cd65 via fabric
	- fabricenchantments 0.6.0
	- fabricloader 0.12.12
	- fabricshieldlib 1.4.5-1.18
	- fallingleaves 1.8.1+1.18.1
	- farmersdelight 1.18.1-0.2.0
	- farmingforblockheads 9.0.3
	- feature_nbt_deadlock_be_gone $version
	- fiber 0.23.0-2 via collective-fabric
	- fireplacelib 6.2.2+1.18
	- firespreadtweaks-fabric 1.2
	- flamearrows 1.18.1
	- friendsandfoes 1.2.3
	- geckolib3 3.0.21
	- genesis 0.8
	- geodes 1.2.1
	- gimme_bundles 1.0.3
	- go-fish 1.4.1-1.18.1
	- goblintraders 1.4.1
	- goosik-config 0.2.0 via visuality
	- graveyard 1.3
	- grindstonesharpertools-fabric 1.6
	- healingcampfire-fabric 3.3
	- homebodies_fantasy 1.0.0
	- hookshot 23.0
	- horizontalpanes 1.1.6
	- icarus 1.9
	- illuminations 1.10.2
	- improved-stations 2.0.8
	- incantationem 1.1.2+1.18-pre1
	- inmis 2.4.0-1.18
	- interactic 0.1.7+1.18
	- io_leangen_geantyref_geantyref 1.3.11 via confabricate
	- iris 1.1.4
	- jankson 4.0.0+j1.2.0 via adorn
	- java 17
	- javax_inject_javax_inject 1 via annotateddi
	- kambrik 3.0.0
	- kanos_config 0.1.4+1.14.4-1.17.1 via pehkui
	- kirin 1.9.1 via presencefootsteps
	- lambdynlights 2.1.0+1.17
	- libcd 3.0.3+1.16.3 via adorn
	- libgui 5.1.0+1.18 via additionaladditions
	- libninepatch 1.1.0 via dark-enchanting
	- lightoverlay 6.0.4
	- lithium 0.7.7
	- logical_zoom 0.0.13
	- lootcrates 2.7.0-1.18.1
	- lovely_snails 1.0.3+1.18
	- malilib 0.10.0-dev.26
	- maybe-more-data 1.0.0-21w40a via deepslatecutting
	- mcda 2.0.2
	- mcdar 1.4.3-1.18
	- mcdw 4.2.3
	- mcf-reap 1.7.1
	- midnightlib 0.3.1 via rocks
	- minecraft 1.18.1
	- mm 2.3 via shulkerboxtooltip
	- moborigins 1.8.0
	- mobscarecrow 1.0.0
	- modmenu 3.0.0
	- morevillagers-fabric 3.0.0-SNAPSHOT
	- mythic-mounts 1.18-5.0
	- nears 1.1.2
	- netherportalspread-fabric 5.6
	- no_null_processors 2.0.1+1.18.1
	- nohostilesaroundcampfire-fabric 3.8
	- nomoreglowingpots 1.0.2
	- notenoughanimations 1.4.0
	- nyfsquiver Fabric-0.4.0-1.18
	- omega-config 1.2.2-1.18.1 via friendsandfoes
	- onsoulfire 1.18-1
	- org_anarres_jcpp 1.4.14 via iris
	- org_apache_httpcomponents_httpclient 4.5.10 via skinswapper
	- org_apache_httpcomponents_httpcore 4.4.12 via skinswapper
	- org_apache_httpcomponents_httpmime 4.5.10 via skinswapper
	- org_aperlambda_lambdajcommon 1.8.1 via spruceui
	- org_jetbrains_kotlin_kotlin-reflect 1.6.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.6.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.6.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.6.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.5.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.5.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.1 via fabric-language-kotlin
	- org_joml_joml 1.10.2 via sodium
	- org_slf4j_slf4j-api 1.7.12 via iris
	- org_spongepowered_configurate-core 4.1.1 via confabricate
	- org_spongepowered_configurate-extra-dfu4 4.1.1 via confabricate
	- org_spongepowered_configurate-gson 4.1.1 via confabricate
	- org_spongepowered_configurate-hocon 4.1.1 via confabricate
	- origins 1.3.1
	- owo 0.5.2+1.18
	- patchouli 1.18.1-63-FABRIC
	- pehkui 3.0.0+1.14.4-1.18
	- playerabilitylib 1.3.0 via apoli
	- plushies 1.1
	- presencefootsteps r34-1.17-rc1
	- pride 1.1.0+1.17 via lambdynlights
	- reach-entity-attributes 2.1.1 via mcdw
	- reinfbarrel 1.0.6+1.18
	- reinfchest 1.0.6+1.18
	- reinfcore 1.1.3+1.18 via reinfbarrel
	- reinfshulker 1.1.8+1.18
	- replaymod 1.18.1-2.6.3
	- repurposed_structures 3.3.4+1.18.1
	- respawningshulkers-fabric 1.6
	- rocks 1.5.2
	- roughlyenoughitems 7.0.339
	- ruined_equipment 1.4.0
	- sakuradecor 1.0.1
	- sbm-jukebox 1.0.2
	- sculk_worm 0.1.5
	- seasons 1.3-BETA+1.18
	- seedfix 1.0.0 via amplified_nether
	- seethroughlava 2.2
	- shulkerboxtooltip 3.0.5-beta.1+1.18-pre5
	- skinnedlanterns 1.2.0+build.12
	- skinswapper 3.1.0
	- skyvillages 1.0.1-1.18.1-fabric
	- slabby 0.2.3
	- small_artifacts 0.1.0-1.18
	- soaringstructures2 1.18 - 2.1
	- sodium 0.4.0-alpha5+rev.76d0e6e
	- spruceui 3.3.0+1.17 via lambdynlights
	- squirrels 1.2.1-1.18
	- step-height-entity-attribute 1.0.0 via artifacts
	- stoneholm 1.4.1
	- stonevaults 1.1.0
	- terralith 2.0_b0.1.8
	- things 0.2.15+1.18
	- thonkutil 1.3 via goblintraders
	- torchkey 1.0.5
	- towers_of_the_wild_reworked 2.1.0
	- transportables 1.1
	- treeharvester-fabric 4.1
	- trinketofundying 2.0.1-1.18
	- trinkets 3.1.0
	- tweakeroo 0.10.0-dev.20211223.033756
	- twigs 1.1.2
	- twm 0.6 dev
	- unforgivingvoid 3.1.1+1.18
	- unlimiteddragoneggs 1.3.1
	- urns 1.0.1
	- villager-hats 1.3.1
	- villagers-follow-emeralds 1.2.0
	- visuality 0.3.3
	- voicechat 1.18.1-2.1.18
	- wallpaperandcarpet 0.1.0
	- waystones 9.0.1
	- wilderworld 1.0.0
	- witherborn_origins 1.0.0
	- witherturnsskeletons 1.1.0-1.18.0
	- xaerominimapfair 22.2.0.1
	- xp_storage 1.4.3+1.18
	- yigd 1.2.20
	- yungsapi 1.18-Fabric-35`

If it is working on your end, then do not worry. I am sure I can figure out where it is coming from then during testing. I have a few oddities in my pack. (Like bees not working, and some blocks not accepting items from hoppers that are caused by a couple bugs in other mods.) I just found it very strange that it worked during single player testing, and now it doesn't in multiplayer.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This should have been fixed in version 2.2 of Grindstone Sharper Tools. I'm using a different function to find the grindstone block. It's been a while, and you probably don't have it loaded anymore, but if you do, please let me know if the issue persists.

https://www.curseforge.com/minecraft/mc-mods/grindstone-sharper-tools-fabric/files
