### ISSUE TITLE
Collective 4.4/4.5 crashes in 22w07a

### ISSUE THREAD

**Issue by BaccarWozat** [ricksouth/serilum-mc-mods#946]
## **Information**
Minecraft version: 1.18.2 snapshot 22w07a
Modloader: Fabric
Fabric loader version: 0.13.2
Environment: Any

Mod name: Collective
Mod version: 4.4/4.5

## **Description**
Crashes before loading. Only other (enabled) mod is Fabric API 0.47.2. (All other listed mods are disabled so won't load.)

## **Crash report**
With 4.4: [https://paste.ee/p/zCibQ](https://paste.ee/p/zCibQ)
With 4.5: [https://paste.ee/p/ziuqc](https://paste.ee/p/ziuqc)

**Comment by James103** [comment]
Can you please try again with Collective 4.3 and earlier and post the results?

**Comment by BaccarWozat** [comment]
4.3: No such thing
4.2: [https://paste.ee/p/7iCVy](https://paste.ee/p/7iCVy)
4.1: [https://paste.ee/p/3nWXe](https://paste.ee/p/3nWXe)
4.0: [https://paste.ee/p/GX3e8](https://paste.ee/p/GX3e8)

**Comment by James103** [comment]
In all 5 of the pastes that you posted, `Process exited with code 1` because `Mixin apply for mod collective-fabric failed` because `java.lang.RuntimeException: Mixin transformation of net.minecraft.class_310 failed`.

In other words, the mod is effectively incompatible with the most recent 1.18.2 snapshots.

**Comment by BaccarWozat** [comment]
I am so dumb. Collective 3.20 still works! I was sure that today's release was because of the new snapshot, and yet I now see in my other instance that I haven't updated Collective to any 4.x.

Of course, this image suggests it _ought_ to work on the recent ones...
![image](https://user-images.githubusercontent.com/8357501/154390911-59f2d2c6-4194-4b5d-80c1-bb2479ea0357.png)

My bad. Apologies all around.

**Comment by ricksouth** [comment]
Thanks for opening the issue @BaccarWozat and using some of my mods! The mod worked with previous snapshots and thus the tag was still there. I made some changes to the mixin that was causing issues and 4.6 should work with the latest snapshots and includes some efficiency improvements.

https://www.curseforge.com/minecraft/mc-mods/collective-fabric/files/all
