### ISSUE TITLE
dispenser with seawead crashes server

### ISSUE THREAD

**Issue by djluke001** [ricksouth/serilum-mc-mods#949]
## **Information**
Minecraft version: 1.18.1
Modloader: Forge 
Forge version: xx.xx.xx  
Environment: Multiplayer

Mod name: vanilla experience modpack   (seaweed acts as bonemeal mod)
Mod version: x.x

## **Description**
When you put seaweed in a dispenser and activate it. it crashes the server
djluke#3865

## **Crash report**
not the server admin

**Comment by James103** [comment]
Are you able to reproduce this in single player?

**Comment by djluke001** [comment]
Yes it also happens in single player.
error code for Minecraft cracsh is:

The game crashed whilst exception ticking world
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.player.Player.m_6144_()" because "player" is null
Exit Code: -1

correction: you put kelp* in a dispencer and power it

**Comment by James103** [comment]
Do you have the corresponding crash reports? If so, can you please post them?
You can find them in your Minecraft instance's `.minecraft/crash-reports` folder.

**Comment by djluke001** [comment]
[crash-2022-02-18_10.33.06-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/8101099/crash-2022-02-18_10.33.06-server.txt)

**Comment by ricksouth** [comment]
Fixed in version 1.6 of Extended Bone Meal. Thanks for letting me know! Will upload an updated Vanilla Experience as soon as possible (whenever it updates in the CurseForge app)

https://www.curseforge.com/minecraft/mc-mods/extended-bone-meal-fabric/files/all
