### ISSUE TITLE
[1.18.1] [Fabric] Crash when entity eats/drinks something

### ISSUE THREAD

**Issue by pewblaze** [ricksouth/serilum-mc-mods#950]
## **Information**
Minecraft version: 1.18.1
Modloader: Fabric
Fabric loader version: 0.13.0
Environment: Singleplayer

Mod name: collective-fabric-1.18.x-4.8
Mod version: 4.8

## **Description**
When the Wandering Trader drinks his potion the game crashes. (Same if the fox is eating something)

## **Crash report**
[crash-2022-02-19_14.02.06-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/8102212/crash-2022-02-19_14.02.06-server.txt)

**Comment by James103** [comment]
Are you able to reproduce this using only Minecraft 1.18.1, Fabric 0.13.x, and Collective (Fabric) 4.8? If so, can you please post the resulting logs?

**Comment by pewblaze** [comment]
Yes, there you go:
[crash-2022-02-19_14.23.06-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/8102234/crash-2022-02-19_14.23.06-server.txt)

[latest.log](https://github.com/ricksouth/serilum-mc-mods/files/8102238/latest.log)

I also created a new world & same thing happened.
Happens also with Modloader Version 0.13.2
I also tried a few other older collective version - same outcome.

Cause of the Structure Bug i cant update my Modpack to an older fabric api. 
(Yungs API & Repurposed Structures needs the newer API)

**Comment by TWJedi** [comment]
I also replicated this problem. The game consistently crashes whenever any NPC entity uses an item. It crashed with Foxes and Wandering Traders. Here is my crash log: https://pastebin.com/2iFxgLHt

I tried several earlier versions, and the latest version that **_didn't_** crash is 4.4. It seems that the changes made in 4.5 is what is causing the issue.

**Comment by MechanicalDragon0687** [comment]
https://github.com/ricksouth/serilum-mc-mods/blob/e49e14ba8add37f895383bc47f5a9cf6f401751a/sources-fabric/Collective%20(Fabric)/src/main/java/com/natamus/collective_fabric/fabric/mixin/ItemStackMixin.java#L39

Casting livingentity to playerentity here

**Comment by ricksouth** [comment]
Thanks everyone for reporting the issue and providing the solution! I've uploading Collective (Fabric) 4.9 which fixes the issue. Apologies for the inconvenience.

https://www.curseforge.com/minecraft/mc-mods/collective-fabric/files/all
