### ISSUE TITLE
Furnace Recycle (Fabric): Smelting recipes not grouped properly

### ISSUE THREAD

**Issue by Darkiceflame** [ricksouth/serilum-mc-mods#951]
## **Information**
Minecraft version: 1.18.1
Modloader: Fabric
Fabric loader version: 0.13.1
Environment: Singleplayer / Multiplayer

Mod name: Furnace Recycle
Mod version: 1.0

## **Description**
When viewing smelting recipes in the furnace recipe book, the recipes from this mod are not grouped properly. This results in a rather messy looking recipe book and ought to be cleaned up by assigning these recipes to the proper groups.

![javaw 2022-02-20 11-36-25-13](https://user-images.githubusercontent.com/5132968/154858474-ec18fcb8-b25c-4216-abaf-b4eadf849d58.jpg)

## **Crash report**
N/A

**Comment by ricksouth** [comment]
Thanks for opening the issue and using the mod! I've just uploaded version 1.2 which groups all smelting recipes to the correct output. Definitely looks a lot cleaner.

https://www.curseforge.com/minecraft/mc-mods/furnace-recycle-fabric/files
