### ISSUE TITLE
[Bug] Double doors doesn't work with pressure plates or redstone

### ISSUE THREAD

**Issue by SirGalahad001** [ricksouth/serilum-mc-mods#953]
## **Information**
Minecraft version: 1.18.1
Modloader: Forge
Forge version: 39.0.79
Environment: Singleplayer

Installed Mods:
Anvil Restoration 1.18.1 v1.2
Better Crates 1.18.1 v1.0
Bigger Stacks 1.18 v2.6.1
Collective 1.18.1 v4.7
Configured 1.18.1 v1.5.3
Corail Recycler 1.18.1 v5.5.0
Double Doors 1.18.1 v3.2
Enchantment Descriptions Forge 1.18.1 v9.0.11
Fixed Anvil Repaircost 1.18.1 v1.7
Hourglass 1.18 v2.1.0
Inventory Spam 1.18.1
Items Don't Break 1.18.1
JEI 1.18.1 v9.2.1.69
JRFTL+ 1.18.1 v1.4.1
Moving Elevators 1.18 v1.3.3
Optifine v.1.18.1_HD_U_H5_pre5
Quick+Harvest 1.18.1 v1.5.1
Sophisticated Backpacks 1.18.1
SuperMartijn642 Config Lib 1.18 v1.0.9
SuperMartijn642 Core Lib 1.18 v1.0.16b
Toro Health 1.18 Forge v2
Xaeros Minimap 1.18 v22.1.3
Xaeros World Map 1.18 v1.20.2

Misa's Realistic Texture v1.18c
BSL Shaders v8.1.02.1

## **Description**
Double doors only works when opened by hand or button.
Redstone signal and pressure plates only opens one door.
I tried using only Forge, Optifine and Double Doors/Collective, but the problem persists.

*Update*
Regarding pressure plates: It seems that only 2 of the different pressure plates are not working: Light Weighted and Heavy Weighted. The other pressure plates (i.e. oak) do work as intended.

## **Screenshots**

Button used, double door is working:
![2022-02-23_13 53 21](https://user-images.githubusercontent.com/100205274/155324442-449af1c4-0422-4373-b149-34473e95c0d4.jpg)

Using pressure plate, double door is not working:
![2022-02-23_13 53 38](https://user-images.githubusercontent.com/100205274/155324549-eee503c5-f97b-4956-87a4-99853eb968b8.jpg)

Trapdoor using pressure plate, not working:
![2022-02-23_13 53 54](https://user-images.githubusercontent.com/100205274/155324653-d592949b-cf1a-4e6b-bd16-21915ebcc24a.jpg)

Redstone not working:
![2022-02-23_13 54 04](https://user-images.githubusercontent.com/100205274/155324751-bab465d0-afd8-4e71-adb6-91aae8175820.jpg)

Same for trapdoors:
![2022-02-23_13 54 13](https://user-images.githubusercontent.com/100205274/155324836-f1d8cafb-d57a-4305-bf40-88ff245a4398.jpg)

**Comment by ricksouth** [comment]
Thanks for giving the mod a try and opening the issue! I've fixed weighted plates not triggering double doors in version 3.3. I've not made a redstone signal a trigger on purpose, as it can mess with redstone contraptions. It's definitely possible to make a double door open with redstone, you'll just need to do it the vanilla way.

https://www.curseforge.com/minecraft/mc-mods/double-doors/files
