### ISSUE TITLE
Does not work on the server

### ISSUE THREAD

**Issue by fixsesh** [ricksouth/serilum-mc-mods#954]
## **Information**
Minecraft version:1.18.1
Modloader: Fabric
Fabric loader version: Sorry I do not know because I use tlauncher.
Environment: Multiplayer

Mod name: Easy Elytra Takeoff
Mod version: 2.2

## **Description**
The mod does not work on the server , I checked it works in single mode.
(sorry for my English, it's a translator, I just live in Russia.)

## **Crash report**
dont crash.

**Comment by ricksouth** [comment]
I've tested it to confirm and the mod does work in multiplayer. It does however need to be installed on the server, not just the client. Let me know if it was installed on the server as well and I can re-open the issue. Thanks for giving the mod a try.
