### ISSUE TITLE
Trap doors open/close rapidly when disabled

### ISSUE THREAD

**Issue by munzuradam** [ricksouth/serilum-mc-mods#956]
## **Information**
Minecraft version: 1.18.1
Modloader: Fabric
Fabric loader version: 0.13.1
Environment: Singleplayer

Mod name: Double Doors
Mod version: 3.1

## **Description**
Hey! When I make `"enableTrapdoors": false` trap doors opens and closes rapidly. That's it.

## **Crash report**
Doesn't crash.

**Comment by MiarKraiM** [comment]
I'm having this same issue though until this bug is fixed I have found a workaround, if you have both hands empty and shift click the trapdoor it will only change state once (if it was closed it will open and stay open and if it was open it will close and stay closed)

**Comment by chimericdream** [comment]
It looks like this is still an issue on Fabric 1.19. I decided to disable the extended trapdoors, but then realized none of my trapdoors were usable anymore. The workaround suggested by @MiarKraiM works, so I am still able to get in and out of places, but I wish I didn't have to have empty hands and hold shift every time I want to open or close a trapdoor.

**Comment by Echo343** [comment]
I'm seeing this issue on Forge 1.19 multiplayer server as well.

**Comment by dehen** [comment]
This also affects fence gates for me. Fabric 1.19.2

**Comment by Nerdtality** [comment]
Same for Fabric 1.19.3 for trapdoors and fencegates

**Comment by thimblebird** [comment]
it's for any "Enable X" option. any mod loader. none of them work.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 4+ of Double Doors.

https://www.curseforge.com/minecraft/mc-mods/double-doors/files
