### ISSUE TITLE
Does  NHAC affect performance?

### ISSUE THREAD

**Issue by Laifsyn** [ricksouth/serilum-mc-mods#958]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: xx.xx.xx
Modloader:Fabric
 Fabric loader version: 0.13.3
Environment:Multiplayer

Mod name: No Hostiles Around Campfire
Mod version: 1.18.1

## **Question**
How is the spawn negation proccessed? will a large number of campfires or huge radius affect the mspts/tps?
I was thinking something about like creating a "safe" stronghold, but if having a huge radius effect may affect the performance, I might just drop the idea(Realistically, an apart block ,let's say a command block or Structure Block is better to work as an anti spawn beacon instead a campfire that can be easily crafted/obtained)

**Comment by ricksouth** [comment]
All mod affect performance, but it shouldn't be that much of an issue. The mod saves online entities in a cache and whenever a hostile entity spawns it checks if the distance to a campfire is close enough to cancel the spawn. It **should** be fine but of course depends on other mods and circumstances.

Thanks for looking at the mod! :)
