### ISSUE TITLE
When the player is too far, the compass doesn't seem to work

### ISSUE THREAD

**Issue by BlueOpRed** [ricksouth/serilum-mc-mods#961]
## **Information**
Minecraft version: 1.16.5
Modloader: Forge
Forge version: How should i know 
Environment: Multiplayer Lan

Mod name: Serilum Compass mod
Mod version: Dunnno

## **DUDE HELP ME**
whenever a player is very far from the player who has a compass. The dam compass doesn't seem to work

## **Crash report**
i dunno if it is a crash, bug, or poor coding

**Comment by ricksouth** [comment]
Please run a local server via the official Forge server files instead. LAN multiplayer causes some weird mod interactions.

If the problem persists, I can do some debugging to find the cause.

**Comment by BlueOpRed** [comment]
> Please run a local server via the official Forge server files instead. LAN multiplayer causes some weird mod interactions.
> 
> If the problem persists, I can do some debugging to find the cause.
"Reply"
Sir, I still have the problem, I have ran a local server and nothing change, maybe because I use the 1.16.5 version. Can you try to update the 1.16.5 version of your mod? One more question, how did you make mods instead of using Mcreator.
