### ISSUE TITLE
Crash raport

### ISSUE THREAD

**Issue by toffi3** [ricksouth/serilum-mc-mods#963]
## **Information**
Minecraft version: 1.18.1
Modloader: Fabric
Fabric loader version: x.xx.x
Environment: Singleplayer 

Mod name: Mineral Chance
Mod version: Latest for 1.18

## **Description**
The game is crashing when mining dirt with a shovel

## **Crash report**
(https://pastebin.com/62Gn6HgA)

**Comment by ricksouth** [comment]
For 1.18.1 you need Collective version 4.9. The latest version is for 1.18.2. Thanks for giving the mod a try!

This one:
https://www.curseforge.com/minecraft/mc-mods/collective-fabric/files/3654799

**Comment by toffi3** [comment]
So i think it shouldn't have "1.18.X" in name, it should be "1.18.2" but okey, thanks for help!
