### ISSUE TITLE
Error message about "𝘪𝘯𝘤𝘰𝘳𝘳𝘦𝘤𝘵 𝘴𝘰𝘶𝘳𝘤𝘦" when downloaded from CurseForge

### ISSUE THREAD

**Issue by NatoBoram** [ricksouth/serilum-mc-mods#964]
## **Information**
Minecraft version: 1.18.2
Modloader: Fabric
Fabric loader version: 0.13.3-1.18.2
Environment: Singleplayer

Mod name: Collective
Mod version: `collective-fabric-1.18.x-4.13.jar`

Mod name: Easy Elytra Takeoff
Mod version: `easyelytratakeoff-fabric_1.18.x-2.2`

## **Description**

When downloading the mods from https://www.curseforge.com/minecraft/mc-mods/collective-fabric and https://www.curseforge.com/minecraft/mc-mods/easy-elytra-takeoff-fabric, it displays an error message about not being downloaded from the "correct" "source".

![2022-03-03_19 27 21](https://user-images.githubusercontent.com/10495562/156675940-952154a1-c37e-4554-aaae-6e5a112e24b7.png)

## ~~**Crash report**~~

**Comment by ricksouth** [comment]
Could you show me a screenshot of the /mods folder, with the jar file names?

**Comment by NatoBoram** [comment]
Heh, I figured out what happened.

Basically, you hard-coded `$pwd/mods` in [`getModDirectory`](https://github.com/ricksouth/serilum-mc-mods/blob/master/sources-fabric/Collective%20(Fabric)/src/main/java/com/natamus/collective_fabric/functions/DataFunctions.java#L36-L38) and you hard-coded the mod's name in [`jarname`](https://github.com/ricksouth/serilum-mc-mods/blob/master/sources/Collective/src/main/java/com/natamus/collective/check/RegisterMod.java#L41). You then use both of them to trip [`checkIfAllJarsExist`](https://github.com/ricksouth/serilum-mc-mods/blob/master/sources/Collective/src/main/java/com/natamus/collective/check/RegisterMod.java#L137-L142).

*Of course* it's not gonna work.

![image](https://user-images.githubusercontent.com/10495562/156678077-fd6d89b0-4b00-4095-a93e-51dd40871d45.png) ![image](https://user-images.githubusercontent.com/10495562/156678309-4612d118-100a-475b-ac8d-ef720a142d00.png)

**Comment by ricksouth** [comment]
It's a fragile system for sure, but an attempt to stop the hundreds of reposting sites. Thanks for the screenshot and I'll try to make it work for these cases!

For now you can either remove the check in the collective config, or keep it like this because the message won't show up again. Thanks for giving them a try, and downloading from CurseForge of course :)

**Comment by ricksouth** [comment]
Where did you change the mod directory folder? Or is this built in functionality?

**Comment by NatoBoram** [comment]
It's built-in with Fabric, but fairly hard to access. It's for modded client developers, so they can create separate Minecraft installation folders for every Minecraft version automatically.

* https://github.com/FabricMC/fabric-loader/pull/470#issuecomment-1028400603

Not a fan of this since the disadvantages of creating one installation per version outweighs having versionned, but at least there's a command-line argument to do what I want.

**Comment by ricksouth** [comment]
Thanks! I'll take a look at adding the functionality.

**Comment by ricksouth** [comment]
Could you update Collective to version 4.19 I just uploaded, delete the _./data/collective_ folder in your minecraft root folder and see if the message still shows up? It'd be much appreciated! It should not show up.

https://www.curseforge.com/minecraft/mc-mods/collective-fabric/files

**Comment by NatoBoram** [comment]
I noticed that your mod is the only one writing in `./data` out of my 26 mods. Can you use `./config` instead for this one? There's many mods writing in many places, and `data` makes it seem like it's something important related to Minecraft itself.

Also your config file uses JSONC but has the `.json` extension; it would be appropriate to rename it `.jsonc` to avoid confusion. JSON editors are not able to handle JSONC, so that distinction is important for users.

I just tested it and the message doesn't appear. Thanks!

**Comment by Swoofterkitty** [comment]
I just encountered this after updating to collective version 7.36, downloaded thru the curseforge launcher

**Comment by ricksouth** [comment]
> I just encountered this after updating to collective version 7.36, downloaded thru the curseforge launcher

Did you rename any of the mod files? Can you post a screenshot from your mods folder?

**Comment by Swoofterkitty** [comment]
Yeah I can, sorry for the delay
I did not rename any mods, all downloaded straight from curseforge.
![Mod help](https://github.com/Serilum/.issue-tracker/assets/105351053/3d4bed43-c179-4b0f-b9d3-4da9a267666d)

Here is the modpack exported


[Fuckshit TIME.zip](https://github.com/Serilum/.issue-tracker/files/14621838/Fuckshit.TIME.zip)

**Comment by ricksouth** [comment]
That's strange. Could you open a new issue for this? I'll try to take a look as soon as possible.
