### ISSUE TITLE
(Better Beacon Placement) Crash when placing beacon blocks

### ISSUE THREAD

**Issue by SirKrunk** [ricksouth/serilum-mc-mods#965]
## **Information**
Minecraft version: 1.18.1
Modloader: Fabric
Fabric loader version: 0.12.12
Environment: Singleplayer

Mod name: Better Beacon Placement
Mod version: betterbeaconplacement-fabric_1.18.x-1.4.jar

## **Description**
It says "server closed" when placing beacon blocks(diamond, iron, gold blocks)

## **Crash report**
https://pastebin.com/0eYF1Qmh

**Comment by ricksouth** [comment]
Please use Collective version 4.9 for Minecraft 1.18.1. I've released an update with better version syntax to warn other users in the future. If the problem persists, let me know. Thanks for giving the mod a try!

Collective version 4.9:
https://www.curseforge.com/minecraft/mc-mods/collective-fabric/files/3654799

**Comment by SirKrunk** [comment]
Its been fixed! Thank you!
