### ISSUE TITLE
Crash with Realistic Bees

### ISSUE THREAD

**Issue by ekiplier** [ricksouth/serilum-mc-mods#966]
## **Information**
Minecraft version: 1.16.5
Modloader: Forge
Forge version: 36.2.29
Environment: Singleplayer

Mod name: Realistic Bees
Mod version: 2.3

## **Description**
![signal-2022-03-04-210405_001](https://user-images.githubusercontent.com/74121461/156841302-5a2aa69e-2a91-4e2b-bad1-85e64794f08e.jpeg)
If it turns out that Realistic Bees isn't the issue I would really appreciate it if you could point me in the right direction. Thanks in advance :)

## **Crash report**
[crash-2022-03-03_18.58.06-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/8188750/crash-2022-03-03_18.58.06-server.txt)

**Comment by ricksouth** [comment]
Thanks for opening the issue and using the mod! I've just released Realistic Bees version 2.5 which should fix the problem you were having. Apologies for the inconvenience. It's also a lot more efficient and a beehive can now hold more bees, with a config value.

https://www.curseforge.com/minecraft/mc-mods/realistic-bees/files

**Comment by ekiplier** [comment]
Thank you! I'll definitely check it out :)

**Comment by ricksouth** [comment]
Seems like the CurseForge server had some issues but it's slowly catching up. The file should be available in half an hour or so!

**Comment by ekiplier** [comment]
Thanks, but I'll have to try it in a few hours as I'm not home atm. It'd be great if you could check out my modpack, Alar, where I'll be testing Realistic Bees later :)

**Comment by ekiplier** [comment]
It's very likely that some other mod there is conflicting with Realistic Bees, so it might be useful for assessing that

**Comment by ricksouth** [comment]
> Thanks, but I'll have to try it in a few hours as I'm not home atm. It'd be great if you could check out my modpack, Alar, where I'll be testing Realistic Bees later :)

Looks good! Glad some of my mods have been useful to you :)

> It's very likely that some other mod there is conflicting with Realistic Bees, so it might be useful for assessing that

It's indeed probably another mod that didn't like the interaction. But it should be fixed now. Thanks for taking a look at it
