### ISSUE TITLE
Fox Crash w/ Only Library Enabled

### ISSUE THREAD

**Issue by Master-64** [ricksouth/serilum-mc-mods#971]
## **Information**
Minecraft version: 1.18.1
Modloader: Fabric 
Fabric loader version: 0.13.3
Environment: Singleplayer

Mod name: Collective (Fabric)
Mod version: 4.8 (collective-fabric-1.18.x-4.8.jar)

## **Description**
A fox running around at night will cause a ClassCastException crash to desktop.

## **How to Replicate**

1. Load into any world (Default generation)
2. /difficulty peaceful
3. /gamerule doMobSpawning false
4. /gamerule keepInventory true
5. Locate to a Taiga biome (this step may not be required, but is what I did)
6. /spawnpoint
7. /kill @e (do this twice to erase all mobs from the world)
8. /time set night
9. Give yourself a fox spawn egg
10. Hold right click on a wall to spawn foxes for around 15 seconds (30 seconds to be the most consistent [this crash tends to be random from what I've seen])
11. Wait for roughly 5-60 seconds without moving (and without interacting with the foxes in any way)
12. Crash to desktop

## **Crash report**
Link: https://crashy.net/QyYhqLSdwOawyKlMNdPE
(used Crashy [through Not Enough Crashes] instead of a true crash report since it's much more clean and readable, but this exact crash happens without "Not Enough Crashes" enabled)

## **Additional Note**
The game version is 1.18.1 instead of 1.18.2. It's simply not an option for me to change to 1.18.2 because this is part of a mod pack (and roughly 10 or so of the mods require Collective to run [your mods are great!]). I've tested for a few hours in a lot of different scenarios and the crash would only occur with the Collective library mod enabled. Please let me know what the actual problem is though, since I'm still confused on it and why it occurs the way it does.

**Comment by ricksouth** [comment]
Glad some of my mods have been useful! :) Appreciate the replication steps. I believe this problem was fixed in Collective (Fabric) version 4.9. Could you give that a try?

https://www.curseforge.com/minecraft/mc-mods/collective-fabric/files/3654799

**Comment by Master-64** [comment]
Thanks for providing a direct link to the update! I wasn't too sure if 4.9 was safe since it was a beta file, but it does appear to fix the problem! Seems to be a duplicate of issue #590 as well, so it seems I was a bit late to the party. Thanks again! 👍

**Comment by ricksouth** [comment]
I've set the old 4.9 to release and uploaded an extra 4.9 as beta so it's double easier to find. Glad it works!

**Comment by ricksouth** [comment]
If only those foxes didn't eat so many berries it wouldn't have been a problem
