### ISSUE TITLE
Collective for 1.18.1 not working in 1.18.1 (???)

### ISSUE THREAD

**Issue by itsMarkiS** [ricksouth/serilum-mc-mods#972]
## **Information**
Minecraft version: 1.18.1
Modloader: Fabric
Fabric loader version: 0.13.3

Mod name: Collective
Mod version: 4.19 (1.18.1)

## **Description**
Collective mod listed for 1.18.1 doesnt truly works for 1.18.1
![image](https://user-images.githubusercontent.com/47507632/156937072-b35df1a2-0348-4b0e-af7a-3ecf5b2bafb6.png)

## **Crash report**
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Collective (Fabric)' (collective-fabric) 4.19 with version 4.19 or later that is compatible with:
		 - minecraft 1.18.1
Unmet dependency listing:
	 - Mod 'Collective (Fabric)' (collective-fabric) 4.19 requires version 1.18.2 or later of 'Minecraft' (minecraft), but only the wrong version is present: 1.18.1!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by ricksouth** [comment]
For 1.18.1 you'll need version 4.9: https://www.curseforge.com/minecraft/mc-mods/collective-fabric/files/3654799

I've tried to make it as easy to find as possible, in the description and file tags. This is due to changes made in 1.18.2.

**Comment by ricksouth** [comment]
I've added another pinned issue to make it easier for people to find here. Thanks for giving some of my mods a try!
