### ISSUE TITLE
Negative Durabilities

### ISSUE THREAD

**Issue by Syhlo** [ricksouth/serilum-mc-mods#974]
## **Information**
**Minecraft version:** 1.18.1
**Modloader:** Fabric
**Fabric loader version:** 0.13.3
**Environment:** Multiplayer

**Mod name:** Replanting Crops (Fabric)
**Mod version:** 2.5

## **Description**
Tested it with a stone and iron hoe, with only Replanting Crops installed, and when harvesting crops with a hoe this mod seems to be reducing the durability below 0 rather than breaking the item.

**Comment by ricksouth** [comment]
This has been fixed in version 4.0. Thanks for giving the mod a try and opening the issue!

https://www.curseforge.com/minecraft/mc-mods/replanting-crops-fabric
