### ISSUE TITLE
Tree Harvester 1.18.2 requires Collective (Forge) version 4.5

### ISSUE THREAD

**Issue by arthur633** [ricksouth/serilum-mc-mods#976]
## **Information**
Minecraft version: 1.18.2
Modloader: Forge
Forge version: 40.0.12
Environment: Singleplayer

Mod name: Tree Harvester
Mod version: FallingTree-1.18.2-0.0.1

## **Description**
The falling three causes this error mesage "Tree Harvester 1.18.2 requires Collective (Forge) version 4.5"

**Comment by ricksouth** [comment]
Have you installed the Collective library?

https://www.curseforge.com/minecraft/mc-mods/collective/files

**Comment by arthur633** [comment]
yea, but asks for 4.5 version that isn't available

**Comment by ricksouth** [comment]
Any version above that should work too.

Try to install the latest and launch again:
https://www.curseforge.com/minecraft/mc-mods/collective/files/3679826

**Comment by arthur633** [comment]
still does not work. I tried to start with collective and desactivate the tree harvester mod and the game starts and shows on mod tab. but when I activate the tree harvester mod again I got the same issue and the game doesn't start

**Comment by ricksouth** [comment]
Something about your installation isn't right. Are you using the curseforge launcher?

You've also referenced the FallingTree mod file but it's actually called treeharvester-...jar. Which version do you have?

**Comment by Caeyn** [comment]
This is the error I'm getting

"[Server] INFO - Mod 'Tree Harvester (Fabric)' (treeharvester-fabric) 5.0 requires version 4.25 or later of mod 'Collective (Fabric)' (collective-fabric), but only the wrong version is present: 4.24!"

4.24 is the highest version available on CF at the moment.

**Comment by ricksouth** [comment]
> This is the error I'm getting
> 
> "[Server] INFO - Mod 'Tree Harvester (Fabric)' (treeharvester-fabric) 5.0 requires version 4.25 or later of mod 'Collective (Fabric)' (collective-fabric), but only the wrong version is present: 4.24!"
> 
> 4.24 is the highest version available on CF at the moment.

Ahh that makes more sense. I forgot to upload 4.25 to CurseForge. Uploading right now!

**Comment by ricksouth** [comment]
I've uploaded Collective version 4.25. Should be available in a few minutes. Thanks for letting me know!

https://www.curseforge.com/minecraft/mc-mods/collective/files
https://www.curseforge.com/minecraft/mc-mods/collective-fabric/files
