### ISSUE TITLE
Cutting speed not configurable on 1.18.1 release

### ISSUE THREAD

**Issue by Some-Doofus** [ricksouth/serilum-mc-mods#977]
I have noticed the config file does not have the option to change the speed multiplier per block when chopping a tree on the 1.18.1 - 4.1 release and by default all trees break at the speed of 1 block regardless of the size of the tree. I'm sure the 1.18.2 version fixes this but most of my mods are not updated to that yet. Is it possible for this to be fixed for this game version?

**Comment by ricksouth** [comment]
This is indeed only available in the 1.18.2 version. I focus on the latest sub versions. At the moment including fabric I've got 7 versions to update mods for. I have to let some versions go. Whenever you can, upgrade to 1.18.2 to have the feature. Thanks for the interest!
