### ISSUE TITLE
Realistic bees in distance invisible?

### ISSUE THREAD

**Issue by agentwolf88** [ricksouth/serilum-mc-mods#978]
Is it a bug that the bees in distance invisible?

**Comment by ricksouth** [comment]
I have not changed the default Minecraft behaviour on rendering entities. You should be able to change the video settings to set how far in the distance entities should be visible. Thanks for giving the mod a try!

**Comment by agentwolf88** [comment]
Look at this video. Only realistic bees is installed.

https://youtu.be/LqZFlvASDBE

**Comment by Polarni** [comment]
I have same issue like on video (1.19.2 - Forge 43.3.0). Bees disappear near the player. Without the mode, they render as far away as other animals.
