### ISSUE TITLE
[Suggestion] Compatiblity with Minecraft Comes Alive Reborn

### ISSUE THREAD

**Issue by novorow** [ricksouth/serilum-mc-mods#979]
## **Information**
Mod name: Villager Names

## **Feature description**
The names of the villagers will appear instead of Male or Female Villager, and
custom names of course

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been added in version 6.0 of Villager Names and version 6.80 of Collective. :) Apologies it took so long for me to get to.

https://legacy.curseforge.com/minecraft/mc-mods/villager-names/files
https://legacy.curseforge.com/minecraft/mc-mods/collective/files
