### ISSUE TITLE
Causes Shockbyte Server To Crash

### ISSUE THREAD

**Issue by mahjutsu** [ricksouth/serilum-mc-mods#982]
## **Information**
Minecraft version: 1.18.1
Modloader: Forge
Forge version: 1.18.1 - 39.0.66
Environment: Multiplayer

Mod name: Surface Mushrooms (Forge)
Mod version: 1-1.2

## **Description**
When I installed this mod to my server, it caused my server to crash when restarting. Once I removed the mod, the server restarted successfully.

**Comment by James103** [comment]
1. Do you have the crash report? If so, can you please post it here?
2. Have you tried reproducing in a fresh server with only Minecraft 1.18.1, Forge 39.0.66, Collective (latest compatible version for 1.18.1), and Surface Mushrooms? If this crashes, can you please post the resulting crash report?

**Comment by ricksouth** [comment]
Please update to the latest version (1.4) which has been completely rewritten and should fix the problems you were having.
