### ISSUE TITLE
(Fabric) GUIClock: Time doesn't appear when clock is held in the offhand

### ISSUE THREAD

**Issue by Dejeh** [ricksouth/serilum-mc-mods#983]
## **Information**
Minecraft version: 1.18.1
Modloader: Fabric
Fabric loader version: 0.13.3

Mod name: GUIClock
Mod version: 3.0

## **Description**
Time doesn't show when clock is in offhand

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in the latest version of GUI Clock.

https://www.curseforge.com/minecraft/mc-mods/gui-clock-fabric-version/
