### ISSUE TITLE
easy takeoff doesn't work when elytra is dyed using customizable elytra mod

### ISSUE THREAD

**Issue by Jadan1213** [ricksouth/serilum-mc-mods#984]
## **Information**
Minecraft version: 1.18.1
Modloader: Forge 
Forge version: 39.1.0
Environment: Multiplayer

Mod name: easy elytra takeoff
Mod version: 1.18.1-2.2

## **Description**
After dying an elytra using the customizable elytra mod, easy takeoff no longer works.

**Comment by ricksouth** [comment]
Thanks for using the mod! I've just tested it, and it does work. As they extend the ElytraItem, which the code checks for, it should also work in theory. Could you try again, and if it still doesn't work, send the mod list?

**Comment by Jadan1213** [comment]
It does not currently work in my game. The only difference is the coloring on my elytra. To try it again, I colored another elytra and tried it.
[client_mods.txt](https://github.com/ricksouth/serilum-mc-mods/files/8256532/client_mods.txt)
[server_mods.txt](https://github.com/ricksouth/serilum-mc-mods/files/8256533/server_mods.txt)

**Comment by ricksouth** [comment]
This should be fixed in version 3.0 of Easy Elytra Takeoff. I've changed a lot of the code. Thanks for giving the mod a try!

https://www.curseforge.com/minecraft/mc-mods/easy-elytra-takeoff
