### ISSUE TITLE
Quick Paths mod no longer on the website.

### ISSUE THREAD

**Issue by RedAISkye** [ricksouth/serilum-mc-mods#985]
## **Information**
Mod name: **Quick Paths**

## **Question**
I can no longer find this mod in your **[website](https://minecraft.natamus.com)**, what happened? (_I didn't manually check, only tried searching terms like "quick, path, paths, quick path, quick paths, quickpath, quickpaths" which all came with 0 results_)

It is listed in **[CurseForge](https://www.curseforge.com/minecraft/mc-mods/quick-paths)** site though.

**Comment by James103** [comment]
The mod is listed on the overview and accessible there but only until you modify the search query (such as by pressing "Select All"), at which point the mod is hidden in the overview until the page is reloaded.

**Comment by RedAISkye** [comment]
> The mod is listed on the overview and accessible there but only until you modify the search query (such as by pressing "Select All"), at which point the mod is hidden in the overview until the page is reloaded.

So, it's an issue with the search function then?

**Comment by ricksouth** [comment]
Since the mod overview has been moved to https://serilum.com/, this has been fixed. Thanks for submitting the issue!
