### ISSUE TITLE
Not working on forge server

### ISSUE THREAD

**Issue by Anonymaru-tv** [ricksouth/serilum-mc-mods#986]
## **Information**
Minecraft version: 1.18.2
Modloader: Forge
Forge version: 40.0.12 
Environment: Multiplayer

Mod name: TreeHarvester
Mod version: 1.18.2-5.0

## **Description**
Does nothing on my server. It does a longer breakdown but not breaking all logs.

My modlist:
TreeHarvest
Collective
Enhanced farming
Just enough items
Oh biomes you'll go
Quick harvest
Terrablender

**Comment by ricksouth** [comment]
It does work for me in my server. What trees are you trying to break? Do you have images/gifs available?

**Comment by ricksouth** [comment]
Is the mod installed on the server?

**Comment by KingBarker** [comment]
Doesnt work for me on 1.18 server either

**Comment by ricksouth** [comment]
Can you try the latest version of Tree Harvester? If that doesn't work, please open another issue with your modlist included. Thanks for giving the mod a try!
