### ISSUE TITLE
"Replace mod 'Collective (Fabric)' (collective-fabric) 4.9 with version 4.25 or later" on 1.18.1

### ISSUE THREAD

**Issue by Th3600** [ricksouth/serilum-mc-mods#989]
## **Information**
Minecraft version: 1.18.1
Modloader: Fabric
Fabric loader version: 0.13.3
Environment: Initialization
Using MultiMC

Mod name: Collective (I think)
Mod version: 4.9

## **Description**
When I start Fabric (1.18.1) on MultiMC, it crashes and says that some mods need collective 4.25+, but in CurseForge it says that 4.9 is the correct version to be used with 1.18.1.

## **Crash report**
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Collective (Fabric)' (collective-fabric) 4.9 with version 4.25 or later.
Unmet dependency listing:
	 - Mod 'Better Spawner Control (Fabric)' (betterspawnercontrol-fabric) 1.6 requires version 4.12 or later of mod 'Collective (Fabric)' (collective-fabric), but only the wrong version is present: 4.9!
	 - Mod 'Double Doors (Fabric)' (doubledoors-fabric) 3.3 requires version 4.19 or later of mod 'Collective (Fabric)' (collective-fabric), but only the wrong version is present: 4.9!
	 - Mod 'Furnace Recycle (Fabric)' (furnacerecycle-fabric) 1.2 requires version 4.12 or later of mod 'Collective (Fabric)' (collective-fabric), but only the wrong version is present: 4.9!
	 - Mod 'Hoe Tweaks (Fabric)' (hoetweaks-fabric) 1.4 requires version 4.22 or later of mod 'Collective (Fabric)' (collective-fabric), but only the wrong version is present: 4.9!
	 - Mod 'Just Mob Heads (Fabric)' (justmobheads-fabric) 5.4 requires version 4.22 or later of mod 'Collective (Fabric)' (collective-fabric), but only the wrong version is present: 4.9!
	 - Mod 'Nether Portal Spread (Fabric)' (netherportalspread-fabric) 5.7 requires version 4.12 or later of mod 'Collective (Fabric)' (collective-fabric), but only the wrong version is present: 4.9!
	 - Mod 'Passive Shield (Fabric)' (passiveshield-fabric) 2.0 requires version 4.18 or later of mod 'Collective (Fabric)' (collective-fabric), but only the wrong version is present: 4.9!
	 - Mod 'Surface Mushrooms (Fabric)' (surfacemushrooms-fabric) 1.4 requires version 4.22 or later of mod 'Collective (Fabric)' (collective-fabric), but only the wrong version is present: 4.9!
	 - Mod 'Tree Harvester (Fabric)' (treeharvester-fabric) 5.0 requires version 4.25 or later of mod 'Collective (Fabric)' (collective-fabric), but only the wrong version is present: 4.9!
	 - Mod 'Wool Tweaks (Fabric)' (wooltweaks-fabric) 1.5 requires version 4.12 or later of mod 'Collective (Fabric)' (collective-fabric), but only the wrong version is present: 4.9!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Comment by ricksouth** [comment]
Are you using the CurseForge launcher? All files are correctly tagged. For 1.18.1 you'll need a version older for those mods. For example for tree harvester 4.1: https://www.curseforge.com/minecraft/mc-mods/tree-harvester-fabric/files/3542092.

I know it's a bit of a hassle, apologies for the inconvenience. My fabric naming isn't well set up for different code bases in sub versions (1.18.1 -> 1.18.2). Usually the code is the same.

It's because I've added new code to Collective, but I only have 1.18.2 in my dev environment. I already have to upload 4 files now, having 1.18.1 active means another upload and code management.
