### ISSUE TITLE
Tree Harvester (Fabric)

### ISSUE THREAD

**Issue by wsesrdtf** [ricksouth/serilum-mc-mods#990]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.18.2
Modloader: Fabric
Fabric loader version: 0.13.3
Environment: Singleplayer

Mod name: Tree Harvester (Fabric)
Mod version: 1.18.x-5.1

fabric-api-0.48.0+1.18.2.jar
collective-fabric-1.18.x-4.25.jar
treeharvester-fabric_1.18.x-5.1.jar

## **Question**

{
	// If enabled, tree harvesting only works when a player is holding an axe in the main hand.
	"mustHoldAxeForTreeHarvest": false,
	// If enabled, tree harvesting works when not holding the sneak button. If disabled it's reversed, and only works when sneaking.
	"treeHarvestWithoutSneak": true,
	// If enabled, players instantly break the leaves as well as all logs of the tree when a bottom log is broken.
	"instantBreakLeavesAround": false,
	// Whether the mod should attempt to find the actual bottom log of the tree and start there. This means you can break a tree in the middle and it will still completely be felled.
	"automaticallyFindBottomBlock": false,
	// If enabled, the leaves around a broken tree will quickly disappear. Only works with 'instantBreakLeavesAround' disabled.
	"enableFastLeafDecay": true,
	// If enabled, the warped stem/crimson trees in the nether will also be chopped down quickly.
	"enableNetherTrees": true,
	// If enabled, giant/huge mushrooms will also be chopped down quickly.
	"enableHugeMushrooms": true,
	// If enabled, automatically replaces the sapling from the drops when a tree is harvested.
	"replaceSaplingOnTreeHarvest": false,
	// If enabled, automatically replaces the sapling from the drops when a huge mushroom is harvested and 'enableHugeMushrooms' is enabled.
	"replaceMushroomOnMushroomHarvest": false,
	// If enabled, for every log harvested, the axe held loses durability.
	"loseDurabilityPerHarvestedLog": true,
	// Here you can set how much durability chopping down a tree should take from the axe. For example if set to 0.1, this means that every 10 logs take 1 durability.
	"loseDurabilityModifier": 1.0,
	// If enabled, players' exhaustion level increases 0.005 per harvested log (Minecraft's default per broken block) * increaseExhaustionModifier.
	"increaseExhaustionPerHarvestedLog": true,
	// This determines how much exhaustion should be added to the player per harvested log. By default 0.005 * 1.0.
	"increaseExhaustionModifier": 1.0,
	// If enabled, harvesting time will increase per existing log in the tree. The amount is determined by 'increasedHarvestingTimePerLogModifier'.
	"increaseHarvestingTimePerLog": true,
	// How much longer it takes to harvest a tree with 'increaseHarvestingTimePerLog' enabled. The actual speed is: newSpeed = originalSpeed / (1 + (logCount * increasedHarvestingTimePerLogModifier)).
	"increasedHarvestingTimePerLogModifier": 0.5,
	// How many leaves should be broken per tick after a tree has been harvested. Increasing this will speed up the fast leaf decay, but costs more processing power per tick.
	"amountOfLeavesBrokenPerTick": 3
}

https://user-images.githubusercontent.com/101512862/158330477-295225e8-7149-48bf-a859-bc748a140505.mp4

As in the attached video, 
if try to cut down the remaining bottom after cutting upper part, 
the mod function does not work.
Can this be improved?

https://user-images.githubusercontent.com/101512862/158334012-10bb8e76-1907-4d13-ada7-b829c7d73356.mp4

And there is no difference in time between felling a very large tree and a small tree.
Even if you compare it with a single block.
I wonder if something is wrong with my config settings.

**Comment by ricksouth** [comment]
The mod has to detect whether the tree broken is an actual tree, and not for example part of a building. It unfortunately doesn't work with just log blocks on top of each other.

The harvesting speed seems like a bug, I'll leave this open and take a look soon. Thanks!

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 6.48 of Collective. Tree Harvester doesn't need an update. Apologies it took so long to get to.

https://www.curseforge.com/minecraft/mc-mods/collective/files
