### ISSUE TITLE
Healing Campfire (Fabric)

### ISSUE THREAD

**Issue by wsesrdtf** [ricksouth/serilum-mc-mods#991]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.18.2
Modloader: Fabric
Fabric loader version: 0.13.3
Environment: Singleplayer

Mod name: Healing Campfire (Fabric)
Mod version: 1.18.x-3.3

fabric-api-0.48.0+1.18.2.jar
collective-fabric-1.18.x-4.25.jar
healingcampfire-fabric_1.18.x-3.3.jar

## **Question**

{
	// How often in ticks the mod checks for campfires around the player. 1 second = 20 ticks, so by default every 2 seconds.
	"checkForCampfireDelayInTicks": 200,
	// The radius around the campfire in blocks where players receive the regeneration effect.
	"healingRadius": 3,
	// The duration of the regeneration effect which the campfire applies.
	"effectDurationSeconds": 10,
	// The level of regeneration which the campfire applies, by default 1.
	"regenerationLevel": 1,
	// When enabled, the campfire heals passive mobs around where the radius is half the width of a bounding box.
	"healPassiveMobs": true,
	// When enabled, hides the particles from the regeneration effect around the campfire.
	"hideEffectParticles": false,
	// When enabled, the campfire only has an effect when the block is lit up.
	"campfireMustBeLit": true,
	// When enabled, the campfire only has an effect when the block is signalling.
	"campfireMustBeSignalling": false,
	// When enabled, the mod will work with normal campfires.
	"enableEffectForNormalCampfires": true,
	// When enabled, the mod will work with soul campfires.
	"enableEffectForSoulCampfires": true
}

Does the "checkForCampfireDelayInTicks" option count as delay cycles from 0 ticks in world time, 
rather than counting ticks after the player reaches campfire range?

As for why I question this,
Sometimes, regeneration starts as soon as I approach the healingRadius, and sometimes it doesn't even start after 10 seconds.

So I did an experiment. 
Once regeneration is activated, wait 15 seconds outside the healingRadius and approach the healingRadius again, then I receive the regeneration effect in 5 seconds.

I would like to apply the delay to ticks after reaching healingRadius, not "checkForCampfireDelayInTicks", which is calculated based on ticks in the world. Is this possible?

**Comment by ricksouth** [comment]
Thanks for the interest! The delay is there to prevent the mod from using too much processing power. If it would have to start when reaching the radius, it would have to check almost every tick. You can accomplish this, by setting 'checkForCampfireDelayInTicks' to 5 or so.

**Comment by wsesrdtf** [comment]
So it's hard to get a regeneration effect exactly 10 seconds after the player approaches the campfire healingRadius?
