### ISSUE TITLE
Passive Endermen newest fix for 1.18.1 Forge

### ISSUE THREAD

**Issue by Auuki** [ricksouth/serilum-mc-mods#996]
## **Question**
I was about to report the bug with Endermen still being able to pick up the blocks so I'm glad you've fixed that, however I was wondering if it would be possible to fix it in 1.18.1 Forge version as well as a last update?

**Comment by ricksouth** [comment]
Definitely a little late, apologies. I always develop with the latest version, as it's not feasible to keep the other dev environments active. Thanks for the interest though!
