### ISSUE TITLE
Offhand Slot doesn't get refilled

### ISSUE THREAD

**Issue by vanGrunz** [ricksouth/serilum-mc-mods#997]
## **Information**
Minecraft version: 1.15.2
Modloader: Forge
Forge version: 31.2.50
Environment: Singleplayer / Multiplayer

Mod name: Stack Refill
Mod version: 1.7

## **Description**
Spreading hundreds of thousand of torches around to prevent monster spawning requires a sword in the main hand while placing torches via right click from the offhand slot. Once completely consumed, it doesn't get refilled, even having some stacks of torches in my inventory.

Same problem with other blocks like Stone Bricks: placing them from the offhand slot and having a pickaxe in the main hand for a quick correction of misplaced blocks forces a manual refill.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! Apologies this took so long for me to get to. This has been fixed in version 3.0 of Stack Refill.

https://www.curseforge.com/minecraft/mc-mods/stack-refill
