### ISSUE TITLE
In-world wool dyeing only works on certain sides of the block

### ISSUE THREAD

**Issue by mariberry-hearn** [ricksouth/serilum-mc-mods#998]
## **Information**
Minecraft version: 1.18.2
Modloader: Fabric
Fabric loader version: 0.13.2-1.18.2
Environment: Singleplayer

Mod name: Wool Tweaks
Mod version: 1.5

## **Description**
I recently added the Wool Tweaks mod to my personal pack and was playing around with its features.
I tried to dye a block of wool but noticed that it doesn't seem to work. After much confusion and testing, I found out that you can only dye wool blocks from the east, south, and bottom sides.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 2.2 of Wool Tweaks.

https://www.curseforge.com/minecraft/mc-mods/wool-tweaks-fabric
